package com.acme.opsweave.platform.persistence;
import java.time.Instant;
import com.acme.opsweave.integration.domain.WorkflowMetricReplay;
import com.acme.opsweave.integration.domain.WorkflowLogReplay;
import com.acme.opsweave.platform.workflow.WorkflowMetricReplayJson;
import com.acme.opsweave.platform.workflow.WorkflowLogReplayJson;
import com.acme.opsweave.integration.api.WorkflowStore;
import com.acme.opsweave.platform.workflow.WorkflowJson;
import com.acme.opsweave.platform.workflow.SourceSetupJson;
import com.acme.opsweave.integration.domain.SourceSetup;
import com.acme.opsweave.integration.domain.WorkflowMetricStream;
import com.acme.opsweave.integration.domain.WorkflowLogStream;
import com.acme.opsweave.integration.domain.WorkflowHostSchedule;
import com.acme.opsweave.platform.workflow.WorkflowHostScheduleJson;
import com.acme.opsweave.platform.workflow.WorkflowMetricStreamJson;
import com.acme.opsweave.platform.workflow.WorkflowLogStreamJson;
import com.acme.opsweave.platform.workflow.WorkflowDiagnosticsJson;
import com.acme.opsweave.integration.domain.WorkflowDiagnostics;
import com.acme.opsweave.integration.domain.WorkflowRecovery;
import com.acme.opsweave.integration.domain.WorkflowTaskArchive;
import com.acme.opsweave.integration.domain.WorkflowSampleRecovery;
import com.acme.opsweave.integration.domain.WorkflowQualityAlerts;
import com.acme.opsweave.integration.domain.WorkflowHistory;
import com.acme.opsweave.integration.domain.WorkflowQuality;
import com.acme.opsweave.platform.workflow.WorkflowQualityAlertsJson;
import com.acme.opsweave.platform.workflow.WorkflowSampleRecoveryJson;
import com.acme.opsweave.platform.workflow.WorkflowTaskArchiveJson;
import com.acme.opsweave.platform.workflow.WorkflowRecoveryJson;
import com.acme.opsweave.platform.workflow.WorkflowHostScanJson;
import com.acme.opsweave.integration.domain.SourceInstance;
import com.acme.opsweave.platform.workflow.SourceInstanceJson;
import com.acme.opsweave.integration.domain.SourceInspection;
import com.acme.opsweave.integration.domain.SourceCredential;
import com.acme.opsweave.integration.domain.SourceConnectionConfiguration;
import com.acme.opsweave.platform.workflow.SourceConnectionJson;
import com.acme.opsweave.platform.workflow.SourceCredentialJson;
import com.acme.opsweave.platform.workflow.SourceInspectionJson;
import com.acme.opsweave.platform.catalog.CatalogJson;
import com.acme.opsweave.sharedkernel.TenantId;
import javax.sql.DataSource;
import java.sql.*;
import java.util.*;

final class PostgresWorkflowStore implements WorkflowStore {
 private final DataSource source;
 PostgresWorkflowStore(DataSource source){this.source=source;}
 public <T>T transaction(TenantId tenant,Work<T> work){
  try(var c=source.getConnection()){c.setAutoCommit(false);try{
   try(var s=c.prepareStatement("SELECT pg_advisory_xact_lock(hashtextextended(?,0))")){s.setQueryTimeout(5);s.setString(1,"transform-workflow:"+tenant.value());s.execute();}
   T result=work.apply(new Jdbc(c,tenant.value()));c.commit();return result;
  }catch(RuntimeException|SQLException failure){c.rollback();throw failure;}}
  catch(SQLException failure){throw unavailable();}
 }
 private record Jdbc(Connection connection,String tenant) implements Session {
  public Optional<WorkflowLogReplay.Plan> logReplayPlan(String owner,UUID id){try(var q=prepare("SELECT workflow_id,revision,body,created_at FROM integration.workflow_log_replay_plan WHERE tenant_id=? AND owner_subject=? AND request_id=?",tenant,owner,id);var row=q.executeQuery()){if(!row.next())return Optional.empty();var p=WorkflowLogReplayJson.plan(row.getString("body"));if(!id.equals(p.requestId())||!p.reference().id().equals(row.getString("workflow_id"))||p.reference().revision()!=row.getInt("revision")||!p.createdAt().equals(row.getTimestamp("created_at").toInstant()))throw unavailable();return Optional.of(p);}catch(SQLException|IllegalArgumentException invalid){throw unavailable();}}
  public List<WorkflowLogReplay.Plan> logReplayPlans(String owner,WorkflowQuality.Reference ref){try(var q=prepare("SELECT request_id FROM integration.workflow_log_replay_plan WHERE tenant_id=? AND owner_subject=? AND workflow_id=? AND revision=? ORDER BY created_at DESC,request_id LIMIT 21",tenant,owner,ref.id(),ref.revision());var row=q.executeQuery()){var rows=new ArrayList<WorkflowLogReplay.Plan>();while(row.next()){var p=logReplayPlan(owner,row.getObject("request_id",UUID.class)).orElseThrow();if(!p.reference().equals(ref))throw unavailable();rows.add(p);}return List.copyOf(rows);}catch(SQLException|IllegalArgumentException invalid){throw unavailable();}}
  public int logReplayPlanCount(String owner){try(var q=prepare("SELECT count(*) FROM integration.workflow_log_replay_plan WHERE tenant_id=? AND owner_subject=?",tenant,owner);var row=q.executeQuery()){row.next();return row.getInt(1);}catch(SQLException invalid){throw unavailable();}}
  public void addLogReplayPlan(String owner,WorkflowLogReplay.Plan p){var e=published(p.reference().id(),p.reference().revision()).orElseThrow();if(!p.state().equals("PREPARING")||!e.digest().equals(p.reference().digest())||logReplayPlanCount(owner)>=200)throw unavailable();update("INSERT INTO integration.workflow_log_replay_plan(tenant_id,owner_subject,request_id,workflow_id,revision,body,created_at) VALUES (?,?,?,?,?,?::jsonb,?)",tenant,owner,p.requestId(),p.reference().id(),p.reference().revision(),CatalogJson.JSON.writeValueAsString(p),Timestamp.from(p.createdAt()));}
  public void finishLogReplayPlan(String owner,WorkflowLogReplay.Plan p){logReplayPlan(owner,p.requestId()).orElseThrow().requireSuccessor(p);update("UPDATE integration.workflow_log_replay_plan SET body=?::jsonb WHERE tenant_id=? AND owner_subject=? AND request_id=?",CatalogJson.JSON.writeValueAsString(p),tenant,owner,p.requestId());}
  public Optional<WorkflowLogReplay.Receipt> logReplayReceipt(String owner,UUID id){try(var q=prepare("SELECT plan_id,body,accepted_at FROM integration.workflow_log_replay_receipt WHERE tenant_id=? AND owner_subject=? AND request_id=?",tenant,owner,id);var row=q.executeQuery()){if(!row.next())return Optional.empty();var r=WorkflowLogReplayJson.receipt(row.getString("body"));var p=logReplayPlan(owner,r.planId()).orElseThrow();if(!id.equals(r.requestId())||!r.planId().equals(row.getObject("plan_id",UUID.class))||!r.reference().equals(p.reference())||!r.acceptedAt().equals(row.getTimestamp("accepted_at").toInstant())||!r.commandDigest().equals(new WorkflowLogReplay.Execute(r.requestId(),p.requestId(),p.proof().inputDigest(),p.proof().batchDigest()).commandDigest()))throw unavailable();return Optional.of(r);}catch(SQLException|IllegalArgumentException invalid){throw unavailable();}}
  public Optional<WorkflowLogReplay.Receipt> logReplayReceiptForPlan(String owner,UUID id){try(var q=prepare("SELECT request_id FROM integration.workflow_log_replay_receipt WHERE tenant_id=? AND owner_subject=? AND plan_id=?",tenant,owner,id);var row=q.executeQuery()){return row.next()?logReplayReceipt(owner,row.getObject("request_id",UUID.class)):Optional.empty();}catch(SQLException invalid){throw unavailable();}}
  public void addLogReplayReceipt(String owner,WorkflowLogReplay.Receipt r){var p=logReplayPlan(owner,r.planId()).orElseThrow();if(!r.state().equals("PENDING")||!r.reference().equals(p.reference())||!r.commandDigest().equals(new WorkflowLogReplay.Execute(r.requestId(),p.requestId(),p.proof().inputDigest(),p.proof().batchDigest()).commandDigest()))throw unavailable();update("INSERT INTO integration.workflow_log_replay_receipt(tenant_id,owner_subject,request_id,plan_id,body,accepted_at) VALUES (?,?,?,?,?::jsonb,?)",tenant,owner,r.requestId(),r.planId(),CatalogJson.JSON.writeValueAsString(r),Timestamp.from(r.acceptedAt()));}
  public void finishLogReplayReceipt(String owner,WorkflowLogReplay.Receipt r){logReplayReceipt(owner,r.requestId()).orElseThrow().requireSuccessor(r);update("UPDATE integration.workflow_log_replay_receipt SET body=?::jsonb WHERE tenant_id=? AND owner_subject=? AND request_id=?",CatalogJson.JSON.writeValueAsString(r),tenant,owner,r.requestId());}
  public Optional<WorkflowMetricReplay.Plan> metricReplayPlan(String owner,UUID id){try(var q=prepare("SELECT workflow_id,revision,body,created_at FROM integration.workflow_metric_replay_plan WHERE tenant_id=? AND owner_subject=? AND request_id=?",tenant,owner,id);var row=q.executeQuery()){if(!row.next())return Optional.empty();var p=WorkflowMetricReplayJson.plan(row.getString("body"));if(!id.equals(p.requestId())||!p.reference().id().equals(row.getString("workflow_id"))||p.reference().revision()!=row.getInt("revision")||!p.createdAt().equals(row.getTimestamp("created_at").toInstant()))throw unavailable();return Optional.of(p);}catch(SQLException|IllegalArgumentException invalid){throw unavailable();}}
  public List<WorkflowMetricReplay.Plan> metricReplayPlans(String owner,WorkflowQuality.Reference ref){try(var q=prepare("SELECT request_id FROM integration.workflow_metric_replay_plan WHERE tenant_id=? AND owner_subject=? AND workflow_id=? AND revision=? ORDER BY created_at DESC,request_id LIMIT 21",tenant,owner,ref.id(),ref.revision());var row=q.executeQuery()){var rows=new ArrayList<WorkflowMetricReplay.Plan>();while(row.next()){var p=metricReplayPlan(owner,row.getObject("request_id",UUID.class)).orElseThrow();if(!p.reference().equals(ref))throw unavailable();rows.add(p);}return List.copyOf(rows);}catch(SQLException|IllegalArgumentException invalid){throw unavailable();}}
  public int metricReplayPlanCount(String owner){try(var q=prepare("SELECT count(*) FROM integration.workflow_metric_replay_plan WHERE tenant_id=? AND owner_subject=?",tenant,owner);var row=q.executeQuery()){row.next();return row.getInt(1);}catch(SQLException invalid){throw unavailable();}}
  public void addMetricReplayPlan(String owner,WorkflowMetricReplay.Plan p){var e=published(p.reference().id(),p.reference().revision()).orElseThrow();if(!p.state().equals("PREPARING")||!e.digest().equals(p.reference().digest())||metricReplayPlanCount(owner)>=200)throw unavailable();update("INSERT INTO integration.workflow_metric_replay_plan(tenant_id,owner_subject,request_id,workflow_id,revision,body,created_at) VALUES (?,?,?,?,?,?::jsonb,?)",tenant,owner,p.requestId(),p.reference().id(),p.reference().revision(),CatalogJson.JSON.writeValueAsString(p),Timestamp.from(p.createdAt()));}
  public void finishMetricReplayPlan(String owner,WorkflowMetricReplay.Plan p){metricReplayPlan(owner,p.requestId()).orElseThrow().requireSuccessor(p);update("UPDATE integration.workflow_metric_replay_plan SET body=?::jsonb WHERE tenant_id=? AND owner_subject=? AND request_id=?",CatalogJson.JSON.writeValueAsString(p),tenant,owner,p.requestId());}
  public Optional<WorkflowMetricReplay.Receipt> metricReplayReceipt(String owner,UUID id){try(var q=prepare("SELECT plan_id,body,accepted_at FROM integration.workflow_metric_replay_receipt WHERE tenant_id=? AND owner_subject=? AND request_id=?",tenant,owner,id);var row=q.executeQuery()){if(!row.next())return Optional.empty();var r=WorkflowMetricReplayJson.receipt(row.getString("body"));var p=metricReplayPlan(owner,r.planId()).orElseThrow();if(!id.equals(r.requestId())||!r.planId().equals(row.getObject("plan_id",UUID.class))||!r.reference().equals(p.reference())||!r.acceptedAt().equals(row.getTimestamp("accepted_at").toInstant())||!r.commandDigest().equals(new WorkflowMetricReplay.Execute(r.requestId(),p.requestId(),p.proof().inputDigest(),p.proof().batchDigest()).commandDigest()))throw unavailable();return Optional.of(r);}catch(SQLException|IllegalArgumentException invalid){throw unavailable();}}
  public Optional<WorkflowMetricReplay.Receipt> metricReplayReceiptForPlan(String owner,UUID id){try(var q=prepare("SELECT request_id FROM integration.workflow_metric_replay_receipt WHERE tenant_id=? AND owner_subject=? AND plan_id=?",tenant,owner,id);var row=q.executeQuery()){return row.next()?metricReplayReceipt(owner,row.getObject("request_id",UUID.class)):Optional.empty();}catch(SQLException invalid){throw unavailable();}}
  public void addMetricReplayReceipt(String owner,WorkflowMetricReplay.Receipt r){var p=metricReplayPlan(owner,r.planId()).orElseThrow();if(!r.state().equals("PENDING")||!r.reference().equals(p.reference())||!r.commandDigest().equals(new WorkflowMetricReplay.Execute(r.requestId(),p.requestId(),p.proof().inputDigest(),p.proof().batchDigest()).commandDigest()))throw unavailable();update("INSERT INTO integration.workflow_metric_replay_receipt(tenant_id,owner_subject,request_id,plan_id,body,accepted_at) VALUES (?,?,?,?,?::jsonb,?)",tenant,owner,r.requestId(),r.planId(),CatalogJson.JSON.writeValueAsString(r),Timestamp.from(r.acceptedAt()));}
  public void finishMetricReplayReceipt(String owner,WorkflowMetricReplay.Receipt r){metricReplayReceipt(owner,r.requestId()).orElseThrow().requireSuccessor(r);update("UPDATE integration.workflow_metric_replay_receipt SET body=?::jsonb WHERE tenant_id=? AND owner_subject=? AND request_id=?",CatalogJson.JSON.writeValueAsString(r),tenant,owner,r.requestId());}

  private WorkflowHistory.Row historyRow(ResultSet row)throws SQLException{var v=WorkflowDiagnosticsJson.decode(row.getString("body"));var o=v.observation();if(!o.id().equals(row.getObject("observation_id",UUID.class))||!o.reference().id().equals(row.getString("workflow_id"))||o.reference().revision()!=row.getInt("revision")||!o.completedAt().equals(row.getTimestamp("completed_at").toInstant()))throw unavailable();return new WorkflowHistory.Row(row.getLong("history_sequence"),v);}
  public long diagnosticHistoryWatermark(String owner,WorkflowQuality.Reference ref){try(var q=prepare("SELECT coalesce(max(history_sequence),0) FROM integration.workflow_diagnostic WHERE tenant_id=? AND owner_subject=? AND workflow_id=? AND revision=?",tenant,owner,ref.id(),ref.revision());var row=q.executeQuery()){row.next();return row.getLong(1);}catch(SQLException invalid){throw unavailable();}}
  public int diagnosticHistoryCount(String owner,WorkflowQuality.Reference ref,Instant snapshot,long watermark){try(var q=prepare("SELECT count(*) FROM integration.workflow_diagnostic WHERE tenant_id=? AND owner_subject=? AND workflow_id=? AND revision=? AND completed_at<=? AND history_sequence<=?",tenant,owner,ref.id(),ref.revision(),Timestamp.from(snapshot),watermark);var row=q.executeQuery()){row.next();return row.getInt(1);}catch(SQLException invalid){throw unavailable();}}
  public Optional<WorkflowHistory.Row> diagnosticHistoryRow(String owner,UUID id){try(var q=prepare("SELECT observation_id,workflow_id,revision,body,completed_at,history_sequence FROM integration.workflow_diagnostic WHERE tenant_id=? AND owner_subject=? AND observation_id=?",tenant,owner,id);var row=q.executeQuery()){return row.next()?Optional.of(historyRow(row)):Optional.empty();}catch(SQLException|IllegalArgumentException invalid){throw unavailable();}}
  public List<WorkflowHistory.Row> diagnosticHistoryRows(String owner,WorkflowQuality.Reference ref,Instant snapshot,long watermark,WorkflowHistory.Row anchor){
   var sql="SELECT observation_id,workflow_id,revision,body,completed_at,history_sequence FROM integration.workflow_diagnostic WHERE tenant_id=? AND owner_subject=? AND workflow_id=? AND revision=? AND completed_at<=? AND history_sequence<=?";var args=new ArrayList<Object>(List.of(tenant,owner,ref.id(),ref.revision(),Timestamp.from(snapshot),watermark));
   if(anchor!=null){sql+=" AND (completed_at<? OR completed_at=? AND observation_id>?)";var o=anchor.stored().observation();args.add(Timestamp.from(o.completedAt()));args.add(Timestamp.from(o.completedAt()));args.add(o.id());}sql+=" ORDER BY completed_at DESC,observation_id LIMIT 21";
   try(var q=prepare(sql,args.toArray());var rows=q.executeQuery()){var result=new ArrayList<WorkflowHistory.Row>();while(rows.next()){var row=historyRow(rows);if(!row.stored().observation().reference().equals(ref))throw unavailable();result.add(row);}return List.copyOf(result);}catch(SQLException|IllegalArgumentException invalid){throw unavailable();}
  }
  public Optional<WorkflowQualityAlerts.Configuration> alertConfiguration(String owner,String id,int revision){try(var q=prepare("SELECT edit_version,body,updated_at FROM integration.workflow_quality_alert_configuration WHERE tenant_id=? AND owner_subject=? AND workflow_id=? AND revision=?",tenant,owner,id,revision);var row=q.executeQuery()){if(!row.next())return Optional.empty();var c=WorkflowQualityAlertsJson.configuration(row.getString("body"));if(!c.reference().id().equals(id)||c.reference().revision()!=revision||c.editVersion()!=row.getInt("edit_version")||!c.updatedAt().equals(row.getTimestamp("updated_at").toInstant()))throw unavailable();return Optional.of(c);}catch(SQLException|IllegalArgumentException invalid){throw unavailable();}}
  public void saveAlertConfiguration(String owner,WorkflowQualityAlerts.Configuration value,int expected){var old=alertConfiguration(owner,value.reference().id(),value.reference().revision()).orElse(null);if((old==null?0:old.editVersion())!=expected||value.editVersion()!=expected+1||old!=null&&(!old.reference().equals(value.reference())||value.updatedAt().isBefore(old.updatedAt())))throw new com.acme.opsweave.integration.domain.WorkflowFailure(com.acme.opsweave.integration.domain.WorkflowFailure.Code.CONFLICT);var parent=published(value.reference().id(),value.reference().revision()).orElseThrow();if(!parent.digest().equals(value.reference().digest()))throw unavailable();if(expected==0)update("INSERT INTO integration.workflow_quality_alert_configuration(tenant_id,owner_subject,workflow_id,revision,edit_version,body,updated_at) VALUES (?,?,?,?,?,?::jsonb,?)",tenant,owner,value.reference().id(),value.reference().revision(),value.editVersion(),CatalogJson.JSON.writeValueAsString(value),Timestamp.from(value.updatedAt()));else update("UPDATE integration.workflow_quality_alert_configuration SET edit_version=?,body=?::jsonb,updated_at=? WHERE tenant_id=? AND owner_subject=? AND workflow_id=? AND revision=? AND edit_version=?",value.editVersion(),CatalogJson.JSON.writeValueAsString(value),Timestamp.from(value.updatedAt()),tenant,owner,value.reference().id(),value.reference().revision(),expected);}
  public Optional<WorkflowQualityAlerts.Receipt> alertCommand(String owner,UUID id){try(var q=prepare("SELECT workflow_id,revision,body,accepted_at FROM integration.workflow_quality_alert_command WHERE tenant_id=? AND owner_subject=? AND request_id=?",tenant,owner,id);var row=q.executeQuery()){if(!row.next())return Optional.empty();var r=WorkflowQualityAlertsJson.receipt(row.getString("body"));if(!r.requestId().equals(id)||!r.configuration().reference().id().equals(row.getString("workflow_id"))||r.configuration().reference().revision()!=row.getInt("revision")||!r.acceptedAt().equals(row.getTimestamp("accepted_at").toInstant()))throw unavailable();return Optional.of(r);}catch(SQLException|IllegalArgumentException invalid){throw unavailable();}}
  public int alertCommandCount(String owner){try(var q=prepare("SELECT count(*) FROM integration.workflow_quality_alert_command WHERE tenant_id=? AND owner_subject=?",tenant,owner);var row=q.executeQuery()){row.next();return row.getInt(1);}catch(SQLException invalid){throw unavailable();}}
  public void addAlertCommand(String owner,WorkflowQualityAlerts.Receipt receipt){var c=receipt.configuration();if(alertCommandCount(owner)>=200||!Objects.equals(alertConfiguration(owner,c.reference().id(),c.reference().revision()).orElse(null),c))throw unavailable();update("INSERT INTO integration.workflow_quality_alert_command(tenant_id,owner_subject,request_id,workflow_id,revision,body,accepted_at) VALUES (?,?,?,?,?,?::jsonb,?)",tenant,owner,receipt.requestId(),c.reference().id(),c.reference().revision(),CatalogJson.JSON.writeValueAsString(receipt),Timestamp.from(receipt.acceptedAt()));}

  public Optional<SourceCredential> credential(String owner,UUID id){return credentialRows("SELECT credential_id,body,updated_at FROM integration.source_credential WHERE tenant_id=? AND owner_subject=? AND credential_id=?",tenant,owner,id).stream().findFirst();}
  public boolean credentialExists(UUID id){try(var s=prepare("SELECT 1 FROM integration.source_credential WHERE tenant_id=? AND credential_id=? LIMIT 1",tenant,id);var r=s.executeQuery()){return r.next();}catch(SQLException failure){throw unavailable();}}
  public List<SourceCredential> credentials(String owner){return credentialRows("SELECT credential_id,body,updated_at FROM integration.source_credential WHERE tenant_id=? AND owner_subject=? ORDER BY updated_at DESC,credential_id LIMIT 101",tenant,owner);}
  private List<SourceCredential> credentialRows(String sql,Object...args){try(var s=prepare(sql,args);var r=s.executeQuery()){var items=new ArrayList<SourceCredential>();while(r.next()){var c=SourceCredentialJson.metadata(r.getString("body"));if(!c.id().equals(r.getObject("credential_id",UUID.class))||!c.updatedAt().equals(r.getTimestamp("updated_at").toInstant()))throw unavailable();items.add(c);}return List.copyOf(items);}catch(SQLException|IllegalArgumentException failure){throw unavailable();}}
  public void saveCredential(String owner,SourceCredential c){update("INSERT INTO integration.source_credential (tenant_id,owner_subject,credential_id,body,updated_at) VALUES (?,?,?,?::jsonb,?) ON CONFLICT (tenant_id,owner_subject,credential_id) DO UPDATE SET body=EXCLUDED.body,updated_at=EXCLUDED.updated_at",tenant,owner,c.id(),CatalogJson.JSON.writeValueAsString(SourceCredentialJson.wire(c)),Timestamp.from(c.updatedAt()));}
  public List<SourceCredential.Version> credentialVersions(String owner,UUID id){try(var s=prepare("SELECT credential_id,revision,version_id,key_id,nonce,body,created_at FROM integration.source_credential_version WHERE tenant_id=? AND owner_subject=? AND credential_id=? ORDER BY revision DESC LIMIT 101",tenant,owner,id);var r=s.executeQuery()){var items=new ArrayList<SourceCredential.Version>();while(r.next()){var v=SourceCredentialJson.version(r.getString("body"));if(!v.credentialId().equals(r.getObject("credential_id",UUID.class))||v.revision()!=r.getInt("revision")||!v.versionId().equals(r.getObject("version_id",UUID.class))||!v.envelope().keyId().equals(r.getString("key_id"))||!v.envelope().nonce().equals(r.getString("nonce"))||!v.createdAt().equals(r.getTimestamp("created_at").toInstant()))throw unavailable();items.add(v);}return List.copyOf(items);}catch(SQLException|IllegalArgumentException failure){throw unavailable();}}
  public void addCredentialVersion(String owner,SourceCredential.Version v){update("INSERT INTO integration.source_credential_version (tenant_id,owner_subject,credential_id,revision,version_id,key_id,nonce,body,created_at) VALUES (?,?,?,?,?,?,?,?::jsonb,?)",tenant,owner,v.credentialId(),v.revision(),v.versionId(),v.envelope().keyId(),v.envelope().nonce(),CatalogJson.JSON.writeValueAsString(SourceCredentialJson.storageVersion(v)),Timestamp.from(v.createdAt()));}
  public List<SourceCredential.Revocation> credentialRevocations(String owner,UUID id){try(var s=prepare("SELECT revision,request_id,created_at FROM integration.source_credential_revocation WHERE tenant_id=? AND owner_subject=? AND credential_id=? ORDER BY revision",tenant,owner,id);var r=s.executeQuery()){var items=new ArrayList<SourceCredential.Revocation>();while(r.next())items.add(new SourceCredential.Revocation(id,r.getInt("revision"),r.getObject("request_id",UUID.class),r.getTimestamp("created_at").toInstant()));return List.copyOf(items);}catch(SQLException|IllegalArgumentException failure){throw unavailable();}}
  public void addCredentialRevocation(String owner,SourceCredential.Revocation r){update("INSERT INTO integration.source_credential_revocation (tenant_id,owner_subject,credential_id,revision,request_id,created_at) VALUES (?,?,?,?,?,?)",tenant,owner,r.credentialId(),r.revision(),r.requestId(),Timestamp.from(r.createdAt()));}
  public Optional<SourceCredential.Receipt> credentialReceipt(String owner,UUID id){try(var s=prepare("SELECT credential_id,body FROM integration.source_credential_command WHERE tenant_id=? AND owner_subject=? AND request_id=?",tenant,owner,id);var r=s.executeQuery()){if(!r.next())return Optional.empty();var c=SourceCredentialJson.receipt(r.getString("body"));if(!c.requestId().equals(id)||!c.credentialId().equals(r.getObject("credential_id",UUID.class)))throw unavailable();return Optional.of(c);}catch(SQLException|IllegalArgumentException failure){throw unavailable();}}
  public int credentialReceiptCount(String owner){try(var s=prepare("SELECT count(*) FROM integration.source_credential_command WHERE tenant_id=? AND owner_subject=?",tenant,owner);var r=s.executeQuery()){r.next();return r.getInt(1);}catch(SQLException failure){throw unavailable();}}
  public void addCredentialReceipt(String owner,SourceCredential.Receipt r){update("INSERT INTO integration.source_credential_command (tenant_id,owner_subject,request_id,credential_id,body) VALUES (?,?,?,?,?::jsonb)",tenant,owner,r.requestId(),r.credentialId(),CatalogJson.JSON.writeValueAsString(SourceCredentialJson.storageReceipt(r)));}

  public Optional<Entry> draft(String owner,String id,int revision){return find("SELECT entry,workflow_id,revision FROM integration.workflow_draft WHERE tenant_id=? AND owner_subject=? AND workflow_id=? AND revision=?","DRAFT",tenant,owner,id,revision);}
  public Optional<Entry> published(String id,int revision){return find("SELECT entry,workflow_id,revision FROM integration.workflow_version WHERE tenant_id=? AND workflow_id=? AND revision=?","PUBLISHED",tenant,id,revision);}
  private Optional<Entry> find(String sql,String state,Object...args){var entries=read(sql,state,args);return entries.stream().findFirst();}
  public List<Entry> drafts(String owner){return read("SELECT entry,workflow_id,revision FROM integration.workflow_draft d WHERE tenant_id=? AND owner_subject=? AND NOT EXISTS (SELECT 1 FROM integration.workflow_version v WHERE v.tenant_id=d.tenant_id AND v.workflow_id=d.workflow_id AND v.revision=d.revision) ORDER BY updated_at DESC,workflow_id,revision LIMIT 51","DRAFT",tenant,owner);}
  public List<Entry> published(){return read("SELECT entry,workflow_id,revision FROM integration.workflow_version WHERE tenant_id=? ORDER BY updated_at DESC,workflow_id,revision LIMIT 201","PUBLISHED",tenant);}
  private List<Entry> read(String sql,String state,Object...args){try(var s=prepare(sql,args);var r=s.executeQuery()){var list=new ArrayList<Entry>();while(r.next()){var e=WorkflowJson.decode(r.getString("entry"));if(!e.definition().id().equals(r.getString("workflow_id"))||e.definition().revision()!=r.getInt("revision")||!e.state().equals(state))throw unavailable();list.add(e);}return List.copyOf(list);}catch(SQLException|IllegalArgumentException failure){throw unavailable();}}
  public void saveDraft(String owner,Entry entry){
   update("INSERT INTO integration.workflow_draft (tenant_id,owner_subject,workflow_id,revision,entry,updated_at) VALUES (?,?,?,?,?::jsonb,?) ON CONFLICT (tenant_id,owner_subject,workflow_id,revision) DO UPDATE SET entry=EXCLUDED.entry,updated_at=EXCLUDED.updated_at",tenant,owner,entry.definition().id(),entry.definition().revision(),WorkflowJson.encode(entry),Timestamp.from(entry.updatedAt()));
  }
  public void publish(Entry entry,String owner){update("INSERT INTO integration.workflow_version (tenant_id,workflow_id,revision,entry,published_by,updated_at) VALUES (?,?,?,?::jsonb,?,?)",tenant,entry.definition().id(),entry.definition().revision(),WorkflowJson.encode(entry),owner,Timestamp.from(entry.updatedAt()));}
  public void addRun(String owner,Run run){update("INSERT INTO integration.workflow_run (tenant_id,owner_subject,run_id,receipt,created_at) VALUES (?,?,?,?::jsonb,?)",tenant,owner,run.receipt().id(),WorkflowJson.encodeRun(run),Timestamp.from(run.receipt().createdAt()));}
  public Optional<Run> run(String owner,UUID id){try(var s=prepare("SELECT receipt FROM integration.workflow_run WHERE tenant_id=? AND owner_subject=? AND run_id=?",tenant,owner,id);var r=s.executeQuery()){if(!r.next())return Optional.empty();var run=WorkflowJson.run(r.getString("receipt"));if(!run.receipt().id().equals(id))throw unavailable();return Optional.of(run);}catch(SQLException|IllegalArgumentException failure){throw unavailable();}}
  public List<WorkflowLogStream.Batch> qualityLogBatches(String owner,String id,int revision,String digest){try(var q=prepare("SELECT batch_id,body,created_at FROM integration.workflow_log_stream_batch WHERE tenant_id=? AND owner_subject=? AND workflow_id=? AND revision=? ORDER BY created_at DESC,batch_id LIMIT 21",tenant,owner,id,revision);var r=q.executeQuery()){var rows=new ArrayList<WorkflowLogStream.Batch>();while(r.next()){var b=WorkflowLogStreamJson.batch(r.getString("body"));if(!b.id().equals(r.getObject("batch_id",UUID.class))||!b.workflowId().equals(id)||b.revision()!=revision||!b.digest().equals(digest)||!b.createdAt().equals(r.getTimestamp("created_at").toInstant()))throw unavailable();rows.add(b);}return List.copyOf(rows);}catch(SQLException|IllegalArgumentException f){throw unavailable();}}
  public List<WorkflowMetricStream.Batch> qualityMetricBatches(String owner,String id,int revision,String digest){try(var q=prepare("SELECT batch_id,body,created_at FROM integration.workflow_metric_stream_batch WHERE tenant_id=? AND owner_subject=? AND workflow_id=? AND revision=? ORDER BY created_at DESC,batch_id LIMIT 21",tenant,owner,id,revision);var r=q.executeQuery()){var rows=new ArrayList<WorkflowMetricStream.Batch>();while(r.next()){var b=WorkflowMetricStreamJson.batch(r.getString("body"));if(!b.id().equals(r.getObject("batch_id",UUID.class))||!b.workflowId().equals(id)||b.revision()!=revision||!b.digest().equals(digest)||!b.createdAt().equals(r.getTimestamp("created_at").toInstant()))throw unavailable();rows.add(b);}return List.copyOf(rows);}catch(SQLException|IllegalArgumentException f){throw unavailable();}}
  public List<com.acme.opsweave.integration.domain.WorkflowHostScan.Batch> qualityHostBatches(String owner,String id,int revision,String digest){try(var q=prepare("SELECT batch_id,body,updated_at FROM integration.workflow_host_batch WHERE tenant_id=? AND owner_subject=? AND workflow_id=? AND revision=? ORDER BY updated_at DESC,batch_id LIMIT 21",tenant,owner,id,revision);var r=q.executeQuery()){var rows=new ArrayList<com.acme.opsweave.integration.domain.WorkflowHostScan.Batch>();while(r.next()){var b=WorkflowHostScanJson.batch(r.getString("body"));if(!b.id().equals(r.getObject("batch_id",UUID.class))||!b.workflowId().equals(id)||b.revision()!=revision||!b.digest().equals(digest)||!b.updatedAt().equals(r.getTimestamp("updated_at").toInstant()))throw unavailable();rows.add(b);}return List.copyOf(rows);}catch(SQLException|IllegalArgumentException f){throw unavailable();}}
  public Optional<WorkflowMetricStream.Batch> latestConfirmedMetricWindow(String owner,String id,int revision,String digest,Instant till){try(var q=prepare("SELECT batch_id FROM integration.workflow_metric_stream_batch WHERE tenant_id=? AND owner_subject=? AND workflow_id=? AND revision=? AND body->>'digest'=? AND body->>'till'=? AND body->>'state'='CONFIRMED' ORDER BY jsonb_array_length(body->'timestamps') DESC,created_at DESC,batch_id LIMIT 1",tenant,owner,id,revision,digest,till.toString());var r=q.executeQuery()){if(!r.next())return Optional.empty();var b=metricStreamBatch(owner,r.getObject(1,UUID.class)).orElseThrow();if(!b.digest().equals(digest)||!b.till().equals(till)||!b.state().equals("CONFIRMED"))throw unavailable();return Optional.of(b);}catch(SQLException failure){throw unavailable();}}
  public Optional<WorkflowTaskArchive> taskArchive(String owner,String id,int revision,String digest){try(var q=prepare("SELECT next_revision,kind,body,replaced_at FROM integration.workflow_task_archive WHERE tenant_id=? AND owner_subject=? AND workflow_id=? AND revision=?",tenant,owner,id,revision);var row=q.executeQuery()){if(!row.next())return Optional.empty();var a=WorkflowTaskArchiveJson.decode(row.getString("body"));if(!a.reference().matches(id,revision,digest)||a.replacedBy().revision()!=row.getInt("next_revision")||!a.kind().name().equals(row.getString("kind"))||!a.replacedAt().equals(row.getTimestamp("replaced_at").toInstant()))throw unavailable();return Optional.of(a);}catch(SQLException|IllegalArgumentException invalid){throw unavailable();}}
  public int taskArchiveCount(String owner){try(var q=prepare("SELECT count(*) FROM integration.workflow_task_archive WHERE tenant_id=? AND owner_subject=?",tenant,owner);var row=q.executeQuery()){row.next();return row.getInt(1);}catch(SQLException invalid){throw unavailable();}}
  public void addTaskArchive(String owner,WorkflowTaskArchive a){if(taskArchiveCount(owner)>=200)throw unavailable();update("INSERT INTO integration.workflow_task_archive(tenant_id,owner_subject,workflow_id,revision,next_revision,kind,body,replaced_at) VALUES (?,?,?,?,?,?,?::jsonb,?)",tenant,owner,a.reference().id(),a.reference().revision(),a.replacedBy().revision(),a.kind().name(),CatalogJson.JSON.writeValueAsString(a),Timestamp.from(a.replacedAt()));}
  public Optional<WorkflowSampleRecovery.Receipt> sampleRecovery(String owner,UUID id){try(var q=prepare("SELECT workflow_id,revision,kind,batch_id,metric_request_id,log_request_id,body,accepted_at FROM integration.workflow_sample_recovery WHERE tenant_id=? AND owner_subject=? AND request_id=?",tenant,owner,id);var row=q.executeQuery()){if(!row.next())return Optional.empty();var r=WorkflowSampleRecoveryJson.decode(row.getString("body"));boolean metric=r.kind()==WorkflowSampleRecovery.Kind.METRIC_SAMPLE;if(!r.requestId().equals(id)||!r.reference().id().equals(row.getString("workflow_id"))||r.reference().revision()!=row.getInt("revision")||!r.kind().name().equals(row.getString("kind"))||!r.batchId().equals(row.getObject("batch_id",UUID.class))||!r.batchId().equals(row.getObject(metric?"metric_request_id":"log_request_id",UUID.class))||row.getObject(metric?"log_request_id":"metric_request_id")!=null||!r.acceptedAt().equals(row.getTimestamp("accepted_at").toInstant()))throw unavailable();return Optional.of(r);}catch(SQLException|IllegalArgumentException invalid){throw unavailable();}}
  public Optional<WorkflowSampleRecovery.Receipt> sampleRecoveryForBatch(String owner,WorkflowSampleRecovery.Kind kind,UUID id){try(var q=prepare("SELECT request_id FROM integration.workflow_sample_recovery WHERE tenant_id=? AND owner_subject=? AND kind=? AND batch_id=? LIMIT 2",tenant,owner,kind.name(),id);var row=q.executeQuery()){if(!row.next())return Optional.empty();var r=sampleRecovery(owner,row.getObject("request_id",UUID.class)).orElseThrow();if(row.next()||r.kind()!=kind||!r.batchId().equals(id))throw unavailable();return Optional.of(r);}catch(SQLException|IllegalArgumentException invalid){throw unavailable();}}
  public int sampleRecoveryCount(String owner){try(var q=prepare("SELECT count(*) FROM integration.workflow_sample_recovery WHERE tenant_id=? AND owner_subject=?",tenant,owner);var row=q.executeQuery()){row.next();return row.getInt(1);}catch(SQLException invalid){throw unavailable();}}
  public void addSampleRecovery(String owner,WorkflowSampleRecovery.Receipt r){if(sampleRecoveryCount(owner)>=200)throw unavailable();boolean metric=r.kind()==WorkflowSampleRecovery.Kind.METRIC_SAMPLE;update("INSERT INTO integration.workflow_sample_recovery(tenant_id,owner_subject,request_id,workflow_id,revision,kind,batch_id,metric_request_id,log_request_id,body,accepted_at) VALUES (?,?,?,?,?,?,?,?,?,?::jsonb,?)",tenant,owner,r.requestId(),r.reference().id(),r.reference().revision(),r.kind().name(),r.batchId(),metric?r.batchId():null,metric?null:r.batchId(),CatalogJson.JSON.writeValueAsString(r),Timestamp.from(r.acceptedAt()));}
  public Optional<WorkflowRecovery.Receipt> recovery(String owner,UUID id){try(var q=prepare("SELECT workflow_id,revision,kind,batch_id,body,accepted_at FROM integration.workflow_recovery_closure WHERE tenant_id=? AND owner_subject=? AND request_id=?",tenant,owner,id);var row=q.executeQuery()){if(!row.next())return Optional.empty();var r=WorkflowRecoveryJson.decode(row.getString("body"));if(!r.requestId().equals(id)||!r.reference().id().equals(row.getString("workflow_id"))||r.reference().revision()!=row.getInt("revision")||!r.kind().name().equals(row.getString("kind"))||!r.batchId().equals(row.getObject("batch_id",UUID.class))||!r.acceptedAt().equals(row.getTimestamp("accepted_at").toInstant()))throw unavailable();return Optional.of(r);}catch(SQLException|IllegalArgumentException invalid){throw unavailable();}}
  public Optional<WorkflowRecovery.Receipt> recoveryForVersion(String owner,String id,int revision,String digest){try(var q=prepare("SELECT request_id FROM integration.workflow_recovery_closure WHERE tenant_id=? AND owner_subject=? AND workflow_id=? AND revision=? LIMIT 2",tenant,owner,id,revision);var row=q.executeQuery()){if(!row.next())return Optional.empty();var r=recovery(owner,row.getObject("request_id",UUID.class)).orElseThrow();if(row.next()||!r.reference().digest().equals(digest))throw unavailable();return Optional.of(r);}catch(SQLException|IllegalArgumentException invalid){throw unavailable();}}
  public int recoveryCount(String owner){try(var q=prepare("SELECT count(*) FROM integration.workflow_recovery_closure WHERE tenant_id=? AND owner_subject=?",tenant,owner);var row=q.executeQuery()){row.next();return row.getInt(1);}catch(SQLException invalid){throw unavailable();}}
  public void addRecovery(String owner,WorkflowRecovery.Receipt r){if(recoveryCount(owner)>=200)throw unavailable();update("INSERT INTO integration.workflow_recovery_closure(tenant_id,owner_subject,request_id,workflow_id,revision,kind,batch_id,body,accepted_at) VALUES (?,?,?,?,?,?,?,?::jsonb,?)",tenant,owner,r.requestId(),r.reference().id(),r.reference().revision(),r.kind().name(),r.batchId(),CatalogJson.JSON.writeValueAsString(r),Timestamp.from(r.acceptedAt()));}
  public Optional<WorkflowDiagnostics.Stored> diagnostic(String owner,UUID id){try(var q=prepare("SELECT workflow_id,revision,body,completed_at FROM integration.workflow_diagnostic WHERE tenant_id=? AND owner_subject=? AND observation_id=?",tenant,owner,id);var r=q.executeQuery()){if(!r.next())return Optional.empty();var v=WorkflowDiagnosticsJson.decode(r.getString("body"));var o=v.observation();if(!o.id().equals(id)||!o.reference().id().equals(r.getString("workflow_id"))||o.reference().revision()!=r.getInt("revision")||!o.completedAt().equals(r.getTimestamp("completed_at").toInstant()))throw unavailable();return Optional.of(v);}catch(SQLException|IllegalArgumentException failure){throw unavailable();}}
  public List<WorkflowDiagnostics.Stored> diagnostics(String owner,String id,int revision,String digest){try(var q=prepare("SELECT observation_id FROM integration.workflow_diagnostic WHERE tenant_id=? AND owner_subject=? AND workflow_id=? AND revision=? ORDER BY completed_at DESC,observation_id LIMIT 21",tenant,owner,id,revision);var r=q.executeQuery()){var rows=new ArrayList<WorkflowDiagnostics.Stored>();while(r.next()){var v=diagnostic(owner,r.getObject(1,UUID.class)).orElseThrow();if(!v.observation().reference().digest().equals(digest))throw unavailable();rows.add(v);}return List.copyOf(rows);}catch(SQLException failure){throw unavailable();}}
  public int diagnosticCount(String owner){try(var q=prepare("SELECT count(*) FROM integration.workflow_diagnostic WHERE tenant_id=? AND owner_subject=?",tenant,owner);var r=q.executeQuery()){r.next();return r.getInt(1);}catch(SQLException failure){throw unavailable();}}
  public void addDiagnostic(String owner,WorkflowDiagnostics.Stored v){if(diagnosticCount(owner)>=200)throw unavailable();var o=v.observation();update("INSERT INTO integration.workflow_diagnostic(tenant_id,owner_subject,observation_id,workflow_id,revision,body,completed_at) VALUES (?,?,?,?,?,?::jsonb,?)",tenant,owner,o.id(),o.reference().id(),o.reference().revision(),CatalogJson.JSON.writeValueAsString(v),Timestamp.from(o.completedAt()));}
  public List<Run> runs(String owner){try(var s=prepare("SELECT run_id,receipt FROM integration.workflow_run WHERE tenant_id=? AND owner_subject=? ORDER BY created_at DESC,run_id DESC LIMIT 201",tenant,owner);var r=s.executeQuery()){var result=new ArrayList<Run>();while(r.next()){var run=WorkflowJson.run(r.getString("receipt"));if(!run.receipt().id().equals(r.getObject("run_id",UUID.class)))throw unavailable();result.add(run);}return List.copyOf(result);}catch(SQLException|IllegalArgumentException failure){throw unavailable();}}
  public Optional<SourceSetup> setup(String owner,UUID id){return setupRows("SELECT setup_id,body FROM integration.source_setup WHERE tenant_id=? AND owner_subject=? AND setup_id=?",tenant,owner,id).stream().findFirst();}
  public boolean sourceSetupExists(UUID id){try(var s=prepare("SELECT 1 FROM integration.source_setup WHERE tenant_id=? AND setup_id=? LIMIT 1",tenant,id);var r=s.executeQuery()){return r.next();}catch(SQLException failure){throw unavailable();}}
  public List<SourceSetup> setups(String owner){return setupRows("SELECT setup_id,body FROM integration.source_setup WHERE tenant_id=? AND owner_subject=? ORDER BY created_at DESC,setup_id DESC LIMIT 201",tenant,owner);}
  private List<SourceSetup> setupRows(String sql,Object...args){try(var s=prepare(sql,args);var r=s.executeQuery()){var result=new ArrayList<SourceSetup>();while(r.next()){var setup=SourceSetupJson.decode(r.getString("body"));if(!setup.id().equals(r.getObject("setup_id",UUID.class)))throw unavailable();result.add(setup);}return List.copyOf(result);}catch(SQLException|IllegalArgumentException failure){throw unavailable();}}
  public void saveSetup(String owner,SourceSetup setup){update("INSERT INTO integration.source_setup (tenant_id,owner_subject,setup_id,body,created_at) VALUES (?,?,?,?::jsonb,?)",tenant,owner,setup.id(),CatalogJson.JSON.writeValueAsString(SourceSetupJson.wire(setup)),Timestamp.from(setup.createdAt()));}
  public Optional<SourceInstance> sourceInstance(String owner,UUID id){try(var s=prepare("SELECT body FROM integration.source_instance WHERE tenant_id=? AND owner_subject=? AND source_id=?",tenant,owner,id);var r=s.executeQuery()){if(!r.next())return Optional.empty();var i=SourceInstanceJson.instance(r.getString("body"));if(!i.id().equals(id))throw unavailable();return Optional.of(i);}catch(SQLException|IllegalArgumentException failure){throw unavailable();}}
  public void saveSourceInstance(String owner,SourceInstance i){update("INSERT INTO integration.source_instance (tenant_id,owner_subject,source_id,body,updated_at) VALUES (?,?,?,?::jsonb,?) ON CONFLICT (tenant_id,owner_subject,source_id) DO UPDATE SET body=EXCLUDED.body,updated_at=EXCLUDED.updated_at",tenant,owner,i.id(),CatalogJson.JSON.writeValueAsString(SourceInstanceJson.wire(i)),Timestamp.from(i.updatedAt()));}
  public List<SourceInstance.Configuration> sourceConfigurations(String owner,UUID id){try(var s=prepare("SELECT revision,body FROM integration.source_configuration WHERE tenant_id=? AND owner_subject=? AND source_id=? ORDER BY revision DESC LIMIT 101",tenant,owner,id);var r=s.executeQuery()){var rows=new ArrayList<SourceInstance.Configuration>();while(r.next()){var c=SourceInstanceJson.configuration(r.getString("body"));if(!c.sourceId().equals(id)||c.revision()!=r.getInt("revision"))throw unavailable();rows.add(c);}return List.copyOf(rows);}catch(SQLException|IllegalArgumentException failure){throw unavailable();}}
  public void addSourceConfiguration(String owner,SourceInstance.Configuration c){update("INSERT INTO integration.source_configuration (tenant_id,owner_subject,source_id,revision,body) VALUES (?,?,?,?,?::jsonb)",tenant,owner,c.sourceId(),c.revision(),CatalogJson.JSON.writeValueAsString(c));}
  public List<SourceConnectionConfiguration> sourceConnections(String owner,UUID id){try(var statement=prepare("SELECT source_id,revision,body,created_at FROM integration.source_connection_configuration WHERE tenant_id=? AND owner_subject=? AND source_id=? ORDER BY revision DESC LIMIT 101",tenant,owner,id);var rows=statement.executeQuery()){var result=new ArrayList<SourceConnectionConfiguration>();while(rows.next()){var c=SourceConnectionJson.configuration(rows.getString("body"));if(!c.sourceId().equals(rows.getObject("source_id",UUID.class))||c.revision()!=rows.getInt("revision")||!c.createdAt().equals(rows.getTimestamp("created_at").toInstant()))throw unavailable();result.add(c);}return List.copyOf(result);}catch(SQLException|IllegalArgumentException failure){throw unavailable();}}
  public void addSourceConnection(String owner,SourceConnectionConfiguration c){update("INSERT INTO integration.source_connection_configuration (tenant_id,owner_subject,source_id,revision,body,created_at) VALUES (?,?,?,?,?::jsonb,?)",tenant,owner,c.sourceId(),c.revision(),CatalogJson.JSON.writeValueAsString(SourceConnectionJson.wire(c)),Timestamp.from(c.createdAt()));}
  public Optional<SourceInstance.CommandReceipt> sourceCommand(String owner,UUID id){try(var s=prepare("SELECT source_id,body FROM integration.source_command WHERE tenant_id=? AND owner_subject=? AND request_id=?",tenant,owner,id);var r=s.executeQuery()){if(!r.next())return Optional.empty();var receipt=SourceInstanceJson.receipt(r.getString("body"));if(!receipt.requestId().equals(id)||!receipt.sourceId().equals(r.getObject("source_id",UUID.class)))throw unavailable();return Optional.of(receipt);}catch(SQLException|IllegalArgumentException failure){throw unavailable();}}
  public int sourceCommandCount(String owner){try(var s=prepare("SELECT count(*) FROM integration.source_command WHERE tenant_id=? AND owner_subject=?",tenant,owner);var r=s.executeQuery()){r.next();return r.getInt(1);}catch(SQLException failure){throw unavailable();}}
  public void addSourceCommand(String owner,SourceInstance.CommandReceipt r){update("INSERT INTO integration.source_command (tenant_id,owner_subject,request_id,source_id,body) VALUES (?,?,?,?,?::jsonb)",tenant,owner,r.requestId(),r.sourceId(),CatalogJson.JSON.writeValueAsString(SourceInstanceJson.wire(r)));}
  public Optional<SourceInspection> sourceInspection(String owner,UUID id){return inspections("SELECT request_id,source_id,state,body,started_at FROM integration.source_inspection WHERE tenant_id=? AND owner_subject=? AND request_id=?",tenant,owner,id).stream().findFirst();}
  public List<SourceInspection> sourceInspections(String owner,UUID id){return inspections("SELECT request_id,source_id,state,body,started_at FROM integration.source_inspection WHERE tenant_id=? AND owner_subject=? AND source_id=? ORDER BY started_at DESC,request_id LIMIT 20",tenant,owner,id);}
  public List<SourceInspection> sourceInspections(String owner,UUID id,String kind){return inspections("SELECT request_id,source_id,state,body,started_at FROM integration.source_inspection WHERE tenant_id=? AND owner_subject=? AND source_id=? AND body->>'kind'=? ORDER BY started_at DESC,request_id LIMIT 20",tenant,owner,id,kind);}
  private List<SourceInspection> inspections(String sql,Object...args){try(var s=prepare(sql,args);var r=s.executeQuery()){var list=new ArrayList<SourceInspection>();while(r.next()){var i=SourceInspectionJson.decode(r.getString("body"));if(!i.requestId().equals(r.getObject("request_id",UUID.class))||!i.sourceId().equals(r.getObject("source_id",UUID.class))||!i.state().equals(r.getString("state"))||!i.asOf().equals(r.getTimestamp("started_at").toInstant()))throw unavailable();list.add(i);}return List.copyOf(list);}catch(SQLException|IllegalArgumentException failure){throw unavailable();}}
  public int sourceInspectionCount(String owner){try(var s=prepare("SELECT count(*) FROM integration.source_inspection WHERE tenant_id=? AND owner_subject=?",tenant,owner);var r=s.executeQuery()){r.next();return r.getInt(1);}catch(SQLException failure){throw unavailable();}}
  public void addSourceInspection(String owner,SourceInspection r){if(!r.state().equals("PENDING"))throw unavailable();update("INSERT INTO integration.source_inspection (tenant_id,owner_subject,request_id,source_id,state,body,started_at) VALUES (?,?,?,?,?,?::jsonb,?)",tenant,owner,r.requestId(),r.sourceId(),r.state(),CatalogJson.JSON.writeValueAsString(SourceInspectionJson.storage(r)),Timestamp.from(r.asOf()));}
  public void finishSourceInspection(String owner,SourceInspection r){if(r.state().equals("PENDING"))throw unavailable();var old=sourceInspection(owner,r.requestId()).orElseThrow(PostgresWorkflowStore::unavailable);if(!old.commandDigest().equals(r.commandDigest())||!old.sourceId().equals(r.sourceId()))throw unavailable();update("UPDATE integration.source_inspection SET state=?,body=?::jsonb WHERE tenant_id=? AND owner_subject=? AND request_id=? AND source_id=? AND state='PENDING'",r.state(),CatalogJson.JSON.writeValueAsString(SourceInspectionJson.storage(r)),tenant,owner,r.requestId(),r.sourceId());}
  public Optional<WorkflowHostSchedule.Schedule> hostSchedule(String owner,String id){try(var q=prepare("SELECT revision,body FROM integration.workflow_host_schedule WHERE tenant_id=? AND owner_subject=? AND workflow_id=?",tenant,owner,id);var r=q.executeQuery()){if(!r.next())return Optional.empty();var schedule=WorkflowHostScheduleJson.schedule(r.getString("body"));if(!schedule.workflowId().equals(id)||schedule.revision()!=r.getInt("revision"))throw unavailable();return Optional.of(schedule);}catch(SQLException|IllegalArgumentException f){throw unavailable();}}
  public List<WorkflowHostSchedule.Schedule> hostSchedules(String owner){try(var q=prepare("SELECT workflow_id FROM integration.workflow_host_schedule WHERE tenant_id=? AND owner_subject=? ORDER BY workflow_id LIMIT 21",tenant,owner);var r=q.executeQuery()){var rows=new ArrayList<WorkflowHostSchedule.Schedule>();while(r.next())rows.add(hostSchedule(owner,r.getString(1)).orElseThrow());return List.copyOf(rows);}catch(SQLException f){throw unavailable();}}
  public void saveHostSchedule(String owner,WorkflowHostSchedule.Schedule schedule){update("INSERT INTO integration.workflow_host_schedule (tenant_id,owner_subject,workflow_id,revision,body) VALUES (?,?,?,?,?::jsonb) ON CONFLICT (tenant_id,owner_subject,workflow_id) DO UPDATE SET revision=EXCLUDED.revision,body=EXCLUDED.body",tenant,owner,schedule.workflowId(),schedule.revision(),CatalogJson.JSON.writeValueAsString(schedule));}
  public Optional<WorkflowHostSchedule.Receipt> hostScheduleControl(String owner,UUID id){try(var q=prepare("SELECT workflow_id,body FROM integration.workflow_host_schedule_control WHERE tenant_id=? AND owner_subject=? AND request_id=?",tenant,owner,id);var r=q.executeQuery()){if(!r.next())return Optional.empty();var receipt=WorkflowHostScheduleJson.receipt(r.getString("body"));if(!receipt.requestId().equals(id)||!receipt.schedule().workflowId().equals(r.getString("workflow_id")))throw unavailable();return Optional.of(receipt);}catch(SQLException|IllegalArgumentException f){throw unavailable();}}
  public int hostScheduleControlCount(String owner){try(var q=prepare("SELECT count(*) FROM integration.workflow_host_schedule_control WHERE tenant_id=? AND owner_subject=?",tenant,owner);var r=q.executeQuery()){r.next();return r.getInt(1);}catch(SQLException f){throw unavailable();}}
  public void addHostScheduleControl(String owner,WorkflowHostSchedule.Receipt receipt){update("INSERT INTO integration.workflow_host_schedule_control (tenant_id,owner_subject,request_id,workflow_id,body) VALUES (?,?,?,?,?::jsonb)",tenant,owner,receipt.requestId(),receipt.schedule().workflowId(),CatalogJson.JSON.writeValueAsString(receipt));}
  public Optional<WorkflowLogStream.Task> logStreamTask(String owner,String id){try(var q=prepare("SELECT body FROM integration.workflow_log_stream_task WHERE tenant_id=? AND owner_subject=? AND workflow_id=?",tenant,owner,id);var r=q.executeQuery()){if(!r.next())return Optional.empty();var task=WorkflowLogStreamJson.task(r.getString(1));if(!task.workflowId().equals(id))throw unavailable();return Optional.of(task);}catch(SQLException|IllegalArgumentException f){throw unavailable();}}
  public List<WorkflowLogStream.Task> logStreamTasks(String owner){try(var q=prepare("SELECT workflow_id FROM integration.workflow_log_stream_task WHERE tenant_id=? AND owner_subject=? ORDER BY workflow_id LIMIT 21",tenant,owner);var r=q.executeQuery()){var rows=new ArrayList<WorkflowLogStream.Task>();while(r.next())rows.add(logStreamTask(owner,r.getString(1)).orElseThrow());return List.copyOf(rows);}catch(SQLException f){throw unavailable();}}
  public void saveLogStreamTask(String owner,WorkflowLogStream.Task task){update("INSERT INTO integration.workflow_log_stream_task (tenant_id,owner_subject,workflow_id,revision,body) VALUES (?,?,?,?,?::jsonb) ON CONFLICT (tenant_id,owner_subject,workflow_id) DO UPDATE SET revision=EXCLUDED.revision,body=EXCLUDED.body",tenant,owner,task.workflowId(),task.revision(),CatalogJson.JSON.writeValueAsString(task));}
  public Optional<WorkflowLogStream.Batch> logStreamBatch(String owner,UUID id){try(var q=prepare("SELECT workflow_id,revision,body,created_at FROM integration.workflow_log_stream_batch WHERE tenant_id=? AND owner_subject=? AND batch_id=?",tenant,owner,id);var r=q.executeQuery()){if(!r.next())return Optional.empty();var batch=WorkflowLogStreamJson.batch(r.getString("body"));if(!batch.id().equals(id)||!batch.workflowId().equals(r.getString("workflow_id"))||batch.revision()!=r.getInt("revision")||!batch.createdAt().equals(r.getTimestamp("created_at").toInstant()))throw unavailable();return Optional.of(batch);}catch(SQLException|IllegalArgumentException f){throw unavailable();}}
  public List<WorkflowLogStream.Batch> logStreamBatches(String owner,String id){try(var q=prepare("SELECT batch_id FROM integration.workflow_log_stream_batch WHERE tenant_id=? AND owner_subject=? AND workflow_id=? ORDER BY created_at DESC,batch_id LIMIT 20",tenant,owner,id);var r=q.executeQuery()){var rows=new ArrayList<WorkflowLogStream.Batch>();while(r.next())rows.add(logStreamBatch(owner,r.getObject(1,UUID.class)).orElseThrow());return List.copyOf(rows);}catch(SQLException f){throw unavailable();}}
  public int logStreamBatchCount(String owner){try(var q=prepare("SELECT count(*) FROM integration.workflow_log_stream_batch WHERE tenant_id=? AND owner_subject=?",tenant,owner);var r=q.executeQuery()){r.next();return r.getInt(1);}catch(SQLException f){throw unavailable();}}
  public Optional<WorkflowLogStream.Batch> latestConfirmedLogWindow(String owner,String id,int revision,String digest,Instant till){try(var q=prepare("SELECT batch_id FROM integration.workflow_log_stream_batch WHERE tenant_id=? AND owner_subject=? AND workflow_id=? AND revision=? AND body->>'digest'=? AND body->>'till'=? AND body->>'state'='CONFIRMED' ORDER BY (body->>'inputCount')::integer DESC,created_at DESC,batch_id LIMIT 1",tenant,owner,id,revision,digest,till.toString());var r=q.executeQuery()){if(!r.next())return Optional.empty();var batch=logStreamBatch(owner,r.getObject(1,UUID.class)).orElseThrow();if(!batch.state().equals("CONFIRMED")||!batch.till().equals(till)||!batch.digest().equals(digest))throw unavailable();return Optional.of(batch);}catch(SQLException f){throw unavailable();}}
  public void addLogStreamBatch(String owner,WorkflowLogStream.Batch batch){if(batch.reconcilesBatchId()!=null)batch.requireReconciliation(logStreamBatch(owner,batch.reconcilesBatchId()).orElseThrow());if(!Set.of("IN_FLIGHT","CONFIRMED").contains(batch.state()))throw unavailable();update("INSERT INTO integration.workflow_log_stream_batch (tenant_id,owner_subject,batch_id,workflow_id,revision,body,created_at) VALUES (?,?,?,?,?,?::jsonb,?)",tenant,owner,batch.id(),batch.workflowId(),batch.revision(),CatalogJson.JSON.writeValueAsString(batch),Timestamp.from(batch.createdAt()));}
  public boolean logStreamRejectionKnown(String owner,UUID id){try(var q=prepare("SELECT rejection_known FROM integration.workflow_log_stream_batch WHERE tenant_id=? AND owner_subject=? AND batch_id=?",tenant,owner,id);var row=q.executeQuery()){if(!row.next())throw unavailable();return row.getBoolean(1);}catch(SQLException invalid){throw unavailable();}}
  public void finishLogStreamBatch(String owner,WorkflowLogStream.Batch batch){logStreamBatch(owner,batch.id()).orElseThrow().requireSuccessor(batch);update("UPDATE integration.workflow_log_stream_batch SET body=?::jsonb,rejection_known=? WHERE tenant_id=? AND owner_subject=? AND batch_id=?",CatalogJson.JSON.writeValueAsString(batch),batch.state().equals("FAILED"),tenant,owner,batch.id());}
  public Optional<WorkflowLogStream.Receipt> logStreamControl(String owner,UUID id){try(var q=prepare("SELECT workflow_id,body FROM integration.workflow_log_stream_control WHERE tenant_id=? AND owner_subject=? AND request_id=?",tenant,owner,id);var r=q.executeQuery()){if(!r.next())return Optional.empty();var receipt=WorkflowLogStreamJson.receipt(r.getString("body"));if(!receipt.requestId().equals(id)||!receipt.task().workflowId().equals(r.getString("workflow_id")))throw unavailable();return Optional.of(receipt);}catch(SQLException|IllegalArgumentException f){throw unavailable();}}
  public int logStreamControlCount(String owner){try(var q=prepare("SELECT count(*) FROM integration.workflow_log_stream_control WHERE tenant_id=? AND owner_subject=?",tenant,owner);var r=q.executeQuery()){r.next();return r.getInt(1);}catch(SQLException f){throw unavailable();}}
  public void addLogStreamControl(String owner,WorkflowLogStream.Receipt receipt){update("INSERT INTO integration.workflow_log_stream_control (tenant_id,owner_subject,request_id,workflow_id,body) VALUES (?,?,?,?,?::jsonb)",tenant,owner,receipt.requestId(),receipt.task().workflowId(),CatalogJson.JSON.writeValueAsString(receipt));}
  public Optional<WorkflowMetricStream.Task> metricStreamTask(String owner,String id){try(var q=prepare("SELECT body FROM integration.workflow_metric_stream_task WHERE tenant_id=? AND owner_subject=? AND workflow_id=?",tenant,owner,id);var r=q.executeQuery()){if(!r.next())return Optional.empty();var task=WorkflowMetricStreamJson.task(r.getString(1));if(!task.workflowId().equals(id))throw unavailable();return Optional.of(task);}catch(SQLException|IllegalArgumentException f){throw unavailable();}}
  public List<WorkflowMetricStream.Task> metricStreamTasks(String owner){try(var q=prepare("SELECT workflow_id FROM integration.workflow_metric_stream_task WHERE tenant_id=? AND owner_subject=? ORDER BY workflow_id LIMIT 21",tenant,owner);var r=q.executeQuery()){var rows=new ArrayList<WorkflowMetricStream.Task>();while(r.next())rows.add(metricStreamTask(owner,r.getString(1)).orElseThrow());return List.copyOf(rows);}catch(SQLException f){throw unavailable();}}
  public void saveMetricStreamTask(String owner,WorkflowMetricStream.Task task){update("INSERT INTO integration.workflow_metric_stream_task (tenant_id,owner_subject,workflow_id,revision,body) VALUES (?,?,?,?,?::jsonb) ON CONFLICT (tenant_id,owner_subject,workflow_id) DO UPDATE SET revision=EXCLUDED.revision,body=EXCLUDED.body",tenant,owner,task.workflowId(),task.revision(),CatalogJson.JSON.writeValueAsString(task));}
  public Optional<WorkflowMetricStream.Batch> metricStreamBatch(String owner,UUID id){try(var q=prepare("SELECT workflow_id,revision,body,created_at FROM integration.workflow_metric_stream_batch WHERE tenant_id=? AND owner_subject=? AND batch_id=?",tenant,owner,id);var r=q.executeQuery()){if(!r.next())return Optional.empty();var batch=WorkflowMetricStreamJson.batch(r.getString("body"));if(!batch.id().equals(id)||!batch.workflowId().equals(r.getString("workflow_id"))||batch.revision()!=r.getInt("revision")||!batch.createdAt().equals(r.getTimestamp("created_at").toInstant()))throw unavailable();return Optional.of(batch);}catch(SQLException|IllegalArgumentException f){throw unavailable();}}
  public List<WorkflowMetricStream.Batch> metricStreamBatches(String owner,String id){try(var q=prepare("SELECT batch_id FROM integration.workflow_metric_stream_batch WHERE tenant_id=? AND owner_subject=? AND workflow_id=? ORDER BY created_at DESC,batch_id LIMIT 20",tenant,owner,id);var r=q.executeQuery()){var rows=new ArrayList<WorkflowMetricStream.Batch>();while(r.next())rows.add(metricStreamBatch(owner,r.getObject(1,UUID.class)).orElseThrow());return List.copyOf(rows);}catch(SQLException f){throw unavailable();}}
  public int metricStreamBatchCount(String owner){try(var q=prepare("SELECT count(*) FROM integration.workflow_metric_stream_batch WHERE tenant_id=? AND owner_subject=?",tenant,owner);var r=q.executeQuery()){r.next();return r.getInt(1);}catch(SQLException f){throw unavailable();}}
  public void addMetricStreamBatch(String owner,WorkflowMetricStream.Batch batch){if(batch.reconcilesBatchId()!=null)batch.requireReconciliation(metricStreamBatch(owner,batch.reconcilesBatchId()).orElseThrow());if(!Set.of("IN_FLIGHT","CONFIRMED").contains(batch.state()))throw unavailable();update("INSERT INTO integration.workflow_metric_stream_batch (tenant_id,owner_subject,batch_id,workflow_id,revision,body,created_at) VALUES (?,?,?,?,?,?::jsonb,?)",tenant,owner,batch.id(),batch.workflowId(),batch.revision(),CatalogJson.JSON.writeValueAsString(batch),Timestamp.from(batch.createdAt()));}
  public void finishMetricStreamBatch(String owner,WorkflowMetricStream.Batch batch){metricStreamBatch(owner,batch.id()).orElseThrow().requireSuccessor(batch);update("UPDATE integration.workflow_metric_stream_batch SET body=?::jsonb WHERE tenant_id=? AND owner_subject=? AND batch_id=?",CatalogJson.JSON.writeValueAsString(batch),tenant,owner,batch.id());}
  public Optional<WorkflowMetricStream.Receipt> metricStreamControl(String owner,UUID id){try(var q=prepare("SELECT workflow_id,body FROM integration.workflow_metric_stream_control WHERE tenant_id=? AND owner_subject=? AND request_id=?",tenant,owner,id);var r=q.executeQuery()){if(!r.next())return Optional.empty();var receipt=WorkflowMetricStreamJson.receipt(r.getString("body"));if(!receipt.requestId().equals(id)||!receipt.task().workflowId().equals(r.getString("workflow_id")))throw unavailable();return Optional.of(receipt);}catch(SQLException|IllegalArgumentException f){throw unavailable();}}
  public int metricStreamControlCount(String owner){try(var q=prepare("SELECT count(*) FROM integration.workflow_metric_stream_control WHERE tenant_id=? AND owner_subject=?",tenant,owner);var r=q.executeQuery()){r.next();return r.getInt(1);}catch(SQLException f){throw unavailable();}}
  public void addMetricStreamControl(String owner,WorkflowMetricStream.Receipt receipt){update("INSERT INTO integration.workflow_metric_stream_control (tenant_id,owner_subject,request_id,workflow_id,body) VALUES (?,?,?,?,?::jsonb)",tenant,owner,receipt.requestId(),receipt.task().workflowId(),CatalogJson.JSON.writeValueAsString(receipt));}
  public Optional<com.acme.opsweave.integration.domain.WorkflowLogOutput.Receipt> logOutput(String owner,UUID id){try(var s=prepare("SELECT workflow_id,revision,body,created_at FROM integration.workflow_log_output WHERE tenant_id=? AND owner_subject=? AND request_id=?",tenant,owner,id);var r=s.executeQuery()){if(!r.next())return Optional.empty();var value=com.acme.opsweave.platform.workflow.WorkflowLogOutputJson.decode(r.getString("body"));if(!value.requestId().equals(id)||!value.workflowId().equals(r.getString("workflow_id"))||value.revision()!=r.getInt("revision")||!value.createdAt().equals(r.getTimestamp("created_at").toInstant()))throw unavailable();return Optional.of(value);}catch(SQLException|IllegalArgumentException failure){throw unavailable();}}
  public int logOutputCount(String owner){try(var s=prepare("SELECT COUNT(*) FROM integration.workflow_log_output WHERE tenant_id=? AND owner_subject=?",tenant,owner);var r=s.executeQuery()){r.next();return r.getInt(1);}catch(SQLException failed){throw unavailable();}}
  public List<com.acme.opsweave.integration.domain.WorkflowLogOutput.Receipt> logOutputs(String owner,String workflowId){try(var s=prepare("SELECT request_id FROM integration.workflow_log_output WHERE tenant_id=? AND owner_subject=? AND workflow_id=? ORDER BY created_at DESC,request_id LIMIT 21",tenant,owner,workflowId);var r=s.executeQuery()){var result=new ArrayList<com.acme.opsweave.integration.domain.WorkflowLogOutput.Receipt>();while(r.next())result.add(logOutput(owner,r.getObject(1,UUID.class)).orElseThrow());return List.copyOf(result);}catch(SQLException|IllegalArgumentException failed){throw unavailable();}}
  public void addLogOutput(String owner,com.acme.opsweave.integration.domain.WorkflowLogOutput.Receipt value){update("INSERT INTO integration.workflow_log_output (tenant_id,owner_subject,request_id,workflow_id,revision,body,created_at) VALUES (?,?,?,?,?,?::jsonb,?)",tenant,owner,value.requestId(),value.workflowId(),value.revision(),CatalogJson.JSON.writeValueAsString(value),Timestamp.from(value.createdAt()));}
  public void finishLogOutput(String owner,com.acme.opsweave.integration.domain.WorkflowLogOutput.Receipt value){if(sampleRecoveryForBatch(owner,WorkflowSampleRecovery.Kind.LOG_SAMPLE,value.requestId()).isPresent())throw new com.acme.opsweave.integration.domain.WorkflowFailure(com.acme.opsweave.integration.domain.WorkflowFailure.Code.CONFLICT);logOutput(owner,value.requestId()).orElseThrow().requireSuccessor(value);update("UPDATE integration.workflow_log_output SET body=?::jsonb WHERE tenant_id=? AND owner_subject=? AND request_id=? AND body->>'state' IN ('PENDING','UNKNOWN')",CatalogJson.JSON.writeValueAsString(value),tenant,owner,value.requestId());}
  public Optional<com.acme.opsweave.integration.domain.WorkflowMetricOutput.Receipt> metricOutput(String owner,UUID id){try(var s=prepare("SELECT workflow_id,revision,body,created_at FROM integration.workflow_metric_output WHERE tenant_id=? AND owner_subject=? AND request_id=?",tenant,owner,id);var r=s.executeQuery()){if(!r.next())return Optional.empty();var receipt=com.acme.opsweave.platform.workflow.WorkflowMetricOutputJson.decode(r.getString("body"));if(!receipt.requestId().equals(id)||!receipt.workflowId().equals(r.getString("workflow_id"))||receipt.revision()!=r.getInt("revision")||!receipt.createdAt().equals(r.getTimestamp("created_at").toInstant()))throw unavailable();return Optional.of(receipt);}catch(SQLException|IllegalArgumentException failure){throw unavailable();}}
  public int metricOutputCount(String owner){try(var s=prepare("SELECT COUNT(*) FROM integration.workflow_metric_output WHERE tenant_id=? AND owner_subject=?",tenant,owner);var r=s.executeQuery()){r.next();return r.getInt(1);}catch(SQLException failed){throw unavailable();}}
  public List<com.acme.opsweave.integration.domain.WorkflowMetricOutput.Receipt> metricOutputs(String owner,String workflowId){try(var s=prepare("SELECT request_id FROM integration.workflow_metric_output WHERE tenant_id=? AND owner_subject=? AND workflow_id=? ORDER BY created_at DESC,request_id ASC LIMIT 21",tenant,owner,workflowId);var r=s.executeQuery()){var result=new ArrayList<com.acme.opsweave.integration.domain.WorkflowMetricOutput.Receipt>();while(r.next())result.add(metricOutput(owner,r.getObject(1,UUID.class)).orElseThrow());return List.copyOf(result);}catch(SQLException|IllegalArgumentException failure){throw unavailable();}}
  public void addMetricOutput(String owner,com.acme.opsweave.integration.domain.WorkflowMetricOutput.Receipt receipt){update("INSERT INTO integration.workflow_metric_output (tenant_id,owner_subject,request_id,workflow_id,revision,body,created_at) VALUES (?,?,?,?,?,?::jsonb,?)",tenant,owner,receipt.requestId(),receipt.workflowId(),receipt.revision(),CatalogJson.JSON.writeValueAsString(receipt),Timestamp.from(receipt.createdAt()));}
  public void finishMetricOutput(String owner,com.acme.opsweave.integration.domain.WorkflowMetricOutput.Receipt receipt){if(sampleRecoveryForBatch(owner,WorkflowSampleRecovery.Kind.METRIC_SAMPLE,receipt.requestId()).isPresent())throw new com.acme.opsweave.integration.domain.WorkflowFailure(com.acme.opsweave.integration.domain.WorkflowFailure.Code.CONFLICT);metricOutput(owner,receipt.requestId()).orElseThrow().requireSuccessor(receipt);update("UPDATE integration.workflow_metric_output SET body=?::jsonb WHERE tenant_id=? AND owner_subject=? AND request_id=? AND body->>'state' IN ('PENDING','UNKNOWN')",CatalogJson.JSON.writeValueAsString(receipt),tenant,owner,receipt.requestId());}
  public Optional<com.acme.opsweave.integration.domain.WorkflowHostScan.Checkpoint> hostCheckpoint(String owner,String id){try(var q=prepare("SELECT revision,body FROM integration.workflow_host_checkpoint WHERE tenant_id=? AND owner_subject=? AND workflow_id=?",tenant,owner,id);var r=q.executeQuery()){if(!r.next())return Optional.empty();var c=com.acme.opsweave.platform.workflow.WorkflowHostScanJson.checkpoint(r.getString("body"));if(!c.workflowId().equals(id)||c.revision()!=r.getInt("revision"))throw unavailable();return Optional.of(c);}catch(SQLException|IllegalArgumentException failure){throw unavailable();}}
  public void saveHostCheckpoint(String owner,com.acme.opsweave.integration.domain.WorkflowHostScan.Checkpoint c){update("INSERT INTO integration.workflow_host_checkpoint (tenant_id,owner_subject,workflow_id,revision,body) VALUES (?,?,?,?,?::jsonb) ON CONFLICT (tenant_id,owner_subject,workflow_id) DO UPDATE SET revision=EXCLUDED.revision,body=EXCLUDED.body",tenant,owner,c.workflowId(),c.revision(),CatalogJson.JSON.writeValueAsString(c));}
  public Optional<com.acme.opsweave.integration.domain.WorkflowHostScan.Batch> hostBatch(String owner,UUID id){try(var q=prepare("SELECT workflow_id,revision,body,updated_at FROM integration.workflow_host_batch WHERE tenant_id=? AND owner_subject=? AND batch_id=?",tenant,owner,id);var r=q.executeQuery()){if(!r.next())return Optional.empty();var b=com.acme.opsweave.platform.workflow.WorkflowHostScanJson.batch(r.getString("body"));if(!b.id().equals(id)||!b.workflowId().equals(r.getString("workflow_id"))||b.revision()!=r.getInt("revision")||!b.updatedAt().equals(r.getTimestamp("updated_at").toInstant()))throw unavailable();return Optional.of(b);}catch(SQLException|IllegalArgumentException failure){throw unavailable();}}
  public List<com.acme.opsweave.integration.domain.WorkflowHostScan.Batch> hostBatches(String owner,String id){try(var q=prepare("SELECT batch_id FROM integration.workflow_host_batch WHERE tenant_id=? AND owner_subject=? AND workflow_id=? ORDER BY updated_at DESC,batch_id LIMIT 20",tenant,owner,id);var r=q.executeQuery()){var result=new ArrayList<com.acme.opsweave.integration.domain.WorkflowHostScan.Batch>();while(r.next())result.add(hostBatch(owner,r.getObject(1,UUID.class)).orElseThrow());return List.copyOf(result);}catch(SQLException|IllegalArgumentException failure){throw unavailable();}}
  public int hostBatchCount(String owner){try(var q=prepare("SELECT COUNT(*) FROM integration.workflow_host_batch WHERE tenant_id=? AND owner_subject=?",tenant,owner);var r=q.executeQuery()){r.next();return r.getInt(1);}catch(SQLException failure){throw unavailable();}}
  public void addHostBatch(String owner,com.acme.opsweave.integration.domain.WorkflowHostScan.Batch b){if(!b.state().equals("READY"))throw new IllegalArgumentException();update("INSERT INTO integration.workflow_host_batch (tenant_id,owner_subject,batch_id,workflow_id,revision,body,updated_at) VALUES (?,?,?,?,?,?::jsonb,?)",tenant,owner,b.id(),b.workflowId(),b.revision(),CatalogJson.JSON.writeValueAsString(b),Timestamp.from(b.updatedAt()));}
  public void finishHostBatch(String owner,com.acme.opsweave.integration.domain.WorkflowHostScan.Batch b){hostBatch(owner,b.id()).orElseThrow().requireSuccessor(b);update("UPDATE integration.workflow_host_batch SET body=?::jsonb,updated_at=? WHERE tenant_id=? AND owner_subject=? AND batch_id=?",CatalogJson.JSON.writeValueAsString(b),Timestamp.from(b.updatedAt()),tenant,owner,b.id());}
  public Optional<com.acme.opsweave.integration.domain.WorkflowRuntime.Task> task(String owner,String id){return tasks(owner).stream().filter(t->t.workflowId().equals(id)).findFirst();}
  public List<com.acme.opsweave.integration.domain.WorkflowRuntime.Task> tasks(String owner){try(var s=prepare("SELECT workflow_id,body FROM integration.workflow_task WHERE tenant_id=? AND owner_subject=? ORDER BY updated_at DESC,workflow_id LIMIT 21",tenant,owner);var r=s.executeQuery()){var result=new ArrayList<com.acme.opsweave.integration.domain.WorkflowRuntime.Task>();while(r.next()){var t=com.acme.opsweave.platform.workflow.WorkflowRuntimeJson.task(r.getString("body"));if(!t.workflowId().equals(r.getString("workflow_id")))throw unavailable();result.add(t);}return List.copyOf(result);}catch(SQLException|IllegalArgumentException failure){throw unavailable();}}
  public void saveTask(String owner,com.acme.opsweave.integration.domain.WorkflowRuntime.Task t){update("INSERT INTO integration.workflow_task (tenant_id,owner_subject,workflow_id,body,updated_at) VALUES (?,?,?,?::jsonb,?) ON CONFLICT (tenant_id,owner_subject,workflow_id) DO UPDATE SET body=EXCLUDED.body,updated_at=EXCLUDED.updated_at",tenant,owner,t.workflowId(),CatalogJson.JSON.writeValueAsString(t),Timestamp.from(t.updatedAt()));}
  public Optional<com.acme.opsweave.integration.domain.WorkflowRuntimeControl.Receipt> runtimeControl(String owner,UUID id){try(var s=prepare("SELECT workflow_id,body,created_at FROM integration.workflow_control_command WHERE tenant_id=? AND owner_subject=? AND request_id=?",tenant,owner,id);var r=s.executeQuery()){if(!r.next())return Optional.empty();var receipt=com.acme.opsweave.platform.workflow.WorkflowRuntimeJson.control(r.getString("body"));if(!receipt.requestId().equals(id)||!receipt.task().workflowId().equals(r.getString("workflow_id"))||!receipt.createdAt().equals(r.getTimestamp("created_at").toInstant()))throw unavailable();return Optional.of(receipt);}catch(SQLException|IllegalArgumentException failure){throw unavailable();}}
  public int runtimeControlCount(String owner){try(var s=prepare("SELECT count(*) FROM integration.workflow_control_command WHERE tenant_id=? AND owner_subject=?",tenant,owner);var r=s.executeQuery()){r.next();return r.getInt(1);}catch(SQLException failure){throw unavailable();}}
  public void addRuntimeControl(String owner,com.acme.opsweave.integration.domain.WorkflowRuntimeControl.Receipt receipt){update("INSERT INTO integration.workflow_control_command (tenant_id,owner_subject,request_id,workflow_id,body,created_at) VALUES (?,?,?,?,?::jsonb,?)",tenant,owner,receipt.requestId(),receipt.task().workflowId(),CatalogJson.JSON.writeValueAsString(receipt),Timestamp.from(receipt.createdAt()));}
  public Optional<com.acme.opsweave.integration.domain.WorkflowRuntime.Execution> execution(String owner,UUID id){try(var s=prepare("SELECT body FROM integration.workflow_execution WHERE tenant_id=? AND owner_subject=? AND execution_id=?",tenant,owner,id);var r=s.executeQuery()){if(!r.next())return Optional.empty();var x=com.acme.opsweave.platform.workflow.WorkflowRuntimeJson.execution(r.getString("body"));if(!x.id().equals(id))throw unavailable();return Optional.of(x);}catch(SQLException|IllegalArgumentException failure){throw unavailable();}}
  public List<com.acme.opsweave.integration.domain.WorkflowRuntime.Execution> executions(String owner){try(var s=prepare("SELECT execution_id,body FROM integration.workflow_execution WHERE tenant_id=? AND owner_subject=? ORDER BY created_at DESC,execution_id LIMIT 201",tenant,owner);var r=s.executeQuery()){var result=new ArrayList<com.acme.opsweave.integration.domain.WorkflowRuntime.Execution>();while(r.next()){var x=com.acme.opsweave.platform.workflow.WorkflowRuntimeJson.execution(r.getString("body"));if(!x.id().equals(r.getObject("execution_id",UUID.class)))throw unavailable();result.add(x);}return List.copyOf(result);}catch(SQLException|IllegalArgumentException failure){throw unavailable();}}
  public void addExecution(String owner,com.acme.opsweave.integration.domain.WorkflowRuntime.Execution x){update("INSERT INTO integration.workflow_execution (tenant_id,owner_subject,execution_id,body,created_at) VALUES (?,?,?,?::jsonb,?)",tenant,owner,x.id(),CatalogJson.JSON.writeValueAsString(x),Timestamp.from(x.createdAt()));}
  private void update(String sql,Object...args){try(var s=prepare(sql,args)){if(s.executeUpdate()!=1)throw unavailable();}catch(SQLException failure){throw unavailable();}}
  private PreparedStatement prepare(String sql,Object...args)throws SQLException{var s=connection.prepareStatement(sql);s.setQueryTimeout(5);for(int i=0;i<args.length;i++)s.setObject(i+1,args[i]);return s;}
 }
 private static IllegalStateException unavailable(){return new IllegalStateException("Workflow store unavailable");}
}
