package com.acme.opsweave.platform.persistence;

import static org.junit.jupiter.api.Assertions.*;
import com.acme.opsweave.identity.domain.*;
import com.acme.opsweave.integration.api.WorkflowStore;
import com.acme.opsweave.integration.application.*;
import com.acme.opsweave.integration.domain.*;
import com.acme.opsweave.platform.OpsweaveProperties;
import com.acme.opsweave.platform.catalog.CatalogJson;
import com.acme.opsweave.sharedkernel.TenantId;
import java.time.*;
import java.nio.file.*;
import java.util.*;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.condition.EnabledIfEnvironmentVariable;
import org.springframework.jdbc.datasource.DriverManagerDataSource;

/** Actual PostgreSQL, explicitly synthetic validation input. No provider connectivity claim. */
@EnabledIfEnvironmentVariable(named="OPSWEAVE_TEST_JDBC_URL",matches=".+")
class PostgresWorkflowDiagnosticsIT extends OwnedInventoryTest {
    final TenantId tenant=new TenantId("diagnostic-pg-fixture-"+UUID.randomUUID());final String owner="diagnostic-author";
    final DriverManagerDataSource source=new DriverManagerDataSource(System.getenv("OPSWEAVE_TEST_JDBC_URL"),System.getenv("OPSWEAVE_TEST_JDBC_USER"),System.getenv("OPSWEAVE_TEST_JDBC_PASSWORD"));
    final InventoryWiring wiring=openInventory(new OpsweaveProperties(new OpsweaveProperties.Auth("closed",true,new OpsweaveProperties.Auth.Dev("","",tenant.value(),"","")),new OpsweaveProperties.Zabbix("fixture","","env:OPSWEAVE_ZABBIX_TOKEN","diagnostic-fixture",1),new OpsweaveProperties.Inventory("postgres",System.getenv("OPSWEAVE_TEST_JDBC_URL"),System.getenv("OPSWEAVE_TEST_JDBC_USER"),System.getenv("OPSWEAVE_TEST_JDBC_PASSWORD"))));
    final Principal p=new Principal(new SubjectId(owner),tenant,Set.of(Permission.SOURCE_SYNC,Permission.LOG_READ),ResourceScope.tenantWide());
    static final Instant FROM=Instant.parse("2026-10-05T00:00:00Z"),TILL=FROM.plusSeconds(60),NOW=TILL.plusSeconds(10);
    WorkflowDefinition definition(int revision){
        var id=UUID.randomUUID();var src=new WorkflowDefinition.Source("ZABBIX_LOG",id.toString(),new WorkflowDefinition.ConfigurationPin(id,1,"sha256:"+"a".repeat(64)),null,WorkflowLogSourcePin.from(UUID.randomUUID(),new SourceMetricDiscovery.Item("1","2","log[/synthetic-fixture]","Synthetic Fixture","","LOG","NO_MAPPING",null)));
        var nodes=List.of(new WorkflowDefinition.Node("source",WorkflowDefinition.Type.SOURCE,"1",Map.of()),new WorkflowDefinition.Node("map",WorkflowDefinition.Type.MAP,"1",Map.of("timestamp","eventTime","body","body")),new WorkflowDefinition.Node("validate",WorkflowDefinition.Type.VALIDATE,"1",Map.of()),new WorkflowDefinition.Node("output",WorkflowDefinition.Type.OUTPUT,"1",Map.of()));
        var d=WorkflowOperators.builtIn().pin(new WorkflowDefinition("diagnostic-fixture",revision,"Synthetic Fixture",src,new WorkflowDefinition.Target(null,1,null,"LOG"),nodes,List.of(new WorkflowDefinition.Edge("source","map"),new WorkflowDefinition.Edge("map","validate"),new WorkflowDefinition.Edge("validate","output"))));var layout=new HashMap<String,WorkflowStore.Position>();for(var n:nodes)layout.put(n.id(),new WorkflowStore.Position(0,0));wiring.workflows().transaction(tenant,s->{s.publish(new WorkflowStore.Entry(d,d.digest(),"PUBLISHED",0,layout,NOW,null),owner);return null;});return d;
    }
    WorkflowDiagnosticService read(WorkflowStore store){var guards=new WorkflowService.Sources(){public void require(Principal who,WorkflowDefinition.Source src,WorkflowStore.Session s,boolean available){assertFalse(available);}public void requireTarget(Principal who,WorkflowDefinition.Source src,WorkflowDefinition.Target target,WorkflowStore.Session s,boolean available){assertFalse(available);}};var flows=new WorkflowService(store,(who,target)->{throw new AssertionError("No model execution");},(who,src,id)->{throw new AssertionError("No source read");},guards,Clock.fixed(NOW,ZoneOffset.UTC));return new WorkflowDiagnosticService(store,flows,Clock.fixed(NOW,ZoneOffset.UTC));}
    WorkflowDiagnostics.Stored proof(WorkflowDefinition d){var result=new WorkflowDiagnostics.Result("PARTIAL",null,10,4,1,0,5,1,0,0,null,List.of(new WorkflowDiagnostics.Node("source",WorkflowDefinition.Type.SOURCE,5,5,0,0,0,Map.of()),new WorkflowDiagnostics.Node("validate",WorkflowDefinition.Type.VALIDATE,5,4,1,0,0,Map.of("EMPTY_REQUIRED",1))));return new WorkflowDiagnostics.Stored(new WorkflowDiagnostics.Observation(UUID.randomUUID(),new WorkflowQuality.Reference(d.id(),d.revision(),d.digest()),WorkflowQuality.Kind.LOG_STREAM,1,"REJECTED",FROM,TILL,NOW,NOW,null,null,"INVALID_SAMPLE",result),List.of());}
    @Test void appendIsImmutableTransactionalScopedAndFixedVersionFilteredBeforeLimit(){
        var d=definition(1);var next=definition(2);var first=proof(d);assertThrows(IllegalStateException.class,()->wiring.workflows().transaction(tenant,s->{s.addDiagnostic(owner,first);throw new IllegalStateException("Synthetic rollback");}));assertTrue(wiring.workflows().transaction(tenant,s->s.diagnostic(owner,first.observation().id())).isEmpty());
        wiring.workflows().transaction(tenant,s->{s.addDiagnostic(owner,first);for(int i=0;i<20;i++)s.addDiagnostic(owner,proof(d));for(int i=0;i<25;i++)s.addDiagnostic(owner,proof(next));return null;});var reopened=new PostgresWorkflowStore(source);var service=read(reopened);var report=service.report(p,d.id(),1);assertEquals(20,report.observations().size());assertTrue(report.truncated());assertTrue(report.observations().stream().allMatch(o->o.reference().revision()==1));assertEquals(first.observation(),service.observation(p,d.id(),1,first.observation().id()));
        assertThrows(IllegalStateException.class,()->reopened.transaction(tenant,s->{s.addDiagnostic(owner,first);return null;}));assertEquals(46,reopened.<Integer>transaction(tenant,s->s.diagnosticCount(owner)).intValue());assertTrue(reopened.transaction(new TenantId(tenant.value()+"-other"),s->s.diagnostic(owner,first.observation().id())).isEmpty());var other=new Principal(new SubjectId("other"),tenant,p.permissions(),p.resourceScope());assertTrue(service.report(other,d.id(),1).observations().isEmpty());assertEquals(WorkflowFailure.Code.NOT_FOUND,assertThrows(WorkflowFailure.class,()->service.observation(other,d.id(),1,first.observation().id())).code());assertEquals(WorkflowFailure.Code.NOT_FOUND,assertThrows(WorkflowFailure.class,()->service.observation(p,d.id(),2,first.observation().id())).code());var denied=new Principal(p.subjectId(),tenant,Set.of(Permission.SOURCE_SYNC),p.resourceScope());assertEquals(WorkflowFailure.Code.FORBIDDEN,assertThrows(WorkflowFailure.class,()->service.report(denied,d.id(),1)).code());assertFalse(CatalogJson.JSON.writeValueAsString(report).contains("entityIds"));
    }
    @Test void corruptMetadataFailsClosedRatherThanReturningEmpty()throws Exception{
        var typed=proof(definition(2));assertThrows(IllegalArgumentException.class,()->com.acme.opsweave.platform.workflow.WorkflowDiagnosticsJson.decode(CatalogJson.JSON.writeValueAsString(typed).replace("\"unitMismatch\":null","\"unitMismatch\":0")));
        var d=definition(1);var proof=proof(d);wiring.workflows().transaction(tenant,s->{s.addDiagnostic(owner,proof);return null;});try(var c=source.getConnection();var q=c.prepareStatement("UPDATE integration.workflow_diagnostic SET body=jsonb_set(body,'{observation,raw}',to_jsonb(?::text)) WHERE tenant_id=? AND observation_id=?")){q.setString(1,"Synthetic Fixture private");q.setString(2,tenant.value());q.setObject(3,proof.observation().id());assertEquals(1,q.executeUpdate());}assertThrows(IllegalStateException.class,()->read(new PostgresWorkflowStore(source)).report(p,d.id(),1));
    }
    @Test void metadataCapacityIsCheckedBeforeSourceAndUnknownSourceRetainsNullCounts(){
        var d=definition(1);var recorder=new WorkflowDiagnosticRecorder(wiring.workflows(),Clock.fixed(NOW,ZoneOffset.UTC));var calls=new int[]{0};var ref=new WorkflowQuality.Reference(d.id(),1,d.digest());var error=assertThrows(WorkflowFailure.class,()->recorder.inspect(tenant,owner,ref,WorkflowQuality.Kind.LOG_STREAM,1,FROM,TILL,null,s->true,(consumer,at)->{calls[0]++;throw new WorkflowFailure(WorkflowFailure.Code.SOURCE_UNAVAILABLE);}));assertEquals(WorkflowFailure.Code.SOURCE_UNAVAILABLE,error.code());var stored=read(new PostgresWorkflowStore(source)).report(p,d.id(),1).observations().getFirst();assertEquals("SOURCE_FAILED",stored.state());assertNull(stored.result().received());assertEquals(List.of(),stored.result().nodes());wiring.workflows().transaction(tenant,s->{for(int i=1;i<200;i++)s.addDiagnostic(owner,proof(d));return null;});assertEquals(WorkflowFailure.Code.CAPACITY,assertThrows(WorkflowFailure.class,()->recorder.inspect(tenant,owner,ref,WorkflowQuality.Kind.LOG_STREAM,1,FROM,TILL,null,s->true,(consumer,at)->{calls[0]++;return null;})).code());assertEquals(1,calls[0]);
    }
    @Test void migrationForwardRollbackAndReapplyPreservePublishedVersionTable()throws Exception{
        var schema="diagnostic_migration_fixture_"+UUID.randomUUID().toString().replace("-","");assertTrue(schema.matches("diagnostic_migration_fixture_[a-f0-9]{32}"));var forward=Files.readString(Path.of("../../db/migrations/platform/V049__workflow_diagnostics.sql")).replace("integration.",schema+".");var reverse=Files.readString(Path.of("../../db/rollback/platform/V049__workflow_diagnostics.sql")).replace("integration.",schema+".");
        try(var c=source.getConnection()){c.setAutoCommit(false);try(var q=c.createStatement()){q.execute("CREATE SCHEMA "+schema);q.execute("CREATE TABLE "+schema+".workflow_version(tenant_id text,workflow_id text,revision integer,PRIMARY KEY(tenant_id,workflow_id,revision))");q.execute("INSERT INTO "+schema+".workflow_version VALUES ('fixture','fixed',1)");q.execute(forward);q.execute(reverse);q.execute(forward);try(var r=q.executeQuery("SELECT count(*) FROM "+schema+".workflow_version")){r.next();assertEquals(1,r.getInt(1));}try(var r=q.executeQuery("SELECT count(*) FROM "+schema+".workflow_diagnostic")){r.next();assertEquals(0,r.getInt(1));}}finally{c.rollback();}}
    }

 @Test void measuredSourceFailureIsDurableAndLegacyWireIsUnchanged()throws Exception{
  var d=definition(1);var recorder=new WorkflowDiagnosticRecorder(wiring.workflows(),Clock.fixed(NOW,ZoneOffset.UTC));var ref=new WorkflowQuality.Reference(d.id(),1,d.digest());var calls=new int[]{0};assertEquals(WorkflowFailure.Code.SOURCE_CHANGED,assertThrows(WorkflowFailure.class,()->recorder.inspectSource(tenant,owner,ref,WorkflowQuality.Kind.LOG_STREAM,1,FROM,TILL,null,t->true,(inspection,at)->inspection.source().read(()->{calls[0]++;throw WorkflowFailure.sourceChanged(WorkflowDiagnostics.SourceFailure.UNIT_CHANGED);}))).code());assertEquals(1,calls[0]);var reopened=new PostgresWorkflowStore(source);var observed=read(reopened).report(p,d.id(),1).observations().getFirst();assertNull(observed.result().received());assertEquals(1,observed.sourceRead().attempts());assertEquals(1,observed.sourceRead().failed());assertNull(observed.sourceRead().received());assertEquals(WorkflowDiagnostics.SourceFailure.UNIT_CHANGED,observed.sourceRead().failureCode());assertEquals(observed,read(reopened).observation(p,d.id(),1,observed.id()));assertTrue(CatalogJson.JSON.readTree(CatalogJson.JSON.writeValueAsString(com.acme.opsweave.platform.workflow.WorkflowDiagnosticsJson.wire(observed))).has("sourceRead"));
  var legacy=proof(d);var encoded=CatalogJson.JSON.writeValueAsString(legacy);var oldTree=CatalogJson.JSON.readTree(encoded).deepCopy();((tools.jackson.databind.node.ObjectNode)oldTree.get("observation")).remove("sourceRead");((tools.jackson.databind.node.ObjectNode)oldTree.get("observation")).remove("dispatch");var old=com.acme.opsweave.platform.workflow.WorkflowDiagnosticsJson.decode(oldTree.toString());assertNull(old.observation().sourceRead());assertEquals(legacy,old);var wire=CatalogJson.JSON.readTree(CatalogJson.JSON.writeValueAsString(com.acme.opsweave.platform.workflow.WorkflowDiagnosticsJson.wire(old.observation())));assertFalse(wire.has("sourceRead"));assertEquals(13,wire.size());
  try(var c=source.getConnection();var q=c.prepareStatement("UPDATE integration.workflow_diagnostic SET body=jsonb_set(body,'{observation,sourceRead,received}','0'::jsonb) WHERE tenant_id=? AND observation_id=?")){q.setString(1,tenant.value());q.setObject(2,observed.id());assertEquals(1,q.executeUpdate());}assertThrows(IllegalStateException.class,()->read(reopened).observation(p,d.id(),1,observed.id()));
 }
}

