package com.acme.opsweave.platform.persistence;
import static org.junit.jupiter.api.Assertions.*;
import com.acme.opsweave.integration.domain.*;
import com.acme.opsweave.integration.domain.WorkflowLogOutput.Receipt;
import com.acme.opsweave.integration.api.WorkflowStore;
import com.acme.opsweave.platform.OpsweaveProperties;
import com.acme.opsweave.sharedkernel.TenantId;
import java.time.*;
import java.util.*;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.condition.EnabledIfEnvironmentVariable;
import org.springframework.jdbc.datasource.DriverManagerDataSource;
/** Actual PG metadata transactions, with synthetic versions; no log text stored in receipts. */
@EnabledIfEnvironmentVariable(named="OPSWEAVE_TEST_JDBC_URL",matches=".+")
class PostgresWorkflowLogOutputIT extends OwnedInventoryTest{
 final TenantId tenant=new TenantId("logs-pg-fixture-"+UUID.randomUUID());final String owner="logs-pg-author";
 final DriverManagerDataSource source=new DriverManagerDataSource(System.getenv("OPSWEAVE_TEST_JDBC_URL"),System.getenv("OPSWEAVE_TEST_JDBC_USER"),System.getenv("OPSWEAVE_TEST_JDBC_PASSWORD"));
 final InventoryWiring wiring=openInventory(new OpsweaveProperties(new OpsweaveProperties.Auth("closed",true,new OpsweaveProperties.Auth.Dev("","",tenant.value(),"","")),new OpsweaveProperties.Zabbix("fixture","","env:OPSWEAVE_ZABBIX_TOKEN","logs-fixture",1),new OpsweaveProperties.Inventory("postgres",System.getenv("OPSWEAVE_TEST_JDBC_URL"),System.getenv("OPSWEAVE_TEST_JDBC_USER"),System.getenv("OPSWEAVE_TEST_JDBC_PASSWORD"))));
 Receipt prepare(){var nodes=List.of(new WorkflowDefinition.Node("source",WorkflowDefinition.Type.SOURCE,"1",Map.of()),new WorkflowDefinition.Node("map",WorkflowDefinition.Type.MAP,"1",Map.of("eventTime","eventTime","body","body")),new WorkflowDefinition.Node("validate",WorkflowDefinition.Type.VALIDATE,"1",Map.of()),new WorkflowDefinition.Node("output",WorkflowDefinition.Type.OUTPUT,"1",Map.of()));var d=WorkflowOperators.builtIn().pin(new WorkflowDefinition("logs-pg",1,"Fixture metadata",new WorkflowDefinition.Source("MANUAL_SAMPLE","manual"),new WorkflowDefinition.Target(null,1,null,"LOG"),nodes,List.of(new WorkflowDefinition.Edge("source","map"),new WorkflowDefinition.Edge("map","validate"),new WorkflowDefinition.Edge("validate","output"))));var now=Instant.now().truncatedTo(java.time.temporal.ChronoUnit.MICROS);var layout=new HashMap<String,WorkflowStore.Position>();for(var n:nodes)layout.put(n.id(),new WorkflowStore.Position(0,0));wiring.workflows().transaction(tenant,s->{s.publish(new WorkflowStore.Entry(d,d.digest(),"PUBLISHED",0,layout,now,null),owner);return null;});return new Receipt(UUID.randomUUID(),d.id(),1,d.digest(),UUID.randomUUID(),"sha256:"+"a".repeat(64),now,now,"PENDING",2,1,0,0,2,null,"sha256:"+"b".repeat(64),List.of(0,2));}
 @Test void durableAdmissionRollsBackAndReopenedStoreConfirmsOnlyOriginalBatch(){var original=prepare();assertThrows(IllegalStateException.class,()->wiring.workflows().transaction(tenant,s->{s.addLogOutput(owner,original);throw new IllegalStateException("Fixture rollback");}));assertTrue(wiring.workflows().transaction(tenant,s->s.logOutput(owner,original.requestId())).isEmpty());wiring.workflows().transaction(tenant,s->{s.addLogOutput(owner,original);return null;});var unknown=original.finish("UNKNOWN","OUTPUT_UNCONFIRMED",original.createdAt().plusSeconds(1));wiring.workflows().transaction(tenant,s->{s.finishLogOutput(owner,unknown);return null;});var reopened=new PostgresWorkflowStore(source);assertEquals(unknown,reopened.transaction(tenant,s->s.logOutput(owner,original.requestId()).orElseThrow()));assertEquals(List.of(unknown),reopened.transaction(tenant,s->s.logOutputs(owner,original.workflowId())));assertTrue(reopened.transaction(tenant,s->s.logOutput("other",original.requestId())).isEmpty());assertTrue(reopened.transaction(new TenantId(tenant.value()+"-other"),s->s.logOutput(owner,original.requestId())).isEmpty());assertThrows(IllegalStateException.class,()->reopened.transaction(tenant,s->{s.finishLogOutput(owner,unknown.finish("FAILED","OUTPUT_REJECTED",unknown.updatedAt()));return null;}));var confirmed=unknown.finish("CONFIRMED",null,unknown.updatedAt().plusSeconds(1));reopened.transaction(tenant,s->{s.finishLogOutput(owner,confirmed);return null;});assertEquals(confirmed,wiring.workflows().transaction(tenant,s->s.logOutput(owner,original.requestId()).orElseThrow()));assertThrows(IllegalStateException.class,()->reopened.transaction(tenant,s->{s.finishLogOutput(owner,unknown);return null;}));}
 @Test void corruptMetadataAndLogTextInjectionCannotBecomeAReceipt()throws Exception{var r=prepare();wiring.workflows().transaction(tenant,s->{s.addLogOutput(owner,r);return null;});try(var c=source.getConnection();var sql=c.prepareStatement("UPDATE integration.workflow_log_output SET body=jsonb_set(body,'{body}',to_jsonb(?::text)) WHERE tenant_id=? AND request_id=?")){sql.setString(1,"Fixture private text");sql.setString(2,tenant.value());sql.setObject(3,r.requestId());assertEquals(1,sql.executeUpdate());}assertThrows(IllegalStateException.class,()->wiring.workflows().transaction(tenant,s->s.logOutput(owner,r.requestId())));}

 @Test void sampleClosureIsDurableScopedAndPreservesOriginalProof()throws Exception{
  var original=prepare();var unknown=original.finish("UNKNOWN","OUTPUT_UNCONFIRMED",original.createdAt());wiring.workflows().transaction(tenant,t->{t.addLogOutput(owner,unknown);return null;});
  var p=new com.acme.opsweave.identity.domain.Principal(new com.acme.opsweave.identity.domain.SubjectId(owner),tenant,Set.of(com.acme.opsweave.identity.domain.Permission.SOURCE_SYNC,com.acme.opsweave.identity.domain.Permission.METRIC_READ,com.acme.opsweave.identity.domain.Permission.LOG_READ,com.acme.opsweave.identity.domain.Permission.LOG_WRITE),com.acme.opsweave.identity.domain.ResourceScope.tenantWide());
  var c=new WorkflowSampleRecovery.Command(UUID.randomUUID(),unknown.workflowId(),1,unknown.digest(),WorkflowSampleRecovery.Kind.LOG_SAMPLE,unknown.requestId(),unknown.batchDigest(),unknown.updatedAt(),true);
  var service=new com.acme.opsweave.integration.application.WorkflowSampleRecoveryService(wiring.workflows(),Clock.systemUTC());assertNull(service.status(p,c.kind(),c.batchId()).closure());var receipt=service.abandon(p,c);assertEquals("ABANDONED",receipt.state());assertEquals(c.commandDigest(),receipt.commandDigest());
  var reopened=new PostgresWorkflowStore(source);var read=new com.acme.opsweave.integration.application.WorkflowSampleRecoveryService(reopened,Clock.systemUTC());assertEquals(receipt,read.receipt(p,c.requestId()));assertEquals(receipt,read.abandon(p,c));assertEquals(receipt,read.status(p,c.kind(),c.batchId()).closure());assertEquals(unknown,reopened.transaction(tenant,t->t.logOutput(owner,c.batchId()).orElseThrow()));
  assertTrue(reopened.transaction(tenant,t->t.sampleRecovery("other",c.requestId())).isEmpty());assertTrue(reopened.transaction(new TenantId(tenant.value()+"-other"),t->t.sampleRecovery(owner,c.requestId())).isEmpty());
  var conflict=assertThrows(WorkflowFailure.class,()->reopened.transaction(tenant,t->{t.finishLogOutput(owner,unknown.finish("CONFIRMED",null,unknown.updatedAt().plusSeconds(1)));return null;}));assertEquals(WorkflowFailure.Code.CONFLICT,conflict.code());assertEquals(unknown,reopened.transaction(tenant,t->t.logOutput(owner,c.batchId()).orElseThrow()));
  try(var connection=source.getConnection();var sql=connection.prepareStatement("UPDATE integration.workflow_sample_recovery SET body=jsonb_set(body,'{batchId}',to_jsonb(?::text)) WHERE tenant_id=? AND request_id=?")){sql.setString(1,UUID.randomUUID().toString());sql.setString(2,tenant.value());sql.setObject(3,c.requestId());assertEquals(1,sql.executeUpdate());}assertThrows(IllegalStateException.class,()->read.receipt(p,c.requestId()));
 }

 @Test @EnabledIfEnvironmentVariable(named="OPSWEAVE_TEST_LOGS_URL",matches=".+") void actualLogRowsSurviveSampleClosure(){
  var original=prepare();var scope=new WorkflowLogOutput.Scope(tenant.value(),WorkflowDefinition.hash(List.of(owner)).substring(7),original.requestId(),original.workflowId(),1,original.digest());var rows=List.of(new WorkflowLogOutput.Record(0,original.createdAt().toString(),"Synthetic sample closure Fixture one","INFO",null,null,null),new WorkflowLogOutput.Record(2,original.createdAt().toString(),"Synthetic sample closure Fixture two","INFO",null,null,null));var batch=new WorkflowLogOutput.Batch(scope,rows);var sink=new com.acme.opsweave.platform.telemetry.ClickHouseWorkflowLogSink(java.net.URI.create(System.getenv("OPSWEAVE_TEST_LOGS_URL")),System.getenv("OPSWEAVE_TEST_LOGS_USER"),System.getenv("OPSWEAVE_TEST_LOGS_PASSWORD"));assertTrue(sink.ready());sink.write(batch);
  var unknown=new Receipt(original.requestId(),original.workflowId(),1,original.digest(),original.previewId(),original.commandDigest(),original.createdAt(),original.updatedAt(),"UNKNOWN",2,1,0,0,2,"OUTPUT_UNCONFIRMED",batch.digest(),List.of(0,2));wiring.workflows().transaction(tenant,t->{t.addLogOutput(owner,unknown);return null;});

  var principal=new com.acme.opsweave.identity.domain.Principal(new com.acme.opsweave.identity.domain.SubjectId(owner),tenant,Set.of(com.acme.opsweave.identity.domain.Permission.SOURCE_SYNC,com.acme.opsweave.identity.domain.Permission.METRIC_READ,com.acme.opsweave.identity.domain.Permission.LOG_READ,com.acme.opsweave.identity.domain.Permission.LOG_WRITE),com.acme.opsweave.identity.domain.ResourceScope.tenantWide());
  var command=new WorkflowSampleRecovery.Command(UUID.randomUUID(),unknown.workflowId(),1,unknown.digest(),WorkflowSampleRecovery.Kind.LOG_SAMPLE,unknown.requestId(),unknown.batchDigest(),unknown.updatedAt(),true);var service=new com.acme.opsweave.integration.application.WorkflowSampleRecoveryService(wiring.workflows(),Clock.systemUTC());var receipt=service.abandon(principal,command);assertEquals(receipt,service.abandon(principal,command));assertEquals("UNKNOWN",new PostgresWorkflowStore(source).transaction(tenant,t->t.logOutput(owner,unknown.requestId()).orElseThrow()).state());

  var persisted=sink.read(scope);assertEquals(rows,persisted);assertEquals(unknown.batchDigest(),new WorkflowLogOutput.Batch(scope,persisted).digest());assertEquals(unknown,wiring.workflows().transaction(tenant,t->t.logOutput(owner,unknown.requestId()).orElseThrow()));
 }
}
