package com.acme.opsweave.platform.persistence;

import static org.junit.jupiter.api.Assertions.*;
import com.acme.opsweave.catalog.domain.ModelDefinition;
import com.acme.opsweave.integration.api.WorkflowStore;
import com.acme.opsweave.integration.application.*;
import com.acme.opsweave.integration.domain.*;
import com.acme.opsweave.integration.domain.WorkflowHostScan.*;
import com.acme.opsweave.identity.domain.*;
import com.acme.opsweave.platform.OpsweaveProperties;
import com.acme.opsweave.sharedkernel.TenantId;
import java.time.*;
import java.util.*;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.condition.EnabledIfEnvironmentVariable;
import org.springframework.jdbc.datasource.DriverManagerDataSource;

/** Actual PostgreSQL journal and inventory; source rows and failures are explicit fixtures. */
@EnabledIfEnvironmentVariable(named="OPSWEAVE_TEST_JDBC_URL",matches=".+")
class PostgresWorkflowHostRuntimeIT extends OwnedInventoryTest {
 final TenantId tenant=new TenantId("host-batch-pg-fixture-"+UUID.randomUUID());final String owner="host-batch-fixture-author";
 final DriverManagerDataSource source=new DriverManagerDataSource(System.getenv("OPSWEAVE_TEST_JDBC_URL"),System.getenv("OPSWEAVE_TEST_JDBC_USER"),System.getenv("OPSWEAVE_TEST_JDBC_PASSWORD"));
 final InventoryWiring wiring=openInventory(new OpsweaveProperties(new OpsweaveProperties.Auth("closed",true,new OpsweaveProperties.Auth.Dev("","",tenant.value(),"","")),new OpsweaveProperties.Zabbix("fixture","","env:OPSWEAVE_ZABBIX_TOKEN","host-fixture",1),new OpsweaveProperties.Inventory("postgres",System.getenv("OPSWEAVE_TEST_JDBC_URL"),System.getenv("OPSWEAVE_TEST_JDBC_USER"),System.getenv("OPSWEAVE_TEST_JDBC_PASSWORD"))));
 final Principal p=new Principal(new SubjectId(owner),tenant,Set.of(Permission.SOURCE_SYNC,Permission.ENTITY_READ,Permission.ENTITY_MANAGE),ResourceScope.tenantWide());
 final ModelDefinition model=new ModelDefinition("custom.host_batch",1,ModelDefinition.Kind.ENTITY,"Fixture","fixture",List.of(new ModelDefinition.Field("name","Name",ModelDefinition.Type.TEXT,true,255,null,null,List.of())),null);
 final WorkflowRuntime.Settings settings=new WorkflowRuntime.Settings("entity_id","name");
 final WorkflowDefinition d=definition();int reads,writes;boolean failAfterWrite,revoked;
 WorkflowDefinition definition(){var nodes=List.of(new WorkflowDefinition.Node("source",WorkflowDefinition.Type.SOURCE,"1",Map.of()),new WorkflowDefinition.Node("map",WorkflowDefinition.Type.MAP,"1",Map.of("name","name")),new WorkflowDefinition.Node("validate",WorkflowDefinition.Type.VALIDATE,"1",Map.of()),new WorkflowDefinition.Node("output",WorkflowDefinition.Type.OUTPUT,"1",Map.of()));return WorkflowOperators.builtIn().pin(new WorkflowDefinition("fixture-host-batches",1,"Fixture host batches",new WorkflowDefinition.Source("ZABBIX_HOST","host-fixture",new WorkflowDefinition.ConfigurationPin(UUID.randomUUID(),1,"sha256:"+"a".repeat(64))),new WorkflowDefinition.Target(model.id(),1,model.digest()),nodes,List.of(new WorkflowDefinition.Edge("source","map"),new WorkflowDefinition.Edge("map","validate"),new WorkflowDefinition.Edge("validate","output"))));}
 void publish(){var layout=new HashMap<String,WorkflowStore.Position>();for(var n:d.nodes())layout.put(n.id(),new WorkflowStore.Position(0,0));wiring.workflows().transaction(tenant,s->{s.publish(new WorkflowStore.Entry(d,d.digest(),"PUBLISHED",0,layout,Instant.now(),null),owner);return null;});}
 static List<Map<String,Object>> rows(int first,int count){var values=new ArrayList<Map<String,Object>>();for(int i=first;i<first+count;i++)values.add(Map.of("name","Fixture host "+i,"ip","192.0.2."+i,"lifecycle","ACTIVE","entity_id",UUID.nameUUIDFromBytes(("fixture-"+i).getBytes(java.nio.charset.StandardCharsets.UTF_8)).toString()));return values;}
 WorkflowRuntimeService runtime(){var store=new PostgresWorkflowStore(source);var sink=new WorkflowEntityOutput(wiring.writer());return new WorkflowRuntimeService(store,(who,target)->model,(who,s,id)->{throw new AssertionError("No preview reread");},(who,s,at,id)->{throw new AssertionError("No legacy source");},new WorkflowRuntimeService.Output(){
  public void validate(Principal who,WorkflowDefinition flow,WorkflowRuntime.Settings config,List<Map<String,Object>> input,WorkflowEvaluation evaluation){sink.validate(who,flow,config,input,evaluation);}
  public String write(Principal who,WorkflowDefinition flow,WorkflowRuntime.Settings config,UUID id,Instant time,Map<String,Object> input,Map<String,Object> output,String origin){writes++;var result=sink.write(who,flow,config,id,time,input,output,origin);if(failAfterWrite&&writes==2)throw new IllegalStateException("Fixture lost acknowledgement");return result;}
 },Clock.systemUTC(),new WorkflowHostRuntimeService.Sources(){
  public void require(WorkflowStore.Session session,Principal who,WorkflowDefinition.Source source){if(revoked)throw new WorkflowFailure(WorkflowFailure.Code.AUTHORIZATION_REVOKED);}
  public Page read(Principal who,WorkflowDefinition.Source source,String cursor){reads++;return new Page(cursor==null?rows(1,5):rows(6,2),cursor==null?"ids-v1|"+"a".repeat(64)+"|7|5":null,cursor!=null,Instant.now().truncatedTo(java.time.temporal.ChronoUnit.MICROS));}
 });}
 WorkflowRuntimeControl.Command command(WorkflowRuntimeControl.Operation operation,long generation){return new WorkflowRuntimeControl.Command(UUID.randomUUID(),d.id(),1,d.digest(),settings,generation,operation);}
 int observations()throws Exception{try(var c=source.getConnection();var q=c.prepareStatement("SELECT count(*) FROM inventory.entity_observation WHERE tenant_id=? AND source_instance_id=?")){q.setString(1,tenant.value());q.setString(2,"workflow."+d.id());try(var r=q.executeQuery()){r.next();return r.getInt(1);}}}
 WorkflowDiagnosticService diagnostics(){var store=new PostgresWorkflowStore(source);var guards=new WorkflowService.Sources(){public void require(Principal who,WorkflowDefinition.Source src,WorkflowStore.Session s,boolean available){assertFalse(available);}};return new WorkflowDiagnosticService(store,new WorkflowService(store,(who,target)->{throw new AssertionError("No model evaluation");},(who,src,id)->{throw new AssertionError("No source IO");},guards,Clock.systemUTC()),Clock.systemUTC());}

 @Test void abandonUnknownHostKeepsActualInventoryAndOriginalPage(){publish();var r=runtime();r.command(p,command(WorkflowRuntimeControl.Operation.START,0),()->null);failAfterWrite=true;r.tick(p);var cp=r.hostCheckpoint(p,d.id()).orElseThrow();var b=r.hostBatches(p,d.id()).getFirst();var recovery=new WorkflowRecoveryService(new PostgresWorkflowStore(source),Clock.systemUTC());var command=new WorkflowRecovery.Command(UUID.randomUUID(),d.id(),1,d.digest(),WorkflowQuality.Kind.HOST_SCAN,b.id(),1,true);var receipt=recovery.abandon(p,command);assertEquals(receipt,new WorkflowRecoveryService(new PostgresWorkflowStore(source),Clock.systemUTC()).receipt(p,command.requestId()));assertEquals(b,r.hostBatches(p,d.id()).getFirst());assertEquals(cp.confirmedRecords(),r.hostCheckpoint(p,d.id()).orElseThrow().confirmedRecords());assertEquals(cp.nextCursor(),r.hostCheckpoint(p,d.id()).orElseThrow().nextCursor());r.tick(p);assertEquals(2,writes);assertEquals("ABANDONED",r.tasks(p).getFirst().state());assertThrows(WorkflowFailure.class,()->r.command(p,command(WorkflowRuntimeControl.Operation.RESUME,2),()->null));}
 @Test void hostValidationStatisticsRequireAllSourceEntitiesAndOriginalRecoveryDoesNotDuplicateThem()throws Exception{
  publish();var r=runtime();r.command(p,command(WorkflowRuntimeControl.Operation.START,0),()->null);failAfterWrite=true;r.tick(p);var service=diagnostics();var report=service.report(p,d.id(),1);assertEquals(1,report.observations().size());var o=report.observations().getFirst();var b=r.hostBatches(p,d.id()).getFirst();assertEquals(b.id(),o.relatedBatchId());assertEquals("CHECKED",o.state());assertEquals(5,o.result().received());assertEquals(5,o.result().accepted());assertNull(o.result().unitMismatch());var stored=wiring.workflows().transaction(tenant,s->s.diagnostic(owner,o.id()).orElseThrow());assertEquals(5,stored.entityIds().size());var json=com.acme.opsweave.platform.catalog.CatalogJson.JSON.writeValueAsString(report);assertFalse(json.contains("entityIds"));assertFalse(json.contains("Fixture host 1"));assertFalse(json.contains("192.0.2.1"));for(var id:stored.entityIds())assertFalse(json.contains(id));
  var refs=new HashSet<ResourceRef>(Set.of(new ResourceRef(tenant,"workflow","*"),new ResourceRef(tenant,"catalog","*")));refs.add(ResourceRef.entity(tenant,new com.acme.opsweave.sharedkernel.EntityId(UUID.fromString(stored.entityIds().getFirst()))));var restricted=new Principal(p.subjectId(),tenant,p.permissions(),ResourceScope.of(refs));assertEquals(WorkflowFailure.Code.FORBIDDEN,assertThrows(WorkflowFailure.class,()->service.report(restricted,d.id(),1)).code());assertEquals(WorkflowFailure.Code.FORBIDDEN,assertThrows(WorkflowFailure.class,()->service.observation(restricted,d.id(),1,o.id())).code());var other=new Principal(new SubjectId("other"),tenant,p.permissions(),p.resourceScope());assertTrue(service.report(other,d.id(),1).observations().isEmpty());
  failAfterWrite=false;var reopened=runtime();reopened.command(p,command(WorkflowRuntimeControl.Operation.RESUME,1),()->null);reopened.tick(p);assertEquals(1,reads);assertEquals(5,reopened.hostCheckpoint(p,d.id()).orElseThrow().confirmedRecords());assertEquals(List.of(o),diagnostics().report(p,d.id(),1).observations());assertEquals(5,observations());
  try(var c=source.getConnection();var q=c.prepareStatement("UPDATE integration.workflow_diagnostic SET body=jsonb_set(body,'{entityIds}',?::jsonb) WHERE tenant_id=? AND observation_id=?")){q.setString(1,com.acme.opsweave.platform.catalog.CatalogJson.JSON.writeValueAsString(java.util.stream.IntStream.range(0,5).mapToObj(i->UUID.randomUUID().toString()).toList()));q.setString(2,tenant.value());q.setObject(3,o.id());assertEquals(1,q.executeUpdate());}assertThrows(IllegalStateException.class,()->diagnostics().report(p,d.id(),1));
 }
 @Test void typedHostRejectionPersistsStatisticsWithoutOutputOrCheckpointAdmission()throws Exception{
  var nodes=new ArrayList<>(d.nodes());nodes.add(2,new WorkflowDefinition.Node("rule",WorkflowDefinition.Type.ENUM_MAP,"1",Map.of("field","name","from","Fixture host 3","to"," ")));var flow=WorkflowOperators.builtIn().pin(new WorkflowDefinition("host-rejected-fixture",1,"Synthetic Fixture",d.source(),d.target(),nodes,java.util.stream.IntStream.range(1,nodes.size()).mapToObj(i->new WorkflowDefinition.Edge(nodes.get(i-1).id(),nodes.get(i).id())).toList()));var layout=new HashMap<String,WorkflowStore.Position>();for(var n:nodes)layout.put(n.id(),new WorkflowStore.Position(0,0));wiring.workflows().transaction(tenant,s->{s.publish(new WorkflowStore.Entry(flow,flow.digest(),"PUBLISHED",0,layout,Instant.now(),null),owner);return null;});var r=runtime();r.command(p,new WorkflowRuntimeControl.Command(UUID.randomUUID(),flow.id(),1,flow.digest(),settings,0,WorkflowRuntimeControl.Operation.START),()->null);r.tick(p);var report=diagnostics().report(p,flow.id(),1);assertEquals(1,report.observations().size());var o=report.observations().getFirst();assertEquals("REJECTED",o.state());assertEquals(5,o.result().received());assertEquals(4,o.result().accepted());assertEquals(1,o.result().rejected());assertEquals(0,o.result().unknown());assertEquals(1,o.result().schemaMismatch());assertNull(o.relatedBatchId());assertEquals(0,writes);assertTrue(r.hostBatches(p,flow.id()).isEmpty());assertEquals(0,r.hostCheckpoint(p,flow.id()).orElseThrow().confirmedRecords());assertEquals(5,wiring.workflows().transaction(tenant,s->s.diagnostic(owner,o.id()).orElseThrow()).entityIds().size());
 }
 @Test void restartPreservesOriginalPageAndExplicitResumeConfirmsIdempotentOutputs()throws Exception{
  publish();var first=runtime();first.command(p,command(WorkflowRuntimeControl.Operation.START,0),()->null);failAfterWrite=true;first.tick(p);assertEquals(2,observations());var before=first.hostCheckpoint(p,d.id()).orElseThrow();assertEquals(0,before.confirmedRecords());var original=first.hostBatches(p,d.id()).getFirst();assertEquals("UNKNOWN",original.state());assertEquals(1,original.entityIds().size());
  var reopened=runtime();assertEquals(before,reopened.hostCheckpoint(p,d.id()).orElseThrow());assertEquals(original,reopened.hostBatches(p,d.id()).getFirst());reopened.tick(p);assertEquals(2,writes);assertThrows(WorkflowFailure.class,()->reopened.command(p,command(WorkflowRuntimeControl.Operation.START,1),()->null));
  failAfterWrite=false;var resume=command(WorkflowRuntimeControl.Operation.RESUME,1);var receipt=reopened.command(p,resume,()->null);assertEquals(receipt,runtime().command(p,resume,()->{throw new AssertionError("No authority reissue");}));reopened.tick(p);
  assertEquals(1,reads);assertEquals(5,observations());assertEquals(5,reopened.hostCheckpoint(p,d.id()).orElseThrow().confirmedRecords());var confirmed=reopened.hostBatches(p,d.id()).getFirst();assertEquals(original.id(),confirmed.id());assertEquals(original.records(),confirmed.records());assertEquals(original.observedAt(),confirmed.observedAt());assertEquals("CONFIRMED",confirmed.state());
  reopened.command(p,command(WorkflowRuntimeControl.Operation.STOP,2),()->null);runtime().tick(p);assertEquals(1,reads);runtime().command(p,command(WorkflowRuntimeControl.Operation.RESUME,3),()->null);runtime().tick(p);assertEquals(2,reads);assertEquals(7,observations());assertTrue(runtime().hostCheckpoint(p,d.id()).orElseThrow().complete());assertEquals("STOPPED",runtime().tasks(p).getFirst().state());
  assertTrue(runtime().hostBatches(new Principal(new SubjectId("other"),tenant,p.permissions(),ResourceScope.tenantWide()),d.id()).isEmpty());
 }
 @Test void sourceRevocationStopsBeforeNetworkAndStorageCannotChangeAnAdmittedBody(){
  publish();var r=runtime();r.command(p,command(WorkflowRuntimeControl.Operation.START,0),()->null);revoked=true;r.tick(p);assertEquals(0,reads);assertEquals(0,writes);assertEquals("AUTHORIZATION_REVOKED",r.tasks(p).getFirst().error());assertThrows(WorkflowFailure.class,()->r.command(p,command(WorkflowRuntimeControl.Operation.RESUME,1),()->null));
  revoked=false;r.command(p,command(WorkflowRuntimeControl.Operation.RESUME,1),()->null);failAfterWrite=true;r.tick(p);var b=r.hostBatches(p,d.id()).getFirst();
  var replacement=new Batch(b.id(),b.scanId(),b.workflowId(),b.revision(),b.digest(),b.settings(),b.sequence(),b.beforeCursor(),b.nextCursor(),b.complete(),b.observedAt(),rows(20,5),"READY",b.entityIds(),null,b.updatedAt());
  assertThrows(IllegalArgumentException.class,()->wiring.workflows().transaction(tenant,s->{s.finishHostBatch(owner,replacement);return null;}));assertEquals(b,runtime().hostBatches(p,d.id()).getFirst());
 }
 @Test void publicMetadataOmitsOriginalRowsAndManifestCursorsAndStorageRejectsCorruption(){
  publish();var r=runtime();r.command(p,command(WorkflowRuntimeControl.Operation.START,0),()->null);r.tick(p);var b=r.hostBatches(p,d.id()).getFirst();var json=com.acme.opsweave.platform.catalog.CatalogJson.JSON.valueToTree(com.acme.opsweave.platform.workflow.WorkflowHostScanJson.wire(b));assertFalse(json.has("records"));assertFalse(json.has("beforeCursor"));assertFalse(json.has("nextCursor"));assertEquals(5,json.get("recordCount").asInt());
  assertThrows(IllegalArgumentException.class,()->com.acme.opsweave.platform.workflow.WorkflowHostScanJson.batch(com.acme.opsweave.platform.catalog.CatalogJson.JSON.writeValueAsString(b).replace("\"sequence\":1","\"sequence\":0")));
 }
}
