package com.acme.opsweave.platform.persistence;

import static org.junit.jupiter.api.Assertions.*;
import com.acme.opsweave.identity.domain.*;
import com.acme.opsweave.integration.api.WorkflowStore;
import com.acme.opsweave.integration.application.*;
import com.acme.opsweave.integration.domain.*;
import com.acme.opsweave.integration.domain.WorkflowQualityAlerts.*;
import com.acme.opsweave.platform.OpsweaveProperties;
import com.acme.opsweave.platform.catalog.CatalogJson;
import com.acme.opsweave.platform.workflow.AesWorkflowHistoryCursors;
import com.acme.opsweave.sharedkernel.TenantId;
import java.time.*;
import java.time.temporal.ChronoUnit;
import java.util.*;
import java.nio.file.*;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.condition.EnabledIfEnvironmentVariable;
import org.springframework.jdbc.datasource.DriverManagerDataSource;

/** Actual isolated PostgreSQL tenants, with synthetic fixed-source metadata and no provider IO. */
@EnabledIfEnvironmentVariable(named="OPSWEAVE_TEST_JDBC_URL",matches=".+")
class PostgresWorkflowHistoryIT extends OwnedInventoryTest {
 final TenantId tenant=new TenantId("history-pg-fixture-"+UUID.randomUUID());final String owner="history-author";
 final DriverManagerDataSource source=new DriverManagerDataSource(System.getenv("OPSWEAVE_TEST_JDBC_URL"),System.getenv("OPSWEAVE_TEST_JDBC_USER"),System.getenv("OPSWEAVE_TEST_JDBC_PASSWORD"));
 final InventoryWiring wiring=openInventory(new OpsweaveProperties(new OpsweaveProperties.Auth("closed",true,new OpsweaveProperties.Auth.Dev("","",tenant.value(),"","")),new OpsweaveProperties.Zabbix("fixture","","env:OPSWEAVE_ZABBIX_TOKEN","history-fixture",1),new OpsweaveProperties.Inventory("postgres",System.getenv("OPSWEAVE_TEST_JDBC_URL"),System.getenv("OPSWEAVE_TEST_JDBC_USER"),System.getenv("OPSWEAVE_TEST_JDBC_PASSWORD"))));
 final Principal principal=new Principal(new SubjectId(owner),tenant,Set.of(Permission.SOURCE_SYNC,Permission.LOG_READ),ResourceScope.tenantWide());
 final Instant at=Instant.now().minusSeconds(3).truncatedTo(ChronoUnit.MICROS);
 WorkflowDefinition definition(){var sid=UUID.randomUUID();var item=new SourceMetricDiscovery.Item("1","2","log[/synthetic-fixture]","Synthetic Fixture","","LOG","NO_MAPPING",null);var src=new WorkflowDefinition.Source("ZABBIX_LOG",sid.toString(),new WorkflowDefinition.ConfigurationPin(sid,1,"sha256:"+"a".repeat(64)),null,WorkflowLogSourcePin.from(UUID.randomUUID(),item));var nodes=List.of(new WorkflowDefinition.Node("source",WorkflowDefinition.Type.SOURCE,"1",Map.of()),new WorkflowDefinition.Node("map",WorkflowDefinition.Type.MAP,"1",Map.of("timestamp","eventTime","body","body")),new WorkflowDefinition.Node("validate",WorkflowDefinition.Type.VALIDATE,"1",Map.of()),new WorkflowDefinition.Node("output",WorkflowDefinition.Type.OUTPUT,"1",Map.of()));var d=WorkflowOperators.builtIn().pin(new WorkflowDefinition("history-fixture",1,"Synthetic Fixture",src,new WorkflowDefinition.Target(null,1,null,"LOG"),nodes,List.of(new WorkflowDefinition.Edge("source","map"),new WorkflowDefinition.Edge("map","validate"),new WorkflowDefinition.Edge("validate","output"))));var layout=new HashMap<String,WorkflowStore.Position>();nodes.forEach(n->layout.put(n.id(),new WorkflowStore.Position(0,0)));wiring.workflows().transaction(tenant,s->{s.publish(new WorkflowStore.Entry(d,d.digest(),"PUBLISHED",0,layout,at,null),owner);return null;});return d;}
 WorkflowHistoryService service(WorkflowStore store){var guards=new WorkflowService.Sources(){public void require(Principal p,WorkflowDefinition.Source src,WorkflowStore.Session s,boolean available){assertFalse(available);}public void requireTarget(Principal p,WorkflowDefinition.Source src,WorkflowDefinition.Target target,WorkflowStore.Session s,boolean available){assertFalse(available);}};var flows=new WorkflowService(store,(p,t)->{throw new AssertionError("No model IO");},(p,src,id)->{throw new AssertionError("No source IO");},guards,Clock.systemUTC());return new WorkflowHistoryService(store,flows,new AesWorkflowHistoryCursors(new byte[32]),Clock.fixed(at.plusSeconds(1),ZoneOffset.UTC));}

 WorkflowDiagnostics.Observation observation(WorkflowDefinition d,int index){var ref=new WorkflowQuality.Reference(d.id(),1,d.digest());var completed=at.minusSeconds(index/3);var from=completed.minusSeconds(70).truncatedTo(ChronoUnit.SECONDS);return new WorkflowDiagnostics.Observation(UUID.randomUUID(),ref,WorkflowQuality.Kind.LOG_STREAM,1,"SOURCE_FAILED",from,from.plusSeconds(60),completed,completed,null,null,"SOURCE_UNAVAILABLE",WorkflowDiagnostics.Result.unavailable());}
 @Test void realPaginationReopensAndExcludesNewAndBackdatedInsertions()throws Exception{
  var d=definition();var original=new ArrayList<WorkflowDiagnostics.Observation>();for(int i=0;i<45;i++)original.add(observation(d,i));wiring.workflows().transaction(tenant,s->{original.forEach(o->s.addDiagnostic(owner,new WorkflowDiagnostics.Stored(o,List.of())));return null;});original.sort(WorkflowHistory.ORDER);var first=service(wiring.workflows()).history(principal,d.id(),1,null);assertEquals(original.subList(0,20),first.items());assertEquals(45,first.recordedCount());assertTrue(first.hasMore());
  var backdated=observation(d,100);wiring.workflows().transaction(tenant,s->{s.addDiagnostic(owner,new WorkflowDiagnostics.Stored(backdated,List.of()));return null;});var reopened=new PostgresWorkflowStore(source);var next=service(reopened).history(principal,d.id(),1,first.nextCursor());assertEquals(original.subList(20,40),next.items());assertEquals(20,next.offset());assertEquals(first.snapshotAt(),next.snapshotAt());assertEquals(next.items(),service(reopened).history(principal,d.id(),1,first.nextCursor()).items());var last=service(reopened).history(principal,d.id(),1,next.nextCursor());assertEquals(original.subList(40,45),last.items());assertFalse(last.hasMore());assertNull(last.nextCursor());assertEquals(46,service(reopened).history(principal,d.id(),1,null).recordedCount());
  for(var value:original)assertEquals(value,reopened.transaction(tenant,s->s.diagnostic(owner,value.id()).orElseThrow()).observation());var other=new Principal(new SubjectId("other"),tenant,principal.permissions(),principal.resourceScope());assertEquals(0,service(reopened).history(other,d.id(),1,null).recordedCount());assertEquals(WorkflowFailure.Code.NOT_FOUND,assertThrows(WorkflowFailure.class,()->service(reopened).history(other,d.id(),1,first.nextCursor())).code());var denied=new Principal(principal.subjectId(),tenant,Set.of(Permission.SOURCE_SYNC),principal.resourceScope());assertEquals(WorkflowFailure.Code.FORBIDDEN,assertThrows(WorkflowFailure.class,()->service(reopened).history(denied,d.id(),1,first.nextCursor())).code());var foreign=new Principal(principal.subjectId(),new TenantId(tenant.value()+"-foreign"),principal.permissions(),principal.resourceScope());assertEquals(WorkflowFailure.Code.NOT_FOUND,assertThrows(WorkflowFailure.class,()->service(reopened).history(foreign,d.id(),1,first.nextCursor())).code());assertEquals(WorkflowFailure.Code.NOT_FOUND,assertThrows(WorkflowFailure.class,()->service(reopened).history(principal,d.id(),2,null)).code());
  // Only this isolated tenant is deliberately corrupted; customer state is never touched.
  try(var c=source.getConnection();var q=c.prepareStatement("UPDATE integration.workflow_diagnostic SET body=jsonb_set(body,'{observation,id}',to_jsonb(?::text)) WHERE tenant_id=? AND observation_id=?")){q.setString(1,UUID.randomUUID().toString());q.setString(2,tenant.value());q.setObject(3,original.getFirst().id());assertEquals(1,q.executeUpdate());}assertThrows(IllegalStateException.class,()->service(reopened).history(principal,d.id(),1,null));
  try(var c=source.getConnection();var q=c.prepareStatement("DELETE FROM integration.workflow_diagnostic WHERE tenant_id=? AND observation_id=?")){q.setString(1,tenant.value());q.setObject(2,first.items().getLast().id());assertEquals(1,q.executeUpdate());}assertEquals(WorkflowFailure.Code.CONFLICT,assertThrows(WorkflowFailure.class,()->service(reopened).history(principal,d.id(),1,first.nextCursor())).code());
 }
 @Test void forwardRollbackAndForwardPreserveTheOriginalBodyAndTimestamp()throws Exception{
  var schema="history_migration_fixture_"+UUID.randomUUID().toString().replace("-","");assertTrue(schema.matches("history_migration_fixture_[a-f0-9]{32}"));var root=Path.of(System.getProperty("user.dir")).toAbsolutePath();while(!Files.exists(root.resolve("db/migrations/platform/V055__workflow_history_selection.sql")))root=root.getParent();var forward=Files.readString(root.resolve("db/migrations/platform/V055__workflow_history_selection.sql")).replace("integration.",schema+".");var rollback=Files.readString(root.resolve("db/rollback/platform/V055__workflow_history_selection.sql")).replace("integration.",schema+".");try(var c=source.getConnection();var q=c.createStatement()){try{q.execute("CREATE SCHEMA "+schema);q.execute("CREATE TABLE "+schema+".workflow_diagnostic(body jsonb,completed_at timestamptz)");q.execute("INSERT INTO "+schema+".workflow_diagnostic VALUES ('{\"fixture\":true}', '2026-10-05T00:00:00.123456Z')");q.execute(forward);try(var rs=q.executeQuery("SELECT history_sequence,body::text,completed_at FROM "+schema+".workflow_diagnostic")){assertTrue(rs.next());assertTrue(rs.getLong(1)>0);assertEquals("{\"fixture\": true}",rs.getString(2));assertEquals(Instant.parse("2026-10-05T00:00:00.123456Z"),rs.getTimestamp(3).toInstant());}q.execute(rollback);try(var rs=q.executeQuery("SELECT body::text,completed_at FROM "+schema+".workflow_diagnostic")){assertTrue(rs.next());assertEquals("{\"fixture\": true}",rs.getString(1));assertEquals(Instant.parse("2026-10-05T00:00:00.123456Z"),rs.getTimestamp(2).toInstant());}q.execute(forward);try(var rs=q.executeQuery("SELECT count(*),min(history_sequence) FROM "+schema+".workflow_diagnostic")){assertTrue(rs.next());assertEquals(1,rs.getInt(1));assertTrue(rs.getLong(2)>0);}}finally{q.execute("DROP SCHEMA "+schema+" CASCADE");}}
 }
}
