package com.acme.opsweave.platform.persistence;

import static org.junit.jupiter.api.Assertions.*;
import com.acme.opsweave.identity.domain.*;
import com.acme.opsweave.integration.application.*;
import com.acme.opsweave.integration.domain.*;
import com.acme.opsweave.integration.domain.WorkflowMetricStream.*;
import com.acme.opsweave.platform.catalog.CatalogJson;
import com.acme.opsweave.platform.telemetry.VictoriaWorkflowMetricSink;
import com.acme.opsweave.telemetry.domain.MetricWriteBatch;
import java.net.URI;
import java.time.*;
import java.util.*;
import java.util.concurrent.Semaphore;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.condition.EnabledIfEnvironmentVariable;

/** Actual PG and time-series sink, isolated synthetic metric series. No source/provider claim. */
@EnabledIfEnvironmentVariable(named="OPSWEAVE_TEST_VM_URL",matches=".+")
class PostgresWorkflowMetricStreamIT extends PostgresWorkflowMetricOutputIT {
    static class Time extends Clock {Instant now=Instant.now().truncatedTo(java.time.temporal.ChronoUnit.MICROS);public Instant instant(){return now;}public ZoneId getZone(){return ZoneOffset.UTC;}public Clock withZone(ZoneId zone){return this;}void advance(int n){now=now.plusSeconds(n);}}
    final Principal p=new Principal(new SubjectId(owner),tenant,Set.of(Permission.SOURCE_SYNC,Permission.METRIC_READ,Permission.ENTITY_READ),ResourceScope.tenantWide());
    WorkflowMetricStreamService service(com.acme.opsweave.integration.api.WorkflowStore store,WorkflowMetricOutputService.Sink sink,Time clock){
        return service(store,sink,clock,(p,s,from,till)->List.of(Map.of("timestamp",from.plusSeconds(1).toString(),"sourceKey",s.metric().sourceKey(),"value","12.5")));
    }
    WorkflowMetricStreamService service(com.acme.opsweave.integration.api.WorkflowStore store,WorkflowMetricOutputService.Sink sink,Time clock,WorkflowMetricStreamService.Source input){
        var mapping=com.acme.opsweave.integration.infrastructure.ClasspathMappingCatalog.load(getClass().getClassLoader()).find("zabbix","system.cpu.util[,user]").orElseThrow();
        var sources=new WorkflowService.Sources(){public void require(Principal p,WorkflowDefinition.Source src,com.acme.opsweave.integration.api.WorkflowStore.Session s,boolean available){}public void requireTarget(Principal p,WorkflowDefinition.Source src,WorkflowDefinition.Target target,com.acme.opsweave.integration.api.WorkflowStore.Session s,boolean available){assertEquals(mapping.pin(),target.mappingPin());}};
        var workflows=new WorkflowService(store,(p,t)->{throw new AssertionError();},(p,s,id)->{throw new AssertionError("No preview reused as output");},sources,(p,pin)->mapping,clock);
        return new WorkflowMetricStreamService(store,workflows,input,sink,new Semaphore(2),clock);
    }
    WorkflowMetricStreamService.Status verifyReadOnly(WorkflowMetricStreamService service,String id)throws Exception{
        var current=service.status(p,id);for(int i=0;i<40&&current.task().pendingBatchId()!=null;i++){Thread.sleep(200);current=service.verify(p,id,current.task().pendingBatchId());}return current;
    }

    @Test void actualMetricOutputIsNotDeletedOrConfirmedByAbandonment()throws Exception{
        var fixture=prepare();var clock=new Time();var actual=new VictoriaWorkflowMetricSink(URI.create(System.getenv("OPSWEAVE_TEST_VM_URL")),Duration.ofSeconds(5));var writes=new java.util.concurrent.atomic.AtomicInteger();var lost=new WorkflowMetricOutputService.Sink(){public void write(MetricWriteBatch batch){writes.incrementAndGet();actual.write(batch);throw new WorkflowMetricOutputService.OutputFailure(true);}public List<MetricWriteBatch.Sample> read(Map<String,String> labels,List<Long> timestamps){return actual.read(labels,timestamps);}};
        var runtime=service(wiring.workflows(),lost,clock);runtime.command(p,new Command(UUID.randomUUID(),fixture.workflowId(),1,fixture.digest(),0,Operation.START),()->null);clock.advance(11);runtime.tick(p);var before=runtime.status(p,fixture.workflowId());var b=before.batches().getFirst();assertEquals("UNKNOWN",b.state());var original=actual.read(b.labels(),b.timestamps());
        // This isolated fixture allows at most 30 additional scoped reads for observed visibility delay.
        // Neither the write nor runtime.verify is called again; UNKNOWN must remain unchanged.
        for(int i=0;i<30&&original.isEmpty();i++){Thread.sleep(1000);original=actual.read(b.labels(),b.timestamps());}
        assertEquals(before,runtime.status(p,fixture.workflowId()));assertEquals(1,writes.get(),"Fixture adapter invocation");assertEquals(1,original.size(),"Actual preserved point readback");var recovery=new WorkflowRecoveryService(new PostgresWorkflowStore(source),clock);var command=new WorkflowRecovery.Command(UUID.randomUUID(),fixture.workflowId(),1,fixture.digest(),WorkflowQuality.Kind.METRIC_STREAM,b.id(),1,true);var receipt=recovery.abandon(p,command);assertEquals(receipt,new WorkflowRecoveryService(new PostgresWorkflowStore(source),clock).abandon(p,command));assertEquals(original,actual.read(b.labels(),b.timestamps()));assertEquals(b,runtime.status(p,fixture.workflowId()).batches().getFirst());assertEquals(before.task().cursor(),runtime.status(p,fixture.workflowId()).task().cursor());assertEquals(0,runtime.status(p,fixture.workflowId()).task().confirmedPoints());assertEquals(1,writes.get());assertThrows(WorkflowFailure.class,()->runtime.verify(p,fixture.workflowId(),b.id()));
    }
    @Test void sixHundredPointProofAndLateReconciliationSurviveReopeningWithoutChangingCursor()throws Exception{
        var fixture=prepare();var clock=new Time();var sink=new VictoriaWorkflowMetricSink(URI.create(System.getenv("OPSWEAVE_TEST_VM_URL")),Duration.ofSeconds(5));var count=new java.util.concurrent.atomic.AtomicInteger(598);
        WorkflowMetricStreamService.Source input=(p,s,from,till)->java.util.stream.IntStream.range(0,count.get()).mapToObj(i->Map.<String,Object>of("timestamp",from.plusMillis(i*50L).toString(),"sourceKey",s.metric().sourceKey(),"value","12.5")).toList();
        var service=service(wiring.workflows(),sink,clock,input);service.command(p,new Command(UUID.randomUUID(),fixture.workflowId(),1,fixture.digest(),0,Operation.START),()->null);clock.advance(11);service.tick(p);var initial=verifyReadOnly(service,fixture.workflowId());assertEquals(598,initial.task().confirmedPoints(),initial.task().error());var original=initial.batches().getFirst();var cursor=initial.task().cursor();count.set(600);clock.advance(60);if(initial.task().state().equals("STOPPED"))service.command(p,new Command(UUID.randomUUID(),fixture.workflowId(),1,fixture.digest(),initial.task().generation(),Operation.RESUME),()->null);service.tick(p);var current=verifyReadOnly(service,fixture.workflowId());assertNull(current.task().error());assertEquals(600,current.task().confirmedPoints());assertEquals(1,current.task().confirmedWindows());assertEquals(initial.task().state().equals("STOPPED")?1:2,current.task().sessionBatches());assertEquals(cursor,current.task().cursor());var late=current.batches().getFirst();assertEquals(original.id(),late.reconcilesBatchId());assertEquals(2,late.latePoints());assertEquals(600,sink.read(late.labels(),late.timestamps()).size());
        var reopened=new PostgresWorkflowStore(source);assertEquals(current,service(reopened,sink,clock,input).status(p,fixture.workflowId()));assertEquals(original,reopened.transaction(tenant,s->s.metricStreamBatch(owner,original.id()).orElseThrow()));assertTrue(CatalogJson.JSON.writeValueAsString(late).length()>8192);assertFalse(CatalogJson.JSON.writeValueAsString(late).contains("0.125"));
        var oldJson=(tools.jackson.databind.node.ObjectNode)CatalogJson.JSON.valueToTree(original);oldJson.remove("reconcilesBatchId");oldJson.remove("latePoints");assertEquals(original,com.acme.opsweave.platform.workflow.WorkflowMetricStreamJson.batch(oldJson.toString()));
        var other=new Batch(UUID.randomUUID(),late.workflowId(),1,late.digest(),late.from(),late.till(),late.createdAt(),late.updatedAt(),"IN_FLIGHT",late.inputCount(),late.filtered(),late.collapsed(),late.labels(),late.batchDigest(),late.timestamps(),null,UUID.randomUUID(),2);assertThrows(NoSuchElementException.class,()->reopened.transaction(tenant,s->{s.addMetricStreamBatch(owner,other);return null;}));assertTrue(reopened.transaction(tenant,s->s.metricStreamBatch(owner,other.id())).isEmpty());
    }
    @Test void twoWindowsConfirmInActualSinkAndResumeFromReopenedCheckpoint()throws Exception{
        var fixture=prepare();var clock=new Time();var sink=new VictoriaWorkflowMetricSink(URI.create(System.getenv("OPSWEAVE_TEST_VM_URL")),Duration.ofSeconds(5));var service=service(wiring.workflows(),sink,clock);
        var start=new Command(UUID.randomUUID(),fixture.workflowId(),1,fixture.digest(),0,Operation.START);var receipt=service.command(p,start,()->null);clock.advance(11);service.tick(p);var first=service.status(p,fixture.workflowId());for(int i=0;i<40&&first.task().pendingBatchId()!=null;i++){Thread.sleep(200);first=service.verify(p,fixture.workflowId(),first.task().pendingBatchId());}assertEquals(1,first.task().confirmedWindows(),first.task().error());assertEquals(1,first.task().confirmedPoints());assertEquals("CONFIRMED",first.batches().getFirst().state());var b=first.batches().getFirst();var points=sink.read(b.labels(),b.timestamps());assertEquals(b.batchDigest(),WorkflowMetricOutput.batchDigest(new MetricWriteBatch(b.labels(),points,0)));assertEquals("0.125",points.getFirst().value().toPlainString());
        var stop=new Command(UUID.randomUUID(),fixture.workflowId(),1,fixture.digest(),1,Operation.STOP);if(first.task().state().equals("RUNNING"))service.command(p,stop,()->null);var reopened=service(new PostgresWorkflowStore(source),sink,clock);assertEquals(receipt,reopened.receipt(p,start.requestId()));assertEquals(receipt,reopened.command(p,start,()->{throw new AssertionError("No new authority");}));assertEquals(first.task().cursor(),reopened.status(p,fixture.workflowId()).task().cursor());clock.advance(60);reopened.tick(p);assertEquals(1,reopened.status(p,fixture.workflowId()).task().confirmedWindows());reopened.command(p,new Command(UUID.randomUUID(),fixture.workflowId(),1,fixture.digest(),reopened.status(p,fixture.workflowId()).task().generation(),Operation.RESUME),()->null);reopened.tick(p);var second=reopened.status(p,fixture.workflowId());for(int i=0;i<40&&second.task().pendingBatchId()!=null;i++){Thread.sleep(200);second=reopened.verify(p,fixture.workflowId(),second.task().pendingBatchId());}assertEquals(2,reopened.status(p,fixture.workflowId()).task().confirmedWindows());assertEquals(2,reopened.status(p,fixture.workflowId()).task().confirmedPoints());
    }
    @Test void confirmedMetricWindowRecoverySurvivesTwentyOneMoreRecentFailures()throws Exception{
        var fixture=prepare();var clock=new Time();var sink=new VictoriaWorkflowMetricSink(URI.create(System.getenv("OPSWEAVE_TEST_VM_URL")),Duration.ofSeconds(5));var count=new java.util.concurrent.atomic.AtomicInteger(1);WorkflowMetricStreamService.Source input=(who,src,from,till)->java.util.stream.IntStream.range(0,count.get()).mapToObj(i->Map.<String,Object>of("timestamp",from.plusSeconds(i+1).toString(),"sourceKey",src.metric().sourceKey(),"value","12.5")).toList();var service=service(wiring.workflows(),sink,clock,input);service.command(p,new Command(UUID.randomUUID(),fixture.workflowId(),1,fixture.digest(),0,Operation.START),()->null);clock.advance(11);service.tick(p);var first=verifyReadOnly(service,fixture.workflowId());var original=first.batches().getFirst();assertEquals("CONFIRMED",original.state());
        wiring.workflows().transaction(tenant,s->{for(int i=0;i<21;i++){var at=original.createdAt().plusNanos(1000L*(i+1));var b=new Batch(UUID.randomUUID(),original.workflowId(),1,original.digest(),original.from(),original.till(),at,at,"IN_FLIGHT",original.inputCount(),original.filtered(),original.collapsed(),original.labels(),original.batchDigest(),original.timestamps(),null);s.addMetricStreamBatch(owner,b);s.finishMetricStreamBatch(owner,b.finish("FAILED","OUTPUT_REJECTED",at));}return null;});var reopened=service(new PostgresWorkflowStore(source),sink,clock,input);assertTrue(reopened.status(p,fixture.workflowId()).batches().stream().noneMatch(b->b.id().equals(original.id())));count.set(2);clock.advance(60);if(first.task().state().equals("STOPPED"))reopened.command(p,new Command(UUID.randomUUID(),fixture.workflowId(),1,fixture.digest(),first.task().generation(),Operation.RESUME),()->null);reopened.tick(p);var late=verifyReadOnly(reopened,fixture.workflowId());assertEquals(1,late.task().confirmedWindows());assertEquals(2,late.task().confirmedPoints());assertEquals(first.task().cursor(),late.task().cursor());assertEquals(original.id(),late.batches().getFirst().reconcilesBatchId());assertEquals(1,late.batches().getFirst().latePoints());assertEquals(original,new PostgresWorkflowStore(source).transaction(tenant,s->s.metricStreamBatch(owner,original.id()).orElseThrow()));
    }
    @Test void unknownJournalSurvivesRestartAndOnlyExactReadbackAdvances(){
        var fixture=prepare();var clock=new Time();var saved=new ArrayList<MetricWriteBatch>();var visible=new ArrayList<MetricWriteBatch.Sample>();var sink=new WorkflowMetricOutputService.Sink(){public void write(MetricWriteBatch batch){saved.add(batch);throw new WorkflowMetricOutputService.OutputFailure(true);}public List<MetricWriteBatch.Sample> read(Map<String,String> labels,List<Long> timestamps){return List.copyOf(visible);}};
        var service=service(wiring.workflows(),sink,clock);service.command(p,new Command(UUID.randomUUID(),fixture.workflowId(),1,fixture.digest(),0,Operation.START),()->null);clock.advance(11);service.tick(p);var unknown=service.status(p,fixture.workflowId());assertEquals("UNKNOWN",unknown.batches().getFirst().state());assertEquals(0,unknown.task().confirmedWindows());var reopened=service(new PostgresWorkflowStore(source),sink,clock);assertEquals(unknown,reopened.status(p,fixture.workflowId()));clock.advance(60);reopened.tick(p);assertEquals(1,saved.size());reopened.verify(p,fixture.workflowId(),unknown.task().pendingBatchId());assertEquals(0,reopened.status(p,fixture.workflowId()).task().confirmedWindows());visible.addAll(saved.getFirst().samples());var confirmed=reopened.verify(p,fixture.workflowId(),unknown.task().pendingBatchId());assertEquals(1,confirmed.task().confirmedWindows());assertEquals(1,saved.size());assertNull(confirmed.task().pendingBatchId());
        var privateTask=CatalogJson.JSON.writeValueAsString(confirmed.task());assertFalse(privateTask.contains("12.5"));assertThrows(IllegalArgumentException.class,()->com.acme.opsweave.platform.workflow.WorkflowMetricStreamJson.task(privateTask.replace("\"sessionBatches\":1","\"sessionBatches\":\"1\"")));assertThrows(IllegalArgumentException.class,()->com.acme.opsweave.platform.workflow.WorkflowMetricStreamJson.batch(CatalogJson.JSON.writeValueAsString(confirmed.batches().getFirst()).replace("\"CONFIRMED\"","\"FAILED\"")));
    }
}
