package com.acme.opsweave.platform.persistence;
import static org.junit.jupiter.api.Assertions.*;
import com.acme.opsweave.platform.OpsweaveProperties;
import com.acme.opsweave.platform.catalog.BuiltinCatalog;
import com.acme.opsweave.integration.domain.*;
import com.acme.opsweave.integration.domain.WorkflowDefinition.*;
import com.acme.opsweave.integration.api.WorkflowStore.*;
import com.acme.opsweave.integration.application.WorkflowService;
import com.acme.opsweave.identity.domain.*;
import com.acme.opsweave.sharedkernel.TenantId;
import java.time.*;
import java.util.*;
import java.util.concurrent.*;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.condition.EnabledIfEnvironmentVariable;
import org.springframework.jdbc.datasource.DriverManagerDataSource;

@EnabledIfEnvironmentVariable(named="OPSWEAVE_TEST_JDBC_URL",matches=".+")
class PostgresWorkflowIT extends OwnedInventoryTest {
 final TenantId tenant=new TenantId("workflow-pg-"+UUID.randomUUID());
 final DriverManagerDataSource source=new DriverManagerDataSource(System.getenv("OPSWEAVE_TEST_JDBC_URL"),System.getenv("OPSWEAVE_TEST_JDBC_USER"),System.getenv("OPSWEAVE_TEST_JDBC_PASSWORD"));
 final InventoryWiring wiring=openInventory(new OpsweaveProperties(new OpsweaveProperties.Auth("closed",true,new OpsweaveProperties.Auth.Dev("","",tenant.value(),"","")),new OpsweaveProperties.Zabbix("fixture","","env:OPSWEAVE_ZABBIX_TOKEN","zabbix-1",1),new OpsweaveProperties.Inventory("postgres",System.getenv("OPSWEAVE_TEST_JDBC_URL"),System.getenv("OPSWEAVE_TEST_JDBC_USER"),System.getenv("OPSWEAVE_TEST_JDBC_PASSWORD"))));
 final com.acme.opsweave.catalog.domain.ModelDefinition model=new BuiltinCatalog().definitions().stream().filter(m->m.id().equals("builtin.service")).findFirst().orElseThrow();
 Principal user(String owner){return new Principal(new SubjectId(owner),tenant,Set.of(Permission.SOURCE_SYNC),ResourceScope.tenantWide());}
 WorkflowService service(){return new WorkflowService(new PostgresWorkflowStore(source),(p,t)->model,(p,s,b)->{throw new AssertionError();},Clock.systemUTC());}
 WorkflowDefinition definition(String name){return WorkflowOperators.builtIn().pin(new WorkflowDefinition("pg-flow",1,name,new Source("MANUAL_SAMPLE","manual"),new Target(model.id(),1,model.digest()),List.of(new Node("source",Type.SOURCE,"1",Map.of()),new Node("map",Type.MAP,"1",Map.of("name","name")),new Node("validate",Type.VALIDATE,"1",Map.of()),new Node("output",Type.OUTPUT,"1",Map.of())),List.of(new Edge("source","map"),new Edge("map","validate"),new Edge("validate","output"))));}
 Map<String,Position> layout(){return Map.of("source",new Position(0,0),"map",new Position(0,100),"validate",new Position(0,200),"output",new Position(0,300));}
 @Test void reopenedConnectionsKeepReceiptsAndIsolatePrivateData(){var p=user("one");var d=definition("Fixture");service().save(p,d,layout(),0);var result=service().evaluate(p,d.id(),1,1,d.digest(),false,List.of(Map.of("name","Fixture private sample")),null);assertEquals(result.receipt(),service().draft(p,d.id(),1).preview());assertTrue(service().drafts(user("two")).items().isEmpty());assertTrue(service().runs(user("two")).items().isEmpty());assertEquals(1,service().runs(p).items().size());var published=service().publish(p,d.id(),1,1,d.digest(),result.receipt().id());assertTrue(service().drafts(p).items().isEmpty());assertEquals(published,service().version(user("two"),d.id(),1));var otherTenant=new Principal(p.subjectId(),new TenantId(tenant.value()+"-other"),p.permissions(),p.resourceScope());assertTrue(service().versions(otherTenant).items().isEmpty());}
 @Test void concurrentCompareAndSetHasOneWinnerAndNoPartialWrites()throws Exception{var p=user("one");service().save(p,definition("Initial"),layout(),0);var start=new CountDownLatch(1);try(var pool=Executors.newFixedThreadPool(4)){var futures=new ArrayList<Future<Boolean>>();for(int i=0;i<4;i++){final int n=i;futures.add(pool.submit(()->{start.await();try{service().save(p,definition("Writer "+n),layout(),1);return true;}catch(WorkflowFailure conflict){assertEquals(WorkflowFailure.Code.CONFLICT,conflict.code());return false;}}));}start.countDown();int successes=0;for(var future:futures)if(future.get(15,TimeUnit.SECONDS))successes++;assertEquals(1,successes);assertEquals(2,service().draft(p,"pg-flow",1).editVersion());}}
 @Test void rollbackAndCorruptionFailClosed()throws Exception{var d=definition("Fixture");var p=user("one");service().save(p,d,layout(),0);var saved=service().draft(p,d.id(),1);var s=new PostgresWorkflowStore(source);assertThrows(IllegalStateException.class,()->s.transaction(tenant,tx->{tx.saveDraft("two",saved);throw new IllegalStateException("Test rollback");}));assertTrue(service().drafts(user("two")).items().isEmpty());try(var c=source.getConnection();var q=c.prepareStatement("UPDATE integration.workflow_draft SET entry=jsonb_set(entry,'{digest}',to_jsonb(?::text)) WHERE tenant_id=?")){q.setString(1,"sha256:"+"0".repeat(64));q.setString(2,tenant.value());q.executeUpdate();}assertThrows(IllegalStateException.class,()->service().draft(p,d.id(),1));}
 @Test void mixedTracePersistsWithoutSampleValuesAndOldReceiptsRemainReadable()throws Exception{
  var p=user("trace-owner");var original=definition("PRIVATE WORKFLOW NAME");var nodes=List.of(new Node("source",Type.SOURCE,"1",Map.of()),new Node("map",Type.MAP,"1",Map.of("name","name","port","port")),new Node("filter",Type.FILTER,"1",Map.of("field","name","equals","keep-private")),new Node("validate",Type.VALIDATE,"1",Map.of()),new Node("output",Type.OUTPUT,"1",Map.of()));var edges=new ArrayList<Edge>();var positions=new LinkedHashMap<String,Position>();for(int i=0;i<nodes.size();i++){positions.put(nodes.get(i).id(),new Position(0,i*100));if(i>0)edges.add(new Edge(nodes.get(i-1).id(),nodes.get(i).id()));}
  var d=new WorkflowDefinition("pg-mixed",1,original.name(),original.source(),original.target(),nodes,edges);service().save(p,d,positions,0);var result=service().evaluate(p,d.id(),1,1,d.digest(),false,List.of(Map.of("name","keep-private","port",8080),Map.of("name","keep-private","port","private-invalid-value"),Map.of("name","drop-private")),null);
  var id=result.receipt().id();var run=service().run(p,id);assertEquals(1,run.receipt().accepted());assertEquals(1,run.receipt().rejected());assertEquals(1,run.receipt().filtered());assertEquals("TYPE_MISMATCH",run.trace().rows().get(1).steps().get(3).issues().getFirst().code());assertEquals("SKIPPED",run.trace().rows().get(2).steps().getLast().status());assertEquals(run,service().run(p,id));assertThrows(WorkflowFailure.class,()->service().run(user("different-owner"),id));var differentTenant=new Principal(p.subjectId(),new TenantId(tenant.value()+"-other"),p.permissions(),p.resourceScope());assertThrows(WorkflowFailure.class,()->service().run(differentTenant,id));
  try(var c=source.getConnection();var q=c.prepareStatement("SELECT receipt::text FROM integration.workflow_run WHERE tenant_id=? AND run_id=?")){q.setString(1,tenant.value());q.setObject(2,id);try(var rows=q.executeQuery()){assertTrue(rows.next());var json=rows.getString(1);assertFalse(json.contains("private"));assertFalse(json.contains("values"));assertFalse(json.contains("config"));}}
  var store=new PostgresWorkflowStore(source);var rollbackId=UUID.randomUUID();var receipt=new Receipt(rollbackId,run.receipt().digest(),run.receipt().inputDigest(),run.receipt().origin(),1,1,1,run.receipt().createdAt());assertThrows(IllegalStateException.class,()->store.transaction(tenant,tx->{tx.addRun("trace-owner",new Run(d.id(),1,"PREVIEW",receipt,run.trace()));throw new IllegalStateException("rollback");}));assertThrows(WorkflowFailure.class,()->service().run(p,rollbackId));
  try(var c=source.getConnection();var q=c.prepareStatement("UPDATE integration.workflow_run SET receipt=receipt-'trace' WHERE tenant_id=? AND run_id=?")){q.setString(1,tenant.value());q.setObject(2,id);assertEquals(1,q.executeUpdate());}assertNull(service().run(p,id).trace());assertEquals(result.receipt(),service().run(p,id).receipt());
 }
 @Test void tamperedTraceCountsFailClosed()throws Exception{var p=user("bad-trace");var d=definition("fixture");service().save(p,d,layout(),0);var result=service().evaluate(p,d.id(),1,1,d.digest(),false,List.of(Map.of("name","fixture")),null);try(var c=source.getConnection();var q=c.prepareStatement("UPDATE integration.workflow_run SET receipt=jsonb_set(receipt,'{trace,rows,0,status}','\"REJECTED\"'::jsonb) WHERE tenant_id=? AND run_id=?")){q.setString(1,tenant.value());q.setObject(2,result.receipt().id());q.executeUpdate();}assertThrows(IllegalStateException.class,()->service().run(p,result.receipt().id()));}
 @Test void legacyPublishedNodesAreNotRewrittenOnReadOrExecution()throws Exception{
  var p=user("legacy-owner");var current=definition("Fixture legacy immutable");var legacy=new WorkflowDefinition(current.id(),1,current.name(),current.source(),current.target(),current.nodes().stream().map(n->new Node(n.id(),n.type(),n.version(),n.config())).toList(),current.edges());
  var version=new Entry(legacy,legacy.digest(),"PUBLISHED",0,layout(),Instant.now(),null);var store=new PostgresWorkflowStore(source);store.transaction(tenant,tx->{tx.publish(version,p.subjectId().value());return null;});
  assertEquals(legacy,service().version(p,legacy.id(),1).definition());assertEquals(1,service().evaluate(p,legacy.id(),1,0,legacy.digest(),true,List.of(Map.of("name","Fixture old execution")),null).evaluation().accepted());
  try(var c=source.getConnection();var q=c.prepareStatement("SELECT entry::text FROM integration.workflow_version WHERE tenant_id=? AND workflow_id=?")){q.setString(1,tenant.value());q.setString(2,legacy.id());try(var rows=q.executeQuery()){assertTrue(rows.next());var entry=rows.getString(1);assertFalse(entry.contains("operatorDigest"));assertEquals(legacy.digest(),com.acme.opsweave.platform.workflow.WorkflowJson.decode(entry).digest());}}
 }
}
