package com.acme.opsweave.platform.persistence;

import static org.junit.jupiter.api.Assertions.*;
import com.acme.opsweave.identity.domain.*;
import com.acme.opsweave.integration.api.*;
import com.acme.opsweave.integration.application.*;
import com.acme.opsweave.integration.domain.*;
import com.acme.opsweave.integration.domain.WorkflowLogStream.*;
import com.acme.opsweave.platform.catalog.CatalogJson;
import com.acme.opsweave.platform.workflow.*;
import com.acme.opsweave.platform.telemetry.ClickHouseWorkflowLogWindowSink;
import java.net.URI;
import java.time.*;
import java.util.*;
import java.util.concurrent.Semaphore;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.condition.EnabledIfEnvironmentVariable;

/** Actual PG and optional ClickHouse. Source rows here are explicit synthetic fixtures. */
class PostgresWorkflowLogStreamIT extends PostgresWorkflowLogOutputIT {
    static final class Time extends Clock {Instant value=Instant.now().truncatedTo(java.time.temporal.ChronoUnit.MICROS);public Instant instant(){return value;}public ZoneId getZone(){return ZoneOffset.UTC;}public Clock withZone(ZoneId z){return this;}void advance(int n){value=value.plusSeconds(n);}}
    final Principal p=new Principal(new SubjectId(owner),tenant,Set.of(Permission.SOURCE_SYNC,Permission.LOG_READ,Permission.LOG_WRITE,Permission.ENTITY_READ),ResourceScope.tenantWide());
    WorkflowDefinition definition(){
        var item=new SourceMetricDiscovery.Item("1","2","log[/synthetic-fixture]","Synthetic Fixture","","LOG","NO_MAPPING",null);var sourceId=UUID.randomUUID();
        var src=new WorkflowDefinition.Source("ZABBIX_LOG",sourceId.toString(),new WorkflowDefinition.ConfigurationPin(sourceId,1,"sha256:"+"a".repeat(64)),null,WorkflowLogSourcePin.from(UUID.randomUUID(),item));
        var nodes=List.of(new WorkflowDefinition.Node("source",WorkflowDefinition.Type.SOURCE,"1",Map.of()),new WorkflowDefinition.Node("mapping",WorkflowDefinition.Type.MAP,"1",Map.of("timestamp","eventTime","body","body")),new WorkflowDefinition.Node("validate",WorkflowDefinition.Type.VALIDATE,"1",Map.of()),new WorkflowDefinition.Node("output",WorkflowDefinition.Type.OUTPUT,"1",Map.of()));
        var d=WorkflowOperators.builtIn().pin(new WorkflowDefinition("log-stream-fixture",1,"Synthetic Fixture",src,new WorkflowDefinition.Target(null,1,null,"LOG"),nodes,List.of(new WorkflowDefinition.Edge("source","mapping"),new WorkflowDefinition.Edge("mapping","validate"),new WorkflowDefinition.Edge("validate","output"))));
        var layout=new HashMap<String,WorkflowStore.Position>();for(var n:nodes)layout.put(n.id(),new WorkflowStore.Position(0,0));wiring.workflows().transaction(tenant,s->{s.publish(new WorkflowStore.Entry(d,d.digest(),"PUBLISHED",0,layout,Instant.now(),null),owner);return null;});return d;
    }
    List<Map<String,Object>> rows(WorkflowDefinition.Source src,Instant from,int count){var rows=new ArrayList<Map<String,Object>>();for(int i=0;i<count;i++){var r=new LinkedHashMap<String,Object>();r.put("timestamp",from.plusNanos(i).toString());r.put("body","  Synthetic Fixture "+i+" 🧵\n<script>  ");r.put("sourceKey",src.log().sourceKey());r.put("logEventTime",null);r.put("severityCode","0");r.put("eventSource",null);r.put("eventId","0");rows.add(r);}return List.copyOf(rows);}
    WorkflowService flows(WorkflowStore store,Time time){
        var sources=new WorkflowService.Sources(){public void require(Principal who,WorkflowDefinition.Source src,WorkflowStore.Session s,boolean available){}public void requireTarget(Principal who,WorkflowDefinition.Source src,WorkflowDefinition.Target target,WorkflowStore.Session s,boolean available){}};
        return new WorkflowService(store,(who,t)->{throw new AssertionError();},(who,src,id)->{throw new AssertionError("Preview is not reused as a batch");},sources,time);
    }
    WorkflowLogStreamService service(WorkflowStore store,WorkflowLogWindowSink sink,Time time,WorkflowLogStreamService.Source input){
        return new WorkflowLogStreamService(store,flows(store,time),input,sink,new Semaphore(2),time);
    }
    static final class Sink implements WorkflowLogWindowSink {int writes,reads;boolean unknown;WorkflowLogWindow.Batch last;final Map<UUID,List<WorkflowLogWindow.Record>> visible=new HashMap<>();public boolean ready(){return true;}public void write(WorkflowLogWindow.Batch b){last=b;writes++;if(unknown)throw new WorkflowLogOutputService.OutputFailure(true);visible.put(b.scope().requestId(),b.records());}public List<WorkflowLogWindow.Record> read(WorkflowLogOutput.Scope s){reads++;return visible.getOrDefault(s.requestId(),List.of());}}

    @Test @EnabledIfEnvironmentVariable(named="OPSWEAVE_TEST_LOGS_URL",matches=".+") void actualSuccessfulWriteThenReadFailureStaysUnknownAndOnlyOriginalVerificationCanConfirm(){
        var d=definition();var time=new Time();var actual=new ClickHouseWorkflowLogWindowSink(URI.create(System.getenv("OPSWEAVE_TEST_LOGS_URL")),System.getenv("OPSWEAVE_TEST_LOGS_USER"),System.getenv("OPSWEAVE_TEST_LOGS_PASSWORD"));var writes=new java.util.concurrent.atomic.AtomicInteger();var failRead=new java.util.concurrent.atomic.AtomicBoolean(true);
        var lost=new WorkflowLogWindowSink(){public boolean ready(){return actual.ready();}public void write(WorkflowLogWindow.Batch batch){writes.incrementAndGet();actual.write(batch);}public List<WorkflowLogWindow.Record> read(WorkflowLogOutput.Scope scope){if(failRead.get())throw new WorkflowLogOutputService.OutputFailure(false);return actual.read(scope);}};
        var runtime=service(wiring.workflows(),lost,time,(who,src,from,till)->rows(src,from,2));runtime.command(p,new Command(UUID.randomUUID(),d.id(),1,d.digest(),0,Operation.START),()->null);time.advance(11);runtime.tick(p);var before=runtime.status(p,d.id());var b=before.batches().getFirst();assertEquals("UNKNOWN",b.state());assertEquals("OUTPUT_UNCONFIRMED",before.task().error());assertEquals(0,before.task().confirmedRecords());assertEquals(1,writes.get());
        var d2=new WorkflowDefinition(d.id(),2,d.name(),d.source(),d.target(),d.nodes(),d.edges());wiring.workflows().transaction(tenant,s->{s.publish(new WorkflowStore.Entry(d2,d2.digest(),"PUBLISHED",0,Map.of("source",new WorkflowStore.Position(0,0),"mapping",new WorkflowStore.Position(0,160),"validate",new WorkflowStore.Position(0,320),"output",new WorkflowStore.Position(0,480)),time.instant(),null),owner);return null;});assertFalse(runtime.versionStatus(p,d.id(),2).control().startAllowed());assertThrows(WorkflowFailure.class,()->runtime.command(p,new Command(UUID.randomUUID(),d.id(),2,d2.digest(),1,Operation.START),()->null));
        failRead.set(false);var found=runtime.data(p,d.id(),b.id());assertTrue(found.complete());assertEquals(2,found.records().size());assertEquals(b,runtime.status(p,d.id()).batches().getFirst());runtime.verify(p,d.id(),b.id());assertEquals("STOPPED",runtime.status(p,d.id()).task().state());assertEquals(2,runtime.status(p,d.id()).task().confirmedRecords());assertEquals(1,writes.get());
    }
    @Test void legacyFailedBodyWithoutNoWriteEvidenceCannotResumeOrReplaceAndIsNotRewritten()throws Exception{
        var d=definition();var time=new Time();var rejected=new WorkflowLogWindowSink(){public boolean ready(){return true;}public void write(WorkflowLogWindow.Batch b){throw new WorkflowLogOutputService.OutputFailure(false);}public List<WorkflowLogWindow.Record> read(WorkflowLogOutput.Scope s){throw new AssertionError("No output query");}};var runtime=service(wiring.workflows(),rejected,time,(who,src,from,till)->rows(src,from,2));runtime.command(p,new Command(UUID.randomUUID(),d.id(),1,d.digest(),0,Operation.START),()->null);time.advance(11);runtime.tick(p);var before=runtime.status(p,d.id());var b=before.batches().getFirst();assertTrue(wiring.workflows().transaction(tenant,s->s.logStreamRejectionKnown(owner,b.id())).booleanValue());
        var quality=new WorkflowQualityService(wiring.workflows(),flows(wiring.workflows(),time),time);assertEquals(2,quality.batch(p,d.id(),1,b.id()).counts().outputRejected());var command=new WorkflowRecovery.Command(UUID.randomUUID(),d.id(),1,d.digest(),WorkflowQuality.Kind.LOG_STREAM,b.id(),1,true);var recovery=new WorkflowRecoveryService(wiring.workflows(),time);assertThrows(WorkflowFailure.class,()->recovery.abandon(p,command));assertEquals(before,runtime.status(p,d.id()));
        try(var c=source.getConnection();var q=c.prepareStatement("UPDATE integration.workflow_log_stream_batch SET rejection_known=false WHERE tenant_id=? AND owner_subject=? AND batch_id=?")){q.setString(1,tenant.value());q.setString(2,owner);q.setObject(3,b.id());assertEquals(1,q.executeUpdate());}
        assertFalse(runtime.versionStatus(p,d.id(),1).resumeAllowed());assertThrows(WorkflowFailure.class,()->runtime.command(p,new Command(UUID.randomUUID(),d.id(),1,d.digest(),1,Operation.RESUME),()->null));var d2=new WorkflowDefinition(d.id(),2,d.name(),d.source(),d.target(),d.nodes(),d.edges());wiring.workflows().transaction(tenant,s->{s.publish(new WorkflowStore.Entry(d2,d2.digest(),"PUBLISHED",0,Map.of("source",new WorkflowStore.Position(0,0),"mapping",new WorkflowStore.Position(0,160),"validate",new WorkflowStore.Position(0,320),"output",new WorkflowStore.Position(0,480)),time.instant(),null),owner);return null;});assertFalse(runtime.versionStatus(p,d.id(),2).control().startAllowed());assertThrows(WorkflowFailure.class,()->runtime.command(p,new Command(UUID.randomUUID(),d.id(),2,d2.digest(),1,Operation.START),()->null));assertEquals(before,runtime.status(p,d.id()));
        assertEquals(List.of(b.id()),runtime.versionStatus(p,d.id(),1).uncertainBatchIds());var observed=quality.batch(p,d.id(),1,b.id());assertEquals("UNKNOWN",observed.state());assertEquals(2,observed.counts().unknown());assertEquals(0,observed.counts().outputRejected());assertEquals(0,observed.counts().confirmed());assertEquals("OUTPUT_UNCONFIRMED",quality.report(p,d.id(),1).task().error());assertThrows(WorkflowFailure.class,()->runtime.verify(p,d.id(),b.id()));
        var other=new Principal(new SubjectId("other-legacy-fixture"),tenant,p.permissions(),ResourceScope.tenantWide());assertThrows(WorkflowFailure.class,()->recovery.abandon(other,command));assertThrows(WorkflowFailure.class,()->recovery.abandon(p,new WorkflowRecovery.Command(UUID.randomUUID(),d.id(),1,d.digest(),WorkflowQuality.Kind.LOG_STREAM,b.id(),2,true)));
        var receipt=recovery.abandon(p,command);var reopened=new PostgresWorkflowStore(source);var reread=new WorkflowRecoveryService(reopened,time);assertEquals(receipt,reread.receipt(p,command.requestId()));assertEquals(receipt,reread.abandon(p,command));assertEquals(b,reopened.transaction(tenant,s->s.logStreamBatch(owner,b.id()).orElseThrow()));assertFalse(reopened.transaction(tenant,s->s.logStreamRejectionKnown(owner,b.id())).booleanValue());assertEquals(before.task().cursor(),runtime.status(p,d.id()).task().cursor());assertEquals(0,runtime.status(p,d.id()).task().confirmedRecords());assertEquals("ABANDONED",quality.report(p,d.id(),1).task().state());assertEquals(observed,quality.batch(p,d.id(),1,b.id()));
        assertTrue(runtime.versionStatus(p,d.id(),2).control().startAllowed());runtime.command(p,new Command(UUID.randomUUID(),d.id(),2,d2.digest(),2,Operation.START),()->null);assertEquals("ABANDONED",quality.report(p,d.id(),1).task().state());assertEquals(observed,quality.batch(p,d.id(),1,b.id()));assertEquals(List.of(b.id()),runtime.versionStatus(p,d.id(),1).uncertainBatchIds());assertEquals(receipt,reread.receipt(p,command.requestId()));assertEquals(1,reopened.transaction(tenant,s->s.recoveryCount(owner)).intValue());
    }
    @Test @EnabledIfEnvironmentVariable(named="OPSWEAVE_TEST_LOGS_URL",matches=".+") void legacyUncertainObservationAndClosurePreserveActualOutputWithoutAnotherWrite()throws Exception{
        var d=definition();var time=new Time();var actual=new ClickHouseWorkflowLogWindowSink(URI.create(System.getenv("OPSWEAVE_TEST_LOGS_URL")),System.getenv("OPSWEAVE_TEST_LOGS_USER"),System.getenv("OPSWEAVE_TEST_LOGS_PASSWORD"));var writes=new java.util.concurrent.atomic.AtomicInteger();
        var lost=new WorkflowLogWindowSink(){public boolean ready(){return actual.ready();}public void write(WorkflowLogWindow.Batch b){writes.incrementAndGet();actual.write(b);throw new WorkflowLogOutputService.OutputFailure(true);}public List<WorkflowLogWindow.Record> read(WorkflowLogOutput.Scope scope){return actual.read(scope);}};
        var runtime=service(wiring.workflows(),lost,time,(who,src,from,till)->rows(src,from,2));runtime.command(p,new Command(UUID.randomUUID(),d.id(),1,d.digest(),0,Operation.START),()->null);time.advance(11);runtime.tick(p);var original=runtime.status(p,d.id()).batches().getFirst();
        // Explicit legacy fixture: old executors could store FAILED after a successful write.
        try(var c=source.getConnection();var q=c.prepareStatement("UPDATE integration.workflow_log_stream_batch SET body=jsonb_set(jsonb_set(body,'{state}','\"FAILED\"'::jsonb),'{error}','\"OUTPUT_REJECTED\"'::jsonb),rejection_known=false WHERE tenant_id=? AND owner_subject=? AND batch_id=?")){q.setString(1,tenant.value());q.setString(2,owner);q.setObject(3,original.id());assertEquals(1,q.executeUpdate());}
        var before=runtime.status(p,d.id());var raw=before.batches().getFirst();var found=runtime.data(p,d.id(),raw.id());assertTrue(found.complete());assertEquals(2,found.records().size());var quality=new WorkflowQualityService(wiring.workflows(),flows(wiring.workflows(),time),time);assertEquals("UNKNOWN",quality.batch(p,d.id(),1,raw.id()).state());assertEquals(2,quality.batch(p,d.id(),1,raw.id()).counts().unknown());assertFalse(runtime.versionStatus(p,d.id(),1).resumeAllowed());assertThrows(WorkflowFailure.class,()->runtime.verify(p,d.id(),raw.id()));
        var command=new WorkflowRecovery.Command(UUID.randomUUID(),d.id(),1,d.digest(),WorkflowQuality.Kind.LOG_STREAM,raw.id(),1,true);var recovery=new WorkflowRecoveryService(new PostgresWorkflowStore(source),time);var receipt=recovery.abandon(p,command);assertEquals(receipt,recovery.abandon(p,command));assertEquals(found.records(),runtime.data(p,d.id(),raw.id()).records());assertEquals(raw,runtime.status(p,d.id()).batches().getFirst());assertEquals("UNKNOWN",quality.batch(p,d.id(),1,raw.id()).state());assertEquals(0,quality.report(p,d.id(),1).batches().getFirst().counts().confirmed());assertEquals(before.task().cursor(),runtime.status(p,d.id()).task().cursor());assertEquals("ABANDONED",runtime.status(p,d.id()).task().state());assertNull(runtime.status(p,d.id()).task().authority());assertEquals(1,writes.get());
    }
    @Test void stoppedVersionArchiveReopensAndPreservesOriginalTaskAndBatches(){
        var d=definition();var time=new Time();var sink=new Sink();var runtime=service(wiring.workflows(),sink,time,(who,src,from,till)->rows(src,from,2));
        runtime.command(p,new Command(UUID.randomUUID(),d.id(),1,d.digest(),0,Operation.START),()->null);time.advance(11);runtime.tick(p);runtime.command(p,new Command(UUID.randomUUID(),d.id(),1,d.digest(),1,Operation.STOP),()->null);var before=runtime.status(p,d.id());
        var d2=new WorkflowDefinition(d.id(),2,d.name(),d.source(),d.target(),d.nodes(),d.edges());wiring.workflows().transaction(tenant,s->{s.publish(new WorkflowStore.Entry(d2,d2.digest(),"PUBLISHED",0,Map.of("source",new WorkflowStore.Position(0,0),"mapping",new WorkflowStore.Position(0,160),"validate",new WorkflowStore.Position(0,320),"output",new WorkflowStore.Position(0,480)),time.instant(),null),owner);return null;});
        var body=new Command(UUID.randomUUID(),d2.id(),2,d2.digest(),2,Operation.START);assertTrue(runtime.versionStatus(p,d.id(),2).control().startAllowed());var receipt=runtime.command(p,body,()->null);var reopened=new PostgresWorkflowStore(source);var archive=reopened.transaction(tenant,s->s.taskArchive(owner,d.id(),1,d.digest()).orElseThrow());
        assertEquals("STOPPED",archive.task().state());assertEquals(before.task().generation(),archive.task().generation());assertEquals(3,archive.nextGeneration());assertEquals(d2.digest(),archive.replacedBy().digest());assertEquals(before.batches(),runtime.status(p,d.id()).batches());assertEquals(0,receipt.task().confirmedRecords());assertEquals(1,sink.writes);assertTrue(reopened.transaction(tenant,s->s.taskArchive("other",d.id(),1,d.digest())).isEmpty());
        assertEquals(receipt,runtime.command(p,body,()->{throw new AssertionError("No replay issuance");}));assertEquals(1,reopened.transaction(tenant,s->s.taskArchiveCount(owner)).intValue());assertEquals(archive,WorkflowTaskArchiveJson.decode(CatalogJson.JSON.writeValueAsString(archive)));
        assertThrows(IllegalArgumentException.class,()->WorkflowTaskArchiveJson.decode(CatalogJson.JSON.writeValueAsString(archive).replace("\"2.0\"","\"2.0\",\"authority\":{}")));
    }
    @Test void archiveRollsBackTogetherWithReplacementWhenAuthorityIssuanceFails(){
        var d=definition();var time=new Time();var runtime=service(wiring.workflows(),new Sink(),time,(who,src,from,till)->rows(src,from,2));runtime.command(p,new Command(UUID.randomUUID(),d.id(),1,d.digest(),0,Operation.START),()->null);runtime.command(p,new Command(UUID.randomUUID(),d.id(),1,d.digest(),1,Operation.STOP),()->null);var before=runtime.status(p,d.id()).task();
        var d2=new WorkflowDefinition(d.id(),2,d.name(),d.source(),d.target(),d.nodes(),d.edges());wiring.workflows().transaction(tenant,s->{s.publish(new WorkflowStore.Entry(d2,d2.digest(),"PUBLISHED",0,Map.of("source",new WorkflowStore.Position(0,0),"mapping",new WorkflowStore.Position(0,160),"validate",new WorkflowStore.Position(0,320),"output",new WorkflowStore.Position(0,480)),time.instant(),null),owner);return null;});
        assertThrows(IllegalStateException.class,()->runtime.command(p,new Command(UUID.randomUUID(),d.id(),2,d2.digest(),2,Operation.START),()->{throw new IllegalStateException("Explicit fixture issuance failure");}));assertEquals(before,runtime.status(p,d.id()).task());assertEquals(0,wiring.workflows().transaction(tenant,s->s.taskArchiveCount(owner)).intValue());
    }
    @Test void archiveMigrationRollbackReapplyPreservesBothParentVersions()throws Exception{
        var schema="task_archive_fixture_"+UUID.randomUUID().toString().replace("-","");var forward=java.nio.file.Files.readString(java.nio.file.Path.of("../../db/migrations/platform/V051__workflow_task_archive.sql")).replace("integration.",schema+".");var reverse=java.nio.file.Files.readString(java.nio.file.Path.of("../../db/rollback/platform/V051__workflow_task_archive.sql")).replace("integration.",schema+".");
        try(var connection=source.getConnection();var statement=connection.createStatement()){
            statement.execute("CREATE SCHEMA "+schema);try{statement.execute("CREATE TABLE "+schema+".workflow_version(tenant_id text,workflow_id text,revision integer,PRIMARY KEY(tenant_id,workflow_id,revision))");statement.execute("INSERT INTO "+schema+".workflow_version VALUES('fixture','archive',1),('fixture','archive',2)");statement.execute(forward);statement.execute(reverse);statement.execute(forward);statement.execute("CREATE TABLE "+schema+".workflow_log_stream_batch(body jsonb)");statement.execute("INSERT INTO "+schema+".workflow_log_stream_batch VALUES('{\"state\":\"FAILED\",\"error\":\"OUTPUT_REJECTED\"}')");var certainty=java.nio.file.Files.readString(java.nio.file.Path.of("../../db/migrations/platform/V052__log_rejection_certainty.sql")).replace("integration.",schema+".");var undoCertainty=java.nio.file.Files.readString(java.nio.file.Path.of("../../db/rollback/platform/V052__log_rejection_certainty.sql")).replace("integration.",schema+".");statement.execute(certainty);try(var evidence=statement.executeQuery("SELECT rejection_known,body->>'state' FROM "+schema+".workflow_log_stream_batch")){assertTrue(evidence.next());assertFalse(evidence.getBoolean(1));assertEquals("FAILED",evidence.getString(2));}statement.execute(undoCertainty);statement.execute(certainty);try(var rows=statement.executeQuery("SELECT count(*) FROM "+schema+".workflow_version")){rows.next();assertEquals(2,rows.getInt(1));}}finally{statement.execute("DROP SCHEMA "+schema+" CASCADE");}
        }
    }
    @Test void recoveryClosureReopensReplaysAndRollsBackWithoutChangingUnknownProof(){
        var d=definition();var time=new Time();var sink=new Sink();sink.unknown=true;var runtime=service(wiring.workflows(),sink,time,(who,src,from,till)->rows(src,from,2));runtime.command(p,new Command(UUID.randomUUID(),d.id(),1,d.digest(),0,Operation.START),()->null);time.advance(11);runtime.tick(p);var before=runtime.status(p,d.id());var b=before.batches().getFirst();var body=new WorkflowRecovery.Command(UUID.randomUUID(),d.id(),1,d.digest(),WorkflowQuality.Kind.LOG_STREAM,b.id(),1,true);var recovery=new WorkflowRecoveryService(wiring.workflows(),time);
        assertThrows(IllegalStateException.class,()->wiring.workflows().transaction(tenant,s->{s.saveLogStreamTask(owner,before.task().state(2,"ABANDONED","OUTPUT_UNCONFIRMED",time.instant(),before.task().sessionBatches(),null));throw new IllegalStateException("Explicit fixture rollback");}));assertEquals(before,runtime.status(p,d.id()));
        var receipt=recovery.abandon(p,body);var reopened=new PostgresWorkflowStore(source);var read=new WorkflowRecoveryService(reopened,time);assertEquals(receipt,read.receipt(p,body.requestId()));assertEquals(receipt,read.abandon(p,body));assertEquals(b,reopened.transaction(tenant,s->s.logStreamBatch(owner,b.id()).orElseThrow()));assertEquals(before.task().cursor(),runtime.status(p,d.id()).task().cursor());assertEquals("ABANDONED",runtime.status(p,d.id()).task().state());assertNull(runtime.status(p,d.id()).task().authority());time.advance(60);runtime.tick(p);assertEquals(1,sink.writes);assertThrows(WorkflowFailure.class,()->runtime.verify(p,d.id(),b.id()));assertThrows(WorkflowFailure.class,()->runtime.command(p,new Command(UUID.randomUUID(),d.id(),1,d.digest(),2,Operation.RESUME),()->null));assertTrue(reopened.transaction(tenant,s->s.recovery("other",body.requestId())).isEmpty());assertFalse(CatalogJson.JSON.writeValueAsString(receipt).contains("Synthetic Fixture"));
    }
    @Test void versionStatusPreservesHistoricalClosureAfterNewTaskReplacesCurrent(){
        var d=definition();var time=new Time();var sink=new Sink();sink.unknown=true;var runtime=service(wiring.workflows(),sink,time,(who,src,from,till)->rows(src,from,2));runtime.command(p,new Command(UUID.randomUUID(),d.id(),1,d.digest(),0,Operation.START),()->null);time.advance(11);runtime.tick(p);var b=runtime.status(p,d.id()).batches().getFirst();var recovery=new WorkflowRecoveryService(wiring.workflows(),time);var receipt=recovery.abandon(p,new WorkflowRecovery.Command(UUID.randomUUID(),d.id(),1,d.digest(),WorkflowQuality.Kind.LOG_STREAM,b.id(),1,true));
        var d2=new WorkflowDefinition(d.id(),2,d.name(),d.source(),d.target(),d.nodes(),d.edges());wiring.workflows().transaction(tenant,s->{s.publish(new WorkflowStore.Entry(d2,d2.digest(),"PUBLISHED",0,Map.of("source",new WorkflowStore.Position(0,0),"mapping",new WorkflowStore.Position(0,160),"validate",new WorkflowStore.Position(0,320),"output",new WorkflowStore.Position(0,480)),time.instant(),null),owner);return null;});
        var waiting=runtime.versionStatus(p,d.id(),2);assertNull(waiting.task());assertTrue(waiting.batches().isEmpty());assertEquals(2,waiting.control().generation());assertTrue(waiting.control().startAllowed());runtime.command(p,new Command(UUID.randomUUID(),d2.id(),2,d2.digest(),2,Operation.START),()->null);
        var reopened=service(new PostgresWorkflowStore(source),sink,time,(who,src,from,till)->{throw new AssertionError("Read only");});var old=reopened.versionStatus(p,d.id(),1);assertNull(old.task());assertTrue(old.control().recoveryClosed());assertFalse(old.control().startAllowed());assertEquals(List.of(b),old.batches());var fresh=reopened.versionStatus(p,d.id(),2);assertEquals(2,fresh.task().revision());assertTrue(fresh.batches().isEmpty());assertEquals(receipt,new WorkflowRecoveryService(new PostgresWorkflowStore(source),time).receipt(p,receipt.requestId()));assertEquals(1,sink.writes);
    }
    @Test @EnabledIfEnvironmentVariable(named="OPSWEAVE_TEST_LOGS_URL",matches=".+") void actualLogOutputRemainsPresentAfterRecoveryClosure(){
        var d=definition();var time=new Time();var actual=new ClickHouseWorkflowLogWindowSink(URI.create(System.getenv("OPSWEAVE_TEST_LOGS_URL")),System.getenv("OPSWEAVE_TEST_LOGS_USER"),System.getenv("OPSWEAVE_TEST_LOGS_PASSWORD"));var writes=new java.util.concurrent.atomic.AtomicInteger();
        var lost=new WorkflowLogWindowSink(){public boolean ready(){return actual.ready();}public void write(WorkflowLogWindow.Batch b){writes.incrementAndGet();actual.write(b);throw new WorkflowLogOutputService.OutputFailure(true);}public List<WorkflowLogWindow.Record> read(WorkflowLogOutput.Scope scope){return actual.read(scope);}};
        var runtime=service(wiring.workflows(),lost,time,(who,src,from,till)->rows(src,from,2));runtime.command(p,new Command(UUID.randomUUID(),d.id(),1,d.digest(),0,Operation.START),()->null);time.advance(11);runtime.tick(p);var before=runtime.status(p,d.id());assertEquals("UNKNOWN",before.batches().getFirst().state());var b=before.batches().getFirst();var original=runtime.data(p,d.id(),b.id()).records();assertEquals(2,original.size());var recovery=new WorkflowRecoveryService(new PostgresWorkflowStore(source),time);recovery.abandon(p,new WorkflowRecovery.Command(UUID.randomUUID(),d.id(),1,d.digest(),WorkflowQuality.Kind.LOG_STREAM,b.id(),1,true));assertEquals(original,runtime.data(p,d.id(),b.id()).records());assertEquals(b,runtime.status(p,d.id()).batches().getFirst());assertEquals(0,runtime.status(p,d.id()).task().confirmedRecords());assertEquals(1,writes.get());
    }
    @Test void closureMigrationRollbackReapplyIsIsolatedAndPreservesParent()throws Exception{
        var schema="recovery_fixture_"+UUID.randomUUID().toString().replace("-","");var forward=java.nio.file.Files.readString(java.nio.file.Path.of("../../db/migrations/platform/V050__workflow_recovery_closure.sql")).replace("integration.",schema+".");var reverse=java.nio.file.Files.readString(java.nio.file.Path.of("../../db/rollback/platform/V050__workflow_recovery_closure.sql")).replace("integration.",schema+".");
        try(var c=source.getConnection()){c.setAutoCommit(false);try(var q=c.createStatement()){q.execute("CREATE SCHEMA "+schema);q.execute("CREATE TABLE "+schema+".workflow_version(tenant_id text,workflow_id text,revision integer,PRIMARY KEY(tenant_id,workflow_id,revision))");q.execute("INSERT INTO "+schema+".workflow_version VALUES ('fixture','fixed',1)");q.execute(forward);q.execute(reverse);q.execute(forward);try(var r=q.executeQuery("SELECT count(*) FROM "+schema+".workflow_version")){r.next();assertEquals(1,r.getInt(1));}}finally{c.rollback();}}
    }
    @Test void unknownAndOriginalControlSurviveReopeningWithNoImplicitResend(){
        var d=definition();var time=new Time();var sink=new Sink();sink.unknown=true;var service=service(wiring.workflows(),sink,time,(who,src,from,till)->rows(src,from,2));var command=new Command(UUID.randomUUID(),d.id(),1,d.digest(),0,Operation.START);var receipt=service.command(p,command,()->null);time.advance(11);service.tick(p);var unknown=service.status(p,d.id());assertEquals("UNKNOWN",unknown.batches().getFirst().state());assertEquals(0,unknown.task().confirmedWindows());
        var reopened=service(new PostgresWorkflowStore(source),sink,time,(who,src,from,till)->{throw new AssertionError("No source retry");});assertEquals(unknown,reopened.status(p,d.id()));assertEquals(receipt,reopened.command(p,command,()->{throw new AssertionError("No authorization renewal");}));time.advance(60);reopened.tick(p);reopened.verify(p,d.id(),unknown.task().pendingBatchId());assertEquals(1,sink.writes);assertEquals(0,reopened.status(p,d.id()).task().confirmedRecords());sink.visible.put(sink.last.scope().requestId(),sink.last.records());var confirmed=reopened.verify(p,d.id(),unknown.task().pendingBatchId());assertEquals("STOPPED",confirmed.task().state());assertEquals(2,confirmed.task().confirmedRecords());assertEquals(1,sink.writes);assertNull(confirmed.task().pendingBatchId());
        assertFalse(CatalogJson.JSON.writeValueAsString(confirmed).contains("Synthetic Fixture"));assertThrows(IllegalArgumentException.class,()->WorkflowLogStreamJson.batch(CatalogJson.JSON.writeValueAsString(confirmed.batches().getFirst()).replace("\"inputCount\":2","\"inputCount\":\"2\"")));
    }
    @Test void scopeRollbackAndTerminalProofCannotBeRewritten(){
        var d=definition();var time=new Time();var sink=new Sink();var service=service(wiring.workflows(),sink,time,(who,src,from,till)->rows(src,from,2));service.command(p,new Command(UUID.randomUUID(),d.id(),1,d.digest(),0,Operation.START),()->null);time.advance(11);service.tick(p);var proof=service.status(p,d.id()).batches().getFirst();var reopened=new PostgresWorkflowStore(source);
        assertTrue(reopened.transaction(tenant,s->s.logStreamBatch("other",proof.id())).isEmpty());assertTrue(reopened.transaction(new com.acme.opsweave.sharedkernel.TenantId(tenant.value()+"-other"),s->s.logStreamBatch(owner,proof.id())).isEmpty());assertThrows(IllegalStateException.class,()->reopened.transaction(tenant,s->{s.finishLogStreamBatch(owner,proof.finish("UNKNOWN","OUTPUT_UNCONFIRMED",time.instant()));return null;}));
        var copy=new Batch(UUID.randomUUID(),d.id(),1,d.digest(),proof.from(),proof.till(),time.instant(),time.instant(),"IN_FLIGHT",proof.inputCount(),0,0,proof.indices(),proof.positions(),proof.inputDigest(),proof.batchDigest(),null,null);assertThrows(IllegalStateException.class,()->reopened.transaction(tenant,s->{s.addLogStreamBatch(owner,copy);throw new IllegalStateException("Synthetic Fixture rollback");}));assertTrue(reopened.transaction(tenant,s->s.logStreamBatch(owner,copy.id())).isEmpty());assertEquals(proof,reopened.transaction(tenant,s->s.logStreamBatch(owner,proof.id()).orElseThrow()));
    }
    @Test @EnabledIfEnvironmentVariable(named="OPSWEAVE_TEST_LOGS_URL",matches=".+") void thousandRecordsAndLateSupplementUseActualStorageAndReopenedCheckpoint(){
        var d=definition();var time=new Time();var count=new java.util.concurrent.atomic.AtomicInteger(998);var sink=new ClickHouseWorkflowLogWindowSink(URI.create(System.getenv("OPSWEAVE_TEST_LOGS_URL")),System.getenv("OPSWEAVE_TEST_LOGS_USER"),System.getenv("OPSWEAVE_TEST_LOGS_PASSWORD"));assertTrue(sink.ready());WorkflowLogStreamService.Source input=(who,src,from,till)->rows(src,from,count.get());var service=service(wiring.workflows(),sink,time,input);service.command(p,new Command(UUID.randomUUID(),d.id(),1,d.digest(),0,Operation.START),()->null);time.advance(11);service.tick(p);var initial=service.status(p,d.id());assertEquals(998,initial.task().confirmedRecords(),initial.task().error());var original=initial.batches().getFirst();count.set(1000);time.advance(60);service.tick(p);var status=service.status(p,d.id());assertEquals(1000,status.task().confirmedRecords(),status.task().error());assertEquals(1,status.task().confirmedWindows());assertEquals(initial.task().cursor(),status.task().cursor());var supplement=status.batches().getFirst();assertEquals(original.id(),supplement.reconcilesBatchId());assertEquals(998,supplement.deduplicated());assertEquals(List.of(998,999),supplement.indices());assertEquals(2,service.data(p,d.id(),supplement.id()).records().size());
        var reopened=service(new PostgresWorkflowStore(source),sink,time,input);assertEquals(status,reopened.status(p,d.id()));assertTrue(reopened.data(p,d.id(),original.id()).complete());assertEquals(50,reopened.data(p,d.id(),original.id()).records().size());assertEquals(50,reopened.data(p,d.id(),original.id(),49).records().getFirst().index());assertTrue(CatalogJson.JSON.writeValueAsString(supplement).length()>32768);assertFalse(CatalogJson.JSON.writeValueAsString(supplement).contains("Synthetic Fixture"));
        wiring.workflows().transaction(tenant,s->{for(int i=0;i<20;i++){var at=time.instant().plusNanos((i+1)*1000L);var b=new Batch(UUID.randomUUID(),d.id(),1,d.digest(),supplement.from(),supplement.till(),at,at,"IN_FLIGHT",original.inputCount(),0,0,original.indices(),original.positions(),original.inputDigest(),original.batchDigest(),null,null);s.addLogStreamBatch(owner,b);s.finishLogStreamBatch(owner,b.finish("FAILED","OUTPUT_REJECTED",at));}return null;});assertTrue(reopened.status(p,d.id()).batches().stream().noneMatch(b->b.id().equals(supplement.id())));time.advance(1);reopened.tick(p);
        // A successful external write can have an unavailable immediate read. One explicit original
        // verification exercises recovery; it cannot write or silently restart the task.
        var after=reopened.status(p,d.id());if(after.task().pendingBatchId()!=null){var pending=wiring.workflows().transaction(tenant,s->s.logStreamBatch(owner,after.task().pendingBatchId()).orElseThrow());assertEquals("UNKNOWN",pending.state());assertEquals("OUTPUT_UNCONFIRMED",after.task().error());reopened.verify(p,d.id(),pending.id());}
        assertEquals(2,reopened.status(p,d.id()).task().confirmedWindows(),reopened.status(p,d.id()).task().error());assertEquals(2000,reopened.status(p,d.id()).task().confirmedRecords());
    }
}
