package com.acme.opsweave.platform.persistence;

import static org.junit.jupiter.api.Assertions.*;
import com.acme.opsweave.identity.domain.*;
import com.acme.opsweave.integration.api.WorkflowStore;
import com.acme.opsweave.integration.application.*;
import com.acme.opsweave.integration.domain.*;
import com.acme.opsweave.integration.domain.WorkflowQualityAlerts.*;
import com.acme.opsweave.platform.OpsweaveProperties;
import com.acme.opsweave.platform.catalog.CatalogJson;
import com.acme.opsweave.platform.workflow.WorkflowQualityAlertsJson;
import com.acme.opsweave.sharedkernel.TenantId;
import java.time.*;
import java.time.temporal.ChronoUnit;
import java.util.*;
import java.nio.file.*;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.condition.EnabledIfEnvironmentVariable;
import org.springframework.jdbc.datasource.DriverManagerDataSource;

/** Actual isolated PostgreSQL tenants, with synthetic fixed-source metadata and no provider IO. */
@EnabledIfEnvironmentVariable(named="OPSWEAVE_TEST_JDBC_URL",matches=".+")
class PostgresWorkflowQualityAlertsIT extends OwnedInventoryTest {
 final TenantId tenant=new TenantId("quality-alert-pg-fixture-"+UUID.randomUUID());final String owner="quality-alert-author";
 final DriverManagerDataSource source=new DriverManagerDataSource(System.getenv("OPSWEAVE_TEST_JDBC_URL"),System.getenv("OPSWEAVE_TEST_JDBC_USER"),System.getenv("OPSWEAVE_TEST_JDBC_PASSWORD"));
 final InventoryWiring wiring=openInventory(new OpsweaveProperties(new OpsweaveProperties.Auth("closed",true,new OpsweaveProperties.Auth.Dev("","",tenant.value(),"","")),new OpsweaveProperties.Zabbix("fixture","","env:OPSWEAVE_ZABBIX_TOKEN","quality-alert-fixture",1),new OpsweaveProperties.Inventory("postgres",System.getenv("OPSWEAVE_TEST_JDBC_URL"),System.getenv("OPSWEAVE_TEST_JDBC_USER"),System.getenv("OPSWEAVE_TEST_JDBC_PASSWORD"))));
 final Principal principal=new Principal(new SubjectId(owner),tenant,Set.of(Permission.SOURCE_SYNC,Permission.LOG_READ),ResourceScope.tenantWide());
 final Instant at=Instant.now().minusSeconds(3).truncatedTo(ChronoUnit.MICROS);
 WorkflowDefinition definition(){var sid=UUID.randomUUID();var item=new SourceMetricDiscovery.Item("1","2","log[/synthetic-fixture]","Synthetic Fixture","","LOG","NO_MAPPING",null);var src=new WorkflowDefinition.Source("ZABBIX_LOG",sid.toString(),new WorkflowDefinition.ConfigurationPin(sid,1,"sha256:"+"a".repeat(64)),null,WorkflowLogSourcePin.from(UUID.randomUUID(),item));var nodes=List.of(new WorkflowDefinition.Node("source",WorkflowDefinition.Type.SOURCE,"1",Map.of()),new WorkflowDefinition.Node("map",WorkflowDefinition.Type.MAP,"1",Map.of("timestamp","eventTime","body","body")),new WorkflowDefinition.Node("validate",WorkflowDefinition.Type.VALIDATE,"1",Map.of()),new WorkflowDefinition.Node("output",WorkflowDefinition.Type.OUTPUT,"1",Map.of()));var d=WorkflowOperators.builtIn().pin(new WorkflowDefinition("quality-alert-fixture",1,"Synthetic Fixture",src,new WorkflowDefinition.Target(null,1,null,"LOG"),nodes,List.of(new WorkflowDefinition.Edge("source","map"),new WorkflowDefinition.Edge("map","validate"),new WorkflowDefinition.Edge("validate","output"))));var layout=new HashMap<String,WorkflowStore.Position>();nodes.forEach(n->layout.put(n.id(),new WorkflowStore.Position(0,0)));wiring.workflows().transaction(tenant,s->{s.publish(new WorkflowStore.Entry(d,d.digest(),"PUBLISHED",0,layout,at,null),owner);return null;});return d;}
 WorkflowQualityAlertService service(WorkflowStore store){var guards=new WorkflowService.Sources(){public void require(Principal p,WorkflowDefinition.Source src,WorkflowStore.Session s,boolean available){assertFalse(available);}public void requireTarget(Principal p,WorkflowDefinition.Source src,WorkflowDefinition.Target target,WorkflowStore.Session s,boolean available){assertFalse(available);}};var flows=new WorkflowService(store,(p,t)->{throw new AssertionError("No model IO");},(p,src,id)->{throw new AssertionError("No source IO");},guards,Clock.systemUTC());return new WorkflowQualityAlertService(store,flows,Clock.systemUTC());}
 @Test void realSettingsReopenIdempotencyAndCurrentEvidenceAreIsolated()throws Exception{
  var d=definition();var api=service(wiring.workflows());assertNull(api.status(principal,d.id(),1).configuration());var cmd=new Command(UUID.randomUUID(),d.id(),1,d.digest(),0,600,List.of(new Rule(Kind.SOURCE_FAILURES,1),new Rule(Kind.QUEUE_WAIT,250),new Rule(Kind.TASK_FAILURE,1)));var accepted=api.configure(principal,cmd);assertEquals(accepted,api.configure(principal,cmd));assertEquals(accepted,WorkflowQualityAlertsJson.receipt(CatalogJson.JSON.writeValueAsString(accepted)));
  var from=at.minusSeconds(80).truncatedTo(ChronoUnit.SECONDS);var ref=cmd.reference();var dispatch=new WorkflowDiagnostics.Dispatch(UUID.randomUUID(),at.minusMillis(275),at);var observation=new WorkflowDiagnostics.Observation(UUID.randomUUID(),ref,WorkflowQuality.Kind.LOG_STREAM,1,"SOURCE_FAILED",from,from.plusSeconds(60),at,at,275L,null,"SOURCE_UNAVAILABLE",WorkflowDiagnostics.Result.unavailable(),new WorkflowDiagnostics.SourceRead(1,0,1,null,WorkflowDiagnostics.SourceFailure.UNAVAILABLE,at,at),dispatch);var task=new WorkflowLogStream.Task(d.id(),1,d.digest(),1,"FAILED",from,null,0,0,0,at,"SOURCE_UNAVAILABLE",null);wiring.workflows().transaction(tenant,s->{s.addDiagnostic(owner,new WorkflowDiagnostics.Stored(observation,List.of()));s.saveLogStreamTask(owner,task);return null;});var reopened=new PostgresWorkflowStore(source);var report=service(reopened).status(principal,d.id(),1);assertTrue(report.evaluations().stream().allMatch(e->e.state()==State.TRIGGERED));assertEquals(275L,report.evaluations().get(1).value().longValue());assertEquals(accepted,service(reopened).receipt(principal,d.id(),1,cmd.requestId()));assertEquals(1,reopened.transaction(tenant,s->s.alertCommandCount(owner)).intValue());assertEquals(observation,reopened.transaction(tenant,s->s.diagnostic(owner,observation.id()).orElseThrow()).observation());
  var other=new Principal(new SubjectId("other"),tenant,principal.permissions(),principal.resourceScope());assertNull(service(reopened).status(other,d.id(),1).configuration());assertEquals(WorkflowFailure.Code.NOT_FOUND,assertThrows(WorkflowFailure.class,()->service(reopened).receipt(other,d.id(),1,cmd.requestId())).code());var foreign=new Principal(principal.subjectId(),new TenantId(tenant.value()+"-other"),principal.permissions(),principal.resourceScope());assertThrows(WorkflowFailure.class,()->service(reopened).status(foreign,d.id(),1));var denied=new Principal(principal.subjectId(),tenant,Set.of(Permission.SOURCE_SYNC),principal.resourceScope());assertEquals(WorkflowFailure.Code.FORBIDDEN,assertThrows(WorkflowFailure.class,()->api.configure(denied,new Command(UUID.randomUUID(),d.id(),1,d.digest(),1,600,List.of()))).code());assertEquals(WorkflowFailure.Code.CONFLICT,assertThrows(WorkflowFailure.class,()->api.configure(principal,new Command(UUID.randomUUID(),d.id(),1,d.digest(),0,600,List.of()))).code());
  var off=api.configure(principal,new Command(UUID.randomUUID(),d.id(),1,d.digest(),1,600,List.of()));assertTrue(off.configuration().rules().isEmpty());assertTrue(service(reopened).status(principal,d.id(),1).evaluations().isEmpty());assertEquals(accepted,service(reopened).receipt(principal,d.id(),1,cmd.requestId()));
  try(var c=source.getConnection();var q=c.prepareStatement("UPDATE integration.workflow_quality_alert_configuration SET body=jsonb_set(body,'{editVersion}','9'::jsonb) WHERE tenant_id=?")){q.setString(1,tenant.value());assertEquals(1,q.executeUpdate());}assertThrows(IllegalStateException.class,()->service(reopened).status(principal,d.id(),1));
 }
 @Test void migrationForwardRollbackAndForwardOnlyTouchAnOwnedSchema()throws Exception{
  var schema="quality_alert_migration_fixture_"+UUID.randomUUID().toString().replace("-","");assertTrue(schema.matches("quality_alert_migration_fixture_[a-f0-9]{32}"));var root=Path.of(System.getProperty("user.dir")).toAbsolutePath();while(!Files.exists(root.resolve("db/migrations/platform/V054__workflow_quality_alerts.sql")))root=root.getParent();var forward=Files.readString(root.resolve("db/migrations/platform/V054__workflow_quality_alerts.sql")).replace("integration.",schema+".");var rollback=Files.readString(root.resolve("db/rollback/platform/V054__workflow_quality_alerts.sql")).replace("integration.",schema+".");try(var c=source.getConnection();var q=c.createStatement()){try{q.execute("CREATE SCHEMA "+schema);q.execute("CREATE TABLE "+schema+".workflow_version(tenant_id text,workflow_id text,revision integer,PRIMARY KEY(tenant_id,workflow_id,revision))");q.execute(forward);try(var result=q.executeQuery("SELECT to_regclass('"+schema+".workflow_quality_alert_command') IS NOT NULL")){result.next();assertTrue(result.getBoolean(1));}q.execute(rollback);try(var result=q.executeQuery("SELECT to_regclass('"+schema+".workflow_quality_alert_command') IS NULL AND to_regclass('"+schema+".workflow_quality_alert_configuration') IS NULL AND to_regclass('"+schema+".workflow_version') IS NOT NULL")){result.next();assertTrue(result.getBoolean(1));}q.execute(forward);try(var result=q.executeQuery("SELECT to_regclass('"+schema+".workflow_quality_alert_configuration') IS NOT NULL")){result.next();assertTrue(result.getBoolean(1));}}finally{q.execute("DROP SCHEMA "+schema+" CASCADE");}}
 }
}
