import com.acme.opsweave.catalog.domain.*;
import com.acme.opsweave.catalog.domain.ModelDefinition.*;
import com.acme.opsweave.catalog.application.*;
import com.acme.opsweave.catalog.infrastructure.InMemoryModelCatalogStore;
import com.acme.opsweave.integration.application.*;
import com.acme.opsweave.integration.domain.*;
import com.acme.opsweave.integration.infrastructure.InMemoryWorkflowStore;
import com.acme.opsweave.identity.domain.*;
import java.time.*;
import java.util.*;
import java.math.BigDecimal;

/** Explicit fixtures: compatibility parity, exact private candidates, authorized references and no execution. */
public final class ModelImpactSmoke {
 static int checks;static void check(boolean v){checks++;if(!v)throw new AssertionError("Model impact "+checks);}
 static void rejects(Runnable r){checks++;try{r.run();}catch(CatalogFailure|WorkflowFailure|IllegalArgumentException expected){return;}throw new AssertionError("Expected rejection "+checks);}
 static ModelDefinition model(int rev,List<Field> fields){return new ModelDefinition("custom.impact",rev,Kind.ENTITY,"Fixture model","Fixture",fields,null);}
 static ModelRevisionReview.Review compare(ModelDefinition a,ModelDefinition b){return ModelRevisionReview.compare(a,b,1,Instant.parse("2026-10-04T07:00:00Z"),true);}
 static void parity(ModelDefinition a,ModelDefinition b){boolean compatible=true;try{b.requireCompatibleWith(a);}catch(CatalogFailure rejected){compatible=false;}check(compare(a,b).compatible()==compatible);}
 public static void main(String[] args){
  var name=ModelCatalogSmoke.text("name",true);var one=model(1,List.of(name));var two=model(2,List.of(name,ModelCatalogSmoke.text("owner",false)));check(compare(null,one).compatible());check(compare(one,two).compatible());check(compare(one,two).changes().getFirst().fieldId().equals("owner"));parity(one,two);
  var candidates=List.of(model(2,List.of()),model(2,List.of(name,ModelCatalogSmoke.text("owner",true))),model(3,List.of(name)),model(2,List.of(ModelCatalogSmoke.text("name",false))),model(2,List.of(new Field("name","N",Type.TEXT,true,254,null,null,List.of()))),model(2,List.of(new Field("name","N",Type.INTEGER,true,null,null,null,List.of()))));for(var candidate:candidates)parity(one,candidate);
  var cosmetic=new ModelDefinition(one.id(),2,Kind.ENTITY,"New display","New description",List.of(new Field("name","New field label",Type.TEXT,true,255,null,null,List.of())),null);check(compare(one,cosmetic).changes().size()==3);parity(one,cosmetic);
  var decimal=model(1,List.of(new Field("value","V",Type.DECIMAL,false,null,new BigDecimal("1.00"),new BigDecimal("9.00"),List.of())));var same=model(2,List.of(new Field("value","V",Type.DECIMAL,false,null,BigDecimal.ONE,new BigDecimal("9"),List.of())));check(compare(decimal,same).changes().isEmpty());parity(decimal,same);
  var a=model(1,List.of(new Field("choice","C",Type.ENUM,false,80,null,null,List.of("a | b","c"))));var b=model(2,List.of(new Field("choice","C",Type.ENUM,false,80,null,null,List.of("a","b | c"))));check(!compare(a,b).compatible());parity(a,b);
  var rel=new ModelDefinition("custom.self",1,Kind.RELATION,"Fixture self","",List.of(),new Endpoints(one.ref(),one.ref(),Cardinality.MANY_TO_MANY));var next=new ModelDefinition(rel.id(),2,Kind.RELATION,rel.label(),"",List.of(),new Endpoints(two.ref(),one.ref(),Cardinality.MANY_TO_MANY));parity(rel,next);check(!ModelRevisionReview.compare(null,rel,1,Instant.now(),false).compatible());
  var store=new InMemoryModelCatalogStore();var clock=Clock.fixed(Instant.parse("2026-10-04T07:00:00Z"),ZoneOffset.UTC);var p=ModelCatalogSmoke.principal("impact-a","one",Set.of(Permission.ENTITY_READ,Permission.ENTITY_MANAGE,Permission.SOURCE_SYNC),ResourceScope.tenantWide());var other=ModelCatalogSmoke.principal("impact-a","two",p.permissions(),p.resourceScope());var foreign=ModelCatalogSmoke.principal("impact-b","one",p.permissions(),p.resourceScope());var service=new ModelCatalogService(store,List.of(),clock);service.save(p,one,0);
  check(service.review(p,one.ref(),1,one.digest()).compatible());rejects(()->service.review(other,one.ref(),1,one.digest()));rejects(()->service.review(foreign,one.ref(),1,one.digest()));rejects(()->service.review(p,one.ref(),2,one.digest()));rejects(()->service.review(p,one.ref(),1,"sha256:"+"0".repeat(64)));check(service.published(p).items().isEmpty());service.publish(p,one.ref(),1,one.digest());rejects(()->service.review(p,one.ref(),1,one.digest()));service.save(p,two,0);check(service.review(p,two.ref(),1,two.digest()).base().digest().equals(one.digest()));check(store.find(p.tenantId(),two.ref()).isEmpty());service.save(p,rel,0);service.publish(p,rel.ref(),1,rel.digest());check(store.relations(p.tenantId(),one.ref(),51).size()==1);check(store.relations(foreign.tenantId(),one.ref(),51).isEmpty());check(store.relations(p.tenantId(),two.ref(),51).isEmpty());
  var refs=new ModelReferenceService(store,List.of(),(who,pin)->new ModelReferences.Page(List.of(),false),clock);var report=refs.references(p,one.ref());check(report.references().items().getFirst().roles().equals(List.of("FROM","TO")));check(report.target().digest().equals(one.digest()));rejects(()->refs.references(foreign,one.ref()));rejects(()->refs.references(p,two.ref()));var reader=ModelCatalogSmoke.principal("impact-a","reader",Set.of(Permission.ENTITY_READ),ResourceScope.tenantWide());var restricted=new ModelReferenceService(store,List.of(),(who,pin)->{throw new AssertionError("No unauthorized workflow read");},clock);check(!restricted.references(reader,one.ref()).workflowsAvailable());
  for(int i=0;i<51;i++){var r=new ModelDefinition("custom.rel_"+i,1,Kind.RELATION,"Fixture relation","",List.of(),rel.endpoints());service.save(p,r,0);service.publish(p,r.ref(),1,r.digest());}check(refs.references(p,one.ref()).references().truncated());check(refs.references(p,one.ref()).references().items().size()==50);check(service.review(p,two.ref(),1,two.digest()).base().revision()==1);
  var flows=new InMemoryWorkflowStore();var flowService=new WorkflowService(flows,(who,target)->WorkflowSmoke.MODEL,(who,source,id)->{throw new AssertionError("No sample read");},clock);var wp=WorkflowSmoke.principal("impact-flow","owner");var wo=WorkflowSmoke.principal("impact-flow","other");var wt=WorkflowSmoke.principal("impact-other","owner");var flow=WorkflowSmoke.flow();flowService.save(wp,flow,WorkflowSmoke.layout(flow),0);var otherFlow=WorkflowSmoke.flow("other-private",1,flow.source());flowService.save(wo,otherFlow,WorkflowSmoke.layout(otherFlow),0);var wr=new WorkflowModelReferenceService(flows,flowService);var pin=ModelRevisionReview.pin(WorkflowSmoke.MODEL);check(wr.references(wp,pin).items().size()==1);check(wr.references(wo,pin).items().getFirst().id().equals("other-private"));check(wr.references(wt,pin).items().isEmpty());check(wr.references(wp,pin).items().getFirst().fieldIds().equals(List.of("count","name","state")));check(wr.references(wp,new ModelRevisionReview.Pin(pin.id(),2,pin.digest())).items().isEmpty());rejects(()->wr.references(wp,new ModelRevisionReview.Pin(pin.id(),1,"sha256:"+"0".repeat(64))));
  var deniedService=new WorkflowService(flows,(who,target)->WorkflowSmoke.MODEL,(who,source,id)->{throw new AssertionError();},(who,source,s,available)->{check(!available);throw new WorkflowFailure(WorkflowFailure.Code.FORBIDDEN);},clock);check(new WorkflowModelReferenceService(flows,deniedService).references(wp,pin).items().isEmpty());var failingService=new WorkflowService(flows,(who,target)->WorkflowSmoke.MODEL,(who,source,id)->{throw new AssertionError();},(who,source,s,available)->{throw new WorkflowFailure(WorkflowFailure.Code.SOURCE_UNAVAILABLE);},clock);rejects(()->new WorkflowModelReferenceService(flows,failingService).references(wp,pin));
  var host=new WorkflowHostRuntimeSmoke.Fixture();var schedule=new WorkflowHostScheduleService(host.store,host.runtime,host.clock);schedule.command(host.p,WorkflowHostScheduleSmoke.command(host,WorkflowHostSchedule.Operation.START,0),()->null);var hs=new WorkflowService(host.store,(who,target)->WorkflowSmoke.MODEL,(who,source,id)->{throw new AssertionError();},(who,source,s,available)->check(!available),host.clock);var hr=new WorkflowModelReferenceService(host.store,hs);check(hr.references(host.p,pin).items().getFirst().tasks().size()==2);check(host.reads==0&&host.writes==0);var outsider=new Principal(new SubjectId("other"),host.p.tenantId(),host.p.permissions(),host.p.resourceScope());check(hr.references(outsider,pin).items().getFirst().tasks().isEmpty());
  System.out.println("ModelImpactSmoke: "+checks+" checks passed");
 }
}
