import com.acme.opsweave.integration.api.*;
import com.acme.opsweave.integration.application.*;
import com.acme.opsweave.integration.domain.*;
import com.acme.opsweave.integration.infrastructure.*;
import com.acme.opsweave.identity.domain.*;
import com.acme.opsweave.sharedkernel.TenantId;
import java.time.*;
import java.util.*;
import java.util.concurrent.*;
import java.util.concurrent.atomic.*;

/** Explicit synthetic metadata/reader fixture. Does not prove an upstream connection. */
public final class SourceConnectionSmoke {
 static int checks;static void check(boolean b){checks++;if(!b)throw new AssertionError("Connection "+checks);}
 static void fails(WorkflowFailure.Code code,Runnable work){checks++;try{work.run();}catch(WorkflowFailure f){if(f.code()==code)return;throw new AssertionError(f.code());}throw new AssertionError("Expected "+code);}
 static class Catalog implements SourceEndpointCatalog {SourceEndpoint endpoint=SourceEndpoint.registered("fixture-host","Fixture address","https://192.0.2.10/api_jsonrpc.php");TenantId tenant=new TenantId("connection-fixture");public List<SourceEndpoint> list(TenantId t){return t.equals(tenant)&&endpoint!=null?List.of(endpoint):List.of();}public Optional<SourceEndpoint> find(TenantId t,String id){return list(t).stream().filter(e->e.id().equals(id)).findFirst();}}
 static SourceConnectionService.Write command(UUID key,int edit,String name,SourceEndpoint e,SourceCredential.Pin c){return new SourceConnectionService.Write(key,edit,name,"Fixture description",e.pin(),c,List.of("7","2"));}
 public static void main(String[] args)throws Exception {
  var time=Clock.fixed(Instant.parse("2026-10-03T00:00:00Z"),ZoneOffset.UTC);var store=new InMemoryWorkflowStore();var cat=new Catalog();var principal=new Principal(new SubjectId("fixture-owner"),cat.tenant,Set.of(Permission.SOURCE_SYNC,Permission.SOURCE_CONFIGURE),ResourceScope.tenantWide());
  var credentials=new SourceCredentialService(store,new AesGcmCredentialProtector("fixture-key",Map.of("fixture-key",new byte[32])),time);var credentialId=UUID.randomUUID();SourceCredential credential;
  try(var w=new SourceCredentialService.Write(credentialId,0,"Fixture secret","ACTIVE","fixture-secret".toCharArray())){credential=credentials.write(principal,credentialId,w,true).credential();}
  var connections=new SourceConnectionService(store,new SourceEndpointService(cat),credentials,time);var id=UUID.randomUUID();var create=command(id,0,"Fixture connection",cat.endpoint,credential.pin());var first=connections.write(principal,id,create,true);
  check(first.receipt().instance().source().instanceId().equals("connection-"+id));check(first.connection().revision()==1);check(first.connection().hostGroupIds().equals(List.of("2","7")));check(first.connection().connectorVersion().equals(SourceConnectionConfiguration.VERSION));check(connections.read(principal,id).availability().equals("AVAILABLE"));check(connections.write(principal,id,create,true).equals(first));check(connections.history(principal,id).size()==1);
  fails(WorkflowFailure.Code.CONFLICT,()->connections.write(principal,id,new SourceConnectionService.Write(id,0,"Fixture connection","Fixture description",cat.endpoint.pin(),credential.pin(),List.of("8")),true));
  var scopeId=UUID.randomUUID();var scopeFirst=connections.write(principal,scopeId,new SourceConnectionService.Write(scopeId,0,"Scope fixture","",cat.endpoint.pin(),credential.pin(),List.of("2","7")),true);var scopeChanged=connections.write(principal,scopeId,new SourceConnectionService.Write(UUID.randomUUID(),1,"Scope fixture","",cat.endpoint.pin(),credential.pin(),List.of("8")),false);check(scopeChanged.connection().revision()==scopeFirst.connection().revision()+1);check(!scopeChanged.connection().connectionDigest().equals(scopeFirst.connection().connectionDigest()));check(scopeChanged.connection().hostGroupIds().equals(List.of("8")));
  var legacySnapshot=SourceConnectionConfiguration.snapshot(UUID.randomUUID(),1,cat.endpoint,credential.pin(),time.instant());check(legacySnapshot.connectorVersion().equals(SourceConnectionConfiguration.LEGACY_VERSION));check(!legacySnapshot.scoped());check(legacySnapshot.hostGroupIds().isEmpty());
  SourceSetupService.Connections resolver=new SourceSetupService.Connections(){public SourceSetupService.Connection resolve(Principal p,WorkflowDefinition.Source s){throw new AssertionError("No legacy resolution");}public SourceSetupService.Connection resolve(Principal p,SourceInstance i,WorkflowStore.Session s){return connections.resolve(p,i,s);}};
  var instances=new SourceInstanceService(store,resolver,time);var current=instances.read(principal,id);check(current.configurationRevision()==1);check(store.transaction(cat.tenant,s->s.setup(principal.subjectId().value(),id).orElseThrow().name()).equals("Fixture connection"));
  var metadata=instances.edit(principal,id,new SourceInstanceService.Edit(UUID.randomUUID(),1,"Fixture renamed","Fixture description",current.connectionDigest(),"ACTIVE"));check(metadata.instance().configurationRevision()==1);check(connections.history(principal,id).size()==1);check(connections.receipt(principal,id,id).equals(first));
  fails(WorkflowFailure.Code.NOT_FOUND,()->connections.receipt(principal,id,metadata.requestId()));
  fails(WorkflowFailure.Code.CONFLICT,()->connections.write(principal,id,command(UUID.randomUUID(),1,"Fixture stale",cat.endpoint,credential.pin()),false));
  var calls=new AtomicInteger();var inspections=new SourceInspectionService(store,resolver,(p,s,k)->{calls.incrementAndGet();return new SourceInspectionService.Result(new SourceInspection.Check(true,"READ_VERIFIED","7.0.0"),null);},time);
  var test=new SourceInspectionService.Command(UUID.randomUUID(),1,current.connectionDigest());check(inspections.run(principal,id,"TEST",test).validity().equals("CURRENT"));check(calls.get()==1);
  SourceCredential rotated;try(var w=new SourceCredentialService.Write(UUID.randomUUID(),1,"Fixture secret","ACTIVE","fixture-rotated".toCharArray())){rotated=credentials.write(principal,credentialId,w,false).credential();}
  check(connections.read(principal,id).availability().equals("AVAILABLE"));check(inspections.read(principal,id,test.requestId()).validity().equals("CURRENT"));
  var second=connections.write(principal,id,command(UUID.randomUUID(),2,"Fixture rotated connection",cat.endpoint,rotated.pin()),false);check(second.connection().revision()==2);check(connections.history(principal,id).size()==2);check(connections.receipt(principal,id,id).equals(first));check(inspections.read(principal,id,test.requestId()).validity().equals("STALE"));check(inspections.run(principal,id,"TEST",test).inspection().connectionDigest().equals(first.connection().connectionDigest()));check(calls.get()==1);
  fails(WorkflowFailure.Code.CONFLICT,()->instances.edit(principal,id,new SourceInstanceService.Edit(UUID.randomUUID(),3,"Fixture bad","",first.connection().connectionDigest(),"ACTIVE")));
  var oldEndpoint=cat.endpoint;cat.endpoint=SourceEndpoint.registered(oldEndpoint.id(),oldEndpoint.name(),"https://192.0.2.11/api_jsonrpc.php");check(connections.read(principal,id).availability().equals("UNAVAILABLE"));check(connections.receipt(principal,id,id).equals(first));check(connections.write(principal,id,create,true).equals(first));cat.endpoint=oldEndpoint;
  credentials.revoke(principal,credentialId,UUID.randomUUID(),2,1);check(connections.read(principal,id).availability().equals("AVAILABLE"));check(connections.receipt(principal,id,id).equals(first));
  var syncOnly=new Principal(principal.subjectId(),cat.tenant,Set.of(Permission.SOURCE_SYNC),ResourceScope.tenantWide());check(!connections.read(syncOnly,id).canConfigure());fails(WorkflowFailure.Code.FORBIDDEN,()->connections.write(syncOnly,id,command(UUID.randomUUID(),3,"Fixture denied",cat.endpoint,rotated.pin()),false));
  var scoped=new Principal(principal.subjectId(),cat.tenant,principal.permissions(),ResourceScope.of(Set.of(new ResourceRef(cat.tenant,"workflow","*"),ResourceRef.source(cat.tenant,current.source().instanceId()),new ResourceRef(cat.tenant,"credential",credentialId.toString()))));fails(WorkflowFailure.Code.FORBIDDEN,()->connections.read(scoped,id));
  var foreign=new Principal(principal.subjectId(),new TenantId("foreign-fixture"),principal.permissions(),ResourceScope.tenantWide());fails(WorkflowFailure.Code.NOT_FOUND,()->connections.read(foreign,id));
  var archived=instances.edit(principal,id,new SourceInstanceService.Edit(UUID.randomUUID(),3,"Fixture rotated connection","Fixture description",second.connection().connectionDigest(),"ARCHIVED"));check(connections.read(principal,id).availability().equals("ARCHIVED"));check(connections.receipt(principal,id,id).equals(first));fails(WorkflowFailure.Code.CONFLICT,()->connections.write(principal,id,command(UUID.randomUUID(),4,"Fixture archived",cat.endpoint,rotated.pin()),false));instances.edit(principal,id,new SourceInstanceService.Edit(UUID.randomUUID(),4,archived.instance().name(),archived.instance().description(),archived.instance().connectionDigest(),"ACTIVE"));
  var pool=Executors.newFixedThreadPool(2);try{var work=new Callable<Boolean>(){public Boolean call(){try{connections.write(principal,id,command(UUID.randomUUID(),5,"Fixture concurrent",cat.endpoint,rotated.pin()),false);return true;}catch(WorkflowFailure f){if(f.code()!=WorkflowFailure.Code.CONFLICT)throw f;return false;}}};check(pool.invokeAll(List.of(work,work)).stream().filter(f->{try{return f.get();}catch(Exception e){throw new RuntimeException(e);}}).count()==1);}finally{pool.shutdownNow();}
  var rollbackId=UUID.randomUUID();try{store.transaction(cat.tenant,s->{var c=SourceConnectionConfiguration.snapshot(rollbackId,1,cat.endpoint,rotated.pin(),List.of("2","7"),time.instant());s.addSourceConfiguration(principal.subjectId().value(),new SourceInstance.Configuration(rollbackId,1,c.connectionDigest(),"zabbix-jsonrpc",time.instant()));s.addSourceConnection(principal.subjectId().value(),c);throw new IllegalStateException("Fixture rollback");});throw new AssertionError();}catch(IllegalStateException expected){check(true);}check(store.transaction(cat.tenant,s->s.sourceConnections(principal.subjectId().value(),rollbackId).isEmpty()));check(store.transaction(cat.tenant,s->s.sourceConfigurations(principal.subjectId().value(),rollbackId).isEmpty()));
  // Binding a legacy creation preserves its physical source and immutable creation receipt.
  String legacyDigest="sha256:"+"a".repeat(64);var legacy=new SourceSetupService(store,(p,t)->{throw new AssertionError();},(p,s)->new SourceSetupService.Connection(legacyDigest,"fixture"),time).confirm(principal,new SourceSetupService.Command(UUID.randomUUID(),"Fixture legacy","",new WorkflowDefinition.Source("ZABBIX_HOST","fixture-legacy"),legacyDigest,null)).setup();var bound=connections.write(principal,legacy.id(),command(UUID.randomUUID(),1,"Fixture legacy bound",cat.endpoint,rotated.pin()),false);check(bound.connection().revision()==2);check(bound.receipt().instance().source().equals(legacy.source()));check(connections.configuration(principal,legacy.id(),1).isEmpty());check(instances.configurations(principal,legacy.id()).size()==2);check(store.transaction(cat.tenant,s->s.setup(principal.subjectId().value(),legacy.id()).orElseThrow()).equals(legacy));
  var beforeIo=instances.read(principal,id);var duringIo=new SourceInspectionService(store,resolver,(p,s,k)->{cat.endpoint=SourceEndpoint.registered(oldEndpoint.id(),oldEndpoint.name(),"https://192.0.2.11/api_jsonrpc.php");connections.write(p,id,command(UUID.randomUUID(),beforeIo.editVersion(),"Fixture changed during read",cat.endpoint,rotated.pin()),false);return new SourceInspectionService.Result(new SourceInspection.Check(true,"READ_VERIFIED","7.0.0"),null);},time);
  var interrupted=duringIo.run(principal,id,"TEST",new SourceInspectionService.Command(UUID.randomUUID(),beforeIo.configurationRevision(),beforeIo.connectionDigest()));check(interrupted.inspection().state().equals("UNKNOWN"));check(interrupted.inspection().check()==null);
  while(instances.read(principal,id).configurationRevision()<100){var i=instances.read(principal,id);String address=cat.endpoint.address().contains("192.0.2.10")?"https://192.0.2.11/api_jsonrpc.php":"https://192.0.2.10/api_jsonrpc.php";cat.endpoint=SourceEndpoint.registered(oldEndpoint.id(),oldEndpoint.name(),address);connections.write(principal,id,command(UUID.randomUUID(),i.editVersion(),"Fixture capacity",cat.endpoint,rotated.pin()),false);}
  var full=instances.read(principal,id);check(connections.history(principal,id).size()==100);cat.endpoint=SourceEndpoint.registered(oldEndpoint.id(),oldEndpoint.name(),"https://192.0.2.12/api_jsonrpc.php");fails(WorkflowFailure.Code.CAPACITY,()->connections.write(principal,id,command(UUID.randomUUID(),full.editVersion(),"Fixture over capacity",cat.endpoint,rotated.pin()),false));check(instances.read(principal,id).equals(full));
  // A legacy-looking instance without a fixed snapshot must use the instance-scoped
  // resolver for a digest change; the source-only resolver is intentionally unavailable.
  var controlledId=UUID.randomUUID();var controlledDigest="sha256:"+"c".repeat(64);
  var controlledSetup=new SourceSetupService(store,(p,target)->{throw new AssertionError();},(p,source)->new SourceSetupService.Connection(legacyDigest,"zabbix-jsonrpc"),time).confirm(principal,new SourceSetupService.Command(controlledId,"Controlled source","",new WorkflowDefinition.Source("ZABBIX_HOST","controlled-source"),legacyDigest,null)).setup();
  var controlledConnections=new SourceSetupService.Connections(){
    public SourceSetupService.Connection resolve(Principal p,WorkflowDefinition.Source source){throw new AssertionError("legacy source resolver used");}
    public SourceSetupService.Connection resolve(Principal p,SourceInstance instance,WorkflowStore.Session session){return new SourceSetupService.Connection(controlledDigest,"zabbix-jsonrpc",true);}
  };
  var controlledInstances=new SourceInstanceService(store,controlledConnections,time);
  var controlled=controlledInstances.edit(principal,controlledId,new SourceInstanceService.Edit(UUID.randomUUID(),1,"Controlled source","",controlledDigest,"ACTIVE"));
  check(controlled.instance().configurationRevision()==2&&controlled.instance().connectionDigest().equals(controlledDigest));
  System.out.println("Source connection smoke: "+checks+" checks passed");
 }
}
