import com.acme.opsweave.integration.application.*;
import com.acme.opsweave.integration.domain.*;
import com.acme.opsweave.integration.domain.WorkflowHostSchedule.*;
import com.acme.opsweave.identity.domain.*;
import java.util.*;

/** Explicit fixtures. Real time is replaced by an owned clock, never by an automatic source fallback. */
public final class WorkflowHostScheduleSmoke {
 static int checks;
 static void check(boolean v){checks++;if(!v)throw new AssertionError("Host schedule check "+checks);}
 static void rejects(Runnable run){checks++;try{run.run();}catch(WorkflowFailure|IllegalArgumentException expected){return;}throw new AssertionError("Expected rejection "+checks);}
 static Command command(WorkflowHostRuntimeSmoke.Fixture f,Operation operation,long generation){return new Command(UUID.randomUUID(),f.d.id(),1,f.d.digest(),f.settings,60,generation,operation);}
 static WorkflowHostScheduleService service(WorkflowHostRuntimeSmoke.Fixture f){return new WorkflowHostScheduleService(f.store,f.runtime,f.clock);}
 static Schedule schedule(WorkflowHostRuntimeSmoke.Fixture f,WorkflowHostScheduleService s){return s.status(f.p,f.d.id()).schedule();}
 public static void main(String[] args){
  var f=new WorkflowHostRuntimeSmoke.Fixture();var s=service(f);check(s.status(f.p,f.d.id()).schedule()==null);var c=command(f,Operation.START,0);var receipt=s.command(f.p,c,()->null);check(receipt.schedule().generation()==1&&f.reads==0);f.runtime.tick(f.p);f.runtime.tick(f.p);s.tick(f.p);var first=schedule(f,s);check(first.completedScans()==1&&first.confirmedRecords()==7&&first.sessionBatches()==2&&first.activeScanId()==null);var due=first.nextRunAt();check(due.equals(first.lastSuccessAt().plusSeconds(60)));check(s.command(f.p,c,()->{throw new AssertionError("No new authority on replay");}).equals(receipt));rejects(()->s.command(f.p,new Command(c.requestId(),c.id(),1,c.digest(),c.settings(),61,0,c.operation()),()->null));
  f.clock.instant=due.minusSeconds(1);s.tick(f.p);check(f.task().generation()==1&&f.reads==2);f.clock.instant=due;s.tick(f.p);check(f.task().generation()==2&&f.task().state().equals("RUNNING"));f.runtime.tick(f.p);f.runtime.tick(f.p);s.tick(f.p);check(schedule(f,s).completedScans()==2&&schedule(f,s).confirmedRecords()==14&&schedule(f,s).sessionBatches()==4);var stopped=s.command(f.p,command(f,Operation.STOP,1),()->{throw new AssertionError("No authority on stop");});check(stopped.schedule().state().equals("STOPPED")&&stopped.schedule().nextRunAt()==null);f.clock.instant=f.clock.instant.plusSeconds(500);s.tick(f.p);f.runtime.tick(f.p);check(f.reads==4&&f.writes==14);check(s.receipt(f.p,c.requestId()).equals(receipt));check(s.command(f.p,c,()->null).schedule().state().equals("RUNNING")&&schedule(f,s).state().equals("STOPPED"));
  var skip=new WorkflowHostRuntimeSmoke.Fixture();var ss=service(skip);ss.command(skip.p,command(skip,Operation.START,0),()->null);skip.runtime.tick(skip.p);skip.runtime.tick(skip.p);ss.tick(skip.p);skip.clock.instant=skip.clock.instant.plusSeconds(600);ss.tick(skip.p);ss.tick(skip.p);check(skip.task().generation()==2&&skip.reads==2);skip.runtime.tick(skip.p);skip.runtime.tick(skip.p);ss.tick(skip.p);check(schedule(skip,ss).nextRunAt().equals(skip.clock.instant.plusSeconds(60))&&schedule(skip,ss).completedScans()==2);
  var manual=new WorkflowHostRuntimeSmoke.Fixture();var ms=service(manual);ms.command(manual.p,command(manual,Operation.START,0),()->null);rejects(()->manual.command(WorkflowRuntimeControl.Operation.START,1));manual.command(WorkflowRuntimeControl.Operation.STOP,1);check(schedule(manual,ms).state().equals("STOPPED")&&schedule(manual,ms).taskGeneration()==2);manual.clock.instant=manual.clock.instant.plusSeconds(61);ms.tick(manual.p);check(manual.reads==0);ms.command(manual.p,command(manual,Operation.RESUME,2),()->null);manual.runtime.tick(manual.p);check(manual.reads==1&&manual.checkpoint().confirmedRecords()==5);
  var u=new WorkflowHostRuntimeSmoke.Fixture();var us=service(u);us.command(u.p,command(u,Operation.START,0),()->null);u.outage=true;u.runtime.tick(u.p);check(schedule(u,us).state().equals("FAILED")&&u.checkpoint().confirmedRecords()==0&&schedule(u,us).sessionBatches()==1);var original=u.runtime.hostBatches(u.p,u.d.id()).getFirst();u.clock.instant=u.clock.instant.plusSeconds(61);us.tick(u.p);u.runtime.tick(u.p);check(u.reads==1&&u.writes==2);rejects(()->us.command(u.p,command(u,Operation.START,1),()->null));u.outage=false;u.nextRows=WorkflowHostRuntimeSmoke.rows(30,5);us.command(u.p,command(u,Operation.RESUME,1),()->null);u.runtime.tick(u.p);check(u.reads==1&&u.checkpoint().confirmedRecords()==5);check(u.runtime.hostBatches(u.p,u.d.id()).getFirst().records().equals(original.records()));check(schedule(u,us).sessionBatches()==1);
  var race=new WorkflowHostRuntimeSmoke.Fixture();var rs=service(race);rs.command(race.p,command(race,Operation.START,0),()->null);race.onRead=()->rs.command(race.p,command(race,Operation.STOP,1),()->null);race.runtime.tick(race.p);check(race.writes==0&&race.reads==1&&schedule(race,rs).state().equals("STOPPED"));
  var limited=new WorkflowHostRuntimeSmoke.Fixture();limited.empty=true;var ls=service(limited);ls.command(limited.p,command(limited,Operation.START,0),()->null);for(int i=0;i<20;i++){limited.runtime.tick(limited.p);ls.tick(limited.p);limited.clock.instant=limited.clock.instant.plusSeconds(60);ls.tick(limited.p);}check(limited.reads==20&&limited.writes==0&&schedule(limited,ls).sessionBatches()==20&&schedule(limited,ls).completedScans()==20&&schedule(limited,ls).error().equals("EXECUTION_LIMIT"));ls.tick(limited.p);limited.runtime.tick(limited.p);check(limited.reads==20);
  var a=new WorkflowHostRuntimeSmoke.Fixture();a.empty=true;var as=service(a);var grant=new WorkflowTaskAuthority(UUID.randomUUID(),"https://issuer.example.invalid","fixture","sha256:"+"a".repeat(64),a.clock.instant,a.clock.instant.plusSeconds(125),20,0);as.command(a.p,command(a,Operation.START,0),()->grant);as.tick(a.p);a.runtime.tick(a.p);check(a.reads==0);a.runtime.tickAuthorized(a.p.tenantId(),a.p.subjectId().value(),t->a.p);as.tickAuthorized(a.p.tenantId(),a.p.subjectId().value(),t->a.p);a.clock.instant=a.clock.instant.plusSeconds(60);as.tickAuthorized(a.p.tenantId(),a.p.subjectId().value(),t->a.p);check(a.task().authority().id().equals(grant.id())&&a.task().authority().consumedBatches()==1);a.runtime.tickAuthorized(a.p.tenantId(),a.p.subjectId().value(),t->a.p);as.tickAuthorized(a.p.tenantId(),a.p.subjectId().value(),t->a.p);check(schedule(a,as).completedScans()==2&&a.task().authority().consumedBatches()==2);a.clock.instant=grant.expiresAt();as.tickAuthorized(a.p.tenantId(),a.p.subjectId().value(),t->a.p);check(schedule(a,as).error().equals("AUTHORIZATION_EXPIRED")&&a.reads==2);
  var revoked=new WorkflowHostRuntimeSmoke.Fixture();var vs=service(revoked);vs.command(revoked.p,command(revoked,Operation.START,0),()->null);vs.tickAuthorized(revoked.p.tenantId(),revoked.p.subjectId().value(),t->{throw new AssertionError("Dev tasks are isolated");});revoked.runtime.tick(revoked.p);revoked.runtime.tick(revoked.p);vs.tick(revoked.p);var denied=new Principal(revoked.p.subjectId(),revoked.p.tenantId(),Set.of(Permission.SOURCE_SYNC),ResourceScope.tenantWide());vs.tick(denied);check(revoked.store.transaction(revoked.p.tenantId(),session->session.hostSchedule(revoked.p.subjectId().value(),revoked.d.id()).orElseThrow().state()).equals("FAILED"));
  var other=new Principal(new SubjectId("other"),f.p.tenantId(),f.p.permissions(),ResourceScope.tenantWide());check(s.status(other,f.d.id()).schedule()==null);rejects(()->s.receipt(other,c.requestId()));rejects(()->new Command(UUID.randomUUID(),f.d.id(),1,f.d.digest(),f.settings,59,0,Operation.START));
  var expiry=new WorkflowHostRuntimeSmoke.Fixture();expiry.empty=true;var es=service(expiry);var shortGrant=new WorkflowTaskAuthority(UUID.randomUUID(),grant.issuer(),grant.externalSubject(),grant.grantDigest(),expiry.clock.instant,expiry.clock.instant.plusSeconds(3),20,0);es.command(expiry.p,command(expiry,Operation.START,0),()->shortGrant);expiry.runtime.tickAuthorized(expiry.p.tenantId(),expiry.p.subjectId().value(),t->expiry.p);check(schedule(expiry,es).completedScans()==1&&schedule(expiry,es).lastSuccessAt()!=null);expiry.clock.instant=shortGrant.expiresAt();es.tickAuthorized(expiry.p.tenantId(),expiry.p.subjectId().value(),t->{throw new WorkflowFailure(WorkflowFailure.Code.AUTHORIZATION_EXPIRED);});check(schedule(expiry,es).completedScans()==1&&schedule(expiry,es).error().equals("AUTHORIZATION_EXPIRED"));
  System.out.println("WorkflowHostScheduleSmoke: "+checks+" checks passed");
 }
}
