import com.acme.opsweave.identity.domain.*;
import com.acme.opsweave.integration.application.WorkflowQualityService;
import com.acme.opsweave.integration.domain.*;
import java.time.*;
import java.util.*;

/** Explicit journal fixtures; reading quality must not collect or write a second time. */
public final class WorkflowQualitySmoke {
    static int checks;static void check(boolean value){checks++;if(!value)throw new AssertionError("Quality "+checks);}
    static void fail(WorkflowFailure.Code code,Runnable action){checks++;try{action.run();}catch(WorkflowFailure f){if(f.code()==code)return;throw f;}throw new AssertionError("Expected "+code);}
    public static void main(String[] args)throws Exception{
        var a=new WorkflowLogStreamSmoke.Fixture();var q=new WorkflowQualityService(a.store,a.flows,a.clock);
        check(q.report(a.p,a.d.id(),1).batches().isEmpty());check(q.report(a.p,a.d.id(),1).task()==null);
        a.command(WorkflowLogStream.Operation.START,0);a.clock.advance(11);a.tick();var original=a.status().batches().getFirst();var report=q.report(a.p,a.d.id(),1);var c=report.batches().getFirst().counts();
        check(c.input()==2&&c.accepted()==2&&c.confirmed()==2&&c.outputExpected()==2);check(c.unknown()==0&&c.pending()==0&&c.repeatedOutput()==0&&c.late()==0);check(a.reads==1&&a.sink.writes==1&&a.sink.reads==1);check(report.task().state().equals("RUNNING"));check(report.batches().getFirst().sampleRate()==null);check(!report.toString().contains("Synthetic Fixture"));
        a.clock.advance(60);a.late=true;a.tick();var late=q.report(a.p,a.d.id(),1).batches().getFirst();check(late.reconcilesBatchId().equals(original.id()));check(late.counts().input()==3&&late.counts().deduplicated()==2&&late.counts().accepted()==1&&late.counts().confirmed()==1&&late.counts().late()==1);check(q.batch(a.p,a.d.id(),1,original.id()).counts().confirmed()==2);
        var u=new WorkflowLogStreamSmoke.Fixture();u.sink.unknown=true;u.command(WorkflowLogStream.Operation.START,0);u.clock.advance(11);u.tick();var uq=new WorkflowQualityService(u.store,u.flows,u.clock);var unknown=uq.report(u.p,u.d.id(),1).batches().getFirst();check(unknown.counts().unknown()==2&&unknown.counts().confirmed()==0&&unknown.counts().outputRejected()==0);check(u.reads==1&&u.sink.writes==1);var before=u.status();uq.batch(u.p,u.d.id(),1,unknown.id());check(before.equals(u.status()));
        var empty=new WorkflowLogStreamSmoke.Fixture();empty.empty=true;empty.command(WorkflowLogStream.Operation.START,0);empty.clock.advance(11);empty.tick();var ec=new WorkflowQualityService(empty.store,empty.flows,empty.clock).report(empty.p,empty.d.id(),1).batches().getFirst().counts();check(ec.input()==0&&ec.outputExpected()==0&&ec.confirmed()==0);
        var down=new WorkflowLogStreamSmoke.Fixture();down.unavailable=true;down.command(WorkflowLogStream.Operation.START,0);down.clock.advance(11);down.tick();var dr=new WorkflowQualityService(down.store,down.flows,down.clock).report(down.p,down.d.id(),1);check(dr.task().error().equals("SOURCE_UNAVAILABLE")&&dr.batches().isEmpty());check(down.reads==1&&down.sink.writes==0);
        var m=new WorkflowMetricStreamSmoke.Fixture();m.command(WorkflowMetricStream.Operation.START,0);m.time.advance(11);m.tick();m.time.advance(60);m.late=true;m.tick();var mq=new WorkflowQualityService(m.f.store,m.f.workflows,m.time);var mc=mq.report(m.f.p,m.f.d.id(),1).batches().getFirst().counts();check(mc.input()==3&&mc.confirmed()==3&&mc.late()==1&&mc.repeatedOutput()==2);check(m.status().task().confirmedPoints()==3);check(m.f.sink.writes==2&&m.reads==2);
        var entity=UUID.randomUUID().toString();var at=a.clock.instant();var host=new WorkflowHostScan.Batch(UUID.randomUUID(),UUID.randomUUID(),"host-fixture",1,"sha256:"+"b".repeat(64),new WorkflowRuntime.Settings("entity_id","name"),1,null,null,true,at,List.of(Map.of("name","Synthetic Fixture private","ip","127.0.0.1","lifecycle","ACTIVE","entity_id",entity)),"UNKNOWN",List.of(entity),"OUTPUT_UNAVAILABLE",at);var hc=WorkflowQuality.host(host).counts();check(hc.input()==1&&hc.confirmed()==1&&hc.accepted()==null&&hc.outputExpected()==null&&hc.unknown()==null);check(!WorkflowQuality.host(host).toString().contains(entity));
        var other=new Principal(new SubjectId("other"),a.p.tenantId(),a.p.permissions(),a.p.resourceScope());check(q.report(other,a.d.id(),1).batches().isEmpty());fail(WorkflowFailure.Code.NOT_FOUND,()->q.batch(other,a.d.id(),1,original.id()));
        var denied=new Principal(a.p.subjectId(),a.p.tenantId(),Set.of(Permission.SOURCE_SYNC),ResourceScope.tenantWide());fail(WorkflowFailure.Code.FORBIDDEN,()->q.report(denied,a.d.id(),1));fail(WorkflowFailure.Code.NOT_FOUND,()->q.report(a.p,a.d.id(),2));fail(WorkflowFailure.Code.NOT_FOUND,()->q.batch(a.p,a.d.id(),1,UUID.randomUUID()));
        a.store.transaction(a.p.tenantId(),s->{for(int i=0;i<21;i++){var time=a.clock.instant().plusNanos(i*1000L);var b=new WorkflowLogStream.Batch(UUID.randomUUID(),a.d.id(),1,a.d.digest(),original.from(),original.till(),time,time,"IN_FLIGHT",original.inputCount(),0,0,original.indices(),original.positions(),original.inputDigest(),original.batchDigest(),null,null);s.addLogStreamBatch(a.p.subjectId().value(),b);s.finishLogStreamBatch(a.p.subjectId().value(),b.finish("FAILED","OUTPUT_REJECTED",time));}return null;});a.clock.advance(1);var bounded=q.report(a.p,a.d.id(),1);check(bounded.truncated()&&bounded.batches().size()==20&&bounded.batches().stream().noneMatch(b->b.id().equals(original.id())));check(q.batch(a.p,a.d.id(),1,original.id()).counts().confirmed()==2);check(a.reads==2&&a.sink.writes==2);
        var rejected=original.finish("FAILED","OUTPUT_REJECTED",original.updatedAt());var legacy=WorkflowQuality.log(rejected,false);check(legacy.state().equals("UNKNOWN")&&legacy.error().equals("OUTPUT_UNCONFIRMED"));check(legacy.counts().unknown()==2&&legacy.counts().outputRejected()==0&&legacy.counts().confirmed()==0);check(legacy.id().equals(rejected.id())&&rejected.state().equals("FAILED"));var known=WorkflowQuality.log(rejected,true);check(known.state().equals("FAILED")&&known.counts().outputRejected()==2&&known.counts().unknown()==0);check(WorkflowQuality.log(original,false).state().equals("CONFIRMED"));
        System.out.println("WorkflowQualitySmoke: "+checks+" checks passed");
    }
}
