import com.acme.opsweave.identity.domain.*;
import com.acme.opsweave.integration.api.*;
import com.acme.opsweave.integration.application.*;
import com.acme.opsweave.integration.domain.*;
import com.acme.opsweave.integration.domain.WorkflowHistory.*;
import com.acme.opsweave.sharedkernel.TenantId;
import java.time.*;
import java.util.*;

/** Explicit in-memory selection and cursor fixtures; not a cryptography or durability test. */
public final class WorkflowHistorySmoke {
 static int checks;static void check(boolean v){checks++;if(!v)throw new AssertionError("History check "+checks);}
 static void fail(WorkflowFailure.Code code,Runnable r){checks++;try{r.run();}catch(WorkflowFailure e){if(e.code()==code)return;throw e;}throw new AssertionError("Expected "+code);}
 static void invalid(Runnable r){checks++;try{r.run();}catch(IllegalArgumentException e){return;}throw new AssertionError("Expected invalid history");}
 static final class SyntheticCursors implements WorkflowHistoryCursors {
  record Scope(TenantId tenant,String owner,WorkflowQuality.Reference reference,Cursor cursor){}
  final Map<String,Scope> values=new HashMap<>();boolean unavailable;
  public void requireAvailable(){if(unavailable)throw new IllegalStateException("Synthetic Fixture unavailable");}
  public String seal(TenantId t,String o,WorkflowQuality.Reference r,Cursor c){var token="h1.fixture"+values.size();values.put(token,new Scope(t,o,r,c));return token;}
  public Cursor open(TenantId t,String o,WorkflowQuality.Reference r,String token){var s=values.get(token);if(s==null||!s.tenant.equals(t)||!s.owner.equals(o)||!s.reference.equals(r))throw new WorkflowFailure(WorkflowFailure.Code.NOT_FOUND);return s.cursor;}
 }
 public static void main(String[] args){
  var f=new WorkflowLogStreamSmoke.Fixture();var ref=new WorkflowQuality.Reference(f.d.id(),1,f.d.digest());var cursors=new SyntheticCursors();var api=new WorkflowHistoryService(f.store,f.flows,cursors,f.clock);var at=f.clock.instant();var empty=api.history(f.p,ref.id(),1,null);check(empty.recordedCount()==0&&empty.items().isEmpty()&&!empty.hasMore()&&empty.nextCursor()==null);check(empty.coverage().equals("RECORDED_CHECKS"));
  var original=new ArrayList<WorkflowDiagnostics.Observation>();for(int i=0;i<45;i++)original.add(WorkflowQualityAlertsSmoke.observation(ref,at.minusSeconds(i),true,null));f.store.transaction(f.p.tenantId(),s->{original.forEach(o->s.addDiagnostic(f.p.subjectId().value(),new WorkflowDiagnostics.Stored(o,List.of())));return null;});
  var first=api.history(f.p,ref.id(),1,null);check(first.items().equals(original.subList(0,20))&&first.recordedCount()==45&&first.offset()==0&&first.hasMore());f.clock.advance(1);var backdated=WorkflowQualityAlertsSmoke.observation(ref,at.minusSeconds(25),true,null);f.store.transaction(f.p.tenantId(),s->{s.addDiagnostic(f.p.subjectId().value(),new WorkflowDiagnostics.Stored(backdated,List.of()));return null;});var next=api.history(f.p,ref.id(),1,first.nextCursor());check(next.items().equals(original.subList(20,40))&&next.offset()==20&&next.recordedCount()==45&&next.snapshotAt().equals(first.snapshotAt()));check(api.history(f.p,ref.id(),1,first.nextCursor()).items().equals(next.items()));var last=api.history(f.p,ref.id(),1,next.nextCursor());check(last.items().equals(original.subList(40,45))&&!last.hasMore()&&last.nextCursor()==null&&last.offset()==40);check(api.history(f.p,ref.id(),1,null).recordedCount()==46);check(f.reads==0&&f.sink.writes==0);
  var other=new Principal(new SubjectId("history-other"),f.p.tenantId(),f.p.permissions(),f.p.resourceScope());check(api.history(other,ref.id(),1,null).recordedCount()==0);fail(WorkflowFailure.Code.NOT_FOUND,()->api.history(other,ref.id(),1,first.nextCursor()));var denied=new Principal(f.p.subjectId(),f.p.tenantId(),Set.of(Permission.SOURCE_SYNC),f.p.resourceScope());fail(WorkflowFailure.Code.FORBIDDEN,()->api.history(denied,ref.id(),1,first.nextCursor()));var foreign=new Principal(f.p.subjectId(),new TenantId("history-foreign"),f.p.permissions(),f.p.resourceScope());fail(WorkflowFailure.Code.NOT_FOUND,()->api.history(foreign,ref.id(),1,null));fail(WorkflowFailure.Code.NOT_FOUND,()->api.history(f.p,ref.id(),2,null));fail(WorkflowFailure.Code.NOT_FOUND,()->api.history(f.p,ref.id(),1,"h1.unknown"));invalid(()->api.history(f.p,ref.id(),1,"h1.padded=="));
  fail(WorkflowFailure.Code.CONFLICT,()->new WorkflowHistoryService(f.store,f.flows,cursors,Clock.fixed(at.minusSeconds(1),ZoneOffset.UTC)).history(f.p,ref.id(),1,first.nextCursor()));f.clock.advance(599);fail(WorkflowFailure.Code.CONFLICT,()->api.history(f.p,ref.id(),1,first.nextCursor()));cursors.unavailable=true;checks++;try{api.history(f.p,ref.id(),1,null);throw new AssertionError();}catch(IllegalStateException expected){}cursors.unavailable=false;
  invalid(()->new Cursor("2.0",at,0,45,20,UUID.randomUUID()));invalid(()->new Cursor("2.0",at,45,45,21,UUID.randomUUID()));invalid(()->new Cursor("2.0",at,45,20,20,UUID.randomUUID()));invalid(()->new Page("2.0",at,at,ref,"ALL_RUNS",0,0,List.of(),null,false));invalid(()->new Page("2.0",at,at,ref,"RECORDED_CHECKS",20,20,List.of(),null,false));invalid(()->new Page("2.0",at,at,ref,"RECORDED_CHECKS",0,45,first.items(),null,true));var reversed=new ArrayList<>(first.items());Collections.reverse(reversed);invalid(()->new Page("2.0",at,at,ref,"RECORDED_CHECKS",0,45,reversed,"h1.fixture",true));
  var capacity=new WorkflowLogStreamSmoke.Fixture();var cr=new WorkflowQuality.Reference(capacity.d.id(),1,capacity.d.digest());var tied=new ArrayList<WorkflowDiagnostics.Observation>();for(int i=0;i<200;i++)tied.add(WorkflowQualityAlertsSmoke.observation(cr,capacity.clock.instant(),true,null));capacity.store.transaction(capacity.p.tenantId(),s->{tied.forEach(o->s.addDiagnostic(capacity.p.subjectId().value(),new WorkflowDiagnostics.Stored(o,List.of())));return null;});tied.sort(WorkflowHistory.ORDER);var bounded=new WorkflowHistoryService(capacity.store,capacity.flows,new SyntheticCursors(),capacity.clock);var all=new ArrayList<WorkflowDiagnostics.Observation>();String token=null;for(int i=0;i<10;i++){var p=bounded.history(capacity.p,cr.id(),1,token);check(p.offset()==i*20&&p.recordedCount()==200&&p.items().size()==20);all.addAll(p.items());token=p.nextCursor();}check(token==null&&all.equals(tied)&&all.stream().map(WorkflowDiagnostics.Observation::id).distinct().count()==200);checks++;try{capacity.store.transaction(capacity.p.tenantId(),s->{s.addDiagnostic(capacity.p.subjectId().value(),new WorkflowDiagnostics.Stored(WorkflowQualityAlertsSmoke.observation(cr,capacity.clock.instant(),true,null),List.of()));return null;});throw new AssertionError();}catch(IllegalStateException expected){}check(capacity.reads==0&&capacity.sink.writes==0);

  var host=new WorkflowHostRuntimeSmoke.Fixture();host.command(WorkflowRuntimeControl.Operation.START,0);host.runtime.tick(host.p);var witness=WorkflowHostDiagnosticsSmoke.rows(host).getFirst();var originalHost=witness.observation();host.store.transaction(host.p.tenantId(),s->{for(int i=0;i<20;i++){var o=new WorkflowDiagnostics.Observation(UUID.randomUUID(),originalHost.reference(),originalHost.kind(),originalHost.generation(),originalHost.state(),null,null,originalHost.startedAt(),originalHost.completedAt(),originalHost.queueWaitMillis(),originalHost.relatedBatchId(),originalHost.error(),originalHost.result(),originalHost.sourceRead(),originalHost.dispatch());s.addDiagnostic(host.p.subjectId().value(),new WorkflowDiagnostics.Stored(o,witness.entityIds()));}return null;});var guards=new WorkflowService.Sources(){public void require(Principal p,WorkflowDefinition.Source src,WorkflowStore.Session s,boolean available){check(!available);}};var flows=new WorkflowService(host.store,(p,t)->{throw new AssertionError("No model IO");},(p,src,id)->{throw new AssertionError("No source IO");},guards,host.clock);var history=new WorkflowHistoryService(host.store,flows,new SyntheticCursors(),host.clock);var hp=history.history(host.p,host.d.id(),1,null);check(hp.recordedCount()==21&&hp.items().size()==20);var scopes=new HashSet<ResourceRef>(Set.of(new ResourceRef(host.p.tenantId(),"workflow","*"),new ResourceRef(host.p.tenantId(),"catalog","*")));scopes.add(ResourceRef.entity(host.p.tenantId(),new com.acme.opsweave.sharedkernel.EntityId(UUID.fromString(witness.entityIds().getFirst()))));var restricted=new Principal(host.p.subjectId(),host.p.tenantId(),host.p.permissions(),ResourceScope.of(scopes));fail(WorkflowFailure.Code.FORBIDDEN,()->history.history(restricted,host.d.id(),1,hp.nextCursor()));fail(WorkflowFailure.Code.FORBIDDEN,()->history.history(restricted,host.d.id(),1,null));for(var id:witness.entityIds())scopes.add(ResourceRef.entity(host.p.tenantId(),new com.acme.opsweave.sharedkernel.EntityId(UUID.fromString(id))));var scoped=new Principal(host.p.subjectId(),host.p.tenantId(),host.p.permissions(),ResourceScope.of(scopes));check(history.history(scoped,host.d.id(),1,hp.nextCursor()).items().size()==1);check(host.reads==1&&host.writes==5&&WorkflowHostDiagnosticsSmoke.rows(host).size()==21);
  System.out.println("WorkflowHistorySmoke: "+checks+" checks passed");
 }
}
