import com.acme.opsweave.identity.domain.*;
import com.acme.opsweave.integration.application.*;
import com.acme.opsweave.integration.domain.*;
import com.acme.opsweave.integration.infrastructure.*;
import java.time.*;
import java.util.*;
import java.util.concurrent.*;
import java.util.concurrent.atomic.*;

/** Explicit in-memory metadata/body fixtures. External storage is verified separately. */
public final class WorkflowLogSourceSmoke {
 static int checks;static void check(boolean b){checks++;if(!b)throw new AssertionError("Log source "+checks);}
 static void fail(WorkflowFailure.Code c,Runnable work){checks++;try{work.run();}catch(WorkflowFailure e){if(e.code()==c)return;throw e;}throw new AssertionError("Expected "+c);}
 static void invalid(Runnable work){checks++;try{work.run();}catch(IllegalArgumentException e){return;}throw new AssertionError("Invalid pin accepted");}
 public static void main(String[] args){
  var clock=Clock.fixed(Instant.parse("2026-10-04T00:00:02Z"),ZoneOffset.UTC);var store=new InMemoryWorkflowStore();var catalog=new SourceConnectionSmoke.Catalog();
  var p=new Principal(new SubjectId("log-source-fixture"),catalog.tenant,Set.of(Permission.SOURCE_SYNC,Permission.SOURCE_CONFIGURE,Permission.ENTITY_READ,Permission.LOG_READ,Permission.LOG_WRITE),ResourceScope.tenantWide());
  var credentials=new SourceCredentialService(store,new AesGcmCredentialProtector("fixture-key",Map.of("fixture-key",new byte[32])),clock);var credentialId=UUID.randomUUID();SourceCredential credential;
  try(var w=new SourceCredentialService.Write(credentialId,0,"Fixture credential","ACTIVE","fixture-value".toCharArray())){credential=credentials.write(p,credentialId,w,true).credential();}
  var connections=new SourceConnectionService(store,new SourceEndpointService(catalog),credentials,clock);var id=UUID.randomUUID();var created=connections.write(p,id,SourceConnectionSmoke.command(id,0,"Fixture log connection",catalog.endpoint,credential.pin()),true);
  var host=new WorkflowDefinition.Source("ZABBIX_HOST",created.receipt().instance().source().instanceId(),new WorkflowDefinition.ConfigurationPin(id,1,created.connection().connectionDigest()));
  var item=new SourceMetricDiscovery.Item("50742","10683","log[/var/log/fixture.log]","Fixture log","","LOG","NO_MAPPING",null);
  var pending=SourceInspection.pending(id,UUID.randomUUID(),"DISCOVER_METRICS",created.receipt().instance(),clock.instant());var discovery=new SourceMetricDiscovery(List.of(item),true,"FIRST_PAGE_MATCH","READ_VERIFIED",SourceMetricDiscovery.digest(List.of(item)));var receipt=pending.complete(clock.instant(),null,null,discovery);
  store.transaction(p.tenantId(),s->{s.addSourceInspection(p.subjectId().value(),pending);s.finishSourceInspection(p.subjectId().value(),receipt);return null;});
  var logSources=new WorkflowLogSourceService(store,connections,clock);var page=logSources.list(p,host);check(page.items().size()==1&&!page.truncated());var source=page.items().getFirst().source();check(source.log().equals(WorkflowLogSourcePin.from(receipt.requestId(),item)));check(store.transaction(p.tenantId(),s->logSources.require(s,p,source,true)).equals(item));
  var noRead=new Principal(p.subjectId(),p.tenantId(),Set.of(Permission.SOURCE_SYNC,Permission.ENTITY_READ,Permission.LOG_WRITE),ResourceScope.tenantWide());check(logSources.list(noRead,host).items().isEmpty());fail(WorkflowFailure.Code.FORBIDDEN,()->store.transaction(p.tenantId(),s->logSources.require(s,noRead,source,true)));
  var noEntity=new Principal(p.subjectId(),p.tenantId(),Set.of(Permission.SOURCE_SYNC,Permission.LOG_READ),ResourceScope.tenantWide());check(logSources.list(noEntity,host).items().isEmpty());fail(WorkflowFailure.Code.FORBIDDEN,()->store.transaction(p.tenantId(),s->logSources.require(s,noEntity,source,true)));
  var other=new Principal(new SubjectId("other"),p.tenantId(),p.permissions(),ResourceScope.tenantWide());fail(WorkflowFailure.Code.NOT_FOUND,()->logSources.list(other,host));
  var expired=new WorkflowLogSourceService(store,connections,Clock.offset(clock,Duration.ofHours(1)));check(expired.list(p,host).items().isEmpty());check(store.transaction(p.tenantId(),s->expired.require(s,p,source,false)).equals(item));
  invalid(()->new WorkflowDefinition.Source("ZABBIX_LOG",source.instanceId(),source.configuration()));invalid(()->new WorkflowDefinition.Source("ZABBIX_HOST",source.instanceId(),source.configuration(),null,source.log()));invalid(()->new WorkflowLogSourcePin(receipt.requestId(),item.itemId(),item.hostId(),item.sourceKey(),item.sourceUnit(),"TEXT",source.log().digest()));
  var original=WorkflowOutputSmoke.definition("LOG");var nodes=original.nodes().stream().map(n->n.type()==WorkflowDefinition.Type.MAP?new WorkflowDefinition.Node(n.id(),n.type(),n.version(),Map.of("timestamp","eventTime","body","body"),n.operatorDigest()):n).toList();var d=new WorkflowDefinition("log-source-fixture",1,"Fixture log processing",source,original.target(),nodes,original.edges());
  invalid(()->new WorkflowDefinition(d.id(),1,d.name(),source,new WorkflowDefinition.Target(null,1,null,"METRIC"),nodes,original.edges()));check(!d.digest().equals(original.digest()));
  var secondItem=new SourceMetricDiscovery.Item("50743",item.hostId(),item.sourceKey(),item.name(),item.sourceUnit(),"LOG","NO_MAPPING",null);var secondSource=new WorkflowDefinition.Source("ZABBIX_LOG",source.instanceId(),source.configuration(),null,WorkflowLogSourcePin.from(receipt.requestId(),secondItem));var second=new WorkflowDefinition(d.id(),2,d.name(),secondSource,d.target(),d.nodes(),d.edges());check(!second.digest().equals(d.digest()));check(WorkflowComparison.compare(d,second).stream().anyMatch(c->c.key().equals("logItemId")));check(WorkflowComparison.compare(d,second).stream().anyMatch(c->c.key().equals("logSourceDigest")));
  var sources=new WorkflowService.Sources(){public void require(Principal who,WorkflowDefinition.Source src,com.acme.opsweave.integration.api.WorkflowStore.Session s,boolean available){connections.workflowConfiguration(s,who,src,available);}public void requireTarget(Principal who,WorkflowDefinition.Source src,WorkflowDefinition.Target t,com.acme.opsweave.integration.api.WorkflowStore.Session s,boolean available){logSources.requireTarget(s,who,src,t,available);}};
  var reads=new AtomicInteger();var blocked=new AtomicBoolean();var samples=List.of(Map.<String,Object>of("timestamp","2026-10-04T00:00:00Z","body","  Fixture <script>body</script>\n  "),Map.<String,Object>of("timestamp","2026-10-04T00:00:01Z","body","Fixture second"));
  var flows=new WorkflowService(store,(who,t)->{throw new AssertionError();},(who,src,batch)->{reads.incrementAndGet();if(blocked.get())throw new WorkflowFailure(WorkflowFailure.Code.SOURCE_UNAVAILABLE);return new WorkflowService.Batch(samples,"zabbix-jsonrpc",6,0,true,"SUCCEEDED");},sources,clock);
  flows.save(p,d,WorkflowSmoke.layout(d),0);check(reads.get()==0);var preview=flows.evaluate(p,d.id(),1,1,d.digest(),false,null,null);check(preview.receipt().accepted()==2&&preview.truncated());flows.publish(p,d.id(),1,1,d.digest(),preview.receipt().id());
  var sink=new WorkflowLogOutputSmoke.MemorySink();var output=new WorkflowLogOutputService(store,flows,sink,clock,new Semaphore(2));var command=new WorkflowLogOutput.SourceCommand(UUID.randomUUID(),d.id(),1,d.digest());var written=output.write(p,command);check(written.state().equals("CONFIRMED")&&written.confirmed()==2);check(reads.get()==2&&sink.writes==1);check(!written.toString().contains("<script>"));check(output.data(p,written.requestId()).records().getFirst().body().equals(samples.getFirst().get("body")));
  blocked.set(true);check(output.write(p,command).equals(written));check(reads.get()==2&&sink.writes==1);fail(WorkflowFailure.Code.CONFLICT,()->output.write(p,new WorkflowLogOutput.SourceCommand(command.requestId(),d.id(),2,d.digest())));fail(WorkflowFailure.Code.CONFLICT,()->output.write(p,new WorkflowLogOutput.Command(command.requestId(),d.id(),1,d.digest(),written.previewId(),samples)));check(sink.writes==1);
  var noWrite=new Principal(p.subjectId(),p.tenantId(),Set.of(Permission.SOURCE_SYNC,Permission.ENTITY_READ,Permission.LOG_READ),ResourceScope.tenantWide());fail(WorkflowFailure.Code.FORBIDDEN,()->output.write(noWrite,new WorkflowLogOutput.SourceCommand(UUID.randomUUID(),d.id(),1,d.digest())));check(reads.get()==2);fail(WorkflowFailure.Code.SOURCE_UNAVAILABLE,()->output.write(p,new WorkflowLogOutput.SourceCommand(UUID.randomUUID(),d.id(),1,d.digest())));check(sink.writes==1);
  blocked.set(false);sink.unknown=true;var unknownCommand=new WorkflowLogOutput.SourceCommand(UUID.randomUUID(),d.id(),1,d.digest());var unknown=output.write(p,unknownCommand);check(unknown.state().equals("UNKNOWN"));int readCount=reads.get();check(output.write(p,unknownCommand).state().equals("UNKNOWN"));check(output.confirm(p,unknown.requestId()).state().equals("UNKNOWN"));check(reads.get()==readCount&&sink.writes==2);sink.visible=sink.batch.records();check(output.confirm(p,unknown.requestId()).state().equals("CONFIRMED"));check(reads.get()==readCount&&sink.writes==2);
  System.out.println("WorkflowLogSourceSmoke: "+checks+" checks passed");
 }
}
