import com.acme.opsweave.integration.application.*;
import com.acme.opsweave.integration.domain.*;
import com.acme.opsweave.identity.domain.*;
import java.util.*;

/** Explicit in-memory fixtures; witness permissions and original-body recovery are exercised. */
public final class WorkflowHostDiagnosticsSmoke {
 static int checks;static void check(boolean v){checks++;if(!v)throw new AssertionError("Host diagnostics "+checks);}
 static void rejects(Runnable r){checks++;try{r.run();}catch(IllegalArgumentException|WorkflowFailure expected){return;}throw new AssertionError("Expected rejection");}
 static List<WorkflowDiagnostics.Stored> rows(WorkflowHostRuntimeSmoke.Fixture f){return f.store.transaction(f.p.tenantId(),s->s.diagnostics(f.p.subjectId().value(),f.d.id(),1,f.d.digest()));}
 static WorkflowDiagnosticService service(WorkflowHostRuntimeSmoke.Fixture f){var guards=new WorkflowService.Sources(){public void require(Principal p,WorkflowDefinition.Source src,com.acme.opsweave.integration.api.WorkflowStore.Session s,boolean available){if(available)throw new AssertionError("No source IO");}};var flows=new WorkflowService(f.store,(p,t)->{throw new AssertionError("No model evaluation");},(p,s,id)->{throw new AssertionError("No source samples");},guards,f.clock);return new WorkflowDiagnosticService(f.store,flows,f.clock);}
 static java.util.function.UnaryOperator<List<WorkflowDefinition.Node>> insert(WorkflowDefinition.Type type,Map<String,String> config){return nodes->{var copy=new ArrayList<>(nodes);copy.add(2,WorkflowSmoke.node("rule",type,config));return List.copyOf(copy);};}
 public static void main(String[] args){
  var f=new WorkflowHostRuntimeSmoke.Fixture();f.command(WorkflowRuntimeControl.Operation.START,0);f.runtime.tick(f.p);var observation=rows(f).getFirst();var o=observation.observation();check(o.kind()==WorkflowQuality.Kind.HOST_SCAN&&o.state().equals("CHECKED")&&o.from()==null&&o.till()==null);check(o.result().received()==5&&o.result().accepted()==5&&o.result().unknown()==0&&o.result().unitMismatch()==null);check(o.relatedBatchId().equals(f.runtime.hostBatches(f.p,f.d.id()).getFirst().id()));check(observation.entityIds().size()==5&&new HashSet<>(observation.entityIds()).equals(new HashSet<>(f.nextRows.stream().map(r->(String)r.get("entity_id")).toList())));check(o.result().nodes().stream().allMatch(n->n.received()==5));check(service(f).report(f.p,f.d.id(),1).observations().getFirst().equals(o));check(f.reads==1&&f.writes==5);
  var scopedRefs=new HashSet<ResourceRef>(Set.of(new ResourceRef(f.p.tenantId(),"workflow","*"),new ResourceRef(f.p.tenantId(),"catalog","*")));scopedRefs.add(ResourceRef.entity(f.p.tenantId(),new com.acme.opsweave.sharedkernel.EntityId(UUID.fromString(observation.entityIds().getFirst()))));var scoped=new Principal(f.p.subjectId(),f.p.tenantId(),f.p.permissions(),ResourceScope.of(scopedRefs));rejects(()->service(f).report(scoped,f.d.id(),1));rejects(()->service(f).observation(scoped,f.d.id(),1,o.id()));for(var id:observation.entityIds())scopedRefs.add(ResourceRef.entity(f.p.tenantId(),new com.acme.opsweave.sharedkernel.EntityId(UUID.fromString(id))));var allowed=new Principal(f.p.subjectId(),f.p.tenantId(),f.p.permissions(),ResourceScope.of(scopedRefs));check(service(f).observation(allowed,f.d.id(),1,o.id()).equals(o));rejects(()->new WorkflowDiagnostics.Stored(o,List.of()));
  var filtered=new WorkflowHostRuntimeSmoke.Fixture(insert(WorkflowDefinition.Type.FILTER,Map.of("field","name","equals","Fixture host 3")));filtered.command(WorkflowRuntimeControl.Operation.START,0);filtered.runtime.tick(filtered.p);var v=rows(filtered).getFirst();check(v.observation().result().accepted()==1&&v.observation().result().filtered()==4&&v.entityIds().size()==5&&filtered.writes==1);check(v.observation().result().nodes().getLast().skipped()==4);
  var invalid=new WorkflowHostRuntimeSmoke.Fixture(insert(WorkflowDefinition.Type.ENUM_MAP,Map.of("field","name","from","Fixture host 3","to"," ")));invalid.command(WorkflowRuntimeControl.Operation.START,0);invalid.runtime.tick(invalid.p);v=rows(invalid).getFirst();check(v.observation().state().equals("REJECTED")&&v.observation().result().received()==5&&v.observation().result().accepted()==4&&v.observation().result().rejected()==1&&v.observation().result().unknown()==0);check(v.observation().result().schemaMismatch()==1&&v.entityIds().size()==5);check(v.observation().relatedBatchId()==null&&invalid.writes==0&&invalid.runtime.hostBatches(invalid.p,invalid.d.id()).isEmpty()&&invalid.checkpoint().confirmedRecords()==0);
  var unavailable=new WorkflowHostRuntimeSmoke.Fixture();unavailable.onRead=()->{throw new WorkflowFailure(WorkflowFailure.Code.SOURCE_UNAVAILABLE);};unavailable.command(WorkflowRuntimeControl.Operation.START,0);unavailable.runtime.tick(unavailable.p);v=rows(unavailable).getFirst();check(v.observation().state().equals("SOURCE_FAILED")&&v.observation().result().received()==null&&v.entityIds().isEmpty()&&unavailable.writes==0);
  var zero=new WorkflowHostRuntimeSmoke.Fixture();zero.empty=true;zero.command(WorkflowRuntimeControl.Operation.START,0);zero.runtime.tick(zero.p);v=rows(zero).getFirst();check(v.observation().result().received()==0&&v.observation().result().accepted()==0&&v.entityIds().isEmpty()&&v.observation().relatedBatchId()!=null);
  var unknown=new WorkflowHostRuntimeSmoke.Fixture();unknown.outage=true;unknown.command(WorkflowRuntimeControl.Operation.START,0);unknown.runtime.tick(unknown.p);var original=rows(unknown).getFirst();check(original.observation().state().equals("CHECKED")&&unknown.task().state().equals("FAILED"));unknown.outage=false;unknown.command(WorkflowRuntimeControl.Operation.RESUME,1);unknown.runtime.tick(unknown.p);check(unknown.reads==1&&rows(unknown).equals(List.of(original))&&unknown.checkpoint().confirmedRecords()==5);
  var raced=new WorkflowHostRuntimeSmoke.Fixture();raced.command(WorkflowRuntimeControl.Operation.START,0);raced.onRead=()->raced.command(WorkflowRuntimeControl.Operation.STOP,1);raced.runtime.tick(raced.p);check(rows(raced).isEmpty()&&raced.writes==0&&raced.task().state().equals("STOPPED"));
  var full=new WorkflowHostRuntimeSmoke.Fixture();full.command(WorkflowRuntimeControl.Operation.START,0);full.store.transaction(full.p.tenantId(),s->{for(int i=0;i<200;i++){var record=new WorkflowDiagnostics.Observation(UUID.randomUUID(),new WorkflowQuality.Reference(full.d.id(),1,full.d.digest()),WorkflowQuality.Kind.HOST_SCAN,1,"SOURCE_FAILED",null,null,full.clock.instant,full.clock.instant,null,null,"SOURCE_UNAVAILABLE",WorkflowDiagnostics.Result.unavailable());s.addDiagnostic(full.p.subjectId().value(),new WorkflowDiagnostics.Stored(record,List.of()));}return null;});full.runtime.tick(full.p);check(full.reads==0&&full.writes==0&&full.task().error().equals("BACKLOG_LIMIT"));
  System.out.println("WorkflowHostDiagnosticsSmoke: "+checks+" checks passed");
 }
}
