import com.acme.opsweave.integration.application.*;
import com.acme.opsweave.integration.domain.*;
import com.acme.opsweave.integration.domain.WorkflowMetricStream.*;
import java.time.*;
import java.util.*;
import java.util.concurrent.Semaphore;

/** Explicit in-memory protocol fixture; verifies actual state transitions, no real source claim. */
public final class WorkflowMetricStreamSmoke {
    static int checks;
    static void check(boolean v){checks++;if(!v)throw new AssertionError("Stream check "+checks);}
    static void fail(WorkflowFailure.Code code,Runnable work){checks++;try{work.run();}catch(WorkflowFailure f){if(f.code()==code)return;throw f;}throw new AssertionError("Expected "+code);}
    static class Time extends Clock {Instant instant=Instant.parse("2026-10-04T00:00:02Z");public Instant instant(){return instant;}public ZoneId getZone(){return ZoneOffset.UTC;}public Clock withZone(ZoneId z){return this;}void advance(long seconds){instant=instant.plusSeconds(seconds);}}
    static class Fixture {
        final WorkflowMetricOutputSmoke.Fixture f;final Time time=new Time();final Semaphore budget=new Semaphore(2);final WorkflowMetricStreamService service;int reads;int points=2;boolean empty,unavailable,stopDuringRead,late,changed;
        Fixture()throws Exception{f=new WorkflowMetricOutputSmoke.Fixture();service=new WorkflowMetricStreamService(f.store,f.workflows,(p,s,from,till)->{reads++;if(stopDuringRead)command(Operation.STOP,1);if(unavailable)throw new WorkflowFailure(WorkflowFailure.Code.SOURCE_UNAVAILABLE);if(points!=2)return java.util.stream.IntStream.range(0,points).mapToObj(i->Map.<String,Object>of("timestamp",from.plusMillis(i*50L).toString(),"sourceKey",s.metric().sourceKey(),"value","12.5")).toList();if(empty)return List.of();var rows=new ArrayList<Map<String,Object>>(List.of(Map.of("timestamp",from.plusSeconds(1).toString(),"sourceKey",s.metric().sourceKey(),"value",changed?"13.5":"12.5"),Map.of("timestamp",from.plusSeconds(2).toString(),"sourceKey",s.metric().sourceKey(),"value","15")));if(late)rows.add(Map.of("timestamp",from.plusSeconds(3).toString(),"sourceKey",s.metric().sourceKey(),"value","20"));return List.copyOf(rows);},f.sink,budget,time);}
        Command commandBody(Operation op,long generation){return new Command(UUID.randomUUID(),f.d.id(),1,f.d.digest(),generation,op);}
        Receipt command(Operation op,long generation){return service.command(f.p,commandBody(op,generation),()->null);}
        WorkflowMetricStreamService.Status status(){return service.status(f.p,f.d.id());}
        void tick(){service.tick(f.p);}
    }
    public static void main(String[] args)throws Exception{
        var a=new Fixture();var start=a.commandBody(Operation.START,0);var receipt=a.service.command(a.f.p,start,()->null);a.tick();check(a.reads==0&&a.f.sink.writes==0);a.time.advance(11);a.tick();var status=a.status();check(status.task().confirmedWindows()==1&&status.task().confirmedPoints()==2&&status.task().pendingBatchId()==null);check(status.batches().getFirst().state().equals("CONFIRMED")&&a.f.sink.writes==1);check(a.f.sink.batch.samples().getFirst().value().toPlainString().equals("0.125"));check(a.f.sink.batch.labels().get("collection_mode").equals("WINDOW_60S"));a.tick();check(a.reads==1);a.time.advance(60);a.tick();check(a.status().task().confirmedWindows()==2);var stopped=a.command(Operation.STOP,1);a.time.advance(60);a.tick();check(a.reads==3&&a.status().task().state().equals("STOPPED"));check(a.service.command(a.f.p,start,()->{throw new AssertionError("Replay must not renew");}).equals(receipt));check(a.status().task().generation()==stopped.task().generation());fail(WorkflowFailure.Code.CONFLICT,()->a.service.command(a.f.p,new Command(start.requestId(),start.id(),1,start.digest(),0,Operation.RESUME),()->null));a.command(Operation.RESUME,2);a.tick();check(a.status().task().confirmedWindows()==3&&a.status().task().generation()==3);
        var b=new Fixture();b.command(Operation.START,0);b.time.advance(11);b.f.sink.unknown=true;b.tick();status=b.status();var unknown=status.batches().getFirst();check(unknown.state().equals("UNKNOWN")&&status.task().confirmedWindows()==0&&status.task().cursor().equals(unknown.from()));b.time.advance(60);b.tick();check(b.f.sink.writes==1&&b.reads==1);fail(WorkflowFailure.Code.CONFLICT,()->b.command(Operation.RESUME,1));b.service.verify(b.f.p,b.f.d.id(),unknown.id());check(b.status().task().confirmedWindows()==0&&b.f.sink.writes==1);b.f.sink.visible=b.f.sink.batch.samples();b.service.verify(b.f.p,b.f.d.id(),unknown.id());check(b.status().task().confirmedWindows()==1&&b.status().task().pendingBatchId()==null&&b.f.sink.writes==1);b.command(Operation.RESUME,1);b.f.sink.unknown=false;b.tick();check(b.status().task().confirmedWindows()==2);
        var c=new Fixture();c.empty=true;c.command(Operation.START,0);c.time.advance(11);c.tick();check(c.status().task().confirmedWindows()==1&&c.status().task().confirmedPoints()==0&&c.f.sink.writes==0);check(c.status().batches().getFirst().timestamps().isEmpty());
        var d=new Fixture();d.unavailable=true;d.command(Operation.START,0);d.time.advance(11);d.tick();check(d.status().task().state().equals("FAILED")&&d.status().task().confirmedWindows()==0&&d.status().batches().isEmpty());d.unavailable=false;d.command(Operation.RESUME,1);d.tick();check(d.status().task().confirmedWindows()==1);
        var e=new Fixture();e.f.sink.rejected=true;e.command(Operation.START,0);e.time.advance(11);e.tick();check(e.status().batches().getFirst().state().equals("FAILED")&&e.status().task().confirmedWindows()==0);e.command(Operation.RESUME,1);e.f.sink.rejected=false;e.tick();check(e.status().task().confirmedWindows()==1&&e.reads==2);
        var f=new Fixture();f.stopDuringRead=true;f.command(Operation.START,0);f.time.advance(11);f.tick();check(f.status().task().state().equals("STOPPED")&&f.status().batches().isEmpty()&&f.f.sink.writes==0);
        var g=new Fixture();g.command(Operation.START,0);g.time.advance(11);g.f.revokeAt=1;g.tick();g.f.revokeAt=Integer.MAX_VALUE;check(g.status().task().error().equals("FORBIDDEN")&&g.f.sink.writes==0);g.budget.acquire(2);g.command(Operation.RESUME,1);g.tick();check(g.reads==0);g.budget.release(2);
        var h=new Fixture();h.empty=true;h.command(Operation.START,0);h.time.advance(11);for(int i=0;i<21;i++){h.tick();h.time.advance(60);}check(h.status().task().confirmedWindows()==20&&h.status().task().error().equals("EXECUTION_LIMIT"));
        var full=new Fixture();full.points=600;full.command(Operation.START,0);full.time.advance(11);full.tick();check(full.status().task().confirmedPoints()==600&&full.f.sink.batch.samples().size()==600);check(full.f.sink.batch.samples().stream().allMatch(point->point.value().toPlainString().equals("0.125")));var overflow=new Fixture();overflow.points=601;overflow.command(Operation.START,0);overflow.time.advance(11);overflow.tick();check(overflow.status().task().error().equals("INVALID_SAMPLE")&&overflow.status().batches().isEmpty()&&overflow.f.sink.writes==0);
        var auth=new Fixture();var issued=auth.time.instant();var authority=new WorkflowTaskAuthority(UUID.randomUUID(),"https://fixture.invalid","fixture-subject","sha256:"+"a".repeat(64),issued,issued.plusSeconds(30),1,0);auth.service.command(auth.f.p,auth.commandBody(Operation.START,0),()->authority);auth.time.advance(11);auth.service.tick(auth.f.p);check(auth.reads==0);auth.service.tickAuthorized(auth.f.p.tenantId(),auth.f.p.subjectId().value(),task->auth.f.p);check(auth.status().task().authority().consumedBatches()==1&&auth.status().task().confirmedWindows()==1);auth.service.tickAuthorized(auth.f.p.tenantId(),auth.f.p.subjectId().value(),task->auth.f.p);check(auth.status().task().error().equals("EXECUTION_LIMIT"));
        var expiry=new Fixture();issued=expiry.time.instant();var shortAuthority=new WorkflowTaskAuthority(UUID.randomUUID(),"https://fixture.invalid","fixture-subject","sha256:"+"a".repeat(64),issued,issued.plusSeconds(5),20,0);expiry.service.command(expiry.f.p,expiry.commandBody(Operation.START,0),()->shortAuthority);expiry.time.advance(11);expiry.service.tickAuthorized(expiry.f.p.tenantId(),expiry.f.p.subjectId().value(),task->expiry.f.p);check(expiry.status().task().error().equals("AUTHORIZATION_EXPIRED")&&expiry.reads==0);
        var revoked=new Fixture();revoked.service.command(revoked.f.p,revoked.commandBody(Operation.START,0),()->authority);revoked.time.advance(11);revoked.service.tickAuthorized(revoked.f.p.tenantId(),revoked.f.p.subjectId().value(),task->null);check(revoked.status().task().error().equals("AUTHORIZATION_REVOKED")&&revoked.reads==0);
        check(!unknown.toString().contains("12.5")&&!unknown.toString().contains("0.125"));
        var late=new Fixture();late.command(Operation.START,0);late.time.advance(11);late.tick();var original=late.status().batches().getFirst();var cursor=late.status().task().cursor();late.time.advance(60);late.late=true;late.tick();var correction=late.status().batches().getFirst();check(correction.reconcilesBatchId().equals(original.id())&&correction.latePoints()==1);check(late.status().task().cursor().equals(cursor)&&late.status().task().confirmedWindows()==1&&late.status().task().confirmedPoints()==3&&late.status().task().sessionBatches()==2);check(late.status().batches().contains(original));late.time.advance(1);late.tick();check(late.status().task().confirmedWindows()==2&&late.status().task().confirmedPoints()==6&&late.status().task().sessionBatches()==3);check(late.f.sink.writes==3);
        var revised=new Fixture();revised.command(Operation.START,0);revised.time.advance(11);revised.tick();revised.time.advance(60);revised.changed=true;revised.tick();check(revised.status().task().error().equals("SOURCE_WINDOW_CHANGED")&&revised.f.sink.writes==1&&revised.status().batches().size()==1);var missing=new Fixture();missing.command(Operation.START,0);missing.time.advance(11);missing.tick();missing.time.advance(60);missing.empty=true;missing.tick();check(missing.status().task().error().equals("SOURCE_WINDOW_CHANGED")&&missing.f.sink.writes==1);
        var lateUnknown=new Fixture();lateUnknown.command(Operation.START,0);lateUnknown.time.advance(11);lateUnknown.tick();cursor=lateUnknown.status().task().cursor();lateUnknown.time.advance(60);lateUnknown.late=true;lateUnknown.f.sink.unknown=true;lateUnknown.tick();var pending=lateUnknown.status().task().pendingBatchId();check(lateUnknown.status().task().confirmedPoints()==2&&lateUnknown.status().task().cursor().equals(cursor));lateUnknown.time.advance(60);lateUnknown.tick();check(lateUnknown.f.sink.writes==2);lateUnknown.f.sink.visible=lateUnknown.f.sink.batch.samples();lateUnknown.service.verify(lateUnknown.f.p,lateUnknown.f.d.id(),pending);check(lateUnknown.status().task().state().equals("STOPPED")&&lateUnknown.status().task().cursor().equals(cursor)&&lateUnknown.status().task().confirmedPoints()==3&&lateUnknown.status().task().confirmedWindows()==1);check(lateUnknown.f.sink.writes==2);
        System.out.println("Workflow metric stream smoke: "+checks+" checks passed");
    }
}
