import com.acme.opsweave.identity.domain.*;
import com.acme.opsweave.integration.application.*;
import com.acme.opsweave.integration.domain.*;
import com.acme.opsweave.integration.domain.WorkflowLogOutput.*;
import com.acme.opsweave.integration.domain.WorkflowLogOutput.Record;
import com.acme.opsweave.integration.infrastructure.InMemoryWorkflowStore;
import com.acme.opsweave.sharedkernel.TenantId;
import java.time.*;
import java.util.*;
import java.util.concurrent.Semaphore;

/** Explicit in-memory protocol fixture; it proves admission rules, not external durability. */
public final class WorkflowLogOutputSmoke{
 static int checks;static void check(boolean ok){checks++;if(!ok)throw new AssertionError("Log output "+checks);}
 static void fail(WorkflowFailure.Code code,Runnable work){checks++;try{work.run();}catch(WorkflowFailure e){if(e.code()==code)return;throw e;}throw new AssertionError("Expected "+code);}
 static final class MemorySink implements WorkflowLogOutputService.Sink{Batch batch;List<Record> visible=List.of();int writes,reads;boolean unknown,rejected,unavailable,readDown;public boolean ready(){return !unavailable;}public void write(Batch batch){writes++;this.batch=batch;if(rejected)throw new WorkflowLogOutputService.OutputFailure(false);visible=unknown?batch.records().subList(0,1):batch.records();if(unknown)throw new WorkflowLogOutputService.OutputFailure(true);}public List<Record> read(Scope scope){reads++;if(unavailable||readDown)throw new WorkflowLogOutputService.OutputFailure(false);return visible;}}
 static final class Fixture{
  final Clock clock=Clock.fixed(Instant.parse("2026-10-04T00:00:02Z"),ZoneOffset.UTC);final InMemoryWorkflowStore store=new InMemoryWorkflowStore();final MemorySink sink=new MemorySink();final Semaphore budget=new Semaphore(2);
  final Principal p=new Principal(new SubjectId("logs-fixture"),new TenantId("logs-fixture"),Set.of(Permission.SOURCE_SYNC,Permission.LOG_READ,Permission.LOG_WRITE),ResourceScope.tenantWide());final WorkflowDefinition d=WorkflowOutputSmoke.definition("LOG");final WorkflowService flows;final Command command;int guards;int revokeAt=Integer.MAX_VALUE;
  Fixture(){flows=new WorkflowService(store,(who,target)->{throw new AssertionError();},(who,source,id)->{throw new AssertionError();},(who,source,s,available)->{if(available&&++guards>=revokeAt)throw new WorkflowFailure(WorkflowFailure.Code.FORBIDDEN);},clock);flows.save(p,d,WorkflowSmoke.layout(d),0);var samples=List.of(Map.<String,Object>of("eventTime","2026-10-04T00:00:00Z","body","  Fixture untrusted <script>body</script>  ","severityText","INFO"),Map.<String,Object>of("eventTime","2026-10-04T00:00:01Z","body","Fixture second\nline"));var preview=flows.evaluate(p,d.id(),1,1,d.digest(),false,samples,null);flows.publish(p,d.id(),1,1,d.digest(),preview.receipt().id());var run=flows.evaluate(p,d.id(),1,0,d.digest(),true,samples,null);command=new Command(UUID.randomUUID(),d.id(),1,d.digest(),run.receipt().id(),samples);guards=0;}
  WorkflowLogOutputService service(){return new WorkflowLogOutputService(store,flows,sink,clock,budget);}
 }
 public static void main(String[] args){
  var f=new Fixture();var s=f.service();var r=s.write(f.p,f.command);check(r.state().equals("CONFIRMED")&&r.confirmed()==2);check(r.indices().equals(List.of(0,1)));check(f.sink.writes==1);check(f.sink.batch.records().getFirst().body().startsWith("  "));check(!r.toString().contains("untrusted"));check(r.equals(s.write(f.p,f.command)));check(f.sink.writes==1);check(s.data(f.p,r.requestId()).complete());check(s.data(f.p,r.requestId()).records().get(1).body().endsWith("\nline"));check(s.records(f.p,f.d.id()).items().equals(List.of(r)));
  var changed=new Command(r.requestId(),f.d.id(),1,f.d.digest(),f.command.previewId(),List.of(Map.of("eventTime","2026-10-04T00:00:00Z","body","changed")));fail(WorkflowFailure.Code.CONFLICT,()->s.write(f.p,changed));check(f.sink.writes==1);
  var other=new Principal(new SubjectId("other"),f.p.tenantId(),f.p.permissions(),ResourceScope.tenantWide());fail(WorkflowFailure.Code.NOT_FOUND,()->s.read(other,r.requestId()));check(s.records(other,f.d.id()).items().isEmpty());var tenant=new Principal(f.p.subjectId(),new TenantId("other-log"),f.p.permissions(),ResourceScope.tenantWide());fail(WorkflowFailure.Code.NOT_FOUND,()->s.read(tenant,r.requestId()));
  var metadataOnly=new Principal(f.p.subjectId(),f.p.tenantId(),Set.of(Permission.SOURCE_SYNC),ResourceScope.tenantWide());check(s.read(metadataOnly,r.requestId()).equals(r));fail(WorkflowFailure.Code.FORBIDDEN,()->s.data(metadataOnly,r.requestId()));fail(WorkflowFailure.Code.FORBIDDEN,()->s.confirm(metadataOnly,r.requestId()));check(s.write(metadataOnly,f.command).equals(r));fail(WorkflowFailure.Code.FORBIDDEN,()->s.write(metadataOnly,new Command(UUID.randomUUID(),f.d.id(),1,f.d.digest(),f.command.previewId(),f.command.samples())));
  var limited=new Principal(f.p.subjectId(),f.p.tenantId(),f.p.permissions(),ResourceScope.of(Set.of(new ResourceRef(f.p.tenantId(),"workflow","*"),new ResourceRef(f.p.tenantId(),"log","workflow.other-log"))));var reads=f.sink.reads;fail(WorkflowFailure.Code.FORBIDDEN,()->s.data(limited,r.requestId()));fail(WorkflowFailure.Code.FORBIDDEN,()->s.confirm(limited,r.requestId()));fail(WorkflowFailure.Code.FORBIDDEN,()->s.write(limited,new Command(UUID.randomUUID(),f.d.id(),1,f.d.digest(),f.command.previewId(),f.command.samples())));check(f.sink.reads==reads);check(f.sink.writes==1);
  var expired=new WorkflowLogOutputService(f.store,f.flows,f.sink,Clock.offset(f.clock,Duration.ofSeconds(901)),f.budget);fail(WorkflowFailure.Code.PREVIEW_REQUIRED,()->expired.write(f.p,new Command(UUID.randomUUID(),f.d.id(),1,f.d.digest(),f.command.previewId(),f.command.samples())));check(f.sink.writes==1);
  var partial=new Fixture();partial.sink.unknown=true;var u=partial.service().write(partial.p,partial.command);check(u.state().equals("UNKNOWN")&&u.unknown()==2);check(!partial.service().data(partial.p,u.requestId()).complete());check(partial.service().confirm(partial.p,u.requestId()).state().equals("UNKNOWN"));check(partial.service().write(partial.p,partial.command).state().equals("UNKNOWN"));check(partial.sink.writes==1);partial.sink.visible=partial.sink.batch.records();check(partial.service().confirm(partial.p,u.requestId()).state().equals("CONFIRMED"));check(partial.sink.writes==1);
  var readDown=new Fixture();readDown.sink.readDown=true;var unread=readDown.service().write(readDown.p,readDown.command);check(unread.state().equals("UNKNOWN"));check(unread.unknown()==2);check(readDown.sink.writes==1);check(readDown.service().confirm(readDown.p,unread.requestId()).state().equals("UNKNOWN"));readDown.sink.readDown=false;check(readDown.service().confirm(readDown.p,unread.requestId()).state().equals("CONFIRMED"));check(readDown.sink.writes==1);
  var rejected=new Fixture();rejected.sink.rejected=true;check(rejected.service().write(rejected.p,rejected.command).state().equals("FAILED"));var revoked=new Fixture();revoked.revokeAt=2;check(revoked.service().write(revoked.p,revoked.command).error().equals("FORBIDDEN"));check(revoked.sink.writes==0);
  var down=new Fixture();var known=down.service().write(down.p,down.command);down.sink.unavailable=true;check(!down.service().available());fail(WorkflowFailure.Code.SOURCE_UNAVAILABLE,()->down.service().data(down.p,known.requestId()));check(down.sink.writes==1);
  f.budget.acquireUninterruptibly(2);fail(WorkflowFailure.Code.BUSY,()->s.data(f.p,r.requestId()));f.budget.release(2);
  check(WorkflowLogOutput.numberText(new java.math.BigDecimal("1.0E-7")).equals("0.0000001"));check(WorkflowLogOutput.numberText(new java.math.BigDecimal("0.00000010")).equals("0.0000001"));check(WorkflowLogOutput.numberText(-0.0).equals("0"));
  for(var time:List.of("2026-10-02T00:00:00Z","2026-10-04T00:00:03Z")){var edge=new Fixture();var samples=List.of(Map.<String,Object>of("eventTime",time,"body","Fixture"));var run=edge.flows.evaluate(edge.p,edge.d.id(),1,0,edge.d.digest(),true,samples,null);fail(WorkflowFailure.Code.INVALID_SAMPLE,()->edge.service().write(edge.p,new Command(UUID.randomUUID(),edge.d.id(),1,edge.d.digest(),run.receipt().id(),samples)));check(edge.sink.writes==0);}
  System.out.println("WorkflowLogOutputSmoke: "+checks+" checks passed");
 }
}
