import com.acme.opsweave.identity.domain.*;
import com.acme.opsweave.integration.application.*;
import com.acme.opsweave.integration.domain.*;
import com.acme.opsweave.integration.domain.WorkflowLogStream.*;
import com.acme.opsweave.integration.infrastructure.InMemoryWorkflowStore;
import com.acme.opsweave.integration.api.*;
import com.acme.opsweave.sharedkernel.TenantId;
import java.time.*;
import java.util.*;
import java.util.concurrent.Semaphore;

/** Explicit domain fixtures, with no assertion of external durability. */
public final class WorkflowLogStreamSmoke {
    static int checks;static void check(boolean v){checks++;if(!v)throw new AssertionError("Log stream "+checks);}
    static void fail(WorkflowFailure.Code c,Runnable r){checks++;try{r.run();}catch(WorkflowFailure e){if(e.code()==c)return;throw e;}throw new AssertionError("Expected "+c);}
    static final class Time extends Clock {Instant value=Instant.parse("2026-10-04T00:00:02Z");public Instant instant(){return value;}public ZoneId getZone(){return ZoneOffset.UTC;}public Clock withZone(ZoneId zone){return this;}void advance(long seconds){value=value.plusSeconds(seconds);}}
    static final class Sink implements WorkflowLogWindowSink {
        int writes,reads;boolean unknown,rejected,readDown;WorkflowLogWindow.Batch batch;final Map<UUID,List<WorkflowLogWindow.Record>> visible=new HashMap<>();
        public boolean ready(){return true;}public void write(WorkflowLogWindow.Batch b){writes++;batch=b;if(rejected)throw new WorkflowLogOutputService.OutputFailure(false);visible.put(b.scope().requestId(),unknown?b.records().subList(0,Math.max(0,b.records().size()-1)):b.records());if(unknown)throw new WorkflowLogOutputService.OutputFailure(true);}
        public List<WorkflowLogWindow.Record> read(WorkflowLogOutput.Scope scope){reads++;if(readDown)throw new WorkflowLogOutputService.OutputFailure(false);return visible.getOrDefault(scope.requestId(),List.of());}
    }
    static final class Fixture {
        final Time clock=new Time();final InMemoryWorkflowStore store=new InMemoryWorkflowStore();final Sink sink=new Sink();final Semaphore budget=new Semaphore(2);final WorkflowDefinition d;
        final Principal p=new Principal(new SubjectId("log-stream-fixture"),new TenantId("log-stream-fixture"),Set.of(Permission.SOURCE_SYNC,Permission.ENTITY_READ,Permission.LOG_READ,Permission.LOG_WRITE),ResourceScope.tenantWide());
        final WorkflowService flows;final WorkflowLogStreamService service;int reads,count=2,guards;boolean empty,late,changed,unavailable,stopDuringRead,revoked;
        Fixture(){this(false);}
        Fixture(boolean filter){
            d=WorkflowLogWindowSmoke.definition(filter);
            var sources=new WorkflowService.Sources(){public void require(Principal who,WorkflowDefinition.Source source,WorkflowStore.Session s,boolean available){if(available){guards++;if(revoked)throw new WorkflowFailure(WorkflowFailure.Code.FORBIDDEN);}}public void requireTarget(Principal who,WorkflowDefinition.Source source,WorkflowDefinition.Target target,WorkflowStore.Session s,boolean available){require(who,source,s,available);}};
            flows=new WorkflowService(store,(who,target)->{throw new AssertionError();},(who,source,id)->new WorkflowService.Batch(rows(clock.instant().minusSeconds(2)),"zabbix-jsonrpc",2,0,false,"SUCCEEDED"),sources,clock);
            flows.save(p,d,WorkflowSmoke.layout(d),0);var preview=flows.evaluate(p,d.id(),1,1,d.digest(),false,null,null);flows.publish(p,d.id(),1,1,d.digest(),preview.receipt().id());
            service=new WorkflowLogStreamService(store,flows,(who,source,from,till)->{reads++;if(stopDuringRead)command(Operation.STOP,1);if(unavailable)throw new WorkflowFailure(WorkflowFailure.Code.SOURCE_UNAVAILABLE);return rows(from);},sink,budget,clock);
        }
        List<Map<String,Object>> rows(Instant from){if(empty)return List.of();var result=new ArrayList<Map<String,Object>>();if(late)result.add(row(from,1,"Synthetic Fixture late"));for(int i=0;i<count;i++)result.add(row(from,2L+i*2,changed?"Synthetic Fixture changed":"  Synthetic Fixture "+i+"\n<script>  "));return List.copyOf(result);}
        Map<String,Object> row(Instant from,long ns,String body){var row=new LinkedHashMap<String,Object>();row.put("timestamp",from.plusNanos(ns).toString());row.put("body",body);row.put("sourceKey",d.source().log().sourceKey());row.put("logEventTime",null);row.put("severityCode",body.contains("late")?"0":"1");row.put("eventSource",null);row.put("eventId","0");return row;}
        Command body(Operation op,long generation){return new Command(UUID.randomUUID(),d.id(),1,d.digest(),generation,op);}
        Receipt command(Operation op,long generation){return service.command(p,body(op,generation),()->null);}WorkflowLogStreamService.Status status(){return service.status(p,d.id());}void tick(){service.tick(p);}
    }
    public static void main(String[] args){
        var a=new Fixture();var start=a.body(Operation.START,0);var accepted=a.service.command(a.p,start,()->null);a.tick();check(a.reads==0);a.clock.advance(11);a.tick();var status=a.status();check(status.task().confirmedWindows()==1&&status.task().confirmedRecords()==2&&status.task().pendingBatchId()==null);check(a.sink.writes==1&&status.batches().getFirst().state().equals("CONFIRMED"));check(!status.batches().getFirst().toString().contains("Synthetic Fixture"));check(a.service.command(a.p,start,()->{throw new AssertionError("No renewal");}).equals(accepted));a.command(Operation.STOP,1);a.clock.advance(60);a.tick();check(a.sink.writes==1);a.command(Operation.RESUME,2);a.tick();check(a.status().task().confirmedWindows()==2);fail(WorkflowFailure.Code.CONFLICT,()->a.service.command(a.p,new Command(start.requestId(),start.id(),1,start.digest(),0,Operation.RESUME),()->null));
        var full=new Fixture();full.count=1000;full.command(Operation.START,0);full.clock.advance(11);full.tick();check(full.status().task().confirmedRecords()==1000&&full.sink.writes==1&&full.sink.batch.records().getLast().index()==999);
        var fullId=full.status().batches().getFirst().id();var firstPage=full.service.data(full.p,full.d.id(),fullId);check(firstPage.complete()&&firstPage.records().size()==50&&firstPage.nextIndex()==49);var secondPage=full.service.data(full.p,full.d.id(),fullId,49);check(secondPage.complete()&&secondPage.records().getFirst().index()==50&&secondPage.nextIndex()==99);
        var empty=new Fixture();empty.empty=true;empty.command(Operation.START,0);empty.clock.advance(11);empty.tick();check(empty.status().task().confirmedWindows()==1&&empty.sink.writes==0);
        var u=new Fixture();u.command(Operation.START,0);u.clock.advance(11);u.sink.unknown=true;u.tick();var original=u.status().batches().getFirst();check(original.state().equals("UNKNOWN")&&u.status().task().cursor().equals(original.from()));u.clock.advance(60);u.tick();check(u.reads==1&&u.sink.writes==1);fail(WorkflowFailure.Code.CONFLICT,()->u.command(Operation.RESUME,1));u.service.verify(u.p,u.d.id(),original.id());check(u.status().task().confirmedWindows()==0);u.sink.visible.put(original.id(),u.sink.batch.records());u.service.verify(u.p,u.d.id(),original.id());check(u.status().task().state().equals("STOPPED")&&u.status().task().confirmedRecords()==2&&u.sink.writes==1);check(u.service.data(u.p,u.d.id(),original.id()).complete());
        var late=new Fixture();late.command(Operation.START,0);late.clock.advance(11);late.tick();original=late.status().batches().getFirst();var cursor=late.status().task().cursor();late.clock.advance(60);late.late=true;late.tick();var correction=late.status().batches().getFirst();check(correction.reconcilesBatchId().equals(original.id())&&correction.deduplicated()==2&&correction.indices().equals(List.of(0)));check(late.status().task().cursor().equals(cursor)&&late.status().task().confirmedWindows()==1&&late.status().task().confirmedRecords()==3);check(late.sink.batch.records().size()==1&&late.sink.batch.records().getFirst().body().equals("Synthetic Fixture late"));late.tick();check(late.status().task().confirmedWindows()==2&&late.sink.writes==3);
        var change=new Fixture();change.command(Operation.START,0);change.clock.advance(11);change.tick();change.clock.advance(60);change.changed=true;change.tick();check(change.status().task().error().equals("SOURCE_WINDOW_CHANGED")&&change.sink.writes==1);var missing=new Fixture();missing.command(Operation.START,0);missing.clock.advance(11);missing.tick();missing.clock.advance(60);missing.empty=true;missing.tick();check(missing.status().task().error().equals("SOURCE_WINDOW_CHANGED")&&missing.sink.writes==1);
        var stopped=new Fixture();stopped.stopDuringRead=true;stopped.command(Operation.START,0);stopped.clock.advance(11);stopped.tick();check(stopped.status().task().state().equals("STOPPED")&&stopped.sink.writes==0&&stopped.status().batches().isEmpty());
        var down=new Fixture();down.unavailable=true;down.command(Operation.START,0);down.clock.advance(11);down.tick();check(down.status().task().error().equals("SOURCE_UNAVAILABLE")&&down.sink.writes==0);down.unavailable=false;down.command(Operation.RESUME,1);down.tick();check(down.status().task().confirmedWindows()==1);
        var rejected=new Fixture();rejected.sink.rejected=true;rejected.command(Operation.START,0);rejected.clock.advance(11);rejected.tick();check(rejected.status().task().error().equals("OUTPUT_REJECTED"));rejected.sink.rejected=false;rejected.command(Operation.RESUME,1);rejected.tick();check(rejected.status().task().confirmedWindows()==1);
        var noWrite=new Principal(a.p.subjectId(),a.p.tenantId(),Set.of(Permission.SOURCE_SYNC,Permission.LOG_READ),ResourceScope.tenantWide());fail(WorkflowFailure.Code.FORBIDDEN,()->a.service.command(noWrite,a.body(Operation.RESUME,3),()->null));var noRead=new Principal(u.p.subjectId(),u.p.tenantId(),Set.of(Permission.SOURCE_SYNC,Permission.LOG_WRITE),ResourceScope.tenantWide());var id=u.status().batches().getFirst().id();fail(WorkflowFailure.Code.FORBIDDEN,()->u.service.data(noRead,u.d.id(),id));
        var max=new Fixture();max.empty=true;max.command(Operation.START,0);max.clock.advance(11);for(int i=0;i<21;i++){max.tick();max.clock.advance(60);}check(max.status().task().confirmedWindows()==20&&max.status().task().error().equals("EXECUTION_LIMIT"));
        var auth=new Fixture();var issued=auth.clock.instant();var authority=new WorkflowTaskAuthority(UUID.randomUUID(),"https://fixture.invalid","fixture","sha256:"+"a".repeat(64),issued,issued.plusSeconds(30),1,0);auth.service.command(auth.p,auth.body(Operation.START,0),()->authority);auth.clock.advance(11);auth.tick();check(auth.reads==0);auth.service.tickAuthorized(auth.p.tenantId(),auth.p.subjectId().value(),task->auth.p);check(auth.status().task().confirmedWindows()==1&&auth.status().task().authority().consumedBatches()==1);auth.service.tickAuthorized(auth.p.tenantId(),auth.p.subjectId().value(),task->auth.p);check(auth.status().task().error().equals("EXECUTION_LIMIT"));
        var filtered=new Fixture(true);filtered.command(Operation.START,0);filtered.clock.advance(11);filtered.tick();filtered.clock.advance(60);filtered.late=true;filtered.tick();check(filtered.status().task().confirmedRecords()==2&&filtered.sink.writes==1&&filtered.status().batches().getFirst().filtered()==1&&filtered.status().batches().getFirst().indices().isEmpty());filtered.tick();check(filtered.status().task().confirmedWindows()==2&&filtered.sink.writes==2);
        var lateUnknown=new Fixture();lateUnknown.command(Operation.START,0);lateUnknown.clock.advance(11);lateUnknown.tick();var stable=lateUnknown.status().task().cursor();lateUnknown.clock.advance(60);lateUnknown.late=true;lateUnknown.sink.unknown=true;lateUnknown.tick();var lost=lateUnknown.status().batches().getFirst();check(lost.reconcilesBatchId()!=null&&lateUnknown.status().task().confirmedRecords()==2);lateUnknown.sink.visible.put(lost.id(),lateUnknown.sink.batch.records());lateUnknown.service.verify(lateUnknown.p,lateUnknown.d.id(),lost.id());check(lateUnknown.status().task().cursor().equals(stable)&&lateUnknown.status().task().confirmedRecords()==3&&lateUnknown.status().task().state().equals("STOPPED")&&lateUnknown.sink.writes==2);
        var denied=new Principal(new SubjectId("another-owner"),u.p.tenantId(),u.p.permissions(),ResourceScope.tenantWide());fail(WorkflowFailure.Code.NOT_FOUND,()->u.service.data(denied,u.d.id(),id));
        var expiry=new Fixture();var issuedAt=expiry.clock.instant();expiry.service.command(expiry.p,expiry.body(Operation.START,0),()->new WorkflowTaskAuthority(UUID.randomUUID(),"https://fixture.invalid","fixture","sha256:"+"a".repeat(64),issuedAt,issuedAt.plusSeconds(5),20,0));expiry.clock.advance(11);expiry.service.tickAuthorized(expiry.p.tenantId(),expiry.p.subjectId().value(),t->expiry.p);check(expiry.status().task().error().equals("AUTHORIZATION_EXPIRED")&&expiry.reads==0&&expiry.sink.writes==0);
        var revoke=new Fixture();var grant=revoke.clock.instant();revoke.service.command(revoke.p,revoke.body(Operation.START,0),()->new WorkflowTaskAuthority(UUID.randomUUID(),"https://fixture.invalid","fixture","sha256:"+"a".repeat(64),grant,grant.plusSeconds(30),20,0));revoke.clock.advance(11);revoke.service.tickAuthorized(revoke.p.tenantId(),revoke.p.subjectId().value(),t->null);check(revoke.status().task().error().equals("AUTHORIZATION_REVOKED")&&revoke.reads==0&&revoke.sink.writes==0);
        var historical=new Fixture();historical.command(Operation.START,0);historical.clock.advance(11);historical.tick();var oldest=historical.status().batches().getFirst();historical.store.transaction(historical.p.tenantId(),s->{for(int i=0;i<20;i++){var at=historical.clock.instant().plusNanos((i+1)*1000L);var b=new Batch(UUID.randomUUID(),oldest.workflowId(),1,oldest.digest(),oldest.from(),oldest.till(),at,at,"IN_FLIGHT",oldest.inputCount(),oldest.filtered(),0,oldest.indices(),oldest.positions(),oldest.inputDigest(),oldest.batchDigest(),null,null);s.addLogStreamBatch(historical.p.subjectId().value(),b);s.finishLogStreamBatch(historical.p.subjectId().value(),b.finish("FAILED","OUTPUT_REJECTED",at));}return null;});check(historical.status().batches().stream().noneMatch(b->b.id().equals(oldest.id())));historical.clock.advance(60);historical.late=true;historical.tick();check(historical.status().task().confirmedRecords()==3&&historical.status().task().confirmedWindows()==1&&historical.status().task().error()==null);
        var readLost=new Fixture();readLost.sink.readDown=true;readLost.command(Operation.START,0);readLost.clock.advance(11);readLost.tick();var readLostTask=readLost.status().task();var readLostBatch=readLost.status().batches().getFirst();check(readLostTask.state().equals("FAILED")&&readLostTask.error().equals("OUTPUT_UNCONFIRMED")&&readLostBatch.state().equals("UNKNOWN")&&readLost.sink.writes==1);fail(WorkflowFailure.Code.CONFLICT,()->readLost.command(Operation.RESUME,1));readLost.sink.readDown=false;readLost.service.verify(readLost.p,readLost.d.id(),readLostBatch.id());check(readLost.status().task().state().equals("STOPPED")&&readLost.status().task().confirmedRecords()==2&&readLost.sink.writes==1);
        System.out.println("WorkflowLogStreamSmoke: "+checks+" checks passed");
    }
}
