import com.acme.opsweave.catalog.domain.*;
import com.acme.opsweave.catalog.domain.ModelDefinition.*;
import com.acme.opsweave.identity.domain.*;
import com.acme.opsweave.integration.domain.*;
import com.acme.opsweave.integration.domain.WorkflowDefinition.*;
import com.acme.opsweave.integration.api.WorkflowStore.*;
import com.acme.opsweave.integration.application.WorkflowService;
import com.acme.opsweave.integration.infrastructure.InMemoryWorkflowStore;
import com.acme.opsweave.sharedkernel.TenantId;
import java.time.*;
import java.util.*;
import java.math.BigDecimal;

public final class WorkflowSmoke {
 static int checks;
 static void check(boolean ok){checks++;if(!ok)throw new AssertionError("Workflow check "+checks);}
 static void rejects(Runnable r){checks++;try{r.run();}catch(IllegalArgumentException|WorkflowFailure e){return;}throw new AssertionError("Expected rejection "+checks);}
 static void failure(WorkflowFailure.Code code,Runnable r){checks++;try{r.run();}catch(WorkflowFailure e){if(e.code()==code)return;throw new AssertionError(e.code());}throw new AssertionError("Expected "+code);}
 static final ModelDefinition MODEL=new ModelDefinition("custom.flow",1,Kind.ENTITY,"Flow","fixture",List.of(new Field("name","Name",ModelDefinition.Type.TEXT,true,255,null,null,List.of()),new Field("count","Count",ModelDefinition.Type.INTEGER,false,null,BigDecimal.ZERO,new BigDecimal("9999"),List.of()),new Field("state","State",ModelDefinition.Type.ENUM,false,16,null,null,List.of("on","off"))),null);
 static Node node(String id,WorkflowDefinition.Type type,Map<String,String> c){return WorkflowOperators.builtIn().pin(new Node(id,type,"1",c));}
 static WorkflowDefinition flow(String id,int rev,Source source,Node...middle){var nodes=new ArrayList<Node>();nodes.add(node("source",WorkflowDefinition.Type.SOURCE,Map.of()));nodes.add(node("map",WorkflowDefinition.Type.MAP,Map.of("raw_name","name","raw_count","count","raw_state","state")));nodes.addAll(List.of(middle));nodes.add(node("validate",WorkflowDefinition.Type.VALIDATE,Map.of()));nodes.add(node("output",WorkflowDefinition.Type.OUTPUT,Map.of()));var edges=new ArrayList<Edge>();for(int i=0;i<nodes.size()-1;i++)edges.add(new Edge(nodes.get(i).id(),nodes.get(i+1).id()));return new WorkflowDefinition(id,rev,"Fixture workflow",source,new Target(MODEL.id(),1,MODEL.digest()),nodes,edges);}
 static WorkflowDefinition flow(Node...middle){return flow("fixture-flow",1,new Source("MANUAL_SAMPLE","manual"),middle);}
 static Map<String,Position> layout(WorkflowDefinition d){var result=new LinkedHashMap<String,Position>();for(int i=0;i<d.nodes().size();i++)result.put(d.nodes().get(i).id(),new Position(100,100*i));return result;}
 static Principal principal(String tenant,String owner){return new Principal(new SubjectId(owner),new TenantId(tenant),Set.of(Permission.SOURCE_SYNC,Permission.ENTITY_READ),ResourceScope.tenantWide());}
 static final class TestClock extends Clock {Instant instant=Instant.parse("2026-09-27T12:00:00Z");public Instant instant(){return instant;}public ZoneId getZone(){return ZoneOffset.UTC;}public Clock withZone(ZoneId zone){return this;}}
 public static void main(String[] args){
  var trim=node("trim",WorkflowDefinition.Type.TRIM,Map.of());var d=flow(trim);var result=WorkflowEvaluation.evaluate(d,MODEL,List.of(Map.of("raw_name"," service ","raw_count","9")));
  check(result.accepted()==1&&result.rejected()==0&&result.filtered()==0&&result.dryRun()&&!result.writesPerformed());check(result.rows().getFirst().steps().getLast().values().get("name").equals("service"));check(result.rows().getFirst().steps().getFirst().values().get("raw_name").equals(" service "));
  var transform=flow(trim,node("default",WorkflowDefinition.Type.DEFAULT,Map.of("field","count","value","2")),node("scale",WorkflowDefinition.Type.SCALE,Map.of("field","count","factor","10")),node("enum",WorkflowDefinition.Type.ENUM_MAP,Map.of("field","state","from","yes","to","on")),node("filter",WorkflowDefinition.Type.FILTER,Map.of("field","state","equals","on")));
  result=WorkflowEvaluation.evaluate(transform,MODEL,List.of(Map.of("raw_name","a","raw_state"," yes "),Map.of("raw_name","b","raw_state","no"),Map.of("raw_name","c","raw_count","NaN","raw_state","yes")));
  check(result.accepted()==1&&result.filtered()==1&&result.rejected()==1);check(((BigDecimal)result.rows().getFirst().steps().getLast().values().get("count")).intValueExact()==20);check(result.rows().get(1).steps().getLast().status().equals("SKIPPED"));check(result.rows().get(2).steps().stream().anyMatch(s->s.issues().stream().anyMatch(i->i.code().equals("TRANSFORM_FAILED"))));
  rejects(()->WorkflowEvaluation.evaluate(d,MODEL,List.of(Map.of("raw_name",String.valueOf((char)1).repeat(1000)))));rejects(()->WorkflowEvaluation.evaluate(d,MODEL,List.of(Map.of("raw_name",Double.NaN))));
  var nulls=new HashMap<String,Object>();nulls.put("raw_name","n");nulls.put("raw_count",null);result=WorkflowEvaluation.evaluate(flow(node("default",WorkflowDefinition.Type.DEFAULT,Map.of("field","count","value","5"))),MODEL,List.of(nulls));check(result.accepted()==1);check(result.rows().getFirst().steps().getLast().values().containsKey("count"));check(result.rows().getFirst().steps().getLast().values().get("count")==null);
  result=WorkflowEvaluation.evaluate(flow(node("empty",WorkflowDefinition.Type.EMPTY_TO_NULL,Map.of("field","name"))),MODEL,List.of(Map.of("raw_name"," ")));check(result.rejected()==1);check(result.rows().getFirst().steps().get(3).issues().getFirst().code().equals("NULL_REQUIRED"));
  check(WorkflowEvaluation.evaluate(d,MODEL,List.of(Map.of())).rejected()==1);rejects(()->WorkflowEvaluation.evaluate(d,MODEL,List.of()));rejects(()->WorkflowEvaluation.evaluate(d,MODEL,Collections.nCopies(6,Map.of("raw_name","n"))));rejects(()->WorkflowEvaluation.evaluate(d,MODEL,List.of(Map.of("raw_name",Map.of("nested",true)))));rejects(()->WorkflowEvaluation.evaluate(d,MODEL,List.of(Map.of("raw_name","x".repeat(2049)))));
  rejects(()->new Source("HTTP","example"));rejects(()->new Source("MANUAL_SAMPLE","source"));rejects(()->node("shell",WorkflowDefinition.Type.TRIM,Map.of("script","x")));rejects(()->node("map",WorkflowDefinition.Type.MAP,Map.of("tenantId","name")));rejects(()->node("map",WorkflowDefinition.Type.MAP,Map.of("a","name","b","name")));rejects(()->new Node("x",WorkflowDefinition.Type.TRIM,"2",Map.of()));
  for(String factor:List.of("0","1e4","NaN","1000001","0.0000000000001"))rejects(()->node("scale",WorkflowDefinition.Type.SCALE,Map.of("field","count","factor",factor)));
  var wrongEdges=new ArrayList<>(d.edges());wrongEdges.set(0,new Edge("source","source"));rejects(()->new WorkflowDefinition(d.id(),1,d.name(),d.source(),d.target(),d.nodes(),wrongEdges));rejects(()->flow(node("map",WorkflowDefinition.Type.TRIM,Map.of())));rejects(()->flow(node("another-source",WorkflowDefinition.Type.SOURCE,Map.of())));
  var copy=new LinkedHashMap<String,String>();copy.put("raw_state","state");copy.put("raw_count","count");copy.put("raw_name","name");var nodes=new ArrayList<>(d.nodes());nodes.set(1,node("map",WorkflowDefinition.Type.MAP,copy));check(new WorkflowDefinition(d.id(),1,d.name(),d.source(),d.target(),nodes,d.edges()).digest().equals(d.digest()));
  var p=principal("flow-a","one");var other=principal("flow-a","two");var tenant=principal("flow-b","one");var store=new InMemoryWorkflowStore();var clock=new TestClock();var service=new WorkflowService(store,(who,t)->MODEL,(who,s,b)->{throw new AssertionError("Manual must not read source");},clock);
  var saved=service.save(p,d,layout(d),0);check(saved.editVersion()==1);rejects(()->service.save(p,d,layout(d),0));check(service.drafts(other).items().isEmpty());check(service.drafts(tenant).items().isEmpty());failure(WorkflowFailure.Code.NOT_FOUND,()->service.draft(other,d.id(),1));
  var scoped=new Principal(p.subjectId(),p.tenantId(),p.permissions(),ResourceScope.of(Set.of(ResourceRef.anyEntity(p.tenantId()))));failure(WorkflowFailure.Code.FORBIDDEN,()->service.save(scoped,d,layout(d),0));var noSync=new Principal(p.subjectId(),p.tenantId(),Set.of(Permission.ENTITY_READ),ResourceScope.tenantWide());failure(WorkflowFailure.Code.FORBIDDEN,()->service.versions(noSync));
  failure(WorkflowFailure.Code.PREVIEW_REQUIRED,()->service.publish(p,d.id(),1,1,d.digest(),UUID.randomUUID()));
  var preview=service.evaluate(p,d.id(),1,1,d.digest(),false,List.of(Map.of("raw_name","fixture")),null);check(preview.receipt().origin().equals("MANUAL_SAMPLE"));check(service.runs(p).items().size()==1);check(service.runs(other).items().isEmpty());failure(WorkflowFailure.Code.PREVIEW_REQUIRED,()->service.publish(p,d.id(),1,1,d.digest(),UUID.randomUUID()));
  var moved=new LinkedHashMap<>(layout(d));moved.put("source",new Position(200,0));var movedDraft=service.save(p,d,moved,1);check(movedDraft.preview().id().equals(preview.receipt().id()));check(movedDraft.editVersion()==2);var published=service.publish(p,d.id(),1,2,d.digest(),preview.receipt().id());check(published.state().equals("PUBLISHED"));check(service.drafts(p).items().isEmpty());check(service.version(other,d.id(),1).digest().equals(d.digest()));check(service.publish(p,d.id(),1,2,d.digest(),preview.receipt().id()).equals(published));rejects(()->service.save(p,d,moved,2));failure(WorkflowFailure.Code.NOT_FOUND,()->service.version(tenant,d.id(),1));
  check(service.evaluate(p,d.id(),1,0,d.digest(),true,List.of(Map.of("raw_name","fixture")),null).evaluation().accepted()==1);check(service.runs(p).items().getFirst().mode().equals("RUN"));
  var d2=flow(d.id(),2,d.source(),trim);service.save(p,d2,layout(d2),0);var bad=service.evaluate(p,d2.id(),2,1,d2.digest(),false,List.of(Map.of()),null);failure(WorkflowFailure.Code.PREVIEW_REQUIRED,()->service.publish(p,d2.id(),2,1,d2.digest(),bad.receipt().id()));
  var good=service.evaluate(p,d2.id(),2,1,d2.digest(),false,List.of(Map.of("raw_name","ok")),null);clock.instant=clock.instant.plusSeconds(901);failure(WorkflowFailure.Code.PREVIEW_REQUIRED,()->service.publish(p,d2.id(),2,1,d2.digest(),good.receipt().id()));clock.instant=good.receipt().createdAt().minusSeconds(1);failure(WorkflowFailure.Code.PREVIEW_REQUIRED,()->service.publish(p,d2.id(),2,1,d2.digest(),good.receipt().id()));
  var renamed=new WorkflowDefinition(d2.id(),2,"Changed",d2.source(),d2.target(),d2.nodes(),d2.edges());check(service.save(p,renamed,layout(renamed),1).preview()==null);
  var remote=flow("remote",1,new Source("ZABBIX_HOST","zabbix-1"),trim);var remoteService=new WorkflowService(store,(who,t)->MODEL,(who,s,b)->new WorkflowService.Batch(List.of(Map.of("raw_name","real marker fixture")),"fixture",9,2,true,"FAILED"),clock);remoteService.save(p,remote,layout(remote),0);var remoteResult=remoteService.evaluate(p,remote.id(),1,1,remote.digest(),false,null,UUID.randomUUID());check(remoteResult.receipt().origin().equals("fixture")&&remoteResult.truncated()&&remoteResult.missingRaw()==2&&remoteResult.sourceStatus().equals("FAILED"));rejects(()->remoteService.evaluate(p,remote.id(),1,1,remote.digest(),false,List.of(Map.of("raw_name","no")),UUID.randomUUID()));
  var invalidTarget=new WorkflowDefinition("pin",1,d.name(),d.source(),new Target(MODEL.id(),1,"sha256:"+"a".repeat(64)),d.nodes(),d.edges());failure(WorkflowFailure.Code.MODEL_CHANGED,()->service.save(p,invalidTarget,layout(invalidTarget),0));
  // A source read racing a save must not attach its old receipt to the new edit.
  var racing=new WorkflowService(store,(who,t)->MODEL,(who,s,b)->{remoteService.save(p,remote,layout(remote),1);return new WorkflowService.Batch(List.of(Map.of("raw_name","n")),"fixture",1,0,false,"SUCCEEDED");},clock);failure(WorkflowFailure.Code.CONFLICT,()->racing.evaluate(p,remote.id(),1,1,remote.digest(),false,null,UUID.randomUUID()));
  var retained=service.run(p,preview.receipt().id());check(retained.trace()!=null&&retained.trace().rows().size()==1);check(retained.trace().rows().getFirst().steps().getLast().status().equals("OK"));
  failure(WorkflowFailure.Code.NOT_FOUND,()->service.run(other,preview.receipt().id()));failure(WorkflowFailure.Code.NOT_FOUND,()->service.run(tenant,preview.receipt().id()));failure(WorkflowFailure.Code.FORBIDDEN,()->service.run(noSync,preview.receipt().id()));
  var traceMixed=WorkflowEvaluation.evaluate(transform,MODEL,List.of(Map.of("raw_name","PRIVATE VALUE","raw_state","yes"),Map.of("raw_name","b","raw_state","no"),Map.of("raw_name","c","raw_count","bad","raw_state","yes")));
  var metadata=WorkflowTrace.metadata(traceMixed);check(metadata.size()==3);check(metadata.get(1).status().equals("FILTERED"));check(metadata.get(2).steps().stream().anyMatch(step->step.issues().stream().anyMatch(issue->issue.code().equals("TRANSFORM_FAILED"))));check(!metadata.toString().contains("PRIVATE VALUE"));
  rejects(()->new WorkflowTrace.Step("node",WorkflowDefinition.Type.VALIDATE,"OK",List.of(new ModelPreview.Issue("name","TYPE_MISMATCH"))));rejects(()->new WorkflowTrace.Step("node",WorkflowDefinition.Type.VALIDATE,"ERROR",List.of(new ModelPreview.Issue("name","EXCEPTION_TEXT"))));rejects(()->new WorkflowTrace.Row(0,"REJECTED",metadata.getFirst().steps()));
  var sourceTrace=remoteService.run(p,remoteResult.receipt().id()).trace();check(sourceTrace.sourceStatus().equals("FAILED")&&sourceTrace.missingRaw()==2&&sourceTrace.truncated());
  System.out.println("WorkflowSmoke: "+checks+" checks passed");
 }
}
