import com.acme.opsweave.integration.domain.*;
import com.acme.opsweave.integration.application.*;
import java.time.*;
import java.util.*;

/** Explicit in-memory protocol fixtures. No claim of provider or database connectivity. */
public final class WorkflowDiagnosticsSmoke {
    static int checks;static void check(boolean v){checks++;if(!v)throw new AssertionError("Diagnostics "+checks);}
    static WorkflowFailure failure(Runnable r){checks++;try{r.run();}catch(WorkflowFailure f){return f;}throw new AssertionError("Expected typed rejection");}
    static final Instant FROM=WorkflowLogWindowSmoke.FROM,TILL=FROM.plusSeconds(60),NOW=TILL.plusSeconds(10);
    static WorkflowDiagnostics.Result logs(List<Map<String,Object>> rows){var d=WorkflowLogWindowSmoke.definition(false);var result=new WorkflowDiagnostics.Result[1];WorkflowLogWindow.prepare(WorkflowLogWindowSmoke.scope(d),WorkflowOperators.builtIn().compile(d,null),rows,FROM,TILL,NOW,v->result[0]=v);return result[0];}
    public static void main(String[] args)throws Exception{
        var rows=new ArrayList<>(java.util.stream.IntStream.range(0,10).mapToObj(WorkflowLogWindowSmoke::row).toList());var bad=new LinkedHashMap<>(rows.get(2));bad.put("body"," ");rows.set(2,Collections.unmodifiableMap(bad));
        var rejection=failure(()->logs(rows));check(rejection.code()==WorkflowFailure.Code.INVALID_SAMPLE);var r=rejection.diagnostics();check(r.coverage().equals("PARTIAL")&&r.received()==10&&r.accepted()==4&&r.rejected()==1&&r.unknown()==5);check(r.schemaMismatch()==1&&r.unitMismatch()==null&&r.invalidTimestamp()==0);check(r.nodes().getFirst().received()==5);check(r.nodes().getLast().skipped()==1&&r.nodes().getLast().accepted()==4);check(r.nodes().stream().anyMatch(n->n.issues().getOrDefault("EMPTY_REQUIRED",0)==1));
        var good=logs(java.util.stream.IntStream.range(0,10).mapToObj(WorkflowLogWindowSmoke::row).toList());check(good.coverage().equals("COMPLETE")&&good.accepted()==10&&good.rejected()==0&&good.unknown()==0);check(good.nodes().stream().allMatch(n->n.received()==10));var empty=logs(List.of());check(empty.received()==0&&empty.accepted()==0&&empty.coverage().equals("COMPLETE"));
        var invalidTime=new LinkedHashMap<>(WorkflowLogWindowSmoke.row(0));invalidTime.put("timestamp","not-a-time");r=failure(()->logs(List.of(invalidTime,WorkflowLogWindowSmoke.row(1)))).diagnostics();check(r.received()==2&&r.rejected()==1&&r.unknown()==1&&r.invalidTimestamp()==1);check(r.nodes().getFirst().issues().equals(Map.of("TYPE_MISMATCH",1)));
        var f=new WorkflowMetricOutputSmoke.Fixture();var plan=f.store.transaction(f.p.tenantId(),s->f.workflows.executionPlan(f.p,s,s.published(f.d.id(),1).orElseThrow()));
        var missing=Map.<String,Object>of("timestamp",FROM.toString(),"value","12.5");r=failure(()->WorkflowMetricBatches.prepare(f.p,f.d,plan,List.of(missing),FROM,TILL)).diagnostics();check(r.missingIdentity()==1&&r.schemaMismatch()==1&&r.unitMismatch()==0);
        var metric=new WorkflowMetricStreamSmoke.Fixture();metric.command(WorkflowMetricStream.Operation.START,0);metric.time.advance(11);metric.tick();var observations=metric.f.store.transaction(metric.f.p.tenantId(),s->s.diagnostics(metric.f.p.subjectId().value(),metric.f.d.id(),1,metric.f.d.digest()));check(observations.size()==1);var observed=observations.getFirst().observation();check(observed.state().equals("CHECKED")&&observed.result().received()==2&&observed.result().unitMismatch()==0);check(observations.getFirst().entityIds().isEmpty());
        var unavailable=new WorkflowMetricStreamSmoke.Fixture();unavailable.unavailable=true;unavailable.command(WorkflowMetricStream.Operation.START,0);unavailable.time.advance(11);unavailable.tick();var failed=unavailable.f.store.transaction(unavailable.f.p.tenantId(),s->s.diagnostics(unavailable.f.p.subjectId().value(),unavailable.f.d.id(),1,unavailable.f.d.digest())).getFirst().observation();check(failed.state().equals("SOURCE_FAILED")&&failed.error().equals("SOURCE_UNAVAILABLE"));check(failed.result().received()==null&&failed.result().nodes().isEmpty());check(unavailable.f.sink.writes==0&&unavailable.status().batches().isEmpty());
        var stop=new WorkflowMetricStreamSmoke.Fixture();stop.stopDuringRead=true;stop.command(WorkflowMetricStream.Operation.START,0);stop.time.advance(11);stop.tick();check(stop.f.store.transaction(stop.f.p.tenantId(),s->s.diagnosticCount(stop.f.p.subjectId().value()))==0&&stop.f.sink.writes==0);
        var ref=new WorkflowQuality.Reference(f.d.id(),1,f.d.digest());var clock=Clock.fixed(NOW,ZoneOffset.UTC);var recorder=new WorkflowDiagnosticRecorder(f.store,clock);var calls=new int[]{0};for(int i=0;i<200;i++)recorder.inspect(f.p.tenantId(),f.p.subjectId().value(),ref,WorkflowQuality.Kind.METRIC_STREAM,1,FROM,TILL,null,s->true,(consumer,at)->{calls[0]++;consumer.accept(new WorkflowDiagnostics.Result("COMPLETE",null,0,0,0,0,0,0,0,0,0,List.of()));return null;});check(calls[0]==200);check(failure(()->recorder.inspect(f.p.tenantId(),f.p.subjectId().value(),ref,WorkflowQuality.Kind.METRIC_STREAM,1,FROM,TILL,null,s->true,(consumer,at)->{calls[0]++;return null;})).code()==WorkflowFailure.Code.CAPACITY);check(calls[0]==200);
        var crowded=new WorkflowMetricStreamSmoke.Fixture();crowded.command(WorkflowMetricStream.Operation.START,0);crowded.time.advance(11);crowded.tick();var original=crowded.status().batches().getFirst();crowded.f.store.transaction(crowded.f.p.tenantId(),s->{for(int i=0;i<21;i++){var at=original.createdAt().plusNanos(1000L*(i+1));var b=new WorkflowMetricStream.Batch(UUID.randomUUID(),original.workflowId(),1,original.digest(),original.from(),original.till(),at,at,"IN_FLIGHT",original.inputCount(),original.filtered(),original.collapsed(),original.labels(),original.batchDigest(),original.timestamps(),null);s.addMetricStreamBatch(crowded.f.p.subjectId().value(),b);s.finishMetricStreamBatch(crowded.f.p.subjectId().value(),b.finish("FAILED","OUTPUT_REJECTED",at));}return null;});check(crowded.status().batches().stream().noneMatch(b->b.id().equals(original.id())));crowded.time.advance(60);crowded.late=true;crowded.tick();var correction=crowded.status().batches().getFirst();check(correction.reconcilesBatchId().equals(original.id())&&correction.latePoints()==1&&crowded.status().task().confirmedPoints()==3);check(crowded.f.sink.writes==2);
        System.out.println("WorkflowDiagnosticsSmoke: "+checks+" checks passed");
    }
}
