import com.acme.opsweave.integration.application.*;
import com.acme.opsweave.integration.domain.*;
import com.acme.opsweave.integration.domain.WorkflowQualityAlerts.*;
import com.acme.opsweave.identity.domain.*;
import com.acme.opsweave.sharedkernel.TenantId;
import java.time.*;
import java.util.*;

/** Explicit source/sink fixtures and journal projections; thresholds cannot perform business IO. */
public final class WorkflowQualityAlertsSmoke {
 static int checks;static void check(boolean v){checks++;if(!v)throw new AssertionError("Threshold check "+checks);}
 static void invalid(Runnable r){checks++;try{r.run();}catch(IllegalArgumentException e){return;}throw new AssertionError("Expected invalid threshold");}
 static void fail(WorkflowFailure.Code code,Runnable r){checks++;try{r.run();}catch(WorkflowFailure e){if(e.code()==code)return;throw e;}throw new AssertionError("Expected "+code);}
 static WorkflowDiagnostics.Observation observation(WorkflowQuality.Reference ref,Instant at,Boolean failed,WorkflowDiagnostics.Dispatch dispatch){var result=failed==null||failed?WorkflowDiagnostics.Result.unavailable():new WorkflowDiagnostics.Result("COMPLETE",null,0,0,0,0,0,0,0,0,null,List.of());var read=failed==null?null:new WorkflowDiagnostics.SourceRead(1,failed?0:1,failed?1:0,failed?null:0,failed?WorkflowDiagnostics.SourceFailure.UNAVAILABLE:null,at,at);return new WorkflowDiagnostics.Observation(UUID.randomUUID(),ref,WorkflowQuality.Kind.LOG_STREAM,1,failed==null||failed?"SOURCE_FAILED":"CHECKED",at.minusSeconds(70),at.minusSeconds(10),at,at,dispatch==null?null:dispatch.waitMillis(),null,failed==null||failed?"SOURCE_UNAVAILABLE":null,result,read,dispatch);}
 static Evaluation evaluate(Rule rule,Instant at,WorkflowQuality.Reference ref,List<WorkflowDiagnostics.Observation> observations,List<WorkflowQuality.Batch> batches,boolean truncated){var c=new Configuration(ref,1,600,List.of(rule),at);var q=new WorkflowQuality.Report("2.0",at,ref,WorkflowQuality.Kind.LOG_STREAM,null,batches,truncated&&batches.size()==20);var d=new WorkflowDiagnostics.Report("2.0",at,ref,observations,truncated&&observations.size()==20);return WorkflowQualityAlerts.evaluate(c,q,d,false).evaluations().getFirst();}
 public static void main(String[] args)throws Exception{
  var f=new WorkflowLogStreamSmoke.Fixture();var service=new WorkflowQualityAlertService(f.store,f.flows,f.clock);var ref=new WorkflowQuality.Reference(f.d.id(),1,f.d.digest());var at=f.clock.instant();
  check(service.status(f.p,f.d.id(),1).configuration()==null);check(f.reads==0&&f.sink.writes==0);
  var command=new Command(UUID.randomUUID(),ref.id(),1,ref.digest(),0,600,List.of(new Rule(Kind.SOURCE_FAILURES,1),new Rule(Kind.TASK_FAILURE,1)));var receipt=service.configure(f.p,command);check(receipt.configuration().editVersion()==1);check(service.configure(f.p,command).equals(receipt));check(service.receipt(f.p,ref.id(),1,command.requestId()).equals(receipt));check(service.status(f.p,ref.id(),1).evaluations().stream().allMatch(e->e.state()==State.UNAVAILABLE));check(f.reads==0&&f.sink.writes==0);
  fail(WorkflowFailure.Code.CONFLICT,()->service.configure(f.p,new Command(command.requestId(),ref.id(),1,ref.digest(),0,600,List.of(new Rule(Kind.SOURCE_FAILURES,2)))));fail(WorkflowFailure.Code.CONFLICT,()->service.configure(f.p,new Command(UUID.randomUUID(),ref.id(),1,ref.digest(),0,600,List.of())));
  var other=new Principal(new SubjectId("threshold-other"),f.p.tenantId(),f.p.permissions(),f.p.resourceScope());check(service.status(other,ref.id(),1).configuration()==null);fail(WorkflowFailure.Code.NOT_FOUND,()->service.receipt(other,ref.id(),1,command.requestId()));var denied=new Principal(f.p.subjectId(),f.p.tenantId(),Set.of(Permission.SOURCE_SYNC),ResourceScope.tenantWide());fail(WorkflowFailure.Code.FORBIDDEN,()->service.configure(denied,new Command(UUID.randomUUID(),ref.id(),1,ref.digest(),1,600,List.of())));var foreign=new Principal(f.p.subjectId(),new TenantId("threshold-other"),f.p.permissions(),f.p.resourceScope());fail(WorkflowFailure.Code.NOT_FOUND,()->service.status(foreign,ref.id(),1));
  f.unavailable=true;f.command(WorkflowLogStream.Operation.START,0);f.clock.advance(11);f.tick();var evidence=service.status(f.p,ref.id(),1);check(evidence.evaluations().stream().allMatch(e->e.state()==State.TRIGGERED));check(evidence.evaluations().getFirst().value()==1);var reads=f.reads;var writes=f.sink.writes;service.status(f.p,ref.id(),1);service.receipt(f.p,ref.id(),1,command.requestId());check(f.reads==reads&&f.sink.writes==writes);
  var disabled=service.configure(f.p,new Command(UUID.randomUUID(),ref.id(),1,ref.digest(),1,600,List.of()));check(disabled.configuration().editVersion()==2&&service.status(f.p,ref.id(),1).evaluations().isEmpty());check(service.receipt(f.p,ref.id(),1,command.requestId()).equals(receipt));fail(WorkflowFailure.Code.CONFLICT,()->new WorkflowQualityAlertService(f.store,f.flows,Clock.fixed(f.clock.instant().minusSeconds(100),ZoneOffset.UTC)).configure(f.p,new Command(UUID.randomUUID(),ref.id(),1,ref.digest(),2,600,List.of())));
  invalid(()->new Rule(Kind.TASK_FAILURE,2));invalid(()->new Rule(Kind.SOURCE_FAILURES,0));invalid(()->new Rule(Kind.QUEUE_WAIT,3600001));invalid(()->new Command(UUID.randomUUID(),ref.id(),1,ref.digest(),0,59,List.of()));invalid(()->new Command(UUID.randomUUID(),ref.id(),1,ref.digest(),0,600,List.of(new Rule(Kind.SOURCE_FAILURES,1),new Rule(Kind.SOURCE_FAILURES,2))));
  at=f.clock.instant();var failObs=observation(ref,at,true,null);var successObs=observation(ref,at.minusSeconds(1),false,null);var oldObs=observation(ref,at.minusSeconds(2),null,null);check(evaluate(new Rule(Kind.SOURCE_FAILURES,1),at,ref,List.of(failObs,oldObs),List.of(),false).state()==State.TRIGGERED);check(evaluate(new Rule(Kind.SOURCE_FAILURES,2),at,ref,List.of(failObs,oldObs),List.of(),false).state()==State.UNAVAILABLE);check(evaluate(new Rule(Kind.SOURCE_FAILURES,2),at,ref,List.of(failObs,successObs,oldObs),List.of(),false).state()==State.NORMAL);check(evaluate(new Rule(Kind.SOURCE_FAILURES,1),at,ref,List.of(observation(ref,at.minusSeconds(601),true,null)),List.of(),false).reason().equals("NO_DATA"));
  var tied=evaluate(new Rule(Kind.SOURCE_FAILURES,1),at,ref,List.of(failObs,observation(ref,at,false,null)),List.of(),false);check(tied.state()==State.UNAVAILABLE&&tied.reason().equals("AMBIGUOUS_ORDER"));
  var dispatch=new WorkflowDiagnostics.Dispatch(UUID.randomUUID(),at.minusMillis(275),at);var one=observation(ref,at,false,dispatch);var two=observation(ref,at,false,dispatch);var peak=evaluate(new Rule(Kind.QUEUE_WAIT,250),at,ref,List.of(one,two,oldObs),List.of(),false);check(peak.state()==State.TRIGGERED&&peak.value()==275&&peak.sampleCount()==1&&peak.missingCount()==1&&peak.evidenceIds().size()==1);check(evaluate(new Rule(Kind.QUEUE_WAIT,500),at,ref,List.of(one,oldObs),List.of(),false).state()==State.UNAVAILABLE);check(evaluate(new Rule(Kind.QUEUE_WAIT,500),at,ref,List.of(one,two),List.of(),false).state()==State.NORMAL);
  var bounded=new ArrayList<WorkflowDiagnostics.Observation>();for(int i=0;i<20;i++){var t=at.minusSeconds(i);bounded.add(observation(ref,t,false,new WorkflowDiagnostics.Dispatch(UUID.randomUUID(),t,t)));}check(evaluate(new Rule(Kind.QUEUE_WAIT,1),at,ref,bounded,List.of(),true).reason().equals("HISTORY_TRUNCATED"));check(evaluate(new Rule(Kind.SOURCE_FAILURES,1),at,ref,bounded,List.of(),true).state()==State.NORMAL);
  var output=new WorkflowLogStreamSmoke.Fixture();output.command(WorkflowLogStream.Operation.START,0);output.clock.advance(11);output.tick();var batch=output.status().batches().getFirst();var observed=WorkflowQuality.log(batch.finish("FAILED","OUTPUT_REJECTED",batch.updatedAt()),true);check(evaluate(new Rule(Kind.OUTPUT_REJECTIONS,1),output.clock.instant(),new WorkflowQuality.Reference(output.d.id(),1,output.d.digest()),List.of(),List.of(observed),false).state()==State.TRIGGERED);var unknown=WorkflowQuality.log(batch.finish("FAILED","OUTPUT_REJECTED",batch.updatedAt()),false);check(evaluate(new Rule(Kind.OUTPUT_REJECTIONS,1),output.clock.instant(),new WorkflowQuality.Reference(output.d.id(),1,output.d.digest()),List.of(),List.of(unknown),false).state()==State.UNAVAILABLE);
  for(int i=2;i<199;i++)service.configure(f.p,new Command(UUID.randomUUID(),ref.id(),1,ref.digest(),i,600,List.of(new Rule(Kind.TASK_FAILURE,1))));fail(WorkflowFailure.Code.CAPACITY,()->service.configure(f.p,new Command(UUID.randomUUID(),ref.id(),1,ref.digest(),199,600,List.of(new Rule(Kind.TASK_FAILURE,1)))));check(service.configure(f.p,new Command(UUID.randomUUID(),ref.id(),1,ref.digest(),199,600,List.of())).configuration().rules().isEmpty());fail(WorkflowFailure.Code.CAPACITY,()->service.configure(f.p,new Command(UUID.randomUUID(),ref.id(),1,ref.digest(),200,600,List.of())));
  System.out.println("WorkflowQualityAlertsSmoke: "+checks+" checks passed");
 }
}
