package com.acme.opsweave.platform;

import static org.junit.jupiter.api.Assertions.*;
import com.acme.opsweave.identity.domain.*;
import com.acme.opsweave.integration.domain.*;
import com.acme.opsweave.platform.catalog.CatalogJson;
import com.acme.opsweave.platform.workflow.RegisteredHostSourceReader;
import com.acme.opsweave.sharedkernel.TenantId;
import com.sun.net.httpserver.HttpServer;
import java.net.*;
import java.net.http.*;
import java.nio.charset.StandardCharsets;
import java.nio.file.*;
import java.time.Duration;
import java.util.*;
import java.util.concurrent.atomic.AtomicInteger;
import org.junit.jupiter.api.*;
import org.junit.jupiter.api.condition.EnabledIfEnvironmentVariable;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.web.server.LocalServerPort;
import org.springframework.test.context.*;

/** Real loopback HTTP and PostgreSQL, with explicitly synthetic upstream rows and credential values. */
@SpringBootTest(webEnvironment=SpringBootTest.WebEnvironment.RANDOM_PORT,properties={"server.address=127.0.0.1","opsweave.auth.mode=dev","opsweave.auth.dev.subject=endpoint-fixture-author","opsweave.auth.dev.permissions=source.sync,source.configure,entity.read,entity.manage,metric.read","opsweave.zabbix.mode=fixture","opsweave.inventory.store=postgres"})
@EnabledIfEnvironmentVariable(named="OPSWEAVE_TEST_JDBC_URL",matches=".+")
class SourceEndpointHttpIT {
 static final String TOKEN="endpoint-fixture-"+UUID.randomUUID(),TENANT="endpoint-http-fixture-"+UUID.randomUUID(),SECRET="fixture-pinned-host-token";
 static Path registry,keyring;static HttpServer upstream;static AtomicInteger upstreamReads=new AtomicInteger();
 static boolean changeMetricAfterHistory,metricHistoryRead;
 static void setup(){try{if(registry!=null)return;
  upstream=HttpServer.create(new InetSocketAddress("127.0.0.1",0),0);upstream.createContext("/api_jsonrpc.php",e->{
   upstreamReads.incrementAndGet();var n=CatalogJson.JSON.readTree(e.getRequestBody().readAllBytes());String method=n.path("method").asText();Object result;
   if(method.equals("apiinfo.version")){assertNull(e.getRequestHeaders().getFirst("Authorization"));result="7.0.0";}
   else if(method.equals("history.get")){
    assertEquals("Bearer "+SECRET,e.getRequestHeaders().getFirst("Authorization"));var params=n.get("params");assertEquals(6,params.get("limit").asInt());assertEquals(0,params.get("history").asInt());assertEquals("20001",params.get("itemids").get(0).asString());metricHistoryRead=true;long till=params.get("time_till").asLong();result=List.of(Map.of("itemid","20001","clock",""+(till-1),"ns","0","value","12.5"),Map.of("itemid","20001","clock",""+(till-2),"ns","0","value","20"));
   }
   else if(method.equals("item.get")&&n.get("params").has("itemids")&&!n.get("params").has("templated")){
    assertEquals("Bearer "+SECRET,e.getRequestHeaders().getFirst("Authorization"));assertEquals("20001",n.get("params").get("itemids").get(0).asString());result=List.of(Map.of("itemid","20001","hostid",changeMetricAfterHistory&&metricHistoryRead?"102":"101","key_","system.cpu.util[,user]","units","%","value_type","0"));
   }
   else if(method.equals("item.get")&&(n.get("params").has("countOutput")||n.get("params").has("itemids")||n.get("params").path("limit").asInt()==1001)){
    assertEquals("Bearer "+SECRET,e.getRequestHeaders().getFirst("Authorization"));var params=n.get("params");assertFalse(params.get("templated").booleanValue());
    if(params.has("countOutput"))result="45";
    else if(params.has("itemids")){var rows=new ArrayList<Map<String,Object>>();for(var item:params.get("itemids"))rows.add(Map.of("itemid",item.asString(),"hostid","101","key_",item.asString().equals("1")?"system.cpu.util[,user]":"fixture.inventory.metric."+item.asString(),"name","Fixture metric "+item.asString(),"units","%","value_type","0"));result=rows;}
    else result=java.util.stream.IntStream.rangeClosed(1,45).mapToObj(v->Map.of("itemid",""+v)).toList();
   }
   else if(method.equals("item.get")){assertEquals("Bearer "+SECRET,e.getRequestHeaders().getFirst("Authorization"));var params=n.get("params");assertEquals(21,params.get("limit").asInt());assertFalse(params.get("templated").booleanValue());assertEquals(6,params.get("output").size());result=List.of(Map.of("itemid","20001","hostid","101","key_","system.cpu.util[,user]","name","Fixture CPU","value_type","0","units","%"),Map.of("itemid","20002","hostid","101","key_","fixture.unmapped","name","Fixture unmapped","value_type","5","units",""));}
   else {assertEquals("host.get",method);assertEquals("Bearer "+SECRET,e.getRequestHeaders().getFirst("Authorization"));var params=n.get("params");
     result=params.has("countOutput")?"1":params.has("hostids")?List.of(Map.of("hostid","101","groups",List.of(Map.of("groupid","1001")),"host","fixture-private-host","name","Fixture host","status","0","interfaces",List.of(Map.of("ip","192.0.2.7")))):List.of(Map.of("hostid","101","groups",List.of(Map.of("groupid","1001"))));
   }
   byte[] body=CatalogJson.JSON.writeValueAsString(Map.of("jsonrpc","2.0","id",1,"result",result)).getBytes(StandardCharsets.UTF_8);e.sendResponseHeaders(200,body.length);try(var out=e.getResponseBody()){out.write(body);}
  });upstream.start();
  registry=Files.writeString(Files.createTempFile("opsweave-endpoint-fixture-",".json"),CatalogJson.JSON.writeValueAsString(Map.of("schemaVersion","2.0","endpoints",List.of(Map.of("id","fixture-live","name","Fixture loopback upstream","connectorKind","ZABBIX_HOST","address","http://127.0.0.1:"+upstream.getAddress().getPort()+"/api_jsonrpc.php","tenants",List.of(TENANT)),Map.of("id","fixture-secondary","name","Fixture second registration","connectorKind","ZABBIX_HOST","address","https://192.0.2.10/api_jsonrpc.php","tenants",List.of(TENANT)),Map.of("id","fixture-foreign","name","Fixture foreign tenant","connectorKind","ZABBIX_HOST","address","https://192.0.2.11/api_jsonrpc.php","tenants",List.of("foreign-fixture"))))));
  keyring=Files.writeString(Files.createTempFile("opsweave-endpoint-fixture-keyring-",".json"),"{\"activeKeyId\":\"fixture-key\",\"keys\":{\"fixture-key\":\""+Base64.getEncoder().encodeToString(new byte[32])+"\"}}");
 }catch(Exception e){throw new IllegalStateException("Endpoint Fixture setup failed");}}
 @DynamicPropertySource static void properties(DynamicPropertyRegistry r){setup();r.add("opsweave.metrics.victoria-url",()->System.getenv("OPSWEAVE_TEST_VM_URL") == null ? "" : System.getenv("OPSWEAVE_TEST_VM_URL"));r.add("opsweave.auth.dev.token",()->TOKEN);r.add("opsweave.auth.dev.tenant",()->TENANT);r.add("opsweave.sources.endpoints-path",()->registry.toString());r.add("opsweave.credentials.keyring-path",()->keyring.toString());r.add("opsweave.inventory.jdbc-url",()->System.getenv("OPSWEAVE_TEST_JDBC_URL"));r.add("opsweave.inventory.jdbc-user",()->System.getenv("OPSWEAVE_TEST_JDBC_USER"));r.add("opsweave.inventory.jdbc-password",()->System.getenv("OPSWEAVE_TEST_JDBC_PASSWORD"));}
 @AfterAll static void cleanup()throws Exception{if(upstream!=null)upstream.stop(0);if(registry!=null)Files.deleteIfExists(registry);if(keyring!=null)Files.deleteIfExists(keyring);}
 @LocalServerPort int port;@Autowired RegisteredHostSourceReader reader;final HttpClient http=HttpClient.newHttpClient();
 Principal principal(){return new Principal(new SubjectId("endpoint-fixture-author"),new TenantId(TENANT),Set.of(Permission.SOURCE_SYNC,Permission.SOURCE_CONFIGURE),ResourceScope.tenantWide());}
 HttpResponse<String> call(String path,String method,Object body,boolean auth)throws Exception{var b=HttpRequest.newBuilder(URI.create("http://127.0.0.1:"+port+path)).timeout(Duration.ofSeconds(15));if(auth)b.header("Authorization","Bearer "+TOKEN);if(body!=null)b.header("Content-Type","application/json");b.method(method,body==null?HttpRequest.BodyPublishers.noBody():HttpRequest.BodyPublishers.ofString(CatalogJson.JSON.writeValueAsString(body)));return http.send(b.build(),HttpResponse.BodyHandlers.ofString());}
 SourceEndpoint.Pin endpoint()throws Exception{var n=CatalogJson.JSON.readTree(call("/api/v2/data-sources/endpoints/fixture-live","GET",null,true).body()).get("endpoint");return new SourceEndpoint.Pin(n.get("id").asText(),n.get("digest").asText());}
 @Autowired com.acme.opsweave.platform.workflow.WorkflowRuntimeController runtime;
 @Test void fixedHostControlReadsRegisteredSourceAndPersistsConfirmedScanMetadata()throws Exception{
  var credential=UUID.randomUUID();assertEquals(200,call("/api/v2/data-sources/credentials","POST",Map.of("requestId",credential,"name","Fixture host runtime credential","secret",SECRET),true).statusCode());
   var id=UUID.randomUUID();var created=call("/api/v2/data-sources/connections","POST",Map.of("requestId",id,"name","Fixture host runtime source","description","Synthetic upstream and actual durable Host batches","endpointPin",endpoint(),"credentialPin",new SourceCredential.Pin(credential,1,credential),"hostGroupIds",List.of("1001")),true);assertEquals(200,created.statusCode(),created.body());
  var instance=CatalogJson.JSON.readTree(created.body()).get("receipt").get("instance");var model=new com.acme.opsweave.platform.catalog.BuiltinCatalog().definitions().stream().filter(m->m.id().equals("builtin.host")).findFirst().orElseThrow();
  var source=new WorkflowDefinition.Source("ZABBIX_HOST",instance.get("source").get("instanceId").asString(),new WorkflowDefinition.ConfigurationPin(id,1,instance.get("connectionDigest").asString()));
  var nodes=List.of(new WorkflowDefinition.Node("source",WorkflowDefinition.Type.SOURCE,"1",Map.of()),new WorkflowDefinition.Node("map",WorkflowDefinition.Type.MAP,"1",Map.of("name","hostname","ip","ip")),new WorkflowDefinition.Node("validate",WorkflowDefinition.Type.VALIDATE,"1",Map.of()),new WorkflowDefinition.Node("output",WorkflowDefinition.Type.OUTPUT,"1",Map.of()));
  var d=WorkflowOperators.builtIn().pin(new WorkflowDefinition("host-"+UUID.randomUUID(),1,"Fixture fixed Host runtime",source,new WorkflowDefinition.Target(model.id(),1,model.digest()),nodes,List.of(new WorkflowDefinition.Edge("source","map"),new WorkflowDefinition.Edge("map","validate"),new WorkflowDefinition.Edge("validate","output"))));
  var layout=new LinkedHashMap<String,Object>();for(var node:d.nodes())layout.put(node.id(),Map.of("x",0,"y",0));String flows="/api/v1/integrations/workflows";
  assertEquals(200,call(flows+"/drafts","POST",Map.of("definition",com.acme.opsweave.platform.workflow.WorkflowJson.wire(d),"layout",layout,"expectedEditVersion",0),true).statusCode());
  var preview=call(flows+"/preview","POST",Map.of("id",d.id(),"revision",1,"editVersion",1,"digest",d.digest(),"dryRun",true),true);assertEquals(200,preview.statusCode(),preview.body());var proof=CatalogJson.JSON.readTree(preview.body()).get("receipt").get("id").asString();assertEquals(200,call(flows+"/publish","POST",Map.of("id",d.id(),"revision",1,"editVersion",1,"digest",d.digest(),"previewId",proof),true).statusCode());
  var command=Map.of("requestId",UUID.randomUUID(),"id",d.id(),"revision",1,"digest",d.digest(),"settings",Map.of("identityField","entity_id","nameField","hostname"),"expectedGeneration",0);int before=upstreamReads.get();var started=call(flows+"/runtime/start","POST",command,true);assertEquals(200,started.statusCode(),started.body());runtime.poll();
  var status=call(flows+"/runtime/host-scans/"+d.id(),"GET",null,true);assertEquals(200,status.statusCode(),status.body());var result=CatalogJson.JSON.readTree(status.body());assertTrue(result.get("checkpoint").get("complete").asBoolean());assertEquals(1,result.get("checkpoint").get("confirmedRecords").asInt());assertEquals("CONFIRMED",result.get("batches").get(0).get("state").asString());assertEquals(1,result.get("batches").get(0).get("entityIds").size());assertFalse(status.body().contains("fixture-private-host"));assertFalse(result.get("checkpoint").has("nextCursor"));assertFalse(result.get("batches").get(0).has("records"));
  int reads=upstreamReads.get();assertTrue(reads>before);runtime.poll();assertEquals(reads,upstreamReads.get());assertEquals(started.body(),call(flows+"/runtime/start","POST",command,true).body());assertEquals(reads,upstreamReads.get());assertEquals(400,call(flows+"/runtime/host-scans/"+d.id()+"?tenantId=forged","GET",null,true).statusCode());assertEquals(401,call(flows+"/runtime/host-scans/"+d.id(),"GET",null,false).statusCode());
 }
 @Test void fixedRawMetricSelectionPreviewPublishAndPostReadDriftArePersistedWithoutBusinessWrites()throws Exception{
  var credential=UUID.randomUUID();assertEquals(200,call("/api/v2/data-sources/credentials","POST",Map.of("requestId",credential,"name","Fixture metric credential","secret",SECRET),true).statusCode());
   var id=UUID.randomUUID();var created=call("/api/v2/data-sources/connections","POST",Map.of("requestId",id,"name","Fixture raw metric source","description","Synthetic HTTP source and PG receipt","endpointPin",endpoint(),"credentialPin",new SourceCredential.Pin(credential,1,credential),"hostGroupIds",List.of("1001")),true);assertEquals(200,created.statusCode(),created.body());
  var instance=CatalogJson.JSON.readTree(created.body()).get("receipt").get("instance");String base="/api/v2/data-sources/"+id,choices=base+"/connection/1/workflow-metrics";
  int before=upstreamReads.get();assertEquals(0,CatalogJson.JSON.readTree(call(choices,"GET",null,true).body()).get("items").size());assertEquals(before,upstreamReads.get());assertEquals(401,call(choices,"GET",null,false).statusCode());assertEquals(400,call(choices+"?tenantId=forged","GET",null,true).statusCode());
   var discovery=call(base+"/discover-metrics","POST",Map.of("requestId",UUID.randomUUID(),"configurationRevision",1,"connectionDigest",instance.get("connectionDigest").asString()),true);assertEquals(200,discovery.statusCode(),discovery.body());assertEquals(before+3,upstreamReads.get());
   var response=call(choices,"GET",null,true);assertEquals(200,response.statusCode(),response.body());assertEquals("no-store",response.headers().firstValue("Cache-Control").orElse(""));assertFalse(response.body().contains(SECRET));var selected=CatalogJson.JSON.readTree(response.body()).get("items");assertEquals(1,selected.size());assertEquals(before+3,upstreamReads.get());
  var source=com.acme.opsweave.platform.workflow.WorkflowJson.source(selected.get(0).get("source"));var registry=com.acme.opsweave.integration.infrastructure.ClasspathMappingCatalog.load(getClass().getClassLoader());var mapping=registry.find("zabbix",source.metric().sourceKey()).orElseThrow();
  var nodes=List.of(new WorkflowDefinition.Node("source",WorkflowDefinition.Type.SOURCE,"1",Map.of()),new WorkflowDefinition.Node("mapping",WorkflowDefinition.Type.MAP,"1",Map.of("timestamp","timestamp","sourceKey","sourceKey","value","value")),new WorkflowDefinition.Node("validate",WorkflowDefinition.Type.VALIDATE,"1",Map.of()),new WorkflowDefinition.Node("output",WorkflowDefinition.Type.OUTPUT,"1",Map.of()));
  var d=WorkflowOperators.builtIn().pin(new WorkflowDefinition("raw-"+UUID.randomUUID(),1,"Fixture raw metric workflow",source,new WorkflowDefinition.Target(null,1,null,"METRIC",mapping.pin(),mapping.metricKey()),nodes,List.of(new WorkflowDefinition.Edge("source","mapping"),new WorkflowDefinition.Edge("mapping","validate"),new WorkflowDefinition.Edge("validate","output"))));
   var layout=new LinkedHashMap<String,Object>();for(var node:d.nodes())layout.put(node.id(),Map.of("x",0,"y",0));String workflows="/api/v1/integrations/workflows";var save=call(workflows+"/drafts","POST",Map.of("definition",com.acme.opsweave.platform.workflow.WorkflowJson.wire(d),"layout",layout,"expectedEditVersion",0),true);assertEquals(200,save.statusCode(),save.body());assertEquals(before+3,upstreamReads.get());
   var command=new LinkedHashMap<String,Object>(Map.of("id",d.id(),"revision",1,"editVersion",1,"digest",d.digest(),"dryRun",true));var preview=call(workflows+"/preview","POST",command,true);assertEquals(200,preview.statusCode(),preview.body());assertEquals(before+8,upstreamReads.get());var result=CatalogJson.JSON.readTree(preview.body());assertEquals(2,result.get("receipt").get("accepted").asInt());assertFalse(result.get("evaluation").get("writesPerformed").asBoolean());assertEquals("0.125",result.get("evaluation").get("rows").get(1).get("steps").get(3).get("values").get("value").asString());assertEquals("12.5",result.get("evaluation").get("rows").get(1).get("steps").get(0).get("values").get("value").asString());
   String receipt=result.get("receipt").get("id").asString();assertTrue(call(workflows+"/runs/"+receipt,"GET",null,true).body().contains(source.metric().digest()));var publish=Map.of("id",d.id(),"revision",1,"editVersion",1,"digest",d.digest(),"previewId",receipt);assertEquals(200,call(workflows+"/publish","POST",publish,true).statusCode());assertEquals(before+8,upstreamReads.get());assertEquals(d,com.acme.opsweave.platform.workflow.WorkflowJson.decode(call(workflows+"/versions/"+d.id()+"/1","GET",null,true).body()).definition());
   for(String field:List.of("samples","syncRunId")){var forged=new LinkedHashMap<>(command);forged.put(field,field.equals("samples")?List.of(Map.of("value","99")):UUID.randomUUID());assertEquals(400,call(workflows+"/preview","POST",forged,true).statusCode());}assertEquals(before+8,upstreamReads.get());
  var pageBefore=CatalogJson.JSON.readTree(call(workflows,"GET",null,true).body()).get("runs");
   try{metricHistoryRead=false;changeMetricAfterHistory=true;command.put("editVersion",0);var failed=call(workflows+"/run","POST",command,true);assertEquals(409,failed.statusCode(),failed.body());assertEquals("SOURCE_CHANGED",CatalogJson.JSON.readTree(failed.body()).get("error").asString());assertEquals(before+11,upstreamReads.get());assertEquals(pageBefore,CatalogJson.JSON.readTree(call(workflows,"GET",null,true).body()).get("runs"));}finally{changeMetricAfterHistory=false;metricHistoryRead=false;}
   assertEquals(200,call("/api/v2/data-sources/credentials/"+credential+"/versions/1/revoke","POST",Map.of("requestId",UUID.randomUUID(),"expectedEditVersion",1),true).statusCode());assertEquals(503,call(choices,"GET",null,true).statusCode());assertEquals(200,call(workflows+"/versions/"+d.id()+"/1","GET",null,true).statusCode());assertEquals(503,call(workflows+"/run","POST",command,true).statusCode());assertEquals(before+11,upstreamReads.get());
 }
 @Test @EnabledIfEnvironmentVariable(named="OPSWEAVE_TEST_VM_URL",matches=".+")
 void fixedMetricSampleWritesRealTimeSeriesAndOriginalReceiptSurvivesNewReads()throws Exception {
  var credential=UUID.randomUUID();assertEquals(200,call("/api/v2/data-sources/credentials","POST",Map.of("requestId",credential,"name","Fixture metric output credential","secret",SECRET),true).statusCode());
   var sourceId=UUID.randomUUID();var created=call("/api/v2/data-sources/connections","POST",Map.of("requestId",sourceId,"name","Fixture metric output source","description","Synthetic upstream, actual PG and time-series","endpointPin",endpoint(),"credentialPin",new SourceCredential.Pin(credential,1,credential),"hostGroupIds",List.of("1001")),true);assertEquals(200,created.statusCode(),created.body());
  var instance=CatalogJson.JSON.readTree(created.body()).get("receipt").get("instance");String base="/api/v2/data-sources/"+sourceId;
  assertEquals(200,call(base+"/discover-metrics","POST",Map.of("requestId",UUID.randomUUID(),"configurationRevision",1,"connectionDigest",instance.get("connectionDigest").asString()),true).statusCode());
  var source=com.acme.opsweave.platform.workflow.WorkflowJson.source(CatalogJson.JSON.readTree(call(base+"/connection/1/workflow-metrics","GET",null,true).body()).get("items").get(0).get("source"));
  var mapping=com.acme.opsweave.integration.infrastructure.ClasspathMappingCatalog.load(getClass().getClassLoader()).find("zabbix",source.metric().sourceKey()).orElseThrow();
  var nodes=List.of(new WorkflowDefinition.Node("source",WorkflowDefinition.Type.SOURCE,"1",Map.of()),new WorkflowDefinition.Node("mapping",WorkflowDefinition.Type.MAP,"1",Map.of("timestamp","timestamp","sourceKey","sourceKey","value","value")),new WorkflowDefinition.Node("validate",WorkflowDefinition.Type.VALIDATE,"1",Map.of()),new WorkflowDefinition.Node("output",WorkflowDefinition.Type.OUTPUT,"1",Map.of()));
  var d=WorkflowOperators.builtIn().pin(new WorkflowDefinition("output-"+UUID.randomUUID(),1,"Fixture metric output",source,new WorkflowDefinition.Target(null,1,null,"METRIC",mapping.pin(),mapping.metricKey()),nodes,List.of(new WorkflowDefinition.Edge("source","mapping"),new WorkflowDefinition.Edge("mapping","validate"),new WorkflowDefinition.Edge("validate","output"))));
  var layout=new LinkedHashMap<String,Object>();for(var node:nodes)layout.put(node.id(),Map.of("x",0,"y",0));String wf="/api/v1/integrations/workflows",outputs=wf+"/metric-outputs";
  assertEquals(200,call(wf+"/drafts","POST",Map.of("definition",com.acme.opsweave.platform.workflow.WorkflowJson.wire(d),"layout",layout,"expectedEditVersion",0),true).statusCode());
  var preview=CatalogJson.JSON.readTree(call(wf+"/preview","POST",Map.of("id",d.id(),"revision",1,"editVersion",1,"digest",d.digest(),"dryRun",true),true).body());
  assertEquals(200,call(wf+"/publish","POST",Map.of("id",d.id(),"revision",1,"editVersion",1,"digest",d.digest(),"previewId",preview.get("receipt").get("id").asString()),true).statusCode());
  var runResponse=call(wf+"/run","POST",Map.of("id",d.id(),"revision",1,"editVersion",0,"digest",d.digest(),"dryRun",true),true);assertEquals(200,runResponse.statusCode(),runResponse.body());var run=CatalogJson.JSON.readTree(runResponse.body());
  var samples=new ArrayList<Map<String,Object>>();for(var row:run.get("evaluation").get("rows")){var values=row.get("steps").get(0).get("values");samples.add(Map.of("timestamp",values.get("timestamp").asString(),"sourceKey",values.get("sourceKey").asString(),"value",values.get("value").asString()));}
  var requestId=UUID.randomUUID();var command=Map.<String,Object>of("requestId",requestId,"id",d.id(),"revision",1,"digest",d.digest(),"previewId",run.get("receipt").get("id").asString(),"samples",samples);
  int before=upstreamReads.get();assertTrue(CatalogJson.JSON.readTree(call(outputs,"GET",null,true).body()).get("available").asBoolean());
  var response=call(outputs,"POST",command,true);assertEquals(200,response.statusCode(),response.body());var receipt=CatalogJson.JSON.readTree(response.body());assertFalse(receipt.has("samples"));assertFalse(receipt.has("values"));assertFalse(receipt.toString().contains(SECRET));
  for(int i=0;i<100&&!receipt.get("state").asString().equals("CONFIRMED");i++){assertEquals("UNKNOWN",receipt.get("state").asString(),receipt.toString());Thread.sleep(200);var check=call(outputs+"/commands/"+requestId+"/verification","GET",null,true);assertEquals(200,check.statusCode(),check.body());receipt=CatalogJson.JSON.readTree(check.body());}
  assertEquals("CONFIRMED",receipt.get("state").asString(),receipt.toString());assertEquals(2,receipt.get("confirmed").asInt());assertEquals(0,receipt.get("unknown").asInt());assertEquals(before,upstreamReads.get());
  var points=call(outputs+"/commands/"+requestId+"/points","GET",null,true);assertEquals(200,points.statusCode(),points.body());var data=CatalogJson.JSON.readTree(points.body());assertTrue(data.get("proofMatches").asBoolean());assertEquals("0.2",data.get("points").get(0).get("value").asString());assertEquals("0.125",data.get("points").get(1).get("value").asString());
  assertEquals(receipt,CatalogJson.JSON.readTree(call(outputs,"POST",command,true).body()));assertEquals(receipt,CatalogJson.JSON.readTree(call(outputs+"/commands/"+requestId,"GET",null,true).body()));assertEquals(before,upstreamReads.get());
  var changed=new LinkedHashMap<>(command);changed.put("previewId",UUID.randomUUID());assertEquals(409,call(outputs,"POST",changed,true).statusCode());assertEquals(401,call(outputs+"/commands/"+requestId,"GET",null,false).statusCode());assertEquals(400,call(outputs+"/commands/"+requestId+"?tenantId=forged","GET",null,true).statusCode());
  var page=CatalogJson.JSON.readTree(call(outputs+"/workflows/"+d.id()+"/receipts","GET",null,true).body());assertEquals(receipt,page.get("items").get(0));assertFalse(page.get("truncated").asBoolean());
  assertEquals(200,call("/api/v2/data-sources/credentials/"+credential+"/versions/1/revoke","POST",Map.of("requestId",UUID.randomUUID(),"expectedEditVersion",1),true).statusCode());assertEquals(receipt,CatalogJson.JSON.readTree(call(outputs+"/commands/"+requestId,"GET",null,true).body()));assertEquals(receipt,CatalogJson.JSON.readTree(call(outputs,"POST",command,true).body()));assertEquals(before,upstreamReads.get());
 }
 @Test void endpointReadsAreScopedClosedAndHaveNoNetworkSideEffects()throws Exception{
  int before=upstreamReads.get();assertEquals(401,call("/api/v2/data-sources/endpoints","GET",null,false).statusCode());var response=call("/api/v2/data-sources/endpoints","GET",null,true);assertEquals(200,response.statusCode());assertEquals("no-store",response.headers().firstValue("Cache-Control").orElse(""));var page=CatalogJson.JSON.readTree(response.body());assertEquals(2,page.get("items").size());assertFalse(response.body().contains("fixture-foreign"));for(String field:List.of("secret","credentialId","tenants","Authorization"))assertFalse(response.body().contains('"'+field+'"'));assertEquals(404,call("/api/v2/data-sources/endpoints/fixture-foreign","GET",null,true).statusCode());assertEquals(400,call("/api/v2/data-sources/endpoints?tenantId=forged","GET",null,true).statusCode());assertEquals(400,call("/api/v2/data-sources/endpoints/UPPER","GET",null,true).statusCode());assertEquals(401,call("/api/v2/data-sources/endpoints/fixture-live","POST",Map.of("address","https://192.0.2.1/api_jsonrpc.php"),true).statusCode());assertEquals(before,upstreamReads.get());
 }
 @Test void persistedPublicConnectionPinsDriveInspectionAndKeepOriginalReceipts()throws Exception{
   var credentialId=UUID.randomUUID();assertEquals(200,call("/api/v2/data-sources/credentials","POST",Map.of("requestId",credentialId,"name","Fixture connection binding credential","secret",SECRET),true).statusCode());var ep=endpoint();var pin=new SourceCredential.Pin(credentialId,1,credentialId);var id=UUID.randomUUID();var create=Map.of("requestId",id,"name","Fixture public connection","description","Synthetic HTTP/PG acceptance","endpointPin",ep,"credentialPin",pin,"hostGroupIds",List.of("1001"));int before=upstreamReads.get();
  var first=call("/api/v2/data-sources/connections","POST",create,true);assertEquals(200,first.statusCode(),first.body());assertFalse(first.body().contains(SECRET));var snapshot=CatalogJson.JSON.readTree(first.body());var instance=snapshot.get("receipt").get("instance");assertEquals("connection-"+id,instance.get("source").get("instanceId").asText());assertEquals(before,upstreamReads.get());assertEquals(snapshot,CatalogJson.JSON.readTree(call("/api/v2/data-sources/connections","POST",create,true).body()));assertEquals(1,CatalogJson.JSON.readTree(call("/api/v2/data-sources/"+id+"/connection/history","GET",null,true).body()).get("items").size());
  var testId=UUID.randomUUID();var test=Map.of("requestId",testId,"configurationRevision",1,"connectionDigest",instance.get("connectionDigest").asText());var tested=call("/api/v2/data-sources/"+id+"/test","POST",test,true);assertEquals(200,tested.statusCode(),tested.body());var result=CatalogJson.JSON.readTree(tested.body()).get("view");assertEquals("CURRENT",result.get("validity").asText());assertTrue(result.get("inspection").get("check").get("reachable").booleanValue());assertTrue(upstreamReads.get()>before);int afterTest=upstreamReads.get();assertEquals(200,call("/api/v2/data-sources/"+id+"/test","POST",test,true).statusCode());assertEquals(afterTest,upstreamReads.get());
  var rotateId=UUID.randomUUID();assertEquals(200,call("/api/v2/data-sources/credentials/"+credentialId,"PATCH",Map.of("requestId",rotateId,"expectedEditVersion",1,"name","Fixture connection binding credential","state","ACTIVE","secret",SECRET),true).statusCode());assertEquals("AVAILABLE",CatalogJson.JSON.readTree(call("/api/v2/data-sources/"+id+"/connection","GET",null,true).body()).get("availability").asText());
   var editId=UUID.randomUUID();var edit=Map.of("requestId",editId,"expectedEditVersion",1,"name","Fixture connection updated","description","Synthetic HTTP/PG acceptance","endpointPin",ep,"credentialPin",new SourceCredential.Pin(credentialId,2,rotateId),"hostGroupIds",List.of("1001"));var changed=call("/api/v2/data-sources/"+id+"/connection","PATCH",edit,true);assertEquals(200,changed.statusCode(),changed.body());var latest=CatalogJson.JSON.readTree(changed.body());assertEquals(2,latest.get("connection").get("revision").asInt());assertEquals("STALE",CatalogJson.JSON.readTree(call("/api/v2/data-sources/"+id+"/inspections/"+testId,"GET",null,true).body()).get("view").get("validity").asText());assertEquals(snapshot,CatalogJson.JSON.readTree(call("/api/v2/data-sources/"+id+"/connection/commands/"+id,"GET",null,true).body()));assertEquals(snapshot,CatalogJson.JSON.readTree(call("/api/v2/data-sources/connections","POST",create,true).body()));assertEquals(2,CatalogJson.JSON.readTree(call("/api/v2/data-sources/"+id+"/connection/history","GET",null,true).body()).get("items").size());
  assertEquals(409,call("/api/v2/data-sources/"+id+"/connection","PATCH",Map.of("requestId",UUID.randomUUID(),"expectedEditVersion",1,"name","Fixture stale update","description","","endpointPin",ep,"credentialPin",pin),true).statusCode());assertEquals(afterTest,upstreamReads.get());
  var discoveryId=UUID.randomUUID();var discovery=call("/api/v2/data-sources/"+id+"/discover","POST",Map.of("requestId",discoveryId,"configurationRevision",2,"connectionDigest",latest.get("connection").get("connectionDigest").asText()),true);assertEquals(200,discovery.statusCode(),discovery.body());var d=CatalogJson.JSON.readTree(discovery.body()).get("view");assertEquals("CURRENT",d.get("validity").asText());assertEquals(5,d.get("inspection").get("discovery").get("fields").size());assertFalse(discovery.body().contains("fixture-private-host"));assertFalse(discovery.body().contains("192.0.2.7"));
  int beforeMetrics=upstreamReads.get();var metricId=UUID.randomUUID();var metricCommand=Map.of("requestId",metricId,"configurationRevision",2,"connectionDigest",latest.get("connection").get("connectionDigest").asText());var metrics=call("/api/v2/data-sources/"+id+"/discover-metrics","POST",metricCommand,true);assertEquals(200,metrics.statusCode(),metrics.body());var mv=CatalogJson.JSON.readTree(metrics.body()).get("view");assertEquals("CURRENT",mv.get("validity").asText());var md=mv.get("inspection").get("metricDiscovery");assertEquals("FIRST_PAGE_MATCH",md.get("scanConsistency").asText());assertEquals(2,md.get("items").size());assertEquals("host.cpu.usage.user",md.get("items").get(0).get("mapping").get("metricKey").asText());assertEquals("NO_MAPPING",md.get("items").get(1).get("mappingStatus").asText());assertEquals(beforeMetrics+2,upstreamReads.get());assertFalse(metrics.body().contains(SECRET));assertEquals(CatalogJson.JSON.readTree(metrics.body()),CatalogJson.JSON.readTree(call("/api/v2/data-sources/"+id+"/discover-metrics","POST",metricCommand,true).body()));assertEquals(beforeMetrics+2,upstreamReads.get());
  int afterDiscovery=upstreamReads.get();assertEquals(200,call("/api/v2/data-sources/credentials/"+credentialId+"/versions/2/revoke","POST",Map.of("requestId",UUID.randomUUID(),"expectedEditVersion",2),true).statusCode());assertEquals("UNAVAILABLE",CatalogJson.JSON.readTree(call("/api/v2/data-sources/"+id+"/connection","GET",null,true).body()).get("availability").asText());assertEquals("STALE",CatalogJson.JSON.readTree(call("/api/v2/data-sources/"+id+"/inspections/"+discoveryId,"GET",null,true).body()).get("view").get("validity").asText());assertEquals(latest,CatalogJson.JSON.readTree(call("/api/v2/data-sources/"+id+"/connection/commands/"+editId,"GET",null,true).body()));assertEquals("STALE",CatalogJson.JSON.readTree(call("/api/v2/data-sources/"+id+"/inspections/"+metricId,"GET",null,true).body()).get("view").get("validity").asText());assertEquals(503,call("/api/v2/data-sources/"+id+"/discover-metrics","POST",Map.of("requestId",UUID.randomUUID(),"configurationRevision",2,"connectionDigest",latest.get("connection").get("connectionDigest").asText()),true).statusCode());assertEquals(afterDiscovery,upstreamReads.get());
 }
 @Test void metricInventoryPagesPersistAcrossHttpReadsAndRevocationStopsContinuation()throws Exception{
  var credentialId=UUID.randomUUID();assertEquals(200,call("/api/v2/data-sources/credentials","POST",Map.of("requestId",credentialId,"name","Fixture inventory credential","secret",SECRET),true).statusCode());
   var id=UUID.randomUUID();var create=call("/api/v2/data-sources/connections","POST",Map.of("requestId",id,"name","Fixture inventory source","description","Synthetic 45-item source","endpointPin",endpoint(),"credentialPin",new SourceCredential.Pin(credentialId,1,credentialId),"hostGroupIds",List.of("1001")),true);
  assertEquals(200,create.statusCode(),create.body());String digest=CatalogJson.JSON.readTree(create.body()).get("receipt").get("instance").get("connectionDigest").asString(),base="/api/v2/data-sources/"+id;
  var command=new LinkedHashMap<String,Object>();command.put("requestId",UUID.randomUUID());command.put("configurationRevision",1);command.put("connectionDigest",digest);command.put("previousRequestId",null);
  int before=upstreamReads.get();assertEquals(401,call(base+"/metric-discoveries","POST",command,false).statusCode());
  for(var field:List.of("offset","cursor","itemids","tenantId","url","credentialPin")){var bad=new LinkedHashMap<>(command);bad.put(field,"forged");assertEquals(400,call(base+"/metric-discoveries","POST",bad,true).statusCode());}
  assertEquals(400,call(base+"/metric-discoveries?offset=20","POST",command,true).statusCode());assertEquals(before,upstreamReads.get());
  Object previous=null;String root=null;
  for(int page=0;page<3;page++){
   command.put("requestId",UUID.randomUUID());command.put("previousRequestId",previous);var response=call(base+"/metric-discoveries","POST",command,true);assertEquals(200,response.statusCode(),response.body());var receipt=CatalogJson.JSON.readTree(response.body());var inspection=receipt.get("view").get("inspection");var result=inspection.get("metricPage");
   assertEquals("CURRENT",receipt.get("view").get("validity").asString());assertEquals(page*20,result.get("offset").asInt());assertEquals(page==2?5:20,result.get("items").size());assertEquals(page==2,result.get("complete").booleanValue());assertEquals(45,result.get("manifest").get("total").asInt());assertEquals(before+6*(page+1),upstreamReads.get());assertFalse(response.body().contains("metricMembership"));assertFalse(response.body().contains("itemIds"));assertFalse(response.body().contains(SECRET));
   if(root==null)root=result.get("manifest").get("snapshotId").asString();assertEquals(root,result.get("manifest").get("snapshotId").asString());
   assertEquals(receipt,CatalogJson.JSON.readTree(call(base+"/inspections/"+command.get("requestId"),"GET",null,true).body()));assertEquals(receipt,CatalogJson.JSON.readTree(call(base+"/metric-discoveries","POST",command,true).body()));assertEquals(before+6*(page+1),upstreamReads.get());previous=command.get("requestId");
  }
  command.put("requestId",UUID.randomUUID());command.put("previousRequestId",previous);assertEquals(409,call(base+"/metric-discoveries","POST",command,true).statusCode());assertEquals(before+18,upstreamReads.get());
  command.put("previousRequestId",null);var first=call(base+"/metric-discoveries","POST",command,true);assertEquals(200,first.statusCode(),first.body());Object lastRoot=command.get("requestId");int after=upstreamReads.get();
  assertEquals(200,call("/api/v2/data-sources/credentials/"+credentialId+"/versions/1/revoke","POST",Map.of("requestId",UUID.randomUUID(),"expectedEditVersion",1),true).statusCode());
  assertEquals("STALE",CatalogJson.JSON.readTree(call(base+"/inspections/"+lastRoot,"GET",null,true).body()).get("view").get("validity").asString());command.put("requestId",UUID.randomUUID());command.put("previousRequestId",lastRoot);assertEquals(503,call(base+"/metric-discoveries","POST",command,true).statusCode());assertEquals(after,upstreamReads.get());
 }
 @Test void publicConnectionCommandsRejectInjectedIdentityAndNetworkFieldsWithoutIo()throws Exception{
   var id=UUID.randomUUID();var base=new LinkedHashMap<String,Object>(Map.of("requestId",id,"name","Fixture closed connection","description","","endpointPin",endpoint(),"credentialPin",new SourceCredential.Pin(UUID.randomUUID(),1,UUID.randomUUID()),"hostGroupIds",List.of("1001")));int before=upstreamReads.get();
  assertEquals(401,call("/api/v2/data-sources/connections","POST",base,false).statusCode());
  for(String field:List.of("address","secret","tenantId","userId","Authorization","permissions","workflowId")){var forged=new LinkedHashMap<>(base);forged.put(field,"fixture-forged");assertEquals(400,call("/api/v2/data-sources/connections","POST",forged,true).statusCode());}
  var forged=new LinkedHashMap<>(base);forged.put("endpointPin",Map.of("id","fixture-live","digest",endpoint().digest(),"address","http://127.0.0.1:1/api_jsonrpc.php"));assertEquals(400,call("/api/v2/data-sources/connections","POST",forged,true).statusCode());assertEquals(400,call("/api/v2/data-sources/connections?tenantId=fixture","POST",base,true).statusCode());assertEquals(before,upstreamReads.get());assertEquals(404,call("/api/v2/data-sources/"+id+"/connection","GET",null,true).statusCode());
 }
 @Test void actualJsonRpcReadUsesFixedCredentialAcrossRotationAndRechecksRevocation()throws Exception{
  var id=UUID.randomUUID();var create=call("/api/v2/data-sources/credentials","POST",Map.of("requestId",id,"name","Fixture pinned endpoint credential","secret",SECRET),true);assertEquals(200,create.statusCode(),create.body());var pin=new SourceCredential.Pin(id,1,id);var ep=endpoint();var p=principal();
   var groups=List.of("1001");var result=reader.read(p,"fixture-managed-source",ep,pin,groups,"TEST");assertTrue(result.check().reachable());assertEquals("READ_VERIFIED",result.check().statusCode());assertEquals("7.0.0",result.check().reportedVersion());var discovery=reader.read(p,"fixture-managed-source",ep,pin,groups,"DISCOVER").discovery();assertTrue(discovery.complete());assertEquals(1,discovery.observedRecords());assertEquals(5,discovery.fields().size());assertFalse(discovery.toString().contains("fixture-private-host"));assertFalse(discovery.toString().contains("192.0.2.7"));
   var rotate=new LinkedHashMap<String,Object>();rotate.put("requestId",UUID.randomUUID());rotate.put("expectedEditVersion",1);rotate.put("name","Fixture pinned endpoint credential");rotate.put("state","ACTIVE");rotate.put("secret","fixture-unused-rotated-token");assertEquals(200,call("/api/v2/data-sources/credentials/"+id,"PATCH",rotate,true).statusCode());assertTrue(reader.read(p,"fixture-managed-source",ep,pin,groups,"TEST").check().reachable());
   int before=upstreamReads.get();assertThrows(WorkflowFailure.class,()->reader.read(p,"fixture-managed-source",new SourceEndpoint.Pin(ep.id(),"sha256:"+"0".repeat(64)),pin,groups,"TEST"));var scoped=new Principal(p.subjectId(),p.tenantId(),p.permissions(),ResourceScope.of(Set.of(new ResourceRef(p.tenantId(),"source-endpoint",ep.id()),new ResourceRef(p.tenantId(),"credential",id.toString()))));assertEquals(WorkflowFailure.Code.FORBIDDEN,assertThrows(WorkflowFailure.class,()->reader.read(scoped,"fixture-managed-source",ep,pin,groups,"TEST")).code());assertEquals(before,upstreamReads.get());
   assertEquals(200,call("/api/v2/data-sources/credentials/"+id+"/versions/1/revoke","POST",Map.of("requestId",UUID.randomUUID(),"expectedEditVersion",2),true).statusCode());assertEquals(SourceCredentialFailure.Code.CONFLICT,assertThrows(SourceCredentialFailure.class,()->reader.read(p,"fixture-managed-source",ep,pin,groups,"DISCOVER")).code());assertEquals(before,upstreamReads.get());
 }
 @Test void fixedWorkflowPublishesAndReadsOriginalConfigurationAfterRotation()throws Exception{
  var credentialId=UUID.randomUUID();assertEquals(200,call("/api/v2/data-sources/credentials","POST",Map.of("requestId",credentialId,"name","Fixture workflow credential","secret",SECRET),true).statusCode());
   var sourceId=UUID.randomUUID();var create=call("/api/v2/data-sources/connections","POST",Map.of("requestId",sourceId,"name","Fixture workflow source","description","","endpointPin",endpoint(),"credentialPin",new SourceCredential.Pin(credentialId,1,credentialId),"hostGroupIds",List.of("1001")),true);assertEquals(200,create.statusCode(),create.body());var connection=CatalogJson.JSON.readTree(create.body()).get("connection");String digest=connection.get("connectionDigest").asString();
  var model=new com.acme.opsweave.platform.catalog.BuiltinCatalog().definitions().stream().filter(m->m.id().equals("builtin.host")).findFirst().orElseThrow();var mapping=new LinkedHashMap<String,String>();for(var f:model.fields()){if(f.id().equals("name")||f.id().equals("hostname"))mapping.put("name",f.id());else if(Set.of("ip","lifecycle","entity_id").contains(f.id()))mapping.put(f.id(),f.id());}
  var nodes=List.of(new WorkflowDefinition.Node("source",WorkflowDefinition.Type.SOURCE,"1",Map.of()),new WorkflowDefinition.Node("mapping",WorkflowDefinition.Type.MAP,"1",mapping),new WorkflowDefinition.Node("validate",WorkflowDefinition.Type.VALIDATE,"1",Map.of()),new WorkflowDefinition.Node("output",WorkflowDefinition.Type.OUTPUT,"1",Map.of()));
  String id="fixture-"+UUID.randomUUID();var source=new WorkflowDefinition.Source("ZABBIX_HOST",SourceConnectionConfiguration.physicalId(sourceId),new WorkflowDefinition.ConfigurationPin(sourceId,1,digest));var d=com.acme.opsweave.integration.domain.WorkflowOperators.builtIn().pin(new WorkflowDefinition(id,1,"Fixture fixed workflow",source,new WorkflowDefinition.Target(model.id(),model.revision(),model.digest()),nodes,List.of(new WorkflowDefinition.Edge("source","mapping"),new WorkflowDefinition.Edge("mapping","validate"),new WorkflowDefinition.Edge("validate","output"))));var layout=new LinkedHashMap<String,Object>();for(int i=0;i<nodes.size();i++)layout.put(nodes.get(i).id(),Map.of("x",i*200,"y",100));var wire=com.acme.opsweave.platform.workflow.WorkflowJson.wire(d);
  int before=upstreamReads.get();var save=call("/api/v1/integrations/workflows/drafts","POST",Map.of("definition",wire,"layout",layout,"expectedEditVersion",0),true);assertEquals(200,save.statusCode(),save.body());assertEquals(before,upstreamReads.get());
  var command=Map.<String,Object>of("id",id,"revision",1,"editVersion",1,"digest",d.digest(),"dryRun",true);var forged=new LinkedHashMap<>(command);forged.put("syncRunId",UUID.randomUUID());assertEquals(400,call("/api/v1/integrations/workflows/preview","POST",forged,true).statusCode());assertEquals(before,upstreamReads.get());
  var preview=call("/api/v1/integrations/workflows/preview","POST",command,true);assertEquals(200,preview.statusCode(),preview.body());var receipt=CatalogJson.JSON.readTree(preview.body()).get("receipt");assertEquals("zabbix-jsonrpc",receipt.get("origin").asString());assertEquals(1,receipt.get("accepted").asInt());assertTrue(upstreamReads.get()>before);String previewId=receipt.get("id").asString();
  var detail=call("/api/v1/integrations/workflows/runs/"+previewId,"GET",null,true);assertEquals(200,detail.statusCode());var trace=CatalogJson.JSON.readTree(detail.body()).get("trace");assertTrue(trace.get("syncRunId").isNull());assertEquals(digest,trace.get("source").get("configuration").get("digest").asString());assertFalse(detail.body().contains(SECRET));assertFalse(detail.body().contains("192.0.2.7"));assertFalse(detail.body().contains("Fixture host"));
  var publish=Map.of("id",id,"revision",1,"editVersion",1,"digest",d.digest(),"previewId",previewId);assertEquals(200,call("/api/v1/integrations/workflows/publish","POST",publish,true).statusCode());
  var rotate=call("/api/v2/data-sources/credentials/"+credentialId,"PATCH",Map.of("requestId",UUID.randomUUID(),"expectedEditVersion",1,"name","Fixture workflow credential","state","ACTIVE","secret","fixture-unused-next-token"),true);assertEquals(200,rotate.statusCode());var newestMetadata=CatalogJson.JSON.readTree(rotate.body()).get("receipt").get("credential");var newest=new SourceCredential.Pin(credentialId,newestMetadata.get("revision").asInt(),UUID.fromString(newestMetadata.get("versionId").asString()));
  assertEquals(200,call("/api/v2/data-sources/"+sourceId+"/connection","PATCH",Map.of("requestId",UUID.randomUUID(),"expectedEditVersion",1,"name","Fixture workflow source","description","","endpointPin",endpoint(),"credentialPin",newest),true).statusCode());
  var published=call("/api/v1/integrations/workflows/versions/"+id+"/1","GET",null,true);assertEquals(200,published.statusCode());assertEquals(digest,CatalogJson.JSON.readTree(published.body()).get("definition").get("source").get("configuration").get("digest").asString());
  var run=new LinkedHashMap<>(command);run.put("editVersion",0);assertEquals(200,call("/api/v1/integrations/workflows/run","POST",run,true).statusCode());
  var revoked=call("/api/v2/data-sources/credentials/"+credentialId+"/versions/1/revoke","POST",Map.of("requestId",UUID.randomUUID(),"expectedEditVersion",2),true);assertEquals(200,revoked.statusCode());before=upstreamReads.get();assertEquals(503,call("/api/v1/integrations/workflows/run","POST",run,true).statusCode());assertEquals(before,upstreamReads.get());assertEquals(200,call("/api/v1/integrations/workflows/versions/"+id+"/1","GET",null,true).statusCode());assertEquals(503,call("/api/v1/integrations/workflows/publish","POST",publish,true).statusCode());
 }
}
