package com.acme.opsweave.platform;
import static org.junit.jupiter.api.Assertions.*;
import com.acme.opsweave.platform.catalog.CatalogJson;
import com.acme.opsweave.integration.api.WorkflowStore;
import com.acme.opsweave.integration.domain.*;
import com.acme.opsweave.platform.persistence.InventoryWiring;
import com.acme.opsweave.sharedkernel.TenantId;
import java.net.URI;
import java.net.http.*;
import java.time.Duration;
import java.time.Instant;
import java.util.*;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.condition.EnabledIfEnvironmentVariable;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.web.server.LocalServerPort;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.*;

/** Actual trusted HTTP boundary with isolated PostgreSQL tenant; no collection or output. */
@SpringBootTest(webEnvironment=SpringBootTest.WebEnvironment.RANDOM_PORT)
@TestPropertySource(properties={"opsweave.auth.mode=dev","opsweave.auth.bind-loopback-only=true","opsweave.auth.dev.token=history-http-fixture-only-32-characters","opsweave.auth.dev.subject=history-author","opsweave.auth.dev.permissions=entity.read,log.read,source.sync","opsweave.zabbix.mode=fixture","opsweave.inventory.store=postgres"})
@EnabledIfEnvironmentVariable(named="OPSWEAVE_TEST_JDBC_URL",matches=".+")
class WorkflowHistoryHttpIT {
 static final String TENANT="history-http-fixture-"+UUID.randomUUID();
 static final String ROOT="/api/v1/integrations/workflows/quality/workflows/missing-fixture/versions/1/history";
 @DynamicPropertySource static void properties(DynamicPropertyRegistry r){r.add("opsweave.auth.dev.tenant",()->TENANT);r.add("opsweave.inventory.jdbc-url",()->System.getenv("OPSWEAVE_TEST_JDBC_URL"));r.add("opsweave.inventory.jdbc-user",()->System.getenv("OPSWEAVE_TEST_JDBC_USER"));r.add("opsweave.inventory.jdbc-password",()->System.getenv("OPSWEAVE_TEST_JDBC_PASSWORD"));}
 @LocalServerPort int port;@Autowired InventoryWiring wiring;final HttpClient http=HttpClient.newHttpClient();
 HttpResponse<String> call(String path,boolean auth,String method)throws Exception{var b=HttpRequest.newBuilder(URI.create("http://127.0.0.1:"+port+path)).timeout(Duration.ofSeconds(15));if(auth)b.header("Authorization","Bearer history-http-fixture-only-32-characters");b.method(method,HttpRequest.BodyPublishers.noBody());return http.send(b.build(),HttpResponse.BodyHandlers.ofString());}

 @Test void actualHistoryWireIsPagedAndReadOnlyUnderTheTrustedBoundary()throws Exception{
  var nodes=List.of(new WorkflowDefinition.Node("source",WorkflowDefinition.Type.SOURCE,"1",Map.of()),new WorkflowDefinition.Node("map",WorkflowDefinition.Type.MAP,"1",Map.of("eventTime","eventTime","body","body")),new WorkflowDefinition.Node("validate",WorkflowDefinition.Type.VALIDATE,"1",Map.of()),new WorkflowDefinition.Node("output",WorkflowDefinition.Type.OUTPUT,"1",Map.of()));
  // Complete synthetic fixed-source metadata; this read-only HTTP test performs no source IO.
  var sourceId=UUID.randomUUID();var configAt=Instant.now().minusSeconds(120).truncatedTo(java.time.temporal.ChronoUnit.SECONDS);var endpoint=SourceEndpoint.registered("diagnostic-fixture","Synthetic Fixture","http://127.0.0.1:1/api_jsonrpc.php");var credential=new SourceCredential.Pin(UUID.randomUUID(),1,UUID.randomUUID());var connection=SourceConnectionConfiguration.snapshot(sourceId,1,endpoint,credential,configAt);var instance=new SourceInstance(sourceId,"Synthetic Fixture","Metadata-only Fixture",new WorkflowDefinition.Source("ZABBIX_HOST",SourceConnectionConfiguration.physicalId(sourceId)),1,connection.connectionDigest(),"zabbix-jsonrpc",1,"ACTIVE",configAt,configAt);var item=new SourceMetricDiscovery.Item("1","2","log[/synthetic-fixture]","Synthetic Fixture","","LOG","NO_MAPPING",null);var discovery=new SourceMetricDiscovery(List.of(item),true,"FIRST_PAGE_MATCH","READ_VERIFIED",SourceMetricDiscovery.digest(List.of(item)));var inspectionId=UUID.randomUUID();var inspection=new SourceInspection(inspectionId,sourceId,"DISCOVER_METRICS",1,connection.connectionDigest(),"zabbix-jsonrpc",SourceInspection.commandDigest(sourceId,inspectionId,"DISCOVER_METRICS",1,connection.connectionDigest()),"COMPLETED",configAt,configAt.plus(SourceInspection.TIMEOUT),configAt,configAt.plus(SourceInspection.VALID_FOR),null,null,discovery);wiring.workflows().transaction(new TenantId(TENANT),s->{s.saveSetup("history-author",new SourceSetup(sourceId,instance.name(),instance.description(),instance.source(),connection.connectionDigest(),"zabbix-jsonrpc",null,SourceSetup.fingerprint(sourceId,instance.name(),instance.description(),instance.source(),connection.connectionDigest(),"zabbix-jsonrpc",null),configAt));s.saveSourceInstance("history-author",instance);s.addSourceConfiguration("history-author",instance.configuration());s.addSourceConnection("history-author",connection);s.addSourceInspection("history-author",SourceInspection.pending(sourceId,inspectionId,"DISCOVER_METRICS",instance,configAt));s.finishSourceInspection("history-author",inspection);return null;});
  var src=new WorkflowDefinition.Source("ZABBIX_LOG",instance.source().instanceId(),new WorkflowDefinition.ConfigurationPin(sourceId,1,connection.connectionDigest()),null,WorkflowLogSourcePin.from(inspectionId,item));var d=WorkflowOperators.builtIn().pin(new WorkflowDefinition("history-http-"+UUID.randomUUID().toString().substring(0,8),1,"Synthetic Fixture",src,new WorkflowDefinition.Target(null,1,null,"LOG"),nodes,List.of(new WorkflowDefinition.Edge("source","map"),new WorkflowDefinition.Edge("map","validate"),new WorkflowDefinition.Edge("validate","output"))));

  var at=Instant.now().minusSeconds(2).truncatedTo(java.time.temporal.ChronoUnit.MICROS);var from=at.minusSeconds(70).truncatedTo(java.time.temporal.ChronoUnit.SECONDS);var ref=new WorkflowQuality.Reference(d.id(),1,d.digest());var original=new ArrayList<WorkflowDiagnostics.Observation>();for(int i=0;i<45;i++){var completed=at.minusSeconds(i);original.add(new WorkflowDiagnostics.Observation(UUID.randomUUID(),ref,WorkflowQuality.Kind.LOG_STREAM,1,"SOURCE_FAILED",completed.minusSeconds(70).truncatedTo(java.time.temporal.ChronoUnit.SECONDS),completed.minusSeconds(70).truncatedTo(java.time.temporal.ChronoUnit.SECONDS).plusSeconds(60),completed,completed,null,null,"SOURCE_UNAVAILABLE",WorkflowDiagnostics.Result.unavailable()));}var layout=new HashMap<String,WorkflowStore.Position>();nodes.forEach(n->layout.put(n.id(),new WorkflowStore.Position(0,0)));wiring.workflows().transaction(new TenantId(TENANT),s->{s.publish(new WorkflowStore.Entry(d,d.digest(),"PUBLISHED",0,layout,at,null),"history-author");original.forEach(o->s.addDiagnostic("history-author",new WorkflowDiagnostics.Stored(o,List.of())));return null;});
  var path=ROOT.replace("missing-fixture",d.id());var first=call(path,true,"GET");assertEquals(200,first.statusCode(),first.body());var page=CatalogJson.JSON.readTree(first.body());assertEquals(10,page.size());assertEquals("RECORDED_CHECKS",page.get("coverage").asString());assertEquals(45,page.get("recordedCount").asInt());assertEquals(20,page.get("items").size());assertTrue(page.get("hasMore").asBoolean());assertEquals(13,page.get("items").get(0).size());assertEquals(original.getFirst().id().toString(),page.get("items").get(0).get("id").asString());assertFalse(first.body().contains("entityIds"));assertFalse(first.body().contains("history_sequence"));assertFalse(first.body().contains("watermark"));
  var nextResponse=call(path+"?cursor="+page.get("nextCursor").asString(),true,"GET");assertEquals(200,nextResponse.statusCode(),nextResponse.body());var next=CatalogJson.JSON.readTree(nextResponse.body());assertEquals(page.get("snapshotAt"),next.get("snapshotAt"));assertEquals(20,next.get("offset").asInt());assertEquals(original.get(20).id().toString(),next.get("items").get(0).get("id").asString());var lastResponse=call(path+"?cursor="+next.get("nextCursor").asString(),true,"GET");assertEquals(200,lastResponse.statusCode(),lastResponse.body());var last=CatalogJson.JSON.readTree(lastResponse.body());assertEquals(5,last.get("items").size());assertEquals(40,last.get("offset").asInt());assertFalse(last.get("hasMore").asBoolean());assertTrue(last.get("nextCursor").isNull());
  assertEquals(401,call(path,false,"GET").statusCode());assertEquals(400,call(path+"?tenantId=forged",true,"GET").statusCode());assertEquals(400,call(path+"?cursor=h1.abc&cursor=h1.abc",true,"GET").statusCode());assertEquals(404,call(path+"?cursor=h1.abc",true,"GET").statusCode());assertEquals(400,call(path+"?cursor=h1.abc=",true,"GET").statusCode());for(var method:List.of("POST","PUT","PATCH","DELETE")){var r=call(path,true,method);assertEquals(405,r.statusCode());assertEquals("GET",r.headers().firstValue("Allow").orElseThrow());}assertEquals(45,wiring.workflows().transaction(new TenantId(TENANT),s->s.diagnosticCount("history-author")).intValue());
 }
}
