package com.acme.opsweave.platform;
import static org.junit.jupiter.api.Assertions.*;
import com.acme.opsweave.platform.catalog.CatalogJson;
import com.acme.opsweave.integration.api.WorkflowStore;
import com.acme.opsweave.integration.domain.*;
import com.acme.opsweave.platform.persistence.InventoryWiring;
import com.acme.opsweave.sharedkernel.TenantId;
import java.net.URI;
import java.net.http.*;
import java.time.Duration;
import java.time.Instant;
import java.util.*;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.condition.EnabledIfEnvironmentVariable;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.web.server.LocalServerPort;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.*;

/** Actual trusted HTTP boundary with isolated PostgreSQL tenant; no collection or output. */
@SpringBootTest(webEnvironment=SpringBootTest.WebEnvironment.RANDOM_PORT)
@TestPropertySource(properties={"opsweave.auth.mode=dev","opsweave.auth.bind-loopback-only=true","opsweave.auth.dev.token=diagnostic-http-fixture-only-32-characters","opsweave.auth.dev.subject=diagnostic-author","opsweave.auth.dev.permissions=entity.read,log.read,source.sync","opsweave.zabbix.mode=fixture","opsweave.inventory.store=postgres"})
@EnabledIfEnvironmentVariable(named="OPSWEAVE_TEST_JDBC_URL",matches=".+")
class WorkflowDiagnosticsHttpIT {
 static final String TENANT="diagnostic-http-fixture-"+UUID.randomUUID();
 static final String ROOT="/api/v1/integrations/workflows/quality/workflows/missing-fixture/versions/1/diagnostics";
 @DynamicPropertySource static void properties(DynamicPropertyRegistry r){r.add("opsweave.auth.dev.tenant",()->TENANT);r.add("opsweave.inventory.jdbc-url",()->System.getenv("OPSWEAVE_TEST_JDBC_URL"));r.add("opsweave.inventory.jdbc-user",()->System.getenv("OPSWEAVE_TEST_JDBC_USER"));r.add("opsweave.inventory.jdbc-password",()->System.getenv("OPSWEAVE_TEST_JDBC_PASSWORD"));}
 @LocalServerPort int port;@Autowired InventoryWiring wiring;final HttpClient http=HttpClient.newHttpClient();
 HttpResponse<String> call(String path,boolean auth,String method)throws Exception{var b=HttpRequest.newBuilder(URI.create("http://127.0.0.1:"+port+path)).timeout(Duration.ofSeconds(15));if(auth)b.header("Authorization","Bearer diagnostic-http-fixture-only-32-characters");b.method(method,HttpRequest.BodyPublishers.noBody());return http.send(b.build(),HttpResponse.BodyHandlers.ofString());}
 @Test void missingMetadataIs404AndTrustedAuthenticationRequired()throws Exception{var r=call(ROOT,true,"GET");assertEquals(404,r.statusCode());assertEquals("NOT_FOUND",CatalogJson.JSON.readTree(r.body()).get("error").asString());assertEquals(401,call(ROOT,false,"GET").statusCode());assertEquals(404,call(ROOT+"/"+UUID.randomUUID(),true,"GET").statusCode());}
 @Test void forgedScopeMalformedIdentityAndMutationsFailClosed()throws Exception{assertEquals(400,call(ROOT+"?tenantId=forged",true,"GET").statusCode());assertEquals(400,call(ROOT+"/1-1-1-1-1",true,"GET").statusCode());for(var method:List.of("POST","PUT","PATCH","DELETE")){var r=call(ROOT,true,method);assertEquals(405,r.statusCode());assertEquals("GET",r.headers().firstValue("Allow").orElseThrow());assertEquals(405,call(ROOT+"/"+UUID.randomUUID(),true,method).statusCode());}}

 @Test void measuredSourceAndLegacyObservationsShareReadOnlyTrustedWire()throws Exception{
  var nodes=List.of(new WorkflowDefinition.Node("source",WorkflowDefinition.Type.SOURCE,"1",Map.of()),new WorkflowDefinition.Node("map",WorkflowDefinition.Type.MAP,"1",Map.of("eventTime","eventTime","body","body")),new WorkflowDefinition.Node("validate",WorkflowDefinition.Type.VALIDATE,"1",Map.of()),new WorkflowDefinition.Node("output",WorkflowDefinition.Type.OUTPUT,"1",Map.of()));
  // Complete synthetic fixed-source metadata; this read-only HTTP test performs no source IO.
  var sourceId=UUID.randomUUID();var configAt=Instant.now().minusSeconds(120).truncatedTo(java.time.temporal.ChronoUnit.SECONDS);var endpoint=SourceEndpoint.registered("diagnostic-fixture","Synthetic Fixture","http://127.0.0.1:1/api_jsonrpc.php");var credential=new SourceCredential.Pin(UUID.randomUUID(),1,UUID.randomUUID());var connection=SourceConnectionConfiguration.snapshot(sourceId,1,endpoint,credential,configAt);var instance=new SourceInstance(sourceId,"Synthetic Fixture","Metadata-only Fixture",new WorkflowDefinition.Source("ZABBIX_HOST",SourceConnectionConfiguration.physicalId(sourceId)),1,connection.connectionDigest(),"zabbix-jsonrpc",1,"ACTIVE",configAt,configAt);var item=new SourceMetricDiscovery.Item("1","2","log[/synthetic-fixture]","Synthetic Fixture","","LOG","NO_MAPPING",null);var discovery=new SourceMetricDiscovery(List.of(item),true,"FIRST_PAGE_MATCH","READ_VERIFIED",SourceMetricDiscovery.digest(List.of(item)));var inspectionId=UUID.randomUUID();var inspection=new SourceInspection(inspectionId,sourceId,"DISCOVER_METRICS",1,connection.connectionDigest(),"zabbix-jsonrpc",SourceInspection.commandDigest(sourceId,inspectionId,"DISCOVER_METRICS",1,connection.connectionDigest()),"COMPLETED",configAt,configAt.plus(SourceInspection.TIMEOUT),configAt,configAt.plus(SourceInspection.VALID_FOR),null,null,discovery);wiring.workflows().transaction(new TenantId(TENANT),s->{s.saveSetup("diagnostic-author",new SourceSetup(sourceId,instance.name(),instance.description(),instance.source(),connection.connectionDigest(),"zabbix-jsonrpc",null,SourceSetup.fingerprint(sourceId,instance.name(),instance.description(),instance.source(),connection.connectionDigest(),"zabbix-jsonrpc",null),configAt));s.saveSourceInstance("diagnostic-author",instance);s.addSourceConfiguration("diagnostic-author",instance.configuration());s.addSourceConnection("diagnostic-author",connection);s.addSourceInspection("diagnostic-author",SourceInspection.pending(sourceId,inspectionId,"DISCOVER_METRICS",instance,configAt));s.finishSourceInspection("diagnostic-author",inspection);return null;});
  var src=new WorkflowDefinition.Source("ZABBIX_LOG",instance.source().instanceId(),new WorkflowDefinition.ConfigurationPin(sourceId,1,connection.connectionDigest()),null,WorkflowLogSourcePin.from(inspectionId,item));var d=WorkflowOperators.builtIn().pin(new WorkflowDefinition("diagnostic-http-"+UUID.randomUUID().toString().substring(0,8),1,"Synthetic Fixture",src,new WorkflowDefinition.Target(null,1,null,"LOG"),nodes,List.of(new WorkflowDefinition.Edge("source","map"),new WorkflowDefinition.Edge("map","validate"),new WorkflowDefinition.Edge("validate","output"))));
  var from=configAt;var till=from.plusSeconds(60);var at=till.plusSeconds(10);var ref=new WorkflowQuality.Reference(d.id(),1,d.digest());var measured=new WorkflowDiagnostics.Observation(UUID.randomUUID(),ref,WorkflowQuality.Kind.LOG_STREAM,1,"SOURCE_FAILED",from,till,at,at,null,null,"SOURCE_CHANGED",WorkflowDiagnostics.Result.unavailable(),new WorkflowDiagnostics.SourceRead(1,0,1,null,WorkflowDiagnostics.SourceFailure.UNIT_CHANGED,at,at));var legacy=new WorkflowDiagnostics.Observation(UUID.randomUUID(),ref,WorkflowQuality.Kind.LOG_STREAM,1,"SOURCE_FAILED",from,till,at,at,null,null,"SOURCE_UNAVAILABLE",WorkflowDiagnostics.Result.unavailable());
  var dispatch=new WorkflowDiagnostics.Dispatch(UUID.randomUUID(),at.minusMillis(250),at);var queued=new WorkflowDiagnostics.Observation(UUID.randomUUID(),ref,WorkflowQuality.Kind.LOG_STREAM,1,"SOURCE_FAILED",from,till,at,at,250L,null,"SOURCE_CHANGED",WorkflowDiagnostics.Result.unavailable(),measured.sourceRead(),dispatch);
  var layout=new HashMap<String,WorkflowStore.Position>();for(var n:nodes)layout.put(n.id(),new WorkflowStore.Position(0,0));wiring.workflows().transaction(new TenantId(TENANT),s->{s.publish(new WorkflowStore.Entry(d,d.digest(),"PUBLISHED",0,layout,at,null),"diagnostic-author");s.addDiagnostic("diagnostic-author",new WorkflowDiagnostics.Stored(measured,List.of()));s.addDiagnostic("diagnostic-author",new WorkflowDiagnostics.Stored(legacy,List.of()));s.addDiagnostic("diagnostic-author",new WorkflowDiagnostics.Stored(queued,List.of()));return null;});
  var path=ROOT.replace("missing-fixture",d.id());var response=call(path,true,"GET");assertEquals(200,response.statusCode(),response.body());var report=CatalogJson.JSON.readTree(response.body());assertEquals(3,report.get("observations").size());assertEquals(200,call(path+"/"+measured.id(),true,"GET").statusCode());var value=CatalogJson.JSON.readTree(call(path+"/"+measured.id(),true,"GET").body());assertEquals(14,value.size());assertEquals("UNIT_CHANGED",value.get("sourceRead").get("failureCode").asString());assertEquals(1,value.get("sourceRead").get("failed").asInt());assertTrue(value.get("sourceRead").get("received").isNull());assertTrue(value.get("result").get("received").isNull());assertEquals(13,CatalogJson.JSON.readTree(call(path+"/"+legacy.id(),true,"GET").body()).size());var queueWire=CatalogJson.JSON.readTree(call(path+"/"+queued.id(),true,"GET").body());assertEquals(15,queueWire.size());assertEquals(250,queueWire.get("queueWaitMillis").asInt());assertEquals(dispatch.id().toString(),queueWire.get("dispatch").get("id").asString());assertEquals(3,queueWire.get("dispatch").size());assertFalse(response.body().contains("entityIds"));assertEquals(401,call(path,false,"GET").statusCode());assertEquals(400,call(path+"?tenantId=forged",true,"GET").statusCode());assertEquals(405,call(path,true,"POST").statusCode());assertEquals(3,wiring.workflows().transaction(new TenantId(TENANT),s->s.diagnosticCount("diagnostic-author")).intValue());
  var alerts=path.replace("/diagnostics","/alerts");var cmd=new WorkflowQualityAlerts.Command(UUID.randomUUID(),d.id(),1,d.digest(),0,600,List.of(new WorkflowQualityAlerts.Rule(WorkflowQualityAlerts.Kind.QUEUE_WAIT,250)));var json=CatalogJson.JSON.writeValueAsString(cmd);
  var post=http.send(HttpRequest.newBuilder(URI.create("http://127.0.0.1:"+port+alerts+"/configure")).header("Authorization","Bearer diagnostic-http-fixture-only-32-characters").header("Content-Type","application/json").POST(HttpRequest.BodyPublishers.ofString(json)).build(),HttpResponse.BodyHandlers.ofString());assertEquals(200,post.statusCode(),post.body());var accepted=CatalogJson.JSON.readTree(post.body());assertEquals(1,accepted.get("configuration").get("editVersion").asInt());
  var evaluated=call(alerts,true,"GET");assertEquals(200,evaluated.statusCode(),evaluated.body());var eval=CatalogJson.JSON.readTree(evaluated.body()).get("evaluations").get(0);assertEquals("TRIGGERED",eval.get("state").asString());assertEquals(250,eval.get("value").asInt());assertEquals(2,eval.get("missingCount").asInt());assertEquals(1,eval.get("sampleCount").asInt());assertEquals(post.body(),call(alerts+"/commands/"+cmd.requestId(),true,"GET").body());assertEquals(401,call(alerts,false,"GET").statusCode());assertEquals(400,call(alerts+"?tenantId=forged",true,"GET").statusCode());assertEquals(405,call(alerts,true,"POST").statusCode());assertEquals(404,call(alerts+"/commands/"+UUID.randomUUID(),true,"GET").statusCode());
  for(var body:List.of("{broken",json.substring(0,json.length()-1)+",\"tenantId\":\"forged\"}")){var bad=http.send(HttpRequest.newBuilder(URI.create("http://127.0.0.1:"+port+alerts+"/configure")).header("Authorization","Bearer diagnostic-http-fixture-only-32-characters").header("Content-Type","application/json").POST(HttpRequest.BodyPublishers.ofString(body)).build(),HttpResponse.BodyHandlers.ofString());assertEquals(400,bad.statusCode(),bad.body());}

 }
}
