import { useEffect, useId, useRef, useState, type ReactNode, type RefObject } from 'react'
import { X } from 'lucide-react'
import { Button } from '../ui/button.tsx'
import { Input } from '../ui/input.tsx'
import { Textarea } from '../ui/textarea.tsx'
import type { Configuration, InstanceEdit, SourceInstance } from '../../api/source-instances.ts'
import type { Connection } from '../../api/source-setups.ts'
import type { ConnectionConfiguration } from '../../api/source-connections.ts'
import { IntegrationViewTabs } from './IntegrationViewTabs.tsx'
type DisplayConnection = Connection | ConnectionConfiguration
function endpointAddress(connection: DisplayConnection | null) { if (!connection) return null; if (typeof connection.endpoint === 'string') return connection.endpoint; return connection.endpoint?.address ?? null }
function credentialReference(connection: DisplayConnection | null) { return connection ? 'credentialRef' in connection ? connection.credentialRef : `v${connection.credentialPin.revision} · ${connection.credentialPin.versionId}` : null }
export function SourceInstanceDrawer(p: { connectionEdit: () => void; dialog: RefObject<HTMLDialogElement | null>; active: boolean; instance: SourceInstance | null; connection: DisplayConnection | null; itemSync?: (active: boolean) => ReactNode; problemPanel?: (active: boolean) => ReactNode; name: string; description: string; digest: string; versions: Configuration[] | null; busy: boolean; pending: InstanceEdit | null; inspectionPending: boolean; inspections: ReactNode; inspectLookup: () => void; inspectReadOnce: () => void; ready: boolean; error: string; notice: string; dirty: boolean; nameChange: (value: string) => void; descriptionChange: (value: string) => void; adopt: () => void; save: (state: SourceInstance['state']) => void; lookup: () => void; reset: () => void; versionsRead: () => void; closed: () => void }) {
  const [view, setView] = useState<{ id: string | undefined; tab: 'config' | 'versions' | 'inspections' | 'problems' | 'itemSync' }>({ id: undefined, tab: 'config' }), [archive, setArchive] = useState(false)
  const tab = view.id === p.instance?.id ? view.tab : 'config'
  const setTab = (value: 'config' | 'versions' | 'inspections' | 'problems' | 'itemSync') => setView({ id: p.instance?.id, tab: value })
  const body = useRef<HTMLDivElement>(null), id = useId()
  useEffect(() => { setArchive(false) }, [p.instance?.id])
  useEffect(() => { if (!p.active) p.dialog.current?.close() }, [p.active, p.dialog])
  useEffect(() => { if (p.active && tab === 'inspections' && p.ready) p.inspectReadOnce() }, [p.active, tab, p.ready, p.busy, p.inspectReadOnce])
  const disabled = p.busy || !!p.pending || p.inspectionPending || !p.ready, archived = p.instance?.state === 'ARCHIVED'
  const address = endpointAddress(p.connection), credential = credentialReference(p.connection)
  return <dialog ref={p.dialog} className="model-drawer source-drawer source-setup-drawer source-instance-drawer" aria-label="维护接入实例" onCancel={event => { if (p.busy || p.pending || p.inspectionPending) event.preventDefault() }} onClose={p.closed}>
    <header className="model-drawer-heading source-setup-heading"><div><div className="model-eyebrow">{archived ? '已归档' : '接入实例'}</div><h3>{p.instance?.name}</h3></div><Button type="button" variant="ghost" size="icon" aria-label="关闭实例维护" disabled={p.busy || !!p.pending || p.inspectionPending} onClick={() => p.dialog.current?.close()}><X size={18}/></Button></header>
    <div className="source-instance-tabs"><IntegrationViewTabs label="实例维护视图" value={tab} items={[{ id: 'config', label: '实例配置' }, { id: 'versions', label: '配置历史' }, ...(p.instance?.source.kind === 'ZABBIX_HOST' ? [{ id: 'inspections' as const, label: '连接与字段' }] : []), ...(p.problemPanel ? [{ id: 'problems' as const, label: '问题读取' }] : []), ...(p.itemSync ? [{ id: 'itemSync' as const, label: '指标同步' }] : [])]} change={value => { setTab(value); body.current?.scrollTo({ top: 0 }); if (value === 'versions' && p.versions === null && !p.busy) p.versionsRead() }}/></div>
    <div className="model-drawer-body source-setup-body" ref={body}><div hidden={tab !== 'config'}><fieldset className="model-form" disabled={disabled || archived}><label htmlFor={id + '-name'}>实例名称<Input id={id + '-name'} aria-label="实例名称" maxLength={80} value={p.name} onChange={event => p.nameChange(event.target.value)}/></label><label htmlFor={id + '-description'}>实例说明<Textarea id={id + '-description'} aria-label="实例说明" maxLength={500} rows={3} value={p.description} onChange={event => p.descriptionChange(event.target.value)}/></label></fieldset>
      <section className="source-instance-connection"><div className="source-instance-history-heading"><h4>连接配置</h4>{p.instance?.source.kind === 'ZABBIX_HOST' ? <Button type="button" variant="outline" disabled={disabled || archived || p.dirty} onClick={p.connectionEdit}>地址与凭据</Button> : null}</div><dl className="source-connection"><dt>来源实例</dt><dd>{p.instance?.source.instanceId}</dd><dt>保存的配置版本</dt><dd>v{p.instance?.configurationRevision}</dd><dt>保存的连接摘要</dt><dd><code>{p.digest}</code></dd><dt>当前登记的地址</dt><dd>{address ?? (p.connection && 'dataMode' in p.connection && p.connection.dataMode === 'fixture' ? 'Fixture · 无外部连接' : p.instance?.source.kind === 'MANUAL_SAMPLE' ? '手工样本，无外部连接' : '查看地址与凭据')}</dd><dt>当前凭据引用</dt><dd><code>{credential ?? (p.instance?.source.kind !== 'ZABBIX_HOST' || p.connection && 'dataMode' in p.connection && p.connection.dataMode === 'fixture' ? '无需凭据' : '查看地址与凭据')}</code></dd></dl>
      {p.connection && ('digest' in p.connection ? p.connection.digest : p.connection.connectionDigest) !== p.digest ? <><p>平台连接已变化。采用后生成新的配置版本，已有工作流和任务不会自动改版。</p><Button type="button" variant="outline" disabled={disabled || archived} onClick={p.adopt}>采用当前连接配置</Button></> : null}</section>
      {archived ? <p>归档保留创建回执、配置历史及已发布版本。恢复后可继续维护。</p> : <><button type="button" className="source-instance-archive" disabled={disabled || p.dirty} onClick={() => setArchive(true)}>归档实例</button>{archive ? <div className="source-instance-confirm"><p>归档保留历史，不停止其他主体的任务。当前主体有运行中的任务时，需要先停止任务。</p><Button type="button" variant="outline" disabled={disabled} onClick={() => setArchive(false)}>取消</Button><Button type="button" disabled={disabled} onClick={() => { p.save('ARCHIVED'); setArchive(false) }}>确认归档</Button></div> : null}</>}
    </div><div hidden={tab !== 'versions'}><div className="source-instance-history-heading"><h4>不可变配置版本</h4><Button type="button" variant="outline" disabled={disabled} onClick={p.versionsRead}>刷新配置历史</Button></div>{p.versions ? <div className="integration-table-wrap"><table className="integration-table" aria-label="配置历史"><thead><tr><th scope="col">版本</th><th scope="col">连接摘要</th><th scope="col">来源标记</th><th scope="col">创建时间</th></tr></thead><tbody>{p.versions.map(c => <tr key={c.revision}><td>v{c.revision}</td><td><code>{c.connectionDigest}</code></td><td>{c.dataMode}</td><td><time dateTime={c.createdAt}>{new Date(c.createdAt).toLocaleString()}</time></td></tr>)}</tbody></table></div> : null}</div>
    <div hidden={tab !== 'inspections'}>{p.inspections}</div>
    {p.problemPanel ? <div hidden={tab !== 'problems'}>{p.problemPanel(p.active && tab === 'problems')}</div> : null}
    {p.itemSync ? <div hidden={tab !== 'itemSync'}>{p.itemSync(p.active && tab === 'itemSync')}</div> : null}
    {p.error ? <p role="alert">{p.error}</p> : null}<p role="status">{p.busy ? '正在处理…' : p.notice}</p>{p.pending || p.inspectionPending ? <p>命令结果待确认，请查询原请求回执；输入保持固定。</p> : null}</div>
    <footer className="model-drawer-footer source-setup-footer"><span>修改不启动采集</span>{p.inspectionPending ? <Button type="button" variant="outline" disabled={p.busy || !p.ready} onClick={p.inspectLookup}>查询原测试或发现回执</Button> : p.pending ? <Button type="button" variant="outline" disabled={p.busy || !p.ready} onClick={p.lookup}>查询原维护回执</Button> : <><Button type="button" variant="outline" disabled={p.busy || !p.ready} onClick={p.reset}>{p.dirty ? '放弃修改并重读' : '读取最新实例'}</Button><Button type="button" disabled={disabled || !p.name.trim() || !archived && !p.dirty} onClick={() => p.save('ACTIVE')}>{archived ? '恢复实例' : '保存实例'}</Button></>}</footer>
  </dialog>
}
