import { useId, type RefObject } from 'react'
import { X } from 'lucide-react'
import { Button } from '../ui/button.tsx'
import { Input } from '../ui/input.tsx'
import { Textarea } from '../ui/textarea.tsx'
import type { SourceCredential, CredentialVersion } from '../../api/source-credentials.ts'
import type { ConnectionConfiguration, ConnectionView, Endpoint } from '../../api/source-connections.ts'
export type ConnectionDraft = { name: string; description: string; endpointId: string; credentialId: string; versionId: string; hostGroupIds: string }
export function SourceConnectionDrawer(p: { dialog: RefObject<HTMLDialogElement | null>; editing: boolean; view: ConnectionView | null; draft: ConnectionDraft; endpoints: Endpoint[] | null; credentials: SourceCredential[] | null; versions: CredentialVersion[] | null; history: ConnectionConfiguration[] | null; busy: boolean; pending: boolean; canSave: boolean; dirty: boolean; error: string; notice: string; change: (draft: ConnectionDraft) => void; credentialChange: (id: string) => void; save: () => void; lookup: () => void; reload: () => void; discard: () => void; historyRead: (force?: boolean) => void; closed: () => void }) {
  const id = useId(), disabled = p.busy || p.pending, currentEndpoint = p.endpoints?.find(e => e.id === p.draft.endpointId), currentVersion = p.versions?.find(v => v.pin.versionId === p.draft.versionId)
  return <dialog ref={p.dialog} className="model-drawer source-drawer source-setup-drawer source-connection-drawer" aria-label={p.editing ? '编辑地址与凭据' : '新增连接'} onCancel={e => { if (disabled) e.preventDefault() }} onClose={p.closed}>
    <header className="model-drawer-heading source-setup-heading"><div><div className="model-eyebrow">数据源连接</div><h3>{p.editing ? '编辑地址与凭据' : '新增连接'}</h3></div><button type="button" className="model-close" aria-label="关闭连接配置" disabled={disabled} onClick={() => p.dialog.current?.close()}><X size={18}/></button></header>
    <div className="model-drawer-body source-setup-body"><fieldset className="model-form" disabled={disabled}><label htmlFor={id + '-name'}>连接名称<Input id={id + '-name'} aria-label="连接名称" maxLength={80} value={p.draft.name} onChange={e => p.change({ ...p.draft, name: e.target.value })}/></label><label htmlFor={id + '-description'}>连接说明<Textarea id={id + '-description'} aria-label="连接说明" rows={3} maxLength={500} value={p.draft.description} onChange={e => p.change({ ...p.draft, description: e.target.value })}/></label><label htmlFor={id + '-groups'}>主机组 ID<Input id={id + '-groups'} aria-label="主机组 ID" aria-describedby={id + '-groups-help'} placeholder="例如 1001, 1002" value={p.draft.hostGroupIds} onChange={e => p.change({ ...p.draft, hostGroupIds: e.target.value })}/></label><small id={id + '-groups-help'}>填写 1 至 32 个正整数 ID，用逗号或空格分隔。读取仅覆盖这些主机组。</small><label htmlFor={id + '-endpoint'}>登记地址<select id={id + '-endpoint'} aria-label="登记地址" value={p.draft.endpointId} onChange={e => p.change({ ...p.draft, endpointId: e.target.value })}><option value="">选择登记地址</option>{p.endpoints?.map(e => <option key={e.id} value={e.id}>{e.name}</option>)}</select></label><label htmlFor={id + '-credential'}>凭据<select id={id + '-credential'} aria-label="连接凭据" value={p.draft.credentialId} onChange={e => p.credentialChange(e.target.value)}><option value="">选择凭据</option>{p.credentials?.map(c => <option key={c.id} value={c.id} disabled={c.state !== 'ACTIVE'}>{c.name}{c.state === 'REVOKED' ? ' · 已撤销' : ''}</option>)}</select></label><label htmlFor={id + '-version'}>凭据版本<select id={id + '-version'} aria-label="连接凭据版本" disabled={!p.versions || disabled} value={p.draft.versionId} onChange={e => p.change({ ...p.draft, versionId: e.target.value })}><option value="">选择固定版本</option>{p.versions?.map(v => <option key={v.pin.versionId} value={v.pin.versionId} disabled={v.revoked}>v{v.pin.revision} · {new Date(v.createdAt).toLocaleString()}{v.revoked ? ' · 已撤销' : ''}</option>)}</select></label></fieldset>
      {currentEndpoint || currentVersion ? <dl className="source-connection source-connection-selection"><dt>地址</dt><dd>{currentEndpoint?.address ?? '尚未选择'}</dd><dt>固定凭据版本</dt><dd>{currentVersion ? <><span>v{currentVersion.pin.revision}</span><code>{currentVersion.pin.versionId}</code></> : '尚未选择'}</dd></dl> : null}
      {p.endpoints?.length === 0 ? <p>尚无可用的登记地址，请由部署配置提供地址目录。</p> : null}{p.credentials?.length === 0 ? <p>尚无可用凭据，请先到凭据管理创建。</p> : null}
      {p.view?.connection ? <section className="source-instance-connection"><h4>已保存的配置 · v{p.view.connection.revision}</h4><dl className="source-connection"><dt>地址</dt><dd>{p.view.connection.endpoint.address}</dd><dt>主机组范围</dt><dd>{p.view.connection.hostGroupIds.length ? p.view.connection.hostGroupIds.join(', ') : '未固定'}</dd><dt>凭据版本</dt><dd>v{p.view.connection.credentialPin.revision}<code>{p.view.connection.credentialPin.versionId}</code></dd></dl>{p.view.connection.hostGroupIds.length === 0 ? <p role="status">此旧配置没有固定主机组。补充范围并保存后，实例检查和工作流读取才可使用。</p> : null}{p.view.availability === 'UNAVAILABLE' ? <p role="alert">地址、凭据或对象范围当前不可用，请重新选择并保存。</p> : null}<details onToggle={e => { if (e.currentTarget.open && p.history === null && !disabled) p.historyRead() }}><summary>连接配置历史</summary><Button type="button" variant="outline" disabled={disabled} onClick={() => p.historyRead(true)}>刷新连接历史</Button>{p.history ? <div className="integration-table-wrap"><table className="integration-table" aria-label="连接配置历史"><thead><tr><th scope="col">版本</th><th scope="col">地址</th><th scope="col">主机组范围</th><th scope="col">凭据版本</th></tr></thead><tbody>{p.history.map(c => <tr key={c.revision}><td>v{c.revision}</td><td>{c.endpoint.address}</td><td>{c.hostGroupIds.length ? c.hostGroupIds.join(', ') : '未固定'}</td><td>v{c.credentialPin.revision}<code>{c.credentialPin.versionId}</code></td></tr>)}</tbody></table></div> : null}</details></section> : p.view ? <p>保存地址、主机组范围与固定凭据后生成新配置版本。</p> : null}
      {p.error ? <p role="alert">{p.error}</p> : null}<p role="status">{p.busy ? '正在处理…' : p.notice}</p>{p.pending ? <p>结果待确认，请查询原请求回执，勿重复提交。</p> : null}
    </div><footer className="model-drawer-footer source-setup-footer"><span>保存不启动采集</span>{p.pending ? <Button type="button" variant="outline" disabled={p.busy} onClick={p.lookup}>查询原连接回执</Button> : <><Button type="button" variant="outline" disabled={p.busy} onClick={p.dirty ? p.discard : p.reload}>{p.dirty ? '放弃修改' : '重新读取'}</Button><Button type="button" disabled={disabled || !p.canSave} onClick={p.save}>{p.editing ? '保存连接配置' : '创建连接'}</Button></>}</footer>
  </dialog>
}
