import { useEffect, useRef, useState, type RefObject } from 'react'
import { X } from 'lucide-react'
import { Button } from '../ui/button.tsx'
import { Input } from '../ui/input.tsx'
import { IntegrationViewTabs } from './IntegrationViewTabs.tsx'
import type { CredentialPage, CredentialVersion, SourceCredential } from '../../api/source-credentials.ts'
export function SourceCredentialDrawer(p: { dialog: RefObject<HTMLDialogElement | null>; secret: RefObject<HTMLInputElement | null>; selected: SourceCredential | null; name: string; secretPresent: boolean; versions: CredentialVersion[] | null; historyAttempted: boolean; active: boolean; page: CredentialPage | null; ready: boolean; busy: boolean; pending: boolean; error: string; notice: string; nameChange: (name: string) => void; secretChange: (present: boolean) => void; save: () => void; revoke: (revision?: number) => void; lookup: () => void; versionsRead: () => void; reset: () => void; closed: () => void }) {
  const [view, setView] = useState<{ id?: string; tab: 'config' | 'versions' }>({ tab: 'config' }), [confirmation, setConfirmation] = useState<{ revision?: number } | null>(null)
  const tab = view.id === p.selected?.id ? view.tab : 'config', body = useRef<HTMLDivElement>(null)
  useEffect(() => { setConfirmation(null) }, [p.selected?.id, p.selected?.editVersion, p.name, p.secretPresent])
  useEffect(() => { if (!p.active) p.dialog.current?.close() }, [p.active, p.dialog])
  const disabled = !p.ready || p.busy || p.pending, mutable = p.page?.canConfigure && p.selected?.state !== 'REVOKED'
  const saveDisabled = disabled || !mutable || !p.name.trim() || (p.selected
    ? !p.secretPresent && p.name === p.selected.name || p.secretPresent && !p.page?.secretWriteAvailable
    : !p.secretPresent || !p.page?.secretWriteAvailable)
  return <dialog ref={p.dialog} className="model-drawer source-drawer source-setup-drawer source-credential-drawer" aria-label="接入凭据" onCancel={event => { if (p.busy || p.pending) event.preventDefault() }} onClose={p.closed}>
    <header className="model-drawer-heading source-setup-heading"><div><div className="model-eyebrow">接入凭据</div><h3>{p.selected?.name ?? '新增凭据'}</h3></div><button type="button" className="model-close" aria-label="关闭凭据维护" disabled={p.busy || p.pending} onClick={() => p.dialog.current?.close()}><X size={18}/></button></header>
    <div className="source-instance-tabs"><IntegrationViewTabs label="凭据维护视图" value={tab} items={[{ id: 'config', label: '凭据配置' }, ...(p.selected ? [{ id: 'versions' as const, label: '版本历史' }] : [])]} change={value => { setView({ id: p.selected?.id, tab: value }); body.current?.scrollTo({ top: 0 }); if (value === 'versions' && p.versions === null && !p.historyAttempted && !disabled) p.versionsRead() }}/></div>
    <div className="model-drawer-body source-setup-body" ref={body}><div hidden={tab !== 'config'}><fieldset className="model-form" disabled={disabled || !mutable}><label>凭据名称<Input aria-label="凭据名称" maxLength={80} value={p.name} onChange={event => p.nameChange(event.target.value)}/></label><label>{p.selected ? '新凭据值（留空保留当前版本）' : '凭据值'}<Input ref={p.secret} type="password" aria-label="凭据值" autoComplete="off" maxLength={4096} disabled={disabled || !mutable || !p.page?.secretWriteAvailable} onChange={event => p.secretChange(!!event.target.value)}/></label></fieldset>
      {p.selected ? <dl className="source-connection source-credential-summary"><dt>凭据标识</dt><dd><code>{p.selected.id}</code></dd><dt>当前版本</dt><dd>v{p.selected.revision}</dd><dt>版本标识</dt><dd><code>{p.selected.versionId}</code></dd><dt>状态</dt><dd>{p.selected.state === 'ACTIVE' ? '可管理' : '已撤销'}</dd></dl> : null}
      <p className="source-reference-note">提交后凭据值会清空。轮换追加新版本，旧版本可单独撤销；撤销不可恢复。</p>
      {p.selected && mutable ? <Button type="button" variant="outline" disabled={disabled || p.secretPresent || p.name !== p.selected.name} onClick={() => setConfirmation({})}>撤销全部版本</Button> : null}
    </div><div hidden={tab !== 'versions'}><div className="source-instance-history-heading"><h4>固定凭据版本</h4><Button type="button" variant="outline" disabled={disabled} onClick={p.versionsRead}>刷新凭据版本</Button></div>{p.versions ? <div className="integration-table-wrap"><table className="integration-table" aria-label="凭据版本"><thead><tr><th scope="col">版本</th><th scope="col">版本标识</th><th scope="col">创建时间</th><th scope="col">状态</th><th scope="col">操作</th></tr></thead><tbody>{p.versions.map(v => <tr key={v.pin.revision}><td>v{v.pin.revision}</td><td><code>{v.pin.versionId}</code></td><td>{new Date(v.createdAt).toLocaleString()}</td><td>{v.revoked ? '已撤销' : '可引用'}</td><td><Button type="button" variant="outline" disabled={disabled || !mutable || v.revoked || p.secretPresent || p.name !== p.selected?.name} aria-label={'撤销凭据版本 v' + v.pin.revision} onClick={() => setConfirmation({ revision: v.pin.revision })}>撤销版本</Button></td></tr>)}</tbody></table></div> : null}</div>
      {confirmation ? <div className="source-instance-confirm"><p>{confirmation.revision ? '撤销 v' + confirmation.revision : '撤销全部凭据版本'}后，已有固定引用将无法读取。历史保留，不能恢复。</p><Button type="button" variant="outline" disabled={disabled} onClick={() => setConfirmation(null)}>保留凭据</Button><Button type="button" disabled={disabled || !mutable} onClick={() => { p.revoke(confirmation.revision); setConfirmation(null) }}>确认撤销凭据</Button></div> : null}
      {p.error ? <p role="alert">{p.error}</p> : null}<p role="status">{p.busy ? '正在处理…' : p.notice}</p>{p.pending ? <p>提交结果待确认，请查询原请求；凭据值已清空。</p> : null}
    </div><footer className="model-drawer-footer source-setup-footer">{p.pending ? <Button type="button" variant="outline" disabled={p.busy || !p.ready} onClick={p.lookup}>查询原凭据回执</Button> : tab === 'config' ? <><Button type="button" variant="outline" disabled={disabled} onClick={p.reset}>{p.selected ? '放弃修改并重读凭据' : '放弃凭据输入'}</Button><Button type="button" disabled={saveDisabled} onClick={p.save}>{p.selected ? p.secretPresent ? '保存新凭据版本' : '保存凭据名称' : '保存凭据'}</Button></> : null}</footer>
  </dialog>
}
