import { SourceMetricPageResults } from './SourceMetricPageResults.tsx'
import { SourceMetricDiscoveryResults } from './SourceMetricDiscoveryResults.tsx'
import { Button } from '../ui/button.tsx'
import { useEffect, useState } from 'react'
import type { InspectionKind, InspectionView } from '../../api/source-inspections.ts'
const states = { CURRENT: '当前配置', STALE: '配置已变化', EXPIRED: '已过期', UNVERIFIED: '未确认可复用' }
const types: Record<string, string> = { TEXT: '文本', NUMBER: '数值', BOOLEAN: '布尔值', TEXT_ARRAY: '文本数组', NULL: '缺失', MIXED: '混合类型' }
export function SourceInspectionResults(p: { items: InspectionView[] | null; busy: boolean; canRun: boolean; ready: boolean; pending: boolean; run: (kind: InspectionKind) => void; read: () => void; previous: (v: InspectionView) => void; next: (v: InspectionView) => void }) {
  const [now, setNow] = useState(Date.now())
  useEffect(() => { const current = Date.now(); const next = Math.min(...(p.items ?? []).map(v => Math.min(Date.parse(v.inspection.expiresAt ?? ''), Date.parse(v.inspection.metricPage?.manifest?.expiresAt ?? v.inspection.expiresAt ?? ''))).filter(at => Number.isFinite(at) && at > current)); if (!Number.isFinite(next)) return; const timer = window.setTimeout(() => setNow(Date.now()), Math.min(next - current + 1, 2147483647)); return () => clearTimeout(timer) }, [p.items, now])
  return <section className="source-inspection-results" aria-label="连接测试与来源发现"><div className="source-instance-history-heading"><h4>连接与发现</h4><Button type="button" variant="outline" disabled={!p.ready || p.busy || p.pending} onClick={p.read}>刷新测试与发现记录</Button></div><div className="source-inspection-actions"><Button type="button" variant="outline" disabled={!p.canRun || p.busy || p.pending} onClick={() => p.run('TEST')}>测试保存的连接</Button><Button type="button" variant="outline" disabled={!p.canRun || p.busy || p.pending} onClick={() => p.run('DISCOVER')}>发现来源字段</Button><Button type="button" variant="outline" disabled={!p.canRun || p.busy || p.pending} onClick={() => p.run('DISCOVER_METRIC_PAGE')}>发现来源指标</Button></div>
    {p.items === null ? <p>{p.busy ? '正在读取测试和发现记录…' : '尚未读取测试和发现记录。'}</p> : !p.items.length ? <p>暂无测试或发现记录。</p> : p.items.filter((v, index, all) => !v.inspection.metricPage?.manifest || all.findIndex(row => row.inspection.metricPage?.manifest?.snapshotId === v.inspection.metricPage?.manifest?.snapshotId) === index).map(v => { const i = v.inspection, validity = i.expiresAt && Math.min(Date.parse(i.expiresAt), Date.parse(i.metricPage?.manifest?.expiresAt ?? i.expiresAt)) <= Date.now() ? 'EXPIRED' : v.validity; return <article className="source-inspection-result" key={i.requestId}><header><strong>{i.kind === 'TEST' ? '连接测试' : i.kind === 'DISCOVER_METRICS' || i.kind === 'DISCOVER_METRIC_PAGE' ? '指标发现' : '字段发现'} · v{i.configurationRevision}</strong><span className="model-pill">{states[validity]}</span></header><dl className="source-connection"><dt>来源模式</dt><dd>{i.dataMode === 'fixture' ? 'Fixture · 合成自检' : 'Zabbix 连接'}</dd><dt>开始时间</dt><dd><time dateTime={i.asOf}>{new Date(i.asOf).toLocaleString()}</time></dd><dt>结果时间</dt><dd>{i.availableAt ? <time dateTime={i.availableAt}>{new Date(i.availableAt).toLocaleString()}</time> : i.state === 'PENDING' ? '处理中' : '结果未知'}</dd><dt>连接摘要</dt><dd><code>{i.connectionDigest}</code></dd></dl>
      {i.check ? <p>{i.check.statusCode === 'UNREACHABLE' ? '连接或授权读取失败' : i.check.statusCode === 'UNVERIFIED' ? '来源响应，但读取范围未验证' : i.dataMode === 'fixture' ? 'Fixture 读取通过' : '本次授权读取通过'}{i.check.reportedVersion ? ' · 来源报告版本 ' + i.check.reportedVersion : ''}</p> : null}
      {i.discovery ? <><p>{i.discovery.statusCode === 'UNREACHABLE' ? '字段读取失败' : i.discovery.complete ? '已覆盖当前主机清单' : '发现不完整，仅覆盖首个主机分页'} · 本次读取 {i.discovery.observedRecords} 条，最多 5 条。原始来源字段与工作流批次字段分别定义。</p><div className="integration-table-wrap"><table className="integration-table" aria-label="发现的来源字段"><thead><tr><th scope="col">字段路径</th><th scope="col">观察到的类型</th><th scope="col">样本存在缺失</th></tr></thead><tbody>{i.discovery.fields.map(f => <tr key={f.name}><td><code>{f.name}</code></td><td>{types[f.type]}</td><td>{f.nullable ? '是' : '否'}</td></tr>)}</tbody></table></div><p className="source-reference-note">发现结果不删除已有字段或修改映射；字段指纹变化后需重新核对映射。</p><code className="source-inspection-fingerprint">{i.discovery.fingerprint}</code></> : null}
      {i.metricPage ? <SourceMetricPageResults value={i.metricPage} previousId={i.previousRequestId ?? null} busy={p.busy || p.pending} canNext={p.canRun && validity === 'CURRENT'} previous={() => p.previous(v)} next={() => p.next(v)}/> : null}
      {i.metricDiscovery ? <SourceMetricDiscoveryResults value={i.metricDiscovery}/> : null}
    </article> })}
  </section>
}
