import { createEffect, createSignal, onCleanup, Show } from '@zeus-js/zeus'
import type { Graph } from '@antv/g6'
export type RelationNode={id:string;label:string;detail:string}
export type RelationLink={id:string;source:string;target:string;label:string}
export function RelationGraph(props:{nodes:()=>RelationNode[];edges:()=>RelationLink[];selected:()=>string;select:(id:string)=>void;label:string}){
 const [status,setStatus]=createSignal('loading');let host:HTMLDivElement|null=null;let graph:Graph|undefined;let disposed=false;let observer:ResizeObserver|undefined;let themeObserver:MutationObserver|undefined;let sequence=0;let chain=Promise.resolve();let signature='';
 function paint(){const nodes=props.nodes(),edges=props.edges(),selected=props.selected();if(!graph||disposed)return;const next=JSON.stringify([nodes,edges,selected,document.documentElement.dataset.theme]);if(next===signature)return;signature=next;const version=++sequence;const g=graph;
  chain=chain.then(async()=>{if(disposed||version!==sequence)return;setStatus('loading');const css=getComputedStyle(document.documentElement);g.setOptions({node:{type:'rect',style:{size:[180,62],radius:9,fill:css.getPropertyValue('--surface').trim(),stroke:css.getPropertyValue('--line').trim(),lineWidth:1.5,labelText:d=>String(d.data?.label??''),labelFill:css.getPropertyValue('--ink').trim(),labelFontSize:16,labelPlacement:'center'},state:{selected:{stroke:css.getPropertyValue('--accent').trim(),lineWidth:2.5,fill:css.getPropertyValue('--accent-soft').trim()}}},edge:{type:'cubic-horizontal',style:{stroke:css.getPropertyValue('--graph-edge').trim(),lineWidth:1.5,endArrow:true,labelText:d=>String(d.data?.label??''),labelFontSize:13,labelFill:css.getPropertyValue('--muted').trim(),labelBackground:true,labelBackgroundFill:css.getPropertyValue('--surface').trim()}}});g.setData({nodes:nodes.map(n=>({id:n.id,data:{label:n.label},states:n.id===selected?['selected']:[]})),edges:edges.map(e=>({id:e.id,source:e.source,target:e.target,data:{label:e.label}}))});await g.render();if(!disposed&&version===sequence)setStatus('ready');}).catch(()=>{if(!disposed)setStatus('error')})
 }
 async function init(node:HTMLDivElement|null){host=node;if(!node)return;try{const {Graph}=await import('@antv/g6');if(disposed||!host)return;graph=new Graph({container:host,width:Math.max(300,host.clientWidth),height:host.clientHeight||470,animation:false,padding:36,autoFit:'view',zoomRange:[.2,2],layout:{type:'antv-dagre',rankdir:'LR',nodesep:34,ranksep:100},behaviors:['drag-canvas','zoom-canvas','drag-element']});graph.on('node:click',e=>{const target='target' in e?e.target:undefined;const id=target&&'id' in target?target.id:undefined;if(typeof id==='string')props.select(id)});observer=new ResizeObserver(()=>{if(!disposed&&graph&&host?.clientWidth)graph.setSize(host.clientWidth,host.clientHeight)});observer.observe(host);themeObserver=new MutationObserver(paint);themeObserver.observe(document.documentElement,{attributes:true,attributeFilter:['data-theme']});paint()}catch{if(!disposed)setStatus('error')}}
 createEffect(paint);onCleanup(()=>{disposed=true;++sequence;observer?.disconnect();themeObserver?.disconnect();graph?.destroy();graph=undefined});
 function zoom(factor:number){if(graph&&status()==='ready')void graph.zoomBy(factor,false)}
 return <div class="relation-graph-frame" data-engine="g6" data-graph-status={status()}><div class="graph-tools"><span>{props.nodes().length+' 个节点 · '+props.edges().length+' 条关系'}</span><div><button type="button" aria-label="缩小关系图" disabled={status()!=='ready'} onClick={()=>zoom(.8)}>−</button><button type="button" aria-label="放大关系图" disabled={status()!=='ready'} onClick={()=>zoom(1.25)}>＋</button><button type="button" disabled={status()!=='ready'} onClick={()=>void graph?.fitView(undefined,false)}>适应视图</button></div></div><div class="relation-graph" role="img" aria-label={props.label} ref={node=>void init(node)} /><Show when={status()!=='ready'}><div class="graph-message" role="status">{status()==='error'?'关系图加载失败，请刷新重试。':'正在绘制关系图…'}</div></Show><div class="graph-caption">点击节点查看详情 · 拖动画布平移 · 滚轮缩放</div></div>
}
