import { test,expect,type Page } from '@playwright/test'
import {readFileSync} from 'node:fs'
import {TOKEN_OK} from './helpers.ts'
const example=JSON.parse(readFileSync(new URL('../../../contracts/examples/entity-topology.json',import.meta.url),'utf8'))
const bundle=JSON.parse(readFileSync(new URL('../../../contracts/catalog/opsweave-core-1.0.0.json',import.meta.url),'utf8'))
async function fixture(page:Page,payload:any=example){const calls:string[]=[];await page.route('**/api/v1/entities/**',async route=>{const url=new URL(route.request().url());calls.push(route.request().method()+' '+url.pathname);if(url.pathname.endsWith('/topology')){await route.fulfill({json:payload});return}await route.fulfill({json:{storage:'memory',query:{q:'',type:'',lifecycle:'',after:null,limit:25},nextCursor:null,items:[{schemaVersion:'1.0',id:example.centerId,tenantId:example.tenantId,entityType:'Service',name:'Fixture service',lifecycle:'ACTIVE',version:1,attributes:{dataMode:'labeled-fixture'}}]}})});await page.goto('/#/inventory/topology');await page.getByRole('textbox',{name:'平台开发 Token（仅保存在当前标签页内存）'}).fill(TOKEN_OK);await page.getByRole('button',{name:'读取资产',exact:true}).click();await page.locator('.topology-asset').click();return calls}
for(const width of [1500,390])test('G6 actual canvas uses labeled fixture relationships at '+width,async({page})=>{await page.setViewportSize({width,height:1000});const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));const calls=await fixture(page);await expect(page.locator('[data-engine=g6]')).toHaveAttribute('data-graph-status','ready');await expect(page.locator('.relation-graph canvas').first()).toBeVisible();await expect(page.locator('.relation-table-wrap')).toContainText('runs_on');await expect(page.locator('.relation-table-wrap')).toContainText('Fixture · 合成数据');await page.locator('.graph-node-list').getByRole('button',{name:'Fixture host'}).click();await expect(page.locator('.topology-detail')).toContainText(example.nodes[1].id);await page.getByRole('button',{name:'放大关系图'}).click();await page.getByRole('button',{name:'适应视图'}).click();await page.getByRole('button',{name:'切换到深色模式'}).click();await expect(page.locator('[data-engine=g6]')).toHaveAttribute('data-graph-status','ready');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);expect(calls.every(c=>c.startsWith('GET '))).toBe(true);await page.getByRole('textbox',{name:'平台开发 Token（仅保存在当前标签页内存）'}).fill('changed-fixture-token-1234567890');await expect(page.locator('[data-engine=g6]')).toHaveCount(0);await expect(page.locator('.topology-main')).not.toContainText('Fixture host');expect(errors).toEqual([])})
test('empty stored neighborhood stays empty and malformed foreign endpoint fails closed',async({page})=>{const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));const empty={...example,nodes:[example.nodes[0]],edges:[]};await fixture(page,empty);await expect(page.getByText('该资产目前没有可展示的已保存关系。关系类型定义不会自动生成资产之间的关系。')).toBeVisible();await expect(page.locator('[data-engine=g6]')).toHaveAttribute('data-graph-status','ready');await page.route('**/api/v1/entities/*/topology',r=>r.fulfill({json:{...example,edges:[{...example.edges[0],to:'90000000-0000-4000-8000-000000000009'}]}}));await page.locator('.topology-asset').click();await expect(page.getByRole('alert')).toContainText('不符合契约');await expect(page.locator('[data-engine=g6]')).toHaveCount(0);expect(errors).toEqual([])})
test('start page and maintenance menus reach distinct workflows without requests',async({page})=>{const calls:string[]=[];page.on('request',r=>{if(r.url().includes('/api/'))calls.push(r.url())});await page.goto('/');await expect(page.getByRole('heading',{name:'运维工作台',exact:true})).toBeVisible();await page.getByRole('link',{name:'接入数据源',exact:true}).click();await expect(page).toHaveURL(/integrations\/sources/);await expect(page.locator('.page-pane:not([hidden])').getByRole('heading',{name:'数据源中心',exact:true})).toBeVisible();const nav=page.getByRole('navigation',{name:'产品模块'});await expect(nav.getByRole('link',{name:'Host 采集维护',exact:true})).not.toBeVisible();await expect(nav.getByRole('button',{name:'接入维护',exact:true})).toHaveCount(0);await page.goto('/#/integrations/pipelines');await expect(page.locator('.page-pane:not([hidden])').getByRole('heading',{name:'Host 接入流水线',exact:true})).toBeVisible();expect(calls).toEqual([])})
test('model relationship G6 diagram is explicitly a definition view',async({page})=>{await page.route('**/api/v1/catalog',route=>route.fulfill({json:{schemaVersion:'1.0',storage:'memory',package:bundle,drafts:{items:[],truncated:false},published:{items:[],truncated:false}}}));await page.goto('/#/modeling/relations');await page.getByRole('textbox',{name:'平台开发 Token（仅保存在当前标签页内存）'}).fill(TOKEN_OK);await page.locator('summary',{hasText:'模型关系图'}).click();await expect(page.getByRole('heading',{name:'关系类型示意',exact:true})).toBeVisible();await expect(page.locator('[data-engine=g6]')).toHaveAttribute('data-graph-status','ready');await expect(page.locator('.model-graph-panel')).toContainText('实际资产之间的关系请到资产关系图查看');await expect(page.locator('.model-graph-panel .graph-tools')).toContainText('4 条关系')})
