import { test, expect } from '@playwright/test'
import { TOKEN_OK } from './helpers.ts'
import { ROUTES } from '../src/state/routes.ts'

test.beforeEach(async ({ page }) => { await page.addInitScript(() => localStorage.setItem('opsweave.ui.layout', 'standard')) })

for (const width of [1440, 1024, 390]) {
  test('all product pages remain readable in both themes at ' + width + 'px', async ({ page }) => {
    await page.setViewportSize({ width, height: 900 })
    await page.emulateMedia({ colorScheme: 'light' })
    const errors: string[] = []
    const calls: string[] = []
    page.on('pageerror', error => errors.push(error.message))
    page.on('request', request => { if (request.url().includes('/api/')) calls.push(request.url()) })
    await page.goto('/#/start')
    for (const route of ROUTES.filter(item => item.navigation !== false)) {
      await page.goto('/#' + route.path)
      const main = page.getByRole('main')
      await expect(main.getByRole('heading').first()).toBeVisible()
      const breadcrumb = page.getByRole('navigation', { name: '当前位置' })
      await expect(breadcrumb.locator('[aria-current=page]')).toHaveText(route.label)
      await expect(page.getByRole('tablist', { name: '已打开页面' })).toHaveCount(0)
      for (const theme of ['dark', 'light']) {
        await page.getByRole('button', { name: theme === 'dark' ? '切换到深色模式' : '切换到浅色模式' }).click()
        await expect(page.locator('html')).toHaveAttribute('data-theme', theme)
        expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), route.path + ' ' + theme).toBe(true)
        const bounds = await main.boundingBox()
        expect(bounds!.width, route.path + ' content width').toBeGreaterThan(width === 390 ? 300 : 600)
        const header = (await page.getByRole('banner').boundingBox())!
        const trail = (await breadcrumb.boundingBox())!
        const panel = (await main.locator('.page-pane').boundingBox())!
        expect(header.y + header.height).toBeLessThanOrEqual(trail.y)
        expect(trail.y + trail.height).toBeLessThanOrEqual(panel.y)
        expect(trail.height).toBeLessThanOrEqual(width === 390 ? 32 : 36)
        expect(await breadcrumb.locator('ol').evaluate(element => element.getBoundingClientRect().left)).toBeCloseTo(panel.x, 0)
      }
    }
    expect(errors).toEqual([])
    expect(calls).toEqual([])
  })
}

for (const width of [1440, 390]) {
  test('navigation remains accessible and bounded at ' + width + 'px', async ({ page }) => {
    await page.setViewportSize({ width, height: 900 })
    await page.goto('/#/inventory')
    if (width === 390) await page.getByRole('button', { name: '切换导航', exact: true }).click()
    const nav = page.getByRole('navigation', { name: '产品模块' })
    await expect(nav.getByRole('link', { includeHidden: true })).toHaveCount(15)
    const asset = nav.getByRole('link', { name: '资产', exact: true })
    await expect(asset).toHaveAttribute('aria-current', 'page')
    await nav.getByRole('button', { name: 'AI 管理', exact: true }).click()
    await nav.getByRole('link', { name: 'AI 数据留存', exact: true }).click()
    await expect(page).toHaveURL(/#\/ai\/retention$/)
    if (width === 390) {
      await expect(page.getByRole('dialog', { name: '移动端导航' })).not.toBeVisible()
      await expect(page.getByRole('button', { name: '切换导航', exact: true })).toBeFocused()
      await page.getByRole('button', { name: '切换导航', exact: true }).click()
    }
    await expect(nav.getByRole('link', { name: 'AI 数据留存', exact: true })).toHaveAttribute('aria-current', 'page')
    await expect(asset).not.toHaveAttribute('aria-current', 'page')
    await expect(nav.getByRole('link', { name: 'Fixture 诊断演示' })).not.toBeVisible()
    await expect(nav.getByRole('button', { name: '开发演示', exact: true })).toHaveCount(0)
    await expect(nav.getByRole('link', { name: 'AI 执行记录', includeHidden: true })).toHaveCount(0)
    if (width === 390) await page.keyboard.press('Escape')
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
    await page.getByRole('button', { name: '跳到主要内容' }).focus()
    await page.keyboard.press('Enter')
    await expect(page.locator('main')).toBeFocused()
    await expect(page).toHaveURL(/#\/ai\/retention$/)
  })
}

test('collapsed sidebar keeps all routes reachable and the active page labelled', async ({ page }) => {
  await page.setViewportSize({ width: 1440, height: 900 })
  await page.goto('/#/inventory')
  const workspace = page.locator('.workspace')
  const before = await workspace.boundingBox()
  await page.getByRole('button', { name: '收起导航', exact: true }).click()
  const after = await workspace.boundingBox()
  expect(after!.width).toBeGreaterThan(before!.width)
  const nav = page.getByRole('navigation', { name: '产品模块' })
  await expect(nav.getByRole('button')).toHaveCount(6)
  await expect(nav.getByRole('link')).toHaveCount(0)
  await nav.getByRole('button', { name: '资源观测', exact: true }).click()
  await nav.getByRole('link', { name: '指标', exact: true }).click()
  await expect(page).toHaveURL(/#\/metrics$/)
  await nav.getByRole('button', { name: '资源观测', exact: true }).click()
  await expect(nav.getByRole('link', { name: '指标', exact: true })).toHaveAttribute('aria-current', 'page')
  await page.setViewportSize({ width: 390, height: 900 })
  await page.getByRole('button', { name: '切换导航', exact: true }).click()
  await expect(page.getByRole('dialog', { name: '移动端导航' }).getByRole('link', { name: '资产', exact: true })).toBeVisible()
  await page.getByRole('dialog', { name: '移动端导航' }).getByRole('link', { name: '观织 OpsWeave 首页' }).click()
  await expect(page).toHaveURL(/#\/start$/)
  await expect(page.getByRole('dialog', { name: '移动端导航' })).not.toBeVisible()
})

test('page finder supports keyboard navigation and never queries business data', async ({ page }) => {
  const calls: string[] = []
  page.on('request', request => { if (request.url().includes('/api/')) calls.push(request.url()) })
  await page.goto('/#/inventory')
  const trigger = page.getByRole('button', { name: '搜索页面', exact: true })
  await trigger.focus()
  await page.keyboard.press('Control+k')
  const dialog = page.getByRole('dialog', { name: '跳转到页面' })
  const input = dialog.getByRole('textbox', { name: '页面名称或路径' })
  await expect(input).toBeFocused()
  await input.fill('留存')
  await expect(dialog.getByRole('link')).toHaveCount(1)
  await page.keyboard.press('ArrowDown')
  await expect(dialog.getByRole('link', { name: /AI 数据留存/ })).toBeFocused()
  await page.keyboard.press('Enter')
  await expect(page).toHaveURL(/#\/ai\/retention$/)
  await expect(dialog).not.toBeVisible()
  await expect(trigger).toBeFocused()
  await trigger.click()
  await input.fill('没有这个页面')
  await expect(dialog.getByText('没有匹配的页面，请尝试其他名称。')).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(trigger).toBeFocused()
  expect(calls).toEqual([])
})

test('theme preference persists while credentials and asset data clear on reload', async ({ page }) => {
  await page.emulateMedia({ colorScheme: 'light' })
  await page.goto('/#/inventory')
  const token = page.getByRole('textbox', { name: '平台开发 Token（仅保存在当前标签页内存）' })
  await token.fill(TOKEN_OK)
  await page.getByRole('button', { name: '切换到深色模式' }).click()
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'dark')
  await page.reload()
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'dark')
  await expect(token).toHaveValue('')
  await expect(page.locator('[data-stat="total"]')).toHaveText('—')
  const stored = await page.evaluate(() => ({ local: { ...localStorage }, session: { ...sessionStorage } }))
  expect(stored).toEqual({ local: { 'opsweave.ui.theme': 'dark', 'opsweave.ui.layout': 'standard' }, session: {} })
  await page.getByRole('button', { name: '切换到浅色模式' }).click()
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'light')
})

test('collapsed groups follow finder navigation, history and direct links', async ({ page }) => {
  await page.goto('/#/inventory')
  const nav = page.getByRole('navigation', { name: '产品模块' })
  const model = nav.getByRole('button', { name: '模型中心', exact: true })
  await expect(model).toHaveAttribute('aria-expanded', 'false')
  await model.focus()
  await page.keyboard.press('Enter')
  await expect(model).toHaveAttribute('aria-expanded', 'true')
  await page.keyboard.press('Enter')
  await expect(model).toHaveAttribute('aria-expanded', 'false')
  await expect(nav.getByRole('link', { name: '关系模型', exact: true })).not.toBeVisible()
  await page.getByRole('button', { name: '搜索页面', exact: true }).click()
  const finder = page.getByRole('dialog', { name: '跳转到页面' })
  await finder.getByRole('textbox').fill('模型中心 关系')
  await expect(finder.getByRole('link')).toHaveCount(1)
  await finder.getByRole('link').click()
  await expect(model).toHaveAttribute('aria-expanded', 'true')
  await expect(nav.getByRole('link', { name: '关系模型', exact: true })).toHaveAttribute('aria-current', 'page')
  await expect(page.locator('.breadcrumb')).toHaveText('模型中心/关系模型')
  await nav.getByRole('button', { name: '资源观测', exact: true }).click()
  await page.goBack()
  await expect(nav.getByRole('button', { name: '资源观测', exact: true })).toHaveAttribute('aria-expanded', 'true')
  await expect(page.locator('.breadcrumb')).toHaveText('资源观测/资产')
  await page.goto('/#/incidents/reorganize')
  await expect(nav.getByRole('button', { name: '故障诊断', exact: true })).toHaveAttribute('aria-expanded', 'true')
  await expect(nav.getByRole('link', { name: '告警归属调整', exact: true })).toHaveAttribute('aria-current', 'page')
})

test('rail keeps every destination and mobile uses its own group controls', async ({ page }) => {
  await page.goto('/#/inventory')
  const nav = page.getByRole('navigation', { name: '产品模块' })
  await expect(nav.getByRole('button', { name: '模型中心', exact: true })).toHaveAttribute('aria-expanded', 'false')
  await page.getByRole('button', { name: '收起导航', exact: true }).click()
  await expect(nav.getByRole('link', { includeHidden: true })).toHaveCount(15)
  await nav.getByRole('button', { name: 'AI 管理', exact: true }).click()
  await nav.getByRole('link', { name: 'AI 数据留存', exact: true }).click()
  await expect(page.locator('.breadcrumb')).toHaveText('AI 管理/AI 数据留存')
  await page.getByRole('button', { name: '展开导航', exact: true }).click()
  await expect(nav.getByRole('button', { name: '模型中心', exact: true })).toHaveAttribute('aria-expanded', 'false')
  await expect(nav.getByRole('button', { name: 'AI 管理', exact: true })).toHaveAttribute('aria-expanded', 'true')
  await page.getByRole('button', { name: '收起导航', exact: true }).click()
  await page.setViewportSize({ width: 390, height: 650 })
  await page.getByRole('button', { name: '切换导航', exact: true }).click()
  const drawer = page.getByRole('dialog', { name: '移动端导航' })
  await expect(drawer.getByRole('button', { name: '模型中心', exact: true })).toBeVisible()
  await expect(drawer.getByRole('button', { name: 'AI 管理', exact: true })).toHaveAttribute('aria-expanded', 'true')
  await drawer.getByRole('link', { name: 'AI 数据留存', exact: true }).click()
  await expect(drawer).not.toBeVisible()
  await expect(page.getByRole('button', { name: '切换导航', exact: true })).toBeFocused()
})

test('rail flyouts support keyboard entry, Escape and outside dismissal', async ({ page }) => {
  await page.emulateMedia({ colorScheme: 'light' })
  await page.goto('/#/inventory')
  await page.getByRole('button', { name: '收起导航', exact: true }).click()
  const nav = page.getByRole('navigation', { name: '产品模块' })
  const model = nav.getByRole('button', { name: '模型中心', exact: true })
  await model.focus()
  await page.keyboard.press('ArrowRight')
  await expect(nav.getByRole('link', { name: '实体模型', exact: true })).toBeFocused()
  await page.keyboard.press('Tab')
  await expect(nav.getByRole('link', { name: '指标定义', exact: true })).toBeFocused()
  await page.keyboard.press('Escape')
  await expect(model).toBeFocused()
  await expect(model).toHaveAttribute('aria-expanded', 'false')
  await page.keyboard.press('Enter')
  await expect(nav.getByRole('link', { name: '关系模型', exact: true })).toBeVisible()
  await page.getByRole('button', { name: '切换到深色模式', exact: true }).click()
  await expect(model).toHaveAttribute('aria-expanded', 'false')
  await model.focus()
  await page.keyboard.press('ArrowDown')
  await expect(nav.getByRole('link', { name: '实体模型', exact: true })).toBeFocused()
  await page.keyboard.press('Tab')
  await page.keyboard.press('Tab')
  await page.keyboard.press('Tab')
  await expect(nav.getByRole('button', { name: '资源观测', exact: true })).toBeFocused()
  await expect(model).toHaveAttribute('aria-expanded', 'false')
})

test('rail hover flyouts stay inside a short viewport and close when resized', async ({ page }) => {
  await page.setViewportSize({ width: 1024, height: 300 })
  await page.goto('/#/inventory')
  await page.getByRole('button', { name: '收起导航', exact: true }).click()
  const nav = page.getByRole('navigation', { name: '产品模块' })
  const integration = nav.getByRole('button', { name: '数据接入', exact: true })
  await integration.hover()
  await expect(nav.getByRole('link', { name: '采集运行记录', exact: true })).toBeVisible()
  const flyout = page.locator('.nav-flyout:visible')
  const bounds = await flyout.boundingBox()
  expect(bounds!.x).toBeGreaterThan(64)
  expect(bounds!.y).toBeGreaterThanOrEqual(8)
  expect(bounds!.y + bounds!.height).toBeLessThanOrEqual(292)
  await nav.getByRole('link', { name: '数据源中心', exact: true }).hover()
  await expect(integration).toHaveAttribute('aria-expanded', 'true')
  const afterHover = await flyout.boundingBox()
  expect(afterHover!.y + afterHover!.height).toBeLessThanOrEqual(292)
  await page.getByRole('heading', { name: '资产', exact: true }).hover()
  await expect(flyout).not.toBeVisible()
  await integration.hover()
  await expect(flyout).toBeVisible()
  await page.setViewportSize({ width: 390, height: 650 })
  await expect(flyout).not.toBeVisible()
  await page.getByRole('button', { name: '切换导航', exact: true }).click()
  await expect(page.getByRole('dialog', { name: '移动端导航' }).getByRole('link', { name: '数据源中心', exact: true })).toBeVisible()
})

test('every product destination can be opened from its rail group without API calls', async ({ page }) => {
  const calls: string[] = []
  page.on('request', request => { if (request.url().includes('/api/')) calls.push(request.url()) })
  await page.goto('/#/inventory')
  await page.getByRole('button', { name: '收起导航', exact: true }).click()
  const nav = page.getByRole('navigation', { name: '产品模块' })
  for (const route of ROUTES.filter(item => item.navigation !== false)) {
    const group = nav.locator('[data-nav-group="' + route.group + '"]')
    await group.getByRole('button').click()
    await group.getByRole('link', { name: route.label, exact: true }).click()
    await expect(page).toHaveURL(new RegExp('#' + route.path + '$'))
    await expect(page.getByRole('main').getByRole('heading').first()).toBeVisible()
  }
  expect(calls).toEqual([])
})

test('finder matches business terms, groups and existing paths without making API calls', async ({ page }) => {
  const calls: string[] = []
  page.on('request', request => { if (request.url().includes('/api/')) calls.push(request.url()) })
  await page.goto('/#/inventory')
  await page.getByRole('button', { name: '搜索页面', exact: true }).click()
  const finder = page.getByRole('dialog', { name: '跳转到页面' })
  const input = finder.getByRole('textbox')
  await input.fill('技能')
  await expect(finder.getByRole('link')).toHaveCount(0)
  await input.fill('  ZABBIX  采集 ')
  await expect(finder.getByRole('link')).toHaveCount(1)
  await expect(finder.getByRole('link', { name: /采集运行记录/ })).toBeVisible()
  await expect(finder.getByRole('link', { name: /Host 采集维护/ })).toHaveCount(0)
  await input.fill('模型中心')
  await expect(finder.getByRole('link')).toHaveCount(3)
  await input.fill('/incidents/diagnose')
  await expect(finder.getByRole('link')).toHaveCount(0)
  await input.fill('AI 执行记录')
  await expect(finder.getByRole('link')).toHaveCount(0)
  expect(calls).toEqual([])
})
