import { test, expect } from '@playwright/test'
import { TOKEN_OK } from './helpers.ts'

for (const width of [1440, 390]) {
  test('navigation remains accessible and bounded at ' + width + 'px', async ({ page }) => {
    await page.setViewportSize({ width, height: 900 })
    await page.goto('/#/inventory')
    if (width === 390) await page.getByRole('button', { name: '切换导航', exact: true }).click()
    const nav = page.getByRole('navigation', { name: '产品模块' })
    await expect(nav.getByRole('link', { includeHidden: true })).toHaveCount(21)
    const asset = nav.getByRole('link', { name: '资产', exact: true })
    await expect(asset).toHaveAttribute('aria-current', 'page')
    await nav.getByRole('button', { name: 'AI 管理', exact: true }).click()
    await nav.getByRole('link', { name: 'AI 数据留存', exact: true }).click()
    await expect(page).toHaveURL(/#\/ai\/retention$/)
    if (width === 390) {
      await expect(page.getByRole('dialog', { name: '移动端导航' })).not.toBeVisible()
      await expect(page.getByRole('button', { name: '切换导航', exact: true })).toBeFocused()
      await page.getByRole('button', { name: '切换导航', exact: true }).click()
    }
    await expect(nav.getByRole('link', { name: 'AI 数据留存', exact: true })).toHaveAttribute('aria-current', 'page')
    await expect(asset).not.toHaveAttribute('aria-current', 'page')
    await expect(nav.getByRole('link', { name: 'Fixture 诊断演示' })).not.toBeVisible()
    await nav.getByRole('button', { name: '开发演示', exact: true }).click()
    await expect(nav.getByRole('link', { name: 'Fixture 诊断演示' })).toBeVisible()
    if (width === 390) await page.keyboard.press('Escape')
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
    await page.getByRole('button', { name: '跳到主要内容' }).focus()
    await page.keyboard.press('Enter')
    await expect(page.locator('main')).toBeFocused()
    await expect(page).toHaveURL(/#\/ai\/retention$/)
  })
}

test('collapsed sidebar keeps all routes reachable and the active page labelled', async ({ page }) => {
  await page.setViewportSize({ width: 1440, height: 900 })
  await page.goto('/#/inventory')
  const workspace = page.locator('.workspace')
  const before = await workspace.boundingBox()
  await page.getByRole('button', { name: '切换导航', exact: true }).click()
  const after = await workspace.boundingBox()
  expect(after!.width).toBeGreaterThan(before!.width)
  const nav = page.getByRole('navigation', { name: '产品模块' })
  await expect(nav.getByRole('link')).toHaveCount(21)
  await nav.getByRole('link', { name: '指标', exact: true }).click()
  await expect(page).toHaveURL(/#\/metrics$/)
  await expect(nav.getByRole('link', { name: '指标', exact: true })).toHaveAttribute('aria-current', 'page')
  await page.setViewportSize({ width: 390, height: 900 })
  await page.getByRole('button', { name: '切换导航', exact: true }).click()
  await expect(page.getByRole('dialog', { name: '移动端导航' }).getByRole('link', { name: '资产', exact: true })).toBeVisible()
  await page.getByRole('dialog', { name: '移动端导航' }).getByRole('link', { name: '观织 OpsWeave 首页' }).click()
  await expect(page).toHaveURL(/#\/start$/)
  await expect(page.getByRole('dialog', { name: '移动端导航' })).not.toBeVisible()
})

test('page finder supports keyboard navigation and never queries business data', async ({ page }) => {
  const calls: string[] = []
  page.on('request', request => { if (request.url().includes('/api/')) calls.push(request.url()) })
  await page.goto('/#/inventory')
  const trigger = page.getByRole('button', { name: '搜索页面', exact: true })
  await trigger.focus()
  await page.keyboard.press('Control+k')
  const dialog = page.getByRole('dialog', { name: '跳转到页面' })
  const input = dialog.getByRole('textbox', { name: '页面名称或路径' })
  await expect(input).toBeFocused()
  await input.fill('留存')
  await expect(dialog.getByRole('link')).toHaveCount(1)
  await page.keyboard.press('ArrowDown')
  await expect(dialog.getByRole('link', { name: /AI 数据留存/ })).toBeFocused()
  await page.keyboard.press('Enter')
  await expect(page).toHaveURL(/#\/ai\/retention$/)
  await expect(dialog).not.toBeVisible()
  await expect(trigger).toBeFocused()
  await trigger.click()
  await input.fill('没有这个页面')
  await expect(dialog.getByText('没有匹配的页面，请尝试其他名称。')).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(trigger).toBeFocused()
  expect(calls).toEqual([])
})

test('theme preference persists while credentials and asset data clear on reload', async ({ page }) => {
  await page.emulateMedia({ colorScheme: 'light' })
  await page.goto('/#/inventory')
  const token = page.getByRole('textbox', { name: '平台开发 Token（仅保存在当前标签页内存）' })
  await token.fill(TOKEN_OK)
  await page.getByRole('button', { name: '切换到深色模式' }).click()
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'dark')
  await page.reload()
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'dark')
  await expect(token).toHaveValue('')
  await expect(page.locator('[data-stat="total"]')).toHaveText('—')
  const stored = await page.evaluate(() => ({ local: { ...localStorage }, session: { ...sessionStorage } }))
  expect(stored).toEqual({ local: { 'opsweave.ui.theme': 'dark' }, session: {} })
  await page.getByRole('button', { name: '切换到浅色模式' }).click()
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'light')
})

test('collapsed groups follow finder navigation, history and direct links', async ({ page }) => {
  await page.goto('/#/inventory')
  const nav = page.getByRole('navigation', { name: '产品模块' })
  const model = nav.getByRole('button', { name: '模型中心', exact: true })
  await expect(model).toHaveAttribute('aria-expanded', 'false')
  await model.focus()
  await page.keyboard.press('Enter')
  await expect(model).toHaveAttribute('aria-expanded', 'true')
  await page.keyboard.press('Enter')
  await expect(model).toHaveAttribute('aria-expanded', 'false')
  await expect(nav.getByRole('link', { name: '关系模型', exact: true })).not.toBeVisible()
  await page.getByRole('button', { name: '搜索页面', exact: true }).click()
  const finder = page.getByRole('dialog', { name: '跳转到页面' })
  await finder.getByRole('textbox').fill('模型中心 关系')
  await expect(finder.getByRole('link')).toHaveCount(1)
  await finder.getByRole('link').click()
  await expect(model).toHaveAttribute('aria-expanded', 'true')
  await expect(nav.getByRole('link', { name: '关系模型', exact: true })).toHaveAttribute('aria-current', 'page')
  await expect(page.locator('.breadcrumb')).toHaveText('模型中心/关系模型')
  await nav.getByRole('button', { name: '资源观测', exact: true }).click()
  await page.goBack()
  await expect(nav.getByRole('button', { name: '资源观测', exact: true })).toHaveAttribute('aria-expanded', 'true')
  await expect(page.locator('.breadcrumb')).toHaveText('资源观测/资产')
  await page.goto('/#/incidents/reorganize')
  await expect(nav.getByRole('button', { name: '故障诊断', exact: true })).toHaveAttribute('aria-expanded', 'true')
  await expect(nav.getByRole('link', { name: '告警归属调整', exact: true })).toHaveAttribute('aria-current', 'page')
})

test('rail keeps every destination and mobile uses its own group controls', async ({ page }) => {
  await page.goto('/#/inventory')
  const nav = page.getByRole('navigation', { name: '产品模块' })
  await expect(nav.getByRole('button', { name: '模型中心', exact: true })).toHaveAttribute('aria-expanded', 'false')
  await page.getByRole('button', { name: '切换导航', exact: true }).click()
  await expect(nav.getByRole('link')).toHaveCount(21)
  await nav.getByRole('link', { name: '诊断技能', exact: true }).click()
  await expect(page.locator('.breadcrumb')).toHaveText('AI 管理/诊断技能')
  await page.getByRole('button', { name: '切换导航', exact: true }).click()
  await expect(nav.getByRole('button', { name: '模型中心', exact: true })).toHaveAttribute('aria-expanded', 'false')
  await expect(nav.getByRole('button', { name: 'AI 管理', exact: true })).toHaveAttribute('aria-expanded', 'true')
  await page.getByRole('button', { name: '切换导航', exact: true }).click()
  await page.setViewportSize({ width: 390, height: 650 })
  await page.getByRole('button', { name: '切换导航', exact: true }).click()
  const drawer = page.getByRole('dialog', { name: '移动端导航' })
  await expect(drawer.getByRole('button', { name: '模型中心', exact: true })).toBeVisible()
  await expect(drawer.getByRole('button', { name: 'AI 管理', exact: true })).toHaveAttribute('aria-expanded', 'true')
  await drawer.getByRole('link', { name: 'AI 数据留存', exact: true }).click()
  await expect(drawer).not.toBeVisible()
  await expect(page.getByRole('button', { name: '切换导航', exact: true })).toBeFocused()
})

test('finder matches business terms, groups and existing paths without making API calls', async ({ page }) => {
  const calls: string[] = []
  page.on('request', request => { if (request.url().includes('/api/')) calls.push(request.url()) })
  await page.goto('/#/inventory')
  await page.getByRole('button', { name: '搜索页面', exact: true }).click()
  const finder = page.getByRole('dialog', { name: '跳转到页面' })
  const input = finder.getByRole('textbox')
  await input.fill('技能')
  await expect(finder.getByRole('link')).toHaveCount(1)
  await expect(finder.getByRole('link')).toContainText('诊断技能')
  await input.fill('  ZABBIX  采集 ')
  await expect(finder.getByRole('link')).toHaveCount(2)
  await expect(finder.getByRole('link', { name: /采集运行记录/ })).toBeVisible()
  await expect(finder.getByRole('link', { name: /Host 采集维护/ })).toBeVisible()
  await input.fill('模型中心')
  await expect(finder.getByRole('link')).toHaveCount(3)
  await input.fill('/incidents/diagnose')
  await expect(finder.getByRole('link')).toContainText('Fixture 诊断演示')
  await expect(finder.getByRole('link')).toContainText('合成数据')
  expect(calls).toEqual([])
})
