import { test, expect, type Page } from '@playwright/test'
import { createHash } from 'node:crypto'
import { readFileSync } from 'node:fs'
import { TOKEN_OK, mockEmptySourceInstances } from './helpers.ts'
test.beforeEach(async ({ page }) => { await mockEmptySourceInstances(page) })
import type { CredentialCommand, SourceCredential } from '../src/api/source-credentials.ts'
const sample = (name: string) => JSON.parse(readFileSync(new URL('../../../contracts/examples/' + name, import.meta.url), 'utf8'))
function digest(c: CredentialCommand) { const hash = createHash('sha256'); for (const part of c.operation === 'REVOKE_VERSION' ? ['source-credential-revoke-version-v2', c.credentialId, c.requestId, String(c.expectedEditVersion), String(c.revokeRevision)] : ['source-credential-write-v2', c.credentialId, c.requestId, c.operation, String(c.expectedEditVersion), c.name, c.state, String(c.changesSecret)]) { const bytes = Buffer.from(part); hash.update(bytes.length + ':'); hash.update(bytes) }; return 'sha256:' + hash.digest('hex') }
async function fixture(page: Page, mode?: 'unknown' | 'mismatch' | 'conflict' | 'forbidden' | 'vault-off' | 'transport-off' | 'read-only' | 'history-error' | 'unsafe-public') {
  const sources = sample('source-center-page.json'), credentialPage = sample('v2/source-credential-page.json')
  let current = structuredClone(credentialPage.items[0]) as SourceCredential, reads = 0, writes = 0, receipt: any, history: any[] = [{ pin: { credentialId: current.id, revision: 1, versionId: current.versionId }, createdAt: current.createdAt, revoked: false }]
  const calls: string[] = [], commands: CredentialCommand[] = [] // Only nonsecret command metadata is retained.
  await page.route('**/api/v1/integrations/sources', route => route.fulfill({ json: sources }))
  await page.route('**/api/v2/data-sources/credentials**', route => {
    const path = new URL(route.request().url()).pathname, method = route.request().method(); calls.push(method + ' ' + path)
    if (method !== 'GET') {
      writes++; const body = route.request().postDataJSON(), operation = path.endsWith('/revoke') ? 'REVOKE_VERSION' : method === 'POST' ? 'CREATE' : 'EDIT', old = operation === 'CREATE' ? null : current
      const c: CredentialCommand = { requestId: body.requestId, credentialId: operation === 'CREATE' ? body.requestId : current.id, operation, expectedEditVersion: body.expectedEditVersion ?? 0, name: body.name ?? current.name, state: body.state ?? 'ACTIVE', changesSecret: body.secret !== null && body.secret !== undefined, previous: old, ...(operation === 'REVOKE_VERSION' ? { revokeRevision: Number(path.split('/').at(-2)) } : {}) }; commands.push(c)
      if (mode === 'conflict') { current = { ...current, name: 'Fixture concurrent credential', editVersion: 2 }; return route.fulfill({ status: 409, json: { error: 'CREDENTIAL_CONFLICT' } }) }
      current = { id: c.credentialId, name: c.name, revision: (old?.revision ?? 0) + (c.changesSecret ? 1 : 0), versionId: c.changesSecret ? c.requestId : old!.versionId, editVersion: c.expectedEditVersion + 1, state: c.state, createdAt: old?.createdAt ?? '2026-10-03T01:00:00Z', updatedAt: '2026-10-03T02:00:00Z' }
      if (operation === 'CREATE') history = []; if (c.changesSecret) history.unshift({ pin: { credentialId: current.id, revision: current.revision, versionId: current.versionId }, createdAt: current.updatedAt, revoked: false }); if (operation === 'REVOKE_VERSION' || c.state === 'REVOKED') history = history.map(v => ({ ...v, revoked: c.state === 'REVOKED' || v.pin.revision === c.revokeRevision || v.revoked }))
      receipt = { schemaVersion: '2.0', storage: 'memory', receipt: { requestId: c.requestId, credentialId: current.id, operation, commandDigest: digest(c), credential: current } }
      if (mode === 'unknown' || mode === 'mismatch') return route.abort('failed')
      return route.fulfill({ json: receipt })
    }
    if (path.includes('/commands/')) return route.fulfill({ json: mode === 'mismatch' ? { ...receipt, receipt: { ...receipt.receipt, commandDigest: 'sha256:' + 'b'.repeat(64) } } : receipt })
    if (path.endsWith('/versions')) return mode === 'history-error' ? route.fulfill({ status: 503, json: { error: 'WORKFLOW_UNAVAILABLE' } }) : route.fulfill({ json: { schemaVersion: '2.0', storage: 'memory', credentialId: current.id, items: history } })
    if (path === '/api/v2/data-sources/credentials') { reads++; if (mode === 'forbidden') return route.fulfill({ status: 403, json: { error: 'CREDENTIAL_FORBIDDEN' } }); return route.fulfill({ json: { ...credentialPage, items: [{ ...current, ...(mode === 'unsafe-public' ? { secret: 'fixture-must-not-display' } : {}) }], vaultAvailable: mode !== 'vault-off', secretWriteAvailable: mode !== 'vault-off' && mode !== 'transport-off', canConfigure: mode !== 'read-only' } }) }
    return route.fulfill({ json: { schemaVersion: '2.0', storage: 'memory', credential: current } })
  })
  await page.goto('/#/integrations/sources'); await page.getByRole('textbox', { name: '平台开发 Token（仅保存在当前标签页内存）' }).fill(TOKEN_OK); await expect(page.getByRole('tab', { name: /已配置接入/ })).toBeVisible(); expect(reads).toBe(0); await page.getByRole('tab', { name: '凭据管理', exact: true }).click()
  return { calls, reads: () => reads, writes: () => writes, current: () => current, commands }
}
async function open(page: Page) { await page.getByRole('button', { name: '管理凭据：Fixture credential', exact: true }).click(); const dialog = page.getByRole('dialog', { name: '接入凭据', exact: true }); await expect(dialog).toBeVisible(); return dialog }
for (const width of [1440, 1024, 390]) for (const theme of ['light', 'dark']) test('explicit fixture credential version lifecycle at ' + width + ' ' + theme, async ({ page }) => {
  await page.setViewportSize({ width, height: 940 }); await page.addInitScript(theme => { localStorage.setItem('opsweave.ui.theme', theme) }, theme); const f = await fixture(page), dialog = await open(page), originalPin = f.current().versionId
  await dialog.getByRole('textbox', { name: '凭据名称', exact: true }).fill('Fixture renamed credential'); await dialog.getByRole('button', { name: '保存凭据名称', exact: true }).click(); await expect(dialog.getByRole('status')).toHaveText('凭据请求已确认'); expect(f.current().revision).toBe(1); expect(f.current().versionId).toBe(originalPin)
  await dialog.getByLabel('凭据值', { exact: true }).fill('fixture-only-rotation'); await dialog.getByRole('button', { name: '保存新凭据版本' }).click(); await expect(dialog.getByRole('status')).toHaveText('凭据请求已确认'); await expect(dialog.getByLabel('凭据值', { exact: true })).toHaveValue(''); expect(f.current().revision).toBe(2)
  await dialog.getByRole('tab', { name: '版本历史', exact: true }).click(); await expect(dialog.getByRole('table', { name: '凭据版本', exact: true })).toContainText(originalPin); await dialog.getByRole('button', { name: '撤销凭据版本 v1', exact: true }).click(); await dialog.getByRole('button', { name: '确认撤销凭据', exact: true }).click(); await expect(dialog.getByRole('table', { name: '凭据版本', exact: true }).getByRole('row').filter({ hasText: originalPin })).toContainText('已撤销')
  await dialog.getByRole('tab', { name: '凭据配置', exact: true }).click(); await dialog.getByRole('button', { name: '撤销全部版本', exact: true }).click(); await dialog.getByRole('button', { name: '确认撤销凭据', exact: true }).click(); await expect(dialog.getByRole('textbox', { name: '凭据名称', exact: true })).toBeDisabled(); expect(f.writes()).toBe(4); expect(f.current().editVersion).toBe(5)
  await dialog.getByRole('button', { name: '关闭凭据维护' }).click(); await page.getByRole('tab', { name: '接入类型', exact: true }).click(); await page.getByRole('tab', { name: '凭据管理', exact: true }).click(); expect(f.reads()).toBe(1); expect(f.calls.filter(s => s.endsWith('/versions'))).toHaveLength(1); expect(JSON.stringify(f.commands)).not.toContain('fixture-only-rotation'); expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(width)
})
for (const mode of ['unknown', 'mismatch'] as const) test('uncertain credential write clears input and queries original only: ' + mode, async ({ page }) => {
  const f = await fixture(page, mode), dialog = await open(page); await dialog.getByLabel('凭据值', { exact: true }).fill('fixture-unknown-secret'); await dialog.getByRole('button', { name: '保存新凭据版本' }).click(); await expect(dialog.getByRole('button', { name: '查询原凭据回执' })).toBeVisible(); await expect(dialog.getByLabel('凭据值', { exact: true })).toHaveValue(''); await expect(dialog.getByRole('textbox', { name: '凭据名称', exact: true })).toBeDisabled(); await expect(dialog.getByRole('button', { name: '关闭凭据维护' })).toBeDisabled()
  await dialog.getByRole('button', { name: '查询原凭据回执' }).click(); if (mode === 'unknown') await expect(dialog.getByRole('status')).toHaveText('凭据请求已确认'); else { await expect(dialog.getByRole('alert')).toContainText('原请求不一致'); await expect(dialog.getByRole('button', { name: '查询原凭据回执' })).toBeVisible() }; expect(f.writes()).toBe(1); expect(JSON.stringify(f.commands)).not.toContain('fixture-unknown-secret')
})
test('credential CAS conflict keeps metadata edit and allows explicit reread', async ({ page }) => {
  const f = await fixture(page, 'conflict'), dialog = await open(page); await dialog.getByRole('textbox', { name: '凭据名称', exact: true }).fill('Fixture stale rename'); await dialog.getByRole('button', { name: '保存凭据名称', exact: true }).click(); await expect(dialog.getByRole('alert')).toContainText('凭据版本已变化'); await expect(dialog.getByRole('textbox', { name: '凭据名称', exact: true })).toHaveValue('Fixture stale rename'); expect(f.calls.filter(s => s === 'GET /api/v2/data-sources/credentials/' + f.current().id)).toHaveLength(1); await dialog.getByRole('button', { name: '放弃修改并重读凭据' }).click(); await expect(dialog.getByRole('textbox', { name: '凭据名称', exact: true })).toHaveValue('Fixture concurrent credential'); expect(f.writes()).toBe(1)
})
for (const mode of ['vault-off', 'transport-off', 'read-only'] as const) test('missing credential write capability remains readable: ' + mode, async ({ page }) => {
  const f = await fixture(page, mode), dialog = await open(page); await expect(page.getByRole('button', { name: '新增凭据', exact: true })).toBeDisabled(); if (mode === 'read-only') await expect(dialog.getByRole('textbox', { name: '凭据名称', exact: true })).toBeDisabled(); else { await expect(dialog.getByLabel('凭据值', { exact: true })).toBeDisabled(); await dialog.getByRole('textbox', { name: '凭据名称', exact: true }).fill('Fixture metadata only'); await expect(dialog.getByRole('button', { name: '保存凭据名称', exact: true })).toBeEnabled() }; expect(f.writes()).toBe(0)
})
test('forbidden credential read clears catalog and never polls', async ({ page }) => {
  const f = await fixture(page, 'forbidden'); await expect(page.getByRole('button', { name: '管理凭据：Fixture credential', exact: true })).toHaveCount(0); await expect(page.getByRole('tab', { name: /已配置接入/ })).toHaveAttribute('aria-selected', 'true'); await page.getByRole('tab', { name: '凭据管理', exact: true }).click(); await expect(page.getByRole('button', { name: '刷新凭据列表', exact: true })).toBeEnabled(); expect(f.reads()).toBe(1); await page.getByRole('button', { name: '刷新凭据列表', exact: true }).click(); await expect(page.getByRole('tab', { name: /已配置接入/ })).toHaveAttribute('aria-selected', 'true'); expect(f.reads()).toBe(2)
})
test('closed public credential parser rejects accidental plaintext and does not retry', async ({ page }) => {
  const f = await fixture(page, 'unsafe-public'); await expect(page.getByRole('alert').filter({ hasText: '凭据回执与原请求不一致' })).toBeVisible(); expect(f.reads()).toBe(1); await expect(page.getByText('fixture-must-not-display', { exact: true })).toHaveCount(0)
})
test('failed version history persists across tabs until explicit refresh', async ({ page }) => {
  const f = await fixture(page, 'history-error'), dialog = await open(page); await dialog.getByRole('tab', { name: '版本历史', exact: true }).click(); await expect(dialog.getByRole('alert')).toContainText('HTTP 503'); await dialog.getByRole('tab', { name: '凭据配置', exact: true }).click(); await dialog.getByRole('tab', { name: '版本历史', exact: true }).click(); expect(f.calls.filter(s => s.endsWith('/versions'))).toHaveLength(1)
})
test('unsaved new credential input can be resumed or discarded without a request', async ({ page }) => {
  const f = await fixture(page); await page.getByRole('button', { name: '新增凭据', exact: true }).click(); const dialog = page.getByRole('dialog', { name: '接入凭据', exact: true }); await dialog.getByRole('textbox', { name: '凭据名称', exact: true }).fill('Fixture draft'); await dialog.getByLabel('凭据值', { exact: true }).fill('fixture-draft-secret'); await dialog.getByRole('button', { name: '关闭凭据维护' }).click(); await page.getByRole('button', { name: '继续编辑凭据', exact: true }).click(); await expect(dialog.getByLabel('凭据值', { exact: true })).toHaveValue('fixture-draft-secret'); await dialog.getByRole('button', { name: '放弃凭据输入' }).click(); await expect(dialog.getByLabel('凭据值', { exact: true })).toHaveValue(''); await expect(dialog.getByRole('textbox', { name: '凭据名称', exact: true })).toHaveValue(''); expect(f.writes()).toBe(0)
})
test('new credential creates one immutable version and no secret browser storage', async ({ page }) => {
  const f = await fixture(page); await page.getByRole('button', { name: '新增凭据', exact: true }).click(); const dialog = page.getByRole('dialog', { name: '接入凭据', exact: true }); await dialog.getByRole('textbox', { name: '凭据名称', exact: true }).fill('Fixture new credential'); await dialog.getByLabel('凭据值', { exact: true }).fill('fixture-new-secret'); await dialog.getByRole('button', { name: '保存凭据', exact: true }).click(); await expect(dialog.getByRole('status')).toHaveText('凭据请求已确认'); await expect(dialog.getByLabel('凭据值', { exact: true })).toHaveValue(''); expect(f.writes()).toBe(1); expect(f.current().revision).toBe(1); expect(await page.evaluate(() => JSON.stringify({ local: { ...localStorage }, session: { ...sessionStorage } }))).not.toContain('fixture-new-secret')
})
test('changing a credential draft cancels an armed revocation without writing', async ({ page }) => {
  const f = await fixture(page), dialog = await open(page); await dialog.getByRole('button', { name: '撤销全部版本', exact: true }).click(); await expect(dialog.getByRole('button', { name: '确认撤销凭据', exact: true })).toBeVisible(); await dialog.getByRole('textbox', { name: '凭据名称', exact: true }).fill('Fixture edited after confirmation'); await expect(dialog.getByRole('button', { name: '确认撤销凭据', exact: true })).toHaveCount(0); expect(f.writes()).toBe(0)
})
