import { test, expect, type Page } from '@playwright/test'
import { readFileSync } from 'node:fs'
import { TOKEN_OK } from './helpers.ts'
const hash='sha256:'+'a'.repeat(64)
const bundle=JSON.parse(readFileSync(new URL('../../../contracts/catalog/opsweave-core-1.0.0.json',import.meta.url),'utf8'))
const models=bundle.definitions.filter((m:any)=>m.kind==='ENTITY').map((definition:any)=>({definition,digest:hash}))
async function setup(page:Page,read=true){
 const calls:{path:string;body:any}[]=[];let receipt:any=null;const sourcePage={schemaVersion:'1.0',storage:'memory',types:[{id:'ZABBIX_HOST',status:'AVAILABLE',connection:{instanceId:'zabbix-fixture',digest:hash,dataMode:'fixture',endpoint:null,credentialRef:null}},{id:'MANUAL_SAMPLE',status:'AVAILABLE',connection:{instanceId:'manual',digest:hash,dataMode:'MANUAL_SAMPLE',endpoint:null,credentialRef:null}},{id:'CMDB_SNAPSHOT',status:'LEGACY_IMPORT',connection:null}],models,modelsTruncated:false,setups:{items:[],truncated:false}}
 await page.route(/\/api\/v1\/integrations\/(sources|workflows|zabbix\/connection-checks)(?:\/|$)/,async route=>{const path=new URL(route.request().url()).pathname,body=route.request().postDataJSON();calls.push({path,body});let result:any
 if(path.endsWith('/sources'))result={...sourcePage,setups:{items:receipt?[receipt.setup]:[],truncated:false}}
 else if(path.endsWith('/confirm')){const ids=['source','mapping','trim','validate','output'];const nodes=ids.map((id,i)=>({id,type:['SOURCE','MAP','TRIM','VALIDATE','OUTPUT'][i],version:'1',config:i===1?{name:body.target.id==='builtin.host'?'hostname':'name'}:{}}));receipt={setup:{id:body.requestId,name:body.name,description:body.description,source:body.source,connectionDigest:body.connectionDigest,dataMode:body.source.kind==='MANUAL_SAMPLE'?'MANUAL_SAMPLE':'fixture',initialTarget:body.target,digest:hash,createdAt:new Date().toISOString(),workflowId:'source-'+body.requestId},workflow:{definition:{schemaVersion:'2.0',id:'source-'+body.requestId,name:body.name,revision:1,source:body.source,target:body.target,nodes,edges:ids.slice(0,-1).map((from,i)=>({from,to:ids[i+1]}))},layout:Object.fromEntries(ids.map((id,i)=>[id,{x:180,y:40+i*116}])),digest:hash,state:'DRAFT',editVersion:1,updatedAt:new Date().toISOString(),preview:null}};result=receipt}
 else if(path.endsWith('/workflows'))result={schemaVersion:'2.0',storage:'memory',drafts:{items:receipt?[receipt.workflow]:[],truncated:false},published:{items:[],truncated:false},models,modelsTruncated:false,zabbixSource:{instanceId:'zabbix-fixture',mode:'fixture'},runs:{items:[],truncated:false}}
 else if(path.includes('/workflows/'))result=receipt?.workflow
 else if(path.endsWith('/connection-checks'))result={schemaVersion:'1.0',storage:'memory',dataMode:'connection-check',tenantId:'fixture',sourceInstanceId:'zabbix-fixture',check:{checkId:'10000000-0000-4000-8000-000000000001',sourceInstanceId:'zabbix-fixture',actor:'fixture',checkedAt:new Date().toISOString(),dataMode:'labeled-fixture',reachable:true,statusCode:'labeled-fixture',reportedVersion:null}}
 else result=receipt
 await route.fulfill({contentType:'application/json',body:JSON.stringify(result)})})
 await page.goto('/#/integrations/sources');await page.getByRole('textbox',{name:'平台开发 Token（仅保存在当前标签页内存）'}).fill(TOKEN_OK);if(read)await page.getByRole('button',{name:'读取数据源',exact:true}).click();await expect(page.getByRole('button',{name:'配置手工样本 →',exact:true})).toBeEnabled();return calls
}
for(const width of [1500,390])test('source selection fixture drawer persists and opens the exact canvas '+width,async({page})=>{
 await page.setViewportSize({width,height:1000});const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));const calls=await setup(page)
 await page.getByRole('button',{name:'配置手工样本 →',exact:true}).click();const drawer=page.getByRole('dialog',{name:'数据源配置'});await expect(drawer).toBeVisible();await expect(page.getByRole('combobox',{name:'初始目标模型'})).toHaveValue('builtin.service@1');await page.getByRole('textbox',{name:'接入名称',exact:true}).fill('Fixture source choice');await page.getByRole('button',{name:'确认并进入画布',exact:true}).click();await expect(page.getByRole('textbox',{name:'工作流名称',exact:true})).toHaveValue('Fixture source choice');await expect(page.locator('.workflow-node')).toHaveCount(5);expect(calls.filter(c=>c.body)).toHaveLength(1);expect(calls[1].body.source).toEqual({kind:'MANUAL_SAMPLE',instanceId:'manual'});expect(calls[1].body).not.toHaveProperty('tenantId');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)
 await page.getByRole('link',{name:'← 数据源中心',exact:true}).click();await page.getByRole('button',{name:'读取数据源',exact:true}).click();await expect(page.locator('.source-saved-row')).toContainText('Fixture source choice');await page.getByRole('button',{name:'查看配置',exact:true}).click();await expect(page.getByRole('textbox',{name:'接入名称',exact:true})).toBeDisabled();await page.getByRole('button',{name:'继续编排',exact:true}).click();await expect(page.getByRole('textbox',{name:'工作流名称',exact:true})).toHaveValue('Fixture source choice');expect(errors).toEqual([])
})
test('Zabbix probe is explicit, fixture marked, and CMDB remains legacy',async({page})=>{const calls=await setup(page);expect(calls).toHaveLength(1);await expect(page.getByRole('link',{name:'前往快照导入 ↗'})).toHaveAttribute('href','#/integrations/cmdb');await page.getByRole('button',{name:'配置 Zabbix →'}).click();await expect(page.getByRole('dialog')).toContainText('暂不支持多实例新增');await expect(page.getByRole('combobox',{name:'初始目标模型'})).toHaveValue('builtin.host@1');await page.getByRole('button',{name:'测试连接',exact:true}).click();await expect(page.getByText('Fixture 自检 · 非真实连接',{exact:true})).toBeVisible();expect(calls.filter(c=>c.path.endsWith('/connection-checks'))).toHaveLength(1);await page.keyboard.press('Escape');await expect(page.getByRole('dialog')).not.toBeVisible();await expect(page.getByRole('button',{name:'配置 Zabbix →'})).toBeFocused()})
test('failed confirmation keeps the same request for explicit retry',async({page})=>{await setup(page);let attempts:any[]=[];await page.route('**/sources/confirm',async r=>{attempts.push(r.request().postDataJSON());await r.fulfill({status:503,contentType:'application/json',body:'{"error":"UNAVAILABLE"}'})});await page.getByRole('button',{name:'配置手工样本 →'}).click();await page.getByRole('button',{name:'确认并进入画布'}).click();await expect(page.getByRole('button',{name:'按原配置重试'})).toBeEnabled();await expect(page.getByRole('textbox',{name:'接入名称',exact:true})).toBeDisabled();await page.getByRole('button',{name:'按原配置重试'}).click();await expect(page.getByRole('button',{name:'查询确认结果'})).toBeEnabled();expect(attempts).toHaveLength(2);expect(attempts[0]).toEqual(attempts[1]);expect(await page.evaluate(()=>JSON.stringify({...localStorage,...sessionStorage}))).not.toContain(attempts[0].requestId)})
test('session change removes saved configuration and closes the private drawer',async({page})=>{await setup(page);await page.getByRole('button',{name:'配置手工样本 →'}).click();await page.getByRole('textbox',{name:'接入名称',exact:true}).fill('Private fixture source');await page.keyboard.press('Escape');await page.getByRole('textbox',{name:'平台开发 Token（仅保存在当前标签页内存）'}).fill('another-token-long-enough-123456789');await expect(page.getByRole('button',{name:'配置手工样本 →'})).toBeEnabled();await expect(page.getByRole('dialog')).not.toBeVisible();expect(await page.getByRole('textbox',{name:'接入名称',exact:true,includeHidden:true}).inputValue()).toBe('')})
test('invalid canvas deep link cannot trigger a workflow request',async({page})=>{const calls=await setup(page);await page.evaluate(()=>location.hash='#/integrations/workflows?id=../../escape&revision=1&state=DRAFT');await expect(page.getByRole('alert').filter({hasText:'工作流地址参数无效'})).toBeVisible();expect(calls.filter(c=>c.path.includes('/workflows'))).toHaveLength(0)})

test('choosing a type loads its authorized catalog without a separate read click',async({page})=>{const calls=await setup(page,false);expect(calls).toHaveLength(0);await page.getByRole('button',{name:'配置手工样本 →',exact:true}).click();await expect(page.getByRole('dialog',{name:'数据源配置'})).toBeVisible();await expect(page.getByRole('combobox',{name:'初始目标模型'})).toHaveValue('builtin.service@1');expect(calls.map(c=>c.path)).toEqual(['/api/v1/integrations/sources']);expect(calls.every(c=>c.body===null)).toBe(true)})
test('missing session explains the blocked action without sending any request',async({page})=>{const calls=await setup(page,false);const token=page.getByRole('textbox',{name:'平台开发 Token（仅保存在当前标签页内存）'});await token.fill('');await expect(page.locator('.source-access-hint')).toContainText('尚未建立开发会话');await page.getByRole('button',{name:'配置 Zabbix →',exact:true}).click();await expect(page.getByRole('alert').filter({hasText:'请先在页面顶部填写平台开发 Token'})).toBeVisible();await expect(page.getByRole('dialog',{name:'数据源配置'})).not.toBeVisible();expect(calls).toHaveLength(0);await page.getByRole('button',{name:'读取数据源',exact:true}).click();expect(calls).toHaveLength(0)})
