import { test, expect, type Page } from '@playwright/test'
import { createHash } from 'node:crypto'
import { readFileSync } from 'node:fs'
import { TOKEN_OK } from './helpers.ts'
const sample = (name: string) => JSON.parse(readFileSync(new URL('../../../contracts/examples/' + name, import.meta.url), 'utf8'))
function hash(parts: string[]) { const h = createHash('sha256'); for (const part of parts) { const b = Buffer.from(part); h.update(b.length + ':'); h.update(b) }; return 'sha256:' + h.digest('hex') }
async function fixture(page: Page, failure?: 'unknown' | 'mismatch' | 'conflict' | 'forbidden' | 'revoked' | 'history') {
  const sources = sample('source-center-page.json'), instances = sample('v2/source-instance-page.json'), endpoints = sample('v2/source-endpoint-page.json'), credentials = sample('v2/source-credential-page.json'), versions = sample('v2/source-credential-version-page.json')
  let current = instances.items[0], config: any = null, receipt: any = null, writes = 0, historyReads = 0
  const calls: string[] = []
  if (failure === 'revoked') versions.items[0].revoked = true
  await page.route('**/api/v1/integrations/sources', route => route.fulfill({ json: sources }))
  await page.route('**/api/v2/data-sources**', route => {
    const path = new URL(route.request().url()).pathname, method = route.request().method(); calls.push(method + ' ' + path)
    if (path === '/api/v2/data-sources/endpoints') return route.fulfill({ json: endpoints })
    if (path === '/api/v2/data-sources/credentials') return failure === 'forbidden' ? route.fulfill({ status: 403, json: { error: 'FORBIDDEN' } }) : route.fulfill({ json: credentials })
    if (path.endsWith('/versions')) return route.fulfill({ json: versions })
    if (path.endsWith('/connection/history')) { historyReads++; return failure === 'history' ? route.fulfill({ status: 503, json: { error: 'UNAVAILABLE' } }) : route.fulfill({ json: { schemaVersion: '2.0', storage: 'memory', sourceId: current.id, items: config ? [config] : [] } }) }
    if (path.includes('/connection/commands/')) return route.fulfill({ json: failure === 'mismatch' ? { ...receipt, receipt: { ...receipt.receipt, commandDigest: 'sha256:' + 'f'.repeat(64) } } : receipt })
    if (method === 'POST' || method === 'PATCH') {
      writes++; const c = route.request().postDataJSON(), id = method === 'POST' ? c.requestId : current.id, ep = endpoints.items[0], pin = c.credentialPin
      if (failure === 'conflict') return route.fulfill({ status: 409, json: { error: 'CONFLICT' } })
      const hostGroupIds = c.hostGroupIds
      const connectionDigest = hash(['source-connection-v3', id, 'host-jsonrpc-v2', ep.id, ep.digest, pin.credentialId, String(pin.revision), pin.versionId, String(hostGroupIds.length), ...hostGroupIds])
      config = { sourceId: id, revision: method === 'POST' ? 1 : current.configurationRevision + (current.connectionDigest === connectionDigest ? 0 : 1), connectorVersion: 'host-jsonrpc-v2', endpoint: ep, credentialPin: pin, hostGroupIds, connectionDigest, createdAt: '2026-10-03T02:00:00Z' }
      current = { ...current, id, name: c.name, description: c.description, source: method === 'POST' ? { kind: 'ZABBIX_HOST', instanceId: 'connection-' + id } : current.source, configurationRevision: config.revision, connectionDigest, dataMode: 'zabbix-jsonrpc', editVersion: (c.expectedEditVersion ?? 0) + 1, state: 'ACTIVE', createdAt: method === 'POST' ? config.createdAt : current.createdAt, updatedAt: config.createdAt, workflowId: 'source-' + id }
      receipt = { schemaVersion: '2.0', storage: 'memory', receipt: { requestId: c.requestId, sourceId: id, commandDigest: hash(['source-connection-write-v3', id, c.requestId, String(c.expectedEditVersion ?? 0), c.name, c.description, ep.id, ep.digest, pin.credentialId, String(pin.revision), pin.versionId, String(hostGroupIds.length), ...hostGroupIds]), instance: current }, connection: config }
      return failure === 'unknown' || failure === 'mismatch' ? route.abort('failed') : route.fulfill({ json: receipt })
    }
    if (path.endsWith('/connection')) return route.fulfill({ json: { schemaVersion: '2.0', storage: 'memory', instance: current, connection: config, availability: config ? 'AVAILABLE' : 'LEGACY', canConfigure: true } })
    if (path === '/api/v2/data-sources') return route.fulfill({ json: { ...instances, items: [current] } })
    return route.fulfill({ json: { schemaVersion: '2.0', instance: current } })
  })
  await page.goto('/#/integrations/sources'); await page.getByRole('textbox', { name: '平台开发 Token（仅保存在当前标签页内存）' }).fill(TOKEN_OK); await page.getByRole('tab', { name: /已配置接入/ }).click(); await expect(page.getByRole('table', { name: '接入实例列表' })).toContainText(current.name)
  return { calls, writes: () => writes, historyReads: () => historyReads, current: () => current }
}
async function open(page: Page) { await page.getByRole('button', { name: '新增连接', exact: true }).click(); const d = page.getByRole('dialog', { name: '新增连接', exact: true }); await expect(d).toBeVisible(); await expect(d.getByLabel('登记地址', { exact: true })).toContainText('Fixture Host endpoint'); return d }
async function fill(page: Page) { const d = await open(page); await d.getByLabel('连接名称', { exact: true }).fill('Fixture new connection'); await d.getByLabel('主机组 ID', { exact: true }).fill('1001'); await d.getByLabel('登记地址', { exact: true }).selectOption('fixture-host'); await d.getByLabel('连接凭据', { exact: true }).selectOption('10000000-0000-4000-8000-000000000081'); await expect(d.getByLabel('连接凭据版本', { exact: true })).toBeEnabled(); await d.getByLabel('连接凭据版本', { exact: true }).selectOption('10000000-0000-4000-8000-000000000081'); return d }
for (const width of [1440, 1024, 390]) for (const theme of ['light', 'dark']) test('explicit Fixture connection drawer at ' + width + ' ' + theme, async ({ page }) => {
  await page.setViewportSize({ width, height: 940 }); await page.addInitScript(t => localStorage.setItem('opsweave.ui.theme', t), theme); const f = await fixture(page), d = await fill(page)
  await expect(d.getByText('https://192.0.2.10/api_jsonrpc.php', { exact: true })).toBeVisible(); await d.getByRole('button', { name: '创建连接', exact: true }).click(); await expect(page.getByRole('dialog', { name: '编辑地址与凭据' }).getByRole('status')).toContainText('连接配置已保存'); expect(f.writes()).toBe(1)
  const saved = page.getByRole('dialog', { name: '编辑地址与凭据' }); await expect(saved.getByLabel('连接名称', { exact: true })).toHaveValue('Fixture new connection'); await expect(saved.getByRole('button', { name: '保存连接配置' })).toBeDisabled(); await saved.getByText('连接配置历史', { exact: true }).click(); await expect(saved.getByRole('table', { name: '连接配置历史' })).toContainText('v1'); expect(f.historyReads()).toBe(1)
  const bounds = await saved.evaluate(e => ({ left: e.getBoundingClientRect().left, right: e.getBoundingClientRect().right, height: e.getBoundingClientRect().height })); expect(bounds.right).toBeLessThanOrEqual(width); expect(bounds.left).toBeGreaterThanOrEqual(0); expect(bounds.height).toBeGreaterThan(800); expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(width)
  await saved.getByRole('button', { name: '关闭连接配置' }).click(); await expect(page.getByRole('table', { name: '接入实例列表' })).toContainText('Fixture new connection'); expect(f.calls.filter(c => c.endsWith('/endpoints'))).toHaveLength(1); expect(f.calls.filter(c => c.endsWith('/versions'))).toHaveLength(1)
})
test('unknown result preserves exact command and recovers with GET only', async ({ page }) => { const f = await fixture(page, 'unknown'), d = await fill(page); await d.getByRole('button', { name: '创建连接' }).click(); await expect(d.getByRole('button', { name: '查询原连接回执' })).toBeVisible(); await expect(d.getByLabel('连接名称', { exact: true })).toBeDisabled(); await expect(d.getByRole('button', { name: '关闭连接配置' })).toBeDisabled(); await d.getByRole('button', { name: '查询原连接回执' }).click(); await expect(page.getByRole('dialog', { name: '编辑地址与凭据' }).getByRole('status')).toContainText('连接配置已保存'); expect(f.writes()).toBe(1) })
test('mismatched original receipt retains pending request', async ({ page }) => { const f = await fixture(page, 'mismatch'), d = await fill(page); await d.getByRole('button', { name: '创建连接' }).click(); await d.getByRole('button', { name: '查询原连接回执' }).click(); await expect(d.getByRole('alert')).toContainText('固定配置不一致'); await expect(d.getByLabel('连接名称', { exact: true })).toBeDisabled(); expect(f.writes()).toBe(1) })
test('definite rejection keeps draft without automatic reread', async ({ page }) => { const f = await fixture(page, 'conflict'), d = await fill(page); await d.getByRole('button', { name: '创建连接' }).click(); await expect(d.getByRole('alert')).toContainText('实例或原请求已变化'); await expect(d.getByLabel('连接名称', { exact: true })).toHaveValue('Fixture new connection'); await expect(d.getByLabel('连接名称', { exact: true })).toBeEnabled(); expect(f.writes()).toBe(1); expect(f.calls.filter(c => c.endsWith('/endpoints'))).toHaveLength(1) })
test('closed dirty drawer resumes without losing invalid name or fixed selectors', async ({ page }) => { const f = await fixture(page), d = await fill(page); await d.getByLabel('连接名称', { exact: true }).fill(''); await d.getByRole('button', { name: '关闭连接配置' }).click(); await page.getByRole('button', { name: '继续配置连接' }).click(); await expect(d.getByLabel('连接名称', { exact: true })).toHaveValue(''); await expect(d.getByLabel('连接凭据版本', { exact: true })).toHaveValue('10000000-0000-4000-8000-000000000081'); await expect(d.getByRole('button', { name: '创建连接' })).toBeDisabled(); expect(f.calls.filter(c => c.endsWith('/endpoints'))).toHaveLength(1) })
test('authorization failure clears hidden draft and closes drawer', async ({ page }) => { const f = await fixture(page, 'forbidden'); await page.getByRole('button', { name: '新增连接', exact: true }).click(); await expect(page.getByRole('dialog', { name: '新增连接' })).toHaveCount(0); expect(f.writes()).toBe(0) })
test('existing binding edits through fixed pins without adding a configuration for a rename', async ({ page }) => { const f = await fixture(page), d = await fill(page); await d.getByRole('button', { name: '创建连接' }).click(); const saved = page.getByRole('dialog', { name: '编辑地址与凭据' }); await expect(saved.getByRole('status')).toContainText('连接配置已保存'); await saved.getByRole('button', { name: '关闭连接配置' }).click(); await page.getByRole('button', { name: '维护实例：Fixture new connection' }).click(); await page.getByRole('dialog', { name: '维护接入实例' }).getByRole('button', { name: '地址与凭据' }).click(); await expect(saved.getByLabel('连接凭据版本', { exact: true })).toHaveValue('10000000-0000-4000-8000-000000000081'); await saved.getByLabel('连接名称', { exact: true }).fill('Fixture renamed binding'); await saved.getByRole('button', { name: '保存连接配置' }).click(); await expect(saved.getByRole('status')).toContainText('连接配置已保存'); expect(f.current().configurationRevision).toBe(1); expect(f.current().editVersion).toBe(2); expect(f.writes()).toBe(2) })
test('history error is retained on reopen until explicit refresh', async ({ page }) => { const f = await fixture(page, 'history'), d = await fill(page); await d.getByRole('button', { name: '创建连接' }).click(); const saved = page.getByRole('dialog', { name: '编辑地址与凭据' }); await expect(saved.getByRole('status')).toContainText('连接配置已保存'); const toggle = saved.getByText('连接配置历史', { exact: true }); await toggle.click(); await expect(saved.getByRole('alert')).toContainText('连接请求失败'); await toggle.click(); await toggle.click(); expect(f.historyReads()).toBe(1); await saved.getByRole('button', { name: '刷新连接历史' }).click(); await expect.poll(f.historyReads).toBe(2) })
test('keyboard escape returns focus and preserves connection draft', async ({ page }) => { await fixture(page); const d = await fill(page); await page.keyboard.press('Escape'); await expect(d).toHaveCount(0); await expect(page.getByRole('button', { name: '继续配置连接' })).toBeFocused(); await page.keyboard.press('Enter'); await expect(d).toBeVisible(); await expect(d.getByLabel('连接名称', { exact: true })).toHaveValue('Fixture new connection') })
test('revoked fixed version is visible but cannot be selected for save', async ({ page }) => { const f = await fixture(page, 'revoked'), d = await open(page); await d.getByLabel('连接名称', { exact: true }).fill('Fixture revoked choice'); await d.getByLabel('登记地址', { exact: true }).selectOption('fixture-host'); await d.getByLabel('连接凭据', { exact: true }).selectOption('10000000-0000-4000-8000-000000000081'); await expect(d.getByLabel('连接凭据版本', { exact: true }).locator('option[value="10000000-0000-4000-8000-000000000081"]')).toHaveAttribute('disabled', ''); await expect(d.getByRole('button', { name: '创建连接' })).toBeDisabled(); expect(f.writes()).toBe(0) })
