import { expect,test,type Page,type Route } from '@playwright/test'
import { readFileSync } from 'node:fs'
import { TOKEN_OK } from './helpers.ts'
const sample=(name:string)=>JSON.parse(readFileSync(new URL(`../../../contracts/examples/${name}.json`,import.meta.url),'utf8'))
const root='/api/v1/integrations/cmdb/binding-corrections'
function fixtures(){const receipt=sample('source-binding-correction-receipt'),c=receipt.command,old=receipt.previous;old.observedAt=new Date(Date.now()-60000).toISOString();old.ingestedAt=new Date(Date.now()-30000).toISOString();old.expiresAt=new Date(Date.parse(old.observedAt)+604800000).toISOString();return {receipt,c,old}}
async function enter(page:Page,f:ReturnType<typeof fixtures>){await page.goto('/#/integrations/cmdb/corrections');await page.getByRole('textbox',{name:'平台开发 Token（仅保存在当前标签页内存）'}).fill(TOKEN_OK);await page.getByRole('textbox',{name:'原资产 ID',exact:true}).fill(f.c.previousEntityId);await page.getByRole('textbox',{name:'待更正来源外部 ID',exact:true}).fill(f.c.externalId);await page.getByRole('textbox',{name:'目标已登记资产 UUID',exact:true}).fill(f.c.targetIdentity.value);await page.getByRole('textbox',{name:'更正来源字段 JSON',exact:true}).fill(JSON.stringify(f.c.values));await page.getByRole('textbox',{name:'绑定更正原因',exact:true}).fill('Verified fixture correction')}
function saved(f:ReturnType<typeof fixtures>,command:any){const r=structuredClone(f.receipt);r.command=command;r.previousEntityVersionAfter=command.expectedPreviousVersion+1;r.snapshot.input={requestId:command.requestId,observedAt:command.observedAt,complete:false,records:[{externalId:command.externalId,assetUuid:command.targetIdentity.value,values:command.values}]};r.snapshot.ingestedAt=new Date().toISOString();r.snapshot.resolved[0]={...r.snapshot.resolved[0],externalId:command.externalId,entityId:command.targetEntityId,identity:command.targetIdentity,entityVersion:command.expectedTargetVersion+1};return r}
async function reads(route:Route,f:ReturnType<typeof fixtures>){const p=new URL(route.request().url()).pathname,c=f.c;if(p.endsWith('/snapshots/config'))return route.fulfill({json:sample('source-snapshot-config')});if(p.endsWith('/resolve-identity')){const r=sample('asset-identity-resolution');r.identity={...r.identity,...c.targetIdentity,entityId:c.targetEntityId};r.entityVersion=c.expectedTargetVersion;return route.fulfill({json:r})}if(p.endsWith('/source-presence'))return route.fulfill({json:{schemaVersion:'1.0',storage:'postgres',dataMode:'import',tenantId:f.receipt.tenantId,entityId:c.previousEntityId,evaluatedAt:new Date().toISOString(),items:[{...f.old,status:'PRESENT'}]}});const old=p.endsWith(c.previousEntityId);return route.fulfill({json:{...sample('entity'),id:old?c.previousEntityId:c.targetEntityId,version:old?c.expectedPreviousVersion:c.expectedTargetVersion,name:old?'Original host':'Target host'}})}
async function prepare(page:Page){await page.getByRole('button',{name:'读取更正预览',exact:true}).click();await expect(page.locator('[data-correction-preview]')).toContainText('Target host');await page.getByRole('checkbox',{name:'已核对新旧资产，确认更正当前绑定并保留历史归属'}).check()}
test('explicit preview confirms both versions and new observation, preserves receipt and audits history',async({page})=>{
  const f=fixtures();let posts=0,result:any,readsCount=0;await page.route('**/api/v1/**',r=>{const p=new URL(r.request().url()).pathname;if(p===root){posts++;const b=r.request().postDataJSON();expect(Object.keys(b).sort()).toEqual(['command','mappingDigest']);result=saved(f,b.command);return r.fulfill({json:result})}if(p.endsWith('/source-binding-corrections'))return r.fulfill({json:{...sample('source-binding-correction-page'),items:[result]}});readsCount++;return reads(r,f)});
  await enter(page,f);expect(readsCount).toBe(0);expect(posts).toBe(0);await prepare(page);await expect(page.locator('[data-correction-preview]')).toContainText('Original host');await page.getByRole('button',{name:'确认绑定更正',exact:true}).click();await expect(page.locator('[data-correction-receipt]')).toContainText('绑定更正已保存');expect(posts).toBe(1);await page.getByRole('button',{name:'读取更正历史',exact:true}).click();await expect(page.locator('[data-correction-history]')).toContainText('Verified fixture correction');await page.getByRole('textbox',{name:'平台开发 Token（仅保存在当前标签页内存）'}).fill('');await expect(page.locator('[data-correction-receipt]')).toHaveCount(0);await expect(page.locator('[data-correction-history]')).toHaveCount(0);await expect(page.getByRole('textbox',{name:'更正来源字段 JSON',exact:true})).toHaveValue('{}')
})
for(const invalid of ['tenant','target','previous','version'])test(`invalid ${invalid} correction receipt leaves submission uncertain`,async({page})=>{
  const f=fixtures();let posts=0;await page.route('**/api/v1/**',r=>{if(new URL(r.request().url()).pathname!==root)return reads(r,f);posts++;const result=saved(f,r.request().postDataJSON().command);if(invalid==='tenant')result.tenantId='other';if(invalid==='target')result.snapshot.resolved[0].entityId=f.c.previousEntityId;if(invalid==='previous')result.previous.snapshotId='00000000-0000-4000-8000-000000000001';if(invalid==='version')result.previousEntityVersionAfter=1;return r.fulfill({json:result})});await enter(page,f);await prepare(page);await page.getByRole('button',{name:'确认绑定更正',exact:true}).click();await expect(page.getByRole('alert')).toContainText('来源更正响应');await expect(page.locator('[data-correction-receipt]')).toHaveCount(0);await expect(page.getByRole('button',{name:'读取更正预览',exact:true})).toBeDisabled();expect(posts).toBe(1)
})
test('unknown correction and hidden receipt never resend or permit replacing its request id',async({page})=>{
  const f=fixtures();let posts=0,queries=0,result:any;await page.route('**/api/v1/**',r=>{const p=new URL(r.request().url()).pathname;if(p===root){posts++;result=saved(f,r.request().postDataJSON().command);return r.abort('failed')}if(p.startsWith(root+'/')){queries++;return queries===1?r.fulfill({status:404,json:{error:'NOT_FOUND'}}):r.fulfill({json:result})}return reads(r,f)});await enter(page,f);await prepare(page);await page.getByRole('button',{name:'确认绑定更正',exact:true}).click();await expect(page.locator('[data-correction-pending]')).toBeVisible();await expect(page.getByRole('textbox',{name:'更正请求标识',exact:true})).toBeDisabled();await page.getByRole('button',{name:'查询更正回执',exact:true}).click();await expect(page.getByRole('alert')).toContainText('不代表未知更正没有生效');await expect(page.locator('[data-correction-pending]')).toBeVisible();await page.getByRole('button',{name:'查询更正回执',exact:true}).click();await expect(page.locator('[data-correction-receipt]')).toBeVisible();expect(posts).toBe(1)
})
test('editing approved values invalidates the preview and confirmation',async({page})=>{
  const f=fixtures();await page.route('**/api/v1/**',r=>reads(r,f));await enter(page,f);await prepare(page);await page.getByRole('textbox',{name:'更正来源字段 JSON',exact:true}).fill('{"owner":"changed"}');await expect(page.locator('[data-correction-preview]')).toHaveCount(0);await expect(page.getByRole('button',{name:'确认绑定更正',exact:true})).toHaveCount(0)
})
test('future observation cannot be submitted and leaves inputs editable',async({page})=>{
  const f=fixtures();let posts=0;await page.route('**/api/v1/**',r=>{if(new URL(r.request().url()).pathname===root)posts++;return reads(r,f)});await enter(page,f);await page.getByRole('textbox',{name:'更正来源观测时间（UTC）',exact:true}).fill('2099-01-01T00:00:00Z');await page.getByRole('button',{name:'读取更正预览',exact:true}).click();await expect(page.getByRole('alert')).toContainText('来源快照响应');await expect(page.getByRole('textbox',{name:'更正来源字段 JSON',exact:true})).toBeEnabled();expect(posts).toBe(0)
})
test('late preview after logout cannot restore identity or source input',async({page})=>{
  const f=fixtures();let release=()=>{};const held=new Promise<void>(r=>{release=r});await page.route('**/api/v1/**',async r=>{if(new URL(r.request().url()).pathname.endsWith('/snapshots/config'))await held;await reads(r,f)});await enter(page,f);const request=page.waitForRequest('**/snapshots/config');await page.getByRole('button',{name:'读取更正预览',exact:true}).click();await request;await page.getByRole('textbox',{name:'平台开发 Token（仅保存在当前标签页内存）'}).fill('');release();await expect(page.locator('[data-correction-preview]')).toHaveCount(0);await expect(page.getByRole('textbox',{name:'原资产 ID',exact:true})).toHaveValue('')
})
