import { expect,test,type Page } from '@playwright/test'
import { readFileSync } from 'node:fs'
import { TOKEN_OK } from './helpers.ts'
const sample=(name:string)=>JSON.parse(readFileSync(new URL(`../../../contracts/examples/${name}.json`,import.meta.url),'utf8'))
const root='/api/v1/integrations/cmdb/snapshots'
async function enter(page:Page){await page.goto('/#/integrations/cmdb');await page.getByRole('textbox',{name:'平台开发 Token（仅保存在当前标签页内存）'}).fill(TOKEN_OK)}
async function prepare(page:Page){await page.getByRole('button',{name:'读取快照配置',exact:true}).click();await page.getByRole('textbox',{name:'来源记录 JSON',exact:true}).fill(JSON.stringify(sample('source-snapshot-input').input.records));await page.getByRole('checkbox',{name:'已核对标识、观测时间与完整性，确认导入本批'}).check()}
function receipt(input:unknown){return {...sample('source-snapshot-receipt'),input,ingestedAt:new Date().toISOString()}}
test('explicit import keeps fields pending, persists one request and clears on identity change',async({page})=>{
  let posts=0,gets=0;await page.route('**/api/v1/**',route=>{if(route.request().method()==='GET'){gets++;return route.fulfill({json:sample('source-snapshot-config')})}posts++;const body=route.request().postDataJSON();expect(Object.keys(body).sort()).toEqual(['input','mappingDigest']);return route.fulfill({json:receipt(body.input)})});
  await enter(page);expect(posts).toBe(0);expect(gets).toBe(0);await prepare(page);await page.getByRole('button',{name:'导入来源快照',exact:true}).click();await expect(page.locator('[data-snapshot-receipt]')).toContainText('快照已保存');await expect(page.locator('[data-snapshot-receipt] li')).toHaveCount(1);expect(posts).toBe(1);expect(gets).toBe(1);
  await page.getByRole('textbox',{name:'平台开发 Token（仅保存在当前标签页内存）'}).fill('');await expect(page.locator('[data-snapshot-receipt]')).toHaveCount(0)
})
for(const invalid of ['tenant','resolution','future','mode'])test(`rejects ${invalid} receipt without hiding uncertain submission`,async({page})=>{
  let posts=0;await page.route('**/api/v1/**',route=>{if(route.request().method()==='GET')return route.fulfill({json:sample('source-snapshot-config')});posts++;const v=receipt(route.request().postDataJSON().input);if(invalid==='tenant')v.tenantId='other';if(invalid==='resolution')v.resolved[0].identity.value='a1111111-1111-4111-8111-111111111111';if(invalid==='future')v.ingestedAt='2000-01-01T00:00:00Z';if(invalid==='mode')v.dataMode='live';return route.fulfill({json:v})});
  await enter(page);await prepare(page);await page.getByRole('button',{name:'导入来源快照',exact:true}).click();await expect(page.getByRole('alert')).toContainText('来源快照响应');await expect(page.locator('[data-snapshot-receipt]')).toHaveCount(0);await expect(page.getByRole('button',{name:'导入来源快照',exact:true})).toBeDisabled();expect(posts).toBe(1)
})
test('unknown result and 404 never resend the snapshot; original receipt can be recovered',async({page})=>{
  let posts=0,queries=0,input:unknown;await page.route('**/api/v1/**',route=>{if(route.request().method()==='POST'){posts++;input=route.request().postDataJSON().input;return route.abort('failed')}if(new URL(route.request().url()).pathname===root+'/config')return route.fulfill({json:sample('source-snapshot-config')});queries++;return queries===1?route.fulfill({status:404,json:{error:'NOT_FOUND'}}):route.fulfill({json:receipt(input)})});
  await enter(page);await prepare(page);await page.getByRole('button',{name:'导入来源快照',exact:true}).click();await expect(page.getByText('提交结果待确认。请查询原请求回执；不会自动重试或提交下一批。')).toBeVisible();await page.getByRole('button',{name:'查询快照回执',exact:true}).click();await expect(page.getByRole('alert')).toContainText('不代表未知提交没有生效');await expect(page.getByRole('button',{name:'读取快照配置',exact:true})).toBeDisabled();await page.getByRole('button',{name:'查询快照回执',exact:true}).click();await expect(page.locator('[data-snapshot-receipt]')).toBeVisible();expect(posts).toBe(1)
})
test('duplicate identity input is refused before POST',async({page})=>{
  let posts=0;await page.route('**/api/v1/**',r=>{if(r.request().method()==='POST')posts++;return r.fulfill({json:sample('source-snapshot-config')})});await enter(page);await prepare(page);const row=sample('source-snapshot-input').input.records[0];await page.getByRole('textbox',{name:'来源记录 JSON',exact:true}).fill(JSON.stringify([row,{...row,externalId:'other'}]));await page.getByRole('checkbox',{name:'已核对标识、观测时间与完整性，确认导入本批'}).check();await page.getByRole('button',{name:'导入来源快照',exact:true}).click();await expect(page.getByRole('alert')).toContainText('来源快照响应');expect(posts).toBe(0)
})
test('source status is explicit, scoped and only fetched on request',async({page})=>{
  const entity=sample('entity'),presence=sample('source-presence-page');presence.tenantId=entity.tenantId;presence.entityId=entity.id;presence.items[0].tenantId=entity.tenantId;presence.items[0].entityId=entity.id;let reads=0;
  await page.route('**/api/v1/**',route=>{const path=new URL(route.request().url()).pathname;if(path.endsWith('/entities/page'))return route.fulfill({json:{...sample('entity-page'),items:[entity],query:{q:'',type:'host',lifecycle:'',after:null,limit:25},nextCursor:null}});if(path.endsWith('/source-presence')){reads++;return route.fulfill({json:presence})}return route.fulfill({json:entity})});
  await page.goto('/#/inventory');await page.getByRole('textbox',{name:'平台开发 Token（仅保存在当前标签页内存）'}).fill(TOKEN_OK);await page.getByRole('button',{name:'刷新列表',exact:true}).click();await page.getByRole('button',{name:'查看详情',exact:true}).click();expect(reads).toBe(0);await page.getByRole('button',{name:'读取来源状态',exact:true}).click();await expect(page.locator('[data-source-presence]')).toContainText('PRESENT');await page.getByRole('textbox',{name:'平台开发 Token（仅保存在当前标签页内存）'}).fill('');await expect(page.locator('[data-source-presence]')).toHaveCount(0)
})
test('late configuration after logout does not restore form or payload',async({page})=>{
  let release=()=>{};const held=new Promise<void>(r=>{release=r});await page.route('**'+root+'/config',async r=>{await held;await r.fulfill({json:sample('source-snapshot-config')})});await enter(page);const waiting=page.waitForRequest('**'+root+'/config');await page.getByRole('button',{name:'读取快照配置',exact:true}).click();await waiting;await page.getByRole('textbox',{name:'平台开发 Token（仅保存在当前标签页内存）'}).fill('');release();await expect(page.getByRole('textbox',{name:'来源记录 JSON',exact:true})).toHaveCount(0)
})
test('future observation is a local validation failure that leaves the form editable',async({page})=>{
  let posts=0;await page.route('**/api/v1/**',r=>{if(r.request().method()==='POST')posts++;return r.fulfill({json:sample('source-snapshot-config')})});await enter(page);await prepare(page);await page.getByRole('textbox',{name:'来源观测时间（UTC）',exact:true}).fill('2099-01-01T00:00:00Z');await page.getByRole('checkbox',{name:'已核对标识、观测时间与完整性，确认导入本批'}).check();await page.getByRole('button',{name:'导入来源快照',exact:true}).click();await expect(page.getByRole('alert')).toContainText('来源快照响应');await expect(page.getByRole('textbox',{name:'来源记录 JSON',exact:true})).toBeEnabled();await expect(page.getByRole('button',{name:'读取快照配置',exact:true})).toBeEnabled();expect(posts).toBe(0)
})
