import { test, expect, type Page } from '@playwright/test'
import { readFileSync } from 'node:fs'
import { TOKEN_OK } from './helpers.ts'
const bundle=JSON.parse(readFileSync(new URL('../../../contracts/catalog/opsweave-core-1.0.0.json',import.meta.url),'utf8'))
const hash='sha256:'+'a'.repeat(64)
async function setup(page:Page){
 const calls:{path:string;body:any}[]=[];let saved:any;let published:any;const runs:any[]=[]
 await page.route(/\/api\/v1\/integrations\/workflows(?:\/|$)/,async route=>{
  const path=new URL(route.request().url()).pathname,body=route.request().postDataJSON();calls.push({path,body});let response:any
  if(path.endsWith('/workflows'))response={schemaVersion:'2.0',storage:'memory',drafts:{items:saved?[saved]:[],truncated:false},published:{items:published?[published]:[],truncated:false},models:bundle.definitions.filter((m:any)=>m.kind==='ENTITY').map((definition:any)=>({definition,digest:hash})),modelsTruncated:false,zabbixSource:{instanceId:'zabbix-fixture',mode:'fixture'},runs:{items:runs,truncated:false}}
  else if(path.endsWith('/drafts')){saved={definition:body.definition,layout:body.layout,digest:hash,state:'DRAFT',editVersion:body.expectedEditVersion+1,updatedAt:new Date().toISOString(),preview:null};response=saved}
  else if(path.endsWith('/preview')||path.endsWith('/run')){const entry=path.endsWith('/run')?published:saved;const receipt={id:'10000000-0000-4000-8000-000000000001',digest:hash,inputDigest:hash,origin:entry.definition.source.kind==='MANUAL_SAMPLE'?'MANUAL_SAMPLE':'fixture',accepted:1,rejected:0,filtered:0,createdAt:new Date().toISOString()};if(entry===saved)saved.preview=receipt;runs.unshift({workflowId:entry.definition.id,revision:entry.definition.revision,mode:entry===saved?'PREVIEW':'RUN',receipt});response={receipt,evaluation:{rows:[{index:0,status:'ACCEPTED',steps:entry.definition.nodes.map((n:any)=>({nodeId:n.id,type:n.type,status:'OK',values:{name:'Fixture service'},issues:[]}))}],accepted:1,rejected:0,filtered:0,dryRun:true,writesPerformed:false},retainedCount:1,missingRaw:0,truncated:false,sourceStatus:receipt.origin==='MANUAL_SAMPLE'?'MANUAL_SAMPLE':'SUCCEEDED'}}
  else if(path.endsWith('/publish')){published={...saved,state:'PUBLISHED',editVersion:0};response=published}
  else response=path.includes('/versions/')?published:saved
  await route.fulfill({contentType:'application/json',body:JSON.stringify(response)})
 })
 await page.goto('/#/integrations/workflows');await page.getByRole('textbox',{name:'平台开发 Token（仅保存在当前标签页内存）'}).fill(TOKEN_OK);await page.getByRole('button',{name:'读取工作流',exact:true}).click();await expect(page.getByRole('button',{name:'＋ 自定义实体模板',exact:true})).toBeVisible();return calls
}
for(const width of [1500,390])test('workflow fixture edit, preview, publish, run and version at '+width,async({page})=>{
 await page.setViewportSize({width,height:1000});const calls=await setup(page);await page.getByRole('button',{name:'＋ 自定义实体模板',exact:true}).click();await expect(page.locator('.workflow-node')).toHaveCount(5); await expect(page.getByRole('combobox',{name:'目标模型',exact:true})).toHaveValue('builtin.service@1'); expect(await page.locator('.x6-edge path').first().evaluate(n=>n.namespaceURI)).toBe('http://www.w3.org/2000/svg');await expect(page.getByRole('button',{name:'发布版本',exact:true})).toBeDisabled();
 await page.locator('.workflow-library-item').filter({hasText:'补充默认值'}).click();await page.getByRole('textbox',{name:'缺失时填入'}).fill('Fixture service');await expect(page.locator('.workflow-node')).toHaveCount(6);await page.getByRole('button',{name:'撤销工作流修改'}).click();await page.getByRole('button',{name:'重做工作流修改'}).click();await page.getByRole('button',{name:'保存草稿',exact:true}).click();await expect(page.getByText('草稿已保存；尚未发布或启用采集。',{exact:true})).toBeVisible();
 const request=calls.find(c=>c.path.endsWith('/drafts'))!.body;expect(request.definition.nodes[3].type).toBe('DEFAULT');expect(request.definition.nodes[3].config.value).toBe('Fixture service');expect(request.definition.target.id).toBe('builtin.service');expect(request.expectedEditVersion).toBe(0);
 await page.getByRole('button',{name:'预览当前草稿',exact:true}).click();await expect(page.getByRole('button',{name:'发布版本',exact:true})).toBeEnabled();await page.getByRole('combobox',{name:'选择工作流节点'}).selectOption('output');await expect(page.locator('[data-workflow-output]')).toContainText('Fixture service');await expect(page.locator('.workflow-history')).toContainText('MANUAL_SAMPLE');
 await page.getByRole('button',{name:'发布版本',exact:true}).click();await expect(page.getByText('版本已发布。当前支持只读测试运行，未启用自动采集或写入。',{exact:true})).toBeVisible();await expect(page.getByRole('textbox',{name:'工作流名称',exact:true})).toBeDisabled();await page.getByRole('button',{name:'测试运行已发布版本',exact:true}).click();await expect(page.locator('.workflow-history')).toContainText('版本测试');await page.getByRole('button',{name:'创建下一版',exact:true}).click();await expect(page.locator('.workflow-state')).toContainText('v2');await expect(page.getByRole('button',{name:'发布版本',exact:true})).toBeDisabled();expect(calls.filter(c=>c.path.endsWith('/run'))[0].body.dryRun).toBe(true);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)
})
test('X6 drag and keyboard movement persist layout without execution',async({page})=>{
 await page.setViewportSize({width:1500,height:1000});const calls=await setup(page);await page.getByRole('button',{name:'＋ 自定义实体模板',exact:true}).click();await expect(page.locator('[data-engine=x6]')).toHaveAttribute('data-graph-status','ready');const node=page.locator('[data-node-id=source]');await node.scrollIntoViewIfNeeded();const canvas=page.locator('.x6-canvas');const beforeNode=(await node.boundingBox())!,beforeCanvas=(await canvas.boundingBox())!;const scrollBefore=await page.evaluate(()=>scrollY);await page.mouse.move(beforeCanvas.x+beforeCanvas.width-20,beforeNode.y+20);await page.mouse.wheel(0,150);await expect.poll(()=>page.evaluate(()=>scrollY)).toBeGreaterThan(scrollBefore);const afterNode=(await node.boundingBox())!,afterCanvas=(await canvas.boundingBox())!;expect(Math.abs((afterNode.y-afterCanvas.y)-(beforeNode.y-beforeCanvas.y))).toBeLessThan(2);await node.scrollIntoViewIfNeeded();const box=(await node.boundingBox())!;await page.mouse.move(box.x+60,box.y+30);await page.mouse.down();await page.mouse.move(box.x+105,box.y+62,{steps:8});await page.mouse.up();await node.focus();await page.keyboard.press('ArrowRight');expect(calls).toHaveLength(1);await page.getByRole('button',{name:'保存草稿',exact:true}).click();await expect(page.getByText('草稿已保存；尚未发布或启用采集。',{exact:true})).toBeVisible();const position=calls.at(-1)!.body.layout.source;expect(position.x).toBeGreaterThan(190);expect(position.y).toBeGreaterThan(40);expect(Number.isInteger(position.x)&&Number.isInteger(position.y)).toBe(true);expect(calls.at(-1)!.body.definition).not.toHaveProperty('cells');await page.getByRole('button',{name:'适应画布'}).click();expect(calls).toHaveLength(2)
})

test('Zabbix workflow sends only an explicit batch and preserves fixture marker',async({page})=>{
 const calls=await setup(page);await page.getByRole('button',{name:'＋ Zabbix 主机模板',exact:true}).click();await expect(page.getByRole('textbox',{name:'工作流手工样本'})).toHaveCount(0);await page.getByRole('button',{name:'保存草稿',exact:true}).click();await expect(page.getByRole('button',{name:'预览当前草稿',exact:true})).toBeEnabled();await page.getByRole('textbox',{name:'工作流来源批次'}).fill('10000000-0000-4000-8000-000000000002');await page.getByRole('button',{name:'预览当前草稿',exact:true}).click();await expect(page.locator('.workflow-result-counts')).toContainText('fixture');const command=calls.find(c=>c.path.endsWith('/preview'))!.body;expect(command).not.toHaveProperty('samples');expect(command.syncRunId).toBe('10000000-0000-4000-8000-000000000002');expect(calls.some(c=>c.path.includes('/sync'))).toBe(false)
})
test('session change clears private drafts and sample without local storage',async({page})=>{
 await setup(page);await page.getByRole('button',{name:'＋ 自定义实体模板',exact:true}).click();await page.getByRole('textbox',{name:'工作流手工样本'}).fill('[{"name":"private fixture"}]');await page.getByRole('textbox',{name:'平台开发 Token（仅保存在当前标签页内存）'}).fill('changed-token-long-enough-123456789');await expect(page.locator('.workflow-node')).toHaveCount(0);await expect(page.locator('.workflow-welcome')).toBeVisible();expect(await page.evaluate(()=>JSON.stringify({...localStorage,...sessionStorage}))).not.toContain('private fixture')
})
test('a write-capable response cannot unlock workflow publication',async({page})=>{
 await setup(page);await page.getByRole('button',{name:'＋ 自定义实体模板',exact:true}).click();await page.getByRole('button',{name:'保存草稿',exact:true}).click();await expect(page.getByRole('button',{name:'预览当前草稿',exact:true})).toBeEnabled();await page.route('**/api/v1/integrations/workflows/preview',route=>route.fulfill({contentType:'application/json',body:JSON.stringify({writesPerformed:true})}));await page.getByRole('button',{name:'预览当前草稿',exact:true}).click();await expect(page.getByRole('alert').filter({hasText:'不符合契约'})).toBeVisible();await expect(page.getByRole('button',{name:'发布版本',exact:true})).toBeDisabled()
})
