import { test, expect, type Page } from '@playwright/test'
import { readFileSync } from 'node:fs'
import { TOKEN_OK } from './helpers.ts'
const fixture=JSON.parse(readFileSync(new URL('../../../contracts/examples/v2/workflow-run-detail.json',import.meta.url),'utf8'))
const tokenLabel='平台开发 Token（仅保存在当前标签页内存）'
async function setup(page:Page,detail:any=structuredClone(fixture)){
 const calls:{method:string;path:string}[]=[]
 await page.route(/\/api\/v1\/integrations\/workflows(?:\/|$)/,async route=>{const path=new URL(route.request().url()).pathname;calls.push({method:route.request().method(),path});const value=path.includes('/runs/')?detail:{schemaVersion:'2.0',storage:'memory',drafts:{items:[],truncated:false},published:{items:[],truncated:false},models:[],modelsTruncated:false,zabbixSource:{instanceId:'fixture-source',mode:'fixture'},runs:{items:[detail.run],truncated:true}};await route.fulfill({contentType:'application/json',body:JSON.stringify(value)})})
 await page.goto('/#/integrations/workflows/runs');await page.getByRole('textbox',{name:tokenLabel}).fill(TOKEN_OK);await page.getByRole('button',{name:'读取运行记录',exact:true}).click();await expect(page.getByRole('button',{name:'查看明细',exact:true})).toBeVisible();return calls
}
for(const width of [1500,390])test('mixed trace fixture is queryable with failure details after refresh at '+width,async({page})=>{
 await page.setViewportSize({width,height:1000});const calls=await setup(page);await expect(page.locator('.run-table')).toContainText('部分失败');await page.getByRole('combobox',{name:'筛选运行结果'}).selectOption('FAILED');await expect(page.getByRole('button',{name:'查看明细'})).toHaveCount(0);await page.getByRole('combobox',{name:'筛选运行结果'}).selectOption('PARTIAL');await page.getByRole('button',{name:'查看明细'}).click();await expect(page.locator('[data-run-detail]')).toContainText('MANUAL_SAMPLE');await expect(page.locator('.run-record')).toHaveCount(3);await expect(page.locator('.run-node-stats>div')).toHaveCount(5);await expect(page.locator('.run-record').filter({hasText:'记录 2'})).toContainText('port：字段类型不匹配（TYPE_MISMATCH）');await expect(page.locator('.run-record').filter({hasText:'记录 2'})).toContainText('此前记录已失败或被过滤');await page.getByRole('combobox',{name:'筛选记录结果'}).selectOption('REJECTED');await expect(page.locator('.run-record')).toHaveCount(1);await expect(page.locator('.run-record')).toContainText('记录 2');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)
 await page.reload();await page.getByRole('textbox',{name:tokenLabel}).fill(TOKEN_OK);await page.getByRole('textbox',{name:'查询运行 ID',exact:true}).fill(fixture.run.receipt.id);await page.getByRole('button',{name:'查询详情',exact:true}).click();await expect(page.locator('.run-record')).toHaveCount(3);expect(calls.every(c=>c.method==='GET')).toBe(true)
})
test('legacy receipt never invents step details',async({page})=>{const d=structuredClone(fixture);d.trace=null;await setup(page,d);await page.getByRole('button',{name:'查看明细'}).click();await expect(page.locator('[data-run-detail]')).toContainText('旧版计数回执');await expect(page.locator('.run-record')).toHaveCount(0)})
test('corrupt trace counts and unexpected body fields fail closed',async({page})=>{const d=structuredClone(fixture);d.trace.rows[0].status='REJECTED';await setup(page,d);await page.getByRole('button',{name:'查看明细'}).click();await expect(page.getByRole('alert')).toContainText('不符合契约');await expect(page.locator('[data-run-detail]')).toHaveCount(0);d.trace.rows[0].status='ACCEPTED';d.trace.rows[0].steps[0].values={name:'must not show'};await page.getByRole('button',{name:'查看明细'}).click();await expect(page.getByRole('alert')).toContainText('不符合契约');await expect(page.locator('[data-run-detail]')).toHaveCount(0)})
test('upstream failure and fixture provenance stay visible',async({page})=>{const d=structuredClone(fixture);d.run.receipt.origin='fixture';Object.assign(d.trace,{source:{kind:'ZABBIX_HOST',instanceId:'zabbix-fixture'},syncRunId:'10000000-0000-4000-8000-000000000003',sourceStatus:'FAILED',retainedCount:9,missingRaw:2,truncated:true});await setup(page,d);await page.getByRole('button',{name:'查看明细'}).click();await expect(page.locator('[data-run-detail]')).toContainText('fixture');await expect(page.locator('[data-run-detail]')).toContainText('缺失 Raw 2');await expect(page.locator('[data-run-detail]')).toContainText('不代表整个来源批次成功')})
test('session replacement clears details and blocks a late private response',async({page})=>{await setup(page);await page.getByRole('button',{name:'查看明细'}).click();await expect(page.locator('[data-run-detail]')).toBeVisible();let release!:()=>void;let arrived!:()=>void;const seen=new Promise<void>(r=>arrived=r),hold=new Promise<void>(r=>release=r);await page.route('**/workflows/runs/*',async route=>{arrived();await hold;await route.fulfill({contentType:'application/json',body:JSON.stringify(fixture)}).catch(()=>{})});await page.getByRole('button',{name:'查询详情'}).click();await seen;await page.getByRole('textbox',{name:tokenLabel}).fill('other-session-fixture-123456789');release();await expect(page.locator('[data-run-detail]')).toHaveCount(0);await expect(page.getByRole('button',{name:'查看明细'})).toHaveCount(0);expect(await page.evaluate(()=>JSON.stringify({...localStorage,...sessionStorage}))).not.toContain(fixture.run.receipt.id)})
