import {test,expect,type Page} from '@playwright/test'
import {readFileSync,mkdirSync} from 'node:fs'
import {WORKFLOW_OPERATORS,TOKEN_OK} from './helpers.ts'
// Closed protocol fixtures; real PG and HTTP evidence are verified separately.
const example=(name:string)=>JSON.parse(readFileSync(new URL('../../../contracts/examples/v2/'+name+'.json',import.meta.url),'utf8'))
const iso=(ms:number)=>new Date(ms).toISOString().replace('.000Z','Z'),tokenLabel='平台开发 Token（仅保存在当前标签页内存）'
const region=(page:Page)=>page.getByRole('region',{name:'运行检查历史',exact:true})
async function fixture(page:Page,mode='normal',hold?:Promise<void>,link=''){
 const now=Math.floor(Date.now()/1000)*1000,definition=example('workflow-real-log-definition');for(const n of definition.nodes)n.operatorDigest=WORKFLOW_OPERATORS.operators.find((o:any)=>o.type===n.type)!.digest
 const entries=[1,2,3].map(revision=>({definition:{...definition,revision},digest:'sha256:'+(revision===1?'a':'b').repeat(64),state:'PUBLISHED',editVersion:0,updatedAt:iso(now),preview:null,layout:Object.fromEntries(definition.nodes.map((n:any,i:number)=>[n.id,{x:160,y:i*160}]))}))
 const total=mode==='empty'?0:mode==='twentyone'?21:45,calls:{path:string;method:string;query:string}[]=[]
 function response(revision:number,offset:number){const entry=entries[revision-1],ref={id:definition.id,revision,digest:entry.digest},items=Array.from({length:Math.min(20,total-offset)},(_,j)=>{const i=offset+j,at=now-i*1000;const o:any={id:'10000000-0000-4000-8000-'+(i+1).toString(16).padStart(12,'0'),reference:ref,kind:'LOG_STREAM',generation:1,state:'SOURCE_FAILED',from:iso(at-80000),till:iso(at-20000),startedAt:iso(at),completedAt:iso(at),queueWaitMillis:null,relatedBatchId:null,error:'SOURCE_UNAVAILABLE',result:{coverage:'UNAVAILABLE',sampleRate:null,received:null,accepted:null,rejected:null,filtered:null,unknown:null,schemaMismatch:null,missingIdentity:null,invalidTimestamp:null,unitMismatch:null,nodes:[]}};if(i===0){o.queueWaitMillis=275;o.dispatch={id:'20000000-0000-4000-8000-000000000135',enqueuedAt:iso(at-275),startedAt:iso(at)};o.sourceRead={attempts:1,completed:0,failed:1,received:null,failureCode:'UNAVAILABLE',startedAt:iso(at),completedAt:iso(at)}}return o});return {schemaVersion:'2.0',asOf:iso(now),snapshotAt:iso(now),reference:ref,coverage:'RECORDED_CHECKS',offset,recordedCount:total,items,nextCursor:offset+items.length<total?'h1.fixture'+(offset+20):null,hasMore:offset+items.length<total}}
 await page.route(/\/api\/v1\/integrations\/workflows(?:\/|$)/,async route=>{
  const url=new URL(route.request().url());calls.push({path:url.pathname,method:route.request().method(),query:url.search});const another=route.request().headers().authorization?.includes('other-session')
  if(url.pathname.includes('/versions/')&&!url.pathname.endsWith('/history')){const revision=Number(url.pathname.split('/versions/')[1].split('/')[1]);return url.pathname.includes('/'+definition.id+'/')&&entries[revision-1]?route.fulfill({json:entries[revision-1]}):route.fulfill({status:404,json:{error:'NOT_FOUND'}})}
  if(!url.pathname.endsWith('/history'))return route.fulfill({json:{schemaVersion:'2.0',storage:'memory',operatorCatalog:WORKFLOW_OPERATORS,drafts:{items:[],truncated:false},published:{items:another||mode==='no-versions'?[]:entries.slice(0,2),truncated:false},models:[],modelsTruncated:false,zabbixSource:{instanceId:'fixture-source',mode:'fixture'},runs:{items:[],truncated:false}}})
  const offset=Number((url.searchParams.get('cursor')??'').replace('h1.fixture',''))||0,revision=Number(url.pathname.split('/versions/')[1].split('/')[0]);if(hold&&offset)await hold;if(mode==='403')return route.fulfill({status:403,json:{error:'FORBIDDEN'}});if(mode==='409'&&offset)return route.fulfill({status:409,json:{error:'CONFLICT'}})
  const value:any=response(revision,offset)
  if(mode==='private')value.watermark=123
  if(mode==='bad-time')value.snapshotAt=iso(now).replace('Z','+00:00')
  if(mode==='bad-id'&&value.items.length)value.items[0].id='1-1-1-1-1'
  if(mode==='foreign-ref')value.reference.id='other-fixture'
  if(mode==='invented-zero'&&value.items.length)value.items[0].result.received=0
  if(mode==='bad-cursor')value.nextCursor='h1.abc='
  if(mode==='expired')value.asOf=iso(now+600000)
  if(offset){if(mode==='wrong-count')value.recordedCount=44;if(mode==='wrong-offset')value.offset=0;if(mode==='wrong-snapshot')value.snapshotAt=iso(now-1000);if(mode==='duplicate')value.items[0]=response(revision,0).items[0];if(mode==='out-of-order')value.items.reverse();if(mode==='false-complete'){value.hasMore=false;value.nextCursor=null}}
  await route.fulfill({json:value}).catch(()=>{})
 })
 await page.goto('/#/integrations/workflows/runs'+link);await page.getByRole('textbox',{name:tokenLabel}).fill(TOKEN_OK);return {calls,entries,now}
}
for(const width of [1440,1024,390])for(const theme of ['light','dark'])test('history remains bounded and readable at '+width+' '+theme,async({page})=>{
 await page.setViewportSize({width,height:1000});await page.addInitScript(value=>localStorage.setItem('opsweave.ui.theme',value),theme);const f=await fixture(page);await expect(region(page).locator('tbody tr')).toHaveCount(20);expect(f.calls.filter(c=>c.path.endsWith('/history'))).toHaveLength(1);expect(f.calls.filter(c=>c.path==='/api/v1/integrations/workflows')).toHaveLength(1);await expect(region(page)).toContainText('已显示 20 / 45 条');await expect(region(page)).toContainText('275 ms');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)
 for(const row of await region(page).locator('tbody tr').all())expect((await row.boundingBox())!.height).toBeLessThanOrEqual(100)
 await region(page).getByRole('button',{name:/查看检查/}).first().focus();await page.keyboard.press('Enter');await expect(page.getByRole('article',{name:'检查节点详情'})).toContainText('275 ms');await page.getByRole('button',{name:'关闭节点明细'}).click();await page.getByRole('button',{name:'加载更早记录'}).click();await expect(region(page).locator('tbody tr')).toHaveCount(40);await page.getByRole('button',{name:'加载更早记录'}).click();await expect(region(page).locator('tbody tr')).toHaveCount(45);await expect(region(page)).toContainText('已到最早记录');expect(f.calls.every(c=>c.method==='GET')).toBe(true)
 await page.getByRole('button',{name:'预览与版本测试',exact:true}).click();await page.getByRole('button',{name:'运行检查历史',exact:true}).click();expect(f.calls.filter(c=>c.path.endsWith('/history'))).toHaveLength(3);expect(await page.evaluate(()=>JSON.stringify({...localStorage,...sessionStorage}))).not.toContain('10000000-0000-4000-8000')
 if(process.env.OPSWEAVE_SOURCE_SCREENSHOTS){mkdirSync(process.env.OPSWEAVE_SOURCE_SCREENSHOTS,{recursive:true});await page.getByRole('button',{name:'刷新运行历史'}).click();await expect(region(page).locator('tbody tr')).toHaveCount(20);await region(page).getByRole('region',{name:'运行检查历史表'}).evaluate(e=>e.scrollLeft=0);await page.screenshot({path:process.env.OPSWEAVE_SOURCE_SCREENSHOTS+'/history-'+width+'-'+theme+'.png',fullPage:true})}
})
test('last page and explicit refresh use one independent snapshot',async({page})=>{const f=await fixture(page,'twentyone');await expect(region(page).locator('tbody tr')).toHaveCount(20);await page.getByRole('button',{name:'加载更早记录'}).click();await expect(region(page).locator('tbody tr')).toHaveCount(21);await page.getByRole('button',{name:'刷新运行历史'}).click();await expect(region(page).locator('tbody tr')).toHaveCount(20);expect(f.calls.filter(c=>c.path.endsWith('/history')).map(c=>c.query)).toEqual(['','?cursor=h1.fixture20',''])})
test('no recorded checks and no eligible versions remain explicit',async({page})=>{const f=await fixture(page,'empty');await expect(region(page)).toContainText('此版本暂无已记录的检查');await expect(page.getByRole('button',{name:'加载更早记录'})).toHaveCount(0);expect(f.calls.filter(c=>c.path.endsWith('/history'))).toHaveLength(1);await page.getByRole('button',{name:'清除开发会话'}).click();await page.unrouteAll();const next=await fixture(page,'no-versions');await expect(region(page)).toContainText('暂无可读取运行历史');expect(next.calls.filter(c=>c.path.endsWith('/history'))).toHaveLength(0)})
for(const mode of ['private','bad-time','bad-id','foreign-ref','invented-zero','bad-cursor','expired'])test('rejects invalid first page '+mode,async({page})=>{const f=await fixture(page,mode);await expect(region(page).getByRole('alert')).toContainText('不符合契约');await expect(region(page).locator('tbody tr')).toHaveCount(0);await page.getByRole('button',{name:'预览与版本测试'}).click();await page.getByRole('button',{name:'运行检查历史',exact:true}).click();expect(f.calls.filter(c=>c.path.endsWith('/history'))).toHaveLength(1)})
for(const mode of ['wrong-count','wrong-offset','wrong-snapshot','duplicate','out-of-order','false-complete','409'])test('retains the prior snapshot when a later page fails '+mode,async({page})=>{const f=await fixture(page,mode);await expect(region(page).locator('tbody tr')).toHaveCount(20);await page.getByRole('button',{name:'加载更早记录'}).click();await expect(region(page).getByRole('alert')).toContainText(mode==='409'?'快照已失效':'不符合契约');await expect(region(page).locator('tbody tr')).toHaveCount(20);expect(f.calls.filter(c=>c.path.endsWith('/history'))).toHaveLength(2)})
test('fixed-version links and explicit switching never select the latest silently',async({page})=>{const definition=example('workflow-real-log-definition');const f=await fixture(page,'normal',undefined,'?workflowId='+definition.id+'&revision=2');await expect(region(page).locator('tbody tr')).toHaveCount(20);await expect(page.getByRole('combobox',{name:'历史发布版本'})).toHaveValue(definition.id+'@2');await page.getByRole('combobox',{name:'历史发布版本'}).selectOption(definition.id+'@1');await expect(region(page).locator('tbody tr')).toHaveCount(20);expect(f.calls.filter(c=>c.path.endsWith('/history')).map(c=>c.path.split('/versions/')[1])).toEqual(['2/history','1/history'])})
test('missing linked version has no implicit fallback',async({page})=>{const f=await fixture(page,'normal',undefined,'?workflowId=missing-fixture&revision=1');await expect(region(page).getByRole('alert')).toContainText('发布版本不可用');expect(f.calls.filter(c=>c.path.endsWith('/history'))).toHaveLength(0)})
test('forged link scope is rejected before workspace reads',async({page})=>{const f=await fixture(page,'normal',undefined,'?tenantId=forged');await expect(page.getByRole('alert').first()).toContainText('链接参数无效');expect(f.calls).toHaveLength(0)})
test('403 clears the global private session and does not retry',async({page})=>{const f=await fixture(page,'403');await expect(page.getByRole('alert')).toContainText('HTTP 403');await expect(region(page)).toHaveCount(0);await page.waitForTimeout(1000);expect(f.calls.filter(c=>c.path.endsWith('/history'))).toHaveLength(1);expect(f.calls.filter(c=>c.path==='/api/v1/integrations/workflows')).toHaveLength(1)})
test('identity replacement cancels late pages and clears private results',async({page})=>{let release!:()=>void;const hold=new Promise<void>(r=>release=r),f=await fixture(page,'normal',hold);await expect(region(page).locator('tbody tr')).toHaveCount(20);await page.getByRole('button',{name:'加载更早记录'}).click();await expect(page.getByRole('combobox',{name:'历史发布版本'})).toBeDisabled();await expect(page.getByRole('button',{name:'预览与版本测试'})).toBeDisabled();await page.getByRole('textbox',{name:tokenLabel}).fill('other-session-fixture-token-123456789');release();await expect(region(page)).toContainText('暂无可读取运行历史');await expect(region(page).locator('tbody tr')).toHaveCount(0);expect(f.calls.filter(c=>c.path.endsWith('/history'))).toHaveLength(2)})

test('an older fixed version is fetched explicitly beyond the directory',async({page})=>{const definition=example('workflow-real-log-definition'),f=await fixture(page,'normal',undefined,'?workflowId='+definition.id+'&revision=3');await expect(region(page).locator('tbody tr')).toHaveCount(20);await expect(page.getByRole('combobox',{name:'历史发布版本'})).toHaveValue(definition.id+'@3');expect(f.calls.filter(c=>c.path.includes('/versions/'+definition.id+'/3'))).toHaveLength(1);expect(f.calls.filter(c=>c.path.endsWith('/history')).map(c=>c.path.split('/versions/')[1])).toEqual(['3/history'])})
test('view selection stays visible and flat under the legacy page button styles',async({page})=>{await fixture(page);await expect(region(page).locator('tbody tr')).toHaveCount(20);const active=page.getByRole('button',{name:'运行检查历史',exact:true}),inactive=page.getByRole('button',{name:'预览与版本测试',exact:true});await expect(active).toHaveCSS('border-top-width','0px');await expect(active).toHaveCSS('border-bottom-width','2px');await expect(active).toHaveCSS('border-radius','0px');const activeColor=await active.evaluate(e=>getComputedStyle(e).color),inactiveColor=await inactive.evaluate(e=>getComputedStyle(e).color);expect(activeColor).not.toBe(inactiveColor)})
