import {test,expect,type Page} from '@playwright/test'
import {readFileSync,mkdirSync} from 'node:fs'
import {WORKFLOW_OPERATORS,TOKEN_OK,closeWorkflowInspector} from './helpers.ts'

// Explicit protocol-shaped browser Fixtures. Real journal and sink checks run separately.
const example=(name:string)=>JSON.parse(readFileSync(new URL('../../../contracts/examples/v2/'+name+'.json',import.meta.url),'utf8'))
const definition=example('workflow-real-metric-definition'),mapping=example('metric-mapping-definition'),digest='sha256:'+'a'.repeat(64),batchId='10000000-0000-4000-8000-000000000117'
const region=(page:Page)=>page.getByRole('region',{name:'持续指标采集',exact:true})
async function fixture(page:Page,mode='normal',delay?:Promise<void>){
 const calls:{path:string;body:any}[]=[],created=Date.now(),from=Math.floor(created/1000)*1000-80000
 const chosen=mode==='new-version'?{...definition,revision:2}:definition
 const saved={definition:chosen,layout:Object.fromEntries(definition.nodes.map((n:any,i:number)=>[n.id,{x:180,y:40+i*160}])),digest,state:'PUBLISHED',editVersion:0,updatedAt:new Date(created).toISOString(),preview:null}
 const task=(state='RUNNING',generation=1,confirmedWindows=0)=>({workflowId:definition.id,revision:chosen.revision,digest,generation,state,cursor:new Date(from+confirmedWindows*60000).toISOString(),pendingBatchId:null,confirmedWindows,confirmedPoints:confirmedWindows,sessionBatches:confirmedWindows,updatedAt:new Date(created+confirmedWindows*60000).toISOString(),error:state==='FAILED'?'OUTPUT_UNCONFIRMED':null})
 const labels={tenant_id:'stream-browser-fixture',owner_scope:'a'.repeat(64),source_instance_id:definition.source.instanceId,external_item_id:definition.source.metric.itemId,host_external_id:definition.source.metric.hostId,metric_key:mapping.metricKey,unit:mapping.unit,mapping_id:mapping.mappingPin.id,mapping_revision:String(mapping.mappingPin.revision),mapping_digest:mapping.mappingPin.digest,workflow_id:definition.id,workflow_revision:String(chosen.revision),workflow_digest:digest,configuration_digest:definition.source.configuration.digest,data_mode:'zabbix-jsonrpc',collection_mode:'WINDOW_60S',dim_mode:'user'}
 const batch=(state='CONFIRMED')=>({id:batchId,workflowId:definition.id,revision:chosen.revision,digest,from:new Date(from).toISOString(),till:new Date(from+60000).toISOString(),createdAt:new Date(created).toISOString(),updatedAt:new Date(created).toISOString(),state,inputCount:1,filtered:0,collapsed:0,labels,batchDigest:digest,timestamps:[from+1000],error:state==='UNKNOWN'?'OUTPUT_UNCONFIRMED':null})
 let current:any=null,batches:any[]=[],original:any=null,reads=0,posts=0
 if(mode==='unknown'){current={...task('FAILED'),pendingBatchId:batchId,sessionBatches:1};batches=[batch('UNKNOWN')]}
 if(['late','badLate'].includes(mode)){const original=batch();current={...task('RUNNING',1,1),confirmedPoints:2,sessionBatches:2};batches=[{...original,id:'10000000-0000-4000-8000-000000000121',inputCount:2,timestamps:[from+1000,from+2000],reconcilesBatchId:batchId,latePoints:mode==='badLate'?2:1},original]}
 if(mode==='large'){current={...task('RUNNING',1,1),confirmedPoints:600};batches=[{...batch(),inputCount:600,timestamps:Array.from({length:600},(_,i)=>from+i*50)}]}
 if(mode==='limit'){current={...task('FAILED'),error:'WINDOW_INCOMPLETE'};batches=[]}
 await page.route(/\/api\/v1\/integrations\/workflows(?:\/|$)/,async route=>{
  const path=new URL(route.request().url()).pathname,body=route.request().postDataJSON();calls.push({path,body})
  if(path.endsWith('/workflows'))return route.fulfill({json:{schemaVersion:'2.0',storage:'postgres',operatorCatalog:WORKFLOW_OPERATORS,metricMappings:[mapping],drafts:{items:[],truncated:false},published:{items:[saved],truncated:false},models:[],modelsTruncated:false,zabbixSource:{instanceId:'fixture-source',mode:'fixture'},runs:{items:[],truncated:false}}})
  if(path.includes('/versions/'))return route.fulfill({json:saved})
  if(path.includes('/metric-streams/workflows/')&&!path.endsWith('/verification')){reads++;if(mode==='fail')return route.fulfill({status:503,json:{error:'SOURCE_UNAVAILABLE'}});const result={schemaVersion:'2.0',available:true,mode:'LOCAL_DEV_METRIC',windowSeconds:60,settleSeconds:10,maxBatchPoints:600,maxSessionBatches:20,maxHistoryRequests:20,lookbackSeconds:60,task:current,batches,...(['new-version','closed-version','bad-control'].includes(mode)?{control:{generation:current?.generation??2,startAllowed:!current&&mode!=='closed-version',recoveryClosed:mode==='closed-version',...(mode==='bad-control'?{tenantId:'forged'}:{})}}:{})};expect(new URL(route.request().url()).searchParams.get('revision')).toBe(String(chosen.revision));return route.fulfill({json:mode==='corrupt'?{...result,samples:[]}:result})}
  if(path.endsWith('/verification')){current={...current,state:"STOPPED",error:null,cursor:new Date(from+60000).toISOString(),pendingBatchId:null,confirmedWindows:1,confirmedPoints:1,updatedAt:new Date(created).toISOString()};batches=[batch()];return route.fulfill({json:{schemaVersion:'2.0',available:true,mode:'LOCAL_DEV_METRIC',windowSeconds:60,settleSeconds:10,maxBatchPoints:600,maxSessionBatches:20,maxHistoryRequests:20,lookbackSeconds:60,task:current,batches}})}
  if(path.includes('/metric-streams/commands/')){if(delay)await delay;return route.fulfill({json:original})}
  if(path.includes('/metric-streams/')&&body){posts++;const operation=path.split('/').at(-1)!.toUpperCase();current=task(operation==='STOP'?'STOPPED':'RUNNING',body.expectedGeneration+1,operation==='START'?1:current?.confirmedWindows??0);batches=[batch()];original={requestId:body.requestId,operation,commandDigest:digest,acceptedAt:current.updatedAt,task:current};if(mode==='lost'&&posts===1)return route.abort('failed');return route.fulfill({json:original})}
  return route.fulfill({status:404,json:{error:'NOT_FOUND'}})
 })
 await page.goto('/#/integrations/workflows');await page.getByRole('textbox',{name:'平台开发 Token（仅保存在当前标签页内存）'}).fill(TOKEN_OK);await page.getByRole('button',{name:'查看',exact:true}).click();await closeWorkflowInspector(page);await page.getByText('持续采集',{exact:true}).click();await expect(region(page)).toBeVisible();return {calls,reads:()=>reads,posts:()=>posts}
}
for(const width of [1440,390])for(const theme of ['light','dark'])test(`metric stream Fixture ${width} ${theme}`,async({page})=>{
 await page.setViewportSize({width,height:940});await page.addInitScript(theme=>localStorage.setItem('opsweave.ui.theme',theme),theme);const f=await fixture(page);await expect(region(page).getByRole('button',{name:'开始采集',exact:true})).toBeEnabled();await region(page).getByRole('button',{name:'开始采集',exact:true}).click();await expect(region(page)).toContainText('已确认 1 窗口 · 1 点');await region(page).getByRole('button',{name:'停止采集',exact:true}).click();await expect(region(page)).toContainText('已停止');expect(f.posts()).toBe(2);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await expect(region(page).getByRole('link',{name:mapping.metricKey,exact:true})).toHaveAttribute('href',/modeling\/metrics/);if(process.env.OPSWEAVE_SOURCE_SCREENSHOTS){mkdirSync(process.env.OPSWEAVE_SOURCE_SCREENSHOTS,{recursive:true});await page.screenshot({path:process.env.OPSWEAVE_SOURCE_SCREENSHOTS+`/stream-${width}-${theme}.png`,fullPage:true})}
})
test('unknown batch verifies without output resend and resumes same checkpoint',async({page})=>{const f=await fixture(page,'unknown');await expect(region(page).getByRole('button',{name:'恢复采集',exact:true})).toBeDisabled();await region(page).getByRole('button',{name:'核验原批次',exact:true}).click();await expect(region(page)).toContainText('已确认 1 窗口 · 1 点');await region(page).getByRole('button',{name:'恢复采集',exact:true}).click();await expect(region(page)).toContainText('采集中');expect(f.calls.filter(c=>c.path.endsWith('/verification'))).toHaveLength(1);expect(f.calls.filter(c=>/\/(start|stop|resume)$/.test(c.path)).map(c=>c.path.split('/').at(-1))).toEqual(['resume'])})
test('lost control response keeps original request and query does not repeat POST',async({page})=>{const f=await fixture(page,'lost');await region(page).getByRole('button',{name:'开始采集',exact:true}).click();await expect(region(page).getByRole('button',{name:'查询原控制回执',exact:true})).toBeEnabled();await expect(region(page).getByRole('button',{name:'开始采集',exact:true})).toBeDisabled();await page.waitForTimeout(5500);expect(f.posts()).toBe(1);await region(page).getByRole('button',{name:'查询原控制回执',exact:true}).click();await expect(region(page)).toContainText('原操作已受理');await expect(region(page)).toContainText('采集中');expect(f.posts()).toBe(1)})
for(const mode of ['fail','corrupt'])test(`metric stream ${mode} stops automatic reads`,async({page})=>{const f=await fixture(page,mode);await expect(region(page).getByRole('alert')).toContainText(mode==='fail'?'HTTP 503':'不符合契约');await page.waitForTimeout(5500);expect(f.reads()).toBe(1);expect(f.posts()).toBe(0);await region(page).getByRole('button',{name:'刷新状态',exact:true}).click();await expect.poll(f.reads).toBe(2)})
test('identity clear rejects a late original control acknowledgement',async({page})=>{let release!:()=>void;const delay=new Promise<void>(r=>release=r),f=await fixture(page,'lost',delay);await region(page).getByRole('button',{name:'开始采集',exact:true}).click();await region(page).getByRole('button',{name:'查询原控制回执',exact:true}).click();await expect.poll(()=>f.calls.filter(c=>c.path.includes('/commands/')).length).toBe(1);await page.getByRole('button',{name:'清除开发会话',exact:true}).click();release();await expect(region(page)).toHaveCount(0);expect(f.posts()).toBe(1)})
for(const width of [1440,390])for(const theme of ['light','dark'])test(`late reconciliation is a separate batch ${width} ${theme}`,async({page})=>{await page.setViewportSize({width,height:940});await page.addInitScript(theme=>localStorage.setItem('opsweave.ui.theme',theme),theme);const f=await fixture(page,'late');await expect(region(page)).toContainText('已确认 1 窗口 · 2 点 · 本次 2/20 批次');await expect(region(page)).toContainText('迟到补采 · 1 点');await expect(region(page)).toContainText('常规采集');await expect(region(page)).toContainText('每窗最多 600 点');await expect(region(page)).toContainText('回看上一分钟');await region(page).getByText('查看摘要').first().click();await expect(region(page)).toContainText('原批次');expect(f.posts()).toBe(0);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);if(process.env.OPSWEAVE_SOURCE_SCREENSHOTS)await page.screenshot({path:process.env.OPSWEAVE_SOURCE_SCREENSHOTS+`/late-${width}-${theme}.png`,fullPage:true})})
test('six hundred timestamps are accepted',async({page})=>{const f=await fixture(page,'large');await expect(region(page)).toContainText('已确认 1 窗口 · 600 点');expect(f.posts()).toBe(0)})
test('an incomplete window keeps its checkpoint',async({page})=>{const f=await fixture(page,'limit');await expect(region(page)).toContainText('窗口读取超过点数、请求数或时间上限');await expect(region(page).getByRole('button',{name:'恢复采集',exact:true})).toBeEnabled();expect(f.posts()).toBe(0)})
test('false late point count rejects the response and stops refresh',async({page})=>{const f=await fixture(page,'badLate');await expect(region(page).getByRole('alert')).toContainText('不符合契约');await page.waitForTimeout(5500);expect(f.reads()).toBe(1);expect(f.posts()).toBe(0)})

test('new published version starts with the original control generation',async({page})=>{const f=await fixture(page,'new-version');await region(page).getByRole('button',{name:'开始采集',exact:true}).click();await expect(region(page)).toContainText('原操作已受理');const call=f.calls.find(c=>c.path.endsWith('/start'))!;expect(call.body.expectedGeneration).toBe(2);expect(call.body.revision).toBe(2);expect(f.posts()).toBe(1)})
test('historical closed version keeps closure visible without restart',async({page})=>{const f=await fixture(page,'closed-version');await expect(region(page)).toContainText('此版本已终止恢复');await expect(region(page).getByRole('button',{name:'开始采集',exact:true})).toHaveCount(0);expect(f.posts()).toBe(0)})
test('foreign version control metadata fails closed without starting',async({page})=>{const f=await fixture(page,'bad-control');await expect(region(page).getByRole('alert')).toContainText('不符合契约');expect(f.posts()).toBe(0)})
