import {sampleRecoveryFixture,closurePanel,acknowledgeSample} from './sample-recovery-fixture.ts'
import {test,expect,type Page} from '@playwright/test'
import{readFileSync,mkdirSync}from'node:fs'
import{createHash}from'node:crypto'
import{WORKFLOW_OPERATORS,TOKEN_OK,closeWorkflowInspector}from'./helpers.ts'

// Explicit browser Fixtures; actual PG/time-series writes have separate Java and local evidence.
const example=(name:string)=>JSON.parse(readFileSync(new URL('../../../contracts/examples/v2/'+name+'.json',import.meta.url),'utf8'))
const cpu=example('metric-mapping-definition'),definition=example('workflow-real-metric-definition'),digest='sha256:'+'a'.repeat(64)
const sha=(value:string)=>createHash('sha256').update(value).digest('hex')
const hash=(parts:string[])=>'sha256:'+sha(parts.map(p=>Buffer.byteLength(p)+':'+p).join(''))
async function fixture(page:Page,mode='normal',delay?:Promise<void>){
 const calls:{path:string;body:any}[]=[],timestamp=Date.now()-10000,raw={timestamp:new Date(timestamp).toISOString(),sourceKey:cpu.sourceKey,value:'12.5'}
 const saved={definition:structuredClone(definition),layout:Object.fromEntries(definition.nodes.map((n:any,i:number)=>[n.id,{x:180,y:40+i*160}])),digest,state:'PUBLISHED',editVersion:0,updatedAt:new Date().toISOString(),preview:null}
 const runReceipt={id:'10000000-0000-4000-8000-000000000115',digest,inputDigest:digest,origin:'zabbix-jsonrpc',accepted:1,rejected:0,filtered:0,createdAt:new Date().toISOString()}
 let original:any=null,posts=0
 function result(command:any,state='CONFIRMED'){
  const labels={tenant_id:'metric-output-fixture',owner_scope:'a'.repeat(64),source_instance_id:definition.source.instanceId,external_item_id:definition.source.metric.itemId,host_external_id:definition.source.metric.hostId,metric_key:cpu.metricKey,unit:cpu.unit,mapping_id:cpu.mappingPin.id,mapping_revision:String(cpu.mappingPin.revision),mapping_digest:cpu.mappingPin.digest,workflow_id:definition.id,workflow_revision:'1',workflow_digest:digest,configuration_digest:definition.source.configuration.digest,data_mode:'zabbix-jsonrpc',dim_mode:'user'}
  const seriesHash=sha(Object.entries(labels).sort(([a],[b])=>a<b?-1:a>b?1:0).map(([key,v])=>key+'='+v+'\n').join('')),parts=['MANUAL_SAMPLE'];for(const row of command.samples){parts.push('record');Object.entries(row).sort(([a],[b])=>a<b?-1:a>b?1:0).forEach(([key,v])=>parts.push(key,'text',String(v)))}
  return {requestId:command.requestId,workflowId:definition.id,revision:1,digest,previewId:command.previewId,commandDigest:hash(['workflow-metric-output-v1',definition.id,'1',digest,command.previewId,hash(parts)]),createdAt:new Date().toISOString(),updatedAt:new Date().toISOString(),state,accepted:1,filtered:0,collapsed:0,confirmed:state==='CONFIRMED'?1:0,failed:0,unknown:state==='CONFIRMED'?0:1,error:state==='UNKNOWN'?'OUTPUT_UNCONFIRMED':null,labels,seriesHash,batchDigest:hash(['workflow-metric-batch-v1',seriesHash,String(timestamp),'0.125']),timestamps:[timestamp]}
 }
 if(mode==='history')original=result({requestId:'10000000-0000-4000-8000-000000000116',previewId:runReceipt.id,samples:[raw]},'UNKNOWN')
 await page.route(/\/api\/v1\/integrations\/workflows(?:\/|$)/,async route=>{
  const path=new URL(route.request().url()).pathname,body=route.request().postDataJSON();calls.push({path,body})
  if(path.includes('/sample-recovery/batches/'))return route.fulfill({json:{schemaVersion:'2.0',closure:null}})
  if(path.endsWith('/workflows'))return route.fulfill({json:{schemaVersion:'2.0',storage:'postgres',operatorCatalog:WORKFLOW_OPERATORS,metricMappings:[cpu],drafts:{items:[],truncated:false},published:{items:[saved],truncated:false},models:[],modelsTruncated:false,zabbixSource:{instanceId:'fixture-host',mode:'fixture'},runs:{items:[],truncated:false}}})
  if(path.includes('/versions/'))return route.fulfill({json:saved})
  if(path.endsWith('/run'))return route.fulfill({json:{receipt:runReceipt,evaluation:{rows:[{index:0,status:'ACCEPTED',steps:definition.nodes.map((n:any)=>({nodeId:n.id,type:n.type,status:'OK',values:['VALIDATE','OUTPUT'].includes(n.type)?{timestamp:raw.timestamp,metricKey:cpu.metricKey,value:'0.125',unit:cpu.unit,metricType:'GAUGE',dimensions:cpu.fixedDimensions,mappingPin:cpu.mappingPin}:raw,issues:[]}))}],accepted:1,rejected:0,filtered:0,dryRun:true,writesPerformed:false},retainedCount:1,missingRaw:0,truncated:false,sourceStatus:'SUCCEEDED'}})
  if(path.endsWith('/metric-outputs')){
   if(!body)return route.fulfill({json:{schemaVersion:'2.0',mode:'FIXED_METRIC_SAMPLE',available:true,maxPoints:5}})
   posts++;original=result(body,['lost','missing','partial','late'].includes(mode)?'UNKNOWN':'CONFIRMED')
   if(mode==='lost'||mode==='late'||mode==='missing'&&posts===1)return route.abort('failed')
   if(mode==='bad-count')return route.fulfill({json:{...original,confirmed:0,unknown:1}})
   if(mode==='bad-hash')return route.fulfill({json:{...original,seriesHash:'0'.repeat(64)}})
   return route.fulfill({json:original})
  }
  if(path.endsWith('/receipts')){if(mode==='history-fail'&&calls.filter(c=>c.path.endsWith('/receipts')).length===1)return route.fulfill({status:503,json:{error:'SOURCE_UNAVAILABLE'}});return route.fulfill({json:{items:original?[original]:[],truncated:false}})}
  if(path.endsWith('/verification')){if(mode!=='partial')original={...original,state:'CONFIRMED',confirmed:1,unknown:0,error:null};return route.fulfill({json:original})}
  if(path.endsWith('/points'))return route.fulfill({json:{requestId:original.requestId,queriedAt:new Date().toISOString(),dataMode:'time-series',expectedPoints:1,proofMatches:mode!=='partial',points:mode==='partial'?[]:[{timestampMillis:timestamp,value:mode==='bad-point'?'0.15':'0.125'}]}})
  if(path.includes('/commands/')){if(delay)await delay;if(mode==='missing'&&posts===1)return route.fulfill({status:404,json:{error:'NOT_FOUND'}});return route.fulfill({json:original})}
  return route.fulfill({status:404,json:{error:'NOT_FOUND'}})
 })
 await page.goto('/#/integrations/workflows');await page.getByRole('textbox',{name:'平台开发 Token（仅保存在当前标签页内存）'}).fill(TOKEN_OK);await page.getByRole('button',{name:'查看',exact:true}).click();await closeWorkflowInspector(page);await page.getByText('指标输出与回读',{exact:true}).click();if(mode==='history-fail')await expect(page.getByRole('button',{name:'写入样本',exact:true})).toBeDisabled();else await expect(page.getByRole('button',{name:'写入样本',exact:true})).toBeEnabled();return calls
}
const section=(page:Page)=>page.getByRole('region',{name:'指标样本输出',exact:true})
for(const width of [1440,390])for(const theme of ['light','dark'])test(`fixed metric output Fixture ${width} ${theme}`,async({page})=>{
 await page.setViewportSize({width,height:940});await page.addInitScript(theme=>localStorage.setItem('opsweave.ui.theme',theme),theme);const calls=await fixture(page)
 await page.getByRole('button',{name:'写入样本',exact:true}).click();await expect(section(page)).toContainText('确认 1 · 失败 0 · 未知 0');await page.getByRole('button',{name:'回读指标点',exact:true}).click();await expect(section(page)).toContainText('完整批次匹配');await expect(section(page).getByRole('cell',{name:'0.125',exact:true})).toBeVisible();await expect(section(page).getByRole('link',{name:cpu.metricKey,exact:true})).toHaveAttribute('href','#/modeling/metrics?metricKey='+cpu.metricKey);await expect(section(page)).toContainText(cpu.sourceKey)
 const command=calls.find(c=>c.path.endsWith('/metric-outputs')&&c.body)!.body;expect(Object.keys(command).sort()).toEqual(['digest','id','previewId','requestId','revision','samples']);expect(command.samples[0].value).toBe('12.5');expect(command.samples[0].sourceKey).toBe(cpu.sourceKey);expect(calls.filter(c=>c.path.endsWith('/run'))).toHaveLength(1);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)
 if(process.env.OPSWEAVE_SOURCE_SCREENSHOTS){mkdirSync(process.env.OPSWEAVE_SOURCE_SCREENSHOTS,{recursive:true});await page.screenshot({path:process.env.OPSWEAVE_SOURCE_SCREENSHOTS+`/output-${width}-${theme}.png`,fullPage:true})}
})
test('lost response keeps the original key and verification does not repeat POST',async({page})=>{const calls=await fixture(page,'lost');await page.getByRole('button',{name:'写入样本',exact:true}).click();await expect(section(page).getByRole('alert')).toBeVisible();await expect(page.getByRole('button',{name:'创建下一版',exact:true})).toBeDisabled();expect(calls.filter(c=>c.path.includes('/commands/'))).toHaveLength(0);await page.getByRole('button',{name:'查询原回执',exact:true}).click();await expect(section(page)).toContainText('未知 1');await page.getByRole('button',{name:'验证批次',exact:true}).click();await expect(section(page)).toContainText('确认 1');expect(calls.filter(c=>c.path.endsWith('/metric-outputs')&&c.body)).toHaveLength(1);await expect(page.getByRole('button',{name:'创建下一版',exact:true})).toBeEnabled()})
test('explicit absence permits only original body resend without a new source read',async({page})=>{const calls=await fixture(page,'missing');await page.getByRole('button',{name:'写入样本',exact:true}).click();await expect(section(page).getByRole('alert')).toBeVisible();await page.getByRole('button',{name:'查询原回执',exact:true}).click();await expect(page.getByRole('button',{name:'重发原请求',exact:true})).toBeVisible();await page.getByRole('button',{name:'重发原请求',exact:true}).click();await expect(section(page)).toContainText('未知 1');const posts=calls.filter(c=>c.path.endsWith('/metric-outputs')&&c.body);expect(posts).toHaveLength(2);expect(posts[0].body).toEqual(posts[1].body);expect(calls.filter(c=>c.path.endsWith('/run'))).toHaveLength(1)})
test('recent unknown receipt is recovered without resending unavailable original values',async({page})=>{const calls=await fixture(page,'history');await section(page).getByText(/最近写入记录/).click();await section(page).getByRole('button',{name:/结果待确认/}).click();await expect(page.getByRole('button',{name:'写入样本',exact:true})).toBeDisabled();await page.getByRole('button',{name:'验证批次',exact:true}).click();await expect(section(page)).toContainText('确认 1');expect(calls.filter(c=>c.body)).toHaveLength(0);expect(calls.filter(c=>c.path.endsWith('/receipts'))).toHaveLength(1)})
test('partial query retains unknown and is never shown as a complete empty batch',async({page})=>{const calls=await fixture(page,'partial');await page.getByRole('button',{name:'写入样本',exact:true}).click();await expect(section(page)).toContainText('未知 1');await page.getByRole('button',{name:'回读指标点',exact:true}).click();await expect(section(page)).toContainText('本次回读 0/1 点 · 批次尚未完整匹配');await page.getByRole('button',{name:'验证批次',exact:true}).click();await expect(section(page)).toContainText('未知 1');expect(calls.filter(c=>c.path.endsWith('/metric-outputs')&&c.body)).toHaveLength(1)})
for(const mode of ['bad-count','bad-hash'])test('invalid output evidence retains original confirmation: '+mode,async({page})=>{const calls=await fixture(page,mode);await page.getByRole('button',{name:'写入样本',exact:true}).click();await expect(section(page).getByRole('alert')).toContainText('不符合契约');await expect(page.getByRole('button',{name:'写入样本',exact:true})).toBeDisabled();expect(calls.filter(c=>c.path.endsWith('/metric-outputs')&&c.body)).toHaveLength(1)})
test('a claimed matching point with changed value is rejected by the persisted batch proof',async({page})=>{const calls=await fixture(page,'bad-point');await page.getByRole('button',{name:'写入样本',exact:true}).click();await expect(section(page)).toContainText('确认 1');await page.getByRole('button',{name:'回读指标点',exact:true}).click();await expect(section(page).getByRole('alert')).toContainText('不符合契约');await expect(section(page).getByRole('cell',{name:'0.15',exact:true})).toHaveCount(0);expect(calls.filter(c=>c.path.endsWith('/metric-outputs')&&c.body)).toHaveLength(1)})
test('failed receipt list blocks a new write until explicit refresh and never retries itself',async({page})=>{const calls=await fixture(page,'history-fail');await expect(section(page).getByRole('alert')).toBeVisible();expect(calls.filter(c=>c.path.endsWith('/receipts'))).toHaveLength(1);expect(calls.filter(c=>c.body)).toHaveLength(0);await page.getByRole('button',{name:'刷新记录',exact:true}).click();await expect(page.getByRole('button',{name:'写入样本',exact:true})).toBeEnabled();expect(calls.filter(c=>c.path.endsWith('/receipts'))).toHaveLength(2);expect(calls.filter(c=>c.body)).toHaveLength(0)})
test('identity clearing discards a late original receipt and all private values',async({page})=>{let release!:()=>void;const delay=new Promise<void>(r=>{release=r}),calls=await fixture(page,'late',delay);await page.getByRole('button',{name:'写入样本',exact:true}).click();await expect(section(page).getByRole('alert')).toBeVisible();await page.getByRole('button',{name:'查询原回执',exact:true}).click();await expect.poll(()=>calls.filter(c=>c.path.includes('/commands/')).length).toBe(1);await page.getByRole('button',{name:'清除开发会话',exact:true}).click();release();await expect(section(page)).toHaveCount(0);expect(calls.filter(c=>c.path.endsWith('/metric-outputs')&&c.body)).toHaveLength(1)})

for(const width of [1440,1024,390])for(const theme of ['light','dark'])test(`sample closure preserves UNKNOWN ${width} ${theme}`,async({page})=>{
 await page.setViewportSize({width,height:1000});await page.addInitScript(t=>localStorage.setItem('opsweave.ui.theme',t),theme);const original=await fixture(page,'partial'),calls=await sampleRecoveryFixture(page);await page.getByRole('button',{name:'写入样本',exact:true}).click();await expect(closurePanel(page).getByRole('checkbox')).toBeVisible();if(process.env.OPSWEAVE_SOURCE_SCREENSHOTS)await closurePanel(page).screenshot({path:process.env.OPSWEAVE_SOURCE_SCREENSHOTS+`/metric-closure-decision-${width}-${theme}.png`});expect(calls.filter(c=>c.path.includes('/batches/'))).toHaveLength(1);expect(calls.filter(c=>c.body)).toHaveLength(0);await acknowledgeSample(page);await expect(closurePanel(page)).toContainText('此批次已终止确认');await expect(section(page)).toContainText('未知 1');await expect(page.getByRole('button',{name:'写入样本',exact:true})).toBeEnabled();await expect(page.getByRole('button',{name:'验证批次',exact:true})).toHaveCount(0);await expect(page.getByRole('button',{name:'创建下一版',exact:true})).toBeEnabled();expect(original.filter(c=>c.body)).toHaveLength(2);expect(original.filter(c=>c.path.endsWith('/verification'))).toHaveLength(0);expect(calls.filter(c=>c.body)).toHaveLength(1);expect(Object.keys(calls.find(c=>c.body)!.body).sort()).toEqual(['acknowledgeUncertainOutput','batchDigest','batchId','digest','expectedUpdatedAt','id','kind','requestId','revision']);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)
 await page.getByText('指标输出与回读',{exact:true}).click();await page.getByText('指标输出与回读',{exact:true}).click();await expect(closurePanel(page)).toContainText('此批次已终止确认');await expect(page.getByRole('button',{name:'写入样本',exact:true})).toBeEnabled();expect(calls.filter(c=>c.path.includes('/batches/'))).toHaveLength(2)
 if(process.env.OPSWEAVE_SOURCE_SCREENSHOTS)await closurePanel(page).locator('..').screenshot({path:process.env.OPSWEAVE_SOURCE_SCREENSHOTS+`/metric-closure-${width}-${theme}.png`})
})
for(const mode of ['lost','missing','bad-proof'])test('sample closure retains original UUID: '+mode,async({page})=>{
 const original=await fixture(page,'partial'),calls=await sampleRecoveryFixture(page,mode);await page.getByRole('button',{name:'写入样本',exact:true}).click();await acknowledgeSample(page);await expect(closurePanel(page).getByRole('alert')).toBeVisible();await expect(page.getByRole('button',{name:'创建下一版',exact:true})).toBeDisabled();await expect(page.getByRole('button',{name:'验证批次',exact:true})).toBeDisabled();await page.getByText('指标输出与回读',{exact:true}).click();await expect(closurePanel(page)).toBeVisible();expect(calls.filter(c=>c.path.includes('/commands/'))).toHaveLength(0);await closurePanel(page).getByRole('button',{name:'查询原终止回执',exact:true}).click();if(mode==='missing'){await closurePanel(page).getByRole('button',{name:'重发原终止请求',exact:true}).click();const writes=calls.filter(c=>c.body);expect(writes).toHaveLength(2);expect(writes[0].body).toEqual(writes[1].body)}await expect(closurePanel(page)).toContainText('此批次已终止确认');await expect(section(page)).toContainText('未知 1');expect(original.filter(c=>c.path.endsWith('/verification'))).toHaveLength(0);expect(original.filter(c=>c.path.endsWith('/metric-outputs')&&c.body)).toHaveLength(1)
})
test('sample closure metadata failure requires explicit retry',async({page})=>{await fixture(page,'partial');const calls=await sampleRecoveryFixture(page,'status-fail');await page.getByRole('button',{name:'写入样本',exact:true}).click();await expect(closurePanel(page).getByRole('alert')).toBeVisible();await expect(closurePanel(page).getByRole('checkbox')).toHaveCount(0);expect(calls.filter(c=>c.path.includes('/batches/'))).toHaveLength(1);await closurePanel(page).getByRole('button',{name:'读取终止状态',exact:true}).click();await expect(closurePanel(page).getByRole('checkbox')).toBeVisible();expect(calls.filter(c=>c.body)).toHaveLength(0)})
test('cleared session discards late sample closure and does not resend',async({page})=>{let release!:()=>void;const delay=new Promise<void>(r=>{release=r});await fixture(page,'partial');const calls=await sampleRecoveryFixture(page,'lost',delay);await page.getByRole('button',{name:'写入样本',exact:true}).click();await acknowledgeSample(page);await expect(closurePanel(page).getByRole('alert')).toBeVisible();await closurePanel(page).getByRole('button',{name:'查询原终止回执',exact:true}).click();await expect.poll(()=>calls.filter(c=>c.path.includes('/commands/')).length).toBe(1);await page.getByRole('button',{name:'清除开发会话',exact:true}).click();release();await expect(closurePanel(page)).toHaveCount(0);expect(calls.filter(c=>c.body)).toHaveLength(1)})
