import { test,expect } from '@playwright/test'
import { mkdirSync } from 'node:fs'
import { fixture } from './host-workflow-fixture.ts'

for(const width of [1440,390])for(const theme of ['light','dark'])test(`periodic host fixture ${width} ${theme}`,async({page})=>{
 await page.setViewportSize({width,height:1000});await page.addInitScript(theme=>localStorage.setItem('opsweave.ui.theme',theme),theme);const calls=await fixture(page,'normal',undefined,'idle');await page.getByText('周期主机采集',{exact:true}).click();const panel=page.getByRole('region',{name:'周期主机采集'});await expect(panel).toContainText('已完成 1 轮 / 已确认 3 条');await expect(panel.getByRole('button',{name:'停止周期采集',exact:true})).toBeEnabled();await expect(panel.getByRole('combobox',{name:'主机采集间隔'})).toBeDisabled();expect(calls.filter(c=>c.path.includes('/host-schedules/')&&c.body)).toHaveLength(0);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)
 if(process.env.OPSWEAVE_SOURCE_SCREENSHOTS){mkdirSync(process.env.OPSWEAVE_SOURCE_SCREENSHOTS,{recursive:true});await panel.screenshot({path:process.env.OPSWEAVE_SOURCE_SCREENSHOTS+`/schedule-${width}-${theme}.png`})}
})
test('opening reads once and explicit periodic controls keep original settings and generation',async({page})=>{
 const calls=await fixture(page);await page.getByText('周期主机采集',{exact:true}).click();const panel=page.getByRole('region',{name:'周期主机采集'});await expect(panel.getByRole('button',{name:'启动周期采集',exact:true})).toBeDisabled();await panel.getByRole('combobox',{name:'周期采集名称字段'}).selectOption('hostname');await panel.getByRole('combobox',{name:'主机采集间隔'}).selectOption('300');await panel.getByRole('button',{name:'启动周期采集',exact:true}).click();await expect(panel.getByRole('button',{name:'停止周期采集',exact:true})).toBeEnabled();await panel.getByRole('button',{name:'停止周期采集',exact:true}).click();await expect(panel).toContainText('已停止');const commands=calls.filter(c=>c.path.includes('/host-schedules/')&&c.body);expect(commands.map(c=>c.body.expectedGeneration)).toEqual([0,1]);expect(commands.every(c=>c.body.intervalSeconds===300&&c.body.settings.identityField==='entity_id')).toBe(true)
})
test('lost control response locks the original body and only explicit GET confirms it',async({page})=>{
 const calls=await fixture(page,'normal',undefined,'lost');await page.getByText('周期主机采集',{exact:true}).click();const panel=page.getByRole('region',{name:'周期主机采集'});await panel.getByRole('combobox',{name:'周期采集名称字段'}).selectOption('hostname');await panel.getByRole('button',{name:'启动周期采集',exact:true}).click();await expect(panel.getByLabel('周期控制结果待确认')).toBeVisible();await expect(page.getByRole('button',{name:'创建下一版',exact:true})).toBeDisabled();await panel.getByRole('button',{name:'查询原周期回执',exact:true}).click();await expect(panel).toContainText('原控制已确认：启动');expect(calls.filter(c=>c.path.includes('/host-schedules/start'))).toHaveLength(1);expect(calls.filter(c=>c.path.includes('/host-schedules/commands/'))).toHaveLength(1)
})
for(const mode of ['corrupt','unavailable'])test('periodic '+mode+' halts automatic reads and writes',async({page})=>{
 const calls=await fixture(page,'normal',undefined,mode);await page.getByText('周期主机采集',{exact:true}).click();const panel=page.getByRole('region',{name:'周期主机采集'});await expect(panel.getByRole('alert')).toBeVisible();await page.waitForTimeout(5500);expect(calls.filter(c=>c.path.includes('/host-schedules/workflows/'))).toHaveLength(1);expect(calls.filter(c=>c.path.includes('/host-schedules/')&&c.body)).toHaveLength(0)
})
test('identity clearing discards pending command and rejects late acknowledgement',async({page})=>{
 let release!:()=>void;const held=new Promise<void>(r=>release=r),calls=await fixture(page,'normal',held,'lost');await page.getByText('周期主机采集',{exact:true}).click();const panel=page.getByRole('region',{name:'周期主机采集'});await panel.getByRole('combobox',{name:'周期采集名称字段'}).selectOption('hostname');await panel.getByRole('button',{name:'启动周期采集',exact:true}).click();await panel.getByRole('button',{name:'查询原周期回执',exact:true}).click();await expect.poll(()=>calls.some(c=>c.path.includes('/host-schedules/commands/'))).toBe(true);await page.getByRole('button',{name:'清除开发会话',exact:true}).click();release();await expect(panel).toHaveCount(0);expect(await page.evaluate(()=>JSON.stringify({...localStorage,...sessionStorage}))).not.toContain('activeScanId')
})
test('404 only permits explicit resend of the identical original periodic command',async({page})=>{
 const calls=await fixture(page,'normal',undefined,'missing');await page.getByText('周期主机采集',{exact:true}).click();const panel=page.getByRole('region',{name:'周期主机采集'});await panel.getByRole('combobox',{name:'周期采集名称字段'}).selectOption('hostname');await panel.getByRole('button',{name:'启动周期采集',exact:true}).click();await expect(panel.getByRole('button',{name:'按原请求重新提交',exact:true})).toHaveCount(0);await panel.getByRole('button',{name:'查询原周期回执',exact:true}).click();await panel.getByRole('button',{name:'按原请求重新提交',exact:true}).click();await expect.poll(()=>calls.filter(c=>c.path.endsWith('/host-schedules/start')).length).toBe(2);const posts=calls.filter(c=>c.path.endsWith('/host-schedules/start'));expect(posts[0].body).toEqual(posts[1].body)
})
