import { test,expect,type Page } from '@playwright/test'
import { readFileSync,mkdirSync } from 'node:fs'
import { createHash } from 'node:crypto'
import { WORKFLOW_OPERATORS,TOKEN_OK,closeWorkflowInspector } from './helpers.ts'
// Explicit HTTP Fixtures; actual PG/log-store evidence is checked separately.
const definition=JSON.parse(readFileSync(new URL('../../../contracts/examples/v2/workflow-real-log-definition.json',import.meta.url),'utf8')),digest='sha256:'+'a'.repeat(64)
for(const n of definition.nodes)n.operatorDigest=WORKFLOW_OPERATORS.operators.find((o:any)=>o.type===n.type)!.digest
const hash=(parts:string[])=>'sha256:'+createHash('sha256').update(parts.map(p=>Buffer.byteLength(p)+':'+p).join('')).digest('hex')
async function fixture(page:Page,mode='normal',delay?:Promise<void>){
 const calls:{path:string;body:any}[]=[],time=new Date(Date.now()-1000).toISOString(),raw={eventTime:time,body:'  <script>fixtureInjection=true</script>\nFixture line  ',severityText:'INFO',...(mode==='numeric'?{fixtureNumber:1e-7}:{})}
 const saved={definition,layout:Object.fromEntries(definition.nodes.map((n:any,i:number)=>[n.id,{x:180,y:40+i*160}])),digest,state:'PUBLISHED',editVersion:0,updatedAt:new Date().toISOString(),preview:null}
 const runReceipt={id:'10000000-0000-4000-8000-000000000120',digest,inputDigest:digest,origin:'MANUAL_SAMPLE',accepted:1,rejected:0,filtered:0,createdAt:new Date().toISOString()};let original:any=null,posts=0
 function result(command:any,state='CONFIRMED'){return {requestId:command.requestId,workflowId:definition.id,revision:1,digest,previewId:runReceipt.id,commandDigest:hash(['workflow-log-source-command-v1',definition.id,'1',digest]),createdAt:new Date().toISOString(),updatedAt:new Date().toISOString(),state,accepted:1,filtered:0,confirmed:state==='CONFIRMED'?1:0,failed:0,unknown:state==='CONFIRMED'?0:1,error:state==='UNKNOWN'?'OUTPUT_UNCONFIRMED':null,batchDigest:digest,indices:[0]}}
 if(mode==='history')original=result({requestId:'10000000-0000-4000-8000-000000000121',previewId:runReceipt.id,samples:[raw]},'UNKNOWN')
 await page.route(/\/api\/v1\/integrations\/workflows(?:\/|$)/,async route=>{
  const path=new URL(route.request().url()).pathname,body=route.request().postDataJSON();calls.push({path,body})
  if(path.includes('/sample-recovery/batches/'))return route.fulfill({json:{schemaVersion:'2.0',closure:null}})
  if(path.endsWith('/workflows'))return route.fulfill({json:{schemaVersion:'2.0',storage:'postgres',operatorCatalog:WORKFLOW_OPERATORS,metricMappings:[],drafts:{items:[],truncated:false},published:{items:[saved],truncated:false},models:[],modelsTruncated:false,zabbixSource:{instanceId:'fixture-host',mode:'fixture'},runs:{items:[],truncated:false}}})
  if(path.includes('/versions/'))return route.fulfill({json:saved})
  if(path.endsWith('/run'))return route.fulfill({json:{receipt:runReceipt,evaluation:{rows:[{index:0,status:'ACCEPTED',steps:definition.nodes.map((n:any)=>({nodeId:n.id,type:n.type,status:'OK',values:n.type==='SOURCE'?body.samples[0]:Object.fromEntries(Object.entries(body.samples[0]).filter(([key])=>key!=='fixtureNumber')),issues:[]}))}],accepted:1,rejected:0,filtered:0,dryRun:true,writesPerformed:false},retainedCount:1,missingRaw:0,truncated:false,sourceStatus:'MANUAL_SAMPLE'}})
  if(path.endsWith('/capability'))return route.fulfill({json:{schemaVersion:'2.0',mode:'SOURCE_LOG_SAMPLE',available:mode!=='unavailable',maxRecords:5,readAllowed:mode!=='no-read',writeAllowed:mode!=='no-write'}})
  if(path.endsWith('/receipts')){if(mode==='history-fail'&&calls.filter(c=>c.path.endsWith('/receipts')).length===1)return route.fulfill({status:503,json:{error:'SOURCE_UNAVAILABLE'}});return route.fulfill({json:{items:original?[original]:[],truncated:false}})}
  if(path.endsWith('/log-outputs/source')){posts++;original=result(body,['lost','missing','partial','late'].includes(mode)?'UNKNOWN':'CONFIRMED');if(mode==='lost'||mode==='late'||mode==='missing'&&posts===1)return route.abort('failed');if(mode==='bad-count')return route.fulfill({json:{...original,confirmed:0,unknown:1}});if(mode==='bad-command')return route.fulfill({json:{...original,commandDigest:digest}});return route.fulfill({json:original})}
  if(path.endsWith('/verification')){if(mode!=='partial')original={...original,state:'CONFIRMED',confirmed:1,unknown:0,error:null};return route.fulfill({json:original})}
  if(path.endsWith('/records'))return route.fulfill({json:{requestId:original.requestId,readAt:new Date().toISOString(),storage:'clickhouse',expectedRecords:1,complete:mode!=='partial',records:mode==='partial'?[]:[{index:mode==='bad-row'?1:0,eventTime:time,body:raw.body,severityText:raw.severityText,serviceName:null,traceId:null,spanId:null}]}})
  if(path.includes('/commands/')){if(delay)await delay;if(mode==='missing'&&posts===1)return route.fulfill({status:404,json:{error:'NOT_FOUND'}});return route.fulfill({json:original})}
  return route.fulfill({status:404,json:{error:'NOT_FOUND'}})
 })
 await page.goto('/#/integrations/workflows');await page.getByRole('textbox',{name:'平台开发 Token（仅保存在当前标签页内存）'}).fill(TOKEN_OK);await page.getByRole('button',{name:'查看',exact:true}).click();await closeWorkflowInspector(page);await expect(page.getByRole('textbox',{name:'工作流手工样本'})).toHaveCount(0);await page.getByText('日志写入与回读',{exact:true}).click();if(['history-fail','unavailable','no-write'].includes(mode))await expect(page.getByRole('button',{name:'写入日志样本',exact:true})).toBeDisabled();else await expect(page.getByRole('button',{name:'写入日志样本',exact:true})).toBeEnabled();return calls
}
const section=(page:Page)=>page.getByRole('region',{name:'日志批次输出',exact:true})
for(const width of [1440,390])for(const theme of ['light','dark'])test(`log output Fixture ${width} ${theme}`,async({page})=>{
 await page.setViewportSize({width,height:1000});await page.addInitScript(t=>localStorage.setItem('opsweave.ui.theme',t),theme);const calls=await fixture(page);expect(calls.filter(c=>c.path.endsWith('/log-outputs/source')&&c.body)).toHaveLength(0);await page.getByRole('button',{name:'写入日志样本',exact:true}).click();await expect(section(page)).toContainText('确认 1 · 失败 0 · 未知 0');await page.getByRole('button',{name:'回读日志记录',exact:true}).click();await expect(section(page)).toContainText('完整批次匹配');await expect(section(page).locator('pre')).toHaveText('  <script>fixtureInjection=true</script>\nFixture line  ');expect(await page.evaluate(()=>Object.hasOwn(window,'fixtureInjection'))).toBe(false);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);expect(calls.filter(c=>c.path.endsWith('/run'))).toHaveLength(0);expect(calls.filter(c=>c.path.endsWith('/log-outputs/source')&&c.body)).toHaveLength(1)
 if(process.env.OPSWEAVE_SOURCE_SCREENSHOTS){mkdirSync(process.env.OPSWEAVE_SOURCE_SCREENSHOTS,{recursive:true});await section(page).screenshot({path:process.env.OPSWEAVE_SOURCE_SCREENSHOTS+`/external-log-${width}-${theme}.png`})}
})
test('unknown original confirmation never repeats a write',async({page})=>{const calls=await fixture(page,'lost');await page.getByRole('button',{name:'写入日志样本',exact:true}).click();await expect(section(page).getByRole('alert')).toBeVisible();await expect(page.getByRole('button',{name:'创建下一版',exact:true})).toBeDisabled();await page.getByRole('button',{name:'查询原回执',exact:true}).click();await expect(section(page)).toContainText('未知 1');await page.getByRole('button',{name:'验证日志批次',exact:true}).click();await expect(section(page)).toContainText('确认 1');expect(calls.filter(c=>c.path.endsWith('/log-outputs/source')&&c.body)).toHaveLength(1)})
test('confirmed absence permits only same original request resend',async({page})=>{const calls=await fixture(page,'missing');await page.getByRole('button',{name:'写入日志样本',exact:true}).click();await expect(section(page).getByRole('alert')).toBeVisible();await page.getByRole('button',{name:'查询原回执',exact:true}).click();await page.getByRole('button',{name:'重发原请求',exact:true}).click();await expect(section(page)).toContainText('未知 1');const writes=calls.filter(c=>c.path.endsWith('/log-outputs/source')&&c.body);expect(writes).toHaveLength(2);expect(writes[0].body).toEqual(writes[1].body);expect(calls.filter(c=>c.path.endsWith('/run'))).toHaveLength(0)})
test('partial read is explicit incomplete data and verification does not write',async({page})=>{const calls=await fixture(page,'partial');await page.getByRole('button',{name:'写入日志样本',exact:true}).click();await expect(section(page)).toContainText('未知 1');await page.getByRole('button',{name:'回读日志记录',exact:true}).click();await expect(section(page)).toContainText('本次回读 0/1 条 · 批次尚未完整匹配');await page.getByRole('button',{name:'验证日志批次',exact:true}).click();await expect(section(page)).toContainText('未知 1');expect(calls.filter(c=>c.path.endsWith('/log-outputs/source')&&c.body)).toHaveLength(1)})
for(const mode of ['bad-count','bad-command'])test('invalid receipt retains original request: '+mode,async({page})=>{const calls=await fixture(page,mode);await page.getByRole('button',{name:'写入日志样本',exact:true}).click();await expect(section(page).getByRole('alert')).toContainText('不符合契约');await expect(page.getByRole('button',{name:'写入日志样本',exact:true})).toBeDisabled();expect(calls.filter(c=>c.path.endsWith('/log-outputs/source')&&c.body)).toHaveLength(1)})
test('foreign row index cannot become original batch',async({page})=>{await fixture(page,'bad-row');await page.getByRole('button',{name:'写入日志样本',exact:true}).click();await expect(section(page)).toContainText('确认 1');await page.getByRole('button',{name:'回读日志记录',exact:true}).click();await expect(section(page).getByRole('alert')).toContainText('不符合契约');await expect(section(page).locator('pre')).toHaveCount(0)})
for(const mode of ['unavailable','no-write'])test('unavailable or denied log write has no POST: '+mode,async({page})=>{const calls=await fixture(page,mode);expect(calls.filter(c=>c.body)).toHaveLength(0)})
test('log read permission independently controls raw text',async({page})=>{await fixture(page,'no-read');await page.getByRole('button',{name:'写入日志样本',exact:true}).click();await expect(section(page)).toContainText('确认 1');await expect(page.getByRole('button',{name:'回读日志记录',exact:true})).toBeDisabled();await expect(section(page).locator('pre')).toHaveCount(0)})
test('history failure requires explicit retry and never retries automatically',async({page})=>{const calls=await fixture(page,'history-fail');await expect(section(page).getByRole('alert')).toBeVisible();expect(calls.filter(c=>c.path.endsWith('/receipts'))).toHaveLength(1);await page.getByRole('button',{name:'刷新记录',exact:true}).click();await expect(page.getByRole('button',{name:'写入日志样本',exact:true})).toBeEnabled();expect(calls.filter(c=>c.body)).toHaveLength(0)})
test('an existing unknown proof can be verified without original text or POST',async({page})=>{const calls=await fixture(page,'history');await section(page).getByText(/最近写入记录/).click();await section(page).getByRole('button',{name:/结果待确认/}).click();await page.getByRole('button',{name:'验证日志批次',exact:true}).click();await expect(section(page)).toContainText('确认 1');expect(calls.filter(c=>c.body)).toHaveLength(0)})
test('identity clearing rejects a late response and clears log text',async({page})=>{let release!:()=>void;const delay=new Promise<void>(r=>{release=r}),calls=await fixture(page,'late',delay);await page.getByRole('button',{name:'写入日志样本',exact:true}).click();await expect(section(page).getByRole('alert')).toBeVisible();await page.getByRole('button',{name:'查询原回执',exact:true}).click();await expect.poll(()=>calls.filter(c=>c.path.includes('/commands/')).length).toBe(1);await page.getByRole('button',{name:'清除开发会话',exact:true}).click();release();await expect(section(page)).toHaveCount(0);expect(calls.filter(c=>c.path.endsWith('/log-outputs/source')&&c.body)).toHaveLength(1)})


test('source sample request contains only the fixed workflow and original UUID',async({page})=>{const calls=await fixture(page);await page.getByRole('button',{name:'写入日志样本',exact:true}).click();await expect(section(page)).toContainText('确认 1');const command=calls.find(c=>c.path.endsWith('/log-outputs/source'))!.body;expect(Object.keys(command).sort()).toEqual(['requestId','id','revision','digest'].sort());expect(calls.filter(c=>c.path.endsWith('/run'))).toHaveLength(0)})
