import {test,expect,type Page} from '@playwright/test'
import {readFileSync,mkdirSync} from 'node:fs'
import {createHash} from 'node:crypto'
import {WORKFLOW_OPERATORS,TOKEN_OK,closeWorkflowInspector} from './helpers.ts'

// Explicit protocol Fixtures. Actual provider, PG and storage are checked separately.
const definition=JSON.parse(readFileSync(new URL('../../../contracts/examples/v2/workflow-real-log-definition.json',import.meta.url),'utf8')),digest='sha256:'+'a'.repeat(64),batchId='10000000-0000-4000-8000-000000000124'
for(const n of definition.nodes)n.operatorDigest=WORKFLOW_OPERATORS.operators.find((o:any)=>o.type===n.type)!.digest
const iso=(ms:number)=>new Date(ms).toISOString().replace('.000Z','Z'),region=(p:Page)=>p.getByRole('region',{name:'持续日志采集',exact:true})
const hash=(parts:string[])=>'sha256:'+createHash('sha256').update(parts.map(p=>Buffer.byteLength(p)+':'+p).join('')).digest('hex')
async function fixture(page:Page,mode='normal',delay?:Promise<void>){
 const calls:{path:string;body:any}[]=[],created=Math.floor(Date.now()/1000)*1000,from=created-80000
 const chosen=mode==='new-version'?{...definition,revision:2}:definition
 const saved={definition:chosen,layout:Object.fromEntries(definition.nodes.map((n:any,i:number)=>[n.id,{x:180,y:40+i*160}])),digest,state:'PUBLISHED',editVersion:0,updatedAt:iso(created),preview:null}
 const positions=Array.from({length:1000},(_,i)=>iso(from).replace(/Z$/,i?'.'+String(i).padStart(9,'0')+'Z':'Z'))
 const task=(state='RUNNING',generation=1,confirmedWindows=1)=>({workflowId:definition.id,revision:chosen.revision,digest,generation,state,cursor:iso(from+confirmedWindows*60000),pendingBatchId:null,confirmedWindows,confirmedRecords:confirmedWindows*1000,sessionBatches:1,updatedAt:iso(created),error:state==='FAILED'?'OUTPUT_UNCONFIRMED':null})
 const batch=(state='CONFIRMED')=>({id:batchId,workflowId:definition.id,revision:chosen.revision,digest,from:iso(from),till:iso(from+60000),createdAt:iso(created),updatedAt:iso(created),state,inputCount:1000,filtered:0,deduplicated:0,indices:Array.from({length:1000},(_,i)=>i),positions,inputDigest:digest,batchDigest:digest,error:state==='UNKNOWN'?'OUTPUT_UNCONFIRMED':null,reconcilesBatchId:null})
 let current:any=null,batches:any[]=[],original:any=null,reads=0,posts=0
 if(['dense','bad-ns','bad-count','foreign','partial'].includes(mode)){current=task('STOPPED');batches=[batch()]}
 if(mode==='unknown'){current={...task('FAILED',1,0),pendingBatchId:batchId};batches=[batch('UNKNOWN')]}
 if(mode==='known-rejection-limit'){current={...task('FAILED',999999,0),error:'OUTPUT_REJECTED',pendingBatchId:batchId};batches=[{...batch('UNKNOWN'),state:'FAILED',error:'OUTPUT_REJECTED'}]}
 if(['legacy-rejection','bad-uncertainty','duplicate-uncertainty','foreign-uncertainty'].includes(mode)){current={...task('FAILED',1,0),error:'OUTPUT_REJECTED',pendingBatchId:batchId};batches=[{...batch('UNKNOWN'),state:'FAILED',error:'OUTPUT_REJECTED'}]}
 await page.route(/\/api\/v1\/integrations\/workflows(?:\/|$)/,async route=>{
  const path=new URL(route.request().url()).pathname,body=route.request().postDataJSON();calls.push({path,body})
  if(path.endsWith('/workflows'))return route.fulfill({json:{schemaVersion:'2.0',storage:'postgres',operatorCatalog:WORKFLOW_OPERATORS,metricMappings:[],drafts:{items:[],truncated:false},published:{items:[saved],truncated:false},models:[],modelsTruncated:false,zabbixSource:{instanceId:'fixture-source',mode:'fixture'},runs:{items:[],truncated:false}}})
  if(path.includes('/versions/'))return route.fulfill({json:saved})
  const status=()=>({schemaVersion:'2.0',available:true,mode:'LOCAL_DEV_LOG',windowSeconds:60,settleSeconds:10,maxBatchRecords:1000,maxSessionBatches:20,maxHistoryRequests:20,lookbackSeconds:60,task:current,batches,...(['legacy-rejection','bad-uncertainty','duplicate-uncertainty','foreign-uncertainty'].includes(mode)?{resumeAllowed:false,uncertainBatchIds:mode==='bad-uncertainty'?'private':mode==='duplicate-uncertainty'?[batchId,batchId]:mode==='foreign-uncertainty'?['10000000-0000-4000-8000-000000000130']:[batchId]}:mode==='known-rejection-limit'?{resumeAllowed:false,uncertainBatchIds:[]}:mode==='bad-resume'?{resumeAllowed:true}:{}),...(['new-version','closed-version','bad-control'].includes(mode)?{control:{generation:current?.generation??2,startAllowed:!current&&mode!=='closed-version',recoveryClosed:mode==='closed-version',...(mode==='bad-control'?{tenantId:'forged'}:{})}}:{})})
  if(path.includes('/records')){const after=path.includes('/after/')?Number(path.split('/').at(-1)):-1;const indices=Array.from({length:Math.min(50,999-after)},(_,i)=>after+1+i);const records=indices.map(index=>({index,position:positions[index],eventTime:positions[index],body:'  Synthetic Fixture '+index+' 🧵\n<script>fixtureInjection=true</script>  ',severityText:null,serviceName:null,traceId:null,spanId:null}));if(mode==='foreign')records[0].position=positions[1];return route.fulfill({json:{batchId,readAt:iso(created),storage:'clickhouse',expectedRecords:1000,complete:mode!=='partial',afterIndex:after,nextIndex:mode!=='partial'&&after+50<999?after+50:null,records:mode==='partial'?[]:records}})}
  if(path.endsWith('/verification')){current=task('STOPPED');batches=[batch()];return route.fulfill({json:status()})}
  if(path.includes('/log-streams/workflows/')){reads++;if(mode==='fail')return route.fulfill({status:503,json:{error:'SOURCE_UNAVAILABLE'}});const value=status();expect(new URL(route.request().url()).searchParams.get('revision')).toBe(String(chosen.revision));if(mode==='bad-ns')value.batches=[{...batch(),positions:[positions[1],positions[0],...positions.slice(2)]}];if(mode==='bad-count')value.batches=[{...batch(),deduplicated:1}];return route.fulfill({json:mode==='corrupt'?{...value,authority:{}}:value})}
  if(path.includes('/commands/')){if(delay)await delay;return route.fulfill({json:original})}
  if(path.includes('/log-streams/')&&body){posts++;const operation=path.split('/').at(-1)!.toUpperCase();current=task(operation==='STOP'?'STOPPED':'RUNNING',body.expectedGeneration+1);batches=[batch()];original={requestId:body.requestId,operation,commandDigest:hash(['log-stream-control-v1',operation,definition.id,String(chosen.revision),digest,String(body.expectedGeneration)]),acceptedAt:current.updatedAt,task:current};if(mode==='bad-receipt')original.commandDigest=digest;if(mode==='lost'&&posts===1)return route.abort('failed');return route.fulfill({json:original})}
  return route.fulfill({status:404,json:{error:'NOT_FOUND'}})
 })
 await page.goto('/#/integrations/workflows');await page.getByRole('textbox',{name:'平台开发 Token（仅保存在当前标签页内存）'}).fill(TOKEN_OK);await page.getByRole('button',{name:'查看',exact:true}).click();await closeWorkflowInspector(page);await page.getByText('持续日志采集',{exact:true}).click();await expect(region(page)).toBeVisible();return {calls,reads:()=>reads,posts:()=>posts}
}
for(const width of [1440,390])for(const theme of ['light','dark'])test(`log stream Fixture ${width} ${theme}`,async({page})=>{
 await page.setViewportSize({width,height:940});await page.addInitScript(t=>localStorage.setItem('opsweave.ui.theme',t),theme);const f=await fixture(page);await expect(region(page).getByRole('button',{name:'开始采集',exact:true})).toBeEnabled();await region(page).getByRole('button',{name:'开始采集',exact:true}).click();await expect(region(page)).toContainText('已确认 1 窗口 · 1000 条');await region(page).getByRole('button',{name:'停止采集',exact:true}).click();await expect(region(page)).toContainText('已停止');await region(page).getByRole('button',{name:'查看日志',exact:true}).click();const records=page.getByRole('region',{name:'窗口日志记录'});await expect(records.locator('article')).toHaveCount(50);await expect(records.locator('pre').first()).toHaveText('  Synthetic Fixture 0 🧵\n<script>fixtureInjection=true</script>  ');await records.getByRole('button',{name:'下一页'}).click();await expect(records.locator('pre').first()).toContainText('Synthetic Fixture 50');await records.getByRole('button',{name:'上一页'}).click();await expect(records.locator('pre').first()).toContainText('Synthetic Fixture 0');expect(f.posts()).toBe(2);expect(await page.evaluate(()=>Object.hasOwn(window,'fixtureInjection'))).toBe(false);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)
 if(process.env.OPSWEAVE_SOURCE_SCREENSHOTS){mkdirSync(process.env.OPSWEAVE_SOURCE_SCREENSHOTS,{recursive:true});await page.screenshot({path:process.env.OPSWEAVE_SOURCE_SCREENSHOTS+`/log-stream-${width}-${theme}.png`,fullPage:true})}
})
for(const mode of ['fail','corrupt','bad-ns','bad-count'])test(`log stream ${mode} stops automatic reads`,async({page})=>{const f=await fixture(page,mode);await expect(region(page).getByRole('alert')).toContainText(mode==='fail'?'HTTP 503':'不符合契约');await page.waitForTimeout(5500);expect(f.reads()).toBe(1);expect(f.posts()).toBe(0);await region(page).getByRole('button',{name:'刷新状态'}).click();await expect.poll(f.reads).toBe(2)})
test('unknown original batch verifies without writing or reading source',async({page})=>{const f=await fixture(page,'unknown');await expect(region(page).getByRole('button',{name:'恢复采集'})).toBeDisabled();await region(page).getByRole('button',{name:'核验原批次'}).click();await expect(region(page)).toContainText('已确认 1 窗口 · 1000 条');expect(f.calls.filter(c=>c.body)).toHaveLength(1);expect(f.posts()).toBe(0)})
test('lost control acknowledgement queries original UUID without resend',async({page})=>{const f=await fixture(page,'lost');await region(page).getByRole('button',{name:'开始采集'}).click();await expect(region(page).getByRole('button',{name:'查询原控制回执'})).toBeEnabled();await region(page).getByRole('button',{name:'查询原控制回执'}).click();await expect(region(page)).toContainText('原操作已受理');expect(f.posts()).toBe(1);const command=f.calls.find(c=>c.path.endsWith('/start'))!;expect(f.calls.find(c=>c.path.includes('/commands/'))!.path).toContain(command.body.requestId)})
test('false command hash preserves original pending control',async({page})=>{const f=await fixture(page,'bad-receipt');await region(page).getByRole('button',{name:'开始采集'}).click();await expect(region(page).getByRole('alert')).toContainText('不符合契约');await expect(region(page).getByRole('button',{name:'查询原控制回执'})).toBeEnabled();await expect(region(page).getByRole('button',{name:'开始采集'})).toBeDisabled();expect(f.posts()).toBe(1)})
test('foreign record position cannot become original output',async({page})=>{await fixture(page,'foreign');await region(page).getByRole('button',{name:'查看日志'}).click();await expect(region(page).getByRole('alert')).toContainText('不符合契约');await expect(page.getByRole('region',{name:'窗口日志记录'})).toHaveCount(0)})
test('partial storage read remains explicitly incomplete without automatic retries',async({page})=>{const f=await fixture(page,'partial');await region(page).getByRole('button',{name:'查看日志'}).click();await expect(page.getByRole('region',{name:'窗口日志记录'}).getByRole('alert')).toContainText('尚未完整匹配');expect(f.calls.filter(c=>c.path.includes('/records'))).toHaveLength(1);expect(f.posts()).toBe(0)})
test('identity clear erases raw page and prevents later control acknowledgement',async({page})=>{const f=await fixture(page,'dense');await region(page).getByRole('button',{name:'查看日志'}).click();await expect(page.getByRole('region',{name:'窗口日志记录'}).locator('pre')).toHaveCount(50);await page.getByRole('button',{name:'清除开发会话'}).click();await expect(region(page)).toHaveCount(0);await expect(page.getByRole('region',{name:'窗口日志记录'})).toHaveCount(0);expect(f.posts()).toBe(0)})

test('new published version starts with the original control generation',async({page})=>{const f=await fixture(page,'new-version');await region(page).getByRole('button',{name:'开始采集',exact:true}).click();await expect(region(page)).toContainText('原操作已受理');const call=f.calls.find(c=>c.path.endsWith('/start'))!;expect(call.body.expectedGeneration).toBe(2);expect(call.body.revision).toBe(2);expect(f.posts()).toBe(1)})
test('historical closed version keeps closure visible without restart',async({page})=>{const f=await fixture(page,'closed-version');await expect(region(page)).toContainText('此版本已终止恢复');await expect(region(page).getByRole('button',{name:'开始采集',exact:true})).toHaveCount(0);expect(f.posts()).toBe(0)})
test('foreign version control metadata fails closed without starting',async({page})=>{const f=await fixture(page,'bad-control');await expect(region(page).getByRole('alert')).toContainText('不符合契约');expect(f.posts()).toBe(0)})

for(const width of [1440,1024,390])for(const theme of ['light','dark'])test(`legacy uncertainty preserves original controls ${width} ${theme}`,async({page})=>{await page.setViewportSize({width,height:940});await page.addInitScript(t=>localStorage.setItem('opsweave.ui.theme',t),theme);const f=await fixture(page,'legacy-rejection');await expect(region(page).getByRole('button',{name:'恢复采集',exact:true})).toBeDisabled();await expect(region(page)).toContainText('结果待确认');await expect(region(page)).not.toContainText('输出被拒绝');await expect(region(page).getByRole('button',{name:'核验原批次',exact:true})).toHaveCount(0);expect(f.posts()).toBe(0);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);if(process.env.OPSWEAVE_SOURCE_SCREENSHOTS){mkdirSync(process.env.OPSWEAVE_SOURCE_SCREENSHOTS,{recursive:true});await region(page).screenshot({path:process.env.OPSWEAVE_SOURCE_SCREENSHOTS+`/legacy-uncertainty-${width}-${theme}.png`})}})
for(const mode of ['bad-uncertainty','duplicate-uncertainty','foreign-uncertainty'])test(`log ${mode} never changes uncertainty into permission`,async({page})=>{const f=await fixture(page,mode);await expect(region(page).getByRole('alert')).toContainText('不符合契约');await expect(region(page).getByRole('button',{name:'开始采集',exact:true})).toBeDisabled();expect(f.posts()).toBe(0)})
test('resume flag with no task is invalid and cannot grant a start',async({page})=>{const f=await fixture(page,'bad-resume');await expect(region(page).getByRole('alert')).toContainText('不符合契约');expect(f.posts()).toBe(0)})

test('known rejection at generation limit keeps rejection evidence while resume stays disabled',async({page})=>{const f=await fixture(page,'known-rejection-limit');await expect(region(page).getByRole('button',{name:'恢复采集',exact:true})).toBeDisabled();await expect(region(page)).toContainText('输出被拒绝');await expect(region(page)).not.toContainText('原输出无法确认');expect(f.posts()).toBe(0)})
