import {test,expect,type Page} from '@playwright/test'
import {readFileSync,mkdirSync} from 'node:fs'
import {createHash} from 'node:crypto'
import {TOKEN_OK,WORKFLOW_OPERATORS} from './helpers.ts'
const example=(name:string)=>JSON.parse(readFileSync(new URL('../../../contracts/examples/v2/'+name+'.json',import.meta.url),'utf8'))
const iso=(ms:number)=>new Date(ms).toISOString().replace('.000Z','Z'),hash=(parts:string[])=>'sha256:'+createHash('sha256').update(parts.map(v=>Buffer.byteLength(v)+':'+v).join('')).digest('hex')
const tokenLabel='平台开发 Token（仅保存在当前标签页内存）',region=(p:Page)=>p.getByRole('region',{name:'日志历史重放',exact:true})
async function fixture(page:Page,mode='normal'){
 const now=Math.floor(Date.now()/1000)*1000,d=example('workflow-real-log-definition');for(const n of d.nodes)n.operatorDigest=WORKFLOW_OPERATORS.operators.find((o:any)=>o.type===n.type)!.digest
 const entry={definition:d,digest:'sha256:'+'a'.repeat(64),state:'PUBLISHED',editVersion:0,layout:Object.fromEntries(d.nodes.map((n:any,i:number)=>[n.id,{x:100,y:i*120}])),preview:null,updatedAt:iso(now)},ref={id:d.id,revision:1,digest:entry.digest},calls:{path:string;method:string;body:any}[]=[],plans:any[]=[];let receipt:any=null,lost=false
 function plan(c:any){const r=example('workflow-log-replay-plan');r.requestId=c.requestId;r.reference=ref;r.from=c.from;r.till=c.till;r.createdAt=iso(now);r.updatedAt=iso(now);r.expiresAt=iso(now+600000);r.commandDigest=hash(['log-replay-plan-v1',d.id,'1',entry.digest,c.from,c.till]);r.proof.scope={tenant:'synthetic-fixture',ownerScope:'a'.repeat(64),requestId:c.requestId,workflowId:d.id,revision:1,digest:entry.digest};r.proof.inputCount=mode==='pages'?60:1;r.proof.filtered=0;r.proof.indices=Array.from({length:r.proof.inputCount},(_,i)=>i);r.proof.positions=r.proof.indices.map((i:number)=>iso(Date.parse(c.from)+1000+i*500));if(mode==='empty'||mode==='bad-empty'){r.proof.positions=[];r.proof.indices=[];r.proof.inputCount=0;if(mode==='empty'){const s=r.proof.scope;r.proof.batchDigest=hash(['workflow-log-window-v1',s.tenant,s.ownerScope,s.requestId,s.workflowId,String(s.revision),s.digest,c.from,c.till,'0','0'])}}if(mode==='long-tenant')r.proof.scope.tenant='t'.repeat(128);if(mode==='too-long-tenant')r.proof.scope.tenant='t'.repeat(129);if(mode==='time-newline')r.proof.positions[0]+='\n';if(mode==='foreign-scope')r.proof.scope.workflowId='foreign-fixture';if(mode==='preparing'){r.state='PREPARING';r.proof=null}return r}
 function outcome(c:any,p:any){return {schemaVersion:'2.0',requestId:c.requestId,planId:p.requestId,reference:ref,commandDigest:hash(['log-replay-execute-v1',p.requestId,p.proof.inputDigest,p.proof.batchDigest]),acceptedAt:iso(now+1000),updatedAt:iso(now+1000),state:mode==='unknown'?'UNKNOWN':'CONFIRMED',error:mode==='unknown'?'OUTPUT_UNCONFIRMED':null}}
 await page.route(/\/api\/v1\/integrations\/workflows(?:\/|$)/,async route=>{
  const url=new URL(route.request().url()),path=url.pathname,method=route.request().method(),body=route.request().postDataJSON();calls.push({path,method,body})
  if(path.endsWith('/history'))return route.fulfill({json:{schemaVersion:'2.0',asOf:iso(now),snapshotAt:iso(now),reference:ref,coverage:'RECORDED_CHECKS',offset:0,recordedCount:0,items:[],nextCursor:null,hasMore:false}})
  if(!path.includes('/log-replays/'))return route.fulfill({json:{schemaVersion:'2.0',storage:'memory',operatorCatalog:WORKFLOW_OPERATORS,metricMappings:[example('metric-mapping-definition')],drafts:{items:[],truncated:false},published:{items:[entry],truncated:false},models:[],modelsTruncated:false,zabbixSource:{instanceId:'fixture-source',mode:'fixture'},runs:{items:[],truncated:false}}})
  if(mode==='403')return route.fulfill({status:403,json:{error:'FORBIDDEN'}})
  if(path.endsWith('/plans')&&method==='GET')return route.fulfill({json:{items:plans,truncated:false}})
  if(path.endsWith('/plans')&&method==='POST'){const r=plan(body);if((mode==='lost-plan'||mode==='missing')&&!lost){lost=true;if(mode!=='missing')plans.unshift(r);return route.abort()}plans.unshift(r);if(mode==='private')r.samples=[{value:'raw'}];if(mode==='invented')r.proof.inputCount=1001;if(mode==='notify')r.notifications=true;if(mode==='foreign')r.reference={...ref,id:'other-fixture'};return route.fulfill({json:r})}
  if(path.endsWith('/execute')){receipt=outcome(body,plans[0]);if(mode==='lost-execute'&&!lost){lost=true;return route.abort()}return route.fulfill({json:receipt})}
  if(path.includes('/records')){const p=plans[0],after=path.includes('/after/')?Number(path.split('/').at(-1)):-1,indices=p.proof.indices.filter((i:number)=>i>after).slice(0,50);return route.fulfill({json:{batchId:p.requestId,readAt:iso(now+2000),storage:'clickhouse',expectedRecords:p.proof.indices.length,complete:true,afterIndex:after,nextIndex:p.proof.indices.some((i:number)=>i>indices.at(-1))?indices.at(-1):null,records:indices.map((i:number)=>({index:i,position:p.proof.positions[i],eventTime:p.proof.positions[i],body:'Synthetic Fixture <script> literal '+i,severityText:null,serviceName:null,traceId:null,spanId:null}))}})}
  if(path.endsWith('/verification')){receipt={...receipt,state:'CONFIRMED',error:null};return route.fulfill({json:receipt})}
  if(path.includes('/commands/'))return receipt?route.fulfill({json:receipt}):route.fulfill({status:404,json:{error:'NOT_FOUND'}})
  if(path.endsWith('/execution'))return route.fulfill({json:{receipt}})
  const r=plans.find(r=>path.endsWith('/'+r.requestId));return r?route.fulfill({json:r}):route.fulfill({status:404,json:{error:'NOT_FOUND'}})
 })
 await page.goto('/#/integrations/workflows/runs');await page.getByRole('textbox',{name:tokenLabel}).fill(TOKEN_OK);await expect(page.getByRole('combobox',{name:'历史发布版本'})).toHaveValue(d.id+'@1');await expect(page.getByRole('button',{name:'刷新运行历史'})).toBeEnabled()
 return {calls,plans,entry,now}
}
async function open(page:Page){await page.locator('.workflow-metric-replay>summary').click();await expect(region(page)).toContainText('暂无历史重放选择')}
async function prepare(page:Page){await region(page).getByRole('button',{name:'检查重放范围'}).click()}
for(const width of [1440,1024,390])for(const theme of ['light','dark'])test('bounded reconstruction at '+width+' '+theme,async({page})=>{
 await page.setViewportSize({width,height:1100});await page.addInitScript(value=>localStorage.setItem('opsweave.ui.theme',value),theme);const f=await fixture(page);expect(f.calls.filter(c=>c.path.includes('/log-replays/'))).toHaveLength(0);await open(page);await prepare(page);await expect(region(page)).toContainText('待执行');await expect(region(page)).toContainText(f.entry.definition.source.log.sourceKey);await expect(region(page)).toContainText('1 / 0 / 1');expect(f.calls.filter(c=>c.path.endsWith('/execute'))).toHaveLength(0)
 await region(page).getByRole('button',{name:'确认重放'}).focus();await page.keyboard.press('Enter');await expect(region(page)).toContainText('已确认');expect((await region(page).getByRole('button',{name:'查看重放日志'}).boundingBox())!.width).toBeLessThan(300);await expect(region(page).locator('tbody tr')).toContainText('范围已固定');expect(f.calls.filter(c=>c.path.endsWith('/execute'))).toHaveLength(1);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);expect(f.calls.filter(c=>c.path.endsWith('/plans')&&c.method==='GET')).toHaveLength(1)
 if(process.env.OPSWEAVE_SOURCE_SCREENSHOTS){mkdirSync(process.env.OPSWEAVE_SOURCE_SCREENSHOTS,{recursive:true});await page.screenshot({path:process.env.OPSWEAVE_SOURCE_SCREENSHOTS+'/log-replay-'+width+'-'+theme+'.png',fullPage:true})}
})
for(const mode of ['private','invented','notify','foreign','bad-empty','time-newline','foreign-scope','too-long-tenant'])test('invalid acknowledgement retains original UUID '+mode,async({page})=>{const f=await fixture(page,mode);await open(page);await prepare(page);await expect(region(page).getByRole('alert')).toContainText('不符合契约');await expect(region(page).getByRole('button',{name:'查询原重放请求'})).toBeVisible();await expect(page.getByRole('button',{name:'预览与版本测试'})).toBeDisabled();await expect(page.getByRole('combobox',{name:'历史发布版本'})).toBeDisabled();expect(f.calls.filter(c=>c.path.endsWith('/plans')&&c.method==='POST')).toHaveLength(1)})
test('lost prepare result is queried without another source command',async({page})=>{const f=await fixture(page,'lost-plan');await open(page);await prepare(page);await expect(region(page).getByRole('button',{name:'查询原重放请求'})).toBeVisible();await region(page).getByRole('button',{name:'查询原重放请求'}).click();await expect(region(page)).toContainText('待执行');expect(f.calls.filter(c=>c.path.endsWith('/plans')&&c.method==='POST')).toHaveLength(1);expect(f.calls.filter(c=>c.path.endsWith('/'+f.plans[0].requestId)&&c.method==='GET')).toHaveLength(1)})
test('404 allows only explicit same UUID and identical body resend',async({page})=>{const f=await fixture(page,'missing');await open(page);await prepare(page);await region(page).getByRole('button',{name:'查询原重放请求'}).click();await region(page).getByRole('button',{name:'原样重发'}).click();await expect(region(page)).toContainText('待执行');const posts=f.calls.filter(c=>c.path.endsWith('/plans')&&c.method==='POST');expect(posts).toHaveLength(2);expect(posts[1].body).toEqual(posts[0].body)})
test('lost execution is recovered from original receipt without resend',async({page})=>{const f=await fixture(page,'lost-execute');await open(page);await prepare(page);await region(page).getByRole('button',{name:'确认重放'}).click();await expect(region(page).getByRole('button',{name:'查询原重放请求'})).toBeVisible();await region(page).getByRole('button',{name:'查询原重放请求'}).click();await expect(region(page)).toContainText('已确认');expect(f.calls.filter(c=>c.path.endsWith('/execute'))).toHaveLength(1);await region(page).getByRole('button',{name:'查看重放',exact:true}).click();await expect.poll(()=>f.calls.filter(c=>c.path.endsWith('/execution')).length).toBe(1);await expect(region(page)).toContainText('已确认')})
test('unknown output only invokes explicit verification',async({page})=>{const f=await fixture(page,'unknown');await open(page);await prepare(page);await region(page).getByRole('button',{name:'确认重放'}).click();await expect(region(page)).toContainText('输出待确认');expect(f.calls.filter(c=>c.path.endsWith('/verification'))).toHaveLength(0);await region(page).getByRole('button',{name:'核验原输出'}).click();await expect(region(page)).toContainText('已确认');expect(f.calls.filter(c=>c.path.endsWith('/execute'))).toHaveLength(1);expect(f.calls.filter(c=>c.path.endsWith('/verification'))).toHaveLength(1)})
test('empty selection is displayed without manufactured data',async({page})=>{await fixture(page,'empty');await open(page);await prepare(page);await expect(region(page)).toContainText('0 / 0 / 0');await region(page).getByRole('button',{name:'确认重放'}).click();await expect(region(page)).toContainText('已确认')})
test('preparing selection cannot execute and is not silently reread',async({page})=>{const f=await fixture(page,'preparing');await open(page);await prepare(page);await expect(region(page)).toContainText('范围检查待确认');await expect(region(page).getByRole('button',{name:'确认重放'})).toHaveCount(0);expect(f.calls.filter(c=>c.method==='POST')).toHaveLength(1)})
test('403 clears private results and has no automatic retry',async({page})=>{const f=await fixture(page,'403');await page.locator('.workflow-metric-replay>summary').click();await expect(region(page)).toHaveCount(0);await page.waitForTimeout(1100);expect(f.calls.filter(c=>c.path.includes('/log-replays/'))).toHaveLength(1)})
test('identity replacement clears held private metadata and UUID',async({page})=>{const f=await fixture(page,'lost-plan');await open(page);await prepare(page);await expect(region(page).getByRole('button',{name:'查询原重放请求'})).toBeVisible();await page.getByRole('button',{name:'清除开发会话'}).click();await expect(region(page)).toHaveCount(0);expect(await page.evaluate(()=>JSON.stringify({...localStorage,...sessionStorage}))).not.toContain(f.plans[0].requestId)})

test('explicit output view escapes log text and never replays again',async({page})=>{const f=await fixture(page);await open(page);await prepare(page);await region(page).getByRole('button',{name:'确认重放'}).click();await expect(region(page)).toContainText('已确认');expect(f.calls.filter(c=>c.path.includes('/records'))).toHaveLength(0);await region(page).getByRole('button',{name:'查看重放日志'}).click();const data=region(page).getByRole('region',{name:'重放日志记录'});await expect(data.locator('pre')).toContainText('Synthetic Fixture <script> literal 0');await expect(data.locator('script')).toHaveCount(0);expect(f.calls.filter(c=>c.path.endsWith('/execute'))).toHaveLength(1);expect(f.calls.filter(c=>c.path.includes('/records'))).toHaveLength(1)})
test('output pagination preserves original range without new source calls',async({page})=>{const f=await fixture(page,'pages');await open(page);await prepare(page);await region(page).getByRole('button',{name:'确认重放'}).click();await expect(region(page)).toContainText('已确认');await region(page).getByRole('button',{name:'查看重放日志'}).click();const data=region(page).getByRole('region',{name:'重放日志记录'});await expect(data.locator('article')).toHaveCount(50);await data.getByRole('button',{name:'下一页'}).click();await expect(data.locator('article')).toHaveCount(10);await expect(data).toContainText('记录 51');await data.getByRole('button',{name:'上一页'}).click();await expect(data.locator('article')).toHaveCount(50);expect(f.calls.filter(c=>c.path.endsWith('/execute'))).toHaveLength(1);expect(f.calls.filter(c=>c.path.endsWith('/plans')&&c.method==='POST')).toHaveLength(1)})

test('full legal tenant identifier remains readable',async({page})=>{await fixture(page,'long-tenant');await open(page);await prepare(page);await expect(region(page)).toContainText('待执行');await region(page).getByRole('button',{name:'确认重放'}).click();await expect(region(page)).toContainText('已确认')})
