import {test,expect,type Page} from '@playwright/test'
import {readFileSync,mkdirSync} from 'node:fs'
import {createHash} from 'node:crypto'
import {WORKFLOW_OPERATORS,TOKEN_OK,closeWorkflowInspector} from './helpers.ts'
// Explicit protocol fixtures; real PostgreSQL and output preservation are checked separately.
const example=(n:string)=>JSON.parse(readFileSync(new URL('../../../contracts/examples/v2/'+n+'.json',import.meta.url),'utf8'))
const batch='20000000-0000-4000-8000-000000000128',digest='sha256:'+'a'.repeat(64),iso=(n:number)=>new Date(n).toISOString().replace('.000Z','Z')
const region=(p:Page)=>p.getByRole('region',{name:'终止任务恢复',exact:true})
async function fixture(page:Page,mode='normal',kind='LOG_STREAM'){
 const now=Math.floor(Date.now()/1000)*1000,definition=example(kind==='HOST_SCAN'?'workflow-definition':kind==='METRIC_STREAM'?'workflow-real-metric-definition':'workflow-real-log-definition')
 if(kind==='HOST_SCAN'){const configuration=example('workflow-real-log-definition').source.configuration;definition.source={kind:'ZABBIX_HOST',instanceId:configuration.sourceId,configuration}}
 for(const n of definition.nodes)n.operatorDigest=WORKFLOW_OPERATORS.operators.find((o:any)=>o.type===n.type)!.digest
 const saved={definition,digest,state:'PUBLISHED',editVersion:0,updatedAt:iso(now),preview:null,layout:Object.fromEntries(definition.nodes.map((n:any,i:number)=>[n.id,{x:160,y:i*160}]))},counts={input:1,accepted:1,rejected:0,filtered:0,deduplicated:0,outputExpected:1,confirmed:0,outputRejected:0,unknown:1,pending:0,repeatedOutput:0,late:0}
 const b:any={id:batch,observedAt:iso(now-1000),updatedAt:iso(now-1000),from:kind==='HOST_SCAN'?null:iso(now-81000),till:kind==='HOST_SCAN'?null:iso(now-21000),unit:kind==='HOST_SCAN'?'ENTITY':kind==='METRIC_STREAM'?'POINT':'LOG_RECORD',state:mode==='in-flight'?'IN_FLIGHT':'UNKNOWN',coverage:kind==='HOST_SCAN'?'PAGE':'WINDOW',sampleRate:null,counts,error:mode==='in-flight'?null:kind==='HOST_SCAN'?'OUTPUT_UNAVAILABLE':'OUTPUT_UNCONFIRMED',reconcilesBatchId:null}
 if(mode==='in-flight'){counts.unknown=0;counts.pending=1}
 if(kind==='HOST_SCAN')b.counts=Object.fromEntries(Object.keys(counts).map(k=>[k,k==='input'?1:k==='confirmed'?0:null]))
 const report:any={schemaVersion:'2.0',asOf:iso(now),reference:{id:definition.id,revision:1,digest},kind,task:{state:mode==='running'?'RUNNING':mode==='closed'?'ABANDONED':'FAILED',generation:1,updatedAt:iso(now-1000),error:mode==='running'?null:kind==='HOST_SCAN'?'OUTPUT_UNAVAILABLE':'OUTPUT_UNCONFIRMED',pendingBatchId:batch},batches:[b],truncated:false}
 if(mode==='outside-history-lost')report.batches=Array.from({length:20},(_,i)=>({...b,id:'30000000-0000-4000-8000-'+String(i).padStart(12,'0'),state:'CONFIRMED',error:null,counts:{...counts,confirmed:1,unknown:0}}));if(mode==='outside-history-lost')report.truncated=true
 const commands:any[]=[];let queries=0,receipt:any
 await page.route(/\/api\/v1\/integrations\/workflows(?:\/|$)/,async route=>{
  const path=new URL(route.request().url()).pathname
  if(path.endsWith('/recovery/abandon')){
   const c=route.request().postDataJSON();commands.push(c);expect(c.acknowledgeUncertainOutput).toBe(true);expect(c.batchId).toBe(batch)
   if(commands.length>1)expect(c).toEqual(commands[0])
   if(mode==='forbidden')return route.fulfill({status:403,json:{error:'FORBIDDEN'}})
   const parts=['workflow-abandon-recovery-v1',c.id,String(c.revision),c.digest,c.kind,c.batchId,String(c.expectedGeneration),'true'];receipt={requestId:c.requestId,commandDigest:'sha256:'+createHash('sha256').update(Buffer.concat(parts.flatMap(v=>[Buffer.from(Buffer.byteLength(v)+':'),Buffer.from(v)]))).digest('hex'),reference:report.reference,kind,batchId:batch,previousGeneration:1,generation:2,acceptedAt:iso(now),state:'ABANDONED',preservedCursor:kind==='HOST_SCAN'?null:b.from,confirmedBatches:0,confirmedRecords:0}
   if(commands.length===1&&(mode==='lost'||mode==='missing'||mode==='outside-history-lost'))return route.abort('failed')
   report.task={...report.task,state:'ABANDONED',generation:2,updatedAt:iso(now)}
   if(mode==='host-cursor')receipt.preservedCursor='ids-v1|'+'a'.repeat(64)+'|7|5';return route.fulfill({json:mode==='private'?{...receipt,authority:{}}:mode==='wrong-generation'?{...receipt,generation:3}:receipt})
  }
  if(path.includes('/recovery/commands/')){queries++;if(mode==='missing')return route.fulfill({status:404,json:{error:'NOT_FOUND'}});report.task={...report.task,state:'ABANDONED',generation:2,updatedAt:iso(now)};return route.fulfill({json:receipt})}
  if(path.includes('/quality/')&&path.endsWith('/batches/'+batch))return route.fulfill({json:b})
  if(path.includes('/quality/'))return route.fulfill({json:report})
  if(path.endsWith('/workflows'))return route.fulfill({json:{schemaVersion:'2.0',storage:'postgres',operatorCatalog:WORKFLOW_OPERATORS,metricMappings:[],drafts:{items:[],truncated:false},published:{items:[saved],truncated:false},models:[],modelsTruncated:false,zabbixSource:{instanceId:'fixture-source',mode:'fixture'},runs:{items:[],truncated:false}}})
  if(path.includes('/versions/'))return route.fulfill({json:saved})
  return route.fulfill({status:404,json:{error:'NOT_FOUND'}})
 })
 await page.goto('/#/integrations/workflows');await page.getByRole('textbox',{name:'平台开发 Token（仅保存在当前标签页内存）'}).fill(TOKEN_OK);await page.getByRole('button',{name:'查看',exact:true}).click();await closeWorkflowInspector(page);await page.locator('summary').filter({hasText:/^运行质量与异常$/}).click()
 return {commands,queries:()=>queries}
}
for(const width of [1440,1024,390])for(const theme of ['light','dark'])test(`recovery explicit closure ${width} ${theme}`,async({page})=>{await page.setViewportSize({width,height:940});await page.addInitScript(t=>localStorage.setItem('opsweave.ui.theme',t),theme);const f=await fixture(page);await expect(region(page).getByRole('button',{name:'终止恢复',exact:true})).toBeDisabled();expect(f.commands).toHaveLength(0);await region(page).getByRole('checkbox').check();await region(page).getByRole('button',{name:'终止恢复',exact:true}).click();await expect(region(page)).toContainText('已受理');await expect(page.getByRole('region',{name:'运行质量与异常',exact:true})).toContainText('结果未知');expect(f.commands).toHaveLength(1);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);if(process.env.OPSWEAVE_SOURCE_SCREENSHOTS){mkdirSync(process.env.OPSWEAVE_SOURCE_SCREENSHOTS,{recursive:true});await region(page).screenshot({path:process.env.OPSWEAVE_SOURCE_SCREENSHOTS+`/recovery-${width}-${theme}.png`})}})
for(const kind of ['HOST_SCAN','METRIC_STREAM'])test(`recovery ${kind} uses the original scope`,async({page})=>{const f=await fixture(page,'normal',kind);await region(page).getByRole('checkbox').check();await region(page).getByRole('button',{name:'终止恢复',exact:true}).click();await expect(region(page)).toContainText('已受理');expect(f.commands[0].kind).toBe(kind)})
test('lost closure response queries original UUID without reposting',async({page})=>{const f=await fixture(page,'lost');await region(page).getByRole('checkbox').check();await region(page).getByRole('button',{name:'终止恢复',exact:true}).click();await expect(region(page)).toContainText('控制结果待确认');await page.waitForTimeout(1200);expect(f.commands).toHaveLength(1);expect(f.queries()).toBe(0);await region(page).getByRole('button',{name:'查询原终止回执'}).click();await expect(region(page)).toContainText('已受理');expect(f.commands).toHaveLength(1);expect(f.queries()).toBe(1)})
test('only original 404 enables exact command resend',async({page})=>{const f=await fixture(page,'missing');await region(page).getByRole('checkbox').check();await region(page).getByRole('button',{name:'终止恢复',exact:true}).click();await region(page).getByRole('button',{name:'查询原终止回执'}).click();await region(page).getByRole('button',{name:'原样重发终止命令'}).click();await expect(region(page)).toContainText('已受理');expect(f.commands).toHaveLength(2);expect(f.commands[1]).toEqual(f.commands[0])})
for(const mode of ['private','wrong-generation'])test(`recovery ${mode} never treats receipt as confirmed`,async({page})=>{const f=await fixture(page,mode);await region(page).getByRole('checkbox').check();await region(page).getByRole('button',{name:'终止恢复',exact:true}).click();await expect(region(page).getByRole('alert')).toContainText('不符合契约');await expect(region(page)).toContainText('控制结果待确认');expect(f.commands).toHaveLength(1)})
for(const mode of ['running','in-flight'])test(`recovery ${mode} has no terminal action`,async({page})=>{const f=await fixture(page,mode);await expect(region(page)).toHaveCount(0);expect(f.commands).toHaveLength(0)})
test('already closed task keeps uncertain batch visible',async({page})=>{await fixture(page,'closed');await expect(region(page)).toContainText('已终止恢复');await expect(region(page).getByRole('button',{name:'终止恢复',exact:true})).toHaveCount(0);await expect(page.getByRole('region',{name:'运行质量与异常',exact:true})).toContainText('结果未知')})
test('recovery 403 clears the trusted page',async({page})=>{const f=await fixture(page,'forbidden');await region(page).getByRole('checkbox').check();await region(page).getByRole('button',{name:'终止恢复',exact:true}).click();await expect(region(page)).toHaveCount(0);expect(f.commands).toHaveLength(1)})

test('unknown closure keeps the quality section open until original receipt is resolved',async({page})=>{const f=await fixture(page,'lost');await region(page).getByRole('checkbox').check();await region(page).getByRole('button',{name:'终止恢复',exact:true}).click();await expect(region(page)).toContainText('控制结果待确认');await expect(page.getByRole('button',{name:'创建下一版',exact:true})).toBeDisabled();await page.locator('summary').filter({hasText:/^运行质量与异常$/}).click();await expect(region(page)).toBeVisible();expect(f.commands).toHaveLength(1);await region(page).getByRole('button',{name:'查询原终止回执'}).click();await expect(region(page)).toContainText('已受理');await page.locator('summary').filter({hasText:/^运行质量与异常$/}).click();await expect(region(page)).toHaveCount(0)})

test('only explicit original 404 permits dropping local confirmation without cancelling output',async({page})=>{const f=await fixture(page,'missing');await region(page).getByRole('checkbox').check();await region(page).getByRole('button',{name:'终止恢复',exact:true}).click();await expect(region(page).getByRole('button',{name:'放弃本次确认',exact:true})).toHaveCount(0);await region(page).getByRole('button',{name:'查询原终止回执'}).click();await region(page).getByRole('button',{name:'放弃本次确认',exact:true}).click();await expect(region(page)).toContainText('服务器命令未取消');await expect(page.getByRole('button',{name:'创建下一版',exact:true})).toBeEnabled();expect(f.commands).toHaveLength(1);await expect(region(page).getByRole('checkbox')).not.toBeChecked()})

test('host receipt private cursor is rejected while original command stays pending',async({page})=>{const f=await fixture(page,'host-cursor','HOST_SCAN');await region(page).getByRole('checkbox').check();await region(page).getByRole('button',{name:'终止恢复',exact:true}).click();await expect(region(page).getByRole('alert')).toContainText('不符合契约');await expect(region(page)).toContainText('控制结果待确认');expect(f.commands).toHaveLength(1)})

test('original UUID outside recent history can close recovery and keeps unknown command when detail is dismissed',async({page})=>{const f=await fixture(page,'outside-history-lost');await expect(region(page)).toHaveCount(0);const quality=page.getByRole('region',{name:'运行质量与异常',exact:true});await quality.getByRole('button',{name:batch,exact:true}).click();await quality.getByRole('button',{name:'查询批次',exact:true}).click();await expect(region(page)).toHaveCount(1);await region(page).getByRole('checkbox').check();await region(page).getByRole('button',{name:'终止恢复',exact:true}).click();await expect(region(page)).toContainText('控制结果待确认');await page.getByRole('article',{name:'质量批次详情',exact:true}).getByRole('button',{name:'关闭详情',exact:true}).click();await expect(region(page)).toContainText('控制结果待确认');await region(page).getByRole('button',{name:'查询原终止回执',exact:true}).click();await expect(region(page)).toContainText('此任务已终止恢复');expect(f.commands).toHaveLength(1);expect(f.commands[0].batchId).toBe(batch)})
