import {test,expect,type Page} from '@playwright/test'
import {readFileSync,mkdirSync} from 'node:fs'
import {createHash} from 'node:crypto'
import {WORKFLOW_OPERATORS,TOKEN_OK,closeWorkflowInspector} from './helpers.ts'
// Explicit wire Fixtures. PostgreSQL/HTTP and actual main preservation are checked separately.
const kinds=['SOURCE_FAILURES','OUTPUT_REJECTIONS','QUEUE_WAIT','TASK_FAILURE'],values=[3,0,275,1],labels=['连续来源失败','连续输出拒绝','排队时间峰值','当前任务失败']
const region=(page:Page)=>page.getByRole('region',{name:'质量阈值',exact:true}),iso=(ms:number)=>new Date(ms).toISOString().replace('.000Z','Z'),evidence='10000000-0000-4000-8000-000000000134'
async function fixture(page:Page,mode='empty',gate?:Promise<void>){
 const definition=JSON.parse(readFileSync(new URL('../../../contracts/examples/v2/workflow-real-log-definition.json',import.meta.url),'utf8')),digest='sha256:'+'a'.repeat(64),now=Math.floor(Date.now()/1000)*1000,at=iso(now)
 for(const n of definition.nodes)n.operatorDigest=WORKFLOW_OPERATORS.operators.find((o:any)=>o.type===n.type)!.digest
 const entry={definition,digest,state:'PUBLISHED',editVersion:0,updatedAt:at,preview:null,layout:Object.fromEntries(definition.nodes.map((n:any,i:number)=>[n.id,{x:100,y:160*i}]))},reference={id:definition.id,revision:definition.revision,digest}
 let configuration:any=mode==='empty'||['lost','missing','invalid-receipt','conflict'].includes(mode)?null:{reference,editVersion:1,windowSeconds:600,rules:kinds.map((kind,i)=>({kind,threshold:i===0?3:i===2?250:1})),updatedAt:at}
 const receipts=new Map<string,any>(),posts:any[]=[],queries:string[]=[];let reads=0
 const report=()=>{const rules=configuration?.rules??[],result:any={schemaVersion:'2.0',asOf:at,reference,configuration,from:configuration?iso(now-configuration.windowSeconds*1000):null,till:configuration?at:null,evaluations:rules.map((r:any)=>({kind:r.kind,state:values[kinds.indexOf(r.kind)]>=r.threshold?'TRIGGERED':'NORMAL',value:values[kinds.indexOf(r.kind)],unit:r.kind==='QUEUE_WAIT'?'MILLISECONDS':'COUNT',sampleCount:1,missingCount:0,evidenceIds:r.kind==='TASK_FAILURE'?[]:[evidence],truncated:false,reason:null}))}
  if(mode==='private')result.tenantId='forged'
  if(mode==='false-normal')result.evaluations[0].state='NORMAL'
  if(mode==='unknown-zero'){result.evaluations[0].state='UNAVAILABLE';result.evaluations[0].reason='NO_DATA';result.evaluations[0].value=0}
  if(mode==='wrong-window')result.from=iso(now-601000)
  if(mode==='future-configuration')result.configuration={...configuration,updatedAt:iso(now+1000)}
  if(mode==='wrong-kind')result.evaluations[0].kind='LEASE_CONFLICT'
  if(mode==='bad-evidence')result.evaluations[0].evidenceIds=['1-1-1-1-1']
  if(mode==='bad-count')result.evaluations[0].sampleCount=21
  if(mode==='unavailable'){for(const e of result.evaluations)Object.assign(e,{state:'UNAVAILABLE',value:null,sampleCount:0,evidenceIds:[],reason:'NO_DATA'})}
  if(mode==='ambiguous')Object.assign(result.evaluations[0],{state:'UNAVAILABLE',value:null,reason:'AMBIGUOUS_ORDER'})
  return result
 }
 await page.route(/\/api\/v1\/integrations\/workflows(?:\/|$)/,async route=>{
  const path=new URL(route.request().url()).pathname
  if(path.includes('/alerts')){
   if(path.endsWith('/configure')){const body=route.request().postDataJSON();posts.push(body);if(mode==='conflict')return route.fulfill({status:409,json:{error:'CONFLICT'}});if(mode==='missing'&&posts.length===1)return route.abort('failed');const parts=['workflow-quality-alerts-v1',body.id,String(body.revision),body.digest,String(body.expectedVersion),String(body.windowSeconds),...body.rules.flatMap((r:any)=>[r.kind,String(r.threshold)])];configuration={reference,editVersion:body.expectedVersion+1,windowSeconds:body.windowSeconds,rules:body.rules,updatedAt:at};const receipt={schemaVersion:'2.0',requestId:body.requestId,commandDigest:'sha256:'+createHash('sha256').update(parts.map(v=>Buffer.byteLength(v)+':'+v).join('')).digest('hex'),acceptedAt:at,configuration};receipts.set(body.requestId,receipt);if(mode==='lost'&&posts.length===1)return route.abort('failed');return route.fulfill({json:mode==='invalid-receipt'&&posts.length===1?{...receipt,tenantId:'forged'}:receipt})}
   if(path.includes('/commands/')){queries.push(path);const receipt=receipts.get(path.split('/').at(-1)!);return receipt?route.fulfill({json:receipt}):route.fulfill({status:404,json:{error:'NOT_FOUND'}})}
   reads++;if(gate)await gate;if(mode==='forbidden'||mode==='fail')return route.fulfill({status:mode==='forbidden'?403:503,json:{error:'UNAVAILABLE'}});return route.fulfill({json:report()})
  }
  if(path.includes('/quality/'))return route.fulfill({json:{schemaVersion:'2.0',asOf:at,reference,kind:'LOG_STREAM',task:null,batches:[],truncated:false}})
  if(path.endsWith('/workflows'))return route.fulfill({json:{schemaVersion:'2.0',storage:'postgres',operatorCatalog:WORKFLOW_OPERATORS,metricMappings:[],drafts:{items:[],truncated:false},published:{items:[entry],truncated:false},models:[],modelsTruncated:false,zabbixSource:{instanceId:'fixture-source',mode:'fixture'},runs:{items:[],truncated:false}}})
  if(path.includes('/versions/'))return route.fulfill({json:entry})
  return route.fulfill({status:404,json:{error:'NOT_FOUND'}})
 })
 await page.goto('/#/integrations/workflows');await page.getByRole('textbox',{name:'平台开发 Token（仅保存在当前标签页内存）'}).fill(TOKEN_OK);await page.getByRole('button',{name:'查看',exact:true}).click();await closeWorkflowInspector(page);await page.getByText('运行质量与异常',{exact:true}).click();expect(reads).toBe(0);await page.locator('details > summary').filter({hasText:/^质量阈值$/}).click();await expect(region(page)).toBeVisible()
 return {reads:()=>reads,posts,queries}
}
for(const width of [1440,1024,390])for(const theme of ['light','dark'])test(`quality alert configuration ${width} ${theme}`,async({page})=>{
 await page.setViewportSize({width,height:940});await page.addInitScript(t=>localStorage.setItem('opsweave.ui.theme',t),theme);const f=await fixture(page,'configured');await expect(region(page).locator('tbody tr')).toHaveCount(4);await expect(region(page)).toContainText('275 ms');await expect(region(page).getByRole('checkbox',{name:'启用连续来源失败'})).toBeChecked();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);const summary=page.locator('details > summary').filter({hasText:/^质量阈值$/});await summary.click();await summary.click();expect(f.reads()).toBe(1);expect(f.posts).toHaveLength(0)
 const geometry=await region(page).evaluate(el=>({rows:[...el.querySelectorAll('.workflow-alert-rule')].map(r=>r.getBoundingClientRect().height),results:[...el.querySelectorAll('tbody tr')].map(r=>r.getBoundingClientRect().height),checkboxes:[...el.querySelectorAll('input[type=checkbox]')].map(r=>r.getBoundingClientRect().height),footerPosition:getComputedStyle(el.querySelector('form > footer')!).position}));expect(geometry.rows.every(h=>h<=100)).toBe(true);expect(geometry.results.every(h=>h<=90)).toBe(true);expect(geometry.checkboxes.every(h=>h<=18)).toBe(true);expect(geometry.footerPosition).toBe('static')
 if(process.env.OPSWEAVE_SOURCE_SCREENSHOTS){mkdirSync(process.env.OPSWEAVE_SOURCE_SCREENSHOTS,{recursive:true});await region(page).screenshot({path:process.env.OPSWEAVE_SOURCE_SCREENSHOTS+`/quality-alerts-${width}-${theme}.png`})}
})
test('unconfigured rules stay inactive until explicit save and preserve one initial GET',async({page})=>{const f=await fixture(page);await expect(region(page)).toContainText('尚未配置阈值');await region(page).getByRole('checkbox',{name:'启用排队时间峰值'}).check();await expect(region(page).getByRole('button',{name:'保存规则'})).toBeEnabled();await region(page).getByRole('button',{name:'保存规则'}).click();await expect(region(page)).toContainText('配置 v1');await expect(region(page)).toContainText('已触发');expect(f.posts).toHaveLength(1);expect(f.reads()).toBe(2);expect(f.posts[0].rules).toEqual([{kind:'QUEUE_WAIT',threshold:250}]);await region(page).getByRole('checkbox',{name:'启用排队时间峰值'}).uncheck();await region(page).getByRole('button',{name:'保存规则'}).click();await expect(region(page)).toContainText('规则已停用');expect(f.posts).toHaveLength(2);expect(f.posts[1].expectedVersion).toBe(1);expect(f.posts[1].rules).toEqual([])})
for(const mode of ['lost','invalid-receipt'])test(`${mode} keeps original command and queries metadata once`,async({page})=>{const f=await fixture(page,mode);await expect(region(page)).toContainText('尚未配置阈值');await region(page).getByRole('checkbox',{name:'启用排队时间峰值'}).check();await region(page).getByRole('button',{name:'保存规则'}).click();await expect(region(page)).toContainText('配置结果待确认');const summary=page.locator('details > summary').filter({hasText:/^质量阈值$/});await summary.click();await expect(region(page)).toBeVisible();await region(page).getByRole('button',{name:'查询配置回执'}).click();await expect(region(page)).toContainText('配置 v1');expect(f.posts).toHaveLength(1);expect(f.queries).toHaveLength(1);expect(f.queries[0]).toContain(f.posts[0].requestId)})
test('explicit 404 allows original resend with same UUID and body',async({page})=>{const f=await fixture(page,'missing');await expect(region(page)).toContainText('尚未配置阈值');await region(page).getByRole('checkbox',{name:'启用排队时间峰值'}).check();await region(page).getByRole('button',{name:'保存规则'}).click();await expect(region(page)).toContainText('配置结果待确认');await region(page).getByRole('button',{name:'查询配置回执'}).click();await expect(region(page).getByRole('button',{name:'原样重发配置'})).toBeVisible();await region(page).getByRole('button',{name:'原样重发配置'}).click();await expect(region(page)).toContainText('配置 v1');expect(f.posts).toHaveLength(2);expect(f.posts[1]).toEqual(f.posts[0])})
test('dirty rules prevent folding and undo returns to loaded configuration',async({page})=>{const f=await fixture(page);await expect(region(page)).toContainText('尚未配置阈值');await region(page).getByRole('checkbox',{name:'启用连续来源失败'}).check();await page.locator('details > summary').filter({hasText:/^运行质量与异常$/}).click();await expect(region(page)).toBeVisible();await region(page).getByRole('button',{name:'撤销修改'}).click();await expect(region(page).getByRole('checkbox',{name:'启用连续来源失败'})).not.toBeChecked();expect(f.posts).toHaveLength(0);expect(f.reads()).toBe(1)})
test('CAS conflict preserves local draft until undo and does not repeat writes',async({page})=>{const f=await fixture(page,'conflict');await expect(region(page)).toContainText('尚未配置阈值');await region(page).getByRole('checkbox',{name:'启用排队时间峰值'}).check();await region(page).getByRole('button',{name:'保存规则'}).click();await expect(region(page).getByRole('alert')).toContainText('HTTP 409');await expect(region(page).getByRole('checkbox',{name:'启用排队时间峰值'})).toBeChecked();await expect(region(page).getByRole('button',{name:'查询配置回执'})).toHaveCount(0);expect(f.posts).toHaveLength(1)})
for(const mode of ['private','false-normal','unknown-zero','wrong-window','future-configuration','wrong-kind','bad-evidence','bad-count','fail'])test(`quality alerts ${mode} refuses automatic fallback`,async({page})=>{const f=await fixture(page,mode);await expect(region(page).getByRole('alert')).toContainText(mode==='fail'?'HTTP 503':'不符合契约');await expect(region(page).locator('tbody tr')).toHaveCount(0);await page.waitForTimeout(1000);expect(f.reads()).toBe(1);expect(f.posts).toHaveLength(0)})
for(const mode of ['unavailable','ambiguous'])test(`${mode} remains unavailable without a false normal`,async({page})=>{const f=await fixture(page,mode);await expect(region(page).locator('tbody tr').first()).toContainText('无法评估');await expect(region(page).locator('tbody tr').first()).toContainText('—');expect(f.posts).toHaveLength(0)})
test('permission rejection removes configuration and evidence',async({page})=>{const f=await fixture(page,'forbidden');await expect(region(page)).toHaveCount(0);await expect(page.getByRole('alert')).toContainText('HTTP 403');await page.waitForTimeout(1000);expect(f.reads()).toBe(1);expect(f.posts).toHaveLength(0)})
test('identity clear discards a late threshold response',async({page})=>{let release!:()=>void;const gate=new Promise<void>(r=>release=r);const f=await fixture(page,'configured',gate);await expect(region(page).getByRole('status')).toContainText('正在处理');await page.getByRole('button',{name:'清除开发会话'}).click();release();await expect(region(page)).toHaveCount(0);expect(f.reads()).toBe(1);expect(f.posts).toHaveLength(0)})
