package com.acme.opsweave.platform.workflow;

import com.acme.opsweave.integration.domain.*;
import com.acme.opsweave.integration.infrastructure.*;
import com.acme.opsweave.platform.catalog.CatalogJson;
import java.net.URI;
import java.time.*;
import java.util.*;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

/** Explicit protocol fixture, including real paging requests and malformed upstream replies. */
class ZabbixWorkflowLogWindowTest {
    final Instant from=Instant.parse("2026-10-04T00:00:00Z"),till=from.plusSeconds(60),now=till.plusSeconds(10);
    final WorkflowLogSourcePin pin=ZabbixWorkflowLogReaderTest.PIN;
    class Transport implements ZabbixJsonRpcConnector.Transport {
        int calls,historyCalls,membershipCalls,limit;long begin,end;String method,hostGroupId="91";boolean adaptive=true,changed,changeMembershipAfterHistory;int failHistory=-1;List<String> expectedHostGroups=List.of();
        Duration remaining;List<Map<String,Object>> rows=List.of(row(from,0));final List<Long> starts=new ArrayList<>();final List<Integer> limits=new ArrayList<>();final List<String> requestBodies=new ArrayList<>();
        public String exchangeWithin(URI uri,String body,String token,Duration remaining){this.remaining=remaining;return exchange(uri,body,token);}
        public String exchange(URI uri,String body,String token){assertEquals("Fixture-token",token);var n=CatalogJson.JSON.readTree(body);method=n.get("method").asString();var p=n.get("params");
            if(method.equals("history.get")){assertEquals("1",p.get("itemids").get(0).asString());assertEquals(1,p.get("itemids").size());begin=p.get("time_from").asLong();end=p.get("time_till").asLong();limit=p.get("limit").asInt();assertTrue(begin>=from.getEpochSecond()&&end<till.getEpochSecond()&&end>=begin);assertEquals(2,p.get("history").asInt());assertEquals(8,p.get("output").size());assertEquals("ASC",p.get("sortorder").get(0).asString());assertEquals("ASC",p.get("sortorder").get(1).asString());assertTrue(limit>=1&&limit<=1001);assertFalse(p.has("filter"));starts.add(begin);limits.add(limit);if(++historyCalls==failHistory)throw new IllegalStateException("Fixture page unavailable");}else if(method.equals("item.get")){assertEquals("1",p.get("itemids").get(0).asString());if(!expectedHostGroups.isEmpty())assertEquals(expectedHostGroups,groupIds(body));}else{assertEquals("host.get",method);assertEquals("101",p.get("hostids").get(0).asString());assertEquals(expectedHostGroups,groupIds(body));membershipCalls++;}requestBodies.add(body);calls++;if(method.equals("history.get")&&changeMembershipAfterHistory)hostGroupId="92";return "Fixture";
        }
        public List<Map<String,Object>> readHostArray(String ignored){if(method.equals("history.get"))return adaptive?rows.stream().filter(r->Long.parseLong((String)r.get("clock"))>=begin&&Long.parseLong((String)r.get("clock"))<=end).limit(limit).toList():rows;if(method.equals("host.get"))return List.of(Map.of("hostid","101","groups",List.of(Map.of("groupid",hostGroupId))));var metadata=new HashMap<>(ZabbixWorkflowLogReaderTest.item());if(changed&&calls>1)metadata.put("units","changed");return List.of(metadata);}
    }
    Map<String,Object> row(Instant time,int ns){return Map.of("itemid","1","clock",Long.toString(time.getEpochSecond()),"ns",Integer.toString(ns),"value","  Synthetic Fixture \" emoji 🧵\n<script>  ","timestamp","0","severity","0","source","","logeventid","0");}
    List<Map<String,Object>> read(Transport t){return new ZabbixWorkflowLogReader().readWindow(URI.create("http://127.0.0.1/api_jsonrpc.php"),t,"Fixture-token",pin,from,till,now);}
    List<Map<String,Object>> read(Transport t,List<String> groups){t.expectedHostGroups=groups;return new ZabbixWorkflowLogReader().readWindow(URI.create("http://127.0.0.1/api_jsonrpc.php"),t,"Fixture-token",pin,from,till,now,groups);}
    List<String> groupIds(String body){var ids=CatalogJson.JSON.readTree(body).get("params").get("groupids");var result=new ArrayList<String>();for(var id:ids)result.add(id.asString());return result;}
    @Test void halfOpenEdgesAndEmptyWindowRemainDistinctFromFailure(){var t=new Transport();t.rows=List.of(row(from,0),row(till.minusSeconds(1),999999999));var result=read(t);assertEquals(till.minusNanos(1).toString(),result.getLast().get("timestamp"));assertEquals(t.rows.getFirst().get("value"),result.getFirst().get("body"));assertNull(result.getFirst().get("logEventTime"));assertEquals(3,t.calls);t=new Transport();t.rows=List.of();assertTrue(read(t).isEmpty());assertEquals(3,t.calls);assertTrue(t.remaining.compareTo(Duration.ofSeconds(20))<=0);}
    @Test void aThousandPositionsSurviveBoundarySeconds(){var t=new Transport();t.rows=java.util.stream.IntStream.range(0,1000).mapToObj(i->row(from.plusSeconds(i/20),i%20)).toList();var result=read(t);assertEquals(1000,result.size());assertEquals(10,t.historyCalls);assertEquals(java.util.stream.IntStream.range(0,10).mapToObj(i->from.plusSeconds(i*5).getEpochSecond()).toList(),t.starts);assertEquals(from.plusSeconds(49).plusNanos(19).toString(),result.getLast().get("timestamp"));}
    @Test void denseSecondAndSentinelOverflowNeverSkipNanoseconds(){var t=new Transport();t.rows=java.util.stream.IntStream.range(0,1000).mapToObj(i->row(from,i)).toList();assertEquals(1000,read(t).size());assertEquals(3,t.historyCalls);assertEquals(List.of(101,1001,101),t.limits);var overflow=new Transport();overflow.rows=java.util.stream.IntStream.range(0,1001).mapToObj(i->row(from,i)).toList();var e=assertThrows(WorkflowFailure.class,()->read(overflow));assertEquals(WorkflowFailure.Code.WINDOW_INCOMPLETE,e.code());assertEquals(2,overflow.historyCalls);}
    @Test void malformedOrderDuplicatesForeignScopeAndOversizedBodiesFailClosed(){var cases=new ArrayList<List<Map<String,Object>>>();cases.add(List.of(row(from,0),row(from,0)));cases.add(List.of(row(from,1),row(from,0)));cases.add(List.of(row(till,0)));cases.add(Collections.nCopies(102,row(from,0)));for(var patch:List.of(Map.of("itemid","other"),Map.of("value"," "),Map.of("value","x".repeat(2049)),Map.of("severity","-1"),Map.of("ns","1000000000"),Map.of("logeventid","4294967296"),Map.of("timestamp",Long.toString(Long.MAX_VALUE)))){var value=new HashMap<>(row(from,0));value.putAll(patch);cases.add(List.of(value));}for(var rows:cases){var t=new Transport();t.adaptive=false;t.rows=rows;assertEquals(WorkflowFailure.Code.INVALID_SAMPLE,assertThrows(WorkflowFailure.class,()->read(t)).code());}}
    @Test void changedMetadataAndUnsettledWindowsCannotReturnRecords(){var t=new Transport();t.changed=true;assertEquals(WorkflowFailure.Code.SOURCE_CHANGED,assertThrows(WorkflowFailure.class,()->read(t)).code());var early=new Transport();assertThrows(WorkflowFailure.class,()->new ZabbixWorkflowLogReader().readWindow(URI.create("http://127.0.0.1/api_jsonrpc.php"),early,"Fixture-token",pin,from,till,now.minusSeconds(1)));assertEquals(0,early.calls);}
    @Test void scopedWindowChecksMembershipBeforeAndAfterHistoryAndRejectsDrift(){var t=new Transport();assertEquals(1,read(t,List.of("91")).size());assertEquals(1,t.historyCalls);assertEquals(2,t.membershipCalls);assertEquals(5,t.calls);assertTrue(t.requestBodies.stream().filter(body->CatalogJson.JSON.readTree(body).get("method").asString().equals("item.get")).allMatch(body->groupIds(body).equals(List.of("91"))));t=new Transport();t.hostGroupId="92";var outside=t;assertEquals(WorkflowFailure.Code.SOURCE_UNAVAILABLE,assertThrows(WorkflowFailure.class,()->read(outside,List.of("91"))).code());assertEquals(0,outside.historyCalls);assertEquals(1,outside.membershipCalls);t=new Transport();t.changeMembershipAfterHistory=true;var changed=t;assertEquals(WorkflowFailure.Code.SOURCE_UNAVAILABLE,assertThrows(WorkflowFailure.class,()->read(changed,List.of("91"))).code());assertEquals(1,changed.historyCalls);assertEquals(2,changed.membershipCalls);}
    @Test void pageFailuresAndSharedDeadlineDiscardThePrefix(){var t=new Transport();t.rows=java.util.stream.IntStream.range(0,201).mapToObj(i->row(from.plusSeconds(i/10),i%10)).toList();t.failHistory=2;assertEquals(WorkflowFailure.Code.SOURCE_UNAVAILABLE,assertThrows(WorkflowFailure.class,()->read(t)).code());var ticks=new java.util.concurrent.atomic.AtomicLong();var slow=new Transport(){public String exchange(URI uri,String body,String token){var r=super.exchange(uri,body,token);if(method.equals("history.get"))ticks.addAndGet(20_000_000_000L);return r;}};assertEquals(WorkflowFailure.Code.WINDOW_INCOMPLETE,assertThrows(WorkflowFailure.class,()->new ZabbixWorkflowLogReader(ticks::get).readWindow(URI.create("http://127.0.0.1/api_jsonrpc.php"),slow,"Fixture-token",pin,from,till,now)).code());assertEquals(2,slow.calls);}
    @Test void responseParsingSharesTheSameReadDeadline(){var ticks=new java.util.concurrent.atomic.AtomicLong();var slow=new Transport(){public List<Map<String,Object>> readHostArray(String body){var rows=super.readHostArray(body);ticks.addAndGet(20_000_000_000L);return rows;}};assertEquals(WorkflowFailure.Code.WINDOW_INCOMPLETE,assertThrows(WorkflowFailure.class,()->new ZabbixWorkflowLogReader(ticks::get).readWindow(URI.create("http://127.0.0.1/api_jsonrpc.php"),slow,"Fixture-token",pin,from,till,now)).code());assertEquals(1,slow.calls);assertEquals(0,slow.historyCalls);}
}
