package com.acme.opsweave.platform.workflow;

import com.acme.opsweave.integration.domain.*;
import com.acme.opsweave.integration.infrastructure.*;
import com.acme.opsweave.platform.catalog.CatalogJson;
import java.net.URI;
import java.time.*;
import java.util.*;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

/** Untrusted protocol fixtures; real provider and storage are checked separately. */
class ZabbixWorkflowLogReaderTest {
 static final Instant NOW=Instant.parse("2026-10-04T00:00:00Z");
 static final UUID INSPECTION=UUID.fromString("10000000-0000-4000-8000-000000000122");
 static final WorkflowLogSourcePin PIN=new WorkflowLogSourcePin(INSPECTION,"1","101","log[/var/log/fixture.log]","","LOG",WorkflowLogSourcePin.digest(INSPECTION,"1","101","log[/var/log/fixture.log]","","LOG"));
 static Map<String,Object> item(){return Map.of("itemid","1","hostid","101","key_",PIN.sourceKey(),"units","","value_type","2","lastvalue","private-fixture");}
 static Map<String,Object> value(int seconds){return Map.of("itemid","1","clock",String.valueOf(NOW.getEpochSecond()-seconds),"ns","3","value","  Fixture <script>body</script>\n  ","timestamp","0","severity","0","source","","logeventid","0");}
 static class Transport implements ZabbixJsonRpcConnector.Transport {
  List<Map<String,Object>> first=List.of(item()),last=first,history=List.of(value(1));int calls;String method;boolean down;Duration remaining;
  public String exchangeWithin(URI uri,String body,String token,Duration remaining){this.remaining=remaining;return exchange(uri,body,token);}
  public String exchange(URI uri,String body,String token){assertEquals("fixture-token",token);if(down)throw new IllegalStateException("private-fixture");var n=CatalogJson.JSON.readTree(body);method=n.get("method").asString();var p=n.get("params");assertEquals("1",p.get("itemids").get(0).asString());assertEquals(1,p.get("itemids").size());
   if(method.equals("history.get")){assertEquals(2,p.get("history").asInt());assertEquals(6,p.get("limit").asInt());assertEquals(NOW.getEpochSecond()-600,p.get("time_from").asLong());assertEquals(NOW.getEpochSecond(),p.get("time_till").asLong());assertEquals("DESC",p.get("sortorder").get(0).asString());assertEquals(8,p.get("output").size());assertFalse(p.has("filter"));}else{assertEquals("item.get",method);assertEquals(2,p.get("limit").asInt());assertEquals(5,p.get("output").size());}calls++;return "fixture";}
  public List<Map<String,Object>> readHostArray(String ignored){return method.equals("history.get")?history:calls==1?first:last;}
 }
 static final class ScopedTransport extends Transport {
  String hostGroupId="91";
  @Override public String exchange(URI uri,String body,String token){var request=CatalogJson.JSON.readTree(body);if(request.get("method").asString().equals("host.get")){var p=request.get("params");assertEquals("101",p.get("hostids").get(0).asString());assertEquals("91",p.get("groupids").get(0).asString());assertTrue(p.has("selectGroups"));calls++;return "groups";}return super.exchange(uri,body,token);}
  @Override public List<Map<String,Object>> readHostArray(String body){return body.equals("groups")?List.of(Map.of("hostid","101","groups",List.of(Map.of("groupid",hostGroupId)))):super.readHostArray(body);}
 }
 static com.acme.opsweave.integration.application.WorkflowService.Batch read(Transport t){return new ZabbixWorkflowLogReader().read(URI.create("http://127.0.0.1/api_jsonrpc.php"),t,"fixture-token",PIN,NOW);}
 @Test void exactBodyAndMissingContextSurviveLatestSampleSelection(){var t=new Transport();t.history=java.util.stream.IntStream.rangeClosed(1,6).mapToObj(ZabbixWorkflowLogReaderTest::value).toList();var b=read(t);assertEquals(3,t.calls);assertEquals(5,b.records().size());assertEquals(6,b.retainedCount());assertTrue(b.truncated());var row=b.records().getFirst();assertEquals(value(1).get("value"),row.get("body"));assertEquals(NOW.minusSeconds(5).plusNanos(3).toString(),row.get("timestamp"));assertNull(row.get("logEventTime"));assertNull(row.get("eventSource"));assertEquals("0",row.get("severityCode"));assertFalse(row.containsKey("severityText"));assertFalse(row.containsKey("serviceName"));assertFalse(row.containsKey("lastvalue"));assertTrue(t.remaining.compareTo(Duration.ofSeconds(20))<=0);}
 @Test void rawEventFieldsAreSeparateFromCollectionTime(){var t=new Transport();var row=new HashMap<>(value(1));row.put("timestamp",String.valueOf(NOW.minusSeconds(3600).getEpochSecond()));row.put("severity","4");row.put("source","Fixture source");row.put("logeventid","4294967295");t.history=List.of(row);var b=read(t).records().getFirst();assertEquals(NOW.minusSeconds(3600).toString(),b.get("logEventTime"));assertEquals(NOW.minusSeconds(1).plusNanos(3).toString(),b.get("timestamp"));assertEquals("4",b.get("severityCode"));assertEquals("Fixture source",b.get("eventSource"));assertEquals("4294967295",b.get("eventId"));}
 @Test void semanticChangesOnEitherMetadataCheckStopTheRead(){for(String key:List.of("itemid","hostid","key_","units","value_type")){var changed=new HashMap<>(item());changed.put(key,"changed");for(boolean before:List.of(true,false)){var t=new Transport();if(before)t.first=List.of(changed);else t.last=List.of(changed);assertEquals(WorkflowFailure.Code.SOURCE_CHANGED,assertThrows(WorkflowFailure.class,()->read(t)).code());assertEquals(before?1:3,t.calls);}}}
 @Test void malformedAndOverBudgetBodiesAreNeverTruncatedOrFalseEmpty(){var cases=new ArrayList<List<Map<String,Object>>>();cases.add(List.of());cases.add(Collections.nCopies(7,value(1)));cases.add(List.of(value(1),value(1)));cases.add(List.of(value(2),value(1)));cases.add(List.of(value(601)));cases.add(List.of(value(-1)));for(var patch:List.of(Map.of("value"," "),Map.of("value","x".repeat(2049)),Map.of("ns","1000000000"),Map.of("itemid","2"),Map.of("timestamp",String.valueOf(NOW.plusSeconds(1).getEpochSecond())),Map.of("source","x\n"),Map.of("logeventid","4294967296"),Map.of("severity","-1"))){var row=new HashMap<>(value(1));row.putAll(patch);cases.add(List.of(row));}for(var rows:cases){var t=new Transport();t.history=rows;assertEquals(WorkflowFailure.Code.INVALID_SAMPLE,assertThrows(WorkflowFailure.class,()->read(t)).code());assertEquals(2,t.calls);}}
 @Test void transportAndElapsedBudgetsHaveStableErrorsWithoutPrivateText(){var t=new Transport();t.down=true;var e=assertThrows(WorkflowFailure.class,()->read(t));assertEquals("SOURCE_UNAVAILABLE",e.getMessage());assertNull(e.getCause());var ticks=new java.util.concurrent.atomic.AtomicInteger();var reader=new ZabbixWorkflowLogReader(()->ticks.getAndIncrement()*Duration.ofSeconds(21).toNanos());var fresh=new Transport();assertEquals(WorkflowFailure.Code.SOURCE_UNAVAILABLE,assertThrows(WorkflowFailure.class,()->reader.read(URI.create("http://127.0.0.1/api_jsonrpc.php"),fresh,"fixture-token",PIN,NOW)).code());assertEquals(0,fresh.calls);}
 @Test void closedJsonSourceRoundTripsAndRejectsUntrustedProperties(){var source=new WorkflowDefinition.Source("ZABBIX_LOG","fixture-source",new WorkflowDefinition.ConfigurationPin(UUID.randomUUID(),1,"sha256:"+"a".repeat(64)),null,PIN);var node=CatalogJson.JSON.valueToTree(WorkflowJson.wire(source));assertEquals(source,WorkflowJson.source(node));var bad=CatalogJson.JSON.readTree(CatalogJson.JSON.writeValueAsString(node).replace("\"kind\":","\"tenantId\":\"forged\",\"kind\":"));assertThrows(IllegalArgumentException.class,()->WorkflowJson.source(bad));}
 @Test void configuredGroupIsCheckedBeforeAndAfterLogRead(){var t=new ScopedTransport();var r=new ZabbixWorkflowLogReader().read(URI.create("http://127.0.0.1/api_jsonrpc.php"),t,"fixture-token",PIN,NOW,List.of("91"));assertEquals(5,t.calls);assertEquals(1,r.records().size());t=new ScopedTransport();t.hostGroupId="92";var outside=t;assertEquals(WorkflowFailure.Code.SOURCE_UNAVAILABLE,assertThrows(WorkflowFailure.class,()->new ZabbixWorkflowLogReader().read(URI.create("http://127.0.0.1/api_jsonrpc.php"),outside,"fixture-token",PIN,NOW,List.of("91"))).code());assertEquals(2,outside.calls);}
}
