package com.acme.opsweave.platform.workflow;

import com.acme.opsweave.integration.domain.*;
import com.acme.opsweave.integration.infrastructure.*;
import com.acme.opsweave.platform.catalog.CatalogJson;
import java.net.URI;
import java.time.Instant;
import java.util.*;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

/** Explicit protocol fixture; actual request boundaries and untrusted responses. */
class ZabbixWorkflowMetricWindowTest {
    final Instant from=Instant.parse("2026-10-04T00:00:00Z"),till=from.plusSeconds(60),now=till.plusSeconds(10);
    final WorkflowMetricSourcePin pin=ZabbixWorkflowMetricReaderTest.source("FLOAT");
    class Transport implements ZabbixJsonRpcConnector.Transport {
        int calls,historyCalls,membershipCalls;long begin,end;int limit;String method,hostGroupId="91";List<Map<String,Object>> rows=List.of(row(from,"0","12.5"));boolean changed,adaptive,changeMembershipAfterHistory;int failHistory=-1;List<String> expectedHostGroups=List.of();final List<Long> starts=new ArrayList<>();final List<String> requestBodies=new ArrayList<>();
        public String exchange(URI uri,String body,String token){var n=CatalogJson.JSON.readTree(body);method=n.get("method").asString();var p=n.get("params");if(method.equals("history.get")){assertEquals("1",p.get("itemids").get(0).asString());begin=p.get("time_from").asLong();end=p.get("time_till").asLong();limit=p.get("limit").asInt();assertTrue(begin>=from.getEpochSecond()&&end<till.getEpochSecond()&&end>=begin);assertEquals("ASC",p.get("sortorder").get(0).asString());assertTrue(limit>=1&&limit<=601);starts.add(begin);if(++historyCalls==failHistory)throw new IllegalStateException("Fixture page unavailable");}else if(method.equals("item.get")){assertEquals("1",p.get("itemids").get(0).asString());if(!expectedHostGroups.isEmpty())assertEquals(expectedHostGroups,groupIds(body));}else{assertEquals("host.get",method);assertEquals("101",p.get("hostids").get(0).asString());assertEquals(expectedHostGroups,groupIds(body));membershipCalls++;}requestBodies.add(body);calls++;if(method.equals("history.get")&&changeMembershipAfterHistory)hostGroupId="92";return "Fixture";}
        public List<Map<String,Object>> readHostArray(String body){if(method.equals("history.get"))return adaptive?rows.stream().filter(r->Long.parseLong((String)r.get("clock"))>=begin&&Long.parseLong((String)r.get("clock"))<=end).limit(limit).toList():rows;if(method.equals("host.get"))return List.of(Map.of("hostid","101","groups",List.of(Map.of("groupid",hostGroupId))));var meta=new HashMap<>(ZabbixWorkflowMetricReaderTest.item());if(changed&&calls>=3)meta.put("units","changed");return List.of(meta);}
        public String readText(String body){throw new AssertionError();}
    }
    Map<String,Object> row(Instant time,String ns,String value){return Map.of("itemid","1","clock",Long.toString(time.getEpochSecond()),"ns",ns,"value",value);}
    List<Map<String,Object>> read(Transport t){return new ZabbixWorkflowMetricReader().readWindow(URI.create("http://127.0.0.1/api_jsonrpc.php"),t,"Fixture-token",pin,from,till,now);}
    List<Map<String,Object>> read(Transport t,List<String> groups){t.expectedHostGroups=groups;return new ZabbixWorkflowMetricReader().readWindow(URI.create("http://127.0.0.1/api_jsonrpc.php"),t,"Fixture-token",pin,from,till,now,WorkflowMetricStream.MAX_POINTS,groups);}
    List<String> groupIds(String body){var ids=CatalogJson.JSON.readTree(body).get("params").get("groupids");var result=new ArrayList<String>();for(var id:ids)result.add(id.asString());return result;}
    @Test void independentlyNarrowedReplayBudgetUsesOnlyItsSentinelAndNeverReturnsAPrefix(){var t=new Transport();t.adaptive=true;t.rows=java.util.stream.IntStream.range(0,60).mapToObj(i->row(from,Integer.toString(i*1_000_000),"12.5")).toList();assertEquals(60,new ZabbixWorkflowMetricReader().readWindow(URI.create("http://127.0.0.1/api_jsonrpc.php"),t,"Fixture-token",pin,from,till,now,60).size());assertEquals(61,t.limit);t.rows=java.util.stream.IntStream.range(0,61).mapToObj(i->row(from,Integer.toString(i*1_000_000),"12.5")).toList();assertEquals(WorkflowFailure.Code.WINDOW_INCOMPLETE,assertThrows(WorkflowFailure.class,()->new ZabbixWorkflowMetricReader().readWindow(URI.create("http://127.0.0.1/api_jsonrpc.php"),t,"Fixture-token",pin,from,till,now,60)).code());assertEquals(61,t.limit);}
    @Test void replayCannotEnlargeTheSharedPointBudget(){var t=new Transport();for(var budget:List.of(0,601))assertThrows(IllegalArgumentException.class,()->new ZabbixWorkflowMetricReader().readWindow(URI.create("http://127.0.0.1/api_jsonrpc.php"),t,"Fixture-token",pin,from,till,now,budget));assertEquals(0,t.calls);}
    @Test void exactHalfOpenWindowIncludesNanosecondEdgesAndHealthyEmpty(){var t=new Transport();t.rows=List.of(row(from,"0","12.5"),row(till.minusSeconds(1),"999999999","15"));var values=read(t);assertEquals(2,values.size());assertEquals(till.minusNanos(1).toString(),values.getLast().get("timestamp"));assertEquals("12.5",values.getFirst().get("value"));assertEquals(3,t.calls);t=new Transport();t.rows=List.of();assertTrue(read(t).isEmpty());assertEquals(3,t.calls);}
    @Test void overflowForeignItemsOrderDuplicatesAndOutsideWindowsNeverBecomeComplete(){var foreign=new HashMap<>(row(from,"0","1"));foreign.put("itemid","other");for(var rows:List.of(Collections.nCopies(61,row(from,"0","1")),List.of(row(till,"0","1")),List.of(row(from.minusSeconds(1),"999999999","1")),List.of(row(from,"0","1"),row(from,"0","1")),List.of(row(from.plusSeconds(1),"0","1"),row(from,"0","1")),List.<Map<String,Object>>of(foreign),List.of(row(from,"0","NaN")))){var t=new Transport();t.rows=rows;assertEquals(WorkflowFailure.Code.INVALID_SAMPLE,assertThrows(WorkflowFailure.class,()->read(t)).code());}}
    @Test void driftAndUnsettledWindowsFailBeforeCheckpoint(){var t=new Transport();t.changed=true;assertEquals(WorkflowFailure.Code.SOURCE_CHANGED,assertThrows(WorkflowFailure.class,()->read(t)).code());var fresh=new Transport();assertThrows(WorkflowFailure.class,()->new ZabbixWorkflowMetricReader().readWindow(URI.create("http://127.0.0.1/api_jsonrpc.php"),fresh,"Fixture-token",pin,from,till,now.minusSeconds(1)));assertEquals(0,fresh.calls);}
    @Test void scopedWindowChecksMembershipBeforeAndAfterHistoryAndRejectsDrift(){var t=new Transport();assertEquals(1,read(t,List.of("91")).size());assertEquals(1,t.historyCalls);assertEquals(2,t.membershipCalls);assertEquals(5,t.calls);assertTrue(t.requestBodies.stream().filter(body->CatalogJson.JSON.readTree(body).get("method").asString().equals("item.get")).allMatch(body->groupIds(body).equals(List.of("91"))));t=new Transport();t.hostGroupId="92";var outside=t;assertEquals(WorkflowFailure.Code.SOURCE_UNAVAILABLE,assertThrows(WorkflowFailure.class,()->read(outside,List.of("91"))).code());assertEquals(0,outside.historyCalls);assertEquals(1,outside.membershipCalls);t=new Transport();t.changeMembershipAfterHistory=true;var changed=t;assertEquals(WorkflowFailure.Code.SOURCE_UNAVAILABLE,assertThrows(WorkflowFailure.class,()->read(changed,List.of("91"))).code());assertEquals(1,changed.historyCalls);assertEquals(2,changed.membershipCalls);}
    @Test void completeSixHundredPointsReplayEntireBoundarySecondWithoutLosingNanoseconds(){var t=new Transport();t.adaptive=true;t.rows=java.util.stream.IntStream.range(0,600).mapToObj(i->row(from.plusSeconds(i/10),Integer.toString(i%10*1_000_000),"12.5")).toList();var result=read(t);assertEquals(600,result.size());assertEquals(6,t.historyCalls);assertEquals(List.of(0L,10L,20L,30L,40L,50L),t.starts.stream().map(x->x-from.getEpochSecond()).toList());assertEquals(from.plusSeconds(59).plusMillis(9).toString(),result.getLast().get("timestamp"));}
    @Test void aDenseSecondIsReadCompletelyWithinTheRemainingPointBudget(){var t=new Transport();t.adaptive=true;t.rows=java.util.stream.IntStream.range(0,600).mapToObj(i->row(from,Integer.toString(i*1_000_000),"12.5")).toList();assertEquals(600,read(t).size());assertEquals(3,t.historyCalls);t.rows=java.util.stream.IntStream.range(0,601).mapToObj(i->row(from,Integer.toString(i*1_000_000),"12.5")).toList();assertEquals(WorkflowFailure.Code.WINDOW_INCOMPLETE,assertThrows(WorkflowFailure.class,()->read(t)).code());}
    @Test void partialPagingAndWholeReadDeadlineNeverReturnASuccessfulPrefix(){var t=new Transport();t.adaptive=true;t.rows=java.util.stream.IntStream.range(0,201).mapToObj(i->row(from.plusSeconds(i/10),Integer.toString(i%10*1_000_000),"12.5")).toList();t.failHistory=2;assertEquals(WorkflowFailure.Code.SOURCE_UNAVAILABLE,assertThrows(WorkflowFailure.class,()->read(t)).code());var ticks=new java.util.concurrent.atomic.AtomicLong();var slow=new Transport(){public String exchange(URI uri,String body,String token){var result=super.exchange(uri,body,token);if(method.equals("history.get"))ticks.addAndGet(20_000_000_000L);return result;}};assertEquals(WorkflowFailure.Code.WINDOW_INCOMPLETE,assertThrows(WorkflowFailure.class,()->new ZabbixWorkflowMetricReader(ticks::get).readWindow(URI.create("http://127.0.0.1/api_jsonrpc.php"),slow,"Fixture-token",pin,from,till,now)).code());assertEquals(2,slow.calls);}
}
