package com.acme.opsweave.platform.workflow;
import com.acme.opsweave.integration.domain.*;
import com.acme.opsweave.integration.api.WorkflowStore.*;
import com.acme.opsweave.platform.catalog.CatalogJson;
import tools.jackson.databind.JsonNode;
import java.time.Instant;
import java.util.*;
import static com.acme.opsweave.platform.integration.PipelineJson.*;

public final class WorkflowJson {
 private WorkflowJson() {}
 public static WorkflowDefinition definition(JsonNode n) {
  fields(n,Set.of("schemaVersion","id","revision","name","source","target","nodes","edges"));if(!text(n,"schemaVersion").equals("2.0"))throw new IllegalArgumentException();
  var s=n.get("source");var t=n.get("target");
  var nodes=new ArrayList<WorkflowDefinition.Node>();var edges=new ArrayList<WorkflowDefinition.Edge>();
  if(n.get("nodes")==null||!n.get("nodes").isArray()||n.get("nodes").size()>16||n.get("edges")==null||!n.get("edges").isArray()||n.get("edges").size()>32)throw new IllegalArgumentException();
  for(var v:n.get("nodes")){fields(v,Set.of("id","type","version","config","operatorDigest"));var config=new LinkedHashMap<String,String>();var c=v.get("config");if(c==null||!c.isObject()||c.size()>32)throw new IllegalArgumentException();for(var e:c.properties()){if(!e.getValue().isString())throw new IllegalArgumentException();config.put(e.getKey(),e.getValue().asString());}nodes.add(new WorkflowDefinition.Node(text(v,"id"),WorkflowDefinition.Type.valueOf(text(v,"type")),text(v,"version"),config,v.has("operatorDigest")?text(v,"operatorDigest"):null));}
  for(var e:n.get("edges")){fields(e,Set.of("from","to"));edges.add(new WorkflowDefinition.Edge(text(e,"from"),text(e,"to")));}
  var d=new WorkflowDefinition(text(n,"id"),integer(n,"revision",null),text(n,"name"),source(s),target(t),nodes,edges);
  if(CatalogJson.JSON.writeValueAsBytes(wire(d)).length>16384)throw new IllegalArgumentException();return d;
 }
 public static WorkflowDefinition.Target target(JsonNode n){if(n!=null&&n.has("kind")){if(n.has("mappingPin")){fields(n,Set.of("kind","schemaVersion","metricKey","mappingPin"));if(!text(n,"schemaVersion").equals("1.1"))throw new IllegalArgumentException();var pin=com.acme.opsweave.platform.telemetry.MetricMappingJson.pin(n.get("mappingPin"));if(pin==null)throw new IllegalArgumentException();return new WorkflowDefinition.Target(null,1,null,text(n,"kind"),pin,text(n,"metricKey"));}fields(n,Set.of("kind","schemaVersion"));if(!text(n,"schemaVersion").equals("1.0"))throw new IllegalArgumentException();return new WorkflowDefinition.Target(null,1,null,text(n,"kind"));}fields(n,Set.of("id","revision","digest"));return new WorkflowDefinition.Target(text(n,"id"),integer(n,"revision",null),text(n,"digest"));}
 public static Map<String,Object> wire(WorkflowDefinition.Target t){return t.entity()?Map.of("id",t.id(),"revision",t.revision(),"digest",t.digest()):t.mappingPin()!=null?Map.of("kind",t.kind(),"schemaVersion","1.1","metricKey",t.metricKey(),"mappingPin",com.acme.opsweave.platform.telemetry.MetricMappingJson.pin(t.mappingPin())):Map.of("kind",t.kind(),"schemaVersion","1.0");}
 public static WorkflowDefinition.Source source(JsonNode n){fields(n,Set.of("kind","instanceId","configuration","metric","log"));WorkflowDefinition.ConfigurationPin pin=null;if(n.has("configuration")){var c=n.get("configuration");fields(c,Set.of("sourceId","revision","digest"));String id=text(c,"sourceId");if(!id.matches("[a-f0-9]{8}(-[a-f0-9]{4}){3}-[a-f0-9]{12}"))throw new IllegalArgumentException();pin=new WorkflowDefinition.ConfigurationPin(UUID.fromString(id),integer(c,"revision",null),text(c,"digest"));}WorkflowMetricSourcePin metric=null;if(n.has("metric")){var m=n.get("metric");fields(m,Set.of("inspectionId","itemId","hostId","sourceKey","sourceUnit","sourceValueType","digest"));metric=new WorkflowMetricSourcePin(SourceConnectionJson.uuid(m,"inspectionId"),text(m,"itemId"),text(m,"hostId"),text(m,"sourceKey"),emptyText(m,"sourceUnit"),text(m,"sourceValueType"),text(m,"digest"));}WorkflowLogSourcePin log=null;if(n.has("log")){var m=n.get("log");fields(m,Set.of("inspectionId","itemId","hostId","sourceKey","sourceUnit","sourceValueType","digest"));log=new WorkflowLogSourcePin(SourceConnectionJson.uuid(m,"inspectionId"),text(m,"itemId"),text(m,"hostId"),text(m,"sourceKey"),emptyText(m,"sourceUnit"),text(m,"sourceValueType"),text(m,"digest"));}return new WorkflowDefinition.Source(text(n,"kind"),text(n,"instanceId"),pin,metric,log);}
 private static String emptyText(JsonNode n,String key){var value=n.get(key);if(value==null||!value.isString())throw new IllegalArgumentException();return value.asString();}
 public static Map<String,Object> wire(WorkflowDefinition.Source s){var v=new LinkedHashMap<String,Object>();v.put("kind",s.kind());v.put("instanceId",s.instanceId());if(s.configuration()!=null)v.put("configuration",s.configuration());if(s.metric()!=null)v.put("metric",s.metric());if(s.log()!=null)v.put("log",s.log());return v;}
 public static Map<String,Object> wire(WorkflowDefinition d){return Map.of("schemaVersion","2.0","id",d.id(),"revision",d.revision(),"name",d.name(),"source",wire(d.source()),"target",wire(d.target()),"nodes",d.nodes().stream().map(WorkflowJson::wire).toList(),"edges",d.edges());}
 public static Map<String,Object> wire(WorkflowDefinition.Node n){var v=new LinkedHashMap<String,Object>();v.put("id",n.id());v.put("type",n.type());v.put("version",n.version());v.put("config",n.config());if(n.operatorDigest()!=null)v.put("operatorDigest",n.operatorDigest());return v;}
 public static Map<String,Object> operatorCatalog(){var registry=WorkflowOperators.builtIn();return Map.of("schemaVersion","2.0","catalogVersion",registry.catalogVersion(),"digest",registry.catalogDigest(),"operators",registry.descriptors());}
 public static Map<String,Position> layout(JsonNode n){if(n==null||!n.isObject()||n.size()>16)throw new IllegalArgumentException();var positions=new LinkedHashMap<String,Position>();for(var e:n.properties()){fields(e.getValue(),Set.of("x","y"));positions.put(e.getKey(),new Position(integer(e.getValue(),"x",null),integer(e.getValue(),"y",null)));}return positions;}
 public static Map<String,Object> wire(Entry e){var v=new LinkedHashMap<String,Object>();v.put("definition",wire(e.definition()));v.put("digest",e.digest());v.put("state",e.state());v.put("editVersion",e.editVersion());v.put("layout",e.layout());v.put("updatedAt",e.updatedAt().toString());v.put("preview",e.preview());return v;}
 public static String encode(Entry e){return CatalogJson.JSON.writeValueAsString(wire(e));}
 public static Entry decode(String json){var n=CatalogJson.JSON.readTree(json);fields(n,Set.of("definition","digest","state","editVersion","layout","updatedAt","preview"));return new Entry(definition(n.get("definition")),text(n,"digest"),text(n,"state"),integer(n,"editVersion",null),layout(n.get("layout")),Instant.parse(text(n,"updatedAt")),n.get("preview").isNull()?null:receipt(n.get("preview")));}
 public static Receipt receipt(JsonNode n){fields(n,Set.of("id","digest","inputDigest","origin","accepted","rejected","filtered","createdAt"));return new Receipt(UUID.fromString(text(n,"id")),text(n,"digest"),text(n,"inputDigest"),text(n,"origin"),integer(n,"accepted",null),integer(n,"rejected",null),integer(n,"filtered",null),Instant.parse(text(n,"createdAt")));}
 public static Map<String,Object> summary(Run r){return Map.of("workflowId",r.workflowId(),"revision",r.revision(),"mode",r.mode(),"receipt",r.receipt());}
 public static Object detail(Run r){var result=new LinkedHashMap<String,Object>();result.put("schemaVersion","2.0");result.put("run",summary(r));result.put("trace",wire(r.trace()));return result;}
 public static Object wire(WorkflowTrace t){if(t==null)return null;var v=new LinkedHashMap<String,Object>();v.put("source",wire(t.source()));v.put("target",wire(t.target()));v.put("syncRunId",t.syncRunId());v.put("startedAt",t.startedAt().toString());v.put("durationMillis",t.durationMillis());v.put("retainedCount",t.retainedCount());v.put("missingRaw",t.missingRaw());v.put("truncated",t.truncated());v.put("sourceStatus",t.sourceStatus());v.put("dryRun",t.dryRun());v.put("writesPerformed",t.writesPerformed());v.put("rows",t.rows());return v;}
 public static String encodeRun(Run r){var v=new LinkedHashMap<String,Object>(summary(r));v.put("trace",wire(r.trace()));return CatalogJson.JSON.writeValueAsString(v);}
 public static Run run(String json){var n=CatalogJson.JSON.readTree(json);fields(n,Set.of("workflowId","revision","mode","receipt","trace"));return new Run(text(n,"workflowId"),integer(n,"revision",null),text(n,"mode"),receipt(n.get("receipt")),n.has("trace")&&!n.get("trace").isNull()?trace(n.get("trace")):null);}
 private static long nonnegative(JsonNode n,String key){var v=n.get(key);if(v==null||!v.isIntegralNumber()||!v.canConvertToLong()||v.asLong()<0||v.asLong()>9007199254740991L)throw new IllegalArgumentException();return v.asLong();}
 private static boolean bool(JsonNode n,String key){var v=n.get(key);if(v==null||!v.isBoolean())throw new IllegalArgumentException();return v.asBoolean();}
 private static WorkflowTrace trace(JsonNode n){
  fields(n,Set.of("source","target","syncRunId","startedAt","durationMillis","retainedCount","missingRaw","truncated","sourceStatus","dryRun","writesPerformed","rows"));
  var source=n.get("source");var target=n.get("target");
  var rows=new ArrayList<WorkflowTrace.Row>();var raw=n.get("rows");if(raw==null||!raw.isArray()||raw.size()>5)throw new IllegalArgumentException();
  for(var row:raw){fields(row,Set.of("index","status","steps"));var steps=new ArrayList<WorkflowTrace.Step>();var rawSteps=row.get("steps");if(rawSteps==null||!rawSteps.isArray()||rawSteps.size()>16)throw new IllegalArgumentException();
   for(var step:rawSteps){fields(step,Set.of("nodeId","type","status","issues"));var issues=new ArrayList<com.acme.opsweave.catalog.domain.ModelPreview.Issue>();var rawIssues=step.get("issues");if(rawIssues==null||!rawIssues.isArray()||rawIssues.size()>64)throw new IllegalArgumentException();for(var issue:rawIssues){fields(issue,Set.of("field","code"));issues.add(new com.acme.opsweave.catalog.domain.ModelPreview.Issue(text(issue,"field"),text(issue,"code")));}steps.add(new WorkflowTrace.Step(text(step,"nodeId"),WorkflowDefinition.Type.valueOf(text(step,"type")),text(step,"status"),issues));}
   rows.add(new WorkflowTrace.Row(integer(row,"index",null),text(row,"status"),steps));
  }
  if(!n.has("syncRunId"))throw new IllegalArgumentException();return new WorkflowTrace(source(source),target(target),n.get("syncRunId").isNull()?null:UUID.fromString(text(n,"syncRunId")),Instant.parse(text(n,"startedAt")),nonnegative(n,"durationMillis"),nonnegative(n,"retainedCount"),nonnegative(n,"missingRaw"),bool(n,"truncated"),text(n,"sourceStatus"),bool(n,"dryRun"),bool(n,"writesPerformed"),rows);
 }
 public static List<Map<String,Object>> samples(JsonNode n){if(n==null||!n.isArray()||n.isEmpty()||n.size()>5)throw new IllegalArgumentException();var values=new ArrayList<Map<String,Object>>();for(var s:n){var v=CatalogJson.sample(s);WorkflowEvaluation.bounded(v);values.add(v);}return values;}
}
