package com.acme.opsweave.integration.domain;
import java.time.Instant;
import java.util.*;

/** Immutable low-volume proofs. Text appears only in the authorized business log port. */
public final class WorkflowLogOutput {
 private WorkflowLogOutput(){}
 public record SourceCommand(UUID requestId,String id,int revision,String digest){
  public SourceCommand{Objects.requireNonNull(requestId);WorkflowDefinition.ref(id,revision);WorkflowDefinition.checkDigest(digest);}
  public String commandDigest(){return WorkflowDefinition.hash(List.of("workflow-log-source-command-v1",id,Integer.toString(revision),digest));}
 }
 public record Command(UUID requestId,String id,int revision,String digest,UUID previewId,List<Map<String,Object>> samples){
  public Command{Objects.requireNonNull(requestId);Objects.requireNonNull(previewId);WorkflowDefinition.ref(id,revision);WorkflowDefinition.checkDigest(digest);samples=samples.stream().map(row->Collections.unmodifiableMap(new LinkedHashMap<>(row))).toList();if(samples.isEmpty()||samples.size()>5)throw new IllegalArgumentException();for(var row:samples){if(row.isEmpty()||row.size()>32)throw new IllegalArgumentException();for(var e:row.entrySet()){if(e.getKey()==null||e.getKey().isBlank()||e.getKey().length()>128||e.getValue()!=null&&!(e.getValue() instanceof String)&&!(e.getValue() instanceof Number)&&!(e.getValue() instanceof Boolean)||e.getValue() instanceof String text&&text.length()>2048||e.getValue() instanceof Number number&&(!Double.isFinite(number.doubleValue())||Math.abs(number.doubleValue())>9007199254740991d))throw new IllegalArgumentException();}}}
  public String commandDigest(){var parts=new ArrayList<String>(List.of("workflow-log-command-v1",id,Integer.toString(revision),digest,previewId.toString()));for(var row:samples){parts.add("record");row.entrySet().stream().sorted(Map.Entry.comparingByKey()).forEach(e->{parts.add(e.getKey());parts.add(e.getValue()==null?"null":e.getValue() instanceof Number?"number":e.getValue() instanceof Boolean?"boolean":"text");parts.add(e.getValue() instanceof Number number?numberText(number):Objects.toString(e.getValue(),""));});}return WorkflowDefinition.hash(parts);}
 }
 public static String numberText(Number value){var decimal=new java.math.BigDecimal(value.toString()).stripTrailingZeros();if(decimal.precision()>1024||decimal.scale()>1000||decimal.scale() < -1000)throw new IllegalArgumentException();return decimal.toPlainString();}
 public record Scope(String tenant,String ownerScope,UUID requestId,String workflowId,int revision,String digest){public Scope{new com.acme.opsweave.sharedkernel.TenantId(tenant);if(ownerScope==null||!ownerScope.matches("[a-f0-9]{64}"))throw new IllegalArgumentException();Objects.requireNonNull(requestId);WorkflowDefinition.ref(workflowId,revision);WorkflowDefinition.checkDigest(digest);}}
 public record Record(int index,String eventTime,String body,String severityText,String serviceName,String traceId,String spanId){
  public Record{if(index<0||index>4)throw new IllegalArgumentException();var values=new LinkedHashMap<String,Object>();values.put("eventTime",eventTime);values.put("body",body);values.put("severityText",severityText);values.put("serviceName",serviceName);values.put("traceId",traceId);values.put("spanId",spanId);if(!TelemetryOutput.validate("LOG",values).valid()||!Instant.parse(eventTime).toString().equals(eventTime))throw new IllegalArgumentException();}
  public static Record from(int index,Map<String,Object> values){return new Record(index,(String)values.get("eventTime"),(String)values.get("body"),(String)values.get("severityText"),(String)values.get("serviceName"),(String)values.get("traceId"),(String)values.get("spanId"));}
 }
 public record Batch(Scope scope,List<Record> records){public Batch{Objects.requireNonNull(scope);records=List.copyOf(records);if(records.isEmpty()||records.size()>5)throw new IllegalArgumentException();int previous=-1;for(var row:records){if(row.index()<=previous)throw new IllegalArgumentException();previous=row.index();}}
  public String digest(){return recordsDigest(scope,records);}
 }
 public static String recordsDigest(Scope scope,List<Record> records){var parts=new ArrayList<String>(List.of("workflow-log-batch-v1",scope.tenant(),scope.ownerScope(),scope.requestId().toString(),scope.workflowId(),Integer.toString(scope.revision()),scope.digest()));for(var row:records){parts.add(Integer.toString(row.index()));parts.add(row.eventTime());parts.add(row.body());for(var text:Arrays.asList(row.severityText(),row.serviceName(),row.traceId(),row.spanId())){parts.add(text==null?"null":"text");parts.add(Objects.toString(text,""));}}return WorkflowDefinition.hash(parts);}
 public record Receipt(UUID requestId,String workflowId,int revision,String digest,UUID previewId,String commandDigest,Instant createdAt,Instant updatedAt,String state,int accepted,int filtered,int confirmed,int failed,int unknown,String error,String batchDigest,List<Integer> indices){
  public Receipt{Objects.requireNonNull(requestId);Objects.requireNonNull(previewId);Objects.requireNonNull(createdAt);Objects.requireNonNull(updatedAt);WorkflowDefinition.ref(workflowId,revision);for(var hash:List.of(digest,commandDigest,batchDigest))WorkflowDefinition.checkDigest(hash);indices=List.copyOf(indices);if(accepted<1||accepted>5||filtered<0||accepted+filtered>5||indices.size()!=accepted||confirmed<0||failed<0||unknown<0||confirmed+failed+unknown!=accepted||updatedAt.isBefore(createdAt)||!Set.of("PENDING","CONFIRMED","FAILED","UNKNOWN").contains(state))throw new IllegalArgumentException();int previous=-1;for(var index:indices){if(index<=previous||index>4)throw new IllegalArgumentException();previous=index;}if(state.equals("CONFIRMED")){if(confirmed!=accepted||failed!=0||unknown!=0||error!=null)throw new IllegalArgumentException();}else if(state.equals("FAILED")){if(failed!=accepted||confirmed!=0||unknown!=0||!Set.of("OUTPUT_REJECTED","FORBIDDEN","RUNTIME_UNAVAILABLE").contains(error))throw new IllegalArgumentException();}else if(unknown!=accepted||confirmed!=0||failed!=0||(state.equals("UNKNOWN")?!"OUTPUT_UNCONFIRMED".equals(error):error!=null))throw new IllegalArgumentException();}
  public void require(Command c){if(!requestId.equals(c.requestId())||!workflowId.equals(c.id())||revision!=c.revision()||!digest.equals(c.digest())||!previewId.equals(c.previewId())||!commandDigest.equals(c.commandDigest()))throw new WorkflowFailure(WorkflowFailure.Code.CONFLICT);}
  public void require(SourceCommand c){if(!requestId.equals(c.requestId())||!workflowId.equals(c.id())||revision!=c.revision()||!digest.equals(c.digest())||!commandDigest.equals(c.commandDigest()))throw new WorkflowFailure(WorkflowFailure.Code.CONFLICT);}
  public Receipt finish(String state,String error,Instant now){return new Receipt(requestId,workflowId,revision,digest,previewId,commandDigest,createdAt,now,state,accepted,filtered,state.equals("CONFIRMED")?accepted:0,state.equals("FAILED")?accepted:0,Set.of("PENDING","UNKNOWN").contains(state)?accepted:0,error,batchDigest,indices);}
  public void requireSuccessor(Receipt next){if(Set.of("CONFIRMED","FAILED").contains(state)||state.equals("UNKNOWN")&&next.state().equals("FAILED")||next.updatedAt().isBefore(updatedAt)||!finish(next.state(),next.error(),next.updatedAt()).equals(next))throw new IllegalStateException("Invalid log confirmation refinement");}
 }
 public record Data(UUID requestId,Instant readAt,String storage,int expectedRecords,boolean complete,List<Record> records){public Data{Objects.requireNonNull(requestId);Objects.requireNonNull(readAt);records=List.copyOf(records);if(!"clickhouse".equals(storage)||expectedRecords<1||expectedRecords>5||records.size()>5||complete&&records.size()!=expectedRecords)throw new IllegalArgumentException();}}
}
