import { ModelRelationsGraph } from './ModelRelationsGraph.tsx'
import { createSignal, For, onCleanup, Show } from '@zeus-js/zeus'
import { forItem } from '../../adapters/zeus-ui/for-item.ts'
import { ZwButton } from '../../adapters/zeus-ui/ZwButton.tsx'
import { usePlatformSession } from '../../state/platform-session.ts'
import { readCatalog, saveModel, publishModel, previewModel, type CatalogPage, type ModelDefinition, type ModelEntry, type ModelField, type FieldType, type ModelPreview, type CatalogMetric } from '../../api/model-catalog.ts'

type Mode = 'ENTITY' | 'RELATION' | 'METRIC'
const typeLabels: Record<FieldType, string> = { TEXT: '文本', INTEGER: '整数', DECIMAL: '小数', BOOLEAN: '布尔', ENUM: '枚举', DATETIME: '时间' }
const ruleLabels: Record<string, string> = { 'trim-text': '去除文本首尾空格', 'strict-scalar-conversion': '严格转换标量类型', 'required-and-null-check': '检查必填与空值', 'enum-and-range-check': '校验枚举与数值范围', 'reject-unknown-field': '报告未定义字段' }
const issueLabels: Record<string, string> = { MISSING_REQUIRED: '缺少必填字段', NULL_REQUIRED: '必填字段为 null', EMPTY_REQUIRED: '必填文本为空', UNKNOWN_FIELD: '未定义字段', TYPE_MISMATCH: '类型转换失败', TOO_LONG: '超出文本长度', ENUM_MISMATCH: '不在枚举范围', OUT_OF_RANGE: '超出数值范围', NUMERIC_LIMIT: '超出数值精度或安全范围' }
export function ModelCatalogPage(props: { mode: Mode }) {
  const [catalog, setCatalog] = createSignal<CatalogPage | null>(null), [search, setSearch] = createSignal('')
  const [busy, setBusy] = createSignal(false), [error, setError] = createSignal(''), [notice, setNotice] = createSignal('')
  const [editing, setEditing] = createSignal<ModelDefinition | null>(null), [saved, setSaved] = createSignal<ModelEntry | null>(null)
  const [readonly, setReadonly] = createSignal(true), [dirty, setDirty] = createSignal(false), [sample, setSample] = createSignal('{}'), [preview, setPreview] = createSignal<ModelPreview | null>(null)
  let dialog: HTMLDialogElement | null = null; let active: AbortController | undefined; let sequence = 0; let disposed = false; let returnFocus: HTMLElement | null = null
  function clear() { ++sequence; active?.abort(); setBusy(false); setCatalog(null); setEditing(null); setSaved(null); setPreview(null); setSample('{}'); setNotice(''); dialog?.close() }
  const ready = usePlatformSession(change => { clear(); setError(change.error?.message ?? '') })
  onCleanup(() => { disposed = true; clear() })
  const disabled = () => busy() || !ready()
  async function run(work: (signal: AbortSignal, current: () => boolean) => Promise<void>) {
    active?.abort(); const controller = new AbortController(); active = controller; const seq = ++sequence; const current = () => !disposed && seq === sequence
    setBusy(true); setError(''); setNotice('')
    try { await work(controller.signal, current) } catch (e) { if (current()) setError(e instanceof Error ? e.message : '模型请求失败') } finally { if (current()) setBusy(false) }
  }
  function load() { setCatalog(null); void run(async (signal, current) => { const data = await readCatalog(signal); if (current()) setCatalog(data) }) }
  const matches = (d: ModelDefinition) => d.kind === props.mode && (d.label + ' ' + d.id).toLowerCase().includes(search().toLowerCase())
  const builtins = () => catalog()?.package.definitions.filter(matches) ?? []
  const custom = () => catalog()?.published.items.filter(e => matches(e.definition)) ?? []
  const drafts = () => catalog()?.drafts.items.filter(e => matches(e.definition) && !catalog()?.published.items.some(p => p.definition.id === e.definition.id && p.definition.revision === e.definition.revision && p.digest === e.digest)) ?? []
  function open(definition: ModelDefinition, entry: ModelEntry | null, locked: boolean) {
    returnFocus = document.activeElement instanceof HTMLElement ? document.activeElement : null
    setEditing(structuredClone(definition)); setSaved(entry); setReadonly(locked); setDirty(!locked && !entry); setPreview(null); setSample('{}'); setError(''); setNotice(''); dialog?.showModal()
  }
  function create() {
    const relation = props.mode === 'RELATION'
    open({ schemaVersion: '1.0', id: 'custom.', revision: 1, kind: relation ? 'RELATION' : 'ENTITY', label: '', description: '', cleaningProfile: 'safe-scalars-v1', fields: relation ? [] : [{ id: 'name', label: '名称', type: 'TEXT', required: true, maxLength: 255 }], ...(relation ? { endpoints: { from: { id: 'builtin.service', revision: 1 }, to: { id: 'builtin.host', revision: 1 }, cardinality: 'MANY_TO_MANY' as const } } : {}) }, null, false)
  }
  function change(patch: Partial<ModelDefinition>) { const d = editing(); if (!d || readonly()) return; setEditing({ ...d, ...patch }); setDirty(true); setPreview(null); setNotice('') }
  function changeField(index: number, patch: Partial<ModelField>) { const d = editing(); if (!d) return; change({ fields: d.fields.map((f, i) => i === index ? Object.fromEntries(Object.entries({ ...f, ...patch }).filter(([, value]) => value !== undefined)) as ModelField : f) }) }
  function fieldType(index: number, type: FieldType) { const f = editing()?.fields[index]; if (!f) return; const next: ModelField = { id: f.id, label: f.label, type, required: f.required, ...(['TEXT', 'ENUM'].includes(type) ? { maxLength: 255 } : {}), ...(type === 'ENUM' ? { choices: ['value'] } : {}) }; change({ fields: editing()!.fields.map((old, i) => i === index ? next : old) }) }
  function addField() { const fields = editing()?.fields ?? []; let n = fields.length + 1; while (fields.some(f => f.id === 'field_' + n)) n++; change({ fields: [...fields, { id: 'field_' + n, label: '新字段', type: 'TEXT', required: false, maxLength: 255 }] }) }
  function copy(nextRevision: boolean) { const d = editing(); if (!d) return; setEditing({ ...structuredClone(d), id: nextRevision ? d.id : 'custom.' + d.id.split('.')[1] + '_copy', revision: nextRevision ? d.revision + 1 : 1 }); setSaved(null); setReadonly(false); setDirty(true); setNotice(''); setPreview(null) }
  function save() { const d = editing(); if (!d) return; const expected = saved()?.state === 'DRAFT' ? saved()!.editVersion : 0; void run(async (signal, current) => { const value = await saveModel(d, expected, signal); if (!current()) return; setSaved(value); setDirty(false); setNotice('私有草稿已保存'); const data = await readCatalog(signal); if (current()) setCatalog(data) }) }
  function publish() { const draft = saved(); if (!draft || dirty() || draft.state !== 'DRAFT') return; void run(async (signal, current) => { const value = await publishModel(draft, signal); if (!current()) return; setSaved(value); setReadonly(true); setNotice('模型版本已发布，历史资产尚未自动转换'); const data = await readCatalog(signal); if (current()) setCatalog(data) }) }
  function inspectSample() { const d = editing(); if (!d) return; setPreview(null); void run(async (signal, current) => { let input: unknown; try { input = JSON.parse(sample()) } catch { throw new Error('样本必须是有效的 JSON 对象') } const value = await previewModel(d, input, signal); if (current()) setPreview(value) }) }
  const entityOptions = () => [...(catalog()?.package.definitions ?? []), ...(catalog()?.published.items.map(e => e.definition) ?? [])].filter(d => d.kind === 'ENTITY')
  function endpoint(which: 'from' | 'to', value: string) { const e = editing()?.endpoints; if (!e) return; const [id, revision] = value.split('@'); change({ endpoints: { ...e, [which]: { id, revision: Number(revision) } } }) }
  function close() { if (busy()) return; dialog?.close(); returnFocus?.focus() }
  return <section class="model-center" data-page="model-catalog">
    <header class="model-heading"><div><div class="eyebrow">DATA MODEL · 数据模型</div><h2>{props.mode==='ENTITY'?'实体模型':props.mode==='RELATION'?'关系模型':'指标定义'}</h2><p>{props.mode==='ENTITY'?'定义资产类型与字段，让不同来源的数据使用同一套结构。':props.mode==='RELATION'?'定义实体类型之间的连接方向、端点与基数。':'统一指标含义、单位与来源转换规则。'}</p></div><div class="model-actions"><ZwButton variant="outline" disabled={disabled()} onPress={load}>读取模型目录</ZwButton><Show when={props.mode !== 'METRIC'}><ZwButton variant="primary" disabled={disabled() || !catalog()} onPress={create}>{props.mode === 'RELATION' ? '新建关系类型' : '新建实体类型'}</ZwButton></Show></div></header>
    <nav class="model-tabs" aria-label="模型类别"><a href="#/modeling/entities" aria-current={props.mode === 'ENTITY' ? 'page' : undefined}>实体类型</a><a href="#/modeling/metrics" aria-current={props.mode === 'METRIC' ? 'page' : undefined}>内置指标</a><a href="#/modeling/relations" aria-current={props.mode === 'RELATION' ? 'page' : undefined}>关系类型</a></nav>
    <Show when={!catalog()}><div class="model-empty"><div class="model-empty-icon">◇</div><h3>加载你的模型目录</h3><p>使用当前平台身份读取内置定义、租户发布版本和个人草稿。</p><p>定义不代表已有资产、关系实例或实时采样。</p></div></Show>
    <Show when={catalog()}><div class="model-meta"><span class="model-pill">{catalog()?.storage === 'postgres' ? 'PostgreSQL 持久化' : 'Memory · 临时存储'}</span><span>{'内置包 opsweave-core · v' + catalog()?.package.version}</span><span>发布版本不可覆盖</span></div>
      <Show when={props.mode !== 'METRIC'}><Show when={props.mode==='RELATION'}><ModelRelationsGraph catalog={catalog} /></Show><div class="model-section-heading"><h3>{props.mode === 'ENTITY' ? '内置实体类型' : '内置关系类型'}</h3><label class="model-search">筛选类型<input type="search" placeholder="名称或标识" prop:value={search()} onInput={e => setSearch((e.target as HTMLInputElement).value)} /></label></div>
        <div class="model-grid"><For each={builtins()}>{row => <ModelCard definition={forItem(row)} badge="内置" open={() => open(forItem(row), null, true)} />}</For></div>
        <h3>租户发布版本 <span class="model-count">{custom().length}</span></h3><Show when={!custom().length}><p class="model-muted">暂无匹配的自定义版本。可复制内置类型，也可从新类型开始。</p></Show><div class="model-grid"><For each={custom()}>{row => <ModelCard definition={forItem(row).definition} badge="已发布" open={() => open(forItem(row).definition, forItem(row), true)} />}</For></div>
        <h3>我的草稿 <span class="model-count">{drafts().length}</span></h3><div class="model-grid"><For each={drafts()}>{row => <ModelCard definition={forItem(row).definition} badge={'草稿 · 编辑 ' + forItem(row).editVersion} open={() => open(forItem(row).definition, forItem(row), false)} />}</For></div><Show when={!drafts().length}><p class="model-muted">没有待发布的个人草稿。</p></Show>
        <Show when={catalog()?.published.truncated || catalog()?.drafts.truncated}><p role="status">目录仅显示前 50 个版本或草稿，当前列表不完整。</p></Show>
      </Show>
      <Show when={props.mode === 'METRIC'}><p class="model-muted">这些指标已有版本化映射定义。实际绑定与采样请到“指标”页面读取；目录不报告在线状态。</p><div class="model-grid"><For each={catalog()?.package.metrics ?? []}>{row => <MetricCard metric={forItem(row)} />}</For></div></Show>
      <details class="model-foundation-details"><summary>默认清洗规则与来源版本说明</summary><div class="model-foundations"><section class="model-rule-card"><div class="eyebrow">DEFAULT RULES</div><h3>开箱即用的清洗规则</h3><p>safe-scalars-v1 · 默认启用，可在字段样本中预览。</p><ol><For each={catalog()?.package.cleaning.rules ?? []}>{row => <li>{ruleLabels[forItem(row)] ?? forItem(row)}</li>}</For></ol><p class="model-muted">不补造缺失值；可选 null 保留，转换失败单独报告。</p></section><section class="model-rule-card"><div class="eyebrow">SOURCE COMPATIBILITY</div><h3>连接器负责版本适配</h3><p>Zabbix 通过 apiinfo.version 探测版本，在连接器内处理认证与字段差异。</p><span class="model-pill">本地已实测：7.0.27</span><p>其他版本：尚未验证。不能仅凭版本号认定兼容。</p><p class="model-muted">在数据源中心选择来源并配置接入，再进入工作流画布。关系实例管理与 AI 协助后续开发。</p></section></div></details>
    </Show>
    <p role="alert">{error()}</p><p role="status">{busy() ? '正在请求…' : notice()}</p>
    <dialog class="model-drawer" aria-label="模型定义" ref={(node: HTMLElement | null) => { dialog = node as HTMLDialogElement | null }} onCancel={(e: Event) => { if (busy()) e.preventDefault() }} onClose={() => returnFocus?.focus()}>
      <header class="model-drawer-heading"><div><div class="eyebrow">{readonly() ? '模型定义 · 固定版本' : '模型定义 · 私有草稿'}</div><h3>{editing()?.label || '创建模型类型'}</h3></div><button type="button" class="model-close" aria-label="关闭模型定义" disabled={busy()} onClick={close}>×</button></header>
      <div class="model-drawer-body"><fieldset disabled={busy() || readonly()} class="model-form"><div class="model-form-grid"><label>类型标识<input aria-label="类型标识" prop:value={editing()?.id ?? ''} disabled={!!saved()} onInput={e => change({ id: (e.target as HTMLInputElement).value })} placeholder="custom.web_service" /></label><label>显示名称<input aria-label="显示名称" prop:value={editing()?.label ?? ''} maxLength={80} onInput={e => change({ label: (e.target as HTMLInputElement).value })} /></label><label>发布版本<input aria-label="发布版本" type="number" min="1" max="10000" prop:value={String(editing()?.revision ?? 1)} disabled={!!saved()} onInput={e => change({ revision: Number((e.target as HTMLInputElement).value) })} /></label><label>类型<span class="model-static-value">{editing()?.kind === 'RELATION' ? '关系' : '实体'}</span></label></div><label>说明<textarea aria-label="模型说明" rows={2} maxLength={1000} prop:value={editing()?.description ?? ''} onInput={e => change({ description: (e.target as HTMLTextAreaElement).value })} /></label>
        <Show when={editing()?.kind === 'ENTITY'}><div class="model-section-heading"><h4>字段 <span class="model-count">{editing()?.fields.length ?? 0} / 32</span></h4><button type="button" class="model-text-button" disabled={(editing()?.fields.length ?? 0) >= 32} onClick={addField}>＋ 添加字段</button></div><div class="model-fields"><For each={editing()?.fields.map((_, i) => i) ?? []}>{row => <FieldEditor index={forItem(row)} value={() => editing()!.fields[forItem(row)]} change={patch => changeField(forItem(row), patch)} type={type => fieldType(forItem(row), type)} remove={() => change({ fields: editing()!.fields.filter((_, i) => i !== forItem(row)) })} />}</For></div></Show>
        <Show when={editing()?.kind === 'RELATION'}><div class="model-relation-form"><label>起点实体类型<select aria-label="起点实体类型" prop:value={(editing()?.endpoints?.from.id ?? '') + '@' + editing()?.endpoints?.from.revision} onChange={e => endpoint('from', (e.target as HTMLSelectElement).value)}><For each={entityOptions()}>{row => <option value={forItem(row).id + '@' + forItem(row).revision}>{forItem(row).label + ' · v' + forItem(row).revision}</option>}</For></select></label><span aria-hidden="true">→</span><label>终点实体类型<select aria-label="终点实体类型" prop:value={(editing()?.endpoints?.to.id ?? '') + '@' + editing()?.endpoints?.to.revision} onChange={e => endpoint('to', (e.target as HTMLSelectElement).value)}><For each={entityOptions()}>{row => <option value={forItem(row).id + '@' + forItem(row).revision}>{forItem(row).label + ' · v' + forItem(row).revision}</option>}</For></select></label></div><label>基数<select aria-label="关系基数" prop:value={editing()?.endpoints?.cardinality ?? 'MANY_TO_MANY'} onChange={e => change({ endpoints: { ...editing()!.endpoints!, cardinality: (e.target as HTMLSelectElement).value as 'ONE_TO_ONE' | 'ONE_TO_MANY' | 'MANY_TO_MANY' } })}><option value="ONE_TO_ONE">一对一</option><option value="ONE_TO_MANY">一对多</option><option value="MANY_TO_MANY">多对多</option></select></label><p class="model-muted">端点固定到已发布实体类型的具体版本；此处管理类型，不创建关系实例。</p></Show>
      </fieldset>
      <Show when={editing()?.kind === 'ENTITY'}><section class="model-sample"><h4>清洗预览 <span class="model-pill">safe-scalars-v1</span></h4><p class="model-muted">输入一条手工 JSON 样本，仅在内存中清洗，不写入资产。</p><label>预览样本<textarea aria-label="预览样本" rows={5} maxLength={16000} spellcheck={false} prop:value={sample()} disabled={busy()} onInput={e => { setSample((e.target as HTMLTextAreaElement).value); setPreview(null) }} /></label><ZwButton variant="outline" disabled={disabled()} onPress={inspectSample}>预览清洗结果</ZwButton><Show when={preview()}><div class="model-preview" data-model-preview><strong>{preview()?.valid ? '样本通过校验' : '样本存在问题，不能作为有效输出'}</strong><pre>{JSON.stringify(preview()?.values, null, 2)}</pre><ul><For each={preview()?.issues ?? []}>{row => <li>{forItem(row).field + '：' + (issueLabels[forItem(row).code] ?? forItem(row).code)}</li>}</For></ul><For each={preview()?.changes ?? []}>{row => <p>{forItem(row).field + ' · ' + ruleLabels[forItem(row).rule]}</p>}</For><p class="model-muted">缺失字段未补值；失败字段未进入有效值集合，原始样本仍保留在上方。</p></div></Show></section></Show>
      <Show when={saved()}><p class="model-digest">{'版本指纹 ' + saved()?.digest}</p></Show><p role="alert">{error()}</p><p role="status">{notice()}</p>
      </div><footer class="model-drawer-footer"><Show when={readonly()}><ZwButton variant="outline" disabled={disabled()} onPress={() => copy(false)}>复制为自定义类型</ZwButton><Show when={saved()?.state === 'PUBLISHED'}><ZwButton variant="primary" disabled={disabled() || (editing()?.revision ?? 1) >= 10000} onPress={() => copy(true)}>创建下一版本</ZwButton></Show></Show><Show when={!readonly()}><ZwButton variant="outline" disabled={disabled() || !dirty()} onPress={save}>保存私有草稿</ZwButton><ZwButton variant="primary" disabled={disabled() || dirty() || saved()?.state !== 'DRAFT'} onPress={publish}>发布模型版本</ZwButton></Show></footer>
    </dialog>
  </section>
}
function ModelCard(props: { definition: ModelDefinition; badge: string; open: () => void }) {
  return <button type="button" class="model-card" onClick={props.open}><div class="model-card-top"><span class="model-glyph" aria-hidden="true">{props.definition.kind === 'RELATION' ? '↗' : '◇'}</span><span class="model-pill">{props.badge}</span></div><h4>{props.definition.label}</h4><code>{props.definition.id}</code><p>{props.definition.description || '自定义模型定义'}</p><div class="model-card-bottom"><span>{props.definition.kind === 'ENTITY' ? props.definition.fields.length + ' 个字段' : props.definition.endpoints?.from.id.split('.')[1] + ' → ' + props.definition.endpoints?.to.id.split('.')[1]}</span><span>{'v' + props.definition.revision + ' →'}</span></div></button>
}
function MetricCard(props: { metric: CatalogMetric }) { return <article class="model-card model-metric"><div class="model-card-top"><span class="model-glyph" aria-hidden="true">∿</span><span class="model-pill">内置定义</span></div><h4>{props.metric.label}</h4><code>{props.metric.key}</code><dl><dt>单位</dt><dd>{props.metric.unit === '1' ? '比例 · 0–1' : props.metric.unit}</dd><dt>来源键</dt><dd><code>{props.metric.sourceKey}</code></dd><dt>转换</dt><dd>{props.metric.transform === 'percent-to-ratio' ? '百分数 × 0.01' : '保留原值'}</dd></dl><p class="model-muted">{props.metric.mapping}</p></article> }
function FieldEditor(props: { index: number; value: () => ModelField; change: (patch: Partial<ModelField>) => void; type: (type: FieldType) => void; remove: () => void }) {
  return <section class="model-field" aria-label={'字段 ' + (props.index + 1)}><div class="model-field-heading"><strong>{'字段 ' + (props.index + 1)}</strong><label class="model-required"><input type="checkbox" checked={props.value()?.required ?? false} onChange={e => props.change({ required: (e.target as HTMLInputElement).checked })} />必填</label><button type="button" class="model-text-button" onClick={props.remove}>移除</button></div><div class="model-form-grid"><label>字段标识<input aria-label={'字段标识 ' + (props.index + 1)} prop:value={props.value()?.id ?? ''} onInput={e => props.change({ id: (e.target as HTMLInputElement).value })} /></label><label>字段名称<input aria-label={'字段名称 ' + (props.index + 1)} prop:value={props.value()?.label ?? ''} onInput={e => props.change({ label: (e.target as HTMLInputElement).value })} /></label><label>字段类型<select aria-label={'字段类型 ' + (props.index + 1)} prop:value={props.value()?.type ?? 'TEXT'} onChange={e => props.type((e.target as HTMLSelectElement).value as FieldType)}><For each={Object.keys(typeLabels) as FieldType[]}>{row => <option value={forItem(row)}>{typeLabels[forItem(row)]}</option>}</For></select></label><Show when={props.value()?.type === 'TEXT' || props.value()?.type === 'ENUM'}><label>最大长度<input aria-label={'最大长度 ' + (props.index + 1)} type="number" min="1" max="2048" prop:value={String(props.value()?.maxLength ?? 255)} onInput={e => props.change({ maxLength: Number((e.target as HTMLInputElement).value) })} /></label></Show><Show when={props.value()?.type === 'INTEGER' || props.value()?.type === 'DECIMAL'}><label>最小值<input aria-label={'最小值 ' + (props.index + 1)} type="number" prop:value={props.value()?.min === undefined ? '' : String(props.value().min)} onInput={e => props.change({ min: (e.target as HTMLInputElement).value === '' ? undefined : Number((e.target as HTMLInputElement).value) })} /></label><label>最大值<input aria-label={'最大值 ' + (props.index + 1)} type="number" prop:value={props.value()?.max === undefined ? '' : String(props.value().max)} onInput={e => props.change({ max: (e.target as HTMLInputElement).value === '' ? undefined : Number((e.target as HTMLInputElement).value) })} /></label></Show></div><Show when={props.value()?.type === 'ENUM'}><label>枚举值（英文逗号分隔）<input aria-label={'枚举值 ' + (props.index + 1)} prop:value={props.value()?.choices?.join(',') ?? ''} onInput={e => props.change({ choices: (e.target as HTMLInputElement).value.split(',') })} /></label></Show></section>
}
