import { platformClient } from './http.ts'
import { parseInstance, type SourceInstance } from './source-instances.ts'
import type { CredentialVersion } from './source-credentials.ts'

export type Endpoint = { id: string; name: string; connectorKind: 'ZABBIX_HOST'; address: string; digest: string }
export type EndpointPin = Pick<Endpoint, 'id' | 'digest'>
export type ConnectionConfiguration = { sourceId: string; revision: number; connectorVersion: 'host-jsonrpc-v1' | 'host-jsonrpc-v2'; endpoint: Endpoint; credentialPin: CredentialVersion['pin']; hostGroupIds: string[]; connectionDigest: string; createdAt: string }
export type ConnectionView = { instance: SourceInstance; connection: ConnectionConfiguration | null; availability: 'LEGACY' | 'AVAILABLE' | 'UNAVAILABLE' | 'ARCHIVED'; canConfigure: boolean }
export type ConnectionCommand = { requestId: string; name: string; description: string; endpointPin: EndpointPin; credentialPin: CredentialVersion['pin']; hostGroupIds: string[]; expectedEditVersion?: number }
export type PendingConnection = { id: string; command: ConnectionCommand; previous: SourceInstance | null }
const uuid = /^[a-f0-9]{8}(-[a-f0-9]{4}){3}-[a-f0-9]{12}$/, hash = /^sha256:[a-f0-9]{64}$/
function invalid(): never { throw new Error('连接响应与固定配置不一致，请保留原请求并核对') }
export function normalizeHostGroupIds(values: string[]) { if (!Array.isArray(values) || values.length < 1 || values.length > 32 || values.some(value => typeof value !== 'string' || !/^[1-9][0-9]{0,18}$/.test(value)) || new Set(values).size !== values.length) throw new Error('请填写1到32个有效且不重复的主机组 ID'); return [...values].sort((a, b) => a.length - b.length || (a < b ? -1 : a > b ? 1 : 0)) }
function object(value: unknown, keys: string[]): Record<string, any> { if (!value || typeof value !== 'object' || Array.isArray(value) || Object.keys(value).length !== keys.length || !keys.every(k => Object.hasOwn(value, k))) invalid(); return value as Record<string, any> }
function instant(value: unknown) { if (typeof value !== 'string' || value.length > 40 || !/^\d{4}-\d{2}-\d{2}T.*(?:Z|[+-]\d{2}:\d{2})$/.test(value) || !Number.isFinite(Date.parse(value))) invalid(); return Date.parse(value) }
async function digest(parts: string[]) { const e = new TextEncoder(), chunks: Uint8Array[] = []; for (const p of parts) { const b = e.encode(p); chunks.push(e.encode(b.length + ':'), b) }; const input = new Uint8Array(chunks.reduce((n, b) => n + b.length, 0)); let offset = 0; for (const b of chunks) { input.set(b, offset); offset += b.length }; return 'sha256:' + [...new Uint8Array(await crypto.subtle.digest('SHA-256', input))].map(b => b.toString(16).padStart(2, '0')).join('') }
function envelope(value: unknown, keys: string[]) { const v = object(value, ['schemaVersion', 'storage', ...keys]); if (v.schemaVersion !== '2.0' || !['memory', 'postgres'].includes(v.storage)) invalid(); return v }
async function endpoint(value: unknown): Promise<Endpoint> { const e = object(value, ['id', 'name', 'connectorKind', 'address', 'digest']); if (typeof e.id !== 'string' || !/^[a-z0-9][a-z0-9_-]{0,63}$/.test(e.id) || e.connectorKind !== 'ZABBIX_HOST' || typeof e.name !== 'string' || !e.name.trim() || e.name !== e.name.trim() || e.name.length > 80 || /[\x00-\x1f\x7f-\x9f\ufeff]/.test(e.name) || typeof e.address !== 'string' || e.address.length > 1024 || !/^https?:\/\/(?:[0-9]+(?:\.[0-9]+){3}|\[[0-9a-fA-F:]+\])(?::[0-9]+)?\/api_jsonrpc\.php$/.test(e.address) || !hash.test(e.digest) || e.digest !== await digest(['source-endpoint-v2', e.id, e.connectorKind, e.address])) invalid(); return e as Endpoint }
async function configuration(value: unknown): Promise<ConnectionConfiguration> { const raw = value as Record<string, any>, legacy = raw?.connectorVersion === 'host-jsonrpc-v1', c = object(value, legacy ? ['sourceId', 'revision', 'connectorVersion', 'endpoint', 'credentialPin', 'connectionDigest', 'createdAt'] : ['sourceId', 'revision', 'connectorVersion', 'endpoint', 'credentialPin', 'hostGroupIds', 'connectionDigest', 'createdAt']), p = object(c.credentialPin, ['credentialId', 'revision', 'versionId']), e = await endpoint(c.endpoint); let groups: string[] = []; if (!uuid.test(c.sourceId) || !Number.isInteger(c.revision) || c.revision < 1 || c.revision > 100 || !['host-jsonrpc-v1', 'host-jsonrpc-v2'].includes(c.connectorVersion) || !uuid.test(p.credentialId) || !uuid.test(p.versionId) || !Number.isInteger(p.revision) || p.revision < 1 || p.revision > 100 || !hash.test(c.connectionDigest)) invalid(); if (!legacy) { try { groups = normalizeHostGroupIds(c.hostGroupIds); if (groups.length !== c.hostGroupIds.length || groups.some((id, index) => id !== c.hostGroupIds[index])) invalid() } catch { invalid() } }; const expected = legacy ? await digest(['source-connection-v2', c.sourceId, c.connectorVersion, e.id, e.digest, p.credentialId, String(p.revision), p.versionId]) : await digest(['source-connection-v3', c.sourceId, c.connectorVersion, e.id, e.digest, p.credentialId, String(p.revision), p.versionId, String(groups.length), ...groups]); if (legacy !== (c.connectorVersion === 'host-jsonrpc-v1') || c.connectionDigest !== expected) invalid(); instant(c.createdAt); return { ...c, hostGroupIds: groups } as ConnectionConfiguration }
function matches(i: SourceInstance, c: ConnectionConfiguration) { if (i.id !== c.sourceId || i.source.kind !== 'ZABBIX_HOST' || i.dataMode !== 'zabbix-jsonrpc' || i.configurationRevision !== c.revision || i.connectionDigest !== c.connectionDigest || instant(c.createdAt) < instant(i.createdAt) || instant(c.createdAt) > instant(i.updatedAt)) invalid() }
export class ConnectionRejectedError extends Error {}
function request(path: string, signal: AbortSignal, method?: 'POST' | 'PATCH', body?: unknown) { return platformClient.request('/api/v2/data-sources' + path, { signal, ...(method ? { method, body } : {}), error: (status, code) => { const messages: Record<string, string> = { CONFLICT: '实例或原请求已变化，请读取最新配置后核对', SOURCE_UNAVAILABLE: '登记地址已变化或固定凭据不可用，请重读后重新选择', CREDENTIAL_UNAVAILABLE: '凭据存储当前不可用', CREDENTIAL_CONFLICT: '所选凭据版本已撤销，请重新选择', CREDENTIAL_NOT_FOUND: '找不到所选凭据版本', CAPACITY: '实例或配置回执已达到容量上限', FORBIDDEN: '当前身份没有这份连接的配置权限', NOT_FOUND: '当前身份下找不到实例或原请求' }; const message = messages[code] ?? '连接请求失败（HTTP ' + status + '）'; return method && ([400, 403, 404, 409].includes(status) || status === 503 && ['SOURCE_UNAVAILABLE', 'CREDENTIAL_UNAVAILABLE'].includes(code)) ? new ConnectionRejectedError(message) : new Error(message) } }) }
export async function readEndpoints(signal: AbortSignal) { const v = envelope(await request('/endpoints', signal), ['items']); if (!Array.isArray(v.items) || v.items.length > 32) invalid(); const items = await Promise.all(v.items.map(endpoint)); if (new Set(items.map(e => e.id)).size !== items.length) invalid(); return items }
export async function readConnection(id: string, signal: AbortSignal): Promise<ConnectionView> { if (!uuid.test(id)) invalid(); const v = envelope(await request('/' + id + '/connection', signal), ['instance', 'connection', 'availability', 'canConfigure']), i = parseInstance(v.instance); if (i.id !== id || typeof v.canConfigure !== 'boolean' || !['LEGACY', 'AVAILABLE', 'UNAVAILABLE', 'ARCHIVED'].includes(v.availability)) invalid(); const c = v.connection === null ? null : await configuration(v.connection); if (c) { matches(i, c); if ((v.availability === 'ARCHIVED') !== (i.state === 'ARCHIVED') || v.availability === 'LEGACY') invalid() } else if (v.availability !== 'LEGACY' || i.source.instanceId === 'connection-' + id) invalid(); return { instance: i, connection: c, availability: v.availability, canConfigure: v.canConfigure } }
export async function readConnectionHistory(id: string, signal: AbortSignal) { if (!uuid.test(id)) invalid(); const v = envelope(await request('/' + id + '/connection/history', signal), ['sourceId', 'items']); if (v.sourceId !== id || !Array.isArray(v.items) || v.items.length > 100) invalid(); const items = await Promise.all(v.items.map(configuration)); if (items.some(c => c.sourceId !== id) || new Set(items.map(c => c.revision)).size !== items.length) invalid(); return items }
export function connectionCommandDigest(p: PendingConnection) { const c = p.command, groups = c.hostGroupIds.length ? normalizeHostGroupIds(c.hostGroupIds) : []; const values = ['source-connection-write-' + (groups.length ? 'v3' : 'v2'), p.id, c.requestId, String(c.expectedEditVersion ?? 0), c.name, c.description, c.endpointPin.id, c.endpointPin.digest, c.credentialPin.credentialId, String(c.credentialPin.revision), c.credentialPin.versionId]; if (groups.length) values.push(String(groups.length), ...groups); return digest(values) }
async function receipt(value: unknown, p: PendingConnection) { const v = envelope(value, ['receipt', 'connection']), r = object(v.receipt, ['requestId', 'sourceId', 'commandDigest', 'instance']), i = parseInstance(r.instance), c = await configuration(v.connection), old = p.previous, command = p.command, groups = normalizeHostGroupIds(command.hostGroupIds); matches(i, c); if (r.requestId !== command.requestId || r.sourceId !== p.id || r.commandDigest !== await connectionCommandDigest(p) || i.id !== p.id || i.name !== command.name || i.description !== command.description || i.editVersion !== (command.expectedEditVersion ?? 0) + 1 || i.state !== 'ACTIVE' || c.connectorVersion !== 'host-jsonrpc-v2' || c.endpoint.id !== command.endpointPin.id || c.endpoint.digest !== command.endpointPin.digest || c.credentialPin.credentialId !== command.credentialPin.credentialId || c.credentialPin.revision !== command.credentialPin.revision || c.credentialPin.versionId !== command.credentialPin.versionId || groups.length !== c.hostGroupIds.length || groups.some((id, index) => id !== c.hostGroupIds[index])) invalid(); if (old ? i.source.kind !== old.source.kind || i.source.instanceId !== old.source.instanceId || i.createdAt !== old.createdAt || instant(i.updatedAt) < instant(old.updatedAt) || i.configurationRevision !== old.configurationRevision + (i.connectionDigest === old.connectionDigest ? 0 : 1) : i.source.instanceId !== 'connection-' + p.id || i.configurationRevision !== 1 || i.createdAt !== i.updatedAt) invalid(); return { instance: i, connection: c } }
export async function writeConnection(p: PendingConnection, signal: AbortSignal) { if (!uuid.test(p.id) || !uuid.test(p.command.requestId) || (!p.previous && p.id !== p.command.requestId) || p.previous && p.command.expectedEditVersion !== p.previous.editVersion) invalid(); normalizeHostGroupIds(p.command.hostGroupIds); return receipt(await request(p.previous ? '/' + p.id + '/connection' : '/connections', signal, p.previous ? 'PATCH' : 'POST', p.command), p) }
export async function readConnectionCommand(p: PendingConnection, signal: AbortSignal) { if (!uuid.test(p.id) || !uuid.test(p.command.requestId)) invalid(); return receipt(await request('/' + p.id + '/connection/commands/' + p.command.requestId, signal), p) }
