import { platformClient } from './http.ts'
export interface SourceCredential { id: string; name: string; revision: number; versionId: string; editVersion: number; state: 'ACTIVE' | 'REVOKED'; createdAt: string; updatedAt: string }
export interface CredentialVersion { pin: { credentialId: string; revision: number; versionId: string }; createdAt: string; revoked: boolean }
export interface CredentialPage { items: SourceCredential[]; truncated: boolean; vaultAvailable: boolean; canConfigure: boolean; secretWriteAvailable: boolean }
export interface CredentialCommand { requestId: string; credentialId: string; operation: 'CREATE' | 'EDIT' | 'REVOKE_VERSION'; expectedEditVersion: number; name: string; state: SourceCredential['state']; changesSecret: boolean; previous: SourceCredential | null; revokeRevision?: number }
const uuid = /^[a-f0-9]{8}(-[a-f0-9]{4}){3}-[a-f0-9]{12}$/, hash = /^sha256:[a-f0-9]{64}$/
function invalid(): never { throw new Error('凭据回执与原请求不一致，请保留请求并核对') }
function object(value: unknown, keys: string[]): Record<string, any> { if (!value || typeof value !== 'object' || Array.isArray(value) || Object.keys(value).length !== keys.length || !keys.every(k => Object.hasOwn(value, k))) invalid(); return value as Record<string, any> }
function date(v: unknown) { if (typeof v !== 'string' || v.length > 40 || !/^\d{4}-\d{2}-\d{2}T.*(?:Z|[+-]\d{2}:\d{2})$/.test(v) || !Number.isFinite(Date.parse(v))) invalid(); return Date.parse(v) }
function metadata(value: unknown): SourceCredential { const c = object(value, ['id', 'name', 'revision', 'versionId', 'editVersion', 'state', 'createdAt', 'updatedAt']); if (!uuid.test(c.id) || !uuid.test(c.versionId) || typeof c.name !== 'string' || !c.name.trim() || c.name !== c.name.trim() || c.name.length > 80 || /[\x00-\x1f\x7f-\x9f\ufeff]/.test(c.name) || !Number.isInteger(c.revision) || c.revision < 1 || c.revision > 100 || !Number.isInteger(c.editVersion) || c.editVersion < c.revision || c.editVersion > 1000 || !['ACTIVE', 'REVOKED'].includes(c.state) || date(c.updatedAt) < date(c.createdAt)) invalid(); return c as SourceCredential }
async function digest(parts: string[]) { const e = new TextEncoder(), chunks: Uint8Array[] = []; for (const part of parts) { const bytes = e.encode(part); chunks.push(e.encode(bytes.length + ':'), bytes) }; const bytes = new Uint8Array(chunks.reduce((n, c) => n + c.length, 0)); let offset = 0; for (const c of chunks) { bytes.set(c, offset); offset += c.length }; return 'sha256:' + [...new Uint8Array(await crypto.subtle.digest('SHA-256', bytes))].map(b => b.toString(16).padStart(2, '0')).join('') }
export function commandDigest(c: CredentialCommand) { return digest(c.operation === 'REVOKE_VERSION' ? ['source-credential-revoke-version-v2', c.credentialId, c.requestId, String(c.expectedEditVersion), String(c.revokeRevision)] : ['source-credential-write-v2', c.credentialId, c.requestId, c.operation, String(c.expectedEditVersion), c.name, c.state, String(c.changesSecret)]) }
export class CredentialRejectedError extends Error {}
function request(path: string, signal: AbortSignal, method?: 'POST' | 'PATCH', body?: unknown) { return platformClient.request('/api/v2/data-sources/credentials' + path, { signal, ...(method ? { method, body } : {}), error: (status, code) => {
  const messages: Record<string, string> = { FORBIDDEN: '当前身份无凭据配置权限', CREDENTIAL_FORBIDDEN: '当前身份无凭据配置权限', CREDENTIAL_NOT_FOUND: '当前身份下找不到凭据或原请求', CREDENTIAL_CONFLICT: '凭据版本已变化、已撤销或请求键已使用，请核对最新版本', CREDENTIAL_CAPACITY: '凭据或回执已达到容量上限', CREDENTIAL_UNAVAILABLE: '凭据存储或安全提交当前不可用' }
  const message = messages[code] ?? '凭据请求失败（HTTP ' + status + '）'; return method && ([400, 409].includes(status) || status === 503 && code === 'CREDENTIAL_UNAVAILABLE') ? new CredentialRejectedError(message) : new Error(message)
} }) }
function envelope(value: unknown, keys: string[]) { const n = object(value, ['schemaVersion', 'storage', ...keys]); if (n.schemaVersion !== '2.0' || !['memory', 'postgres'].includes(n.storage)) invalid(); return n }
export async function readCredentials(signal: AbortSignal): Promise<CredentialPage> { const n = envelope(await request('', signal), ['items', 'truncated', 'vaultAvailable', 'canConfigure', 'secretWriteAvailable']); if (!Array.isArray(n.items) || n.items.length > 20 || !['truncated', 'vaultAvailable', 'canConfigure', 'secretWriteAvailable'].every(k => typeof n[k] === 'boolean') || n.secretWriteAvailable && !n.vaultAvailable) invalid(); const items = n.items.map(metadata); if (new Set(items.map((c: SourceCredential) => c.id)).size !== items.length) invalid(); return { items, truncated: n.truncated, vaultAvailable: n.vaultAvailable, canConfigure: n.canConfigure, secretWriteAvailable: n.secretWriteAvailable } }
export async function readCredential(id: string, signal: AbortSignal) { if (!uuid.test(id)) invalid(); const c = metadata(envelope(await request('/' + id, signal), ['credential']).credential); if (c.id !== id) invalid(); return c }
export async function readCredentialVersions(id: string, signal: AbortSignal): Promise<CredentialVersion[]> { if (!uuid.test(id)) invalid(); const n = envelope(await request('/' + id + '/versions', signal), ['credentialId', 'items']); if (n.credentialId !== id || !Array.isArray(n.items) || n.items.length < 1 || n.items.length > 100) invalid(); const items = n.items.map((value: unknown) => { const v = object(value, ['pin', 'createdAt', 'revoked']), p = object(v.pin, ['credentialId', 'revision', 'versionId']); if (p.credentialId !== id || !Number.isInteger(p.revision) || p.revision < 1 || p.revision > 100 || !uuid.test(p.versionId) || typeof v.revoked !== 'boolean') invalid(); date(v.createdAt); return v as CredentialVersion }); if (new Set(items.map((v: CredentialVersion) => v.pin.revision)).size !== items.length || new Set(items.map((v: CredentialVersion) => v.pin.versionId)).size !== items.length) invalid(); return items }
async function receipt(value: unknown, original: CredentialCommand) { const r = object(envelope(value, ['receipt']).receipt, ['requestId', 'credentialId', 'operation', 'commandDigest', 'credential']); const c = metadata(r.credential); if (r.requestId !== original.requestId || r.credentialId !== original.credentialId || r.operation !== original.operation || !hash.test(r.commandDigest) || r.commandDigest !== await commandDigest(original) || c.id !== original.credentialId || c.editVersion !== original.expectedEditVersion + 1 || c.name !== original.name || c.state !== original.state || c.revision !== (original.previous?.revision ?? 0) + (original.changesSecret ? 1 : 0) || c.versionId !== (original.changesSecret ? original.requestId : original.previous?.versionId) || original.previous && (c.createdAt !== original.previous.createdAt || date(c.updatedAt) < date(original.previous.updatedAt))) invalid(); return c }
export async function writeCredential(original: CredentialCommand, secret: string | null, signal: AbortSignal) {
  if (original.changesSecret !== (secret !== null) || secret !== null && !/^[!-~]{1,4096}$/.test(secret) || !uuid.test(original.credentialId) || !uuid.test(original.requestId)) invalid()
  let body: unknown, path: string, method: 'POST' | 'PATCH'
  if (original.operation === 'REVOKE_VERSION') { if (!original.revokeRevision || original.revokeRevision < 1 || original.revokeRevision > 100 || secret !== null) invalid(); body = { requestId: original.requestId, expectedEditVersion: original.expectedEditVersion }; path = '/' + original.credentialId + '/versions/' + original.revokeRevision + '/revoke'; method = 'POST' }
  else if (original.operation === 'CREATE') { if (original.credentialId !== original.requestId || !original.changesSecret || original.expectedEditVersion !== 0) invalid(); body = { requestId: original.requestId, name: original.name, secret }; path = ''; method = 'POST' }
  else { body = { requestId: original.requestId, expectedEditVersion: original.expectedEditVersion, name: original.name, state: original.state, secret }; path = '/' + original.credentialId; method = 'PATCH' }
  return receipt(await request(path, signal, method, body), original)
}
export async function readCredentialCommand(original: CredentialCommand, signal: AbortSignal) { if (!uuid.test(original.credentialId) || !uuid.test(original.requestId)) invalid(); return receipt(await request('/' + original.credentialId + '/commands/' + original.requestId, signal), original) }
