import { platformClient } from './http.ts'
import type { Entry } from './workflows.ts'
// Wire authority: contracts/schemas/v2/workflow-runtime*.schema.json.
export type RuntimeSettings = { identityField: string; nameField: string }
export type RuntimeControlCommand = { requestId: string; id: string; revision: number; digest: string; settings: RuntimeSettings; expectedGeneration: number; operation: 'START' | 'STOP' | 'RESUME' }
export type RuntimeControlReceipt = { requestId: string; operation: 'START' | 'STOP' | 'RESUME'; commandDigest: string; createdAt: string; task: RuntimeTask }
export type RuntimeAuthorization = { id: string; issuedAt: string; expiresAt: string; maxBatches: number; consumedBatches: number }
export type RuntimeTask = { workflowId: string; revision: number; digest: string; settings: RuntimeSettings; generation: number; state: 'RUNNING' | 'STOPPED' | 'FAILED' | 'ABANDONED'; cursor: string; cursorId: string; updatedAt: string; error: string | null; authorization?: RuntimeAuthorization }
export type Execution = { id: string; workflowId: string; revision: number; digest: string; settings: RuntimeSettings; origin: 'MANUAL_SAMPLE' | 'fixture' | 'zabbix-jsonrpc'; syncRunId: string | null; createdAt: string; state: 'SUCCEEDED' | 'FAILED'; accepted: number; rejected: number; filtered: number; entityIds: string[]; error: string | null; authorizationId?: string | null }
export type RuntimeStatus = { schemaVersion: '2.0'; mode: 'LOCAL_DEV_ENTITY' | 'DELEGATED_ENTITY'; backgroundAvailable?: boolean; pollSeconds: 5; maxBatchRecords: 5; tasks: RuntimeTask[]; executions: Execution[] }
const uuid = /^[a-f0-9]{8}(-[a-f0-9]{4}){3}-[a-f0-9]{12}$/
const errors = ['INVALID_SAMPLE', 'SOURCE_UNAVAILABLE', 'FORBIDDEN', 'MODEL_CHANGED', 'OPERATOR_CHANGED', 'OUTPUT_UNAVAILABLE', 'BACKLOG_LIMIT', 'RUNTIME_UNAVAILABLE', 'AUTHORIZATION_EXPIRED', 'AUTHORIZATION_REVOKED', 'EXECUTION_LIMIT']
function invalid(): never { throw new Error('流程运行响应不符合契约') }
function object(value: unknown, keys: string[], optional: string[] = []): Record<string, unknown> { if (!value || typeof value !== 'object' || Array.isArray(value) || Object.keys(value).some(k => !keys.includes(k) && !optional.includes(k)) || keys.some(k => !Object.hasOwn(value, k))) invalid(); return value as Record<string, unknown> }
function integer(v: unknown, min: number, max: number) { if (!Number.isSafeInteger(v) || Number(v) < min || Number(v) > max) invalid() }
function date(v: unknown) { if (typeof v !== 'string' || v.length > 40 || !Number.isFinite(Date.parse(v))) invalid() }
function common(v: Record<string, unknown>) { if (typeof v.workflowId !== 'string' || !/^[a-z][a-z0-9_-]{0,47}$/.test(v.workflowId) || typeof v.digest !== 'string' || !/^sha256:[a-f0-9]{64}$/.test(v.digest)) invalid(); integer(v.revision, 1, 10000); const s = object(v.settings, ['identityField', 'nameField']); for (const value of Object.values(s)) if (typeof value !== 'string' || !/^[A-Za-z][A-Za-z0-9_]{0,47}$/.test(value) || ['tenantId', 'tenant_id', 'authorization', 'Authorization', 'token', 'secret', 'password', 'constructor', 'prototype'].includes(value)) invalid(); if (v.error !== null && !errors.includes(String(v.error))) invalid(); if ((['FAILED','ABANDONED'].includes(String(v.state))) !== (v.error !== null)) invalid() }
export function parseTask(value: unknown): RuntimeTask { const t = object(value, ['workflowId', 'revision', 'digest', 'settings', 'generation', 'state', 'cursor', 'cursorId', 'updatedAt', 'error'], ['authorization']); common(t); integer(t.generation, 1, 1000001); if (t.generation===1000001 && !['STOPPED','ABANDONED'].includes(String(t.state)) || !['RUNNING', 'STOPPED', 'FAILED', 'ABANDONED'].includes(String(t.state)) || !uuid.test(String(t.cursorId))) invalid(); date(t.cursor); date(t.updatedAt); if(t.state==='ABANDONED'&&(t.error!=='OUTPUT_UNAVAILABLE'||Object.hasOwn(t,'authorization')))invalid();if (Object.hasOwn(t,'authorization')) { const a=object(t.authorization,['id','issuedAt','expiresAt','maxBatches','consumedBatches']);if(!uuid.test(String(a.id)))invalid();date(a.issuedAt);date(a.expiresAt);integer(a.maxBatches,1,20);integer(a.consumedBatches,0,Number(a.maxBatches));const issued=Date.parse(String(a.issuedAt)),expires=Date.parse(String(a.expiresAt));if(expires<=issued||expires-issued>900000||issued>Date.parse(String(t.updatedAt)))invalid() } return value as RuntimeTask }
export function parseExecution(value: unknown): Execution { const x = object(value, ['id', 'workflowId', 'revision', 'digest', 'settings', 'origin', 'syncRunId', 'createdAt', 'state', 'accepted', 'rejected', 'filtered', 'entityIds', 'error'], ['authorizationId']); common(x); if (!uuid.test(String(x.id)) || x.syncRunId !== null && !uuid.test(String(x.syncRunId)) || Object.hasOwn(x,'authorizationId')&&x.authorizationId!==null&&!uuid.test(String(x.authorizationId)) || !['MANUAL_SAMPLE', 'fixture', 'zabbix-jsonrpc'].includes(String(x.origin)) || !['SUCCEEDED', 'FAILED'].includes(String(x.state))) invalid(); date(x.createdAt); for (const k of ['accepted', 'rejected', 'filtered']) integer(x[k], 0, 5); if (Number(x.accepted) + Number(x.rejected) + Number(x.filtered) > 5 || !Array.isArray(x.entityIds) || x.entityIds.length > Number(x.accepted) || x.entityIds.some(id => typeof id !== 'string' || !uuid.test(id)) || x.state === 'SUCCEEDED' && x.entityIds.length !== x.accepted) invalid(); return value as Execution }
const messages: Record<string, string> = { AUTHORIZATION_EXPIRED:'后台授权已到期，请核对后显式重新启动',AUTHORIZATION_REVOKED:'后台授权已撤销或权限配置不可用',EXECUTION_LIMIT:'本次后台授权的批次额度已用完',OPERATOR_CHANGED:'固定算子摘要与当前实现不匹配，请核对已发布版本',FORBIDDEN: '需要来源同步、模型读取和实体管理权限', SOURCE_UNAVAILABLE: '当前环境或固定来源不支持此运行方式', INVALID_SAMPLE: '批次必须完整且最多5条；请核对实体标识、名称和转换结果', PREVIEW_REQUIRED: '需要固定版本及相同输入的有效测试回执', CONFLICT: '任务状态或配置已变化，请先刷新状态', CAPACITY: '任务或执行回执已到容量上限', BUSY: '运行并发已满，请稍后显式重试' }
export class RuntimeRequestError extends Error { constructor(readonly status: number, message: string) { super(message) } }
const request = (path: string, signal: AbortSignal, body?: unknown) => platformClient.request('/api/v1/integrations/workflows/runtime' + path, { signal, body, error: (status, code) => new RuntimeRequestError(status, messages[code] ?? '流程运行请求失败（HTTP ' + status + '）') })
export async function readRuntime(signal: AbortSignal): Promise<RuntimeStatus> { const v = await request('', signal), r = object(v, ['schemaVersion', 'mode', 'pollSeconds', 'maxBatchRecords', 'tasks', 'executions'], ['backgroundAvailable']); if (r.schemaVersion !== '2.0' || !['LOCAL_DEV_ENTITY','DELEGATED_ENTITY'].includes(String(r.mode)) || Object.hasOwn(r,'backgroundAvailable')&&typeof r.backgroundAvailable!=='boolean' || r.mode==='DELEGATED_ENTITY'&&!Object.hasOwn(r,'backgroundAvailable') || r.pollSeconds !== 5 || r.maxBatchRecords !== 5 || !Array.isArray(r.tasks) || r.tasks.length > 20 || !Array.isArray(r.executions) || r.executions.length > 20) invalid(); r.tasks.forEach(parseTask); r.executions.forEach(parseExecution); return v as RuntimeStatus }
export function parseControlReceipt(value: unknown, command: RuntimeControlCommand): RuntimeControlReceipt {
 const receipt=object(value,['requestId','operation','commandDigest','createdAt','task']);const task=parseTask(receipt.task)
 date(receipt.createdAt)
 if(receipt.requestId!==command.requestId || receipt.operation!==command.operation || typeof receipt.commandDigest!=='string' || !/^sha256:[a-f0-9]{64}$/.test(receipt.commandDigest) || receipt.createdAt!==task.updatedAt
  || task.workflowId!==command.id || task.revision!==command.revision || task.digest!==command.digest || task.settings.identityField!==command.settings.identityField || task.settings.nameField!==command.settings.nameField
  || task.generation!==command.expectedGeneration+1 || task.state!==(command.operation==='STOP'?'STOPPED':'RUNNING'))invalid()
 return value as RuntimeControlReceipt
}
export async function controlRuntime(command: RuntimeControlCommand, signal: AbortSignal) {
 const {operation,...body}=command
 return parseControlReceipt(await request('/'+operation.toLowerCase(),signal,body),command)
}
export async function readRuntimeControl(command: RuntimeControlCommand,signal: AbortSignal) {
 return parseControlReceipt(await request('/commands/'+encodeURIComponent(command.requestId),signal),command)
}
export async function executeRuntime(entry: Entry, settings: RuntimeSettings, samples: unknown, syncRunId: string, previewId: string, signal: AbortSignal) { const x = parseExecution(await request('/execute', signal, { id: entry.definition.id, revision: entry.definition.revision, digest: entry.digest, settings, previewId, ...(entry.definition.source.kind === 'MANUAL_SAMPLE' ? { samples } : { syncRunId }) })); if (x.id !== previewId || x.workflowId !== entry.definition.id || x.revision !== entry.definition.revision || x.digest !== entry.digest) invalid(); return x }
