import {platformClient} from './http.ts'
import {logPosition} from './workflow-log-streams.ts'
import type {Entry} from './workflows.ts'

export type ReplayCommand={requestId:string;id:string;revision:number;digest:string;from:string;till:string}
export type ReplayExecute={requestId:string;planId:string;inputDigest:string;batchDigest:string}
export type ReplayProof={inputDigest:string;batchDigest:string;inputCount:number;filtered:number;collapsed:number;labels:Record<string,string>;timestamps:number[]}
export type ReplayPlan={schemaVersion:'2.0';requestId:string;reference:{id:string;revision:number;digest:string};commandDigest:string;from:string;till:string;createdAt:string;updatedAt:string;expiresAt:string;purpose:'REBUILD_METRIC_PROJECTION';outputPolicy:'ISOLATED_METRIC_SERIES';notifications:false;actions:false;state:'PREPARING'|'READY'|'FAILED';proof:ReplayProof|null;error:string|null}
export type ReplayReceipt={schemaVersion:'2.0';requestId:string;planId:string;reference:ReplayPlan['reference'];commandDigest:string;acceptedAt:string;updatedAt:string;state:'PENDING'|'UNKNOWN'|'CONFIRMED'|'FAILED';error:string|null}
export class ReplayError extends Error{constructor(readonly status:number){super(status===403?'没有此版本的重放权限。':status===409?'重放范围、输入或原请求已变化，请查询原记录。':'重放请求失败 · HTTP '+status)}}
const root='/api/v1/integrations/workflows/metric-replays',uuid=/^[a-f0-9]{8}(-[a-f0-9]{4}){3}-[a-f0-9]{12}$(?![\s\S])/,sha=/^sha256:[a-f0-9]{64}$(?![\s\S])/
const errors=['FORBIDDEN','SOURCE_UNAVAILABLE','SOURCE_CHANGED','MAPPING_CHANGED','INVALID_SAMPLE','WINDOW_INCOMPLETE','SOURCE_WINDOW_CHANGED','WINDOW_EXPIRED','RUNTIME_UNAVAILABLE','OUTPUT_REJECTED','OUTPUT_UNCONFIRMED']
function invalid():never{throw Error('重放响应不符合契约，保留原请求进行回查。')}
function obj(v:unknown,keys:string[]):Record<string,unknown>{if(!v||typeof v!=='object'||Array.isArray(v)||Object.keys(v).length!==keys.length||keys.some(k=>!Object.hasOwn(v,k)))invalid();return v as Record<string,unknown>}
function ref(v:unknown,e:Entry){const r=obj(v,['id','revision','digest']);if(r.id!==e.definition.id||r.revision!==e.definition.revision||r.digest!==e.digest)invalid()}
async function digest(parts:string[]){const encoder=new TextEncoder(),bytes=await crypto.subtle.digest('SHA-256',encoder.encode(parts.map(v=>encoder.encode(v).length+':'+v).join('')));return 'sha256:'+Array.from(new Uint8Array(bytes),n=>n.toString(16).padStart(2,'0')).join('')}
async function seriesHash(labels:Record<string,string>){const bytes=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(Object.keys(labels).sort().map(k=>k+'='+labels[k]+'\n').join('')));return Array.from(new Uint8Array(bytes),n=>n.toString(16).padStart(2,'0')).join('')}
const canonical=(ms:number)=>new Date(ms).toISOString().replace('.000Z','Z')
export function replayEligible(e:Entry){return e.state==='PUBLISHED'&&e.definition.source.kind==='ZABBIX_METRIC'&&Boolean(e.definition.source.configuration&&e.definition.source.metric&&'mappingPin' in e.definition.target&&e.definition.target.mappingPin)}
export async function parseReplayPlan(v:unknown,e:Entry,c?:ReplayCommand):Promise<ReplayPlan>{
 const p=obj(v,['schemaVersion','requestId','reference','commandDigest','from','till','createdAt','updatedAt','expiresAt','purpose','outputPolicy','notifications','actions','state','proof','error']);ref(p.reference,e)
 const from=logPosition(p.from),till=logPosition(p.till),at=logPosition(p.createdAt),updated=logPosition(p.updatedAt),expires=logPosition(p.expiresAt)
 if(p.schemaVersion!=='2.0'||typeof p.requestId!=='string'||!uuid.test(p.requestId)||p.notifications!==false||p.actions!==false||p.purpose!=='REBUILD_METRIC_PROJECTION'||p.outputPolicy!=='ISOLATED_METRIC_SERIES'||!['PREPARING','READY','FAILED'].includes(String(p.state))||till-from!==60000000000n||from%1000000000n||at<till+10000000000n||from<at-86400000000000n||updated<at||expires-at!==600000000000n||(p.state==='READY')!==(p.proof!==null)||(p.state==='FAILED')!==(p.error!==null)||p.error!==null&&(!errors.includes(String(p.error))||String(p.error).startsWith('OUTPUT_')))invalid()
 if(p.commandDigest!==await digest(['metric-replay-plan-v1',e.definition.id,String(e.definition.revision),e.digest,String(p.from),String(p.till)]))invalid()
 if(c&&(p.requestId!==c.requestId||p.from!==c.from||p.till!==c.till||e.definition.id!==c.id||e.definition.revision!==c.revision||e.digest!==c.digest))invalid()
 if(p.proof!==null){const q=obj(p.proof,['inputDigest','batchDigest','inputCount','filtered','collapsed','labels','timestamps']);if(!sha.test(String(q.inputDigest))||!sha.test(String(q.batchDigest))||!['inputCount','filtered','collapsed'].every(k=>Number.isSafeInteger(q[k])&&Number(q[k])>=0&&Number(q[k])<=60)||!Array.isArray(q.timestamps)||q.timestamps.length>60||Number(q.filtered)+Number(q.collapsed)+q.timestamps.length!==q.inputCount)invalid()
  const timestamps=q.timestamps as unknown[];if(timestamps.some((t,i)=>!Number.isSafeInteger(t)||BigInt(Number(t))*1000000n<from||BigInt(Number(t))*1000000n>=till||i>0&&Number(timestamps[i-1])>=Number(t)))invalid()
  if(!q.labels||typeof q.labels!=='object'||Array.isArray(q.labels))invalid();const l=q.labels as Record<string,string>,s=e.definition.source,t=e.definition.target;const required=['tenant_id','owner_scope','source_instance_id','external_item_id','host_external_id','metric_key','unit','mapping_id','mapping_revision','mapping_digest','workflow_id','workflow_revision','workflow_digest','configuration_digest','data_mode','collection_mode','replay_id']
  if(Object.keys(l).length>24||required.some(k=>!Object.hasOwn(l,k))||Object.entries(l).some(([k,v])=>!required.includes(k)&&!/^dim_[A-Za-z_][A-Za-z0-9_]{0,59}$/.test(k)||typeof v!=='string'||! /^[a-zA-Z0-9_.:/%\-]{1,128}$(?![\s\S])/.test(v))||! /^[a-f0-9]{64}$(?![\s\S])/.test(l.owner_scope)||l.replay_id!==p.requestId||l.collection_mode!=='REPLAY_60S'||l.data_mode!=='zabbix-jsonrpc'||l.workflow_id!==e.definition.id||l.workflow_revision!==String(e.definition.revision)||l.workflow_digest!==e.digest||l.source_instance_id!==s.instanceId||l.external_item_id!==s.metric?.itemId||l.host_external_id!==s.metric?.hostId||l.configuration_digest!==s.configuration?.digest||!('mappingPin' in t)||l.mapping_id!==t.mappingPin?.id||l.mapping_revision!==String(t.mappingPin?.revision)||l.mapping_digest!==t.mappingPin?.digest||l.metric_key!==t.metricKey)invalid()
  if(!timestamps.length&&q.batchDigest!==await digest(['workflow-metric-batch-v1',await seriesHash(l)]))invalid()
 }
 return v as ReplayPlan
}
export async function parseReplayReceipt(v:unknown,e:Entry,p:ReplayPlan,c?:ReplayExecute):Promise<ReplayReceipt>{const r=obj(v,['schemaVersion','requestId','planId','reference','commandDigest','acceptedAt','updatedAt','state','error']);ref(r.reference,e);if(!p.proof||r.schemaVersion!=='2.0'||typeof r.requestId!=='string'||!uuid.test(r.requestId)||r.planId!==p.requestId||!['PENDING','UNKNOWN','CONFIRMED','FAILED'].includes(String(r.state))||logPosition(r.acceptedAt)<logPosition(p.createdAt)||logPosition(r.updatedAt)<logPosition(r.acceptedAt)||['UNKNOWN','FAILED'].includes(String(r.state))!==(r.error!==null)||r.error!==null&&!errors.includes(String(r.error))||r.state==='UNKNOWN'&&r.error!=='OUTPUT_UNCONFIRMED'||r.state==='FAILED'&&r.error==='OUTPUT_UNCONFIRMED'||r.commandDigest!==await digest(['metric-replay-execute-v1',p.requestId,p.proof.inputDigest,p.proof.batchDigest])||c&&(r.requestId!==c.requestId||r.planId!==c.planId||p.proof.inputDigest!==c.inputDigest||p.proof.batchDigest!==c.batchDigest))invalid();return v as ReplayReceipt}
const options=(signal:AbortSignal)=>({signal,error:(status:number)=>new ReplayError(status)})
export async function replayPlans(e:Entry,signal:AbortSignal){const v=obj(await platformClient.request(root+'/workflows/'+e.definition.id+'/versions/'+e.definition.revision+'/'+encodeURIComponent(e.digest)+'/plans',options(signal)),['items','truncated']);if(!Array.isArray(v.items)||v.items.length>20||typeof v.truncated!=='boolean')invalid();const items=await Promise.all(v.items.map(v=>parseReplayPlan(v,e)));if(new Set(items.map(p=>p.requestId)).size!==items.length)invalid();return {items,truncated:v.truncated}}
export async function replayPlan(e:Entry,id:string,signal:AbortSignal,c?:ReplayCommand){if(!uuid.test(id))throw Error('请输入完整重放 UUID。');return parseReplayPlan(await platformClient.request(root+'/plans/'+id,options(signal)),e,c)}
export async function createReplay(e:Entry,c:ReplayCommand,signal:AbortSignal){return parseReplayPlan(await platformClient.request(root+'/plans',{...options(signal),method:'POST',body:c}),e,c)}
export async function executeReplay(e:Entry,p:ReplayPlan,c:ReplayExecute,signal:AbortSignal){return parseReplayReceipt(await platformClient.request(root+'/execute',{...options(signal),method:'POST',body:c}),e,p,c)}
export async function replayReceipt(e:Entry,p:ReplayPlan,c:ReplayExecute,signal:AbortSignal){return parseReplayReceipt(await platformClient.request(root+'/commands/'+c.requestId,options(signal)),e,p,c)}
export async function replayExecution(e:Entry,p:ReplayPlan,signal:AbortSignal){const v=obj(await platformClient.request(root+'/plans/'+p.requestId+'/execution',options(signal)),['receipt']);return v.receipt===null?null:parseReplayReceipt(v.receipt,e,p)}
export async function verifyReplay(e:Entry,p:ReplayPlan,r:ReplayReceipt,signal:AbortSignal){const next=await parseReplayReceipt(await platformClient.request(root+'/commands/'+r.requestId+'/verification',{...options(signal),method:'POST'}),e,p);if(next.requestId!==r.requestId)invalid();return next}
export function replayWindow(requestId:string,e:Entry,start:string):ReplayCommand{const ms=Date.parse(start);if(!Number.isFinite(ms)||ms%1000)throw Error('请输入精确到秒的历史起始时间。');return {requestId,id:e.definition.id,revision:e.definition.revision,digest:e.digest,from:canonical(ms),till:canonical(ms+60000)}}
