import { platformClient } from './http.ts'
import type { Entry } from './workflows.ts'
import type { RuntimeAuthorization } from './workflow-runtime.ts'

export type MetricStreamTask={workflowId:string;revision:number;digest:string;generation:number;state:'RUNNING'|'STOPPED'|'FAILED'|'ABANDONED';cursor:string;pendingBatchId:string|null;confirmedWindows:number;confirmedPoints:number;sessionBatches:number;updatedAt:string;error:string|null;authorization?:RuntimeAuthorization}
export type MetricStreamBatch={id:string;workflowId:string;revision:number;digest:string;from:string;till:string;createdAt:string;updatedAt:string;state:'IN_FLIGHT'|'CONFIRMED'|'UNKNOWN'|'FAILED';inputCount:number;filtered:number;collapsed:number;labels:Record<string,string>;batchDigest:string;timestamps:number[];error:string|null;reconcilesBatchId?:string|null;latePoints?:number}
export type MetricStreamStatus={schemaVersion:'2.0';available:boolean;mode:'LOCAL_DEV_METRIC'|'DELEGATED_METRIC';windowSeconds:60;settleSeconds:10;maxBatchPoints:600;maxSessionBatches:20;maxHistoryRequests:20;lookbackSeconds:60;task:MetricStreamTask|null;batches:MetricStreamBatch[];control?:{generation:number;startAllowed:boolean;recoveryClosed:boolean}}
export type MetricStreamCommand={requestId:string;id:string;revision:number;digest:string;expectedGeneration:number;operation:'START'|'STOP'|'RESUME'}
export type MetricStreamReceipt={requestId:string;operation:MetricStreamCommand['operation'];commandDigest:string;acceptedAt:string;task:MetricStreamTask}
export class MetricStreamError extends Error{constructor(readonly status:number){super('持续采集请求失败（HTTP '+status+'）')}}
const uuid=/^[a-f0-9]{8}(-[a-f0-9]{4}){3}-[a-f0-9]{12}$/,digest=/^sha256:[a-f0-9]{64}$/
const errors=['FORBIDDEN','AUTHORIZATION_REVOKED','AUTHORIZATION_EXPIRED','EXECUTION_LIMIT','SOURCE_CHANGED','MAPPING_CHANGED','SOURCE_UNAVAILABLE','INVALID_SAMPLE','CAPACITY','WINDOW_EXPIRED','OUTPUT_REJECTED','OUTPUT_UNCONFIRMED','RUNTIME_UNAVAILABLE','WINDOW_INCOMPLETE','SOURCE_WINDOW_CHANGED']
function invalid():never{throw new Error('持续采集响应不符合契约')}
function object(v:unknown,keys:string[],optional:string[]=[]):Record<string,unknown>{if(!v||typeof v!=='object'||Array.isArray(v)||keys.some(k=>!Object.hasOwn(v,k))||Object.keys(v).some(k=>!keys.includes(k)&&!optional.includes(k)))invalid();return v as Record<string,unknown>}
function number(v:unknown,min:number,max:number){if(!Number.isSafeInteger(v)||Number(v)<min||Number(v)>max)invalid()}
function date(v:unknown){if(typeof v!=='string'||v.length>40||!Number.isFinite(Date.parse(v)))invalid();return Date.parse(v)}
function reference(v:Record<string,unknown>,entry:Entry){if(v.workflowId!==entry.definition.id||v.revision!==entry.definition.revision||v.digest!==entry.digest)invalid()}
function task(v:unknown,entry:Entry):MetricStreamTask{
 const t=object(v,['workflowId','revision','digest','generation','state','cursor','pendingBatchId','confirmedWindows','confirmedPoints','sessionBatches','updatedAt','error'],['authorization']);reference(t,entry);number(t.generation,1,1000001);number(t.confirmedWindows,0,200);number(t.confirmedPoints,0,Number(t.confirmedWindows)*600);number(t.sessionBatches,0,20)
 if(!['RUNNING','STOPPED','FAILED','ABANDONED'].includes(String(t.state))||(['FAILED','ABANDONED'].includes(String(t.state)))!==(t.error!==null)||t.error!==null&&!errors.includes(String(t.error))||t.pendingBatchId!==null&&!uuid.test(String(t.pendingBatchId))||date(t.cursor)%1000!==0||date(t.updatedAt)<date(t.cursor))invalid()
 if(t.state==='ABANDONED'&&(t.pendingBatchId===null||t.authorization!==undefined||t.error!=='OUTPUT_UNCONFIRMED'))invalid();if(t.authorization!==undefined){const a=object(t.authorization,['id','issuedAt','expiresAt','maxBatches','consumedBatches']);if(!uuid.test(String(a.id)))invalid();number(a.maxBatches,1,20);number(a.consumedBatches,0,Number(a.maxBatches));const issued=date(a.issuedAt),expires=date(a.expiresAt);if(expires<=issued||expires-issued>900000||issued>date(t.updatedAt)||a.consumedBatches!==t.sessionBatches)invalid()}
 return v as MetricStreamTask
}
export function parseMetricStream(v:unknown,entry:Entry):MetricStreamStatus{
 const s=object(v,['schemaVersion','available','mode','windowSeconds','settleSeconds','maxBatchPoints','maxSessionBatches','maxHistoryRequests','lookbackSeconds','task','batches'],['control']);if(s.schemaVersion!=='2.0'||typeof s.available!=='boolean'||!['LOCAL_DEV_METRIC','DELEGATED_METRIC'].includes(String(s.mode))||s.windowSeconds!==60||s.settleSeconds!==10||s.maxBatchPoints!==600||s.maxSessionBatches!==20||s.maxHistoryRequests!==20||s.lookbackSeconds!==60||!Array.isArray(s.batches)||s.batches.length>20)invalid();const t=s.task===null?null:task(s.task,entry);if(t&&s.mode==='DELEGATED_METRIC'&&t.state!=='ABANDONED'&&!t.authorization||t&&s.mode==='LOCAL_DEV_METRIC'&&t.authorization)invalid()
 const seen=new Set<string>();for(const raw of s.batches){const b=object(raw,['id','workflowId','revision','digest','from','till','createdAt','updatedAt','state','inputCount','filtered','collapsed','labels','batchDigest','timestamps','error'],['reconcilesBatchId','latePoints']);reference(b,entry);if(!uuid.test(String(b.id))||seen.has(String(b.id))||!digest.test(String(b.batchDigest))||!['IN_FLIGHT','CONFIRMED','UNKNOWN','FAILED'].includes(String(b.state)))invalid();seen.add(String(b.id));number(b.inputCount,0,600);number(b.filtered,0,600);number(b.collapsed,0,600);const from=date(b.from),till=date(b.till),created=date(b.createdAt);if(from%1000!==0||till-from!==60000||created<till+10000||date(b.updatedAt)<created||!Array.isArray(b.timestamps)||b.timestamps.length>600||Number(b.filtered)+Number(b.collapsed)+b.timestamps.length!==b.inputCount)invalid();let previous=-1;for(const stamp of b.timestamps){number(stamp,0,Number.MAX_SAFE_INTEGER);if(Number(stamp)<=previous||Number(stamp)<from||Number(stamp)>=till)invalid();previous=Number(stamp)}
  if(Object.hasOwn(b,'reconcilesBatchId')!==Object.hasOwn(b,'latePoints'))invalid();if(b.latePoints!==undefined){number(b.latePoints,0,b.timestamps.length);if(b.reconcilesBatchId===null?b.latePoints!==0:!uuid.test(String(b.reconcilesBatchId))||b.reconcilesBatchId===b.id||Number(b.latePoints)<1)invalid()}
  if(['IN_FLIGHT','CONFIRMED'].includes(String(b.state))?b.error!==null:b.error!==(b.state==='UNKNOWN'?'OUTPUT_UNCONFIRMED':'OUTPUT_REJECTED'))invalid();if(b.timestamps.length===0&&b.state!=='CONFIRMED')invalid()
  const required=['tenant_id','owner_scope','source_instance_id','external_item_id','host_external_id','metric_key','unit','mapping_id','mapping_revision','mapping_digest','workflow_id','workflow_revision','workflow_digest','configuration_digest','data_mode','collection_mode'];const labels=object(b.labels,required,Object.keys(b.labels as object).filter(k=>/^dim_[A-Za-z_][A-Za-z0-9_]{0,59}$/.test(k)));if(Object.keys(labels).length>24||Object.values(labels).some(x=>typeof x!=='string'||!/^[a-zA-Z0-9_.:/%\\-]{1,128}$/.test(x)))invalid()
  const original=s.batches.find((x:any)=>x.id===b.reconcilesBatchId) as MetricStreamBatch|undefined;if(original&&(original.state!=='CONFIRMED'||original.from!==b.from||original.till!==b.till||original.timestamps.some(stamp=>!(b.timestamps as number[]).includes(stamp))||Number(b.latePoints)!==b.timestamps.length-original.timestamps.length))invalid()
  const source=entry.definition.source,target=entry.definition.target;if(!('mappingPin' in target)||!target.mappingPin||labels.workflow_id!==entry.definition.id||labels.workflow_revision!==String(entry.definition.revision)||labels.workflow_digest!==entry.digest||labels.source_instance_id!==source.instanceId||labels.external_item_id!==source.metric?.itemId||labels.host_external_id!==source.metric?.hostId||labels.configuration_digest!==source.configuration?.digest||labels.metric_key!==target.metricKey||labels.mapping_id!==target.mappingPin.id||labels.mapping_revision!==String(target.mappingPin.revision)||labels.mapping_digest!==target.mappingPin.digest||labels.data_mode!=='zabbix-jsonrpc'||labels.collection_mode!=='WINDOW_60S'||!/^[a-f0-9]{64}$/.test(String(labels.owner_scope)))invalid()
  if(t&&t.pendingBatchId===b.id&&(b.state==='CONFIRMED'||from!==date(t.cursor)))invalid()
 }
 if(s.control!==undefined){const c=object(s.control,['generation','startAllowed','recoveryClosed']);number(c.generation,0,1000001);if(typeof c.startAllowed!=='boolean'||typeof c.recoveryClosed!=='boolean'||c.startAllowed&&(Number(c.generation)>=999999||c.recoveryClosed)||t&&Number(c.generation)<t.generation||t&&(t.state==='ABANDONED')!==c.recoveryClosed)invalid()}
 return v as MetricStreamStatus
}
export function parseMetricStreamReceipt(v:unknown,entry:Entry,id:string,command?:MetricStreamCommand):MetricStreamReceipt{
 const r=object(v,['requestId','operation','commandDigest','acceptedAt','task']),t=task(r.task,entry);if(r.requestId!==id||!['START','STOP','RESUME'].includes(String(r.operation))||!digest.test(String(r.commandDigest))||date(r.acceptedAt)!==date(t.updatedAt)||t.state!==(r.operation==='STOP'?'STOPPED':'RUNNING')||command&&(r.operation!==command.operation||t.generation!==command.expectedGeneration+1))invalid();return v as MetricStreamReceipt
}
const root='/api/v1/integrations/workflows/metric-streams'
const options=(signal:AbortSignal)=>({signal,error:(status:number)=>new MetricStreamError(status)})
export async function metricStreamStatus(entry:Entry,signal:AbortSignal){return parseMetricStream(await platformClient.request(root+'/workflows/'+encodeURIComponent(entry.definition.id)+'?revision='+entry.definition.revision,options(signal)),entry)}
export async function metricStreamControl(entry:Entry,command:MetricStreamCommand,signal:AbortSignal){const {operation,...body}=command;return parseMetricStreamReceipt(await platformClient.request(root+'/'+operation.toLowerCase(),{...options(signal),method:'POST',body:body}),entry,command.requestId,command)}
export async function metricStreamReceipt(entry:Entry,command:MetricStreamCommand,signal:AbortSignal){return parseMetricStreamReceipt(await platformClient.request(root+'/commands/'+command.requestId,options(signal)),entry,command.requestId,command)}
export async function metricStreamVerify(entry:Entry,batchId:string,signal:AbortSignal){return parseMetricStream(await platformClient.request(root+'/workflows/'+encodeURIComponent(entry.definition.id)+'/verification',{...options(signal),method:'POST',body:{batchId}}),entry)}
