import {platformClient} from './http.ts'
import type {Entry} from './workflows.ts'
export type DiagnosticNode={nodeId:string;type:string;received:number;accepted:number;rejected:number;filtered:number;skipped:number;issues:Record<string,number>}
export type DiagnosticResult={coverage:'COMPLETE'|'PARTIAL'|'UNAVAILABLE';sampleRate:null;received:number|null;accepted:number|null;rejected:number|null;filtered:number|null;unknown:number|null;schemaMismatch:number|null;missingIdentity:number|null;invalidTimestamp:number|null;unitMismatch:number|null;nodes:DiagnosticNode[]}
export const sourceFailures=['UNAVAILABLE','ACCESS_DENIED','INCOMPLETE_WINDOW','INVALID_RESPONSE','METADATA_CHANGED','SOURCE_KEY_CHANGED','VALUE_TYPE_CHANGED','UNIT_CHANGED','OTHER_FAILURE'] as const
export type DiagnosticSource={attempts:1;completed:0|1;failed:0|1;received:number|null;failureCode:typeof sourceFailures[number]|null;startedAt:string;completedAt:string}
export type DiagnosticDispatch={id:string;enqueuedAt:string;startedAt:string}
export type DiagnosticObservation={id:string;reference:{id:string;revision:number;digest:string};kind:'HOST_SCAN'|'METRIC_STREAM'|'LOG_STREAM';generation:number;state:'CHECKED'|'REJECTED'|'SOURCE_FAILED';from:string|null;till:string|null;startedAt:string;completedAt:string;queueWaitMillis:number|null;relatedBatchId:string|null;error:string|null;result:DiagnosticResult;sourceRead?:DiagnosticSource|null;dispatch?:DiagnosticDispatch|null}
export type DiagnosticReport={schemaVersion:'2.0';asOf:string;reference:DiagnosticObservation['reference'];observations:DiagnosticObservation[];truncated:boolean}
export class DiagnosticError extends Error{constructor(readonly status:number){super('检查统计读取失败（HTTP '+status+'）')}}
const uuid=/^[a-f0-9]{8}(-[a-f0-9]{4}){3}-[a-f0-9]{12}$/
const issues=['UNKNOWN_FIELD','MISSING_REQUIRED','NULL_REQUIRED','TOO_LONG','EMPTY_REQUIRED','ENUM_MISMATCH','OUT_OF_RANGE','TYPE_MISMATCH','NUMERIC_LIMIT','TRANSFORM_FAILED','MERGE_CONFLICT']
const errors=['AUTHORIZATION_EXPIRED','AUTHORIZATION_REVOKED','BACKLOG_LIMIT','CAPACITY','EXECUTION_LIMIT','FORBIDDEN','INVALID_SAMPLE','MAPPING_CHANGED','MODEL_CHANGED','OPERATOR_CHANGED','OPERATOR_PIN_REQUIRED','OUTPUT_REJECTED','OUTPUT_UNAVAILABLE','OUTPUT_UNCONFIRMED','RUNTIME_UNAVAILABLE','SOURCE_CHANGED','SOURCE_UNAVAILABLE','SOURCE_WINDOW_CHANGED','TASK_CHANGED','WINDOW_EXPIRED','WINDOW_INCOMPLETE']
const counts=['received','accepted','rejected','filtered','unknown','schemaMismatch','missingIdentity','invalidTimestamp','unitMismatch'] as const
function invalid():never{throw new Error('检查统计响应不符合契约')}
function object(v:unknown,keys:readonly string[],optional:readonly string[]=[]):Record<string,unknown>{if(!v||typeof v!=='object'||Array.isArray(v)||Object.keys(v).length<keys.length||Object.keys(v).length>keys.length+optional.length||Object.keys(v).some(k=>!keys.includes(k)&&!optional.includes(k))||keys.some(k=>!Object.hasOwn(v,k)))invalid();return v as Record<string,unknown>}
function integer(v:unknown,max=1000,min=0):number{if(!Number.isSafeInteger(v)||Number(v)<min||Number(v)>max)invalid();return Number(v)}
function instant(v:unknown):bigint{if(typeof v!=='string')invalid();const m=/^(\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2})(?:\.(\d{3}|\d{6}|\d{9}))?Z$/.exec(v);if(!m)invalid();const ms=Date.parse(m[1]+'Z'),f=m[2]??'';if(!Number.isFinite(ms)||ms<0||new Date(ms).toISOString().replace('.000Z','Z')!==m[1]+'Z'||f&&(f.endsWith('000')||/^0+$/.test(f)))invalid();return BigInt(ms)*1000000n+BigInt(f.padEnd(9,'0')||'0')}
function reference(value:unknown,e:Entry){const r=object(value,['id','revision','digest']);if(r.id!==e.definition.id||r.revision!==e.definition.revision||r.digest!==e.digest)invalid()}
export function parseDiagnosticObservation(value:unknown,e:Entry,expectedId?:string):DiagnosticObservation{
 const o=object(value,['id','reference','kind','generation','state','from','till','startedAt','completedAt','queueWaitMillis','relatedBatchId','error','result'],['sourceRead','dispatch']);reference(o.reference,e)
 const kind=({ZABBIX_HOST:'HOST_SCAN',ZABBIX_METRIC:'METRIC_STREAM',ZABBIX_LOG:'LOG_STREAM'} as Record<string,string>)[e.definition.source.kind]
 if(!kind||o.kind!==kind||typeof o.id!=='string'||!uuid.test(o.id)||expectedId&&o.id!==expectedId||o.relatedBatchId!==null&&(typeof o.relatedBatchId!=='string'||!uuid.test(o.relatedBatchId))||!['CHECKED','REJECTED','SOURCE_FAILED'].includes(String(o.state))||(o.state==='CHECKED')!==(o.error===null)||o.error!==null&&!errors.includes(String(o.error))||instant(o.completedAt)<instant(o.startedAt))invalid();integer(o.generation,1000001,1)
 if(o.dispatch===undefined||o.dispatch===null){if(o.queueWaitMillis!==null)invalid()}
 else{const dispatch=object(o.dispatch,['id','enqueuedAt','startedAt']);if(typeof dispatch.id!=='string'||!uuid.test(dispatch.id))invalid();const enqueued=instant(dispatch.enqueuedAt),started=instant(dispatch.startedAt);integer(o.queueWaitMillis,3600000);if(started<enqueued||started-enqueued>3600000000000n||started>instant(o.startedAt)||BigInt(Number(o.queueWaitMillis))!==(started-enqueued)/1000000n)invalid()}
 const r=object(o.result,['coverage','sampleRate',...counts,'nodes']);if(r.sampleRate!==null||!Array.isArray(r.nodes)||r.nodes.length>16)invalid()
 if(r.coverage==='UNAVAILABLE'){if(counts.some(k=>r[k]!==null)||r.nodes.length!==0||o.state!=='SOURCE_FAILED')invalid()}
 else{for(const k of counts.slice(0,8))integer(r[k]);if(r.unitMismatch!==null)integer(r.unitMismatch);if(Number(r.accepted)+Number(r.rejected)+Number(r.filtered)+Number(r.unknown)!==r.received||['schemaMismatch','missingIdentity','invalidTimestamp','unitMismatch'].some(k=>r[k]!==null&&Number(r[k])>Number(r.rejected))||r.coverage!==(r.unknown===0?'COMPLETE':'PARTIAL')||o.state==='SOURCE_FAILED'||o.state==='CHECKED'&&(r.rejected!==0||r.unknown!==0)||o.state==='REJECTED'&&r.rejected===0)invalid()}
 if(kind==='HOST_SCAN'){if(o.from!==null||o.till!==null||r.received!==null&&Number(r.received)>5||r.unitMismatch!==null)invalid()}
 else{const from=instant(o.from),till=instant(o.till);if(from%1000000000n!==0n||till-from!==60000000000n||instant(o.startedAt)<till+10000000000n||kind==='METRIC_STREAM'&&r.received!==null&&Number(r.received)>600||kind==='LOG_STREAM'&&r.unitMismatch!==null)invalid()}
 if(o.sourceRead!==undefined&&o.sourceRead!==null){
  const source=object(o.sourceRead,['attempts','completed','failed','received','failureCode','startedAt','completedAt']);integer(source.completed,1);integer(source.failed,1)
  if(source.attempts!==1||Number(source.completed)+Number(source.failed)!==1||instant(source.startedAt)<instant(o.startedAt)||instant(source.completedAt)<instant(source.startedAt)||instant(source.completedAt)>instant(o.completedAt))invalid()
  if(source.completed===1){integer(source.received,kind==='HOST_SCAN'?5:kind==='METRIC_STREAM'?600:1000);if(source.failureCode!==null||r.received!==null&&r.received!==source.received)invalid()}
  else{if(source.received!==null||!sourceFailures.includes(source.failureCode as typeof sourceFailures[number])||o.state!=='SOURCE_FAILED')invalid();const reason=String(source.failureCode),expected=({UNAVAILABLE:'SOURCE_UNAVAILABLE',INCOMPLETE_WINDOW:'WINDOW_INCOMPLETE',INVALID_RESPONSE:'INVALID_SAMPLE',METADATA_CHANGED:'SOURCE_CHANGED',SOURCE_KEY_CHANGED:'SOURCE_CHANGED',VALUE_TYPE_CHANGED:'SOURCE_CHANGED',UNIT_CHANGED:'SOURCE_CHANGED'} as Record<string,string>)[reason];if(expected&&o.error!==expected||reason==='ACCESS_DENIED'&&!['FORBIDDEN','AUTHORIZATION_EXPIRED','AUTHORIZATION_REVOKED'].includes(String(o.error))||kind==='HOST_SCAN'&&['UNIT_CHANGED','SOURCE_KEY_CHANGED','VALUE_TYPE_CHANGED'].includes(reason))invalid()}
 }
 const seen=new Set<string>();for(const raw of r.nodes){const n=object(raw,['nodeId','type','received','accepted','rejected','filtered','skipped','issues']);const declared=e.definition.nodes.find(node=>node.id===n.nodeId);if(!declared||declared.type!==n.type||typeof n.nodeId!=='string'||seen.has(n.nodeId))invalid();seen.add(n.nodeId);for(const k of ['received','accepted','rejected','filtered','skipped'])integer(n[k]);if(Number(n.accepted)+Number(n.rejected)+Number(n.filtered)!==n.received||Number(n.received)+Number(n.skipped)>Number(r.received)-Number(r.unknown)||!n.issues||typeof n.issues!=='object'||Array.isArray(n.issues))invalid();for(const [code,count] of Object.entries(n.issues)){if(!issues.includes(code))invalid();integer(count,Number(n.rejected),1)}}
 return value as DiagnosticObservation
}
export function parseDiagnosticReport(value:unknown,e:Entry):DiagnosticReport{const r=object(value,['schemaVersion','asOf','reference','observations','truncated']);reference(r.reference,e);const at=instant(r.asOf);if(r.schemaVersion!=='2.0'||typeof r.truncated!=='boolean'||!Array.isArray(r.observations)||r.observations.length>20||r.truncated&&r.observations.length!==20)invalid();const seen=new Set<string>();for(const raw of r.observations){const o=parseDiagnosticObservation(raw,e);if(seen.has(o.id)||instant(o.completedAt)>at)invalid();seen.add(o.id)}return value as DiagnosticReport}
const root=(e:Entry)=>'/api/v1/integrations/workflows/quality/workflows/'+encodeURIComponent(e.definition.id)+'/versions/'+e.definition.revision+'/diagnostics'
const options=(signal:AbortSignal)=>({signal,error:(status:number)=>new DiagnosticError(status)})
export async function diagnosticReport(e:Entry,signal:AbortSignal){return parseDiagnosticReport(await platformClient.request(root(e),options(signal)),e)}
export async function diagnosticObservation(e:Entry,id:string,signal:AbortSignal){if(!uuid.test(id))throw new Error('请输入完整检查 UUID');return parseDiagnosticObservation(await platformClient.request(root(e)+'/'+id,options(signal)),e,id)}
