import { platformClient } from './http.ts'
import type { Entry, Page } from './workflows.ts'

// Wire authority: contracts/schemas/v2/workflow-metric-output-*.schema.json.
export type MetricOutputCommand = { requestId:string; id:string; revision:number; digest:string; previewId:string; samples:{timestamp:string;sourceKey:string;value:string}[] }
export type MetricOutputReceipt = {requestId:string;workflowId:string;revision:number;digest:string;previewId:string;commandDigest:string;createdAt:string;updatedAt:string;state:'PENDING'|'CONFIRMED'|'UNKNOWN'|'FAILED';accepted:number;filtered:number;collapsed:number;confirmed:number;failed:number;unknown:number;error:string|null;labels:Record<string,string>;seriesHash:string;batchDigest:string;timestamps:number[]}
export type MetricOutputData = {requestId:string;queriedAt:string;dataMode:'time-series';expectedPoints:number;proofMatches:boolean;points:{timestampMillis:number;value:string}[]}
export class MetricOutputError extends Error {constructor(readonly status:number,message:string){super(message)}}
const uuid=/^[a-f0-9]{8}(-[a-f0-9]{4}){3}-[a-f0-9]{12}$/, digest=/^sha256:[a-f0-9]{64}$/
function invalid():never {throw new Error('指标输出结果不符合契约，请查询原请求回执')}
function object(v:unknown,keys:string[]):Record<string,unknown>{if(!v||typeof v!=='object'||Array.isArray(v)||Object.keys(v).length!==keys.length||keys.some(k=>!Object.hasOwn(v,k)))invalid();return v as Record<string,unknown>}
function integer(v:unknown,min:number,max:number){if(!Number.isSafeInteger(v)||Number(v)<min||Number(v)>max)invalid()}
function date(v:unknown){if(typeof v!=='string'||v.length>40||!/^\d{4}-\d\d-\d\dT/.test(v)||!Number.isFinite(Date.parse(v)))invalid()}
async function sha(value:string){const bytes=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(value));return [...new Uint8Array(bytes)].map(b=>b.toString(16).padStart(2,'0')).join('')}
async function hash(parts:string[]){return 'sha256:'+await sha(parts.map(p=>new TextEncoder().encode(p).length+':'+p).join(''))}
async function commandDigest(c:MetricOutputCommand){const parts=['MANUAL_SAMPLE'];for(const row of c.samples){parts.push('record');Object.entries(row).sort(([a],[b])=>a<b?-1:a>b?1:0).forEach(([key,value])=>parts.push(key,'text',value))}return hash(['workflow-metric-output-v1',c.id,String(c.revision),c.digest,c.previewId,await hash(parts)])}
const requiredLabels=['tenant_id','owner_scope','source_instance_id','external_item_id','host_external_id','metric_key','unit','mapping_id','mapping_revision','mapping_digest','workflow_id','workflow_revision','workflow_digest','configuration_digest','data_mode']
export async function parseMetricOutput(value:unknown,entry?:Entry,command?:MetricOutputCommand):Promise<MetricOutputReceipt>{
 const r=object(value,['requestId','workflowId','revision','digest','previewId','commandDigest','createdAt','updatedAt','state','accepted','filtered','collapsed','confirmed','failed','unknown','error','labels','seriesHash','batchDigest','timestamps'])
 if(!uuid.test(String(r.requestId))||!uuid.test(String(r.previewId))||typeof r.workflowId!=='string'||!/^[a-z][a-z0-9_-]{0,47}$/.test(r.workflowId))invalid()
 integer(r.revision,1,10000);for(const key of ['digest','commandDigest','batchDigest'])if(!digest.test(String(r[key])))invalid();date(r.createdAt);date(r.updatedAt)
 if(Date.parse(String(r.updatedAt))<Date.parse(String(r.createdAt))||!['PENDING','UNKNOWN','CONFIRMED','FAILED'].includes(String(r.state)))invalid()
 for(const key of ['accepted','filtered','collapsed','confirmed','failed','unknown'])integer(r[key],0,5)
 if(Number(r.accepted)<1||Number(r.accepted)+Number(r.filtered)>5||!Array.isArray(r.timestamps)||r.timestamps.length<1||r.timestamps.length>5)invalid()
 let previous=-1;for(const timestamp of r.timestamps){integer(timestamp,0,Date.parse(String(r.createdAt)));if(timestamp<=previous)invalid();previous=timestamp}
 const count=r.timestamps.length
 if(r.collapsed!==Number(r.accepted)-count||Number(r.confirmed)+Number(r.failed)+Number(r.unknown)!==count)invalid()
 if(r.state==='CONFIRMED'?(r.confirmed!==count||r.failed!==0||r.unknown!==0||r.error!==null):r.state==='FAILED'?(r.failed!==count||r.confirmed!==0||r.unknown!==0||!['OUTPUT_REJECTED','FORBIDDEN','SOURCE_CHANGED','MAPPING_CHANGED','RUNTIME_UNAVAILABLE'].includes(String(r.error))):(r.confirmed!==0||r.failed!==0||r.unknown!==count||(r.state==='PENDING'?r.error!==null:r.error!=='OUTPUT_UNCONFIRMED')))invalid()
 if(!r.labels||typeof r.labels!=='object'||Array.isArray(r.labels)||Object.keys(r.labels).length>24)invalid()
 const labels=r.labels as Record<string,string>
 if(requiredLabels.some(key=>!Object.hasOwn(labels,key))||Object.entries(labels).some(([key,v])=>!requiredLabels.includes(key)&&!/^dim_[A-Za-z_][A-Za-z0-9_]{0,59}$/.test(key)||typeof v!=='string'||!/^[a-zA-Z0-9_.:/%\-]{1,128}$/.test(v)))invalid()
 if(labels.workflow_id!==r.workflowId||labels.workflow_revision!==String(r.revision)||labels.workflow_digest!==r.digest||labels.data_mode!=='zabbix-jsonrpc'||!/^[a-f0-9]{64}$/.test(labels.owner_scope)||r.seriesHash!==await sha(Object.entries(labels).sort(([a],[b])=>a<b?-1:a>b?1:0).map(([key,v])=>key+'='+v+'\n').join('')))invalid()
 if(entry){const d=entry.definition,t=d.target;if(!('mappingPin' in t)||!t.mappingPin||r.workflowId!==d.id||r.revision!==d.revision||r.digest!==entry.digest||labels.source_instance_id!==d.source.instanceId||labels.external_item_id!==d.source.metric?.itemId||labels.host_external_id!==d.source.metric?.hostId||labels.configuration_digest!==d.source.configuration?.digest||labels.metric_key!==t.metricKey||labels.mapping_id!==t.mappingPin.id||labels.mapping_revision!==String(t.mappingPin.revision)||labels.mapping_digest!==t.mappingPin.digest)invalid()}
 if(command&&(r.requestId!==command.requestId||r.previewId!==command.previewId||r.commandDigest!==await commandDigest(command)))invalid()
 return value as MetricOutputReceipt
}
const messages:Record<string,string>={PREVIEW_REQUIRED:'读取样本已过期或不匹配，请先确认原写入结果',SOURCE_CHANGED:'固定来源已变化',MAPPING_CHANGED:'固定映射已变化',FORBIDDEN:'当前身份没有此来源或指标的权限',SOURCE_UNAVAILABLE:'指标输出服务或固定来源不可用',CONFLICT:'原请求内容不匹配，请查询原回执',CAPACITY:'输出回执已达到容量上限',BUSY:'输出并发已满，请稍后显式重试'}
const request=(path:string,signal:AbortSignal,body?:unknown)=>platformClient.request('/api/v1/integrations/workflows/metric-outputs'+path,{signal,body,error:(status,code)=>new MetricOutputError(status,messages[code]??'指标输出请求失败（HTTP '+status+'）')})
export async function metricOutputCapability(signal:AbortSignal){const r=object(await request('',signal),['schemaVersion','mode','available','maxPoints']);if(r.schemaVersion!=='2.0'||r.mode!=='FIXED_METRIC_SAMPLE'||typeof r.available!=='boolean'||r.maxPoints!==5)invalid();return r.available}
export async function metricOutputHistory(entry:Entry,signal:AbortSignal):Promise<Page<MetricOutputReceipt>>{const page=object(await request('/workflows/'+encodeURIComponent(entry.definition.id)+'/receipts',signal),['items','truncated']);if(!Array.isArray(page.items)||page.items.length>20||typeof page.truncated!=='boolean')invalid();const items=await Promise.all(page.items.map(value=>parseMetricOutput(value)));if(items.some(r=>r.workflowId!==entry.definition.id)||new Set(items.map(r=>r.requestId)).size!==items.length)invalid();return {items,truncated:page.truncated}}
export async function writeMetricOutput(entry:Entry,command:MetricOutputCommand,signal:AbortSignal){return parseMetricOutput(await request('',signal,command),entry,command)}
export async function readMetricOutput(entry:Entry,id:string,signal:AbortSignal,verify=false,command?:MetricOutputCommand){const result=await parseMetricOutput(await request('/commands/'+encodeURIComponent(id)+(verify?'/verification':''),signal),entry,command);if(result.requestId!==id)invalid();return result}
export async function metricOutputPoints(receipt:MetricOutputReceipt,signal:AbortSignal):Promise<MetricOutputData>{const r=object(await request('/commands/'+encodeURIComponent(receipt.requestId)+'/points',signal),['requestId','queriedAt','dataMode','expectedPoints','proofMatches','points']);date(r.queriedAt);if(r.requestId!==receipt.requestId||r.dataMode!=='time-series'||r.expectedPoints!==receipt.timestamps.length||typeof r.proofMatches!=='boolean'||!Array.isArray(r.points)||r.points.length>receipt.timestamps.length)invalid();let previous=-1;const proof=['workflow-metric-batch-v1',receipt.seriesHash];for(const value of r.points){const point=object(value,['timestampMillis','value']);integer(point.timestampMillis,0,Number.MAX_SAFE_INTEGER);if(!receipt.timestamps.includes(Number(point.timestampMillis))||Number(point.timestampMillis)<=previous||typeof point.value!=='string'||point.value.length>400||!/^-?(0|[1-9][0-9]*)(\.[0-9]+)?$/.test(point.value)||!Number.isFinite(Number(point.value)))invalid();previous=Number(point.timestampMillis);let decimal=point.value;if(decimal.includes('.'))decimal=decimal.replace(/0+$/,'').replace(/\.$/,'');if(/^-?0$/.test(decimal))decimal='0';proof.push(String(point.timestampMillis),decimal)}if(r.proofMatches&&(r.points.length!==receipt.timestamps.length||await hash(proof)!==receipt.batchDigest))invalid();return r as MetricOutputData}
