import { platformClient } from './http.ts'
import type { Entry } from './workflows.ts'
import type { RuntimeAuthorization } from './workflow-runtime.ts'

export type LogStreamTask={workflowId:string;revision:number;digest:string;generation:number;state:'RUNNING'|'STOPPED'|'FAILED'|'ABANDONED';cursor:string;pendingBatchId:string|null;confirmedWindows:number;confirmedRecords:number;sessionBatches:number;updatedAt:string;error:string|null;authorization?:RuntimeAuthorization}
export type LogStreamBatch={id:string;workflowId:string;revision:number;digest:string;from:string;till:string;createdAt:string;updatedAt:string;state:'IN_FLIGHT'|'CONFIRMED'|'UNKNOWN'|'FAILED';inputCount:number;filtered:number;deduplicated:number;indices:number[];positions:string[];inputDigest:string;batchDigest:string;error:string|null;reconcilesBatchId:string|null}
export type LogStreamStatus={schemaVersion:'2.0';available:boolean;mode:'LOCAL_DEV_LOG'|'DELEGATED_LOG';windowSeconds:60;settleSeconds:10;maxBatchRecords:1000;maxSessionBatches:20;maxHistoryRequests:20;lookbackSeconds:60;task:LogStreamTask|null;batches:LogStreamBatch[];resumeAllowed?:boolean;uncertainBatchIds?:string[];control?:{generation:number;startAllowed:boolean;recoveryClosed:boolean}}
export type LogStreamCommand={requestId:string;id:string;revision:number;digest:string;expectedGeneration:number;operation:'START'|'STOP'|'RESUME'}
export type LogStreamReceipt={requestId:string;operation:LogStreamCommand['operation'];commandDigest:string;acceptedAt:string;task:LogStreamTask}
export type LogStreamRecord={index:number;position:string;eventTime:string;body:string;severityText:string|null;serviceName:string|null;traceId:string|null;spanId:string|null}
export type LogStreamData={batchId:string;readAt:string;storage:'clickhouse';expectedRecords:number;complete:boolean;afterIndex:number;nextIndex:number|null;records:LogStreamRecord[]}
export class LogStreamError extends Error{constructor(readonly status:number){super('日志采集请求失败（HTTP '+status+'）')}}
const uuid=/^[a-f0-9]{8}(-[a-f0-9]{4}){3}-[a-f0-9]{12}$/,digest=/^sha256:[a-f0-9]{64}$/
const errors=['FORBIDDEN','AUTHORIZATION_REVOKED','AUTHORIZATION_EXPIRED','EXECUTION_LIMIT','SOURCE_CHANGED','SOURCE_UNAVAILABLE','INVALID_SAMPLE','WINDOW_INCOMPLETE','SOURCE_WINDOW_CHANGED','CAPACITY','WINDOW_EXPIRED','OUTPUT_REJECTED','OUTPUT_UNCONFIRMED','RUNTIME_UNAVAILABLE','OPERATOR_CHANGED','OPERATOR_PIN_REQUIRED']
function invalid():never{throw new Error('日志采集响应不符合契约')}
function object(v:unknown,keys:string[],optional:string[]=[]):Record<string,unknown>{if(!v||typeof v!=='object'||Array.isArray(v)||keys.some(k=>!Object.hasOwn(v,k))||Object.keys(v).some(k=>!keys.includes(k)&&!optional.includes(k)))invalid();return v as Record<string,unknown>}
function number(v:unknown,min:number,max:number){if(!Number.isSafeInteger(v)||Number(v)<min||Number(v)>max)invalid()}
// Java Instant emits UTC with fractional digits grouped in threes. Preserve all nine digits.
export function logPosition(v:unknown):bigint{
 if(typeof v!=='string')invalid();const m=/^(\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2})(?:\.(\d{3}|\d{6}|\d{9}))?Z$(?![\s\S])/.exec(v);if(!m)invalid()
 const seconds=Date.parse(m[1]+'Z'),fraction=m[2]??'';if(!Number.isFinite(seconds)||seconds<0||new Date(seconds).toISOString().replace('.000Z','Z')!==m[1]+'Z'||fraction&&(fraction.endsWith('000')||/^0+$/.test(fraction)))invalid()
 return BigInt(seconds)*1000000n+BigInt(fraction.padEnd(9,'0')||'0')
}
function reference(v:Record<string,unknown>,entry:Entry){if(v.workflowId!==entry.definition.id||v.revision!==entry.definition.revision||v.digest!==entry.digest)invalid()}
function task(v:unknown,entry:Entry):LogStreamTask{
 const t=object(v,['workflowId','revision','digest','generation','state','cursor','pendingBatchId','confirmedWindows','confirmedRecords','sessionBatches','updatedAt','error'],['authorization']);reference(t,entry);number(t.generation,1,1000001);number(t.confirmedWindows,0,200);number(t.confirmedRecords,0,Number(t.confirmedWindows)*1000);number(t.sessionBatches,0,20)
 if(!['RUNNING','STOPPED','FAILED','ABANDONED'].includes(String(t.state))||(['FAILED','ABANDONED'].includes(String(t.state)))!==(t.error!==null)||t.error!==null&&!errors.includes(String(t.error))||t.pendingBatchId!==null&&!uuid.test(String(t.pendingBatchId))||logPosition(t.cursor)%1000000000n!==0n||logPosition(t.updatedAt)<logPosition(t.cursor)||t.generation===1000001&&!['STOPPED','ABANDONED'].includes(String(t.state)))invalid()
 if(t.state==='ABANDONED'&&(t.pendingBatchId===null||t.authorization!==undefined||t.error!=='OUTPUT_UNCONFIRMED'))invalid();if(t.authorization!==undefined){const a=object(t.authorization,['id','issuedAt','expiresAt','maxBatches','consumedBatches']);if(!uuid.test(String(a.id)))invalid();number(a.maxBatches,1,20);number(a.consumedBatches,0,Number(a.maxBatches));const issued=logPosition(a.issuedAt),expires=logPosition(a.expiresAt);if(expires<=issued||expires-issued>900000000000n||issued>logPosition(t.updatedAt)||a.consumedBatches!==t.sessionBatches)invalid()}
 return v as LogStreamTask
}
export function parseLogStream(v:unknown,entry:Entry):LogStreamStatus{
 const s=object(v,['schemaVersion','available','mode','windowSeconds','settleSeconds','maxBatchRecords','maxSessionBatches','maxHistoryRequests','lookbackSeconds','task','batches'],['control','resumeAllowed','uncertainBatchIds']);if(s.schemaVersion!=='2.0'||typeof s.available!=='boolean'||!['LOCAL_DEV_LOG','DELEGATED_LOG'].includes(String(s.mode))||s.windowSeconds!==60||s.settleSeconds!==10||s.maxBatchRecords!==1000||s.maxSessionBatches!==20||s.maxHistoryRequests!==20||s.lookbackSeconds!==60||!Array.isArray(s.batches)||s.batches.length>20)invalid();const t=s.task===null?null:task(s.task,entry);if(t&&s.mode==='DELEGATED_LOG'&&t.state!=='ABANDONED'&&!t.authorization||t&&s.mode==='LOCAL_DEV_LOG'&&t.authorization)invalid()
 const seen=new Set<string>();for(const raw of s.batches){const b=object(raw,['id','workflowId','revision','digest','from','till','createdAt','updatedAt','state','inputCount','filtered','deduplicated','indices','positions','inputDigest','batchDigest','error','reconcilesBatchId']);reference(b,entry);if(!uuid.test(String(b.id))||seen.has(String(b.id))||!digest.test(String(b.batchDigest))||!digest.test(String(b.inputDigest))||!['IN_FLIGHT','CONFIRMED','UNKNOWN','FAILED'].includes(String(b.state)))invalid();seen.add(String(b.id));number(b.inputCount,0,1000);number(b.filtered,0,1000);number(b.deduplicated,0,1000)
  const from=logPosition(b.from),till=logPosition(b.till),created=logPosition(b.createdAt);if(from%1000000000n!==0n||till-from!==60000000000n||created<till+10000000000n||logPosition(b.updatedAt)<created||!Array.isArray(b.indices)||!Array.isArray(b.positions)||b.positions.length!==b.inputCount||Number(b.filtered)+Number(b.deduplicated)+b.indices.length!==b.inputCount)invalid()
  let previous=-1;for(const index of b.indices){number(index,0,Number(b.inputCount)-1);if(Number(index)<=previous)invalid();previous=Number(index)}let last=-1n;for(const position of b.positions){const ns=logPosition(position);if(ns<=last||ns<from||ns>=till)invalid();last=ns}
  if(b.reconcilesBatchId===null?b.deduplicated!==0:!uuid.test(String(b.reconcilesBatchId))||b.reconcilesBatchId===b.id)invalid()
  if(['IN_FLIGHT','CONFIRMED'].includes(String(b.state))?b.error!==null:b.error!==(b.state==='UNKNOWN'?'OUTPUT_UNCONFIRMED':'OUTPUT_REJECTED'))invalid();if(b.indices.length===0&&b.state!=='CONFIRMED')invalid()
  if(t&&t.pendingBatchId===b.id&&(b.state==='CONFIRMED'||logPosition(b.reconcilesBatchId?b.till:b.from)!==logPosition(t.cursor)))invalid()
 }
 const batches=s.batches as LogStreamBatch[];for(const b of batches){const original=batches.find(x=>x.id===b.reconcilesBatchId);if(original&&(original.state!=='CONFIRMED'||original.from!==b.from||original.till!==b.till||b.inputCount<=original.inputCount||original.positions.some(x=>!b.positions.includes(x))||b.deduplicated!==original.inputCount-original.filtered||b.indices.some(i=>original.positions.includes(b.positions[i]))))invalid()}
 if(s.control!==undefined){const c=object(s.control,['generation','startAllowed','recoveryClosed']);number(c.generation,0,1000001);if(typeof c.startAllowed!=='boolean'||typeof c.recoveryClosed!=='boolean'||c.startAllowed&&(Number(c.generation)>=999999||c.recoveryClosed)||t&&Number(c.generation)<t.generation||t&&(t.state==='ABANDONED')!==c.recoveryClosed)invalid()}
 if(Object.hasOwn(s,'uncertainBatchIds')){if(!Array.isArray(s.uncertainBatchIds)||s.uncertainBatchIds.length>20||new Set(s.uncertainBatchIds).size!==s.uncertainBatchIds.length||s.uncertainBatchIds.some(id=>typeof id!=='string'||!uuid.test(id)||!batches.some(b=>b.id===id&&b.state==='FAILED'))||t?.pendingBatchId!==null&&(s.uncertainBatchIds as string[]).includes(t?.pendingBatchId??'')&&s.resumeAllowed!==false)invalid()}
 if(Object.hasOwn(s,'resumeAllowed')&&(typeof s.resumeAllowed!=='boolean'||s.resumeAllowed===true&&(!t||['RUNNING','ABANDONED'].includes(t.state)||t.generation>=999999||t.pendingBatchId!==null&&(s.batches as LogStreamBatch[]).some(b=>b.id===t.pendingBatchId&&b.state!=='FAILED'))))invalid()
 return v as LogStreamStatus
}
export async function logControlDigest(c:LogStreamCommand){const encoder=new TextEncoder(),parts=['log-stream-control-v1',c.operation,c.id,String(c.revision),c.digest,String(c.expectedGeneration)].map(x=>{const bytes=encoder.encode(x);return String(bytes.length)+':'+x});const hash=await crypto.subtle.digest('SHA-256',encoder.encode(parts.join('')));return 'sha256:'+Array.from(new Uint8Array(hash),x=>x.toString(16).padStart(2,'0')).join('')}
export async function parseLogStreamReceipt(v:unknown,entry:Entry,command:LogStreamCommand):Promise<LogStreamReceipt>{
 const r=object(v,['requestId','operation','commandDigest','acceptedAt','task']),t=task(r.task,entry);if(r.requestId!==command.requestId||r.operation!==command.operation||r.commandDigest!==await logControlDigest(command)||logPosition(r.acceptedAt)!==logPosition(t.updatedAt)||t.state!==(r.operation==='STOP'?'STOPPED':'RUNNING')||t.generation!==command.expectedGeneration+1)invalid();return v as LogStreamReceipt
}
export function parseLogStreamData(v:unknown,batch:Pick<LogStreamBatch,'id'|'indices'|'positions'>,afterIndex:number):LogStreamData{
 const d=object(v,['batchId','readAt','storage','expectedRecords','complete','afterIndex','nextIndex','records']);logPosition(d.readAt);if(d.batchId!==batch.id||d.storage!=='clickhouse'||d.expectedRecords!==batch.indices.length||typeof d.complete!=='boolean'||d.afterIndex!==afterIndex||!Array.isArray(d.records)||d.records.length>50||d.nextIndex!==null&&(!Number.isSafeInteger(d.nextIndex)||d.records.length!==50))invalid()
 let previous=afterIndex;for(const raw of d.records){const r=object(raw,['index','position','eventTime','body','severityText','serviceName','traceId','spanId']);number(r.index,0,999);if(Number(r.index)<=previous||!batch.indices.includes(Number(r.index))||r.position!==batch.positions[Number(r.index)])invalid();previous=Number(r.index);logPosition(r.position);logPosition(r.eventTime);if(typeof r.body!=='string'||!r.body.trim()||r.body.length>2048)invalid();for(const key of ['severityText','serviceName','traceId','spanId'])if(r[key]!==null&&(typeof r[key]!=='string'||(r[key] as string).length>128))invalid();if(r.traceId!==null&&!/^[a-f0-9]{32}$/.test(String(r.traceId))||r.spanId!==null&&!/^[a-f0-9]{16}$/.test(String(r.spanId)))invalid()}
 if(d.nextIndex!==null&&(d.nextIndex!==previous||!batch.indices.some(i=>i>previous)))invalid()
 if(d.complete){const expected=batch.indices.filter(i=>i>afterIndex),got=d.records as LogStreamRecord[];if(got.length!==Math.min(50,expected.length)||got.some((r,i)=>r.index!==expected[i])||(d.nextIndex===null)!==(expected.length<=50))invalid()}
 return v as LogStreamData
}
const root='/api/v1/integrations/workflows/log-streams',options=(signal:AbortSignal)=>({signal,error:(status:number)=>new LogStreamError(status)})
export async function logStreamStatus(entry:Entry,signal:AbortSignal){return parseLogStream(await platformClient.request(root+'/workflows/'+encodeURIComponent(entry.definition.id)+'?revision='+entry.definition.revision,options(signal)),entry)}
export async function logStreamControl(entry:Entry,command:LogStreamCommand,signal:AbortSignal){const {operation,...body}=command;return parseLogStreamReceipt(await platformClient.request(root+'/'+operation.toLowerCase(),{...options(signal),method:'POST',body}),entry,command)}
export async function logStreamReceipt(entry:Entry,command:LogStreamCommand,signal:AbortSignal){return parseLogStreamReceipt(await platformClient.request(root+'/commands/'+command.requestId,options(signal)),entry,command)}
export async function logStreamVerify(entry:Entry,batchId:string,signal:AbortSignal){return parseLogStream(await platformClient.request(root+'/workflows/'+encodeURIComponent(entry.definition.id)+'/verification',{...options(signal),method:'POST',body:{batchId}}),entry)}
export async function logStreamData(entry:Entry,batch:LogStreamBatch,afterIndex:number,signal:AbortSignal){return parseLogStreamData(await platformClient.request(root+'/workflows/'+encodeURIComponent(entry.definition.id)+'/batches/'+batch.id+'/records'+(afterIndex<0?'':'/after/'+afterIndex),options(signal)),batch,afterIndex)}
