import { createSignal, For, onCleanup, Show } from '@zeus-js/zeus'
import { forItem } from '../../adapters/zeus-ui/for-item.ts'
import { oidcMode, usePlatformSession } from '../../state/platform-session.ts'
import { confirmSource, readSetup, readSources, workflowLink, type Command, type Setup, type SourcePage, type SourceType } from '../../api/source-setups.ts'
import { runConnectionCheck, type SourceConnectionCheck } from '../../api/source-connection-checks.ts'
import type { Model } from '../../api/workflows.ts'

const titles:Record<SourceType,string>={ZABBIX_HOST:'Zabbix',MANUAL_SAMPLE:'JSON 手工样本',CMDB_SNAPSHOT:'CMDB 快照'}
export function SourceCenterPage(){
 const [page,setPage]=createSignal<SourcePage|null>(null),[kind,setKind]=createSignal<SourceType>('ZABBIX_HOST')
 const [name,setName]=createSignal(''),[description,setDescription]=createSignal(''),[target,setTarget]=createSignal('')
 const [busy,setBusy]=createSignal(false),[error,setError]=createSignal(''),[notice,setNotice]=createSignal('')
 const [pending,setPending]=createSignal<Command|null>(null),[view,setView]=createSignal<Setup|null>(null),[probe,setProbe]=createSignal<SourceConnectionCheck|null>(null)
 let dialog:HTMLDialogElement|null=null,focus:HTMLElement|null=null,active:AbortController|undefined,disposed=false,requestId=''
 const ready=usePlatformSession(change=>{active?.abort();active=undefined;setBusy(false);setPage(null);setPending(null);setView(null);setName('');setDescription('');setTarget('');setProbe(null);setError(change.error?.message??'');setNotice('');dialog?.close()})
 onCleanup(()=>{disposed=true;active?.abort()})
 const disabled=()=>busy()||!ready()
 const option=()=>page()?.types.find(t=>t.id===kind())
 const selectedModel=()=>page()?.models.find(m=>m.definition.id+'@'+m.definition.revision===target())
 async function run(work:(signal:AbortSignal,current:()=>boolean)=>Promise<void>){if(disabled())return;const c=new AbortController();active?.abort();active=c;setBusy(true);setError('');setNotice('');const current=()=>!disposed&&active===c&&!c.signal.aborted;try{await work(c.signal,current)}catch(e){if(current())setError(e instanceof Error?e.message:'数据源请求失败')}finally{if(current())setBusy(false)}}
 function requireSession(){if(ready())return true;setError(oidcMode?'请先在页面顶部登录平台，再选择数据源类型。':'请先在页面顶部填写平台开发 Token，再选择数据源类型。');const panel=document.querySelector<HTMLElement>('[data-platform-session]');panel?.scrollIntoView({block:'center'});const input=panel?.querySelector<HTMLInputElement>('input')??panel?.querySelector('zw-input')?.shadowRoot?.querySelector<HTMLInputElement>('input');input?.focus();return false}
 function choose(type:SourceType){if(busy()||!requireSession())return;const trigger=document.activeElement as HTMLElement;if(page()){open(type,trigger);return}void run(async(s,current)=>{const p=await readSources(s);if(!current())return;setPage(p);if(p.types.find(t=>t.id===type)?.status!=='AVAILABLE'){setError('当前身份无可用的该类型连接，请检查平台来源配置和权限。');return}open(type,trigger)})}
 function load(){if(!requireSession())return;void run(async(s,current)=>{const p=await readSources(s);if(current()){setPage(p);setNotice('已读取可用类型和本人接入配置。')}})}
 function open(type:SourceType,trigger:HTMLElement){if(!ready()||page()?.types.find(t=>t.id===type)?.status!=='AVAILABLE')return;focus=trigger;setKind(type);setView(null);setPending(null);setProbe(null);setError('');setNotice('');setName(type==='ZABBIX_HOST'?'Zabbix 主机接入':'手工样本接入');setDescription('');const m=page()?.models.find(m=>m.definition.id===(type==='ZABBIX_HOST'?'builtin.host':'builtin.service'))??page()?.models[0];setTarget(m?m.definition.id+'@'+m.definition.revision:'');requestId=crypto.randomUUID();dialog?.showModal()}
 function inspect(s:Setup){focus=document.activeElement as HTMLElement;setView(s);setKind(s.source.kind);setName(s.name);setDescription(s.description);setTarget(s.initialTarget.id+'@'+s.initialTarget.revision);setPending(null);setProbe(null);setError('');setNotice('');dialog?.showModal()}
 function close(){if(!busy())dialog?.close()}
 function go(id:string){void run(async(s,current)=>{const r=await readSetup(id,s);if(current()){dialog?.close();location.hash=workflowLink(r.workflow)}})}
 function confirm(){if(kind()==='CMDB_SNAPSHOT'||view())return;const model=selectedModel(),connection=option()?.connection;if(!pending()&&(!model||!connection||!name().trim()))return;const command=pending()??{requestId,name:name().trim(),description:description().trim(),source:{kind:kind() as 'ZABBIX_HOST'|'MANUAL_SAMPLE',instanceId:connection!.instanceId},connectionDigest:connection!.digest,target:{id:model!.definition.id,revision:model!.definition.revision,digest:model!.digest}};setPending(command);void run(async(s,current)=>{const r=await confirmSource(command,s);if(current()){setPending(null);dialog?.close();location.hash=workflowLink(r.workflow)}})}
 function test(){setProbe(null);void run(async(s,current)=>{const r=await runConnectionCheck(s);if(r.sourceInstanceId!==option()?.connection?.instanceId)throw new Error('连接配置已变化，请重新读取数据源');if(current())setProbe(r.check)})}
 return <section class="source-center" data-page="source-center">
  <header class="source-heading"><div><div class="model-eyebrow">DATA SOURCES · 数据接入</div><h2>数据源中心</h2><p>选择数据从哪里来，再把它整理成你的模型。</p></div><button type="button" disabled={busy()} onClick={load}>读取数据源</button></header>
  <Show when={!ready()}><p class="source-access-hint" role="status">{oidcMode?'尚未登录平台。请先在页面顶部登录，再创建接入配置。':'尚未建立开发会话。请在页面顶部填写平台开发 Token；刷新或会话过期后需要重新填写。'}</p></Show>
  <ol class="source-steps" aria-label="接入步骤"><li><span>1</span><div><strong>选择类型</strong><small>确定来源与数据范围</small></div></li><li><span>2</span><div><strong>配置接入</strong><small>命名并选择初始目标模型</small></div></li><li><span>3</span><div><strong>画布编排</strong><small>映射、清洗与样本预览</small></div></li></ol>
  <div class="source-section-title"><h3>选择数据源类型</h3><span>{page()?(page()?.storage==='postgres'?'PostgreSQL 持久化':'开发内存 · 重启后丢失'):ready()?'直接选择类型即可读取并配置':'先填写平台会话凭据'}</span></div>
  <div class="source-type-grid">
   <article class="source-type-card"><div class="source-card-top"><span class="source-mark source-mark-zabbix">Z</span><span class="model-pill">监控平台</span></div><h3>Zabbix</h3><p>读取已有主机采集批次，配置字段映射与默认清洗规则。</p><div class="source-card-meta"><span>Host 主机</span><span>版本化连接器</span></div><small>{page()?.types.find(t=>t.id==='ZABBIX_HOST')?.connection?.dataMode==='fixture'?'Fixture · 合成来源':page()?.types.find(t=>t.id==='ZABBIX_HOST')?.status==='AVAILABLE'?'平台已配置连接 · 连通性待测试':page()?'当前身份无可用平台连接':'读取后查看可用连接'}</small><button type="button" disabled={busy()||!!page()&&page()?.types.find(t=>t.id==='ZABBIX_HOST')?.status!=='AVAILABLE'} onClick={()=>choose('ZABBIX_HOST')}>配置 Zabbix →</button></article>
   <article class="source-type-card"><div class="source-card-top"><span class="source-mark source-mark-json">{'{ }'}</span><span class="model-pill">样本输入</span></div><h3>JSON 手工样本</h3><p>从少量样本开始，验证自定义实体字段和清洗转换逻辑。</p><div class="source-card-meta"><span>内置 / 自定义实体</span><span>1–5 条样本</span></div><small>MANUAL_SAMPLE · 样本在画布中输入</small><button type="button" disabled={busy()} onClick={()=>choose('MANUAL_SAMPLE')}>配置手工样本 →</button></article>
   <article class="source-type-card source-type-legacy"><div class="source-card-top"><span class="source-mark">▦</span><span class="model-pill">已有导入入口</span></div><h3>CMDB 快照</h3><p>导入已有资源快照，核对来源对象与资源绑定。</p><div class="source-card-meta"><span>快照导入</span><span>来源核对</span></div><small>画布配置尚未开放</small><a href="#/integrations/cmdb">前往快照导入 ↗</a></article>
  </div>
  <div class="source-section-title source-saved-heading"><div><h3>我的接入配置</h3><p>保存的接入方案与初始工作流，不代表已启动采集。</p></div><a href="#/integrations/workflows">查看全部工作流 →</a></div>
  <Show when={!page()?.setups.items.length}><div class="source-empty"><span aria-hidden="true">↳</span><div><strong>{page()?'开始你的第一份接入配置':'读取后查看已保存配置'}</strong><p>选择上方类型，确认配置后直接进入画布。</p></div></div></Show>
  <div class="source-saved-list"><For each={page()?.setups.items??[]}>{row=><SetupRow setup={forItem(row)} disabled={disabled()} inspect={()=>inspect(forItem(row))} open={()=>go(forItem(row).id)} />}</For></div>
  <Show when={page()?.setups.truncated}><p>仅显示最近20份配置；更多工作流可在工作流页查询。</p></Show>
  <p role="alert">{error()}</p><p role="status">{busy()?'正在处理…':notice()}</p>
  <dialog class="model-drawer source-drawer" aria-label="数据源配置" ref={(el:HTMLElement|null)=>{dialog=el as HTMLDialogElement|null}} onCancel={(e:Event)=>{if(busy())e.preventDefault()}} onClose={()=>focus?.focus()}>
   <header class="model-drawer-heading"><div><div class="model-eyebrow">{view()?'已保存 · 创建时配置':'步骤 2 / 3 · 配置接入'}</div><h3>{titles[kind()]}</h3></div><button type="button" class="model-close" aria-label="关闭数据源配置" disabled={busy()} onClick={close}>×</button></header>
   <div class="model-drawer-body">
    <fieldset class="model-form" disabled={disabled()||!!pending()||!!view()}><label>接入名称<input aria-label="接入名称" maxlength={80} prop:value={name()} onInput={e=>setName((e.target as HTMLInputElement).value)} /></label><label>说明<textarea aria-label="接入说明" maxlength={500} rows={2} prop:value={description()} onInput={e=>setDescription((e.target as HTMLTextAreaElement).value)} /></label>
    <Show when={!view()}><label>初始目标模型<select aria-label="初始目标模型" prop:value={target()} onChange={e=>setTarget((e.target as HTMLSelectElement).value)}><For each={page()?.models??[]}>{row=><TargetOption model={forItem(row)} selected={target} />}</For></select></label></Show></fieldset>
    <Show when={view()}><dl class="source-connection"><dt>来源实例</dt><dd>{view()?.source.instanceId}</dd><dt>创建时来源标记</dt><dd>{view()?.dataMode}</dd><dt>初始目标模型</dt><dd>{view()?.initialTarget.id+' @ '+view()?.initialTarget.revision}</dd><dt>创建时间</dt><dd>{view()?.createdAt}</dd></dl><p class="model-muted">这是创建时的配置快照。继续编排打开第一版工作流；后续修改以画布中保存的定义为准。</p></Show>
    <Show when={!view()&&kind()==='ZABBIX_HOST'}><section class="source-connection-box"><h4>使用平台已配置的连接</h4><dl class="source-connection"><dt>来源实例</dt><dd>{option()?.connection?.instanceId}</dd><dt>API 地址</dt><dd>{option()?.connection?.endpoint??'Fixture · 无外部连接'}</dd><dt>凭据引用</dt><dd>{option()?.connection?.credentialRef??'无需凭据'}</dd><dt>数据标记</dt><dd>{option()?.connection?.dataMode}</dd></dl><p>本页选择已有连接。新增地址和凭据由平台配置，暂不支持多实例新增。</p><button type="button" disabled={disabled()||!!pending()} onClick={test}>测试连接</button><Show when={probe()}><div class="source-probe" role="status"><strong>{probe()?.dataMode==='labeled-fixture'?'Fixture 自检 · 非真实连接':probe()?.reachable?'连接测试成功':'连接测试失败'}</strong><p>{'来源标记：'+probe()?.dataMode+' · 状态：'+probe()?.statusCode}</p><p>{probe()?.reportedVersion?'来源报告版本：'+probe()?.reportedVersion+'；连通性测试不等于完整采集兼容验收。':'未取得真实版本信息。'}</p></div></Show></section></Show>
    <Show when={!view()&&kind()==='MANUAL_SAMPLE'}><div class="source-connection-box"><h4>使用手工 JSON 样本</h4><p>确认后在画布输入1–5条标量对象样本，用于只读转换预览。样本正文不保存在接入配置中。</p><span class="model-pill">MANUAL_SAMPLE</span></div></Show>
    <Show when={!view()}><section class="source-next"><h4>确认后，为你准备好</h4><p>数据输入 → 字段映射 → 去除空白 → 模型校验 → 输出预览</p><small>默认规则可在画布调整；确认只保存配置和草稿，不启动采集。</small></section></Show>
    <Show when={page()?.modelsTruncated}><p>模型列表仅包含前50个自定义版本。</p></Show>
    <Show when={pending()}><p class="source-pending">确认请求已固定。若结果待确认，可按原请求查询或重试；重新配置前请先查询，避免重复创建。</p></Show><p role="alert">{error()}</p><p role="status">{busy()?'正在处理…':notice()}</p>
   </div><footer class="model-drawer-footer"><button type="button" disabled={busy()} onClick={close}>关闭</button><Show when={pending()}><button type="button" disabled={disabled()} onClick={()=>go(pending()!.requestId)}>查询确认结果</button></Show><Show when={!view()}><button type="button" class="source-primary" disabled={disabled()||!name().trim()||!selectedModel()} onClick={confirm}>{pending()?'按原配置重试':'确认并进入画布'}</button></Show><Show when={view()}><button type="button" class="source-primary" disabled={disabled()} onClick={()=>go(view()!.id)}>继续编排</button></Show></footer>
  </dialog>
 </section>
}
function TargetOption(p:{model:Model;selected:()=>string}){const value=p.model.definition.id+'@'+p.model.definition.revision;return <option value={value} prop:selected={p.selected()===value}>{p.model.definition.label+' · '+value}</option>}
function SetupRow(p:{setup:Setup;disabled:boolean;inspect:()=>void;open:()=>void}){return <article class="source-saved-row"><span class="source-mark">{p.setup.source.kind==='ZABBIX_HOST'?'Z':'{ }'}</span><div class="source-saved-info"><h4>{p.setup.name}</h4><p>{titles[p.setup.source.kind]+' · '+p.setup.dataMode+' · '+p.setup.source.instanceId+' → '+p.setup.initialTarget.id+' @ '+p.setup.initialTarget.revision}</p><small>{'接入方案已保存 · '+new Date(p.setup.createdAt).toLocaleString()}</small></div><div class="source-saved-actions"><button type="button" disabled={p.disabled} onClick={p.inspect}>查看配置</button><button type="button" disabled={p.disabled} onClick={p.open}>继续编排 →</button></div></article>}
