import { useEffect, useRef, useState } from 'react'
import { SourceConnectionDrawer, type ConnectionDraft } from '../../components/integrations/SourceConnectionDrawer.tsx'
import { readCredentials, readCredentialVersions, type CredentialPage, type CredentialVersion } from '../../api/source-credentials.ts'
import { ConnectionRejectedError, normalizeHostGroupIds, readConnection, readConnectionCommand, readConnectionHistory, readEndpoints, writeConnection, type ConnectionConfiguration, type ConnectionView, type Endpoint, type PendingConnection } from '../../api/source-connections.ts'
import type { SourceInstance } from '../../api/source-instances.ts'
import { usePlatformSession } from '../../state/platform-session.ts'
import type { PageCloseReason } from '../../state/page-workspace.ts'
const empty = (): ConnectionDraft => ({ name: '', description: '', endpointId: '', credentialId: '', versionId: '', hostGroupIds: '' })
function groupIds(value: string) { const values = value.trim().split(/[\s,]+/).filter(Boolean); if (!values.length) return null; try { return normalizeHostGroupIds(values) } catch { return null } }
export function SourceConnectionPanel(p: { active: boolean; target: { nonce: number; instance: SourceInstance | null } | null; saved: (i: SourceInstance) => void; guard: (r: PageCloseReason) => void }) {
  const dialog = useRef<HTMLDialogElement>(null), controller = useRef<AbortController | null>(null), disposed = useRef(false), reading = useRef(true), trigger = useRef<HTMLElement | null>(null), lastTarget = useRef(0), historyAttempt = useRef(false)
  const [base, setBase] = useState<SourceInstance | null>(null), [view, setView] = useState<ConnectionView | null>(null), [draft, setDraft] = useState(empty), [initial, setInitial] = useState(empty)
  const [endpoints, setEndpoints] = useState<Endpoint[] | null>(null), [credentials, setCredentials] = useState<CredentialPage | null>(null), [versions, setVersions] = useState<CredentialVersion[] | null>(null), [history, setHistory] = useState<ConnectionConfiguration[] | null>(null)
  const [busy, setBusy] = useState(false), [pending, setPending] = useState<PendingConnection | null>(null), [error, setError] = useState(''), [notice, setNotice] = useState('')
  const ready = usePlatformSession(change => { controller.current?.abort(); controller.current = null; dialog.current?.close(); setBusy(false); setPending(null); setBase(null); setView(null); setDraft(empty()); setInitial(empty()); setEndpoints(null); setCredentials(null); setVersions(null); setHistory(null); historyAttempt.current = false; setError(change.error?.message ?? ''); setNotice('') })
  const dirty = JSON.stringify(draft) !== JSON.stringify(initial)
  useEffect(() => { p.guard(pending ? { message: '连接请求结果待确认，请查询原回执。', blocked: true } : busy ? { message: '连接请求正在处理。', blocked: true } : dirty ? { message: '连接配置有未保存的修改。' } : null) }, [p.guard, pending, busy, dirty])
  useEffect(() => { disposed.current = false; return () => { disposed.current = true; controller.current?.abort(); p.guard(null) } }, [p.guard])
  useEffect(() => { if (!p.active) { dialog.current?.close(); if (reading.current) { controller.current?.abort(); controller.current = null; setBusy(false) } } }, [p.active])
  async function run(work: (signal: AbortSignal, current: () => boolean) => Promise<void>, read = true) { if (!ready || busy) return; const c = new AbortController(); controller.current?.abort(); controller.current = c; reading.current = read; setBusy(true); setError(''); setNotice(''); const current = () => !disposed.current && controller.current === c && !c.signal.aborted; try { await work(c.signal, current) } catch (cause) { if (current()) { setError(cause instanceof Error ? cause.message : '连接请求失败'); if (cause instanceof ConnectionRejectedError) setPending(null) } } finally { if (current()) setBusy(false) } }
  function populate(i: SourceInstance | null, v: ConnectionView | null) { const c = v?.connection, next = { name: i?.name ?? '', description: i?.description ?? '', endpointId: c?.endpoint.id ?? '', credentialId: c?.credentialPin.credentialId ?? '', versionId: c?.credentialPin.versionId ?? '', hostGroupIds: c?.hostGroupIds.join(', ') ?? '' }; setBase(i); setView(v); setDraft(next); setInitial(next); setHistory(null); historyAttempt.current = false }
  function load(i: SourceInstance | null) { void run(async (signal, current) => { const [es, cs, v] = await Promise.all([readEndpoints(signal), readCredentials(signal), i ? readConnection(i.id, signal) : Promise.resolve(null)]); const vs = v?.connection ? await readCredentialVersions(v.connection.credentialPin.credentialId, signal) : null; if (!current()) return; setEndpoints(es); setCredentials(cs); setVersions(vs); populate(v?.instance ?? i, v); if (!cs.vaultAvailable) setError('凭据存储当前不可用'); else if (!(v?.canConfigure ?? cs.canConfigure)) setError('当前身份没有连接配置权限'); else if (cs.truncated) setNotice('凭据列表仅显示当前范围的前20项') }) }
  useEffect(() => { if (!p.target || lastTarget.current === p.target.nonce || !ready || !p.active) return; lastTarget.current = p.target.nonce; trigger.current = document.activeElement as HTMLElement; dialog.current?.showModal(); if (pending || dirty) { setNotice('保留了尚未完成的连接配置，请继续处理或放弃修改'); return }; populate(p.target.instance, null); setEndpoints(null); setCredentials(null); setVersions(null); load(p.target.instance) }, [p.target, ready, p.active])
  function credentialChange(id: string) { setDraft(d => ({ ...d, credentialId: id, versionId: '' })); setVersions(null); if (!id) return; void run(async (signal, current) => { const vs = await readCredentialVersions(id, signal); if (current()) setVersions(vs) }) }
  function accept(result: { instance: SourceInstance; connection: ConnectionConfiguration }) { const v: ConnectionView = { ...result, availability: 'AVAILABLE', canConfigure: true }; populate(result.instance, v); setPending(null); p.saved(result.instance); setNotice('连接配置已保存，可在实例的连接与字段中测试或发现') }
  const ep = endpoints?.find(e => e.id === draft.endpointId), version = versions?.find(v => v.pin.versionId === draft.versionId && !v.revoked), credential = credentials?.items.find(c => c.id === draft.credentialId && c.state === 'ACTIVE')
  const selectedGroups = groupIds(draft.hostGroupIds)
  const canSave = ready && !!endpoints && !!credentials?.vaultAvailable && !!(base ? view?.canConfigure && base.state === 'ACTIVE' && base.source.kind === 'ZABBIX_HOST' : credentials?.canConfigure) && !!draft.name.trim() && !!ep && !!credential && !!version && !!selectedGroups && version.pin.credentialId === credential.id && dirty
  function save() { if (!canSave || busy || pending || !ep || !version || !selectedGroups) return; const requestId = crypto.randomUUID(), command = { requestId, name: draft.name.trim(), description: draft.description, endpointPin: { id: ep.id, digest: ep.digest }, credentialPin: version.pin, hostGroupIds: selectedGroups, ...(base ? { expectedEditVersion: base.editVersion } : {}) }, c: PendingConnection = { id: base?.id ?? requestId, command, previous: base }; setPending(c); void run(async (signal, current) => { const result = await writeConnection(c, signal); if (current()) accept(result) }, false) }
  function lookup() { if (!pending) return; void run(async (signal, current) => { const result = await readConnectionCommand(pending, signal); if (current()) accept(result) }, false) }
  function historyRead(force = false) { if (!base || pending || busy || !force && historyAttempt.current) return; historyAttempt.current = true; void run(async (signal, current) => { const items = await readConnectionHistory(base.id, signal); if (current()) setHistory(items) }) }
  return <SourceConnectionDrawer dialog={dialog} editing={!!base} view={view} draft={draft} endpoints={endpoints} credentials={credentials?.items ?? null} versions={versions} history={history} busy={busy} pending={!!pending} canSave={canSave} dirty={dirty} error={error} notice={notice} change={setDraft} credentialChange={credentialChange} save={save} lookup={lookup} reload={() => { if (!pending && !dirty) load(base) }} discard={() => { if (!pending) { setDraft(initial); setVersions(null); load(base) } }} historyRead={historyRead} closed={() => { if (reading.current) { controller.current?.abort(); controller.current = null; setBusy(false) }; trigger.current?.focus() }}/>
}
