import { useEffect, useRef, useState } from 'react'
import { Button } from '../../components/ui/button.tsx'
import { SourceCredentialDrawer } from '../../components/integrations/SourceCredentialDrawer.tsx'
import { SourceCredentialTable } from '../../components/integrations/SourceCredentialTable.tsx'
import { IntegrationSearchField } from '../../components/integrations/IntegrationSearchField.tsx'
import { CredentialRejectedError, readCredential, readCredentialCommand, readCredentials, readCredentialVersions, writeCredential, type CredentialCommand, type CredentialPage, type CredentialVersion, type SourceCredential } from '../../api/source-credentials.ts'
import { usePlatformSession } from '../../state/platform-session.ts'
import { useInitialPageRead } from '../../state/initial-page-read.ts'
import type { PageCloseReason } from '../../state/page-workspace.ts'
export function SourceCredentialPanel(p: { active: boolean; guard: (reason: PageCloseReason) => void }) {
  const [page, setPage] = useState<CredentialPage | null>(null), [selected, setSelected] = useState<SourceCredential | null>(null), [versions, setVersions] = useState<CredentialVersion[] | null>(null)
  const [query, setQuery] = useState(''), [name, setName] = useState(''), [secretPresent, setSecretPresent] = useState(false), [busy, setBusy] = useState(false), [pending, setPending] = useState<CredentialCommand | null>(null), [error, setError] = useState(''), [notice, setNotice] = useState('')
  const [dialogOpen, setDialogOpen] = useState(false)
  const [historyAttempted, setHistoryAttempted] = useState(false)
  const dialog = useRef<HTMLDialogElement>(null), secret = useRef<HTMLInputElement>(null), trigger = useRef<HTMLElement | null>(null), controller = useRef<AbortController | null>(null), disposed = useRef(false), reading = useRef(true)
  function clearSecret() { if (secret.current) secret.current.value = ''; setSecretPresent(false) }
  function show() { dialog.current?.showModal(); setDialogOpen(true) }
  const ready = usePlatformSession(change => { controller.current?.abort(); controller.current = null; clearSecret(); setPage(null); setSelected(null); setVersions(null); setHistoryAttempted(false); setQuery(''); setName(''); setPending(null); setBusy(false); setError(change.error?.message ?? ''); setNotice(''); dialog.current?.close() })
  const dirty = secretPresent || (selected ? name !== selected.name : !!name)
  useEffect(() => { p.guard(pending ? { message: '凭据请求结果待确认，请先查询原请求回执。', blocked: true } : busy ? { message: '凭据请求正在处理。', blocked: true } : dirty ? { message: '凭据有未提交的修改。' } : null) }, [p.guard, pending, busy, dirty])
  useEffect(() => { disposed.current = false; return () => { disposed.current = true; controller.current?.abort(); if (secret.current) secret.current.value = ''; p.guard(null) } }, [p.guard])
  useEffect(() => { if (!p.active && reading.current) { controller.current?.abort(); controller.current = null; setBusy(false) } }, [p.active])
  async function run(work: (signal: AbortSignal, current: () => boolean) => Promise<void>, read = true) { if (!ready || busy) return; const c = new AbortController(); controller.current?.abort(); controller.current = c; reading.current = read; setBusy(true); setError(''); setNotice(''); const current = () => !disposed.current && controller.current === c && !c.signal.aborted; try { await work(c.signal, current) } catch (cause) { if (current()) { setError(cause instanceof Error ? cause.message : '凭据请求失败'); if (cause instanceof CredentialRejectedError) setPending(null) } } finally { if (current()) setBusy(false) } }
  function load() { if (pending || dirty) return; void run(async (signal, current) => { const r = await readCredentials(signal); if (current()) setPage(r) }) }
  useInitialPageRead({ ready, loaded: !!page, pending: busy, blocked: !p.active, read: load })
  function populate(c: SourceCredential) { setSelected(c); setName(c.name); setHistoryAttempted(false); clearSecret() }
  function open(id?: string) { if (busy || pending) return; trigger.current = document.activeElement as HTMLElement; if (dirty) { setError('当前凭据有未提交的修改，请先保存或放弃。'); show(); return }; if (!id) { if (!page?.canConfigure || !page.secretWriteAvailable) return; setSelected(null); setName(''); setVersions(null); clearSecret(); setError(''); setNotice(''); show(); return }; if (selected?.id === id) { show(); return }; void run(async (signal, current) => { const c = await readCredential(id, signal); if (current()) { populate(c); setVersions(null); show() } }) }
  function accept(c: SourceCredential, original: CredentialCommand) { populate(c); setPending(null); setNotice('凭据请求已确认'); if (original.operation === 'REVOKE_VERSION') setVersions(previous => previous?.map(v => v.pin.revision === original.revokeRevision ? { ...v, revoked: true } : v) ?? null); else setVersions(null); setPage(previous => previous ? { ...previous, items: [c, ...previous.items.filter(i => i.id !== c.id)].sort((a, b) => Date.parse(b.updatedAt) - Date.parse(a.updatedAt)).slice(0, 20), truncated: previous.truncated || !previous.items.some(i => i.id === c.id) && previous.items.length === 20 } : previous) }
  function submit(state: SourceCredential['state'], revision?: number) { if (busy || pending || !page?.canConfigure || selected?.state === 'REVOKED') return; const value = revision === undefined && state === 'ACTIVE' ? secret.current?.value || null : null; if (value && !page.secretWriteAvailable || !selected && !value || value !== null && !/^[!-~]{1,4096}$/.test(value)) { setError('凭据值需为1–4096个可见ASCII字符，且当前连接必须支持安全提交'); return }; const requestId = crypto.randomUUID(), command: CredentialCommand = { requestId, credentialId: selected?.id ?? requestId, operation: revision ? 'REVOKE_VERSION' : selected ? 'EDIT' : 'CREATE', expectedEditVersion: selected?.editVersion ?? 0, name: name.trim(), state, changesSecret: value !== null, previous: selected, ...(revision ? { revokeRevision: revision } : {}) }; clearSecret(); setPending(command); void run(async (signal, current) => { const c = await writeCredential(command, value, signal); if (current()) accept(c, command) }, false) }
  function lookup() { if (!pending) return; const command = pending; void run(async (signal, current) => { const c = await readCredentialCommand(command, signal); if (current()) accept(c, command) }, false) }
  function reset() { if (pending) return; if (!selected) { clearSecret(); setName(''); setError(''); setNotice('已放弃凭据输入'); return }; void run(async (signal, current) => { const c = await readCredential(selected.id, signal); if (current()) { populate(c); setVersions(null); setNotice('已读取最新凭据') } }) }
  function history() { if (!selected || pending || busy || !ready) return; setHistoryAttempted(true); void run(async (signal, current) => { const items = await readCredentialVersions(selected.id, signal); if (current()) setVersions(items) }) }
  const rows = page?.items.filter(c => (c.name + ' ' + c.id).toLowerCase().includes(query.trim().toLowerCase())) ?? []
  return <section className="source-credential-panel" aria-label="凭据管理" hidden={!p.active} inert={!p.active}><div className="source-instance-toolbar"><IntegrationSearchField label="搜索接入凭据" placeholder="搜索凭据名称或标识" value={query} onChange={setQuery} clearLabel="清除凭据搜索"/><Button type="button" variant="outline" disabled={!ready || busy || !!pending || dirty} onClick={load}>刷新凭据列表</Button><Button type="button" disabled={!ready || busy || !!pending || dirty || !page?.canConfigure || !page.secretWriteAvailable} onClick={() => open()}>新增凭据</Button></div>
    {page && !page.vaultAvailable ? <p role="status">凭据密钥存储尚未配置，当前不能新增或轮换凭据。</p> : page && !page.secretWriteAvailable ? <p role="status">当前连接不支持安全提交凭据值。</p> : null}{page && !page.canConfigure ? <p role="status">当前身份可以查看本人凭据，尚未获配置权限。</p> : null}
    <SourceCredentialTable items={rows} disabled={!ready || busy || !!pending} loaded={!!page} busy={busy} failed={!!error} filtered={!!query.trim()} truncated={page?.truncated ?? false} manage={open}/>
    {error && !dialogOpen ? <p role="alert">{error}</p> : null}{pending ? <Button type="button" variant="outline" disabled={!ready} onClick={show}>继续核对凭据请求</Button> : dirty && !dialogOpen ? <Button type="button" variant="outline" disabled={!ready || busy} onClick={show}>继续编辑凭据</Button> : null}
    <SourceCredentialDrawer dialog={dialog} secret={secret} selected={selected} name={name} secretPresent={secretPresent} versions={versions} historyAttempted={historyAttempted} active={p.active} page={page} ready={ready} busy={busy} pending={!!pending} error={error} notice={notice} nameChange={setName} secretChange={setSecretPresent} save={() => submit('ACTIVE')} revoke={revision => submit(revision ? 'ACTIVE' : 'REVOKED', revision)} lookup={lookup} versionsRead={history} reset={reset} closed={() => { setDialogOpen(false); trigger.current?.focus() }}/>
  </section>
}
