#!/usr/bin/env python3
"""Generate static workflow metadata from contracts; development tool only."""
import argparse
import hashlib
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CATALOG = ROOT / 'contracts/catalog/opsweave-transform-operators-1.0.0.json'
JAVA = ROOT / 'modules/integration/src/main/java/com/acme/opsweave/integration/domain/GeneratedWorkflowOperators.java'
TS = ROOT / 'apps/web-console/src/api/generated/workflow-operators.ts'


def digest(parts):
    h = hashlib.sha256()
    for value in parts:
        raw = value.encode('utf-8')
        h.update(str(len(raw)).encode('ascii') + b':' + raw)
    return 'sha256:' + h.hexdigest()


def semantic_parts(operator):
    parts = ['opsweave-operator-v1', operator['type'], operator['version'],
             operator['implementation'], operator['configKind']]
    parts.append(str(len(operator['parameters'])))
    for parameter in operator['parameters']:
        parts.extend([parameter['name'], parameter['kind']])
    for side in ['input', 'output']:
        port = operator[side]
        parts.append(side)
        parts.extend(['none'] if port is None else
                     [port['id'], port['kind'], str(port['minimum']), str(port['maximum'])])
    return parts


def validate(catalog):
    if set(catalog) != {'schemaVersion', 'catalogVersion', 'digest', 'operators'} or catalog['schemaVersion'] != '2.0' or catalog['catalogVersion'] != '1.0.0':
        raise ValueError('Invalid catalog version or fields')
    expected = {'SOURCE', 'MAP', 'TRIM', 'EMPTY_TO_NULL', 'DEFAULT', 'ENUM_MAP', 'SCALE', 'FILTER', 'MERGE', 'VALIDATE', 'OUTPUT'}
    operators = catalog['operators']
    if len(operators) != len(expected) or {o['type'] for o in operators} != expected:
        raise ValueError('Catalog must match the built-in execution allowlist')
    for o in operators:
        if set(o) != {'type', 'version', 'digest', 'implementation', 'label', 'hint', 'category', 'configKind', 'parameters', 'input', 'output'}:
            raise ValueError('Invalid operator fields')
        if o['version'] != '1' or o['implementation'] != 'builtin-' + o['type'].lower().replace('_', '-') + '-v1':
            raise ValueError('Unsupported built-in implementation')
        if o['configKind'] not in ['EMPTY', 'FIELD_MAPPING', 'PARAMETERS'] or o['category'] not in ['STRUCTURE', 'TRANSFORM', 'ROUTING']:
            raise ValueError('Invalid operator kind')
        for p in o['parameters']:
            if set(p) != {'name', 'kind'} or p['kind'] not in ['FIELD', 'TEXT', 'FACTOR']:
                raise ValueError('Invalid parameter')
        for side in ['input', 'output']:
            p = o[side]
            if p is not None and (set(p) != {'id', 'kind', 'minimum', 'maximum'} or p['id'] != ('in' if side == 'input' else 'out') or p['kind'] not in ['RECORD_V1', 'VALIDATED_RECORD_V1'] or not 1 <= p['minimum'] <= p['maximum'] <= 16):
                raise ValueError('Invalid port')
        if digest(semantic_parts(o)) != o['digest']:
            raise ValueError('Operator digest mismatch: ' + o['type'])
    parts = ['opsweave-operator-catalog-v1', catalog['catalogVersion']]
    for o in sorted(operators, key=lambda o: (o['type'], o['version'])):
        parts.extend([o['type'], o['version'], o['digest']])
    if digest(parts) != catalog['digest']:
        raise ValueError('Catalog digest mismatch')


def outputs(catalog):
    def quote(s):
        return json.dumps(s, ensure_ascii=False)

    def port(p):
        return 'null' if p is None else 'new Port(%s, PortKind.%s, %d, %d)' % (quote(p['id']), p['kind'], p['minimum'], p['maximum'])

    entries = []
    for o in catalog['operators']:
        params = ', '.join('new Parameter(%s, ParameterKind.%s)' % (quote(p['name']), p['kind']) for p in o['parameters'])
        entries.append('        new Descriptor(WorkflowDefinition.Type.%s, %s, %s, %s, %s, %s, Category.%s, ConfigKind.%s, List.of(%s), %s, %s)' %
                       (o['type'], quote(o['version']), quote(o['digest']), quote(o['implementation']), quote(o['label']), quote(o['hint']), o['category'], o['configKind'], params, port(o['input']), port(o['output'])))
    java = '''// Generated by scripts/generate_workflow_operators.py. Do not edit.
package com.acme.opsweave.integration.domain;
import java.util.List;
import static com.acme.opsweave.integration.domain.WorkflowOperators.*;
final class GeneratedWorkflowOperators {
    private GeneratedWorkflowOperators() {}
    static final String VERSION = "1.0.0";
    static final String DIGEST = %s;
    static List<Descriptor> descriptors() { return List.of(
%s
    ); }
}
''' % (quote(catalog['digest']), ',\n'.join(entries))
    ts = '// Generated by scripts/generate_workflow_operators.py. Do not edit.\nexport const builtInOperatorCatalog = ' + json.dumps(catalog, ensure_ascii=False, indent=2) + ' as const\n'
    # Configuration alternatives are generated into the existing v2 definition.
    path = ROOT / 'contracts/schemas/v2/workflow-definition.schema.json'
    schema = json.loads(path.read_text(encoding='utf-8'))
    field = {'type': 'string', 'pattern': '^[a-zA-Z][a-zA-Z0-9_]{0,47}$', 'not': {'enum': ['tenantId', 'tenant_id', 'Authorization', 'authorization', 'constructor', 'prototype', 'secret', 'token', 'password']}}
    alternatives = []
    for o in catalog['operators']:
        config = {'type': 'object', 'additionalProperties': False, 'properties': {}}
        if o['configKind'] == 'FIELD_MAPPING':
            config = {'type': 'object', 'minProperties': 1, 'maxProperties': 32, 'propertyNames': field, 'additionalProperties': field}
        elif o['parameters']:
            config['required'] = [p['name'] for p in o['parameters']]
            for p in o['parameters']:
                config['properties'][p['name']] = field if p['kind'] == 'FIELD' else {'type': 'string', 'maxLength': 64 if p['kind'] == 'FACTOR' else 512}
                if p['kind'] == 'FACTOR':
                    config['properties'][p['name']]['pattern'] = '^-?(0|[1-9][0-9]*)(\\.[0-9]+)?$'
        alternatives.append({'type': 'object', 'additionalProperties': False, 'required': ['id', 'type', 'version', 'config'], 'properties': {'id': {'type': 'string', 'pattern': '^[a-z][a-z0-9_-]{0,31}$'}, 'type': {'const': o['type']}, 'version': {'const': o['version']}, 'operatorDigest': {'type': 'string', 'pattern': '^sha256:[a-f0-9]{64}$'}, 'config': config}})
    schema['properties']['nodes']['items']['oneOf'] = alternatives
    example = json.loads((ROOT / 'contracts/examples/v2/workflow-definition.json').read_text(encoding='utf-8'))
    pins = {operator['type']: operator['digest'] for operator in catalog['operators']}
    for node in example['nodes']:
        node['operatorDigest'] = pins[node['type']]
    return {JAVA: java, TS: ts, path: json.dumps(schema, ensure_ascii=False, indent=2) + '\n',
            ROOT / 'contracts/examples/v2/workflow-pinned-definition.json': json.dumps(example, ensure_ascii=False, indent=2) + '\n'}


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--write', action='store_true')
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    if args.write == args.check:
        parser.error('Choose --write or --check')
    catalog = json.loads(CATALOG.read_text(encoding='utf-8'))
    validate(catalog)
    mismatches = []
    for path, body in outputs(catalog).items():
        if args.write:
            path.parent.mkdir(parents=True, exist_ok=True)
            if not path.exists() or path.read_text(encoding='utf-8') != body:
                path.write_text(body, encoding='utf-8', newline='\n')
        elif not path.exists() or path.read_text(encoding='utf-8') != body:
            mismatches.append(path.relative_to(ROOT).as_posix())
    if mismatches:
        raise SystemExit('Generated workflow metadata differs: ' + ', '.join(mismatches))
    print('Workflow operator metadata: 11 built-in operators verified' if args.check else 'Workflow operator metadata generated')


if __name__ == '__main__':
    main()
