import type { LogOutputCapability,LogOutputReceipt,LogOutputData } from '../../api/workflow-log-outputs.ts'
import './workflow-log-output.css'
export function WorkflowLogOutputPanel(p:{capability:LogOutputCapability|null;busy:boolean;pendingId:string|null;missing:boolean;receipt:LogOutputReceipt|null;records:LogOutputReceipt[];truncated:boolean;data:LogOutputData|null;error:string;notice:string;write:()=>void;query:()=>void;verify:()=>void;read:()=>void;refresh:()=>void;resubmit:()=>void;dismiss:()=>void;select:(receipt:LogOutputReceipt)=>void}){
 const states={PENDING:'待确认',UNKNOWN:'结果待确认',CONFIRMED:'已确认',FAILED:'写入失败'},r=p.receipt
 return <section className="workflow-log-output" aria-label="日志批次输出"><header><h3>日志批次输出</h3><button disabled={p.busy||Boolean(p.pendingId)} onClick={p.refresh}>刷新记录</button></header>
  <p>{p.capability?.mode==='SOURCE_LOG_SAMPLE'?'从固定日志项读取最近10分钟的最多5条样本，按已发布规则转换后写入；这是一批样本，写入后回读确认。':'使用测试区的手工样本，最多5条。日志时间须在执行前24小时内；写入后回读完整批次进行确认。'}</p>
  {p.capability?.available===false?<p role="status">当前日志存储不可用。</p>:null}{p.capability&&!p.capability.writeAllowed?<p role="status">当前身份没有日志写入权限。</p>:null}
  <div className="workflow-log-actions"><button disabled={p.busy||!p.capability?.available||!p.capability?.writeAllowed||Boolean(p.pendingId)} onClick={p.write}>写入日志样本</button>{p.pendingId?<><button disabled={p.busy} onClick={p.query}>查询原回执</button><button disabled={p.busy||p.missing||!p.capability?.writeAllowed} onClick={p.verify}>验证日志批次</button></>:null}{p.missing?<><button disabled={p.busy} onClick={p.resubmit}>重发原请求</button><button disabled={p.busy} onClick={p.dismiss}>放弃本次确认</button></>:null}{r?<button disabled={p.busy||!p.capability?.readAllowed} onClick={p.read}>回读日志记录</button>:null}</div>
  {p.pendingId?<p role="status">原请求 <code>{p.pendingId}</code>{p.missing?' 尚未找到；重发使用原内容。放弃不会取消服务器写入。':' 的结果待确认。'}</p>:null}{p.error?<p role="alert">{p.error}</p>:null}{p.notice?<p role="status">{p.notice}</p>:null}
  {r?<article className="workflow-log-receipt"><strong>{states[r.state]}</strong><span>确认 {r.confirmed} · 失败 {r.failed} · 未知 {r.unknown} · 过滤 {r.filtered}</span><small>请求 <code>{r.requestId}</code> · v{r.revision}</small><time>{new Date(r.updatedAt).toLocaleString()}</time></article>:null}
  {p.data?<div className="workflow-log-data"><p role="status">本次回读 {p.data.records.length}/{p.data.expectedRecords} 条 · {p.data.complete?'完整批次匹配':'批次尚未完整匹配'} · {new Date(p.data.readAt).toLocaleString()}</p>{p.data.records.map(row=><article key={row.index}><header><time>{row.eventTime}</time><span>{row.severityText??'未提供级别'}</span></header><pre>{row.body}</pre><dl><dt>服务</dt><dd>{row.serviceName??'未提供'}</dd><dt>Trace ID</dt><dd>{row.traceId??'未提供'}</dd><dt>Span ID</dt><dd>{row.spanId??'未提供'}</dd></dl></article>)}</div>:null}
  {p.records.length?<details><summary>最近写入记录 · {p.records.length}{p.truncated?'（部分）':''}</summary><ul>{p.records.map(row=><li key={row.requestId}><button disabled={p.busy||Boolean(p.pendingId)} onClick={()=>p.select(row)}><span>{states[row.state]} · {new Date(row.createdAt).toLocaleString()}</span><code>{row.requestId}</code></button></li>)}</ul></details>:null}
 </section>
}
