import {ALERT_KINDS,type AlertKind,type AlertStatus,type AlertConfiguration,type AlertCommand} from '../../api/workflow-quality-alerts.ts'
import './workflow-quality-alerts.css'
export type AlertForm={windowSeconds:string;enabled:Record<AlertKind,boolean>;thresholds:Record<AlertKind,string>}
export const ALERT_LABELS:Record<AlertKind,string>={SOURCE_FAILURES:'连续来源失败',OUTPUT_REJECTIONS:'连续输出拒绝',QUEUE_WAIT:'排队时间峰值',TASK_FAILURE:'当前任务失败'}
const states={TRIGGERED:'已触发',NORMAL:'未达阈值',UNAVAILABLE:'无法评估'}
const reasons:Record<string,string>={NO_DATA:'区间内没有观测',MISSING_MEASUREMENT:'缺少实测证据',HISTORY_TRUNCATED:'历史已截断',NO_CURRENT_TASK:'没有当前任务',AMBIGUOUS_ORDER:'观测顺序无法确定'}
export function WorkflowQualityAlertsPanel(p:{configuration:AlertConfiguration|null;report:AlertStatus|null;loaded:boolean;form:AlertForm;dirty:boolean;busy:boolean;pending:AlertCommand|null;missing:boolean;error:string;notice:string;change:(v:AlertForm)=>void;load:()=>void;save:()=>void;cancel:()=>void;query:()=>void;resend:()=>void;dismiss:()=>void}){
 const blocked=p.busy||Boolean(p.pending)
 return <section className="workflow-quality-alerts" aria-label="质量阈值"><header><h3>质量阈值</h3><button disabled={blocked||p.dirty} onClick={p.load}>刷新阈值</button></header><p className="workflow-alert-hint">只保存阈值并进行只读评估，不发送通知或执行动作。</p>{p.error?<p role="alert">{p.error}</p>:null}{p.notice?<p role="status">{p.notice}</p>:null}{p.busy?<p role="status">正在处理阈值请求…</p>:null}
 {p.pending?<div className="workflow-alert-pending"><p>配置结果待确认 · <code>{p.pending.requestId}</code></p><button disabled={p.busy} onClick={p.query}>查询配置回执</button>{p.missing?<><button disabled={p.busy} onClick={p.resend}>原样重发配置</button><button disabled={p.busy} onClick={p.dismiss}>放弃本次确认</button></>:null}</div>:null}
 {p.loaded?<><p>{p.configuration?'配置 v'+p.configuration.editVersion+' · '+(p.configuration.rules.length?'已启用 '+p.configuration.rules.length+' 条规则':'规则已停用'):'尚未配置阈值'}</p><form onSubmit={e=>{e.preventDefault();p.save()}}><label className="workflow-alert-window">统计区间（秒）<input aria-label="阈值统计区间" type="number" min={60} max={86400} step={1} value={p.form.windowSeconds} disabled={blocked} onChange={e=>p.change({...p.form,windowSeconds:e.target.value})}/></label><div className="workflow-alert-rule-list">{ALERT_KINDS.map(kind=><div className="workflow-alert-rule" key={kind}><label><input type="checkbox" aria-label={'启用'+ALERT_LABELS[kind]} checked={p.form.enabled[kind]} disabled={blocked} onChange={e=>p.change({...p.form,enabled:{...p.form.enabled,[kind]:e.target.checked}})}/>{ALERT_LABELS[kind]}</label>{kind==='TASK_FAILURE'?<span>失败时触发</span>:<label>达到<input aria-label={ALERT_LABELS[kind]+'阈值'} type="number" min={1} max={kind==='QUEUE_WAIT'?3600000:20} step={1} value={p.form.thresholds[kind]} disabled={blocked||!p.form.enabled[kind]} onChange={e=>p.change({...p.form,thresholds:{...p.form.thresholds,[kind]:e.target.value}})}/>{kind==='QUEUE_WAIT'?'ms':'次'}</label>}</div>)}</div><footer><button type="submit" disabled={blocked||!p.dirty}>保存规则</button><button type="button" disabled={blocked||!p.dirty} onClick={p.cancel}>撤销修改</button></footer></form></>:null}
 {p.report?.configuration?.rules.length?<><p>统计区间：<time>{p.report.from}</time> — <time>{p.report.till}</time></p><div className="workflow-alert-table" tabIndex={0} role="region" aria-label="阈值结果表"><table><thead><tr><th>规则</th><th>结果</th><th>实测值</th><th>依据</th></tr></thead><tbody>{p.report.evaluations.map(e=><tr key={e.kind} data-state={e.state}><td>{ALERT_LABELS[e.kind]}</td><td>{states[e.state]}</td><td>{e.value===null?'—':e.value+(e.unit==='MILLISECONDS'?' ms':'')}</td><td>{e.reason?reasons[e.reason]:e.sampleCount+' 次实测'}{e.missingCount?<small>缺失 {e.missingCount}</small>:null}{e.truncated?<small>有更早记录</small>:null}{e.evidenceIds.length?<details><summary>查看依据 UUID</summary>{e.evidenceIds.map(id=><code key={id}>{id}</code>)}</details>:null}</td></tr>)}</tbody></table></div></>:null}
 </section>
}
